const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'../assets/simulator-v2');
function runtime(){const window={PhoneBridgerVideoPlaylist:[{},{}]};const sandbox={window};vm.createContext(sandbox);for(const name of ['stories.js','creator-model.js','data.js','state.js','ui.js','creator-ui.js','apps.js'])vm.runInContext(fs.readFileSync(path.join(base,name),'utf8'),sandbox);return window;}
test('every home icon and nested application view renders against the real seed',()=>{const w=runtime(),m=w.PhoneBridgerState.create();const states=Object.keys(w.PhoneBridgerUI.brandNames).map(app=>({app}));states.push({app:'whatsapp',thread:'alex'},{app:'whatsapp',tab:'Updates'},{app:'whatsapp',tab:'Calls'},{app:'gmail',page:'compose',draft:'draft-1'},{app:'gmail',thread:'mail-thread-2'},{app:'gmail',folder:'trash'},{app:'files',page:'home'},{app:'files',folder:'Downloads'},{app:'drive',folder:'Team project'},{app:'drive',driveTab:'Computers'},{app:'photos',photo:'photo-lake'},{app:'news',article:'article-workspaces'},{app:'google',query:'proposal'},{app:'sheets',sheet:'sheet-1'},{app:'sheets',sheet:'sheet-4'},{app:'docs',document:'text-1'},{app:'youtube',video:0},...['connection','mouse','audio','files','help'].map(pbPage=>({app:'phonebridger',pbPage})),...m.data.files.map(f=>({app:'files',preview:f.id})));for(const key of ['left','right','pc'])for(const u of states){const html=w.PhoneBridgerApps.render({m,u:{...u},key});assert.ok(html.length>20,`${key}: ${JSON.stringify(u)}`);assert.ok(!/\bundefined\b/.test(html),`${key}: ${JSON.stringify(u)}`);}});
test('all visible control actions have a controller implementation and media paths resolve',()=>{const w=runtime(),m=w.PhoneBridgerState.create(),controller=fs.readFileSync(path.join(base,'simulator.js'),'utf8');for(const app of Object.keys(w.PhoneBridgerUI.brandNames)){const html=w.PhoneBridgerApps.render({m,u:{app},key:'left'});for(const match of html.matchAll(/data-sim-action="([^"]+)"/g))assert.ok(controller.includes(`case '${match[1]}'`),`${app}: ${match[1]}`);for(const match of html.matchAll(/src="assets\/simulator-v2\/([^\"]+)"/g))assert.ok(fs.existsSync(path.join(base,match[1])),match[1]);}for(let i=1;i<=3;i++)assert.ok(fs.statSync(path.join(base,`media/voice-${i}.wav`)).size>1000);});
test('user content is escaped in chat, articles, document previews and form values',()=>{const w=runtime(),m=w.PhoneBridgerState.create();m.data.messages[0].text='<img src=x onerror=alert(1)>';const html=w.PhoneBridgerApps.render({m,u:{app:'whatsapp',thread:'alex'},key:'left'});assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));m.data.drafts[0].subject='" onfocus="oops';const draft=w.PhoneBridgerApps.render({m,u:{app:'gmail',page:'compose',draft:'draft-1'},key:'right'});assert.ok(draft.includes('&quot; onfocus=&quot;oops'));});
test('eight creator sections render real shared records, safe content and implemented controls',()=>{
  const w=runtime(),m=w.PhoneBridgerState.create(),controller=fs.readFileSync(path.join(base,'creator-ui.js'),'utf8');
  m.data.creator.profile.name='<img src=x onerror=alert(1)>';
  for(const creatorTab of ['Overview','Links','Content','Referrals','Earnings','Payouts','Media kit','Settings']){
    const html=w.PhoneBridgerApps.render({m,u:{app:'creators',creatorTab},key:'pc'});
    assert.ok(html.includes('Demo program'));assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('undefined'));
    for(const match of html.matchAll(/data-sim-action="(creator-[^"]+)"/g))assert.ok(controller.includes(`case '${match[1]}'`),match[1]);
    for(const match of html.matchAll(/src="assets\/([^\"]+)"/g))assert.ok(fs.existsSync(path.resolve(base,'..',match[1])),match[1]);
  }
  const html=w.PhoneBridgerApps.render({m,u:{app:'creators',creatorTab:'Settings',creatorFormDraft:{name:'Draft name'}},key:'pc'});
  assert.ok(html.includes('value="Draft name"'));
});
