const {test}=require('node:test');
const assert=require('node:assert/strict');
const {create}=require('../assets/simulator-v2/state.js');
test('seed is independent and every attachment resolves to shared content',()=>{const a=create(),b=create();assert.equal(a.data.files.length,36);assert.equal(a.data.messages.length,90);assert.equal(a.data.mail.length,30);a.data.contacts[0].name='Changed';assert.equal(b.contact('alex').name,'Alex');for(const msg of b.data.messages)if(msg.attachment)assert.ok(b.file(msg.attachment));for(const mail of b.data.mail)for(const id of mail.attachments)assert.ok(b.file(id));});
test('chat replies use active time and reset cancels pending work',()=>{const m=create();const msg=m.sendMessage('alex','Where is the proposal?');assert.equal(msg.status,'sending');m.tick(30000,false);assert.equal(msg.status,'sending');m.tick(700);assert.equal(msg.status,'delivered');assert.equal(m.data.threads[0].typing,true);m.tick(5000);assert.equal(msg.status,'read');assert.ok(m.data.messages.some(x=>x.from==='alex'&&x.text.includes('email')));m.reset();m.tick(20000);assert.equal(m.data.messages.length,90);assert.equal(m.pending,0);});
test('mail validates, undo restores draft and cancels the reply',()=>{const m=create();const bad=m.newDraft({to:'nobody@test.invalid',text:'Hello'});assert.ok(m.sendMail(bad.id).error);const draft=m.newDraft({to:'alex',subject:'Proposal',text:'Here is the file.',attachments:['doc-1']});const sent=m.sendMail(draft.id).email;assert.equal(sent.folder,'sent');const restored=m.undoMail(sent.id);assert.deepEqual(restored.attachments,['doc-1']);m.tick(15000);assert.ok(!m.data.mail.some(x=>x.thread===sent.thread));});
test('mail reply stays in its thread and completes the proposal story',()=>{const m=create(),d=m.newDraft({to:'alex',subject:'Proposal',text:'Here it is.',attachments:['doc-1']});const sent=m.sendMail(d.id).email;m.tick(11000);assert.equal(m.data.mail.filter(x=>x.thread===sent.thread).length,2);assert.equal(m.data.scenario.proposal,true);assert.ok(m.data.notifications.some(x=>x.app==='gmail'));});
test('transfers are queued, cancellation leaves no copy and conflict requires resolution',()=>{const m=create(),t=m.transfer(['doc-1'],'drive','right','Downloads');m.tick(2000);assert.equal(t.progress,50);m.transferAction(t.id,'pause');m.tick(3000);assert.equal(t.progress,50);m.transferAction(t.id,'cancel');m.tick(5000);assert.ok(!m.localFiles('right').some(x=>x.file==='doc-1'));const a=m.transfer(['doc-1'],'drive','right','Downloads');m.tick(4000);assert.equal(a.status,'complete');const b=m.transfer(['doc-1'],'drive','right','Downloads');m.tick(4000);assert.equal(b.status,'conflict');m.transferAction(b.id,'resume','keep');m.tick(1);assert.equal(b.status,'complete');assert.ok(m.localFiles('right').some(x=>x.name==='Proposal (2).pdf'));});
test('copy and replace preserve the shared content ID and local isolation',()=>{const m=create();m.addCopy('photo-lake','right','Images','keep');assert.ok(m.localFiles('right').some(x=>x.file==='photo-lake'));assert.ok(!m.localFiles('left').some(x=>x.file==='photo-lake'));m.addCopy('photo-lake','right','Images','replace');assert.equal(m.localFiles('right').filter(x=>x.file==='photo-lake').length,1);});
test('sheet formulas, cycles, undo and redo operate on the shared cell model',()=>{const m=create(),s=m.data.sheets[0],w=s.worksheets[0];assert.equal(m.formula(w,5,4),2650);m.cell(s.id,w.id,1,4,'100');assert.equal(m.formula(w,5,4),1550);m.sheetHistory('undo');assert.equal(m.formula(w,5,4),2650);m.sheetHistory('redo');assert.equal(m.formula(w,5,4),1550);m.cell(s.id,w.id,1,0,'=A2');assert.equal(m.formula(w,1,0),'#CYCLE!');m.cell(s.id,w.id,1,0,'=BOGUS()');assert.equal(m.formula(w,1,0),'#ERROR!');});
test('quiet pauses activity and the demo clock wraps minutes correctly',()=>{const m=create();m.start();m.data.quiet=true;m.tick(60000);assert.equal(m.clock,'10:15');m.data.quiet=false;m.tick(3600000);assert.equal(m.clock,'11:15');});

test('a shared photo receives two replies from different group members',()=>{const m=create();m.sendMessage('group-2','Here is my favorite.','photo-studio-detail');m.tick(5000);m.tick(1600);const replies=m.data.messages.slice(-2);assert.deepEqual(replies.map(x=>x.from),['mia','oliver']);assert.ok(replies.every(x=>x.thread==='group-2'));});

test('sharing an article creates one invitation and resetting cancels follow-up work',()=>{const m=create();m.sendMessage('group-1','Please read demo://article-workspaces');m.tick(5000);m.tick(7000);assert.equal(m.data.mail.filter(x=>x.subject==='Let’s discuss your article').length,1);m.sendMessage('group-1','Another look at demo://article-workspaces');m.tick(20000);assert.equal(m.data.mail.filter(x=>x.subject==='Let’s discuss your article').length,1);m.reset();m.tick(30000);assert.equal(m.data.mail.length,30);});

test('repeated transfer commands reuse the pending operation and invalid content is rejected',()=>{const m=create();const a=m.transfer(['photo-workspace'],'pc','right','Downloads');assert.equal(m.transfer(['photo-workspace'],'pc','right','Downloads'),a);assert.equal(m.data.transfers.length,1);assert.equal(m.transfer(['not-a-file'],'pc','right','Downloads'),null);m.tick(4000);assert.equal(m.localFiles('right','Downloads').filter(f=>f.file==='photo-workspace').length,1);assert.equal(m.localFiles('left','Downloads').filter(f=>f.file==='photo-workspace').length,0);});

test('oversized formula ranges fail immediately and every article has substantial unique content',()=>{const m=create(),ws=m.data.sheets[0].worksheets[0];m.cell('sheet-1',ws.id,0,0,'=SUM(A1:XFD1048576)');assert.equal(m.formula(ws,0,0),'#RANGE!');const firstParagraphs=new Set();for(const story of m.data.articles){const words=story.sections.map(s=>s.text).join(' ').split(/\s+/).length;assert.ok(words>=350&&words<=500,story.id);firstParagraphs.add(story.sections[0].text);}assert.equal(firstParagraphs.size,8);});

test('opening a chat clears unread notifications without losing its messages',()=>{const m=create();m.sendMessage('alex','Hello Alex');m.tick(5000);const count=m.data.messages.length;assert.ok(m.data.notifications.some(n=>n.app==='whatsapp'&&!n.read));m.readThread('alex');assert.equal(m.data.messages.length,count);assert.equal(m.data.threads.find(t=>t.id==='alex').unread,0);assert.ok(m.data.notifications.filter(n=>n.app==='whatsapp'&&n.target.thread==='alex').every(n=>n.read));});

test('mail thread actions stay consistent and restoring trash preserves the original folders',()=>{const m=create(),draft=m.newDraft({to:'alex',subject:'A shared thread',text:'Hello Alex'});const sent=m.sendMail(draft.id).email;m.tick(11000);m.mailAction(sent.thread,'star');assert.ok(m.data.mail.filter(x=>x.thread===sent.thread).every(x=>x.star));m.mailAction(sent.thread,'read');assert.ok(m.data.notifications.filter(n=>n.app==='gmail'&&n.target.thread===sent.thread).every(n=>n.read));m.mailAction(sent.thread,'delete');assert.ok(m.data.mail.filter(x=>x.thread===sent.thread).every(x=>x.folder==='trash'));m.mailAction(sent.thread,'restore');assert.deepEqual(m.data.mail.filter(x=>x.thread===sent.thread).map(x=>x.folder),['sent','inbox']);});

test('an idle world does not keep growing after its introductory events',()=>{const m=create();m.start();for(let i=0;i<2400;i++)m.tick(500);const counts=[m.data.messages.length,m.data.mail.length,m.data.notifications.length];assert.equal(m.pending,0);assert.ok(counts[0]<=96);for(let i=0;i<2400;i++)m.tick(500);assert.deepEqual([m.data.messages.length,m.data.mail.length,m.data.notifications.length],counts);assert.equal(m.pending,0);m.reset();assert.equal(m.data.messages.length,90);assert.equal(m.data.notifications.length,0);});
