import assert from'node:assert/strict';import{request}from'node:http';import{execFile}from'node:child_process';import{promisify}from'node:util';import{writeFile,readFile}from'node:fs/promises';import{randomUUID}from'node:crypto';import path from'node:path';
const cwd=path.resolve(import.meta.dirname,'../../output/akmenas-production'),base='http://127.0.0.1:8886',id=randomUUID(),name='AUDIT-'+id;
const config=JSON.parse(await readFile(path.join(cwd,'dist/server/wrangler.json'),'utf8'));assert.equal(config.send_email.length,0);
function post(url,body,extra={}){return new Promise((resolve,reject)=>{const req=request(base+url,{method:'POST',agent:false,headers:{origin:base,referer:base+'/kontaktai','content-type':'application/x-www-form-urlencoded','content-length':Buffer.byteLength(body),...extra}},r=>{let text='';r.setEncoding('utf8');r.on('data',p=>text+=p);r.on('end',()=>resolve({status:r.statusCode,text}));});req.on('error',reject);req.end(body);});}
const valid=new URLSearchParams({name,email:'info@pinet.lt',message:'AUDIT_SELF_TEST '+id+'; tik sintetinis vietinis formos bandymas.',consent:'yes',website:''}).toString(),checks={};
for(const [key,body,headers,status] of [['shortName',new URLSearchParams({name:'A',email:'info@pinet.lt',message:'Pakankamai ilga testine zinute',consent:'yes'}).toString(),{},400],['origin',valid,{origin:'https://outside.invalid'},403],['size','x='.padEnd(10010,'a'),{},400],['honeypot',valid.replace('website=','website=bot'),{},200],['unknownHost','',{host:'unknown-domain.example'},404],['badEmail',valid.replace('info%40pinet.lt','bad-email'),{},400],['missingConsent',valid.replace('consent=yes','consent=no'),{},400]]){checks[key]=(await post('/uzklausa',body,headers)).status;assert.equal(checks[key],status,key);}
const accepted=await post('/uzklausa',valid);assert.equal(accepted.status,200);assert.match(accepted.text,/tik šiame kompiuteryje/);checks.accepted=200;
const run=promisify(execFile);async function sql(command){const{stdout}=await run(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--command',command,'--json'],{cwd,maxBuffer:512000});return JSON.parse(stdout).flatMap(v=>v.results||[]);}
const rows=await sql(`SELECT id,site_id,source_path,status FROM niche_leads WHERE name='${name}' AND site_id='akmenas'`);assert.equal(rows.length,1);assert.equal(rows[0].source_path,'/kontaktai');assert.equal(rows[0].status,'new');assert.match(rows[0].id,/^[a-f0-9-]{36}$/);
await sql(`DELETE FROM niche_leads WHERE id='${rows[0].id}' AND name='${name}' AND site_id='akmenas'`);const after=await sql(`SELECT COUNT(*) as n FROM niche_leads WHERE name='${name}' AND site_id='akmenas'`);assert.equal(after[0].n,0);
const evidence={at:new Date().toISOString(),siteId:'akmenas',synthetic:true,base,checks,durableStored:true,storedStatus:'new',sourcePath:'/kontaktai',smtpDisabled:true,voiceCoreIndependent:true,syntheticRecordRemoved:true,mail:'This is a durable local test. Shared SMTP/INBOX evidence remains scoped to MAIL_CORE 2026-09-30, not an akmenas production delivery.'};await writeFile(path.join(import.meta.dirname,'FORM-VERIFICATION.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));
