import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const repo=path.resolve(import.meta.dirname,'../../..'),output=path.join(repo,'sites/madbeauty/cloudflare/output'),privateRoot=path.join(output,'next19-private'),sha=b=>createHash('sha256').update(b).digest('hex');
const mode=process.argv[2];assert.ok(['native','hosted','live-before','live-after'].includes(mode));
const manifest=JSON.parse(await readFile(path.join(privateRoot,'manifest.json'))),raw=await readFile(path.join(output,'content-package.json')),pkg=JSON.parse(raw),oldPath='C:/Users/Lenovo/Documents/Nisiniai_puslapiai/madbeauty-calendar-20261009/sites/madbeauty/publication-20261009/release/content-package.json',old=JSON.parse(await readFile(oldPath)),baselineSha='bb1b90aa2929d9cc63607afb9b77977203eb9bc45031a6c8ae5e8775ce378511';
assert.equal(sha(raw),manifest.packageSha256);assert.equal(sha(await readFile(oldPath)),baselineSha);
assert.equal(pkg.pages.length,58);assert.equal(old.pages.length,39);for(const p of old.pages)assert.deepEqual(pkg.pages.find(x=>x.id===p.id),p,p.slug+' unchanged snapshot');
const additional=pkg.pages.filter(p=>!old.pages.some(x=>x.id===p.id));assert.equal(additional.length,19);assert.ok(additional.every(p=>Date.parse(p.publishAt)>Date.now()));assert.equal(new Set(additional.map(p=>p.publishAt)).size,19);
const writerRoot=path.resolve(repo,'../madbeauty-next30-20261009/sites/madbeauty/content-next30-20261009'),delivery=JSON.parse(await readFile(path.join(writerRoot,'DELIVERY.json'))),selection=JSON.parse(await readFile(path.join(writerRoot,'SELECTION.json'))),reviews=JSON.parse(await readFile(path.join(writerRoot,'CLAIM-REVIEW.json')));
for(const planId of delivery.specialistPending){const selected=selection.pages.find(x=>x.planId===planId);assert.ok(selected);assert.ok(!pkg.pages.some(x=>x.id===selected.pageId),planId+' remains private');}
for(const p of additional){const review=reviews.pages.find(x=>x.pageId===p.id);assert.ok(review);assert.equal(review.reviewRevisionHash,p.revisionHash,p.slug+' actual revision-bound review');assert.ok(!review.remainingChecks.length,p.slug+' unfinished claims');}
const preservation={oldPages:39,oldSnapshotsUnchanged:true,newApprovedPages:19,specialistExcluded:delivery.specialistPending.length,additional:additional.map(p=>({id:p.id,slug:p.slug,publishAt:p.publishAt,revisionHash:p.revisionHash}))};
const media=[...new Set(pkg.pages.flatMap(p=>p.media.map(m=>m.src)))];assert.equal(media.length,275);const oldMedia=[...new Set(old.pages.flatMap(p=>p.media.map(m=>m.src)))];assert.equal(oldMedia.length,180);
for(const src of oldMedia){const a=await readFile(path.join(output,'assets-release',src)),b=await readFile(path.join(path.dirname(oldPath),'assets',path.basename(src)));assert.equal(sha(a),sha(b),src);}
const future=pkg.pages.filter(p=>p.type==='guide'&&Date.parse(p.publishAt)>Date.now()).sort((a,b)=>Date.parse(a.publishAt)-Date.parse(b.publishAt));assert.equal(future.length,51);
const record={at:new Date().toISOString(),mode,runtimeSource:manifest.runtimeSource,coreSource:manifest.coreSource,rendererSha256:manifest.rendererSha256,producerReviewedRendererSha256:manifest.producerReviewedRendererSha256,packageSha256:manifest.packageSha256,artifactSha256:mode==='native'||mode==='hosted'?manifest.qaArtifactSha256:manifest.productionArtifactSha256,contentComparison:preservation,publicationCases:[],gateChecks:[],assetChecks:[],scope:'HTTP content acceptance. Synthetic private QA clock applies only to native/hosted cases; production uses real Date.now. No provider, booking, SMTP or migration acceptance.'};
await writeFile(path.join(privateRoot,mode+'-manifest.json'),JSON.stringify({...record,state:'planned',plannedPublicationStates:mode==='native'||mode==='hosted'?102:0},null,2));
let mf;const secrets=JSON.parse(await readFile(path.join(privateRoot,'qa-secrets.private.json'))),isQA=['native','hosted'].includes(mode),origin=isQA?manifest.qaOrigin:'https://madbeauty.lt',expectedSha=mode==='live-before'?baselineSha:manifest.packageSha256;
if(mode==='native'){const {Miniflare}=await import(pathToFileURL(path.join(repo,'../madbeauty-calendar-core-20261009/node_modules/miniflare/dist/src/index.js')));const config=JSON.parse(await readFile(path.join(privateRoot,'qa-wrangler.json')));mf=new Miniflare({modules:true,script:await readFile(path.join(privateRoot,'qa-worker.mjs'),'utf8'),compatibilityDate:config.compatibility_date,compatibilityFlags:config.compatibility_flags,durableObjects:{PLATFORM:{className:'CalendarSource',useSQLite:true}},bindings:{...config.vars,...secrets},serviceBindings:{ASSETS:async req=>{try{return new Response(await readFile(path.join(output,'assets-release',new URL(req.url).pathname)));}catch(e){if(e.code!=='ENOENT')throw e;return new Response('Not found',{status:404});}}}});}
const request=async(route,now,extra={})=>{const headers={...(isQA?{Authorization:'Bearer '+secrets.CALENDAR_ACCESS_KEY}:{}),...(now?{'X-Calendar-Acceptance-Now':String(now)}:{}),...extra.headers},url=route.startsWith('http')?route:origin+route;if(mf)return mf.dispatchFetch(url,{redirect:'manual',...extra,headers});for(let attempt=1;attempt<=2;attempt++){try{return await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000),...extra,headers});}catch(e){console.log(JSON.stringify({networkFailure:{route,clock:now||null,attempt,name:e.name,cause:e.cause?.code}}));if(attempt===2)throw Error('HTTP transport failed for '+route,{cause:e});}}};
const text=async(route,now)=>{const r=await request(route,now);assert.equal(r.status,200,route);assert.equal(r.headers.get('x-madbeauty-content-sha256'),expectedSha,route);return r.text();};
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{
 if(isQA){const gates=[['anonymous','/content.json',{headers:{Authorization:''}}],['wrong-key','/content.json',{headers:{Authorization:'Bearer bad'}}],['unknown-host','https://foreign.test/content.json',{}],['mutation','/content.json',{method:'POST'}],['api','/api/madbeauty/session',{}],['unknown-clock','/content.json',{headers:{'X-Calendar-Acceptance-Now':'1'}}],['internal-manifest','/release-manifest.json',{}],['internal-output','/cloudflare/output/content-package.json',{}]].filter(([name])=>mode==='native'||name!=='unknown-host');if(mode==='hosted')record.unperformed=[{check:'unknown-host',reason:'Native Worker URL rejection accepted separately. An unregistered external hostname does not resolve to this isolated Worker; no DNS or TLS bypass used.'}];for(const [name,route,extra]of gates){assert.equal((await request(route,null,extra)).status,404,name);record.gateChecks.push(name);}
  const health=await(await request('/__calendar/health')).json();assert.equal(health.runtime,manifest.runtimeSource);assert.equal(health.core,manifest.coreSource);assert.equal(health.packageSha256,expectedSha);assert.equal(health.smtp,false);
  for(const p of future){for(const now of [Date.parse(p.publishAt)-1,Date.parse(p.publishAt)]){const due=pkg.pages.filter(x=>Date.parse(x.publishAt)<=now),ids=due.map(x=>x.id).sort(),data=JSON.parse(await text('/content.json',now));assert.deepEqual(data.pages.map(x=>x.id).sort(),ids,p.slug+' public JSON');
    const route='/'+p.slug,r=await request(route,now),html=await r.text(),visible=now===Date.parse(p.publishAt);assert.equal(r.status,visible?200:404,route);assert.equal(r.headers.get('x-madbeauty-content-sha256'),expectedSha);
    if(visible){assert.ok(html.includes('<h1>'+escape(p.title)+'</h1>'));assert.ok(html.includes('<time datetime="'+p.publishAt+'">'));const scripts=[...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].flatMap(m=>JSON.parse(m[1]));const article=scripts.flatMap(x=>x['@graph']||[x]).find(x=>x['@type']==='Article');assert.ok(article,'SSR Article');assert.equal(article.datePublished,p.publishAt);assert.equal(data.pages.find(x=>x.id===p.id).dates.published,p.publishAt);}
    else{assert.ok(!html.includes(escape(p.title)));assert.ok(!html.includes('application/ld+json'));}
    for(const route of ['/sitemap.xml','/llms.txt','/llms-full.txt']){const body=await text(route,now);for(const page of pkg.pages.filter(x=>x.type==='guide'))assert.equal(body.includes('https://madbeauty.lt/'+page.slug),ids.includes(page.id),route+':'+page.slug);}
    const publicMedia=new Set(due.flatMap(x=>x.media.map(m=>m.src)));for(const m of p.media){const r=await request(m.src,now);assert.equal(r.status,publicMedia.has(m.src)?200:404,m.src);if(publicMedia.has(m.src))assert.equal(sha(Buffer.from(await r.arrayBuffer())),sha(await readFile(path.join(output,'assets-release',m.src))),m.src);}
    record.publicationCases.push({slug:p.slug,now:new Date(now).toISOString(),visible,publicPages:ids.length,media:p.media.length});
  }await writeFile(path.join(privateRoot,mode+'-progress.json'),JSON.stringify({state:'in-progress',publicationCases:record.publicationCases},null,2));console.log('publication boundary accepted '+p.slug);}
 }
 const now=Date.now(),due=pkg.pages.filter(p=>Date.parse(p.publishAt)<=now),current=JSON.parse(await text('/content.json'));assert.deepEqual(current.pages.map(p=>p.id).sort(),due.map(p=>p.id).sort());assert.equal(due.length,7);
 for(const p of future){const r=await request('/'+p.slug);assert.equal(r.status,404,p.slug);}
 const paths=JSON.parse(await readFile(path.join(output,'asset-paths.json'))),publicMedia=new Set(due.flatMap(p=>p.media.map(m=>m.src)));let served=0,blocked=0;
 for(const route of paths){if(mode==='live-before'&&route.startsWith('/content-assets/')&&!oldMedia.includes(route))continue;const visible=!route.startsWith('/content-assets/')||publicMedia.has(route);let r=await request(route),redirect=null;if(r.status===307){const destination=new URL(r.headers.get('location'),origin);assert.equal(destination.origin,origin);assert.equal(decodeURIComponent(destination.pathname),route);redirect=destination.pathname;await r.body?.cancel();r=await request(redirect);}assert.equal(r.status,visible?200:404,route);if(visible){assert.equal(sha(Buffer.from(await r.arrayBuffer())),sha(await readFile(path.join(output,'assets-release',route))),route);served++;}else blocked++;record.assetChecks.push({path:route,visible,redirect});}
 for(const p of due){const r=await request(p.slug?'/'+p.slug:'/');assert.equal(r.status,200,p.slug);assert.ok((await r.text()).includes(escape(p.title)));}
 for(const route of ['/sitemap.xml','/llms.txt','/llms-full.txt']){const body=await text(route);for(const p of pkg.pages.filter(x=>x.type==='guide'))assert.equal(body.includes('https://madbeauty.lt/'+p.slug),Date.parse(p.publishAt)<=now,route+':'+p.slug);}
 if(!isQA){for(const route of ['/release-manifest.json','/cloudflare/output/content-package.json','/publication-20261009/READY-GUIDES-DATE-CHANGES.json','/gidai/unknown-calendar-proof'])assert.equal((await request(route)).status,404,route);for(const url of ['https://www.madbeauty.lt/gidai','http://madbeauty.lt/gidai']){const r=await request(url);assert.ok([301,308].includes(r.status));assert.equal(r.headers.get('location'),'https://madbeauty.lt/gidai');}assert.ok((await text('/robots.txt')).includes('Sitemap: https://madbeauty.lt/sitemap.xml'));}
 record.state='PASS';record.finishedAt=new Date().toISOString();record.currentProjection={pages:due.length,futureBlocked:future.length,assets:record.assetChecks.length,served,blocked};await writeFile(path.join(privateRoot,mode+'-proof.json'),JSON.stringify(record,null,2));console.log(JSON.stringify({mode,state:record.state,publicationStates:record.publicationCases.length,gateChecks:record.gateChecks.length,...record.currentProjection}));
}finally{if(mf)await mf.dispose();}
