import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../cloudflare/output/next19-private'),phase=process.argv[2];assert.ok(['before','predeploy','after'].includes(phase));
const raw=await readFile('C:/Users/Lenovo/AppData/Roaming/xdg.config/.wrangler/config/default.toml','utf8'),token=raw.match(/^oauth_token\s*=\s*"([^"]+)"/m)?.[1];assert.ok(token,'Normal CLI authentication required');
const account='d102163f74a45ab6d33bca786ce281ec',base='https://api.cloudflare.com/client/v4/accounts/'+account;
const get=async route=>{const r=await fetch(base+route,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(30000)}),data=await r.json();assert.ok(data.success,JSON.stringify(data.errors));return data.result;};
const worker='madbeauty-platform-preview',settings=await get('/workers/scripts/'+worker+'/settings'),domains=await get('/workers/domains'),deployments=await get('/workers/scripts/'+worker+'/deployments'),scripts=await get('/workers/scripts'),metadata=scripts.find(s=>s.id===worker);assert.ok(metadata);
const config={migrationTag:metadata.migration_tag,compatibilityDate:settings.compatibility_date,compatibilityFlags:settings.compatibility_flags,usageModel:settings.usage_model,bindings:settings.bindings.map(b=>({name:b.name,type:b.type,namespaceId:b.namespace_id,className:b.class_name,scriptName:b.script_name,...(b.type==='plain_text'?{text:b.text}:{})})).sort((a,b)=>a.name.localeCompare(b.name)),observability:settings.observability,domains:domains.filter(x=>x.service===worker).map(x=>({hostname:x.hostname,service:x.service,environment:x.environment})).sort((a,b)=>a.hostname.localeCompare(b.hostname))};
assert.equal(config.migrationTag,'v1');const binding=config.bindings.find(b=>b.name==='PLATFORM');assert.equal(binding.namespaceId,'2faf96eedef1425c8d4fc07444cde2f3');assert.equal(binding.className,'MadbeautyPlatform');assert.ok(!config.bindings.some(b=>b.name==='ORGANIZATION_STAGING'));assert.deepEqual(config.domains.map(x=>x.hostname),['madbeauty.lt','www.madbeauty.lt']);
const current=deployments.deployments?.sort((a,b)=>Date.parse(b.created_on)-Date.parse(a.created_on))[0];assert.ok(current);if(phase!=='after')assert.deepEqual(current.versions,[{version_id:'4dbdf361-25c6-4496-97a5-daaed23df201',percentage:100}]);
if(phase==='after'){const log=await readFile(path.join(root,'production-deploy.log'),'utf8'),deployed=log.match(/Current Version ID: ([a-f0-9-]{36})/)?.[1];assert.ok(deployed);assert.deepEqual(current.versions,[{version_id:deployed,percentage:100}]);assert.ok(current.annotations['workers/message'].includes('content-only next19 320a8e0f'));}
if(phase!=='before'){const before=JSON.parse(await readFile(path.join(root,'provider-before.json')));assert.deepEqual(JSON.parse(JSON.stringify(config)),before.config);}
let qa=null;if(phase!=='before'){const r=await get('/workers/scripts/madbeauty-calendar-acceptance-20261009/settings');qa={migrationTag:scripts.find(s=>s.id==='madbeauty-calendar-acceptance-20261009')?.migration_tag,bindings:r.bindings.map(b=>({name:b.name,type:b.type,namespaceId:b.namespace_id,className:b.class_name,scriptName:b.script_name})).sort((a,b)=>a.name.localeCompare(b.name))};const d=qa.bindings.filter(b=>b.namespaceId);assert.equal(d.length,1);assert.equal(d[0].className,'CalendarSource');assert.notEqual(d[0].namespaceId,binding.namespaceId);assert.ok(!qa.bindings.some(b=>b.scriptName||b.name.startsWith('MAIL_')||b.name.startsWith('LEAD_SMTP')));}
const receipt={at:new Date().toISOString(),state:'PASS',account,worker,config,currentDeployment:current,qa};await writeFile(path.join(root,'provider-'+phase+'.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify({phase,state:'PASS',version:current.versions,productionNamespace:binding.namespaceId,qaNamespace:qa?.bindings.find(b=>b.namespaceId)?.namespaceId,secretNames:config.bindings.filter(b=>b.type==='secret_text').map(b=>b.name)}));
