import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
const core='C:/Users/lenovo/Documents/dovanos-memorycasting';
const here=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const pkg=JSON.parse(await fs.readFile(path.join(core,'content-packages/laiptucentras/content-package.json'),'utf8'));
const home=pkg.pages.find(p=>p.type==='home');
const shared=`*{box-sizing:border-box}body{margin:0;color:#203140;background:#f6f6f3;font-family:Manrope,sans-serif}@font-face{font-family:Manrope;src:url('/fonts/laiptucentras/manrope-latin-a30ddcd34970.woff2')}header{display:flex;justify-content:space-between;align-items:center;padding:26px 5%;border-bottom:1px solid #aeb9bf}header b{font-size:24px;letter-spacing:-.03em}nav{display:flex;gap:28px}a{color:inherit;text-underline-offset:.3em}h1{font-size:clamp(42px,5.5vw,78px);line-height:1.04;font-weight:500;letter-spacing:-.035em;margin:0 0 30px;text-wrap:balance}p{line-height:1.7;font-size:18px;max-width:65ch}.action{display:inline-block;padding:16px 24px;background:#203140;color:#fff;text-decoration:none;margin:12px 0 24px}.notice{font-size:15px}img{width:100%;height:100%;object-fit:cover}section{padding:70px 5%}h2{font-size:36px;font-weight:500;letter-spacing:-.025em;max-width:22ch}li{padding:20px 0;border-top:1px solid #aeb9bf;list-style:none;line-height:1.6}ul{padding:0}.bottom{display:grid;grid-template-columns:1fr 1.5fr;gap:70px}.heroA{display:grid;grid-template-columns:1.12fr 1fr;padding:0;background:#203140;color:#f6f6f3;min-height:650px}.heroA img{min-height:650px;object-position:36% center}.heroA .copy{padding:70px 11%}.heroA .action{background:#f6f6f3;color:#203140}.heroA .notice{color:#d8e0e5}.heroB{display:grid;grid-template-columns:1.1fr 1fr;gap:8%;align-items:start}.heroB h1{font-size:64px}.worksheet{border:1px solid #203140;padding:28px}.worksheet label{display:block;padding:18px 0;border-bottom:1px solid #aeb9bf}.smallImage{height:260px;margin-top:28px}.heroC{padding:0;display:grid;grid-template-columns:1fr 1.4fr}.pane{padding:60px;border-right:1px solid #203140;border-bottom:1px solid #203140}.heroC .photo{height:590px}.heroC h1{font-size:66px}.paneDark{background:#203140;color:#fff}@media(max-width:800px){header{padding:20px}nav{display:none}.heroA{display:flex;flex-direction:column}.heroA img{height:360px;min-height:0}.heroA .copy{padding:34px 22px}.heroA h1{font-size:46px}.heroB,.heroC,.bottom{display:block}.heroB h1,.heroC h1{font-size:46px}.heroB{padding:40px 22px}.heroC .photo{height:330px}.pane{padding:32px 22px}.worksheet{margin-top:30px}section{padding:42px 22px}.bottom h2{font-size:32px}}`;
const title=`<h1>${home.title}</h1>`;
const copy=`<p>${home.body[0].text}</p><a class="action" href="#poreikis">Aprašyti laiptų poreikį</a><p class="notice">${home.body[1].text}</p>`;
const photo=`<img src="${home.media[0].src}" alt="${home.media[0].alt}">`;
const bottom=`<section class="bottom"><h2>Kokio darbo reikia jūsų namams?</h2><ul>${home.body[3].items.map(i=>`<li>${i}</li>`).join('')}</ul></section>`;
const studies={
 a:`<main><section class="heroA">${photo}<div class="copy">${title}${copy}</div></section>${bottom}</main>`,
 b:`<main><section class="heroB"><div>${title}${copy}</div><div><div class="worksheet"><h2>Sąmatos apimtis</h2><label>Konstrukcija · įtraukta / neaišku</label><label>Pakopos · įtraukta / neaišku</label><label>Turėklai · įtraukta / neaišku</label><label>Montavimas · įtraukta / neaišku</label></div><div class="smallImage">${photo}</div></div></section>${bottom}</main>`,
 c:`<main><section class="heroC"><div class="pane paneDark">${title}${copy}</div><div class="photo">${photo}</div></section><section class="bottom"><h2>Vienas planas. Aiški darbų apimtis.</h2><ul>${home.body[3].items.map(i=>`<li>${i}</li>`).join('')}</ul></section></main>`
};
for(const [id,body] of Object.entries(studies))await fs.writeFile(path.join(here,`study-${id}.html`),`<!doctype html><html lang="lt"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Laiptų centro kompozicijos tyrimas ${id}</title><style>${shared}</style><header><b>laiptų centras</b><nav><a href="#">Laiptų poreikis</a><a href="#">Gidai</a><a href="#poreikis">Aprašyti poreikį</a></nav></header>${body}</html>`);
createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');const name=url.pathname==='/'?'/study-a.html':url.pathname;const root=name.startsWith('/fonts/')||name.startsWith('/content-assets/')?path.join(core,'public'):here;const file=path.resolve(root,'.'+name);if(!file.startsWith(path.resolve(root)+path.sep)){res.writeHead(403);res.end();return;}const data=await fs.readFile(file);const type={'.html':'text/html; charset=utf-8','.webp':'image/webp','.woff2':'font/woff2'}[path.extname(file)]??'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(data);}catch{res.writeHead(404);res.end();}}).listen(8897,'127.0.0.1',()=>console.log('Design studies 127.0.0.1:8897; local-only, no form sending.'));
