import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base='sites/madbeauty',research='research/madbeauty-implementation',now=new Date().toISOString();
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const write=async(p,d)=>writeFile(p,JSON.stringify(d,null,2)+'\n');
const routes=(await read(research+'/uiux-routes-v1.json')).checks,screens=(await read(research+'/uiux-browser-v1.json')).screens;
const files=['app.mjs','ui.mjs','form-state.mjs','http-adapter.mjs','account-ui.mjs','booking-ui.mjs','public-views.mjs','workspace-ui.mjs','calendar-ui.mjs','service-editor.mjs','chat-ui.mjs','product-trust.mjs','app.css','workspace.css'];
const hashes=Object.fromEntries(await Promise.all(files.map(async f=>[f,createHash('sha256').update(await readFile(base+'/prototype/public/'+f)).digest('hex')])));
const receipt={at:now,reviewer:'same implementing agent',environment:'private loopback preview; fictional QA accounts; no real messages or deployment',routeChecks:routes.length,uniqueRouteSurfaces:new Set(routes.map(r=>r.id)).size,widths:[...new Set(routes.map(r=>r.width))].sort((a,b)=>a-b),failures:routes.filter(r=>r.overflow||r.error||r.h1.length!==1||r.untypedActions),screenshots:screens.length,tests:{backend:'V15 35/35',platform:'V9 30/30',http:'V1 4/4',total:69},lighthouse:await read(research+'/performance-authenticated-v8.json'),sourceSHA256:hashes,limits:['No renewed demo profile/image inspection','DOM width checks are not per-screen pixel or all-state acceptance','Control++ had no effect in IAB; 320/640 CSS-pixel reflow measured, physical 200% zoom unverified','Reduced-motion CSS exists; actual preference emulation unavailable in advertised browser capabilities','Full70/all-state and production launch gates remain unverified'],interventions:['First requested calendar baseline tab had been moved to reports; actual report capture annotated and new dedicated QA tab used','One expiry capture was6 seconds premature; kept as countdown, later expired state confirmed','Guide author-link locator not present in common guide; actual source-defined author route checked separately','Native summary AX button differs from Playwright button selector; corrected to visible summary locator','Additional rounds only for concrete findings: error spanning grid, expired-page h1, duplicate booking back path,320px controls, custom interval display, stable addon drafts']};
await write(research+'/uiux-functional-final-v1.json',receipt);
const matrix=await read(base+'/uiux/SCREEN_STATE_MATRIX.json');matrix.at=now;matrix.currentTests=receipt.tests;matrix.reviewLimits=receipt.limits;
const ownerExcluded=new Set(['public-practitioner','public-venue','public-gallery','public-service-option','professional-gallery']);
const readOnly=new Set(['public-services','public-service-hub','public-city-hub','public-catalog','public-for-business','content-guides','content-guide','content-editorial','content-author','trust-about','trust-how','trust-verification','trust-help','trust-privacy','trust-cookies','trust-terms','trust-cancellation','operator-content','operator-metrics','professional-reports','professional-integrations','professional-settings']);
const set=(screen,state,status,evidence,notes)=>screen.states[state]={status,evidence,notes};
const map={
 'public-search':['search-after','search-empty-after'],
 'booking-services-step':['booking-options-after','booking-repeat-guard'],
 'booking-time-step':['booking-interval-error'],
 'booking-details-step':['booking-auth-recovered','booking-expired-auth'],
 'booking-review-step':['booking-live-hold','booking-hold-expired-confirmed'],
 'booking-confirmation':['booking-confirmation-after'],
 'professional-calendar':['calendar-after','calendar-desktop-after','calendar-320-controls-fixed','calendar-mobile-deliverable','calendar-block-conflict'],
 'professional-clients':['client-validation','client-draft-reload','client-success'],
 'professional-service-editor':['service-addons-required','service-draft-stable-addon-reload'],
 'professional-visit-drawer':['calendar-keyboard-details'],
 'professional-messages':['message-draft-reload']
};
for(const screen of matrix.screens){
 const rows=routes.filter(r=>r.id===screen.id),captures=screens.filter(r=>(map[screen.id]||[]).includes(r.id));
 screen.ownerReviewExcluded=ownerExcluded.has(screen.id);screen.fullStateAcceptance='UNVERIFIED';
 if(screen.ownerReviewExcluded){screen.notes='Not revisited under owner instruction to stop demo profile/image review. Existing implementation and historical evidence retained.';continue;}
 if(readOnly.has(screen.id))set(screen,'success','NA',[],'No mutation on this surface; rendered normal state is recorded separately.');
 if(rows.length||captures.length)set(screen,'normal','PASS',[research+'/uiux-routes-v1.json',research+'/uiux-browser-v1.json'],'Actual route/interaction rendered; width/heading checks do not independently accept every pixel/state.');
 for(const [state,min,max] of [['desktop',1200,Infinity],['tablet',768,1199],['mobile',0,430]])if([...rows,...captures].some(r=>r.width>=min&&r.width<=max))set(screen,state,'PASS',[research+'/uiux-routes-v1.json',research+'/uiux-browser-v1.json'],'Measured CSS-pixel viewport, no document overflow in recorded state. Physical device not tested.');
 const validations=captures.filter(c=>c.state==='validation');if(validations.length)set(screen,'validation','PASS',[research+'/uiux-browser-v1.json'],'Specific invalid fields/interval captured; not every possible validator.');
 const conflicts=captures.filter(c=>c.state==='stale-conflict');if(conflicts.length)set(screen,'stale-conflict','PASS',[research+'/uiux-browser-v1.json'],'Recorded hold expiry or busy-block conflict recovered without mutation.');
 const success=captures.filter(c=>c.state==='success');if(success.length)set(screen,'success','PASS',[research+'/uiux-browser-v1.json'],'Actual local durable mutation confirmed, no live delivery claim.');
 if(captures.some(c=>c.state==='permission'))set(screen,'permission','PASS',[research+'/uiux-browser-v1.json',research+'/uiux-session-expiry-v1.json'],'Named fictional session expiry returns to auth; retained contact restored after ordinary sign-in.');
 if(captures.some(c=>c.state==='keyboard-focus'))set(screen,'keyboard-focus','PASS',[research+'/uiux-browser-v1.json'],'Recorded Enter opens calendar detail; Tab/Shift+Tab/Escape behavior sampled in actual dialogs.');
 if(rows.some(r=>[320,640].includes(r.width)))screen.reflowEvidence={status:'PASS',scope:'Measured narrow CSS-pixel reflow only. Actual browser zoom remains UNVERIFIED.',evidence:[research+'/uiux-routes-v1.json']};
}
await write(base+'/uiux/SCREEN_STATE_MATRIX.json',matrix);
const defects=await read(base+'/uiux/DEFECTS.json');defects.at=now;
const repair={UX01:'Explicit type=button on all shared actions; actual submit progress and duplicate protection.',UX02:'Lithuanian inline constraints, aria-invalid/describedby, first invalid focus; errors span grid.',UX03:'Account/org/entity/version scoped8h tab drafts, success/logout clear, visible restore/discard, stable addon IDs during add/remove and reload.',UX04:'Challenge ID/email/expiry survives reload without code persistence; resend and other email paths.',UX05:'Live countdown, disabled expired confirmation, heading/recovery after reload, auth expiry recovery; already-confirmed booking back guard.',UX06:'Trusted frontend INVALID_INPUT copy survives errorHTML; actual interval correction visible.',UX07:'aria-current, live skeleton and executing submit label; selected booking step centered.',UX08:'Task-specific dashboard CTA, profile readiness note, operator queue and selected-day empties.',UX09:'Short visit reference, compact calendar/sidebar, wrapped utilities and radio choice totals;320px buttons fit parent.',UX11:'15s AbortController and safe non-JSON/null/network errors; conflict code preserved. Upload endpoint unchanged.',UX12:'Map accessible name includes visible number; human-facing time/schedule copy; snapshot-first conversation label.'};
for(const d of defects.defects){if(d.id==='UX10'){d.status='UNVERIFIED';d.repairs=['Expanded current DOM route/viewport coverage and targeted state receipts.'];d.confirmation=[research+'/uiux-functional-final-v1.json'];d.remaining=receipt.limits;continue;}d.status='FIXED_LOCAL';d.repairs=[repair[d.id]];d.confirmation=[research+'/uiux-browser-v1.json',research+'/uiux-routes-v1.json',research+'/http-adapter-tests-v1.tap'];if(d.id==='UX11')d.remaining=['Upload transport was not retested; media inspection stopped by owner.'];}
for(const [id,issue,repairText] of [['UX13','Mobile secondary filters hid first results','Native disclosure, applied count, empty/reset and custom interval retained.'],['UX14','Calendar toolbar and prior empty days pushed visits down','Compact controls, single-workspace name, selected day leads mobile;7 columns desktop.'],['UX15','Native select truncated service/staff duration and price','Radio rows show full name, practitioner, duration and price; actual addon totals.'],['UX16','Confirmed booking allowed editing steps with reused idempotency key','Back steps show existing visit and explicit plan-another action.'],['UX17','320px controls overflowed parent despite no document overflow','Minmax grid/padding/input fix; actual every control right-overflow0.'],['UX18','Custom interval from booking was displayed as native select default','Current interval added once among choices; actual14:00–20:00 display confirmed.']])defects.defects.push({id,priority:'P1',issue,baselineStatus:'BROWSER_CONFIRMED',status:'FIXED_LOCAL',repairs:[repairText],confirmation:[research+'/uiux-browser-v1.json',research+'/uiux-functional-final-v1.json']});
await write(base+'/uiux/DEFECTS.json',defects);
const status=await read(base+'/SCREEN_STATUS.json');status.version=3;status.evaluatedAt=now;status.scope='Current UI/UX repair and route/viewport coverage; owner stopped demo profile/image review; full-state acceptance remains explicitly bounded.';
for(const screen of status.screens){const rows=routes.filter(r=>r.id===screen.id);for(const row of rows)screen.browserEvidence.push({id:row.id,width:row.width,receipt:research+'/uiux-routes-v1.json',review:'Actual rendered DOM/viewport; not standalone pixel acceptance'});screen.widths=[...new Set([...screen.widths,...rows.map(r=>r.width)])].sort((a,b)=>a-b);screen.currentUiuxMatrix=base+'/uiux/SCREEN_STATE_MATRIX.json';}
await write(base+'/SCREEN_STATUS.json',status);
const audit=await read(base+'/PHASE-1-AUDIT.json');audit.evaluatedAt=now;audit.version={backend:'V15 35/35',platform:'V9 30/30; HTTP V1 4/4',lighthouse:'authenticated V8 94/100/100/66',screen:'Current UIUX V1 + SCREEN_STATUS V3; historical inventory unchanged'};audit.verdict.visual='Current platform repairs accepted in bounded actual paths; full70/all-state, physical zoom/reduced-motion still UNVERIFIED; owner media stop respected';
for(const check of audit.checks){if(['R1','R2','R3','S1','S2','T2','Z1'].includes(check.id)){check.evidence.push(research+'/uiux-functional-final-v1.json',base+'/uiux/SCREEN_STATE_MATRIX.json');check.notes+=' Current UIUXV1 records actual narrow reflow, drafts, auth/hold expiry, validation and conflict recovery. Control++ ineffective in IAB, so physical200% zoom and reduced-motion preference remain UNVERIFIED.';}if(check.id==='T2')check.evidence.push(research+'/performance-authenticated-v8.json');}
await write(base+'/PHASE-1-AUDIT.json',audit);
const md=['# Madbeauty — A–Z aktuali patikra','',`Atnaujinta ${now}. Tas pats įgyvendinimo agentas; nepriklausomo vertinimo teiginio nėra. Vietinis UX taisymų paketas priimtas su nurodytomis ribomis. Tikras paleidimas ir paklausa atskiri. Jokio10/10 ar visų70visųbūsenų teiginio.`,'','| ID | Etapas | Būsena | Įrodymai ir ribos |','|---|---|---|---|',...audit.checks.map(c=>`| ${c.id} | ${c.stage} | ${c.status} | ${c.evidence.map(e=>'`'+e+'`').join(', ')}. ${c.notes.replaceAll('|','/')} |`)];await writeFile(base+'/PHASE-1-AUDIT.md',md.join('\n')+'\n');
const acceptance=`# Madbeauty — dabartinis UI/UX priėmimas\n\n2026-10-06. Pagerintos platformos užduotys, išlaikant black/white/violet tapatybę. Demo fotografijų ir profilių peržiūra neatnaujinta. Tai šio pataisų paketo vietinis priėmimas, ne absoliuti tobulybė ar domain-ready.\n\n${receipt.routeChecks} actual DOM/viewport patikrų, ${receipt.uniqueRouteSurfaces} skirtingų route paviršių; dydžiai ${receipt.widths.join('/')} CSS px. Dokumento overflow0, viena h1, neaptikta raw action submit mygtukų šiuose įrašuose. Pixel peržiūra atlikta svarbiems pakeistiems keliams ir modaliams; DOM matavimas nėra kiekvieno ekrano pixel PASS. ${receipt.screenshots} nauji UI kadrai su actual būsena.\n\nSutvarkyta: lietuviškos inline klaidos/focus/ARIA, vykdomo submit būsena, juodraščių atkūrimas ir atmetimas, stable priedų redaktorius, auth challenge reload/resend, auth expiry, live hold expiry, confirmed-booking back guard, kompaktiškas calendar/search, pilnai skaitomi variantai ir kainos. Neįsiųsta QA žinutė tik atkurta/atmesta; realaus laiško ar žinutės žmogui nesiųsta.\n\nBackend35/35, platform30/30, HTTP4/4 — iš viso69PASS. Prisijungęs calendar LighthouseV8:94/100/100/66, LCP2.56s,TBT57ms,CLS0.094,200836bytes. Privatus noindex sąmoningas. Tai vietinis matavimas.\n\nKontrolinis6sekundžių kadras nebuvo expiry proof — anotacija išlaikyta, tikras expired/disabled/recovery užfiksuotas vėliau.320px tėvinio bloko persiliejimas aptiktas po document-only matavimo, pataisytas ir pamatuotas individualiai. Detektoriaus2 perspėjimai: senas nenaudojamo appointment border sumažintas iki1px; disclosure chevron2px yra geometrinė rodyklė, ne card accent. Nebuvo deklaruota, kad detektorius įrodo kokybę.\n\n70 paviršių būsena — SCREEN_STATE_MATRIX.json. UNVERIFIED išlieka visų būsenų/kiekvieno ekrano, physical zoom/OS reduced-motion, dalies multi-staff/short-overlap event kombinacijų ir production/browser/device matrica. IAB Control++ nepakeitė scale/dpr/width;320/640px yra CSS reflow, ne fizinis200%zoom. Owner sustabdytų demo profilių/media peržiūra atskirta nuo platformos runtime patikrų. A–Z score nėra UX paketui suteiktas10/10.\n\nĮrodymai: research/madbeauty-implementation/uiux-functional-final-v1.json, uiux-browser-v1.json, uiux-routes-v1.json, uiux-computed-v1.json, uiux-session-expiry-v1.json. Visi ankstesni fingerprint ir nesėkmės išsaugoti. Gyvas deploy,SMTP/INBOX,realūs tiekėjai/demand/mokėjimai/FB/voice neįjungti.\n`;
await writeFile(base+'/uiux/ACCEPTANCE.md',acceptance);
const update=`## UI/UX pataisų priėmimas — 2026-10-06\n\nVietinės platformos formos, auth/booking atkūrimas, search/calendar ir variantų pasirinkimas pagerinti. ${receipt.routeChecks} actual route/viewport įrašų per ${receipt.uniqueRouteSurfaces} paviršių,320/390/640/820/1440px. BackendV15 35/35, platformV9 30/30, HTTPV1 4/4;69PASS. Authenticated calendar LighthouseV8 94/100/100/66. Aktualios ribos ir70matrix: [uiux/ACCEPTANCE.md](uiux/ACCEPTANCE.md). Full70/all-state, physical zoom/reduced-motion ir production vartai vis darUNVERIFIED. Demo media/profilių peržiūra neatnaujinta.\n\n`;
for(const name of ['IMPLEMENTATION_STATUS.md','DESIGN.md','prototype/IMPLEMENTATION_QA.md']){const p=base+'/'+name,s=await readFile(p,'utf8');await writeFile(p,update+s);}
const ws='WORKSTREAMS.md';await writeFile(ws,(await readFile(ws,'utf8'))+'\n2026-10-06 · Madbeauty UIUX pataisų paketas: own sites/madbeauty + research/madbeauty-implementation ribose užbaigtas bounded local acceptance;69PASS, current route/state evidence. Root8786/shared core neredaguotas. Demo media darbai neatnaujinti; full70/production vartai lieka nurodyti.\n');
console.log(JSON.stringify({routeChecks:receipt.routeChecks,uniqueRouteSurfaces:receipt.uniqueRouteSurfaces,failures:receipt.failures.length,screenshots:receipt.screenshots}));
