import {readFile,writeFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {openStore} from '../backend/store.mjs';
const site=path.resolve(import.meta.dirname,'..'),workspace=path.resolve(site,'../..'),research=path.join(workspace,'research/madbeauty-implementation'),at=new Date().toISOString();
const json=async p=>JSON.parse(await readFile(p,'utf8')),save=async(p,x)=>writeFile(p,JSON.stringify(x,null,2)+'\n');
const currentDocs=['IMPLEMENTATION_STATUS.md','CURRENT_SCOPE.md','BACKEND_DECISION.md','BUSINESS.md','CORE_FEEDBACK.md','PROJECT_ROADMAP.md','prototype/README.md','prototype/IMPLEMENTATION_QA.md'];
for(const f of currentDocs){const p=path.join(site,f),text=await readFile(p,'utf8'),boundary=text.indexOf('## Istoriniai'),current=boundary<0?text:text.slice(0,boundary),history=boundary<0?'':text.slice(boundary);await writeFile(p,current.replaceAll('V12','V14').replaceAll('34/34','35/35').replaceAll('platform V6','platform V7').replaceAll('platformV6','platformV7').replaceAll('backend-tests-v12','backend-tests-v14').replaceAll('platform-tests-v6','platform-tests-v7')+history);}
const note='\nGalutinė papildoma pataisa: reschedule variantas prieš patvirtinimą rodo kainą ir trukmę. Atomic change atnaujina snapshot/meistrą/resursą, tikrina konkretaus vizito prieigą ir leidžia savo esamą nepublikuoto meistro vizitą perkelti klientui. BackendV13 pirmas naujo kontrakto testas FAIL: aptikta approval-dependent reschedule spraga. Pataisyta; V14 35/35PASS2049.8453ms, platformV7 30/30PASS2362.7397ms. V13FAIL išlaikytas. Actual320px reschedule panelė ir native dialog replacement focus retestuoti;1280px savaitė dabar rodo visus7stulpelius.\n';
for(const f of ['IMPLEMENTATION_STATUS.md','prototype/IMPLEMENTATION_QA.md','CORE_FEEDBACK.md']){const p=path.join(site,f),t=await readFile(p,'utf8'),i=t.indexOf('## Istoriniai');await writeFile(p,i<0?t+note:t.slice(0,i)+note+'\n'+t.slice(i));}
const audit=await json(path.join(site,'PHASE-1-AUDIT.json'));audit.evaluatedAt=at;audit.version.backend='V14 35/35; V13 failed new contract retained';audit.version.platform='V7 30/30';for(const c of audit.checks)c.evidence=c.evidence.map(e=>e.replace('backend-tests-v12','backend-tests-v14').replace('platform-tests-v6','platform-tests-v7'));await save(path.join(site,'PHASE-1-AUDIT.json'),audit);
const auditMd=path.join(site,'PHASE-1-AUDIT.md');await writeFile(auditMd,(await readFile(auditMd,'utf8')).replaceAll('backend-tests-v12','backend-tests-v14').replaceAll('platform-tests-v6','platform-tests-v7')+'\nGalutinė backendV14 35/35 ir platformV7 30/30 regresija PASS. Ankstesnis V13 papildomo reschedule kontrakto FAIL išlaikytas; tai nekeičia production/SMTP/visosSEO/accessibility UNVERIFIED vartų.\n');
const screen=await json(path.join(site,'SCREEN_STATUS.json')),v6=await json(path.join(research,'screen-acceptance-v6.json'));screen.evaluatedAt=at;
for(const s of screen.screens){const keys=s.id==='professional-calendar'?['professional-calendar','professional-early-block-final']:s.id==='professional-manual-visit'?['professional-manual-visit','professional-manual-options']:s.id==='booking-reschedule'?['booking-reschedule','professional-reschedule-price-final']:s.id==='professional-clients'?['professional-clients','professional-client-created','professional-clients-tablet-final','professional-client-form-tablet-final']:s.id==='professional-service-editor'?['professional-service-editor','professional-service-future-guard-final']:[s.id];const rows=v6.filter(x=>keys.some(k=>x.id===k||x.id.startsWith(k+'-'))).map(x=>({id:x.id,width:x.metrics.width,receipt:'research/madbeauty-implementation/screen-acceptance-v6.json',screenshot:'research/madbeauty-implementation/'+x.screenshot,review:x.review}));const byFile=new Map([...s.browserEvidence,...rows].map(x=>[x.screenshot,x]));s.browserEvidence=[...byFile.values()];s.widths=[...new Set(s.browserEvidence.map(x=>x.width))].sort((a,b)=>a-b);s.desktopEvidence||=s.widths.some(w=>w>=1000);s.mobileEvidence||=s.widths.some(w=>w<=760);}
await save(path.join(site,'SCREEN_STATUS.json'),screen);
const receipt=await json(path.join(research,'durable-functional-receipt-final.json')),store=openStore({filename:path.join(site,'runtime/platform-preview.sqlite'),fixturePreview:true});try{const d=store.read(),o=d.organizations.find(o=>o.id===receipt.organization.id);receipt.at=at;receipt.organization.profileState=o.profileState;receipt.organization.approved=o.approved;receipt.contactReport=receipt.contactReport.map(r=>({id:r.id,status:d.reports.find(x=>x.id===r.id)?.status}));}finally{store.close();}await save(path.join(research,'durable-functional-receipt-final.json'),receipt);
const functional=await json(path.join(research,'platform-functional-final-v1.json'));functional.at=at;functional.checks.push({id:'reschedule-contract-current-price-duration-and-assignment',status:'PASS_AFTER_REPAIR',evidence:['backend-tests-v14.tap','screen-acceptance-v6.json'],note:'V13 new contract failed due draft-provider approval dependence; fixed own-booking scoped internal availability/choose; refreshed snapshot/staff/resource. Actual UI shows32EUR/60min before choosing. Private unapproved catalogue stays inaccessible to anonymous/other client.'},{id:'dialog-replacement-focus',status:'PASS',evidence:'screen-acceptance-v6.json',note:'Actual appointment drawer→reschedule replacement places focus on close inside modal; Escape returns original appointment.1280 default viewport restored; seven weekday columns visible.'});await save(path.join(research,'platform-functional-final-v1.json'),functional);
const source=await json(path.join(research,'current-source-version.json'));source.at=at;for(const f of source.files)f.sha256=createHash('sha256').update(await readFile(path.join(workspace,f.path))).digest('hex');await save(path.join(research,'current-source-version.json'),source);
const secrets=[];for(const v of ['v6','v7']){const h=await json(path.join(site,'runtime/lighthouse-auth-headers-'+v+'.json'));const c=h.Cookie;if(c){secrets.push(c,c.slice(c.indexOf('=')+1));}}
const list=async dir=>(await readdir(dir,{withFileTypes:true})).flatMap(e=>e.isFile()?[path.join(dir,e.name)]:[]);
const researchFiles=(await list(research)).filter(f=>/\.(json|html|md|tap|txt)$/.test(f)),publicFiles=(await list(path.join(site,'prototype/public'))).filter(f=>/\.(mjs|css|html|json)$/.test(f));
const findings=[];for(const f of [...researchFiles,...publicFiles]){const text=await readFile(f,'utf8');if(secrets.some(s=>s.length>20&&text.includes(s)))findings.push({file:path.relative(workspace,f),kind:'private local auth credential exposed'});if(/(?:sk-[A-Za-z0-9_-]{32,}|ghp_[A-Za-z0-9]{30,})/.test(text))findings.push({file:path.relative(workspace,f),kind:'credential-shaped token'});}
const inaccessible=[];for(const p of ['/backend/store.mjs','/runtime/platform-preview.sqlite','/runtime/browser-test-code.json','/runtime/lighthouse-auth-headers-v7.json','/private-originals/profiles-v2/profile-01-portrait.png']){const r=await fetch('http://127.0.0.1:8788'+p);inaccessible.push({path:p,status:r.status});if(r.status!==404)throw Error('Private path exposed');}
const result={at,scope:'own public source and research text; local generated test credentials only; shared changes not attributed to this task',textFilesScanned:researchFiles.length+publicFiles.length,credentialFindings:findings,privateHttpPaths:inaccessible,backend:{version:14,passed:35,failed:0,previousVersion13Failed:1},platform:{version:7,passed:30,failed:0},sameAgent:true};await save(path.join(research,'final-safety-scope.json'),result);if(findings.length)throw Error('Credential scan failed');console.log(JSON.stringify({...result,privateHttpPaths:inaccessible.length}));
