import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const site=path.resolve(import.meta.dirname,'..'),research=path.resolve(site,'../../research/madbeauty-implementation'),at=new Date().toISOString();
const source=JSON.parse(await readFile(path.join(site,'SCREEN_INVENTORY.json'),'utf8'));
const defects=[
 ['UX01','P1','Shared action buttons lack type=button; submit busy logic can disable an add-on/action button rather than the actual submit control.','prototype/public/ui.mjs; app.mjs','SOURCE_CONFIRMED','interactions'],
 ['UX02','P1','Required/native form errors have no Lithuanian inline explanation, associated invalid field or correction guidance.','screen-acceptance-v6.json professional-client-form-tablet-final','BROWSER_CONFIRMED','interactions'],
 ['UX03','P1','Unsaved contact/profile/new-client input is only copied on submit; render/reload/help/back can lose it.','prototype/public/account-ui.mjs; booking-ui.mjs; workspace-ui.mjs','SOURCE_CONFIRMED','forms'],
 ['UX04','P1','Email challenge is context-only, so reload returns to email entry; no same-email resend/recovery progress.','prototype/public/account-ui.mjs','SOURCE_CONFIRMED','auth-booking'],
 ['UX05','P1','Hold review lacks live expiry state; details dereferences anonymous session when auth expires. Server safely rejects, but recovery UX is weak.','prototype/public/booking-ui.mjs','SOURCE_CONFIRMED','auth-booking'],
 ['UX06','P1','Frontend validation Error without code is replaced with generic retry copy, hiding the actual interval/date/choice correction.','prototype/public/ui.mjs; app.mjs','SOURCE_CONFIRMED','interactions'],
 ['UX07','P2','Active navigation is only a visual class; dynamic page/form loading is generic and mutation progress lacks explicit text.','prototype/public/ui.mjs; app.mjs','SOURCE_CONFIRMED','interactions'],
 ['UX08','P2','Several private empty lists reuse generic empty-state content/CTA instead of the task context; onboarding eligibility/status needs clearer next action.','prototype/public/workspace-ui.mjs','SOURCE_CONFIRMED','workspace'],
 ['UX09','P2','Raw long registration IDs, calendar utility text and dense mobile forms need measured wrapping/reflow review.','prototype/public/booking-ui.mjs; workspace.css','REVIEW_REQUIRED','style-reflow'],
 ['UX10','P2','State coverage and fullscreen tablet/zoom/keyboard/reduced-motion acceptance are incomplete across70 surfaces.','SCREEN_STATUS.json; PHASE-1-AUDIT.json','EVIDENCE_GAP','all-groups'],
 ['UX11','P2','HTTP adapter has no bounded request timeout and assumes every error response is JSON.','prototype/public/http-adapter.mjs','SOURCE_CONFIRMED','interactions'],
 ['UX12','P2','Schematic map numbered button aria-label omits its visible number; some profile/booking auxiliary copy exposes internal terminology.','prototype/public/public-views.mjs; booking-ui.mjs','SOURCE_CONFIRMED','public-editorial']
].map(([id,priority,issue,evidence,baselineStatus,group])=>({id,priority,issue,evidence,baselineStatus,group,status:'OPEN',repairs:[],confirmation:[]}));
const dialogs=new Set(source.screens.filter(x=>!x.route).map(x=>x.id));
const forms=new Set(['public-home','public-search','public-catalog','customer-entry','customer-profile','customer-settings','customer-review','booking-services-step','booking-staff-step','booking-time-step','booking-details-step','booking-inquiry','booking-waitlist','booking-reschedule','booking-cancel','professional-onboarding','professional-manual-visit','professional-clients','professional-services','professional-service-editor','professional-shifts','professional-resources','professional-team','professional-profile','professional-gallery','professional-messages','professional-calendar','operator-provider-review','operator-reports','trust-contact']);
const empty=new Set(['public-search','public-catalog','public-practitioner','public-venue','booking-time-step','customer-appointments','customer-favorites','customer-messages','professional-overview','professional-calendar','professional-inquiries','professional-waitlist','professional-clients','professional-client-detail','professional-services','professional-profile','professional-gallery','professional-messages','professional-reports','operator-queue','operator-reports','operator-delivery','operator-content','operator-metrics']);
const conflict=new Set(['booking-time-step','booking-review-step','booking-confirmation','booking-reschedule','booking-cancel','professional-manual-visit','professional-service-editor','professional-shifts','professional-resources','professional-team','professional-profile','professional-calendar','professional-visit-drawer','operator-provider-review','operator-reports']);
const matrix={siteId:'madbeauty',at,scope:'Current owner-requested UI/UX acceptance. No demo profile/image inspection; profile interaction and layout only. Same implementing agent; no independent claim.',rounds:{baseline:'SOURCE + prior actual evidence + one combined current desktop/tablet/mobile pass',repair:'bounded groups by shared component/real task',confirmation:'one relevant confirmation per repaired group; extra round only documented unresolved defect'},baselineTests:{backend:35,platform:30,total:65},screens:source.screens.map(s=>({id:s.id,route:s.route||null,surface:s.surface,kind:dialogs.has(s.id)?'dialog/state':'route',group:s.surface==='public'?'public-editorial':s.surface==='professional'?'workspace':s.surface==='operator'?'operator':s.surface==='booking'||s.surface==='customer'?'auth-booking':'public-editorial',states:Object.fromEntries(['normal','loading','empty','error','validation','permission','stale-conflict','success','keyboard-focus','desktop','tablet','mobile','zoom-reflow','reduced-motion'].map(state=>{const applicable=state==='validation'?forms.has(s.id):state==='empty'?empty.has(s.id):state==='permission'?['customer','professional','operator'].includes(s.surface)||s.id.startsWith('booking-'):state==='stale-conflict'?conflict.has(s.id):true;return[state,{status:applicable?'UNVERIFIED':'NA',evidence:[],notes:applicable?'Requires actual surface or relevant shared-component state evidence.':'Not an applicable state for this static/read-only surface; unknown content/route handled by404.'}]}))}))};
await mkdir(path.join(site,'uiux'),{recursive:true});
await writeFile(path.join(site,'uiux/DEFECTS.json'),JSON.stringify({at,scope:matrix.scope,defects},null,2));await writeFile(path.join(site,'uiux/SCREEN_STATE_MATRIX.json'),JSON.stringify(matrix,null,2));
await writeFile(path.join(site,'uiux/ACCEPTANCE.md'),'# Madbeauty — UI/UX ir stilių priėmimas\n\n2026-10-06. Savininko tęstinis pavedimas apima visus70 produkto paviršių. Esama black/white/violet tapatybė išlaikoma; demo fotografijų/profilių medijos nebeaudituojame. Tikrinama produkto užduotis, layout ir interaction.\n\nDEFECTS.json — konkretūs radiniai, atskiriant source patvirtintą defektą nuo dar reikalingos naršyklės peržiūros. SCREEN_STATE_MATRIX.json — pritaikomos būsenos; UNVERIFIED nėra PASS. Bazė65 testai. Gyvos operacijos išlieka išjungtos; A–Z production/SMTP/paklausos vartai nėra UI balas.\n\nPataisų grupės: shared interactions/forms; auth/booking/customer; provider onboarding/calendar/services/clients/messages; operator; public/editorial/help/legal. Kiekvienai grupei viena combined viewport peržiūra, viena repair batch ir viena confirmation. Tik konkrečios likusios klaidos pateisina papildomą targeted ratą.\n');
console.log(JSON.stringify({screens:matrix.screens.length,defects:defects.length,baselineTests:65}));
