import {randomUUID} from 'node:crypto';
import {reject} from './primitives.mjs';
import {communityMediaState} from './community-media-state.mjs';
import {matchesTaxonomy} from '../prototype/taxonomy.mjs';
import {monthsBefore,RETENTION_POLICY} from './retention-policy.mjs';
const text=(v,max,min=0)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)reject('VALIDATION_FAILED','Patikrink laukų ilgį ir užpildymą.');return v.trim();};
const target=v=>text(v,100,1);
const mediaIds=(v,max)=>{if(v===undefined)return [];if(!Array.isArray(v)||v.length>max||new Set(v).size!==v.length)reject('VALIDATION_FAILED','Patikrink nuotraukų skaičių.');return v.map(target);};
const version=(expected,actual)=>{if(expected!==actual)reject('CONFLICT','Įrašas pasikeitė. Atnaujink puslapį ir bandyk dar kartą.',409);};
const missing=()=>reject('NOT_FOUND','Turinys nerastas.',404);
const initialPerson={profile:null,posts:[],following:[],blocked:[],saved:[],references:[],reports:[],audit:[]};
export const personActor=id=>'person:'+id;
export const organizationActor=id=>'organization:'+id;
export const conversationKey=(a,b)=>[a,b].sort().join('|');
export function createCommunityPerson(store,owner){
 const media=communityMediaState(store),read=()=>store.read('person',initialPerson),write=d=>store.write('person',d,d.version);
 const own=p=>{if(p.actor!==owner&&!p.canManage)reject('FORBIDDEN','Šio profilio keisti negali.',403);};
 const allowed=(d,p)=>p.actor===owner||!d.blocked.includes(p.actor)&&!p.blocked;
 const visible=(d,post,p)=>allowed(d,p)&&!post.deleted&&!post.hidden&&(p.actor===owner||post.audience==='public'||post.audience==='friends'&&p.friend===true);
 const postFor=(d,id,p)=>{const post=d.posts.find(x=>x.id===id);if(!post||!visible(d,post,p))missing();return post;};
 const projection=(post,p)=>({...post,authorName:read().profile?.name||'Bendruomenės narys',images:media.details(post.media,'post:'+post.id),operation:undefined,likes:post.likes.length,liked:post.likes.includes(p.actor),comments:post.comments.filter(c=>!c.deleted).map(({operation,...c})=>c)});
 const mutate=fn=>store.transaction(()=>{const d=read(),v=fn(d);write(d);return v;});
 const requireProfile=d=>{if(!d.profile||!d.profile.discoverable)reject('PROFILE_REQUIRED','Pirmiausia susikurk bendruomenės profilį.',409);};
 return {
  profile(p){const d=read();if(!allowed(d,p))missing();return {profile:d.profile,version:d.version,...p.actor===owner?{following:d.following,blocked:d.blocked,saved:d.saved,references:d.references,decisions:d.audit.map(({actor,...a})=>a)}:{}};},
  settings(p,v){own(p);if(owner.startsWith('organization:')&&v.messagePolicy==='friends')reject('VALIDATION_FAILED','Salonui pasirink užklausas arba uždarą dėžutę.');return mutate(d=>{version(v.version,d.version);d.profile={actor:owner,name:text(v.name,80,2),bio:text(v.bio||'',500),city:text(v.city||'',80),discoverable:v.discoverable===true,messagePolicy:['requests','friends','closed'].includes(v.messagePolicy)?v.messagePolicy:'requests',isDemo:p.isDemo===true};return {profile:d.profile,version:d.version+1};});},
  list(p,v={}){const d=read();if(!allowed(d,p))return {posts:[],next:null};const limit=Math.min(24,Math.max(1,Number(v.limit)||12));const rows=d.posts.filter(x=>visible(d,x,p)&&(!v.before||x.order<v.before)&&(!v.serviceId||matchesTaxonomy(x.serviceId,v.serviceId))).sort((a,b)=>b.order.localeCompare(a.order));return {posts:rows.slice(0,limit).map(x=>projection(x,p)),next:rows.length>limit?rows[limit-1].order:null};},
  get(p,v){const d=read();return projection(postFor(d,v.id,p),p);},
  publish(p,v){own(p);return mutate(d=>{requireProfile(d);const operation=target(v.operation),prior=d.posts.find(x=>x.operation===operation);if(prior)return projection(prior,p);if(d.posts.filter(x=>!x.deleted).length>=500)reject('LIMIT','Pasiektas profilio įrašų limitas.',409);const body=text(v.text,4000,1),audience=['public','friends','private'].includes(v.audience)?v.audience:'public';if(owner.startsWith('organization:')&&audience==='friends')reject('VALIDATION_FAILED','Salono įrašui pasirink viešą arba privatų matomumą.');const post={id:randomUUID(),author:owner,text:body,audience,city:d.profile.city,serviceId:text(v.serviceId||'',100),providerServiceId:text(v.providerServiceId||'',100),galleryMediaId:text(v.galleryMediaId||'',100),media:mediaIds(v.media,6),createdAt:store.clock(),order:String(store.clock()).padStart(16,'0')+'-'+randomUUID(),version:1,operation,likes:[],comments:[],isDemo:p.isDemo===true};media.attach(owner,post.media,'post:'+post.id,6);d.posts.push(post);return projection(post,p);});},
  edit(p,v){own(p);return mutate(d=>{const post=d.posts.find(x=>x.id===v.id);if(!post||post.deleted)missing();version(v.version,post.version);if(v.delete===true){post.deleted=true;post.text='';post.media=[];post.comments=[];post.likes=[];}else{post.text=text(v.text,4000,1);if(!['public','friends','private'].includes(v.audience))reject('VALIDATION_FAILED','Netinkama auditorija.');if(owner.startsWith('organization:')&&v.audience==='friends')reject('VALIDATION_FAILED','Netinkama auditorija.');post.audience=v.audience;}post.version++;return {id:post.id,version:post.version,deleted:!!post.deleted};});},
  like(p,v){return mutate(d=>{const post=postFor(d,v.id,p);if(!p.actor)reject('FORBIDDEN','Pirmiausia prisijunk.',403);post.likes=post.likes.filter(id=>id!==p.actor);if(v.liked===true)post.likes.push(p.actor);return {id:post.id,likes:post.likes.length,liked:v.liked===true};});},
  comment(p,v){return mutate(d=>{const post=postFor(d,v.id,p);if(!p.actor)reject('FORBIDDEN','Pirmiausia prisijunk.',403);const operation=target(v.operation),prior=post.comments.find(x=>x.author===p.actor&&x.operation===operation);if(prior)return prior;if(post.comments.filter(x=>!x.deleted).length>=500)reject('LIMIT','Pasiektas komentarų limitas.',409);if(v.parentId&&!post.comments.some(x=>x.id===v.parentId&&!x.deleted))missing();const c={id:randomUUID(),author:p.actor,name:text(p.name||'Bendruomenės narys',80),text:text(v.text,1000,1),parentId:v.parentId||null,createdAt:store.clock(),version:1,operation};post.comments.push(c);return c;});},
  editComment(p,v){return mutate(d=>{const post=postFor(d,v.id,p),c=post.comments.find(x=>x.id===v.commentId&&!x.deleted);if(!c)missing();if(c.author!==p.actor&&p.actor!==owner)reject('FORBIDDEN','Komentaro keisti negali.',403);version(v.version,c.version);if(v.delete){c.deleted=true;c.text='';}else{if(c.author!==p.actor)reject('FORBIDDEN','Kito autoriaus teksto keisti negali.',403);c.text=text(v.text,1000,1);}c.version++;return {id:c.id,version:c.version,deleted:!!c.deleted};});},
  save(p,v){own(p);return mutate(d=>{const key=target(v.author)+'/'+target(v.id);d.saved=d.saved.filter(x=>x.key!==key);if(v.saved===true)d.saved.push({key,author:v.author,id:v.id,album:text(v.album||'Idėjos',80,1)});return {saved:d.saved};});},
  follow(p,v){own(p);return mutate(d=>{const t=target(v.target);if(t===owner||d.blocked.includes(t)||v.targetBlocked)reject('FORBIDDEN','Šis ryšys neleidžiamas.',403);d.following=d.following.filter(x=>x!==t);if(v.following===true)d.following.push(t);return {following:d.following};});},
  block(p,v){own(p);return mutate(d=>{const t=target(v.target);if(t===owner)reject('VALIDATION_FAILED','Savęs blokuoti negali.');d.blocked=d.blocked.filter(x=>x!==t);if(v.blocked===true){d.blocked.push(t);d.following=d.following.filter(x=>x!==t);d.saved=d.saved.filter(x=>x.author!==t);}return {blocked:d.blocked};});},
  reference(p,v){own(p);return mutate(d=>{const key=text(v.key,210,1);if(!d.references.includes(key))d.references.push(key);return {key};});},
  report(p,v){if(!p.actor)reject('FORBIDDEN','Pirmiausia prisijunk.',403);return mutate(d=>{const post=postFor(d,v.id,p),operation=target(v.operation),prior=d.reports.find(x=>x.actor===p.actor&&x.operation===operation);if(prior)return {id:prior.id,status:prior.status};const r={id:randomUUID(),target:post.id,actor:p.actor,note:text(v.note,500,3),status:'new',version:1,operation,createdAt:store.clock()};d.reports.push(r);return {id:r.id,status:r.status};});},
  review(p,v){if(!p.operator)reject('FORBIDDEN','Šis veiksmas neleidžiamas.',403);return mutate(d=>{const r=d.reports.find(x=>x.id===v.reportId);if(!r)missing();version(v.version,r.version);const post=d.posts.find(x=>x.id===r.target);post.hidden=v.hidden===true;r.status='resolved';r.version++;d.audit.push({actor:p.actor,target:r.target,hidden:post.hidden,reason:text(v.reason,500,3),at:store.clock()});return {id:r.id,status:r.status,version:r.version};});},
  reports(p){if(!p.operator)reject('FORBIDDEN','Šis veiksmas neleidžiamas.',403);const d=read();return {author:owner,reports:d.reports.filter(r=>r.status==='new').map(({actor,operation,...r})=>({...r,post:d.posts.find(x=>x.id===r.target)?.text||'Pašalintas įrašas'})),audit:d.audit};},
  registerMedia(p,v){own(p);requireProfile(read());return media.register(owner,v);},
  readMedia(p,v){const post=postFor(read(),v.post,p);if(!post.media.includes(v.id))missing();return media.read(v.id,'post:'+post.id,v.width);},
  cleanup(){return store.transaction(()=>media.cleanup(new Set(read().posts.filter(p=>!p.deleted).map(p=>'post:'+p.id))));},
  eraseActor(p,v){if(p.maintenance!==true)reject('FORBIDDEN','Šis veiksmas neleidžiamas.',403);return mutate(d=>{const rooms=[...d.references];if(v.target===owner){Object.assign(d,structuredClone(initialPerson));media.cleanup(new Set());}else{for(const post of d.posts){post.likes=post.likes.filter(a=>a!==v.target);post.comments=post.comments.filter(c=>c.author!==v.target);}for(const field of ['following','blocked'])d[field]=d[field].filter(a=>a!==v.target);d.saved=d.saved.filter(s=>s.author!==v.target);d.references=d.references.filter(k=>!k.split('|').includes(v.target));d.reports=d.reports.filter(r=>r.actor!==v.target);}return {erased:true,rooms};});},
  export(p){own(p);const {reports,audit,...d}=read();return {...d,decisions:audit.map(({actor,...a})=>a)};},
  contributions(p){const d=read();return {author:owner,comments:d.posts.flatMap(post=>post.comments.filter(c=>c.author===p.actor&&!c.deleted).map(({operation,...c})=>({...c,postId:post.id}))),reports:d.reports.filter(r=>r.actor===p.actor).map(({operation,...r})=>r)};},
 };
}

const initialRoom={participants:[],friendship:{state:'none',requestedBy:null,version:0},conversation:{state:'none',requestedBy:null,version:0},messages:[],reads:{},organization:null};
export function createCommunityConversation(store,pair){
 const media=communityMediaState(store),read=()=>store.read('conversation',initialRoom),write=d=>store.write('conversation',d,d.version);
 const member=(d,p)=>{if(!d.participants.length)d.participants=pair;if(!d.participants.includes(p.actor)&&!(p.organization&&d.participants.includes(p.organization)&&p.canReadInbox))missing();if(p.blocked)missing();};
 const mutate=(p,fn)=>store.transaction(()=>{const d=read();member(d,p);const r=fn(d);write(d);return r;});
 const roomParty=(d,p)=>d.participants.includes(p.actor)?p.actor:p.organization;
 const project=(d,p)=>({friendship:d.friendship,conversation:d.conversation,participants:d.participants,messages:['pending','accepted'].includes(d.conversation.state)||d.conversation.requestedBy===roomParty(d,p)?d.messages.map(({sentBy,operation,...m})=>({...m,images:media.details(m.media,'message:'+m.id)})):[],reads:d.reads});
 return {
  status(p){const d=read();member(d,p);return project(d,p);},
  friendship(p,v){if(pair.some(x=>!x.startsWith('person:')))reject('VALIDATION_FAILED','Draugystė galima tarp asmeninių profilių.');return mutate(p,d=>{const f=d.friendship;version(v.version,f.version);if(v.action==='request'&&['none','declined','cancelled'].includes(f.state)){f.state='pending';f.requestedBy=p.actor;}else if(v.action==='accept'&&f.state==='pending'&&f.requestedBy!==p.actor)f.state='accepted';else if(v.action==='decline'&&f.state==='pending'&&f.requestedBy!==p.actor)f.state='declined';else if(v.action==='cancel'&&f.state==='pending'&&f.requestedBy===p.actor)f.state='cancelled';else if(v.action==='remove'&&f.state==='accepted'){f.state='none';d.conversation.state='none';d.conversation.version++;}else reject('CONFLICT','Draugystės būsena pasikeitė.',409);f.version++;return {...f};});},
  request(p,v){return mutate(p,d=>{const c=d.conversation;if(c.state==='none'){if(p.messagePolicy==='closed'||p.messagePolicy==='friends'&&d.friendship.state!=='accepted')reject('FORBIDDEN','Šis profilis žinučių užklausų nepriima.',403);c.requestedBy=roomParty(d,p);c.state=d.friendship.state==='accepted'?'accepted':'pending';c.version++;}if(c.state==='declined')reject('FORBIDDEN','Pokalbio užklausa atmesta.',403);return {...c};});},
  respond(p,v){return mutate(p,d=>{const c=d.conversation;version(v.version,c.version);if(c.state!=='pending'||c.requestedBy===roomParty(d,p))reject('FORBIDDEN','Negali patvirtinti savo užklausos.',403);c.state=v.accept===true?'accepted':'declined';c.version++;return {...c};});},
  send(p,v){return mutate(p,d=>{const c=d.conversation,actor=roomParty(d,p);if(c.state!=='accepted'&&!(c.state==='pending'&&c.requestedBy===actor&&d.messages.length===0))reject('FORBIDDEN','Pirmiausia turi būti priimta pokalbio užklausa.',403);const operation=target(v.operation),prior=d.messages.find(x=>x.author===actor&&x.operation===operation);if(prior)return prior;if(d.messages.length>=2000)reject('LIMIT','Pasiektas pokalbio limitas.',409);const m={id:randomUUID(),author:actor,sentBy:p.actor,text:text(v.text||'',2000),media:mediaIds(v.media,3),operation,createdAt:store.clock(),version:1,isDemo:p.isDemo===true};if(!m.text&&!m.media.length)reject('VALIDATION_FAILED','Įrašyk žinutę arba pridėk nuotrauką.');media.attach(actor,m.media,'message:'+m.id,3);d.messages.push(m);return m;});},
  read(p,v){return mutate(p,d=>{if(d.conversation.state!=='accepted')reject('FORBIDDEN','Pokalbis dar nepriimtas.',403);const m=d.messages.find(x=>x.id===v.messageId);if(!m)missing();d.reads[roomParty(d,p)]=m.createdAt;return {readAt:m.createdAt};});},
  remove(p,v){return mutate(p,d=>{const m=d.messages.find(x=>x.id===v.id);if(!m||m.author!==roomParty(d,p))missing();version(v.version,m.version);m.text='';m.media=[];m.deleted=true;m.version++;return {id:m.id,version:m.version};});},
  registerMedia(p,v){const d=read();member(d,p);if(d.conversation.state!=='accepted')reject('FORBIDDEN','Nuotraukomis dalintis galima priėmus pokalbį.',403);return media.register(roomParty(d,p),v);},
  readMedia(p,v){const d=read();member(d,p);const m=project(d,p).messages.find(m=>m.id===v.message&&!m.deleted);if(!m||!m.media.includes(v.id))missing();return media.read(v.id,'message:'+m.id,v.width);},
  cleanup(){return store.transaction(()=>{const d=read(),cutoff=monthsBefore(store.clock(),RETENTION_POLICY.messagesMonths),before=d.messages.length;d.messages=d.messages.filter(m=>m.createdAt>=cutoff);if(before!==d.messages.length)write(d);return {messagesRemoved:before-d.messages.length,...media.cleanup(new Set(d.messages.filter(m=>!m.deleted).map(m=>'message:'+m.id)))};});},
  eraseActor(p,v){if(p.maintenance!==true)reject('FORBIDDEN','Šis veiksmas neleidžiamas.',403);return store.transaction(()=>{const d=read();d.messages=d.messages.filter(m=>m.author!==v.target);for(const m of d.messages)if(m.sentBy===v.target)delete m.sentBy;delete d.reads[v.target];if(pair.includes(v.target)){d.friendship={state:'none',requestedBy:null,version:d.friendship.version+1};d.conversation={state:'declined',requestedBy:null,version:d.conversation.version+1};}write(d);media.cleanup(new Set(d.messages.filter(m=>!m.deleted).map(m=>'message:'+m.id)));return {erased:true};});},
  export(p){const d=read();member(d,p);return {participants:d.participants,friendship:d.friendship,conversation:d.conversation,messages:d.messages.filter(m=>m.author===p.actor||m.sentBy===p.actor).map(({sentBy,operation,...m})=>({...m,images:media.details(m.media,'message:'+m.id)}))};},
  resetBlocked(p){return store.transaction(()=>{const d=read();if(!pair.includes(p.actor))missing();d.friendship={state:'none',requestedBy:null,version:d.friendship.version+1};d.conversation={state:'none',requestedBy:null,version:d.conversation.version+1};write(d);return {blocked:true};});},
 };
}
