import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
const fail=(expected,fn)=>assert.throws(fn,e=>e.code===expected);
function fixture(){
 let now=Date.parse('2026-10-07T06:00:00Z');const store=openStore({filename:':memory:',clock:()=>now,secret:'isolated-moderation-'.repeat(3)}),api=createPlatform(store),auth=createAuth(store),login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user;},owner=login('moderation-owner@example.com'),client=login('moderation-client@example.com'),other=login('moderation-other@example.com'),operator={...owner,operator:true},org=api.createOrganization(owner,{name:'Moderation fixture',bio:'Isolated moderation acceptance.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),service=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'kirpimas',label:'Fixture haircut',durationMin:60,priceMinor:2500}),revision=()=>api.submitRevision(owner,{scope,name:org.name,bio:org.bio});api.moderate(operator,{id:revision().id,state:'approved'});
 return {store,api,owner,client,other,operator,org,scope,service,revision,advance:at=>now=at,close:()=>store.close()};
}
test('Reports validate public targets, preserve idempotency and a 72-hour internal review target; versioned decisions journal actor privately and keep bookings',()=>{
 const f=fixture();try{
  const input={target:f.org.id,note:'Isolated profile issue',idempotencyKey:'first'};fail('UNAUTHENTICATED',()=>f.api.report(null,input));fail('NOT_FOUND',()=>f.api.report(f.client,{...input,target:'unknown'}));const r=f.api.report(f.client,input);assert.equal(r.targetKind,'organization');assert.equal(Date.parse(r.dueAt)-Date.parse(r.createdAt),72*3600000);assert.equal(f.api.report(f.client,input).id,r.id);assert.equal(f.api.workspace(f.owner,f.scope).reports.length,0);fail('IDEMPOTENCY_CONFLICT',()=>f.api.report(f.client,{...input,note:'Different issue'}));
  const c=f.api.availability({providerServiceId:f.service.id,dateKey:'2026-10-08',from:900,to:1200}).slots[0],h=f.api.hold(f.client,c),b=f.api.confirm(f.client,{holdId:h.id,name:'Moderation booking',idempotencyKey:'retain'}),decision={id:r.id,version:r.version,state:'triage',action:'record-only',reason:'Isolated review in progress'};fail('FORBIDDEN',()=>f.api.reviewReport(f.owner,decision));fail('INVALID_INPUT',()=>f.api.reviewReport(f.operator,{...decision,reason:''}));fail('INVALID_INPUT',()=>f.api.edit(f.operator,{scope:{role:'operator'},table:'reports',id:r.id,values:{status:'resolved'},version:r.version}));let reviewed=f.api.reviewReport(f.operator,decision);assert.equal(reviewed.actions.at(-1).actorId,f.operator.id);fail('VERSION_CONFLICT',()=>f.api.reviewReport(f.operator,decision));
  reviewed=f.api.reviewReport(f.operator,{...decision,version:reviewed.version,state:'resolved',action:'disable-profile',reason:'Isolated public withdrawal'});assert.equal(f.api.profile(f.org.id),null);assert.equal(f.api.catalog().length,0);const own=f.api.workspace(f.client,{role:'customer'});assert.equal(own.bookings[0].id,b.id);assert.equal(own.reports[0].status,'resolved');assert.equal(own.reports[0].actions.at(-1).actorId,undefined);assert.equal(f.api.workspace(f.other,{role:'customer'}).reports.length,0);assert.equal(f.api.exportCustomer(f.client).reports[0].id,r.id);fail('VERSION_CONFLICT',()=>f.api.reviewReport(f.operator,{...decision,version:reviewed.version}));
 }finally{f.close();}
});
test('Completed review authorship is enforced; media/review withdrawal is audited and a pre-existing revision cannot reintroduce restricted media',()=>{
 const f=fixture();try{
  const c=f.api.availability({providerServiceId:f.service.id,dateKey:'2026-10-08',from:900,to:1200}).slots[0],h=f.api.hold(f.client,c),b=f.api.confirm(f.client,{holdId:h.id,name:'Review fixture',idempotencyKey:'review'});f.advance(Date.parse(b.endAt));f.api.completeBooking(f.owner,{scope:f.scope,id:b.id,version:b.version});let review=f.api.review(f.client,{bookingId:b.id,rating:5,text:'Isolated review'});let d=f.store.read();d.reviews[0].clientId=f.other.id;f.store.write(d);fail('INVALID_INPUT',()=>f.api.moderateReview(f.operator,{id:review.id,state:'approved',version:0}));d=f.store.read();d.reviews[0].clientId=f.client.id;f.store.write(d);review=f.api.moderateReview(f.operator,{id:review.id,state:'approved',version:0});assert.equal(review.actions[0].actorId,f.operator.id);assert.equal(f.api.profile(f.org.id).reviews[0].actions,undefined);
  const r=f.api.report(f.other,{target:review.id,note:'Isolated review report'});fail('INVALID_INPUT',()=>f.api.reviewReport(f.operator,{id:r.id,version:r.version,state:'resolved',action:'hide-media',reason:'Mismatched target'}));f.api.reviewReport(f.operator,{id:r.id,version:r.version,state:'resolved',action:'hide-review',reason:'Isolated review withdrawal'});assert.equal(f.api.profile(f.org.id).reviews.length,0);assert.equal(f.api.workspace(f.client,{role:'customer'}).reviews[0].actions.at(-1).actorId,undefined);
  const asset={id:'asset-isolated-moderation',organizationId:f.org.id,usage:'gallery',alt:'Isolated asset',rights:'Isolated test asset rights',variants:[]};f.api.attachMedia(f.owner,asset);fail('NOT_FOUND',()=>f.api.report(f.client,{target:asset.id,note:'Private asset'}));f.api.moderate(f.operator,{id:f.revision().id,state:'approved'});const pending=f.revision(),mediaReport=f.api.report(f.client,{target:asset.id,note:'Isolated media report'});f.api.reviewReport(f.operator,{id:mediaReport.id,version:1,state:'resolved',action:'hide-media',reason:'Isolated media rights review'});assert.equal(f.api.profile(f.org.id).gallery.length,0);fail('MEDIA_RESTRICTED',()=>f.api.moderate(f.operator,{id:pending.id,state:'approved'}));assert.equal(f.api.workspace(f.owner,f.scope).media[0].moderationState,'restricted');assert.equal(f.api.workspace(f.owner,f.scope).organizations[0].draftGallery.length,0);
 }finally{f.close();}
});
