import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {csvCell} from './operations.mjs';
const code=(c,fn)=>assert.throws(fn,e=>e.code===c);
function fixture(){
 let now=Date.parse('2026-10-07T06:00:00Z');const store=openStore({filename:':memory:',clock:()=>now,secret:'isolated-operations-'.repeat(3)}),api=createPlatform(store),auth=createAuth(store),login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user;},owner=login('operation-owner@example.com'),client=login('operation-client@example.com'),other=login('operation-other@example.com'),operator={...owner,operator:true},org=api.createOrganization(owner,{name:'Operations fixture',bio:'Isolated rules and reporting.',kind:'salon',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),p=w.practitioners[0],r=w.resources[0],service=api.createService(owner,{organizationId:org.id,practitionerId:p.id,resourceId:r.id,taxonomyServiceId:'kirpimas',label:'=Formula label',durationMin:60,priceMinor:2500});const rev=api.submitRevision(owner,{scope,name:org.name,bio:org.bio});api.moderate(operator,{id:rev.id,state:'approved'});
 return {store,api,owner,client,other,operator,org:api.workspace(owner,scope).organizations[0],scope,p,r,service,at:v=>{now=v;},close:()=>store.close()};
}
test('Organization and variant availability rules apply together, stale holds revalidate closure, and a closure cannot conceal a confirmed visit',()=>{
 const f=fixture();try{
  const input={providerServiceId:f.service.id,dateKey:'2026-10-08',from:900,to:1200},c=f.api.availability(input).slots[0],h=f.api.hold(f.client,c),rules={organizationId:f.org.id,version:f.org.version,minLeadTimeMin:30,maxAdvanceDays:5,weekdays:['Mon','Tue','Wed','Thu','Fri'],closedDates:['2026-10-08']};code('FORBIDDEN',()=>f.api.saveBookingRules(f.other,rules));let o=f.api.saveBookingRules(f.owner,rules);assert.equal(f.api.availability(input).slots.length,0);code('SLOT_CONFLICT',()=>f.api.confirm(f.client,{holdId:h.id,name:'Closure',idempotencyKey:'closed'}));f.api.releaseHold(f.client,h.id);
  o=f.api.saveBookingRules(f.owner,{...rules,version:o.version,closedDates:[]});code('VERSION_CONFLICT',()=>f.api.saveBookingRules(f.owner,rules));assert.equal(f.api.availability({...input,dateKey:'2026-10-15'}).slots.length,0);
  const ready=f.api.availability(input).slots[0],held=f.api.hold(f.client,ready),b=f.api.confirm(f.client,{holdId:held.id,name:'Closure guard',idempotencyKey:'open'});code('SCHEDULE_CONFLICT',()=>f.api.saveBookingRules(f.owner,{...rules,version:o.version}));assert.equal(f.api.workspace(f.client,{role:'customer'}).bookings[0].id,b.id);
  const offers=f.api.selectProcedures(f.owner,{organizationId:f.org.id,version:0,procedureIds:['kirpimai-moteru-kirpimas'],idempotencyKey:'mode'});let offer=f.api.saveOffer(f.owner,{id:offers[0].id,version:1,label:'Consultation',bookingMode:'consultation',variants:[{id:'consultation-rule',label:'Discuss first',priceMinor:3000,durationMin:60,availabilityRules:{weekdays:['Fri'],minLeadTimeMin:1440,maxAdvanceDays:2,fromMin:900,toMin:1080},staffOptions:[{practitionerId:f.p.id,resourceId:f.r.id}]}]});offer=f.api.submitOffer(f.owner,{id:offer.id,version:offer.version});f.api.moderateOffer(f.operator,{id:offer.id,version:offer.version,state:'approved'});assert.equal(f.api.availability({providerServiceId:'consultation-rule',dateKey:'2026-10-09',from:900,to:1200}).slots.length,0);assert.ok(f.api.createInquiry(f.client,{organizationId:f.org.id,providerServiceId:'consultation-rule',note:'Discuss this service'}));
  offer=f.api.workspace(f.owner,f.scope).offers[0];offer=f.api.saveOffer(f.owner,{...offer,bookingMode:'instant'});offer=f.api.submitOffer(f.owner,{id:offer.id,version:offer.version});f.api.moderateOffer(f.operator,{id:offer.id,version:offer.version,state:'approved'});const friday={providerServiceId:'consultation-rule',dateKey:'2026-10-09',from:840,to:1200};assert.equal(f.api.availability({...friday,dateKey:'2026-10-08'}).slots.length,0);let selected=f.api.availability(friday).slots;assert.ok(selected.length);assert.ok(selected.every(c=>c.startAt>='2026-10-09T12:00:00.000Z'&&c.endAt<='2026-10-09T15:00:00.000Z'));f.at(Date.parse('2026-10-08T12:01:00Z'));selected=f.api.availability(friday).slots;assert.ok(selected.length);assert.ok(selected.every(c=>Date.parse(c.startAt)>=f.store.clock()+1440*60000));
  f.api.grantMembership(f.owner,{organizationId:f.org.id,email:f.other.email,role:'practitioner',practitionerId:f.p.id,version:0});code('FORBIDDEN',()=>f.api.saveBookingRules(f.other,{...rules,version:o.version,closedDates:[]}));code('FORBIDDEN',()=>f.api.organizationReport(f.other,{organizationId:f.org.id,from:'2026-10-08',to:'2026-10-09'}));
 }finally{f.close();}
});
test('Scoped reports define occupancy/returning/cancellation/waitlist denominators and quote service value; CSV neutralizes formulas and excludes contact data',()=>{
 const f=fixture();try{
  const book=(date,key)=>{const c=f.api.availability({providerServiceId:f.service.id,dateKey:date,from:900,to:1200}).slots[0],h=f.api.hold(f.client,c);return f.api.confirm(f.client,{holdId:h.id,name:'Report fixture',idempotencyKey:key});},first=book('2026-10-08','first'),second=book('2026-10-09','second'),third=book('2026-10-12','third');f.api.cancelBooking(f.client,{id:third.id,version:third.version,reason:'Count cancellation'});f.api.createInquiry(f.client,{organizationId:f.org.id,providerServiceId:f.service.id,note:'No causal booking assumption'});f.at(Date.parse('2026-10-10T06:00:00Z'));f.api.completeBooking(f.owner,{scope:f.scope,id:first.id,version:first.version});f.api.completeBooking(f.owner,{scope:f.scope,id:second.id,version:second.version});
  const input={organizationId:f.org.id,from:'2026-10-08',to:'2026-10-12'},r=f.api.organizationReport(f.owner,input);assert.equal(r.statuses.find(s=>s.status==='completed').serviceValueMinor,5000);assert.equal(r.occupancy.reservedMin,120);assert.equal(r.occupancy.scheduledMin,1800);assert.equal(r.cancellations.total,3);assert.equal(r.cancellations.count,1);assert.equal(r.returningClients.count,1);assert.equal(r.returningClients.total,1);assert.equal(r.waitlist.rate,null);assert.equal(r.inquiries.count,0);assert.equal(r.visits[0].clientId,undefined);code('FORBIDDEN',()=>f.api.organizationReport(f.other,input));code('INVALID_INPUT',()=>f.api.organizationReport(f.owner,{...input,from:'2026-01-01'}));
  const csv=f.api.reportCsv(f.owner,input);assert.match(csv,/"'=Formula label"/);assert.doesNotMatch(csv,/operation-client@example.com|Report fixture/);assert.equal(csvCell('   @SUM(1)'), '"\'   @SUM(1)"');assert.equal(csvCell('\t=1'),'"\'\t=1"');assert.equal(csvCell('He said "yes"'),'"He said ""yes"""');
 }finally{f.close();}
});
