import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {createApiHandler} from './http-core.mjs';
import {createOrganizationHandoff,createOrganizationStaging,organizationTransferProof} from './organization-handoff.mjs';
import {createOrganizationCommit,createOrganizationAuthority} from './organization-authority.mjs';
import {createOrganizationDirectory,createOrganizationCommand} from './organization-directory.mjs';
import {ApiError} from './primitives.mjs';
import {createDirectoryCacheIssuer} from './organization-directory-cache.mjs';
const now=Date.parse('2026-10-08T06:00:00Z'),secret='isolated-directory-acceptance-'.repeat(3),origin='https://directory-fixture.test';
function fixture({activate=true,large=false}={}){
 const source=openStore({filename:':memory:',secret,clock:()=>now}),target=openStore({filename:':memory:',secret,clock:()=>now}),auth=createAuth(source),api=createPlatform(source),sessions={};
 const users={owner:{id:'directory-owner',email:'directory-owner@example.com',name:'Owner'},client:{id:'directory-client',email:'directory-client@example.com',name:'Client'},foreign:{id:'directory-foreign',email:'directory-foreign@example.com',name:'Foreign'},reception:{id:'directory-reception',email:'directory-reception@example.com',name:'Reception'}};
 for(const [role,u]of Object.entries(users)){source.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(u.id,source.siteId,u.email,u.name,role==='owner'?1:0,now);source.ensureClient(u.id);const s=auth.session(null);source.db.prepare('UPDATE sessions SET account_id=? WHERE token_hash=?').run(u.id,s.token_hash);sessions[role]=s;}
 const make=name=>{const org=api.createOrganization(users.owner,{name,bio:'Isolated directory test.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(users.owner,scope),service=api.createService(users.owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Original directory service',durationMin:60,priceMinor:2500});api.moderate({...users.owner,operator:true},{id:api.submitRevision(users.owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,scope,service};};
 const a=make('Directory A'),b=make('Directory B'),membership=api.grantMembership(users.owner,{organizationId:a.org.id,email:users.reception.email,role:'reception',version:0}),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0];
 const first=api.confirm(users.client,{holdId:api.hold(users.client,candidate(a)).id,idempotencyKey:'retained-directory',name:'Original client'}),other=api.confirm(users.client,{holdId:api.hold(users.client,candidate(b)).id,idempotencyKey:'other-directory',name:'Original client'}),hold=api.hold(users.client,candidate(a));
 if(large){const data=source.read();for(let n=0;n<14;n++)data.messages.push({id:'large-directory-message-'+n,organizationId:a.org.id,bookingId:first.id,clientId:users.client.id,text:'x'.repeat(90000),createdAt:new Date(now).toISOString()});source.write(data);}
 const handoff=createOrganizationHandoff(source),frozen=handoff.freeze({operatorAccountId:users.owner.id,organizationId:a.org.id,epoch:0,requestKey:'directory-fixture'}),control={operatorAccountId:users.owner.id,organizationId:a.org.id,epoch:frozen.epoch,handoffId:frozen.handoffId},stage=createOrganizationStaging(target,{targetName:frozen.targetName});
 let offset=0;do{const page=handoff.page({...control,offset});stage.accept(page);offset=page.nextOffset;if(page.done)break;}while(true);
 const commit=createOrganizationCommit(source),authority=createOrganizationAuthority(target,{targetName:frozen.targetName}),receipt=authority.prepare(commit.context(control));commit.seal({...control,targetReceipt:receipt});if(activate)authority.activate(commit.seal({...control,targetReceipt:receipt}));
 const command=createOrganizationCommand(target,{targetName:frozen.targetName}),directory=createOrganizationDirectory(source,{getTarget:name=>{assert.equal(name,frozen.targetName);return {executeDirectoryCommand:packet=>command.execute(packet)};}}),handler=createApiHandler(source,{origin,secure:true,media:{},dispatch:directory.dispatch});
 async function request(role,method,input={},options={}){const s=sessions[role],body=JSON.stringify({method,input,siteId:options.siteId||source.siteId}),req={url:options.url||'/api/madbeauty/rpc',method:options.verb||'POST',headers:{host:new URL(origin).host,origin,'content-type':'application/json',cookie:'__Host-madbeauty_sid='+s.token,'x-csrf-token':s.csrf,...options.headers},socket:{remoteAddress:'127.0.0.1'},async *[Symbol.asyncIterator](){yield Buffer.from(body);}},res={writeHead(status,headers){this.status=status;this.headers=headers;},end(body){this.data=JSON.parse(body);}};await handler.handle(req,res);return {status:res.status,...res.data};}
 return {source,target,users,sessions,auth,api,a,b,first,other,hold,membership,frozen,control,command,directory,request,close:()=>{source.close();target.close();}};
}
test('Ordinary authenticated HTTP routes old and new IDs to one active calendar; current search, customer and professional workspaces and revoked session roles agree',async()=>{
 const f=fixture();try{
  const next=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-new-confirm',name:'Original client'});assert.equal(next.status,200,JSON.stringify(next));const booking=next.result;assert.notEqual(booking.id,f.first.id);assert.equal(booking.priceMinor,2500);
  assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-new-confirm',name:'Original client'})).result.id,booking.id);
  const customer=await f.request('client','workspace',{role:'customer'}),professional=await f.request('owner','workspace',f.a.scope),unmigrated=await f.request('owner','workspace',f.b.scope);assert.equal(unmigrated.status,200,JSON.stringify(unmigrated));assert.equal(unmigrated.result.bookings[0].id,f.other.id);assert.equal(unmigrated.result.bookings.some(b=>b.id===booking.id),false);assert.equal(customer.result.bookings.filter(b=>b.id===booking.id).length,1);assert.equal(customer.result.bookings.find(b=>b.id===f.other.id).organizationId,f.b.org.id);assert.equal(professional.result.bookings.find(b=>b.id===booking.id).id,booking.id);
  const changed=await f.request('owner','edit',{scope:f.a.scope,table:'services',id:f.a.service.id,version:1,values:{label:'Current target service',priceMinor:3200}});assert.equal(changed.status,200,JSON.stringify(changed));
  const search=await f.request('client','searchResults',{anyTime:true,sort:'price'});assert.equal(search.result.treatments.filter(s=>s.id===f.a.service.id).length,1);assert.equal(search.result.treatments.find(s=>s.id===f.a.service.id).priceMinor,3200);assert.equal((await f.request('client','profile',{id:f.a.org.id})).result.services[0].label,'Current target service');assert.equal((await f.directory.dispatch('catalog',null,{})).find(s=>s.id===f.a.service.id).priceMinor,3200);
  f.source.db.prepare('DELETE FROM organization_directory_refs').run();const message=await f.request('client','message',{bookingId:booking.id,text:'Recover missing new ID index'});assert.equal(message.status,200,JSON.stringify(message));assert.equal(message.result.bookingId,booking.id);
  const foreign=await f.request('foreign','workspace',{role:'customer',clientId:f.users.client.id,operator:true});assert.equal(foreign.result.bookings.length,0);assert.equal((await f.request('foreign','cancelBooking',{id:booking.id,version:1,reason:'Spoofed user',user:f.users.client,operator:true})).status,403);
  assert.equal((await f.request('reception',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),true);assert.equal((await f.request('owner','revokeMembership',{id:f.membership.id,version:1})).status,200);assert.equal((await f.request('reception',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await f.request('reception','workspace',f.a.scope)).status,403);
  assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);assert.equal(f.source.recordById('bookings',booking.id),null);assert.equal(f.source.recordById('services',f.a.service.id).priceMinor,2500);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,1);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,0);
 }finally{f.close();}
});
test('HTTP security checks precede routing; prepared/unreachable targets never fall back, and admitted identities cannot create a new global account on a target',async()=>{
 const f=fixture({activate:false});try{
  const before=f.target.readCollections(['bookings','holds']);assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'prepared-denied',name:'Client'})).status,503);assert.deepEqual(f.target.readCollections(['bookings','holds']),before);
  assert.equal((await f.request('client','confirm',{}, {headers:{origin:'https://foreign.test'}})).status,403);assert.equal((await f.request('client','confirm',{}, {headers:{'x-csrf-token':'bad'}})).error.code,'CSRF');assert.equal((await f.request('client','confirm',{}, {siteId:'foreign-site'})).error.code,'SITE_SCOPE');
  const unreachable=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:()=>{throw Error('Isolated namespace outage');}})});await assert.rejects(unreachable.dispatch('cancelBooking',f.users.client,{id:f.first.id,version:1,reason:'No fallback'}),e=>e.code==='ORGANIZATION_UNAVAILABLE');assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);
 }finally{f.close();}
 const active=fixture();try{assert.equal(active.target.recordById('clients',active.users.foreign.id),null);const slot=(await active.request('foreign','availability',{providerServiceId:active.a.service.id,dayOffset:1,from:900,to:1200,addons:[]})).result.slots[0],before=active.target.readCollections(['holds']).holds.length;const admitted=await active.request('foreign','hold',slot);assert.equal(admitted.status,200,JSON.stringify(admitted));assert.equal(active.target.readCollections(['holds']).holds.length,before+1);assert.equal(active.target.recordById('clients',active.users.foreign.id).id,active.users.foreign.id);assert.equal(active.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(active.users.foreign.id).operator,0);assert.equal(active.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal((await active.request('owner','createClient',{organizationId:active.a.org.id,email:'unadmitted@example.com',name:'Denied'})).error.code,'GLOBAL_IDENTITY_REQUIRED');assert.equal(active.source.db.prepare('SELECT id FROM accounts WHERE email=?').get('unadmitted@example.com'),undefined);}finally{active.close();}
});
test('Committed OTP rotation survives a temporary organization-session lookup failure and recovers with its new secure cookie',async()=>{
 const store=openStore({filename:':memory:',secret,clock:()=>now}),auth=createAuth(store),api=createPlatform(store);let unavailable=true;
 const handler=createApiHandler(store,{origin,secure:true,media:{},dispatch:(method,user,input)=>{if(method==='session'&&unavailable)throw new ApiError('ORGANIZATION_UNAVAILABLE','Isolated lookup failure',503);return api.session(user);}});
 async function request(session,url,input={},verb='POST'){const req={url,method:verb,headers:{host:new URL(origin).host,origin,'content-type':'application/json',cookie:'__Host-madbeauty_sid='+session.token,'x-csrf-token':session.csrf},socket:{remoteAddress:'127.0.0.1'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(input));}},res={writeHead(status,headers){this.status=status;this.headers=headers;},end(body){this.data=JSON.parse(body);}};await handler.handle(req,res);return res;}
 try{
  const session=auth.session(null),challenge=auth.start(session,'rotation-directory@example.com','127.0.0.1'),verified=await request(session,'/api/madbeauty/auth/verify',{challengeId:challenge.challengeId,code:store.capture(challenge.challengeId).code});assert.equal(verified.status,503);const setCookie=verified.headers['Set-Cookie'];assert.ok(setCookie.startsWith('__Host-madbeauty_sid='));assert.ok(setCookie.includes('; Secure'));assert.ok(setCookie.includes('; HttpOnly'));const token=setCookie.split(';')[0].split('=')[1];assert.notEqual(token,session.token);assert.equal(auth.session(session.token,{create:false}),null);
  unavailable=false;const recovered=await request({token},'/api/madbeauty/session',{},'GET');assert.equal(recovered.status,200);assert.equal(recovered.data.user.email,'rotation-directory@example.com');assert.ok(recovered.data.csrf);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM accounts WHERE email=?').get('rotation-directory@example.com').n,1);
 }finally{store.close();}
});
test('Signed command scope, expiry and durable nonce replay protect post-write rollback; lost central registration recovers a confirmation without duplicate booking or mail',async()=>{
 const f=fixture();try{
  const cache=createDirectoryCacheIssuer(f.source),packet=body=>{const value={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'isolated-command-nonce',expiresAt:now+20000,method:'createResource',actor:{...f.users.owner,operator:true},input:{organizationId:f.a.org.id,label:'Nonce protected'},cache:cache.issue(f.users.owner.id),...body};return {...value,proof:organizationTransferProof(f.source,'directory-command',value)};};
  const value=packet();assert.equal(f.command.execute({...value,epoch:99}).error.code,'FORBIDDEN');assert.equal(f.command.execute(packet({expiresAt:now})).error.code,'INVALID_INPUT');assert.equal(f.command.execute(packet({organizationId:f.b.org.id})).error.code,'ORGANIZATION_UNAVAILABLE');const once=f.command.execute(value),twice=f.command.execute(value);assert.equal(once.result.id,twice.result.id);assert.equal(f.target.organizationRecords('resources',f.a.org.id).filter(r=>r.id===once.result.id).length,1);assert.equal(f.command.execute(packet({input:{organizationId:f.a.org.id,label:'Different command'}})).error.code,'IDEMPOTENCY_CONFLICT');
  const prepare=f.target.db.prepare.bind(f.target.db),before=f.target.readCollections(['bookings','holds']);f.target.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO mail_outbox')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated command post-mail failure');}}:s;};let result=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'});assert.equal(result.error.code,'SERVER_ERROR');f.target.db.prepare=prepare;assert.deepEqual(f.target.readCollections(['bookings','holds']),before);assert.equal(f.target.db.prepare("SELECT COUNT(*) AS n FROM organization_directory_commands WHERE response LIKE '%lost-directory-confirm%'").get().n,0);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=sourcePrepare(q);return q.startsWith('INSERT INTO organization_directory_refs')?{...s,run:()=>{throw Error('Isolated central registration failure');}}:s;};result=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'});assert.equal(result.status,500);f.source.db.prepare=sourcePrepare;const confirmed=f.target.clientRecords('bookings',f.users.client.id).find(b=>b.id!==f.first.id);assert.ok(confirmed);assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'})).result.id,confirmed.id);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(confirmed.id).n,1);assert.equal((await f.request('client','workspace',{role:'customer'})).result.bookings.filter(b=>b.id===confirmed.id).length,1);
 }finally{f.close();}
});
test('Central operator, customer export and erasure review aggregate current owned target records without replacing global identity or bypassing recent OTP',async()=>{
 const f=fixture();try{
  const next=(await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-export-confirm',name:'Original client'})).result;assert.ok(next.id);
  assert.equal((await f.request('owner','edit',{scope:f.a.scope,table:'services',id:f.a.service.id,version:1,values:{priceMinor:3400}})).status,200);
  const operator=await f.request('owner','workspace',{role:'operator'});assert.equal(operator.status,200,JSON.stringify(operator));assert.equal(operator.result.services.find(s=>s.id===f.a.service.id).priceMinor,3400);assert.equal(operator.result.organizations.filter(o=>o.id===f.a.org.id).length,1);assert.equal(operator.result.clients.length,0);assert.equal(operator.result.bookings.length,0);assert.equal(operator.result.outbox.filter(m=>m.bookingId===next.id).length,1);assert.equal((await f.request('client','workspace',{role:'operator',operator:true})).status,403);
  const exported=await f.request('client',null,{}, {verb:'GET',url:'/api/madbeauty/customer-data'});assert.equal(exported.status,200,JSON.stringify(exported));assert.equal(exported.bookings.filter(b=>b.id===next.id).length,1);assert.equal(exported.bookings.find(b=>b.id===f.other.id).organizationId,f.b.org.id);assert.equal(exported.client.id,f.users.client.id);assert.equal((await f.request('foreign','exportCustomer',{clientId:f.users.client.id})).result.bookings.length,0);
  const request=(await f.request('client','requestErasure',{confirmEmail:f.users.client.email})).result;assert.ok(request.id);const review=await f.request('owner','erasureCase',{id:request.id});assert.equal(review.status,200,JSON.stringify(review));assert.equal(review.result.futureBookings.filter(b=>b.id===next.id).length,1);assert.equal(review.result.executionEnabled,false);
  f.source.db.prepare('UPDATE sessions SET created_at=? WHERE account_id=?').run(now-600001,f.users.client.id);assert.equal((await f.request('client','exportCustomer',{verifiedAt:now})).error.code,'REAUTH_REQUIRED');assert.equal((await f.request('client',null,{}, {verb:'GET',url:'/api/madbeauty/customer-data'})).error.code,'REAUTH_REQUIRED');assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);
 }finally{f.close();}
});

test('A first OTP sign-in after handoff books with current central preferences and returns its confirmed name to the central account exactly once',async()=>{
 const f=fixture();try{
  const anonymous=f.auth.session(null),challenge=f.auth.start(anonymous,'new-after-handoff@example.com','127.0.0.1'),verified=f.auth.verify(anonymous,challenge.challengeId,f.source.capture(challenge.challengeId).code,'127.0.0.1');f.sessions.fresh=verified.session;f.users.fresh=verified.user;
  assert.equal(verified.user.name,'');assert.equal(f.target.recordById('clients',verified.user.id),null);
  f.api.preferences(verified.user,{service:false,marketing:false,reminderLeadMin:0});
  const availability=await f.request('fresh','availability',{providerServiceId:f.a.service.id,dayOffset:1,from:900,to:1200,addons:[]}),candidate=availability.result.slots[0],hold=await f.request('fresh','hold',candidate);assert.equal(hold.status,200,JSON.stringify(hold));
  assert.equal(f.target.clientRecords('preferences',verified.user.id)[0].service,false);assert.equal(f.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(verified.user.id).operator,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM email_challenges').get().n,0);
  const confirmed=await f.request('fresh','confirm',{holdId:hold.result.id,idempotencyKey:'fresh-after-handoff',name:'Naujas klientas'});assert.equal(confirmed.status,200,JSON.stringify(confirmed));const booking=confirmed.result;
  assert.equal(f.source.recordById('clients',verified.user.id).name,'Naujas klientas');assert.equal(f.source.recordById('clients',verified.user.id).version,2);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(verified.user.id).name,'Naujas klientas');assert.equal(f.source.recordById('bookings',booking.id),null);
  assert.equal((await f.request('fresh','confirm',{holdId:hold.result.id,idempotencyKey:'fresh-after-handoff',name:'Naujas klientas'})).result.id,booking.id);assert.equal(f.source.recordById('clients',verified.user.id).version,2);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM notification_jobs WHERE booking_id=?').get(booking.id).n,0);
  const customer=await f.request('fresh','workspace',{role:'customer'}),professional=await f.request('owner','workspace',f.a.scope);assert.equal(customer.result.client.name,'Naujas klientas');assert.equal(customer.result.bookings.filter(b=>b.id===booking.id).length,1);assert.equal(professional.result.clients.find(c=>c.id===verified.user.id).name,'Naujas klientas');
 }finally{f.close();}
});

test('Fresh signed cache rejects identity substitution, operator creation and reordering; denied capabilities and post-cache failures roll back admission',async()=>{
 const f=fixture();try{
  const issuer=createDirectoryCacheIssuer(f.source),actor={...f.users.foreign,operator:false},packet=(cache,input={})=>{const body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'cache-'+cache.sequence,expiresAt:now+20000,method:'session',actor,input,cache};return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};},resign=packet=>{const {proof,...body}=packet;return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};};
  const first=issuer.issue(actor.id),bad=structuredClone(first);bad.accounts[0].id=f.users.client.id;assert.equal(f.command.execute(packet(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.accounts[0].id=actor.id;bad.accounts[0].operator=1;assert.equal(f.command.execute(packet(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');assert.equal(f.target.recordById('clients',actor.id),null);
  const denied=packet(first);denied.method='createResource';denied.input={organizationId:f.a.org.id,label:'Forbidden admission'};assert.equal(f.command.execute(resign(denied)).error.code,'FORBIDDEN');assert.equal(f.target.recordById('clients',actor.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(actor.id),undefined);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
  const prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const statement=prepare(q);return q.startsWith('INSERT INTO organization_directory_cache')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated cache post-write failure');}}:statement;};assert.equal(f.command.execute(packet(first)).error.code,'SERVER_ERROR');f.target.db.prepare=prepare;assert.equal(f.target.recordById('clients',actor.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(actor.id),undefined);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_directory_cache').get().n,0);
  f.api.preferences(actor,{service:false,marketing:true,reminderLeadMin:0});const newer=issuer.issue(actor.id);assert.ok(f.command.execute(packet(newer)).result);assert.equal(f.target.clientRecords('preferences',actor.id)[0].service,false);assert.equal(f.command.execute(packet(first)).error.code,'STALE_DIRECTORY_CONTEXT');assert.equal(f.target.clientRecords('preferences',actor.id)[0].service,false);
  assert.throws(()=>f.target.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(actor.id),/GLOBAL_IDENTITY_REQUIRED/);assert.throws(()=>f.target.db.prepare("UPDATE state_rows SET data='{}' WHERE collection='preferences'").run(),/ORGANIZATION_TARGET_FENCED/);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Source taxonomy archival reaches target public eligibility, and a lost identity reply recovers without overwriting a newer central name',async()=>{
 const f=fixture();try{
  assert.equal((await f.directory.dispatch('catalog',null,{})).some(s=>s.id===f.a.service.id),true);
  const archived=[],archive=id=>{for(const n of f.api.taxonomy().nodes.filter(n=>n.parentId===id))archive(n.id);f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:id,operation:'archive',version:f.api.taxonomy().version});archived.push(id);};archive('manikiuras');assert.equal((await f.directory.dispatch('catalog',null,{})).some(s=>s.id===f.a.service.id),false);assert.equal(f.target.readCollections(['taxonomyVersion']).taxonomyVersion,f.source.readCollections(['taxonomyVersion']).taxonomyVersion);
  for(const id of archived.reverse())f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:id,operation:'restore',version:f.api.taxonomy().version});
  const prepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO directory_identity_receipts')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated receipt post-write failure');}}:s;};const before=f.source.recordById('clients',f.users.client.id),first=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'});assert.equal(first.status,500);f.source.db.prepare=prepare;assert.deepEqual(f.source.recordById('clients',f.users.client.id),before);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(f.users.client.id).name,before.name);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_identity_receipts').get().n,0);
  const retry=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'});assert.equal(retry.status,200,JSON.stringify(retry));assert.equal(f.source.recordById('clients',f.users.client.id).name,'Perduotas vardas');assert.equal(f.source.recordById('clients',f.users.client.id).version,before.version+1);
  const view=f.source.readClient(f.users.client.id);view.clients[0].name='Vėliau pakeistas vardas';view.clients[0].version++;f.source.transaction(()=>{f.source.db.prepare('UPDATE accounts SET name=? WHERE id=?').run(view.clients[0].name,f.users.client.id);f.source.writeClient(view);});assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'})).result.id,retry.result.id);assert.equal(f.source.recordById('clients',f.users.client.id).name,'Vėliau pakeistas vardas');assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(retry.result.id).n,1);
 }finally{f.close();}
});

test('An overtaken cache is refreshed once before a business write; oversized context never advances its issue version and row metadata remains exact above the legacy envelope',async()=>{
 const f=fixture({large:true});try{
  const issuer=createDirectoryCacheIssuer(f.source),candidate=(await f.directory.dispatch('availability',null,{providerServiceId:f.a.service.id,dayOffset:1,from:900,to:1200,addons:[]})).slots[0],before=f.target.readCollections(['holds']).holds.length;let calls=0;
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{calls++;if(calls===1){const {proof,...body}=packet,newer={...body,nonce:'overtaking-cache',method:'session',input:{},cache:issuer.issue(body.actor.id)};assert.ok(f.command.execute({...newer,proof:organizationTransferProof(f.source,'directory-command',newer)}).result);}return f.command.execute(packet);}})});
  const held=await directory.dispatch('hold',f.users.foreign,candidate);assert.ok(held.id);assert.equal(calls,2);assert.equal(f.target.readCollections(['holds']).holds.length,before+1);assert.equal(f.target.rowStats().legacyMirrored,false);
  f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:'manikiuras',operation:'aliases',aliases:['Manikiūro paslauga'],version:f.api.taxonomy().version});await f.directory.dispatch('catalog',null,{});assert.equal(f.target.rowStats().bytes,Buffer.byteLength(JSON.stringify(f.target.read())));assert.equal(f.target.rowStats().records,f.target.db.prepare('SELECT COUNT(*) AS n FROM state_rows').get().n);
  const version=f.source.db.prepare('SELECT sequence FROM directory_cache_issues').get().sequence,read=f.source.readCollections;f.source.readCollections=fields=>fields.includes('taxonomy')?{taxonomy:[{id:'oversized-context',label:'x'.repeat(1024*1024)}]}:read(fields);assert.throws(()=>issuer.issue(f.users.foreign.id),e=>e.code==='CAPACITY');f.source.readCollections=read;assert.equal(f.source.db.prepare('SELECT sequence FROM directory_cache_issues').get().sequence,version);
 }finally{f.close();}
});

test('Customer opt-out commits central intent and unmigrated reminders atomically, reconciles target jobs, and retains latest durable work through outage or post-target failure',async()=>{
 const f=fixture();try{
  const jobs=bookingId=>f.target.db.prepare('SELECT state,lead_min FROM notification_jobs WHERE booking_id=?').all(bookingId);assert.equal(jobs(f.first.id)[0].state,'planned');
  const off=await f.request('client','preferences',{service:false,marketing:true,reminderLeadMin:0});assert.equal(off.status,200,JSON.stringify(off));assert.equal(off.result.synchronization,'applied');assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');assert.equal(f.source.db.prepare('SELECT state FROM notification_jobs WHERE booking_id=?').get(f.other.id).state,'suppressed');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  let outage=true;const interrupted=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{if(outage)throw Error('Isolated control delivery outage');return f.command.execute(packet);}})});
  const pending=await interrupted.dispatch('preferences',f.users.client,{service:true,marketing:false,reminderLeadMin:120});assert.equal(pending.synchronization,'pending');assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.ok(interrupted.nextControlAt());assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,1);
  const latest=await interrupted.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0});assert.equal(latest.synchronization,'pending');const revision=f.source.db.prepare('SELECT revision FROM directory_customer_controls').get().revision;outage=false;assert.equal(await interrupted.flushCustomerControls(f.users.client.id),false);assert.equal(f.target.db.prepare('SELECT revision FROM organization_customer_controls WHERE client_id=?').get(f.users.client.id).revision,revision);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  const prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const statement=prepare(q);return q.startsWith('INSERT INTO organization_customer_controls')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated reconciliation post-write failure');}}:statement;};const retry=await f.request('client','preferences',{service:true,marketing:false,reminderLeadMin:1440});assert.equal(retry.status,200);assert.equal(retry.result.synchronization,'pending');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');f.target.db.prepare=prepare;await f.directory.flushCustomerControls(f.users.client.id);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(jobs(f.first.id)[0].state,'planned');
  let lostReply=true;const recovery=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{const result=f.command.execute(packet);if(lostReply){lostReply=false;throw Error('Isolated lost committed control response');}return result;}})}),mailBefore=f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n;assert.equal((await recovery.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0})).synchronization,'pending');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,1);assert.equal(await recovery.flushCustomerControls(f.users.client.id),false);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n,mailBefore);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db),before=f.source.clientRecords('preferences',f.users.client.id)[0];f.source.db.prepare=q=>{const statement=sourcePrepare(q);return q.startsWith('INSERT INTO directory_customer_controls')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated central intent post-write failure');}}:statement;};const rollback=await f.request('client','preferences',{service:true,marketing:true,reminderLeadMin:1440});assert.equal(rollback.status,500);f.source.db.prepare=sourcePrepare;assert.deepEqual(f.source.clientRecords('preferences',f.users.client.id)[0],before);assert.equal(f.source.db.prepare('SELECT state FROM notification_jobs WHERE booking_id=?').get(f.other.id).state,'suppressed');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  assert.equal((await f.request('foreign','applyCustomerControls',{revision:999,clientId:f.users.client.id})).status,404);
 }finally{f.close();}
});

test('Overlapping preference deliveries cannot acknowledge a later intent or restore an older central value',async()=>{
 const f=fixture();try{
  let release,arrived;const signal=new Promise(r=>arrived=r),delay=new Promise(r=>release=r);let count=0;
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:async packet=>{if(++count===1){arrived();await delay;}return f.command.execute(packet);}})});
  const first=directory.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0});await signal;const second=await directory.dispatch('preferences',f.users.client,{service:true,marketing:true,reminderLeadMin:120});assert.equal(second.synchronization,'applied');release();const older=await first;assert.equal(older.synchronization,'superseded');assert.equal(older.service,true);assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Existing central email identities become salon clients and versioned team members without replacing global names or creating target login authority',async()=>{
 const f=fixture();try{
  const globalBefore=f.source.recordById('clients',f.users.foreign.id);
  f.source.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(f.users.foreign.id);
  const added=await f.request('owner','createClient',{organizationId:f.a.org.id,email:' DIRECTORY-FOREIGN@EXAMPLE.COM ',name:'Salono kliento vardas',recipientId:f.users.client.id});
  assert.equal(added.status,200,JSON.stringify(added));assert.equal(added.result.id,f.users.foreign.id);
  assert.deepEqual(f.source.recordById('clients',f.users.foreign.id),globalBefore);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(f.users.foreign.id).name,'Foreign');
  assert.equal(f.target.recordById('clients',f.users.foreign.id).name,'Foreign');assert.equal(f.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(f.users.foreign.id).operator,0);
  assert.equal((await f.request('owner','workspace',f.a.scope)).result.clients.find(c=>c.id===f.users.foreign.id).name,'Salono kliento vardas');assert.equal(f.source.organizationRecords('clientLinks',f.a.org.id).length,0);
  const grant=await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'manager',version:0});assert.equal(grant.status,200,JSON.stringify(grant));assert.equal(grant.result.accountId,f.users.foreign.id);assert.equal(grant.result.version,1);
  const session=await f.request('foreign',null,{}, {verb:'GET',url:'/api/madbeauty/session'});assert.equal(session.organizations.find(o=>o.id===f.a.org.id).membershipRole,'manager');
  assert.equal((await f.request('foreign','workspace',f.a.scope)).result.capabilities.includes('access'),false);
  assert.equal((await f.request('foreign','grantMembership',{organizationId:f.a.org.id,email:f.users.client.email,role:'reception',version:0})).status,403);
  assert.equal((await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'reception',version:0})).error.code,'VERSION_CONFLICT');
  const revoke=await f.request('owner','revokeMembership',{id:grant.result.id,version:1});assert.equal(revoke.status,200,JSON.stringify(revoke));assert.equal(revoke.result.version,2);
  assert.equal((await f.request('foreign',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await f.request('foreign','workspace',f.a.scope)).status,403);
  const restored=await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'reception',version:2});assert.equal(restored.status,200,JSON.stringify(restored));assert.equal(restored.result.id,grant.result.id);assert.equal(restored.result.version,3);
  assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.membershipId===grant.result.id).length,3);assert.equal(f.source.organizationRecords('memberships',f.a.org.id).some(m=>m.accountId===f.users.foreign.id),false);
  assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM email_challenges').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Current target capability precedes central email lookup, and revocation between identity preflight and command prevents recipient admission',async()=>{
 const f=fixture();try{
  let lookups=0;const prepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{if(q==='SELECT id FROM accounts WHERE site_id=? AND email=?')lookups++;return prepare(q);};
  for(const email of [f.users.client.email,'unknown-scope@example.com'])assert.equal((await f.request('foreign','createClient',{organizationId:f.a.org.id,email,name:'Denied'})).status,403);
  assert.equal((await f.request('reception','grantMembership',{organizationId:f.a.org.id,email:f.users.client.email,role:'manager',version:0})).status,403);assert.equal(lookups,0);assert.equal(f.target.recordById('clients',f.users.foreign.id),null);
  assert.equal((await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:'unknown-scope@example.com',role:'manager',version:0})).error.code,'NOT_FOUND');assert.equal(lookups,1);assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE email=?').get('unknown-scope@example.com'),undefined);
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{
   const result=f.command.execute(packet);if(packet.method==='identityActionScope'&&!result.error)createPlatform(f.target).revokeMembership(f.users.owner,{id:f.membership.id,version:1});return result;
  }})});
  await assert.rejects(directory.dispatch('createClient',f.users.reception,{organizationId:f.a.org.id,email:f.users.foreign.email,name:'No recipient after revocation'}),e=>e.code==='FORBIDDEN');
  assert.equal(f.target.recordById('clients',f.users.foreign.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);
  assert.equal((await f.request('owner','identityActionScope',{organizationId:f.a.org.id,operation:'createClient'})).status,404);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Signed recipient cache binds the selected email and operation; target account, client link, access journal and nonce roll back together',()=>{
 const f=fixture();try{
  const issuer=createDirectoryCacheIssuer(f.source),actor={...f.users.owner,operator:true},packet=(method,extra={})=>{const body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'identity-'+method,expiresAt:now+20000,method,actor,input:{organizationId:f.a.org.id,email:f.users.foreign.email,name:'Private name',role:'manager',version:0},cache:issuer.issue(actor.id,f.users.foreign.id),...extra};return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};},resign=value=>{const {proof,...body}=value;return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};};
  const original=packet('createClient'),bad=structuredClone(original);bad.cache.recipientId=f.users.client.id;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.cache.accounts[1].operator=1;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.cache.clients[1].favorites=[f.b.org.id];assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.method='session';assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.method='grantMembership';bad.input.email=f.users.client.email;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');
  assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);
  const before=f.target.rowStats(),prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO organization_directory_commands')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated identity nonce post-write failure');}}:s;};
  assert.equal(f.command.execute(original).error.code,'SERVER_ERROR');assert.equal(f.target.recordById('clients',f.users.foreign.id),null);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);assert.deepEqual(f.target.rowStats(),before);
  const grant=packet('grantMembership');assert.equal(f.command.execute(grant).error.code,'SERVER_ERROR');assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.next.accountId===f.users.foreign.id).length,0);assert.equal(f.target.organizationRecords('memberships',f.a.org.id).some(m=>m.accountId===f.users.foreign.id),false);assert.equal(f.target.recordById('clients',f.users.foreign.id),null);
  f.target.db.prepare=prepare;const once=f.command.execute(grant),again=f.command.execute(grant);assert.ok(once.result,JSON.stringify(once));assert.deepEqual(again,once);assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.next.accountId===f.users.foreign.id).length,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});
