import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {createOrganizationHandoff,createOrganizationStaging} from './organization-handoff.mjs';
import {createOrganizationCommit,createOrganizationAuthority} from './organization-authority.mjs';
const now=Date.parse('2026-10-08T06:00:00Z'),secret='isolated-authority-test-secret-'.repeat(3);
function fixture(sourceFile=':memory:',targetFile=':memory:',{media=false,largeContext=false}={}){
 const source=openStore({filename:sourceFile,secret,clock:()=>now}),target=openStore({filename:targetFile,secret,clock:()=>now}),auth=createAuth(source),api=createPlatform(source);
 const login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,source.capture(c.challengeId).code,'127.0.0.1').user;};
 const owner=login('authority-owner@example.com'),client=login('authority-client@example.com');source.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(owner.id);
 const make=name=>{const org=api.createOrganization(owner,{name,bio:'Isolated authority transfer.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),service=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Preserved authority service',durationMin:60,priceMinor:2500});api.moderate({...owner,operator:true},{id:api.submitRevision(owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,scope,service};};
 const a=make('Authority A'),b=make('Authority B'),candidate=(f,dayOffset=1)=>api.availability({providerServiceId:f.service.id,dayOffset,from:900,to:1200,addons:[]}).slots[0];
 const book=(f,key)=>api.confirm(client,{holdId:api.hold(client,candidate(f)).id,idempotencyKey:key,name:'Original client'}),first=book(a,'retained-authority'),other=book(b,'foreign-authority'),hold=api.hold(client,candidate(a));
 if(media){const d=source.read();d.media.push({id:'untransferred-media',organizationId:a.org.id,accountId:owner.id});source.write(d);}if(largeContext)source.mail({organizationId:a.org.id,recipient:client.email,type:'confirmation',payload:{fixture:'x'.repeat(1024*1024)}});
 const handoff=createOrganizationHandoff(source),frozen=handoff.freeze({operatorAccountId:owner.id,organizationId:a.org.id,epoch:0,requestKey:'authority-fixture'}),control={operatorAccountId:owner.id,organizationId:a.org.id,epoch:frozen.epoch,handoffId:frozen.handoffId},stage=createOrganizationStaging(target,{targetName:frozen.targetName});
 let offset=0;do{const p=handoff.page({...control,offset});stage.accept(p);offset=p.nextOffset;if(p.done)break;}while(true);
 return {source,target,owner,client,api,a,b,first,other,hold,handoff,frozen,control,commit:createOrganizationCommit(source),authority:createOrganizationAuthority(target,{targetName:frozen.targetName})};
}
function oldWriterErrors(store,booking){const errors=[];for(const fn of [()=>store.db.prepare('UPDATE platform_state SET version=version+1 WHERE site_id=?').run(store.siteId),()=>store.db.prepare('UPDATE state_rows SET data=? WHERE site_id=? AND collection=? AND record_key=?').run(JSON.stringify({...booking,status:'canceled'}),store.siteId,'bookings','id:'+booking.id),()=>store.db.prepare("UPDATE mail_outbox SET state='sending' WHERE booking_id=?").run(booking.id),()=>store.db.prepare('DELETE FROM notification_jobs WHERE booking_id=?').run(booking.id)]){try{fn();errors.push('Old writer escaped');}catch(e){errors.push(e.message);}}return errors;}

test('Prepared target is fenced until source seal; target confirms the retained hold, source never resumes, and cross-organization/global controls remain blocked',()=>{
 const f=fixture();try{
  const context=f.commit.context(f.control);assert.deepEqual(f.commit.context(f.control),context);assert.ok(context.accounts.every(a=>a.operator===0));assert.equal(context.clients.some(c=>c.favoriteIds),false);assert.equal(context.outbox.some(m=>m.organization_id===f.b.org.id||m.type==='login-code'),false);
  assert.throws(()=>f.authority.prepare({...context,sha256:'tampered'}),e=>e.code==='FORBIDDEN');const receipt=f.authority.prepare(context);assert.deepEqual(f.authority.prepare(context),receipt);assert.deepEqual(f.target.recordById('bookings',f.first.id),f.first);assert.equal(f.authority.status().writeAuthority,false);
  assert.throws(()=>createPlatform(f.target).confirm(f.client,{holdId:f.hold.id,idempotencyKey:'new-authority-booking',name:'Target client'}),e=>e.code==='ORGANIZATION_MIGRATING');assert.ok(oldWriterErrors(f.target,f.first).every(e=>/ORGANIZATION_TARGET_FENCED/.test(e)));
  assert.throws(()=>f.commit.seal({...f.control,operatorAccountId:f.client.id,targetReceipt:receipt}),e=>e.code==='FORBIDDEN');assert.throws(()=>f.commit.seal({...f.control,targetReceipt:{...receipt,epoch:99}}),e=>e.code==='FORBIDDEN');const token=f.commit.seal({...f.control,targetReceipt:receipt});assert.equal(f.handoff.status(f.control).state,'sealed');assert.deepEqual(f.commit.seal({...f.control,targetReceipt:receipt}),token);assert.throws(()=>f.handoff.abort(f.control),e=>e.code==='INVALID_STATE');
  assert.throws(()=>f.authority.activate({...token,targetName:'other'}),e=>e.code==='FORBIDDEN');assert.equal(f.authority.activate(token).writeAuthority,true);assert.equal(f.authority.status().mailAuthority,false);assert.deepEqual(f.authority.activate(token),f.authority.status());
  const targetApi=createPlatform(f.target),next=targetApi.confirm(f.client,{holdId:f.hold.id,idempotencyKey:'new-authority-booking',name:'Target client'});assert.notEqual(next.id,f.first.id);assert.equal(next.priceMinor,2500);assert.equal(targetApi.confirm(f.client,{holdId:f.hold.id,idempotencyKey:'new-authority-booking',name:'Target client'}).id,next.id);assert.deepEqual(f.target.recordById('bookings',f.first.id),f.first);assert.equal(f.source.recordById('bookings',next.id),null);
  assert.throws(()=>f.api.cancelBooking(f.client,{id:f.first.id,version:1,reason:'Old coordinator must not resume'}),e=>e.code==='ORGANIZATION_MIGRATING');assert.ok(oldWriterErrors(f.source,f.first).every(e=>/ORGANIZATION_MIGRATING/.test(e)));assert.throws(()=>targetApi.cancelBooking({...f.client,id:'unrelated-client'},{id:next.id,version:1,reason:'Denied foreign client'}),e=>['FORBIDDEN','NOT_FOUND'].includes(e.code));
  assert.throws(()=>targetApi.createResource(f.owner,{organizationId:f.b.org.id,label:'Foreign target resource'}));assert.throws(()=>targetApi.preferences(f.client,{service:false,marketing:false,reminderLeadMin:0}));assert.equal(f.target.clientRecords('preferences',f.client.id)[0]?.service,f.source.clientRecords('preferences',f.client.id)[0]?.service);
  assert.throws(()=>targetApi.createClient(f.owner,{organizationId:f.a.org.id,email:'new-directory-identity@example.com',name:'Needs global identity'}),/GLOBAL_IDENTITY_REQUIRED/);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE email=?').get('new-directory-identity@example.com'),undefined);assert.throws(()=>f.target.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(f.owner.id),/GLOBAL_IDENTITY_REQUIRED/);
  const mailed=f.target.db.prepare('SELECT id FROM mail_outbox WHERE booking_id=?').all(next.id);assert.equal(mailed.length,1);assert.equal(f.source.db.prepare('SELECT id FROM mail_outbox WHERE booking_id=?').all(next.id).length,0);f.api.cancelBooking(f.client,{id:f.other.id,version:1,reason:'Other source remains operational'});assert.equal(f.source.recordById('bookings',f.other.id).status,'canceled');
 }finally{f.source.close();f.target.close();}
});

test('Context capacity, untransferred media, corrupt staged rows and nonempty target are rejected without overwriting calendars or partial private imports',()=>{
 for(const options of [{largeContext:true},{media:true},{corruptStage:true},{}]){const f=fixture(':memory:',':memory:',options);try{
  if(options.largeContext){assert.throws(()=>f.commit.context(f.control),e=>e.code==='CAPACITY');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM organization_handoff_context').get().n,0);}
  else if(options.media){assert.throws(()=>f.authority.prepare(f.commit.context(f.control)),e=>e.code==='HANDOFF_DEPENDENCY');assert.equal(f.target.recordById('bookings',f.first.id),null);}
  else if(options.corruptStage){const r=f.target.db.prepare('SELECT ordinal,data FROM organization_stage_rows LIMIT 1').get(),v=JSON.parse(r.data);v.raw='{}';f.target.db.prepare('UPDATE organization_stage_rows SET data=? WHERE ordinal=?').run(JSON.stringify(v),r.ordinal);assert.throws(()=>f.authority.prepare(f.commit.context(f.control)),e=>e.code==='HANDOFF_INTEGRITY');assert.equal(f.target.recordById('bookings',f.first.id),null);}
  else{const d=f.target.read();d.clients.push({id:'unrelated-existing-client',email:'unrelated-existing@example.com',name:'Must remain'});f.target.write(d);assert.throws(()=>f.authority.prepare(f.commit.context(f.control)),e=>e.code==='INVALID_STATE');assert.equal(f.target.recordById('clients','unrelated-existing-client').name,'Must remain');}
  assert.equal(f.authority.status().state,'empty');assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);f.handoff.abort(f.control);assert.equal(f.source.organizationWritable(f.a.org.id),true);
 }finally{f.source.close();f.target.close();}}
});

test('Target import and source seal roll back after SQL writes; changed context cannot be committed',()=>{
 const f=fixture();try{
  const context=f.commit.context(f.control),version=f.target.rowStats().version,prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO notification_jobs'))return s;return {...s,run:(...a)=>{s.run(...a);throw Error('Isolated target import failure');}};};assert.throws(()=>f.authority.prepare(context),/Isolated target import failure/);f.target.db.prepare=prepare;
  assert.equal(f.authority.status().state,'empty');assert.equal(f.target.rowStats().version,version);assert.equal(f.target.recordById('bookings',f.first.id),null);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM accounts').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n,0);const receipt=f.authority.prepare(context);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=sourcePrepare(q);if(!q.startsWith("UPDATE organization_handoffs SET state='sealed'"))return s;return {...s,run:(...a)=>{s.run(...a);throw Error('Isolated source commit failure');}};};assert.throws(()=>f.commit.seal({...f.control,targetReceipt:receipt}),/Isolated source commit failure/);f.source.db.prepare=sourcePrepare;assert.equal(f.handoff.status(f.control).state,'frozen');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM organization_handoff_commits').get().n,0);assert.equal(f.authority.status().state,'prepared');
  f.source.db.prepare('UPDATE accounts SET name=? WHERE id=?').run('Changed central identity',f.client.id);assert.throws(()=>f.commit.seal({...f.control,targetReceipt:receipt}),e=>e.code==='HANDOFF_CONTEXT_CHANGED');assert.equal(f.handoff.status(f.control).state,'frozen');const abort=f.commit.abort(f.control);assert.equal(f.authority.discard(abort).state,'empty');assert.equal(f.authority.discard(abort).state,'empty');assert.equal(f.target.recordById('bookings',f.first.id),null);assert.equal(f.source.recordById('bookings',f.first.id).status,'confirmed');
  const next=f.handoff.freeze({...f.control,requestKey:'replacement-context'}),control={...f.control,epoch:next.epoch,handoffId:next.handoffId},stage=createOrganizationStaging(f.target,{targetName:next.targetName});let offset=0;do{const packet=f.handoff.page({...control,offset});stage.accept(packet);offset=packet.nextOffset;if(packet.done)break;}while(true);const nextReceipt=f.authority.prepare(f.commit.context(control));assert.throws(()=>f.authority.discard(abort),e=>e.code==='INVALID_STATE');f.authority.activate(f.commit.seal({...control,targetReceipt:nextReceipt}));assert.throws(()=>f.authority.discard(abort),e=>e.code==='INVALID_STATE');
 }finally{f.source.close();f.target.close();}
});

test('Restart between prepare, seal and activation preserves one writer and never restores an old calendar over a new booking',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-authority-node-')),sourceFile=path.join(dir,'source.sqlite'),targetFile=path.join(dir,'target.sqlite'),f=fixture(sourceFile,targetFile);let source=f.source,target=f.target;try{
  const receipt=f.authority.prepare(f.commit.context(f.control));source.close();target.close();source=openStore({filename:sourceFile,secret,clock:()=>now});target=openStore({filename:targetFile,secret,clock:()=>now});let authority=createOrganizationAuthority(target,{targetName:f.frozen.targetName}),commit=createOrganizationCommit(source);assert.equal(authority.status().state,'prepared');const token=commit.seal({...f.control,targetReceipt:receipt});assert.throws(()=>createOrganizationHandoff(source).abort(f.control),e=>e.code==='INVALID_STATE');
  source.close();target.close();source=openStore({filename:sourceFile,secret,clock:()=>now});target=openStore({filename:targetFile,secret,clock:()=>now});authority=createOrganizationAuthority(target,{targetName:f.frozen.targetName});assert.equal(authority.status().writeAuthority,false);authority.activate(token);const next=createPlatform(target).confirm(f.client,{holdId:f.hold.id,idempotencyKey:'restart-target-confirm',name:'Retained client'});
  target.close();target=openStore({filename:targetFile,secret,clock:()=>now});authority=createOrganizationAuthority(target,{targetName:f.frozen.targetName});assert.equal(authority.status().state,'active');assert.equal(target.recordById('bookings',next.id).priceMinor,2500);assert.equal(source.recordById('bookings',next.id),null);assert.throws(()=>createOrganizationHandoff(source).abort(f.control),e=>e.code==='INVALID_STATE');assert.deepEqual(target.recordById('bookings',f.first.id),f.first);
 }finally{source.close();target.close();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-authority-node-'))await rm(absolute,{recursive:true,force:true});}
});
