import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {createOrganizationHandoff,createOrganizationStaging} from './organization-handoff.mjs';
const now=Date.parse('2026-10-08T06:00:00Z'),secret='isolated-handoff-test-secret-'.repeat(3);
function fixture(filename=':memory:'){
 const store=openStore({filename,secret,clock:()=>now}),auth=createAuth(store),api=createPlatform(store),login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user;},owner=login('handoff-owner@example.com'),client=login('handoff-client@example.com');store.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(owner.id);
 const make=name=>{const org=api.createOrganization(owner,{name,bio:'Isolated calendar handoff fixture.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),service=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Fixture manicure',durationMin:60,priceMinor:2500});api.moderate({...owner,operator:true},{id:api.submitRevision(owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,scope,service};};
 const a=make('Handoff A'),b=make('Handoff B'),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0],book=(f,key)=>{const hold=api.hold(client,candidate(f));return api.confirm(client,{holdId:hold.id,idempotencyKey:key,name:'Fixture client'});};
 const first=book(a,'first-calendar'),other=book(b,'other-calendar');for(const f of [a,b])api.selectProcedures(owner,{organizationId:f.org.id,procedureIds:['kirpimai-vyru-kirpimas'],version:0,idempotencyKey:'selection-'+f.org.id});
 return {store,api,owner,client,a,b,candidate,first,other,handoff:createOrganizationHandoff(store),control:{operatorAccountId:owner.id,organizationId:a.org.id,epoch:0,requestKey:'isolated-transfer'}};
}
const packets=(handoff,control,frozen)=>{const result=[];let offset=0;do{const packet=handoff.page({...control,epoch:frozen.epoch,handoffId:frozen.handoffId,offset});result.push(packet);offset=packet.nextOffset;if(packet.done)break;}while(true);return result;};

test('Calendar fence rejects full/scoped/source mail writes, rolls back global preference and manual identity changes, and leaves another organization operational',()=>{
 const f=fixture(),{store,api,handoff,control,client,owner}=f;try{
  assert.throws(()=>handoff.freeze({...control,operatorAccountId:client.id}),e=>e.code==='FORBIDDEN');
  const snapshot=store.organizationRecords('bookings',f.a.org.id),version=store.rowStats().version,outbox=store.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n,preferences=store.clientRecords('preferences',client.id),job=store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(f.first.id),frozen=handoff.freeze(control);
  assert.equal(frozen.state,'frozen');assert.equal(frozen.epoch,1);assert.deepEqual(handoff.freeze(control),frozen);assert.throws(()=>handoff.freeze({...control,requestKey:'different'}),e=>e.code==='VERSION_CONFLICT');
  for(const change of [()=>api.cancelBooking(client,{id:f.first.id,version:1,reason:'Should remain confirmed'}),()=>api.createResource(owner,{organizationId:f.a.org.id,label:'Frozen chair'}),()=>api.createClient(owner,{organizationId:f.a.org.id,email:'frozen-manual@example.com',name:'Blocked new identity'}),()=>api.preferences(client,{service:false,marketing:true,reminderLeadMin:0}),()=>store.transaction(()=>{store.mail({organizationId:f.a.org.id,recipient:client.email,type:'confirmation',payload:{}});}),()=>api.retryOutbox(owner,{id:store.db.prepare('SELECT id FROM mail_outbox WHERE booking_id=?').get(f.first.id).id,scope:f.a.scope})])assert.throws(change,e=>e.code==='ORGANIZATION_MIGRATING');
  for(const change of [d=>{d.bookings.find(b=>b.id===f.first.id).status='canceled';},d=>{d.organizations=d.organizations.filter(o=>o.id!==f.a.org.id);},d=>{delete d.idempotency[client.id+':first-calendar'];}]){const d=store.read();change(d);assert.throws(()=>store.write(d),e=>e.code==='ORGANIZATION_MIGRATING');}
  const oldRuntime=store.read();oldRuntime.bookings.find(b=>b.id===f.first.id).status='canceled';assert.throws(()=>store.db.prepare('UPDATE platform_state SET data=?,version=version+1 WHERE site_id=?').run(JSON.stringify(oldRuntime),store.siteId),/ORGANIZATION_MIGRATING/);assert.throws(()=>store.db.prepare('UPDATE state_rows SET data=? WHERE site_id=? AND collection=? AND record_key=?').run(JSON.stringify({...f.first,status:'canceled'}),store.siteId,'bookings','id:'+f.first.id),/ORGANIZATION_MIGRATING/);assert.throws(()=>store.db.prepare('DELETE FROM state_rows WHERE site_id=? AND collection=? AND record_key=?').run(store.siteId,'bookings','id:'+f.first.id),/ORGANIZATION_MIGRATING/);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM state_writer_permits').get().n,0);
  assert.equal(store.rowStats().version,version);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n,outbox);assert.equal(store.db.prepare('SELECT id FROM accounts WHERE email=?').get('frozen-manual@example.com'),undefined);assert.deepEqual(store.clientRecords('preferences',client.id),preferences);assert.deepEqual(store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(f.first.id),job);assert.deepEqual(store.organizationRecords('bookings',f.a.org.id),snapshot);
  api.cancelBooking(client,{id:f.other.id,version:1,reason:'Other calendar remains writable'});api.runAutomation();assert.equal(store.recordById('bookings',f.other.id).status,'canceled');assert.deepEqual(store.organizationRecords('bookings',f.a.org.id),snapshot);assert.equal(api.profile(f.a.org.id).services[0].priceMinor,2500);
  const input={...control,epoch:frozen.epoch,handoffId:frozen.handoffId};assert.throws(()=>handoff.abort({...input,epoch:0}),e=>e.code==='VERSION_CONFLICT');assert.equal(handoff.abort(input).state,'aborted');assert.equal(handoff.abort(input).state,'aborted');assert.throws(()=>handoff.page({...input,offset:0}),e=>e.code==='INVALID_STATE');api.cancelBooking(client,{id:f.first.id,version:1,reason:'Resumed original source'});assert.equal(store.recordById('bookings',f.first.id).status,'canceled');
 }finally{store.close();}
});

test('Bounded authenticated staging preserves exact IDs, old cross-salon replay ownership and snapshots, rejects forged packets, and grants no write authority',()=>{
 const f=fixture(),target=openStore({filename:':memory:',secret,clock:()=>now});try{
  const d=f.store.read();for(let n=0;n<350;n++)d.bookings.push({id:'own-snapshot-'+n,organizationId:f.a.org.id,clientId:f.client.id,status:'completed',serviceSnapshot:{label:'Retained exact snapshot',privateNote:'x'.repeat(2000)}});for(let n=0;n<5000;n++)d.bookings.push({id:'foreign-snapshot-'+n,organizationId:f.b.org.id,clientId:'foreign-client-'+n,status:'completed',serviceSnapshot:{privateNote:'y'.repeat(500)}});f.store.write(d);
  const prepare=f.store.db.prepare.bind(f.store.db);f.store.db.prepare=q=>{if(/FROM state_rows\b/i.test(q)&&!/\bcollection\s*=/i.test(q))throw Error('Global migration history scan forbidden');return prepare(q);};const frozen=f.handoff.freeze(f.control),parts=packets(f.handoff,f.control,frozen);f.store.db.prepare=prepare;assert.ok(parts.length>2);assert.ok(parts.every(p=>Buffer.byteLength(JSON.stringify(p.rows))<=512*1024+256*1024));
  const all=parts.flatMap(p=>p.rows),ids=all.filter(r=>r.collection==='idempotency').map(r=>r.key);assert.ok(ids.includes(f.client.id+':first-calendar'));assert.ok(ids.includes(f.owner.id+':procedures:selection-'+f.a.org.id));assert.ok(!ids.includes(f.client.id+':other-calendar'));assert.ok(!ids.includes(f.owner.id+':procedures:selection-'+f.b.org.id));assert.ok(!JSON.stringify(all).includes('foreign-snapshot-'));assert.ok(!all.some(r=>['clients','preferences','sessions','accounts'].includes(r.collection)));
  const stage=createOrganizationStaging(target,{targetName:frozen.targetName});assert.throws(()=>stage.accept({...parts[0],nextOffset:999}),e=>e.code==='FORBIDDEN');assert.deepEqual(stage.summary(),{state:'empty',writeAuthority:false,rows:0});assert.throws(()=>createOrganizationStaging(target,{targetName:'wrong-object'}).accept(parts[0]),e=>e.code==='HANDOFF_SCOPE');
  for(const packet of [...parts].reverse()){stage.accept(packet);stage.accept(packet);}const summary=stage.summary();assert.equal(summary.state,'ready-read-only');assert.equal(summary.writeAuthority,false);assert.equal(summary.rows,frozen.manifest.rows);assert.equal(summary.sha256,frozen.manifest.sha256);
  const saved=target.db.prepare('SELECT data FROM organization_stage_rows WHERE site_id=? ORDER BY ordinal').all(target.siteId).map(r=>JSON.parse(r.data));assert.deepEqual(saved,all);assert.deepEqual(JSON.parse(saved.find(r=>r.collection==='bookings'&&r.key==='id:'+f.first.id).raw),f.first);assert.equal(target.organizationRecords('bookings',f.a.org.id).length,0);assert.throws(()=>createPlatform(target).confirm(f.client,{holdId:JSON.parse(saved.find(r=>r.collection==='holds').raw).id,idempotencyKey:'no-authority',name:'Fixture'}),e=>e.code==='NOT_FOUND');
  f.handoff.abort({...f.control,epoch:1,handoffId:frozen.handoffId});const next=f.handoff.freeze({...f.control,epoch:1,requestKey:'next-transfer'}),newParts=packets(f.handoff,f.control,next);stage.accept(newParts[0]);assert.equal(stage.summary().epoch,2);assert.throws(()=>stage.accept(parts[0]),e=>e.code==='VERSION_CONFLICT');
 }finally{f.store.close();target.close();}
});

test('Failed snapshot freeze leaves neither fence nor partial export, and an in-flight mail lease prevents starting a handoff',()=>{
 const f=fixture(),{store,handoff,control}=f;try{
  const version=store.rowStats().version,prepare=store.db.prepare.bind(store.db);let n=0;store.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO organization_handoff_rows'))return s;return {run:(...a)=>{s.run(...a);if(++n===3)throw Error('Isolated transfer disk failure');}};};assert.throws(()=>handoff.freeze(control),/Isolated transfer disk failure/);store.db.prepare=prepare;assert.equal(handoff.status(control).state,'source');assert.equal(store.rowStats().version,version);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM organization_handoff_rows').get().n,0);f.api.createResource(f.owner,{organizationId:f.a.org.id,label:'Writable after rollback'});
  const mail=store.db.prepare('SELECT id FROM mail_outbox WHERE booking_id=?').get(f.first.id);store.db.prepare("UPDATE mail_outbox SET state='sending' WHERE id=?").run(mail.id);assert.throws(()=>handoff.freeze(control),e=>e.code==='HANDOFF_BUSY');assert.equal(handoff.status(control).state,'source');store.db.prepare("UPDATE mail_outbox SET state='captured' WHERE id=?").run(mail.id);assert.equal(handoff.freeze(control).state,'frozen');
 }finally{store.close();}
});

test('Incomplete target import rolls back a failed page and resumes source fence/target packets after separate SQLite restarts',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-handoff-node-')),sourceFile=path.join(dir,'source.sqlite'),targetFile=path.join(dir,'target.sqlite'),f=fixture(sourceFile);let source=f.store,target=openStore({filename:targetFile,secret,clock:()=>now});try{
  const d=source.read();for(let n=0;n<160;n++)d.bookings.push({id:'restart-snapshot-'+n,organizationId:f.a.org.id,clientId:f.client.id,status:'completed',serviceSnapshot:{priceMinor:2300}});source.write(d);const frozen=f.handoff.freeze(f.control),parts=packets(f.handoff,f.control,frozen),stage=createOrganizationStaging(target,{targetName:frozen.targetName});assert.ok(parts.length>1);stage.accept(parts[0]);const firstSummary=stage.summary(),prepare=target.db.prepare.bind(target.db);let n=0;target.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO organization_stage_rows'))return s;return {run:(...a)=>{s.run(...a);if(++n===2)throw Error('Isolated target page failure');}};};assert.throws(()=>stage.accept(parts[1]),/Isolated target page failure/);target.db.prepare=prepare;assert.deepEqual(stage.summary(),firstSummary);
  source.close();target.close();source=openStore({filename:sourceFile,secret,clock:()=>now});target=openStore({filename:targetFile,secret,clock:()=>now});const restored=createOrganizationHandoff(source),restoredStage=createOrganizationStaging(target,{targetName:frozen.targetName});assert.deepEqual(restored.status(f.control),frozen);assert.deepEqual(restoredStage.summary(),firstSummary);assert.throws(()=>createPlatform(source).cancelBooking(f.client,{id:f.first.id,version:1,reason:'Still fenced after restart'}),e=>e.code==='ORGANIZATION_MIGRATING');for(const p of parts)restoredStage.accept(p);assert.equal(restoredStage.summary().state,'ready-read-only');assert.equal(restoredStage.summary().writeAuthority,false);restored.abort({...f.control,epoch:1,handoffId:frozen.handoffId});createPlatform(source).cancelBooking(f.client,{id:f.first.id,version:1,reason:'Resumed after partial import'});assert.equal(source.recordById('bookings',f.first.id).status,'canceled');assert.equal(target.organizationRecords('bookings',f.a.org.id).length,0);
 }finally{source.close();target.close();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-handoff-node-'))await rm(absolute,{recursive:true,force:true});}
});
