import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {createApiHandler} from './http-core.mjs';
import {createOrganizationHandoff,createOrganizationStaging,organizationTransferProof} from './organization-handoff.mjs';
import {createOrganizationCommit,createOrganizationAuthority} from './organization-authority.mjs';
import {createOrganizationDirectory,createOrganizationCommand} from './organization-directory.mjs';
import {ApiError} from './primitives.mjs';
import {createDirectoryCacheIssuer} from './organization-directory-cache.mjs';
const now=Date.parse('2026-10-08T06:00:00Z'),secret='isolated-directory-acceptance-'.repeat(3),origin='https://directory-fixture.test';
function fixture({activate=true,large=false}={}){
 const source=openStore({filename:':memory:',secret,clock:()=>now}),target=openStore({filename:':memory:',secret,clock:()=>now}),auth=createAuth(source),api=createPlatform(source),sessions={};
 const users={owner:{id:'directory-owner',email:'directory-owner@example.com',name:'Owner'},client:{id:'directory-client',email:'directory-client@example.com',name:'Client'},foreign:{id:'directory-foreign',email:'directory-foreign@example.com',name:'Foreign'},reception:{id:'directory-reception',email:'directory-reception@example.com',name:'Reception'}};
 for(const [role,u]of Object.entries(users)){source.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(u.id,source.siteId,u.email,u.name,role==='owner'?1:0,now);source.ensureClient(u.id);const s=auth.session(null);source.db.prepare('UPDATE sessions SET account_id=? WHERE token_hash=?').run(u.id,s.token_hash);sessions[role]=s;}
 const make=name=>{const org=api.createOrganization(users.owner,{name,bio:'Isolated directory test.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(users.owner,scope),service=api.createService(users.owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Original directory service',durationMin:60,priceMinor:2500});api.moderate({...users.owner,operator:true},{id:api.submitRevision(users.owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,scope,service};};
 const a=make('Directory A'),b=make('Directory B'),membership=api.grantMembership(users.owner,{organizationId:a.org.id,email:users.reception.email,role:'reception',version:0}),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0];
 const first=api.confirm(users.client,{holdId:api.hold(users.client,candidate(a)).id,idempotencyKey:'retained-directory',name:'Original client'}),other=api.confirm(users.client,{holdId:api.hold(users.client,candidate(b)).id,idempotencyKey:'other-directory',name:'Original client'}),hold=api.hold(users.client,candidate(a));
 if(large){const data=source.read();for(let n=0;n<14;n++)data.messages.push({id:'large-directory-message-'+n,organizationId:a.org.id,bookingId:first.id,clientId:users.client.id,text:'x'.repeat(90000),createdAt:new Date(now).toISOString()});source.write(data);}
 const handoff=createOrganizationHandoff(source),frozen=handoff.freeze({operatorAccountId:users.owner.id,organizationId:a.org.id,epoch:0,requestKey:'directory-fixture'}),control={operatorAccountId:users.owner.id,organizationId:a.org.id,epoch:frozen.epoch,handoffId:frozen.handoffId},stage=createOrganizationStaging(target,{targetName:frozen.targetName});
 let offset=0;do{const page=handoff.page({...control,offset});stage.accept(page);offset=page.nextOffset;if(page.done)break;}while(true);
 const commit=createOrganizationCommit(source),authority=createOrganizationAuthority(target,{targetName:frozen.targetName}),receipt=authority.prepare(commit.context(control));commit.seal({...control,targetReceipt:receipt});if(activate)authority.activate(commit.seal({...control,targetReceipt:receipt}));
 const command=createOrganizationCommand(target,{targetName:frozen.targetName}),directory=createOrganizationDirectory(source,{getTarget:name=>{assert.equal(name,frozen.targetName);return {executeDirectoryCommand:packet=>command.execute(packet)};}}),handler=createApiHandler(source,{origin,secure:true,media:{},dispatch:directory.dispatch});
 async function request(role,method,input={},options={}){const s=sessions[role],body=JSON.stringify({method,input,siteId:options.siteId||source.siteId}),req={url:options.url||'/api/madbeauty/rpc',method:options.verb||'POST',headers:{host:new URL(origin).host,origin,'content-type':'application/json',cookie:'__Host-madbeauty_sid='+s.token,'x-csrf-token':s.csrf,...options.headers},socket:{remoteAddress:'127.0.0.1'},async *[Symbol.asyncIterator](){yield Buffer.from(body);}},res={writeHead(status,headers){this.status=status;this.headers=headers;},end(body){this.data=JSON.parse(body);}};await handler.handle(req,res);return {status:res.status,...res.data};}
 return {source,target,users,sessions,auth,api,a,b,first,other,hold,membership,frozen,control,command,directory,request,close:()=>{source.close();target.close();}};
}
test('Ordinary authenticated HTTP routes old and new IDs to one active calendar; current search, customer and professional workspaces and revoked session roles agree',async()=>{
 const f=fixture();try{
  const next=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-new-confirm',name:'Original client'});assert.equal(next.status,200,JSON.stringify(next));const booking=next.result;assert.notEqual(booking.id,f.first.id);assert.equal(booking.priceMinor,2500);
  assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-new-confirm',name:'Original client'})).result.id,booking.id);
  const customer=await f.request('client','workspace',{role:'customer'}),professional=await f.request('owner','workspace',f.a.scope),unmigrated=await f.request('owner','workspace',f.b.scope);assert.equal(unmigrated.status,200,JSON.stringify(unmigrated));assert.equal(unmigrated.result.bookings[0].id,f.other.id);assert.equal(unmigrated.result.bookings.some(b=>b.id===booking.id),false);assert.equal(customer.result.bookings.filter(b=>b.id===booking.id).length,1);assert.equal(customer.result.bookings.find(b=>b.id===f.other.id).organizationId,f.b.org.id);assert.equal(professional.result.bookings.find(b=>b.id===booking.id).id,booking.id);
  const changed=await f.request('owner','edit',{scope:f.a.scope,table:'services',id:f.a.service.id,version:1,values:{label:'Current target service',priceMinor:3200}});assert.equal(changed.status,200,JSON.stringify(changed));
  const search=await f.request('client','searchResults',{anyTime:true,sort:'price'});assert.equal(search.result.treatments.filter(s=>s.id===f.a.service.id).length,1);assert.equal(search.result.treatments.find(s=>s.id===f.a.service.id).priceMinor,3200);assert.equal((await f.request('client','profile',{id:f.a.org.id})).result.services[0].label,'Current target service');assert.equal((await f.directory.dispatch('catalog',null,{})).find(s=>s.id===f.a.service.id).priceMinor,3200);
  f.source.db.prepare('DELETE FROM organization_directory_refs').run();const message=await f.request('client','message',{bookingId:booking.id,text:'Recover missing new ID index'});assert.equal(message.status,200,JSON.stringify(message));assert.equal(message.result.bookingId,booking.id);
  const foreign=await f.request('foreign','workspace',{role:'customer',clientId:f.users.client.id,operator:true});assert.equal(foreign.result.bookings.length,0);assert.equal((await f.request('foreign','cancelBooking',{id:booking.id,version:1,reason:'Spoofed user',user:f.users.client,operator:true})).status,403);
  assert.equal((await f.request('reception',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),true);assert.equal((await f.request('owner','revokeMembership',{id:f.membership.id,version:1})).status,200);assert.equal((await f.request('reception',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await f.request('reception','workspace',f.a.scope)).status,403);
  assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);assert.equal(f.source.recordById('bookings',booking.id),null);assert.equal(f.source.recordById('services',f.a.service.id).priceMinor,2500);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,1);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,0);
 }finally{f.close();}
});
test('HTTP security checks precede routing; prepared/unreachable targets never fall back, and admitted identities cannot create a new global account on a target',async()=>{
 const f=fixture({activate:false});try{
  const before=f.target.readCollections(['bookings','holds']);assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'prepared-denied',name:'Client'})).status,503);assert.deepEqual(f.target.readCollections(['bookings','holds']),before);
  assert.equal((await f.request('client','confirm',{}, {headers:{origin:'https://foreign.test'}})).status,403);assert.equal((await f.request('client','confirm',{}, {headers:{'x-csrf-token':'bad'}})).error.code,'CSRF');assert.equal((await f.request('client','confirm',{}, {siteId:'foreign-site'})).error.code,'SITE_SCOPE');
  const unreachable=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:()=>{throw Error('Isolated namespace outage');}})});await assert.rejects(unreachable.dispatch('cancelBooking',f.users.client,{id:f.first.id,version:1,reason:'No fallback'}),e=>e.code==='ORGANIZATION_UNAVAILABLE');assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);
 }finally{f.close();}
 const active=fixture();try{assert.equal(active.target.recordById('clients',active.users.foreign.id),null);const slot=(await active.request('foreign','availability',{providerServiceId:active.a.service.id,dayOffset:1,from:900,to:1200,addons:[]})).result.slots[0],before=active.target.readCollections(['holds']).holds.length;const admitted=await active.request('foreign','hold',slot);assert.equal(admitted.status,200,JSON.stringify(admitted));assert.equal(active.target.readCollections(['holds']).holds.length,before+1);assert.equal(active.target.recordById('clients',active.users.foreign.id).id,active.users.foreign.id);assert.equal(active.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(active.users.foreign.id).operator,0);assert.equal(active.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal((await active.request('owner','createClient',{organizationId:active.a.org.id,email:'unadmitted@example.com',name:'Denied'})).error.code,'GLOBAL_IDENTITY_REQUIRED');assert.equal(active.source.db.prepare('SELECT id FROM accounts WHERE email=?').get('unadmitted@example.com'),undefined);}finally{active.close();}
});
test('Committed OTP rotation survives a temporary organization-session lookup failure and recovers with its new secure cookie',async()=>{
 const store=openStore({filename:':memory:',secret,clock:()=>now}),auth=createAuth(store),api=createPlatform(store);let unavailable=true;
 const handler=createApiHandler(store,{origin,secure:true,media:{},dispatch:(method,user,input)=>{if(method==='session'&&unavailable)throw new ApiError('ORGANIZATION_UNAVAILABLE','Isolated lookup failure',503);return api.session(user);}});
 async function request(session,url,input={},verb='POST'){const req={url,method:verb,headers:{host:new URL(origin).host,origin,'content-type':'application/json',cookie:'__Host-madbeauty_sid='+session.token,'x-csrf-token':session.csrf},socket:{remoteAddress:'127.0.0.1'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(input));}},res={writeHead(status,headers){this.status=status;this.headers=headers;},end(body){this.data=JSON.parse(body);}};await handler.handle(req,res);return res;}
 try{
  const session=auth.session(null),challenge=auth.start(session,'rotation-directory@example.com','127.0.0.1'),verified=await request(session,'/api/madbeauty/auth/verify',{challengeId:challenge.challengeId,code:store.capture(challenge.challengeId).code});assert.equal(verified.status,503);const setCookie=verified.headers['Set-Cookie'];assert.ok(setCookie.startsWith('__Host-madbeauty_sid='));assert.ok(setCookie.includes('; Secure'));assert.ok(setCookie.includes('; HttpOnly'));const token=setCookie.split(';')[0].split('=')[1];assert.notEqual(token,session.token);assert.equal(auth.session(session.token,{create:false}),null);
  unavailable=false;const recovered=await request({token},'/api/madbeauty/session',{},'GET');assert.equal(recovered.status,200);assert.equal(recovered.data.user.email,'rotation-directory@example.com');assert.ok(recovered.data.csrf);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM accounts WHERE email=?').get('rotation-directory@example.com').n,1);
 }finally{store.close();}
});
test('Signed command scope, expiry and durable nonce replay protect post-write rollback; lost central registration recovers a confirmation without duplicate booking or mail',async()=>{
 const f=fixture();try{
  const cache=createDirectoryCacheIssuer(f.source),packet=body=>{const value={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'isolated-command-nonce',expiresAt:now+20000,method:'createResource',actor:{...f.users.owner,operator:true},input:{organizationId:f.a.org.id,label:'Nonce protected'},cache:cache.issue(f.users.owner.id),...body};return {...value,proof:organizationTransferProof(f.source,'directory-command',value)};};
  const value=packet();assert.equal(f.command.execute({...value,epoch:99}).error.code,'FORBIDDEN');assert.equal(f.command.execute(packet({expiresAt:now})).error.code,'INVALID_INPUT');assert.equal(f.command.execute(packet({organizationId:f.b.org.id})).error.code,'ORGANIZATION_UNAVAILABLE');const once=f.command.execute(value),twice=f.command.execute(value);assert.equal(once.result.id,twice.result.id);assert.equal(f.target.organizationRecords('resources',f.a.org.id).filter(r=>r.id===once.result.id).length,1);assert.equal(f.command.execute(packet({input:{organizationId:f.a.org.id,label:'Different command'}})).error.code,'IDEMPOTENCY_CONFLICT');
  const prepare=f.target.db.prepare.bind(f.target.db),before=f.target.readCollections(['bookings','holds']);f.target.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO mail_outbox')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated command post-mail failure');}}:s;};let result=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'});assert.equal(result.error.code,'SERVER_ERROR');f.target.db.prepare=prepare;assert.deepEqual(f.target.readCollections(['bookings','holds']),before);assert.equal(f.target.db.prepare("SELECT COUNT(*) AS n FROM organization_directory_commands WHERE response LIKE '%lost-directory-confirm%'").get().n,0);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=sourcePrepare(q);return q.startsWith('INSERT INTO organization_directory_refs')?{...s,run:()=>{throw Error('Isolated central registration failure');}}:s;};result=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'});assert.equal(result.status,500);f.source.db.prepare=sourcePrepare;const confirmed=f.target.clientRecords('bookings',f.users.client.id).find(b=>b.id!==f.first.id);assert.ok(confirmed);assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'lost-directory-confirm',name:'Original client'})).result.id,confirmed.id);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(confirmed.id).n,1);assert.equal((await f.request('client','workspace',{role:'customer'})).result.bookings.filter(b=>b.id===confirmed.id).length,1);
 }finally{f.close();}
});
test('Central operator, customer export and erasure review aggregate current owned target records without replacing global identity or bypassing recent OTP',async()=>{
 const f=fixture();try{
  const next=(await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'directory-export-confirm',name:'Original client'})).result;assert.ok(next.id);
  assert.equal((await f.request('owner','edit',{scope:f.a.scope,table:'services',id:f.a.service.id,version:1,values:{priceMinor:3400}})).status,200);
  const operator=await f.request('owner','workspace',{role:'operator'});assert.equal(operator.status,200,JSON.stringify(operator));assert.equal(operator.result.services.find(s=>s.id===f.a.service.id).priceMinor,3400);assert.equal(operator.result.organizations.filter(o=>o.id===f.a.org.id).length,1);assert.equal(operator.result.clients.length,0);assert.equal(operator.result.bookings.length,0);assert.equal(operator.result.outbox.filter(m=>m.bookingId===next.id).length,1);assert.equal((await f.request('client','workspace',{role:'operator',operator:true})).status,403);
  const exported=await f.request('client',null,{}, {verb:'GET',url:'/api/madbeauty/customer-data'});assert.equal(exported.status,200,JSON.stringify(exported));assert.equal(exported.bookings.filter(b=>b.id===next.id).length,1);assert.equal(exported.bookings.find(b=>b.id===f.other.id).organizationId,f.b.org.id);assert.equal(exported.client.id,f.users.client.id);assert.equal((await f.request('foreign','exportCustomer',{clientId:f.users.client.id})).result.bookings.length,0);
  const request=(await f.request('client','requestErasure',{confirmEmail:f.users.client.email})).result;assert.ok(request.id);const review=await f.request('owner','erasureCase',{id:request.id});assert.equal(review.status,200,JSON.stringify(review));assert.equal(review.result.futureBookings.filter(b=>b.id===next.id).length,1);assert.equal(review.result.executionEnabled,false);
  f.source.db.prepare('UPDATE sessions SET created_at=? WHERE account_id=?').run(now-600001,f.users.client.id);assert.equal((await f.request('client','exportCustomer',{verifiedAt:now})).error.code,'REAUTH_REQUIRED');assert.equal((await f.request('client',null,{}, {verb:'GET',url:'/api/madbeauty/customer-data'})).error.code,'REAUTH_REQUIRED');assert.deepEqual(f.source.recordById('bookings',f.first.id),f.first);
 }finally{f.close();}
});

test('A first OTP sign-in after handoff books with current central preferences and returns its confirmed name to the central account exactly once',async()=>{
 const f=fixture();try{
  const anonymous=f.auth.session(null),challenge=f.auth.start(anonymous,'new-after-handoff@example.com','127.0.0.1'),verified=f.auth.verify(anonymous,challenge.challengeId,f.source.capture(challenge.challengeId).code,'127.0.0.1');f.sessions.fresh=verified.session;f.users.fresh=verified.user;
  assert.equal(verified.user.name,'');assert.equal(f.target.recordById('clients',verified.user.id),null);
  f.api.preferences(verified.user,{service:false,marketing:false,reminderLeadMin:0});
  const availability=await f.request('fresh','availability',{providerServiceId:f.a.service.id,dayOffset:1,from:900,to:1200,addons:[]}),candidate=availability.result.slots[0],hold=await f.request('fresh','hold',candidate);assert.equal(hold.status,200,JSON.stringify(hold));
  assert.equal(f.target.clientRecords('preferences',verified.user.id)[0].service,false);assert.equal(f.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(verified.user.id).operator,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM email_challenges').get().n,0);
  const confirmed=await f.request('fresh','confirm',{holdId:hold.result.id,idempotencyKey:'fresh-after-handoff',name:'Naujas klientas'});assert.equal(confirmed.status,200,JSON.stringify(confirmed));const booking=confirmed.result;
  assert.equal(f.source.recordById('clients',verified.user.id).name,'Naujas klientas');assert.equal(f.source.recordById('clients',verified.user.id).version,2);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(verified.user.id).name,'Naujas klientas');assert.equal(f.source.recordById('bookings',booking.id),null);
  assert.equal((await f.request('fresh','confirm',{holdId:hold.result.id,idempotencyKey:'fresh-after-handoff',name:'Naujas klientas'})).result.id,booking.id);assert.equal(f.source.recordById('clients',verified.user.id).version,2);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM notification_jobs WHERE booking_id=?').get(booking.id).n,0);
  const customer=await f.request('fresh','workspace',{role:'customer'}),professional=await f.request('owner','workspace',f.a.scope);assert.equal(customer.result.client.name,'Naujas klientas');assert.equal(customer.result.bookings.filter(b=>b.id===booking.id).length,1);assert.equal(professional.result.clients.find(c=>c.id===verified.user.id).name,'Naujas klientas');
 }finally{f.close();}
});

test('Fresh signed cache rejects identity substitution, operator creation and reordering; denied capabilities and post-cache failures roll back admission',async()=>{
 const f=fixture();try{
  const issuer=createDirectoryCacheIssuer(f.source),actor={...f.users.foreign,operator:false},packet=(cache,input={})=>{const body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'cache-'+cache.sequence,expiresAt:now+20000,method:'session',actor,input,cache};return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};},resign=packet=>{const {proof,...body}=packet;return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};};
  const first=issuer.issue(actor.id),bad=structuredClone(first);bad.accounts[0].id=f.users.client.id;assert.equal(f.command.execute(packet(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.accounts[0].id=actor.id;bad.accounts[0].operator=1;assert.equal(f.command.execute(packet(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');assert.equal(f.target.recordById('clients',actor.id),null);
  const denied=packet(first);denied.method='createResource';denied.input={organizationId:f.a.org.id,label:'Forbidden admission'};assert.equal(f.command.execute(resign(denied)).error.code,'FORBIDDEN');assert.equal(f.target.recordById('clients',actor.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(actor.id),undefined);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
  const prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const statement=prepare(q);return q.startsWith('INSERT INTO organization_directory_cache')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated cache post-write failure');}}:statement;};assert.equal(f.command.execute(packet(first)).error.code,'SERVER_ERROR');f.target.db.prepare=prepare;assert.equal(f.target.recordById('clients',actor.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(actor.id),undefined);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_directory_cache').get().n,0);
  f.api.preferences(actor,{service:false,marketing:true,reminderLeadMin:0});const newer=issuer.issue(actor.id);assert.ok(f.command.execute(packet(newer)).result);assert.equal(f.target.clientRecords('preferences',actor.id)[0].service,false);assert.equal(f.command.execute(packet(first)).error.code,'STALE_DIRECTORY_CONTEXT');assert.equal(f.target.clientRecords('preferences',actor.id)[0].service,false);
  assert.throws(()=>f.target.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(actor.id),/GLOBAL_IDENTITY_REQUIRED/);assert.throws(()=>f.target.db.prepare("UPDATE state_rows SET data='{}' WHERE collection='preferences'").run(),/ORGANIZATION_TARGET_FENCED/);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Source taxonomy archival reaches target public eligibility, and a lost identity reply recovers without overwriting a newer central name',async()=>{
 const f=fixture();try{
  assert.equal((await f.directory.dispatch('catalog',null,{})).some(s=>s.id===f.a.service.id),true);
  const archived=[],archive=id=>{for(const n of f.api.taxonomy().nodes.filter(n=>n.parentId===id))archive(n.id);f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:id,operation:'archive',version:f.api.taxonomy().version});archived.push(id);};archive('manikiuras');assert.equal((await f.directory.dispatch('catalog',null,{})).some(s=>s.id===f.a.service.id),false);assert.equal(f.target.readCollections(['taxonomyVersion']).taxonomyVersion,f.source.readCollections(['taxonomyVersion']).taxonomyVersion);
  const privateView=await f.directory.dispatch('workspace',f.users.owner,f.a.scope),retained=privateView.catalogueNodes.find(n=>n.id==='manikiuras');assert.equal(retained.archived,true);assert.equal(retained.path.at(-1),'Manikiūras');assert.equal((await f.directory.dispatch('taxonomy',null,{})).nodes.some(n=>n.id==='manikiuras'),false);
  for(const id of archived.reverse())f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:id,operation:'restore',version:f.api.taxonomy().version});
  const prepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO directory_identity_receipts')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated receipt post-write failure');}}:s;};const before=f.source.recordById('clients',f.users.client.id),first=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'});assert.equal(first.status,500);f.source.db.prepare=prepare;assert.deepEqual(f.source.recordById('clients',f.users.client.id),before);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(f.users.client.id).name,before.name);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_identity_receipts').get().n,0);
  const retry=await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'});assert.equal(retry.status,200,JSON.stringify(retry));assert.equal(f.source.recordById('clients',f.users.client.id).name,'Perduotas vardas');assert.equal(f.source.recordById('clients',f.users.client.id).version,before.version+1);
  const view=f.source.readClient(f.users.client.id);view.clients[0].name='Vėliau pakeistas vardas';view.clients[0].version++;f.source.transaction(()=>{f.source.db.prepare('UPDATE accounts SET name=? WHERE id=?').run(view.clients[0].name,f.users.client.id);f.source.writeClient(view);});assert.equal((await f.request('client','confirm',{holdId:f.hold.id,idempotencyKey:'recover-identity-effect',name:'Perduotas vardas'})).result.id,retry.result.id);assert.equal(f.source.recordById('clients',f.users.client.id).name,'Vėliau pakeistas vardas');assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(retry.result.id).n,1);
 }finally{f.close();}
});

test('An overtaken cache is refreshed once before a business write; oversized context never advances its issue version and row metadata remains exact above the legacy envelope',async()=>{
 const f=fixture({large:true});try{
  const issuer=createDirectoryCacheIssuer(f.source),candidate=(await f.directory.dispatch('availability',null,{providerServiceId:f.a.service.id,dayOffset:1,from:900,to:1200,addons:[]})).slots[0],before=f.target.readCollections(['holds']).holds.length;let calls=0;
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{calls++;if(calls===1){const {proof,...body}=packet,newer={...body,nonce:'overtaking-cache',method:'session',input:{},cache:issuer.issue(body.actor.id)};assert.ok(f.command.execute({...newer,proof:organizationTransferProof(f.source,'directory-command',newer)}).result);}return f.command.execute(packet);}})});
  const held=await directory.dispatch('hold',f.users.foreign,candidate);assert.ok(held.id);assert.equal(calls,2);assert.equal(f.target.readCollections(['holds']).holds.length,before+1);assert.equal(f.target.rowStats().legacyMirrored,false);
  f.api.changeTaxonomy({...f.users.owner,operator:true},{nodeId:'manikiuras',operation:'aliases',aliases:['Manikiūro paslauga'],version:f.api.taxonomy().version});await f.directory.dispatch('catalog',null,{});assert.equal(f.target.rowStats().bytes,Buffer.byteLength(JSON.stringify(f.target.read())));assert.equal(f.target.rowStats().records,f.target.db.prepare('SELECT COUNT(*) AS n FROM state_rows').get().n);
  const version=f.source.db.prepare('SELECT sequence FROM directory_cache_issues').get().sequence,read=f.source.readCollections;f.source.readCollections=fields=>fields.includes('taxonomy')?{taxonomy:[{id:'oversized-context',label:'x'.repeat(1024*1024)}]}:read(fields);assert.throws(()=>issuer.issue(f.users.foreign.id),e=>e.code==='CAPACITY');f.source.readCollections=read;assert.equal(f.source.db.prepare('SELECT sequence FROM directory_cache_issues').get().sequence,version);
 }finally{f.close();}
});

test('Customer opt-out commits central intent and unmigrated reminders atomically, reconciles target jobs, and retains latest durable work through outage or post-target failure',async()=>{
 const f=fixture();try{
  const jobs=bookingId=>f.target.db.prepare('SELECT state,lead_min FROM notification_jobs WHERE booking_id=?').all(bookingId);assert.equal(jobs(f.first.id)[0].state,'planned');
  const off=await f.request('client','preferences',{service:false,marketing:true,reminderLeadMin:0});assert.equal(off.status,200,JSON.stringify(off));assert.equal(off.result.synchronization,'applied');assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');assert.equal(f.source.db.prepare('SELECT state FROM notification_jobs WHERE booking_id=?').get(f.other.id).state,'suppressed');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  let outage=true;const interrupted=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{if(outage)throw Error('Isolated control delivery outage');return f.command.execute(packet);}})});
  const pending=await interrupted.dispatch('preferences',f.users.client,{service:true,marketing:false,reminderLeadMin:120});assert.equal(pending.synchronization,'pending');assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.ok(interrupted.nextControlAt());assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,1);
  const latest=await interrupted.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0});assert.equal(latest.synchronization,'pending');const revision=f.source.db.prepare('SELECT revision FROM directory_customer_controls').get().revision;outage=false;assert.equal(await interrupted.flushCustomerControls(f.users.client.id),false);assert.equal(f.target.db.prepare('SELECT revision FROM organization_customer_controls WHERE client_id=?').get(f.users.client.id).revision,revision);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  const prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const statement=prepare(q);return q.startsWith('INSERT INTO organization_customer_controls')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated reconciliation post-write failure');}}:statement;};const retry=await f.request('client','preferences',{service:true,marketing:false,reminderLeadMin:1440});assert.equal(retry.status,200);assert.equal(retry.result.synchronization,'pending');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');f.target.db.prepare=prepare;await f.directory.flushCustomerControls(f.users.client.id);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(jobs(f.first.id)[0].state,'planned');
  let lostReply=true;const recovery=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{const result=f.command.execute(packet);if(lostReply){lostReply=false;throw Error('Isolated lost committed control response');}return result;}})}),mailBefore=f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n;assert.equal((await recovery.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0})).synchronization,'pending');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(jobs(f.first.id)[0].state,'suppressed');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,1);assert.equal(await recovery.flushCustomerControls(f.users.client.id),false);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox').get().n,mailBefore);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db),before=f.source.clientRecords('preferences',f.users.client.id)[0];f.source.db.prepare=q=>{const statement=sourcePrepare(q);return q.startsWith('INSERT INTO directory_customer_controls')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Isolated central intent post-write failure');}}:statement;};const rollback=await f.request('client','preferences',{service:true,marketing:true,reminderLeadMin:1440});assert.equal(rollback.status,500);f.source.db.prepare=sourcePrepare;assert.deepEqual(f.source.clientRecords('preferences',f.users.client.id)[0],before);assert.equal(f.source.db.prepare('SELECT state FROM notification_jobs WHERE booking_id=?').get(f.other.id).state,'suppressed');assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,false);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);
  assert.equal((await f.request('foreign','applyCustomerControls',{revision:999,clientId:f.users.client.id})).status,404);
 }finally{f.close();}
});

test('Overlapping preference deliveries cannot acknowledge a later intent or restore an older central value',async()=>{
 const f=fixture();try{
  let release,arrived;const signal=new Promise(r=>arrived=r),delay=new Promise(r=>release=r);let count=0;
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:async packet=>{if(++count===1){arrived();await delay;}return f.command.execute(packet);}})});
  const first=directory.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0});await signal;const second=await directory.dispatch('preferences',f.users.client,{service:true,marketing:true,reminderLeadMin:120});assert.equal(second.synchronization,'applied');release();const older=await first;assert.equal(older.synchronization,'superseded');assert.equal(older.service,true);assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.target.clientRecords('preferences',f.users.client.id)[0].service,true);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_customer_controls').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Existing central email identities become salon clients and versioned team members without replacing global names or creating target login authority',async()=>{
 const f=fixture();try{
  const globalBefore=f.source.recordById('clients',f.users.foreign.id);
  f.source.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(f.users.foreign.id);
  const added=await f.request('owner','createClient',{organizationId:f.a.org.id,email:' DIRECTORY-FOREIGN@EXAMPLE.COM ',name:'Salono kliento vardas',recipientId:f.users.client.id});
  assert.equal(added.status,200,JSON.stringify(added));assert.equal(added.result.id,f.users.foreign.id);
  assert.deepEqual(f.source.recordById('clients',f.users.foreign.id),globalBefore);assert.equal(f.source.db.prepare('SELECT name FROM accounts WHERE id=?').get(f.users.foreign.id).name,'Foreign');
  assert.equal(f.target.recordById('clients',f.users.foreign.id).name,'Foreign');assert.equal(f.target.db.prepare('SELECT operator FROM accounts WHERE id=?').get(f.users.foreign.id).operator,0);
  assert.equal((await f.request('owner','workspace',f.a.scope)).result.clients.find(c=>c.id===f.users.foreign.id).name,'Salono kliento vardas');assert.equal(f.source.organizationRecords('clientLinks',f.a.org.id).length,0);
  const grant=await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'manager',version:0});assert.equal(grant.status,200,JSON.stringify(grant));assert.equal(grant.result.accountId,f.users.foreign.id);assert.equal(grant.result.version,1);
  const session=await f.request('foreign',null,{}, {verb:'GET',url:'/api/madbeauty/session'});assert.equal(session.organizations.find(o=>o.id===f.a.org.id).membershipRole,'manager');
  assert.equal((await f.request('foreign','workspace',f.a.scope)).result.capabilities.includes('access'),false);
  assert.equal((await f.request('foreign','grantMembership',{organizationId:f.a.org.id,email:f.users.client.email,role:'reception',version:0})).status,403);
  assert.equal((await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'reception',version:0})).error.code,'VERSION_CONFLICT');
  const revoke=await f.request('owner','revokeMembership',{id:grant.result.id,version:1});assert.equal(revoke.status,200,JSON.stringify(revoke));assert.equal(revoke.result.version,2);
  assert.equal((await f.request('foreign',null,{}, {verb:'GET',url:'/api/madbeauty/session'})).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await f.request('foreign','workspace',f.a.scope)).status,403);
  const restored=await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.foreign.email,role:'reception',version:2});assert.equal(restored.status,200,JSON.stringify(restored));assert.equal(restored.result.id,grant.result.id);assert.equal(restored.result.version,3);
  assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.membershipId===grant.result.id).length,3);assert.equal(f.source.organizationRecords('memberships',f.a.org.id).some(m=>m.accountId===f.users.foreign.id),false);
  assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM email_challenges').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Current target capability precedes central email lookup, and revocation between identity preflight and command prevents recipient admission',async()=>{
 const f=fixture();try{
  let lookups=0;const prepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{if(q==='SELECT id FROM accounts WHERE site_id=? AND email=?')lookups++;return prepare(q);};
  for(const email of [f.users.client.email,'unknown-scope@example.com'])assert.equal((await f.request('foreign','createClient',{organizationId:f.a.org.id,email,name:'Denied'})).status,403);
  assert.equal((await f.request('reception','grantMembership',{organizationId:f.a.org.id,email:f.users.client.email,role:'manager',version:0})).status,403);assert.equal(lookups,0);assert.equal(f.target.recordById('clients',f.users.foreign.id),null);
  assert.equal((await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:'unknown-scope@example.com',role:'manager',version:0})).error.code,'NOT_FOUND');assert.equal(lookups,1);assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE email=?').get('unknown-scope@example.com'),undefined);
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{
   const result=f.command.execute(packet);if(packet.method==='identityActionScope'&&!result.error)createPlatform(f.target).revokeMembership(f.users.owner,{id:f.membership.id,version:1});return result;
  }})});
  await assert.rejects(directory.dispatch('createClient',f.users.reception,{organizationId:f.a.org.id,email:f.users.foreign.email,name:'No recipient after revocation'}),e=>e.code==='FORBIDDEN');
  assert.equal(f.target.recordById('clients',f.users.foreign.id),null);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);
  assert.equal((await f.request('owner','identityActionScope',{organizationId:f.a.org.id,operation:'createClient'})).status,404);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Signed recipient cache binds the selected email and operation; target account, client link, access journal and nonce roll back together',()=>{
 const f=fixture();try{
  const issuer=createDirectoryCacheIssuer(f.source),actor={...f.users.owner,operator:true},packet=(method,extra={})=>{const body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'identity-'+method,expiresAt:now+20000,method,actor,input:{organizationId:f.a.org.id,email:f.users.foreign.email,name:'Private name',role:'manager',version:0},cache:issuer.issue(actor.id,f.users.foreign.id),...extra};return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};},resign=value=>{const {proof,...body}=value;return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};};
  const original=packet('createClient'),bad=structuredClone(original);bad.cache.recipientId=f.users.client.id;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.cache.accounts[1].operator=1;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.cache.clients[1].favorites=[f.b.org.id];assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.cache=structuredClone(original.cache);bad.method='session';assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.method='grantMembership';bad.input.email=f.users.client.email;assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');
  assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);
  const before=f.target.rowStats(),prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const s=prepare(q);return q.startsWith('INSERT INTO organization_directory_commands')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated identity nonce post-write failure');}}:s;};
  assert.equal(f.command.execute(original).error.code,'SERVER_ERROR');assert.equal(f.target.recordById('clients',f.users.foreign.id),null);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.users.foreign.id),undefined);assert.deepEqual(f.target.rowStats(),before);
  const grant=packet('grantMembership');assert.equal(f.command.execute(grant).error.code,'SERVER_ERROR');assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.next.accountId===f.users.foreign.id).length,0);assert.equal(f.target.organizationRecords('memberships',f.a.org.id).some(m=>m.accountId===f.users.foreign.id),false);assert.equal(f.target.recordById('clients',f.users.foreign.id),null);
  f.target.db.prepare=prepare;const once=f.command.execute(grant),again=f.command.execute(grant);assert.ok(once.result,JSON.stringify(once));assert.deepEqual(again,once);assert.equal(f.target.organizationRecords('accessChanges',f.a.org.id).filter(c=>c.next.accountId===f.users.foreign.id).length,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('A new manual client is centrally provisioned with a durable intent and one target link; repeated keys keep the same ID and preserve later global name changes',async()=>{
 const f=fixture();try{
  const input={organizationId:f.a.org.id,email:' NEW-DIRECTORY-MANUAL@EXAMPLE.COM ',name:'  Naujas kliento įrašas  ',idempotencyKey:'manual-client-one'};
  const first=await f.request('owner','createClient',input);assert.equal(first.status,200,JSON.stringify(first));assert.equal(first.result.admission.state,'applied');const id=first.result.id;
  assert.equal(f.source.db.prepare('SELECT id,name,operator FROM accounts WHERE email=?').get('new-directory-manual@example.com').id,id);assert.equal(f.source.recordById('clients',id).name,'Naujas kliento įrašas');assert.equal(f.target.recordById('clients',id).id,id);assert.equal(f.source.organizationRecords('clientLinks',f.a.org.id).some(c=>c.clientId===id),false);
  const before=f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===id);assert.equal(before.version,1);assert.equal((await f.request('owner','createClient',input)).result.id,id);assert.deepEqual(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===id),before);
  const changed=await f.request('owner','createClient',{...input,name:'Changed same request'});assert.equal(changed.error.code,'IDEMPOTENCY_CONFLICT');assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===id).version,1);
  const challenge=f.auth.start(f.auth.session(null),'new-directory-manual@example.com','127.0.0.1'),anonymous=f.source.db.prepare('SELECT session_hash FROM email_challenges WHERE id=?').get(challenge.challengeId),session=f.source.db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(anonymous.session_hash),verified=f.auth.verify(session,challenge.challengeId,f.source.capture(challenge.challengeId).code,'127.0.0.1');assert.equal(verified.user.id,id);
  const data=f.source.readClient(id);data.clients[0].name='Vėlesnis paskyros vardas';data.clients[0].version++;f.source.transaction(()=>{f.source.db.prepare('UPDATE accounts SET name=? WHERE id=?').run(data.clients[0].name,id);f.source.writeClient(data);});assert.equal((await f.request('owner','createClient',input)).result.id,id);assert.equal(f.source.recordById('clients',id).name,'Vėlesnis paskyros vardas');
  assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_client_admissions').get().n,1);assert.equal(f.source.db.prepare("SELECT COUNT(*) AS n FROM directory_client_admissions WHERE state='applied'").get().n,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM email_challenges').get().n,0);
 }finally{f.close();}
});

test('Lost manual-client reply and central acknowledgement failure remain pending and recover one target receipt without a duplicate link or event',async()=>{
 const f=fixture();try{
  let loseReply=true;const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{const result=f.command.execute(packet);if(packet.method==='createClient'&&loseReply){loseReply=false;throw Error('Isolated lost committed client reply');}return result;}})}),input={organizationId:f.a.org.id,email:'pending-directory-manual@example.com',name:'Laukiantis klientas',idempotencyKey:'pending-client-one'};
  const pending=await directory.dispatch('createClient',f.users.reception,input);assert.equal(pending.admission.state,'pending');const id=pending.id,row=f.source.db.prepare('SELECT * FROM directory_client_admissions WHERE account_id=?').get(id);assert.equal(row.state,'pending');assert.equal(directory.nextClientAdmissionAt(),now+30000);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).filter(c=>c.clientId===id).length,1);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_client_admissions').get().n,1);
  createPlatform(f.target).revokeMembership(f.users.owner,{id:f.membership.id,version:1});f.source.db.prepare('UPDATE directory_client_admissions SET due_at=0').run();await directory.flushClientAdmissions();assert.equal(f.source.db.prepare('SELECT state FROM directory_client_admissions WHERE id=?').get(row.id).state,'applied');assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===id).version,1);
  const prepare=f.source.db.prepare.bind(f.source.db);let fail=true;f.source.db.prepare=q=>{const s=prepare(q);return q.startsWith("UPDATE directory_client_admissions SET state='applied'")?{...s,run:(...args)=>{s.run(...args);if(fail){fail=false;throw Error('Isolated central admission acknowledgement failure');}}}:s;};
  const second={organizationId:f.a.org.id,email:'receipt-directory-manual@example.com',name:'Kvitą atkuriantis klientas',idempotencyKey:'receipt-client-one'},receipt=await f.directory.dispatch('createClient',f.users.owner,second);assert.equal(receipt.admission.state,'pending');f.source.db.prepare=prepare;
  const pair=await Promise.all([f.directory.dispatch('createClient',f.users.owner,second),f.directory.dispatch('createClient',f.users.owner,second)]);assert.equal(pair[0].admission.state,'applied');assert.equal(pair[1].id,receipt.id);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).filter(c=>c.clientId===receipt.id).length,1);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===receipt.id).version,1);assert.equal(f.target.organizationRecords('events',f.a.org.id).filter(e=>e.type==='client-added'&&e.entityId===receipt.id).length,1);
  assert.equal(f.source.db.prepare("SELECT COUNT(*) AS n FROM directory_client_admissions WHERE state='pending'").get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Manual-client validation and central post-insert failure create no orphan; target post-receipt failure rolls back its cache/link and durable retry later applies',async()=>{
 const f=fixture();try{
  const input={organizationId:f.a.org.id,email:'rollback-directory-manual@example.com',name:'Rollback klientas',idempotencyKey:'rollback-client-one'};
  assert.equal((await f.request('foreign','createClient',input)).status,403);assert.equal((await f.request('owner','createClient',{...input,email:'invalid-email'})).error.code,'INVALID_INPUT');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_client_admissions').get().n,0);assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE email=?').get(input.email),undefined);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=sourcePrepare(q);return q.startsWith('INSERT INTO directory_client_admissions')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated central provisioning post-write failure');}}:s;};assert.equal((await f.request('owner','createClient',input)).status,500);f.source.db.prepare=sourcePrepare;assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE email=?').get(input.email),undefined);assert.equal(f.source.readCollections(['clients']).clients.some(c=>c.email===input.email),false);assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_client_admissions').get().n,0);
  const targetPrepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const s=targetPrepare(q);return q.startsWith('INSERT INTO organization_client_admissions')?{...s,run:(...args)=>{s.run(...args);throw Error('Isolated target admission post-receipt failure');}}:s;};const pending=await f.request('owner','createClient',input);assert.equal(pending.status,200,JSON.stringify(pending));assert.equal(pending.result.admission.state,'pending');const id=pending.result.id;f.target.db.prepare=targetPrepare;
  assert.ok(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(id));assert.equal(f.target.db.prepare('SELECT id FROM accounts WHERE id=?').get(id),undefined);assert.equal(f.target.recordById('clients',id),null);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_client_admissions').get().n,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
  f.source.db.prepare('UPDATE directory_client_admissions SET due_at=0').run();await f.directory.flushClientAdmissions();assert.equal(f.source.db.prepare('SELECT state FROM directory_client_admissions WHERE account_id=?').get(id).state,'applied');assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===id).version,1);
 }finally{f.close();}
});

test('Client admission capacity rejects before provisioning, recorded permission failure remains explicit, and only the same signed actor/input can recover a receipt',async()=>{
 const f=fixture();try{
  let admissionPacket;const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{
   if(packet.method==='createClient'){admissionPacket=structuredClone(packet);createPlatform(f.target).revokeMembership(f.users.owner,{id:f.membership.id,version:1});}return f.command.execute(packet);
  }})}),input={organizationId:f.a.org.id,email:'permission-directory-manual@example.com',name:'Teisių bandymo klientas',idempotencyKey:'permission-client-one'};
  await assert.rejects(directory.dispatch('createClient',f.users.reception,input),e=>e.code==='FORBIDDEN');const failed=f.source.db.prepare('SELECT * FROM directory_client_admissions WHERE request_key=?').get(input.idempotencyKey);assert.equal(failed.state,'failed');assert.equal(failed.error_code,'FORBIDDEN');assert.equal(f.target.recordById('clients',failed.account_id),null);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).length,0);assert.ok(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(failed.account_id));
  await f.request('owner','grantMembership',{organizationId:f.a.org.id,email:f.users.reception.email,role:'reception',version:2});const restored=await f.directory.dispatch('createClient',f.users.reception,input);assert.equal(restored.admission.state,'applied');assert.equal(restored.id,failed.account_id);
  const resign=packet=>{const {proof:signature,...body}=packet;return {...body,proof:organizationTransferProof(f.source,'directory-command',body)};},bad=structuredClone(admissionPacket);bad.nonce='forged-client-recovery';bad.input.name='Forged receipt input';assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.input=admissionPacket.input;bad.actor={...f.users.owner,operator:true};assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');bad.actor=admissionPacket.actor;bad.method='grantMembership';assert.equal(f.command.execute(resign(bad)).error.code,'DIRECTORY_CONTEXT_INVALID');
  const data=f.target.readOrganization(f.a.org.id,[f.users.owner.id]);for(let n=data.clientLinks.length;n<1000;n++)data.clientLinks.push({id:'capacity-client-link-'+n,organizationId:f.a.org.id,clientId:'capacity-account-'+n,name:'Isolated capacity row',version:1});f.target.writeOrganization(data);
  const capacity={organizationId:f.a.org.id,email:'capacity-directory-manual@example.com',name:'No provision at capacity',idempotencyKey:'capacity-client-one'};assert.equal((await f.request('owner','createClient',capacity)).error.code,'LIMIT');assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE email=?').get(capacity.email),undefined);assert.equal((await f.directory.dispatch('createClient',f.users.reception,input)).id,failed.account_id);assert.equal(f.target.organizationRecords('clientLinks',f.a.org.id).find(c=>c.clientId===failed.account_id).version,1);
 }finally{f.close();}
});


test('Favorites use the current target profile, stay central and can remove an archived bookmark without trusting the sealed copy',async()=>{
 const f=fixture();try{
  const saved=await f.request('client','favorite',{organizationId:f.a.org.id,saved:true});assert.equal(saved.status,200,JSON.stringify(saved));assert.deepEqual(saved.result,[f.a.org.id]);assert.equal(f.target.recordById('clients',f.users.client.id).favoriteIds,undefined);
  const view=f.target.readOrganization(f.a.org.id);view.organizations[0].approved=false;f.target.writeOrganization(view);assert.equal(f.source.recordById('organizations',f.a.org.id).approved,true);
  assert.equal((await f.request('client','favorite',{organizationId:f.a.org.id,saved:true})).error.code,'NOT_FOUND');assert.deepEqual((await f.request('client','favorite',{organizationId:f.a.org.id,saved:false})).result,[]);
  const unavailable=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:()=>{throw Error('Favorite profile unavailable');}})});await assert.rejects(unavailable.dispatch('favorite',f.users.client,{organizationId:f.a.org.id,saved:true}),e=>e.code==='ORGANIZATION_UNAVAILABLE');assert.deepEqual(f.source.recordById('clients',f.users.client.id).favoriteIds,[]);
  assert.equal((await f.request('client','favorite',{organizationId:f.a.org.id,saved:'true'})).error.code,'INVALID_INPUT');assert.equal((await f.request('owner','metrics')).status,200);assert.equal(f.source.recordById('clients',f.users.foreign.id).favoriteIds,undefined);
 }finally{f.close();}
});

test('Central taxonomy writes only its indexed scope, preserves sealed organizations and propagates current revisions through signed target cache',async()=>{
 const cold=openStore({filename:':memory:',secret,clock:()=>now});try{const api=createPlatform(cold),before=api.taxonomy().version,changed=api.changeTaxonomy({id:'cold-operator',operator:true},{version:before,nodeId:'manikiuras',operation:'aliases',aliases:['Cold catalogue']});assert.notEqual(changed.version,before);assert.deepEqual(api.taxonomy().nodes.find(n=>n.id==='manikiuras').aliases,['Cold catalogue']);assert.equal(cold.readCollections(['events']).events.length,1);}finally{cold.close();}
 const f=fixture({large:true});try{
  const before=f.source.recordById('services',f.a.service.id),version=f.api.taxonomy().version,read=f.source.read;f.source.read=()=>{throw Error('Global catalogue must not read all private history');};
  const denied=await f.request('client','changeTaxonomy',{version,nodeId:'manikiuras',operation:'aliases',aliases:['Denied']});assert.equal(denied.error.code,'FORBIDDEN');
  const changed=await f.request('owner','changeTaxonomy',{version,nodeId:'manikiuras',operation:'aliases',aliases:['Aktuali katalogo procedūra']});assert.equal(changed.status,200,JSON.stringify(changed));assert.notEqual(changed.result.version,version);assert.deepEqual(f.source.recordById('services',f.a.service.id),before);
  assert.equal((await f.request('owner','changeTaxonomy',{version,nodeId:'manikiuras',operation:'aliases',aliases:['Stale']})).error.code,'VERSION_CONFLICT');await f.directory.dispatch('catalog',null,{});assert.equal(f.target.readCollections(['taxonomyVersion']).taxonomyVersion,changed.result.version);
  assert.throws(()=>f.target.readCatalogue(),e=>e.code==='FORBIDDEN');const foreign=f.source.readCatalogue();foreign.organizations.push({...f.b.org,name:'Cross-scope'});assert.throws(()=>f.source.writeCatalogue(foreign),/another scope/);
  const write=f.source.writeCatalogue;f.source.writeCatalogue=d=>{write(d);throw Error('Catalogue post-write failure');};await assert.rejects(f.directory.dispatch('changeTaxonomy',f.users.owner,{version:changed.result.version,nodeId:'manikiuras',operation:'aliases',aliases:['Rolled back']}),/post-write/);f.source.writeCatalogue=write;assert.equal(f.api.taxonomy().version,changed.result.version);f.source.read=read;
  assert.equal(f.source.rowStats().bytes,Buffer.byteLength(JSON.stringify(f.source.read())));assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,0);
 }finally{f.close();}
});

test('Operator metrics count current organization rows once and catalogue conversion safely resumes after a committed target reply is lost',async()=>{
 const f=fixture();try{
  f.source.clock=f.target.clock=()=>now+3*86400000;
  assert.equal((await f.request('owner','completeBooking',{id:f.first.id,version:1,scope:f.a.scope})).status,200);assert.equal((await f.request('owner','completeBooking',{id:f.other.id,version:1,scope:f.b.scope})).status,200);
  const view=f.target.readOrganization(f.a.org.id);view.inquiries.push({id:'current-target-inquiry',organizationId:f.a.org.id,clientId:f.users.client.id,status:'open'});f.target.writeOrganization(view);
  const metrics=await f.request('owner','metrics');assert.equal(metrics.status,200,JSON.stringify(metrics));assert.equal(metrics.result.realVisits,2);assert.equal(metrics.result.realInquiries,1);assert.equal(metrics.result.demand,'TESTING_NOT_MEASURED');assert.equal((await f.request('client','metrics')).status,403);
  let lost=true;const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{const result=f.command.execute(packet);if(packet.method==='migrateOrganizationCatalogue'&&lost){lost=false;throw Error('Committed catalogue reply lost');}return result;}})});
  await assert.rejects(directory.dispatch('migrateCatalogue',f.users.client,{}),e=>e.code==='FORBIDDEN');await assert.rejects(directory.dispatch('migrateCatalogue',f.users.owner,{}),e=>e.code==='ORGANIZATION_UNAVAILABLE');
  assert.ok(f.target.recordById('services',f.a.service.id).offerId);assert.ok(f.source.recordById('services',f.b.service.id).offerId);assert.equal(f.source.recordById('services',f.a.service.id).offerId,undefined);
  const recovered=await directory.dispatch('migrateCatalogue',f.users.owner,{});assert.equal(recovered.added,0);assert.equal(recovered.services,2);assert.equal(recovered.bookings,2);assert.equal(f.target.readCollections(['offers']).offers.filter(o=>o.legacyServiceId===f.a.service.id).length,1);assert.equal(f.target.readCollections(['events']).events.filter(e=>e.type==='catalogue-migrated').length,1);
  const final=await f.directory.dispatch('metrics',f.users.owner,{}),central=f.api.metrics({...f.users.owner,operator:true},{excludeOrganizationIds:[f.a.org.id]}),target=createPlatform(f.target).metrics({...f.users.owner,operator:true});assert.equal(final.events,central.events+target.events);assert.equal(final.realVisits,2);
 }finally{f.close();}
});


function pendingMailFixture(){const f=fixture();f.target.db.prepare("UPDATE mail_outbox SET state='pending' WHERE state='captured' AND challenge_id IS NULL").run();const mail=f.target.mail;f.target.mail=input=>{const id=mail(input);f.target.db.prepare("UPDATE mail_outbox SET state='pending' WHERE id=?").run(id);return id;};return f;}

test('Delegated organization mail retains one accepted central receipt after a committed acknowledgement reply is lost',async()=>{
 const f=pendingMailFixture();try{
  let timer=now,lost=true;f.source.clock=f.target.clock=()=>timer;const sent=[];
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:packet=>{const result=f.command.execute(packet);if(packet.method==='ackOrganizationMail'&&lost){lost=false;throw Error('Committed mail acknowledgement reply lost');}return result;}})});
  await directory.drainOrganizationMail(async claim=>sent.push(claim.id));assert.equal(sent.length,1);const mailId=sent[0];assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get(mailId).state,'accepted');assert.equal(f.source.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get(mailId).state,'captured');
  assert.equal(f.source.db.prepare('SELECT phase FROM directory_organization_mail WHERE mail_id=?').get(mailId).phase,'ack-pending');timer+=31000;await directory.drainOrganizationMail(async claim=>sent.push(claim.id));assert.equal(sent.length,1);assert.equal(f.source.db.prepare('SELECT phase FROM directory_organization_mail WHERE mail_id=?').get(mailId).phase,'complete');assert.equal(f.target.db.prepare('SELECT attempts FROM mail_outbox WHERE id=?').get(mailId).attempts,1);
  assert.equal((await f.request('client','organizationMailCandidates')).status,404);assert.equal((await f.request('owner','claimOrganizationMail',{id:mailId})).status,404);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);
 }finally{f.close();}
});

test('Mail admission checks source preferences again after target claim and suppresses an opted-out reminder while confirmations remain separate',async()=>{
 const f=pendingMailFixture();try{
  let timer=Date.parse(f.first.startAt)-1440*60000+1000,changed=false;f.source.clock=f.target.clock=()=>timer;
  const outage=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:()=>{throw Error('Control delivery outage');}})}),sent=[];
  const directory=createOrganizationDirectory(f.source,{getTarget:()=>({executeDirectoryCommand:async packet=>{const result=f.command.execute(packet);if(packet.method==='claimOrganizationMail'&&result.result?.type==='reminder'&&!changed){changed=true;const preference=await outage.dispatch('preferences',f.users.client,{service:false,marketing:false,reminderLeadMin:0});assert.equal(preference.synchronization,'pending');}return result;}})});
  await directory.drainOrganizationMail(async claim=>sent.push(claim.type));assert.deepEqual(sent,['confirmation']);assert.equal(changed,true);assert.equal(f.source.clientRecords('preferences',f.users.client.id)[0].service,false);
  const reminder=f.target.db.prepare("SELECT id,state FROM mail_outbox WHERE type='reminder'").get();assert.equal(reminder.state,'expired');assert.equal(f.source.db.prepare('SELECT outcome,phase FROM directory_organization_mail WHERE mail_id=?').get(reminder.id).outcome,'expired');assert.equal(f.source.db.prepare('SELECT outcome,phase FROM directory_organization_mail WHERE mail_id=?').get(reminder.id).phase,'complete');
 }finally{f.close();}
});

test('Rejected organization transport backs off and uses the same stable mail identity on the next successful attempt',async()=>{
 const f=pendingMailFixture();try{
  let timer=now,calls=0;f.source.clock=f.target.clock=()=>timer;const ids=[];const send=async claim=>{ids.push(claim.id);if(++calls===1)throw Error('Isolated mail relay unavailable');};
  await f.directory.drainOrganizationMail(send);const id=ids[0],row=f.target.db.prepare('SELECT state,next_attempt_at,attempts FROM mail_outbox WHERE id=?').get(id);assert.equal(row.state,'pending');assert.equal(row.attempts,1);assert.equal(row.next_attempt_at,timer+15000);await f.directory.drainOrganizationMail(send);assert.equal(calls,1);
  timer+=15001;await f.directory.drainOrganizationMail(send);assert.deepEqual(ids,[id,id]);assert.equal(f.target.db.prepare('SELECT state,attempts FROM mail_outbox WHERE id=?').get(id).state,'accepted');assert.equal(f.target.db.prepare('SELECT state,attempts FROM mail_outbox WHERE id=?').get(id).attempts,2);assert.equal(f.source.db.prepare('SELECT phase FROM directory_organization_mail WHERE mail_id=?').get(id).phase,'complete');
  assert.equal(Object.keys(f.source.db.prepare('SELECT * FROM directory_organization_mail WHERE mail_id=?').get(id)).includes('recipient'),false);assert.equal(Object.keys(f.source.db.prepare('SELECT * FROM directory_organization_mail WHERE mail_id=?').get(id)).includes('payload'),false);
 }finally{f.close();}
});

test('Mail claim/cache/lease roll back on nonce failure, wrong acknowledgement binding is denied, and receipt failure after acceptance remains explicitly uncertain',async()=>{
 const f=pendingMailFixture();try{
  let timer=now;f.source.clock=f.target.clock=()=>timer;const mailId=f.target.db.prepare('SELECT id FROM mail_outbox WHERE booking_id=?').get(f.first.id).id;
  const prepare=f.target.db.prepare.bind(f.target.db);f.target.db.prepare=q=>{const statement=prepare(q);return q.startsWith('INSERT INTO organization_directory_commands')?{...statement,run:(...args)=>{statement.run(...args);throw Error('Mail nonce commit failure');}}:statement;};let calls=0;await assert.rejects(f.directory.drainOrganizationMail(async()=>calls++),e=>e.code==='SERVER_ERROR');f.target.db.prepare=prepare;assert.equal(calls,0);assert.equal(f.target.db.prepare('SELECT state,attempts FROM mail_outbox WHERE id=?').get(mailId).state,'pending');assert.equal(f.target.db.prepare('SELECT attempts FROM mail_outbox WHERE id=?').get(mailId).attempts,0);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM organization_mail_claims').get().n,0);
  const sourcePrepare=f.source.db.prepare.bind(f.source.db);let receiptFailure=true;f.source.db.prepare=q=>{const statement=sourcePrepare(q);return q.startsWith('UPDATE directory_organization_mail SET phase=')&&q.includes('ack-pending')&&receiptFailure?{...statement,run:(...args)=>{receiptFailure=false;statement.run(...args);throw Error('Accepted receipt post-write failure');}}:statement;};const transportIds=new Set();const send=async claim=>{calls++;transportIds.add(claim.id);};await assert.rejects(f.directory.drainOrganizationMail(send),/post-write failure/);f.source.db.prepare=sourcePrepare;assert.equal(calls,1);assert.equal(f.source.db.prepare('SELECT phase FROM directory_organization_mail WHERE mail_id=?').get(mailId).phase,'reserved');assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get(mailId).state,'sending');await f.directory.drainOrganizationMail(send);assert.equal(calls,1);
  const claim=f.target.db.prepare('SELECT lease_token,message_hash FROM organization_mail_claims WHERE mail_id=?').get(mailId),cache=createDirectoryCacheIssuer(f.source).issue(null),body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.a.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'wrong-mail-lease',expiresAt:timer+20000,method:'ackOrganizationMail',actor:null,input:{id:mailId,leaseToken:'wrong-lease',messageHash:claim.message_hash,outcome:'accepted'},cache};assert.equal(f.command.execute({...body,proof:organizationTransferProof(f.source,'directory-command',body)}).error.code,'MAIL_LEASE_CONFLICT');assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get(mailId).state,'sending');
  timer+=60001;await f.directory.drainOrganizationMail(send);assert.equal(calls,2);assert.equal(transportIds.size,1);assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get(mailId).state,'accepted');
 }finally{f.close();}
});

function secondMailTarget(f){
 const target=openStore({filename:':memory:',secret,clock:()=>now}),handoff=createOrganizationHandoff(f.source),frozen=handoff.freeze({operatorAccountId:f.users.owner.id,organizationId:f.b.org.id,epoch:0,requestKey:'second-mail-fixture'}),control={operatorAccountId:f.users.owner.id,organizationId:f.b.org.id,epoch:frozen.epoch,handoffId:frozen.handoffId},stage=createOrganizationStaging(target,{targetName:frozen.targetName});
 let offset=0;do{const page=handoff.page({...control,offset});stage.accept(page);offset=page.nextOffset;if(page.done)break;}while(true);
 const commit=createOrganizationCommit(f.source),authority=createOrganizationAuthority(target,{targetName:frozen.targetName}),receipt=authority.prepare(commit.context(control));authority.activate(commit.seal({...control,targetReceipt:receipt}));const command=createOrganizationCommand(target,{targetName:frozen.targetName});target.db.prepare("UPDATE mail_outbox SET state='pending' WHERE state='captured' AND challenge_id IS NULL").run();return {target,command,frozen};
}

test('One unavailable organization does not prevent another accepted send, and the pump still reports the original recovery error',async()=>{
 const f=pendingMailFixture(),b=secondMailTarget(f);try{
  const directory=createOrganizationDirectory(f.source,{getTarget:name=>name===f.frozen.targetName?{executeDirectoryCommand:()=>{throw Error('One isolated namespace unavailable');}}:{executeDirectoryCommand:packet=>b.command.execute(packet)}}),sent=[];
  await assert.rejects(directory.drainOrganizationMail(async claim=>sent.push(claim.organizationId)),e=>e.code==='ORGANIZATION_UNAVAILABLE');assert.deepEqual(sent,[f.b.org.id]);assert.equal(b.target.db.prepare('SELECT state FROM mail_outbox WHERE booking_id=?').get(f.other.id).state,'accepted');assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE booking_id=?').get(f.first.id).state,'pending');
  await assert.rejects(directory.drainOrganizationMail(async claim=>sent.push(claim.organizationId)),e=>e.code==='ORGANIZATION_UNAVAILABLE');assert.equal(sent.length,1);
 }finally{b.target.close();f.close();}
});

test('Ten total mail admissions per cycle rotate the durable organization cursor; unsupported and OTP rows never enter the delegated queue',async()=>{
 const f=pendingMailFixture(),b=secondMailTarget(f);try{
  const template=f.target.db.prepare('SELECT * FROM mail_outbox WHERE booking_id=?').get(f.first.id),insert=f.target.db.prepare('INSERT INTO mail_outbox(id,site_id,account_id,organization_id,booking_id,challenge_id,recipient,type,payload,state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
  for(let n=0;n<11;n++)insert.run('bulk-mail-'+n,template.site_id,template.account_id,template.organization_id,template.booking_id,null,template.recipient,template.type,template.payload,'pending',now-100);
  insert.run('unsupported-mail',template.site_id,template.account_id,template.organization_id,null,null,template.recipient,'marketing','{}','pending',0);insert.run('forbidden-otp',template.site_id,template.account_id,template.organization_id,null,'private-challenge',template.recipient,'login-code','{}','pending',0);
  const directory=createOrganizationDirectory(f.source,{getTarget:name=>({executeDirectoryCommand:packet=>(name===f.frozen.targetName?f.command:b.command).execute(packet)})});f.source.db.prepare('INSERT OR REPLACE INTO directory_organization_mail_cursor VALUES(?,?)').run(f.source.siteId,f.b.org.id);const sent=[];
  await directory.drainOrganizationMail(async claim=>sent.push(claim));assert.equal(sent.length,10);assert.ok(sent.every(claim=>claim.organizationId===f.a.org.id));assert.equal(b.target.db.prepare('SELECT state FROM mail_outbox WHERE booking_id=?').get(f.other.id).state,'pending');
  await directory.drainOrganizationMail(async claim=>sent.push(claim));assert.equal(sent.length,13);assert.equal(sent[10].organizationId,f.b.org.id);assert.equal(new Set(sent.map(c=>c.id)).size,13);assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get('unsupported-mail').state,'pending');assert.equal(f.target.db.prepare('SELECT state FROM mail_outbox WHERE id=?').get('forbidden-otp').state,'pending');assert.equal(f.source.db.prepare('SELECT COUNT(*) AS n FROM directory_organization_mail').get().n,13);
  assert.equal(await directory.nextOrganizationMailAt(),Date.parse(f.first.startAt)-1440*60000);assert.equal(f.target.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);
 }finally{b.target.close();f.close();}
});
