import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
const now=Date.parse('2026-10-07T06:00:00Z');
function fixture(){
 const store=openStore({filename:':memory:',clock:()=>now,secret:'isolated-organization-patch-'.repeat(3)}),auth=createAuth(store),api=createPlatform(store),login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user;},owner=login('owner@example.com'),client=login('client@example.com'),operator={...owner,operator:true};
 const make=name=>{const org=api.createOrganization(owner,{name,bio:'Isolated organization mutation fixture.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),service=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Fixture manicure',durationMin:60,priceMinor:2500});api.moderate(operator,{id:api.submitRevision(owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,scope,service};};
 const a=make('Fixture A'),b=make('Fixture B'),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0];return {store,api,owner,client,a,b,candidate};
}
test('Organization booking writes avoid global history serialization, keep unrelated rows/reminders and exact size/idempotency through mixed mutations',()=>{
 const f=fixture(),{store,api,client}=f;try{
  const h=api.hold(client,f.candidate(f.b)),other=api.confirm(client,{holdId:h.id,idempotencyKey:'other-confirm',name:'Fixture client'}),job=store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(other.id),read=store.read;
  const d=read();for(let n=0;n<5000;n++){d.bookings.push({id:'unrelated-history-'+n,organizationId:f.b.org.id,clientId:'unrelated-client-'+n,status:'completed',startAt:'2026-01-01T07:00:00Z',endAt:'2026-01-01T08:00:00Z',serviceSnapshot:{description:'x'.repeat(500)}});d.clients.push({id:'unrelated-client-'+n,email:'isolated-'+n+'@example.com',name:'Unrelated fixture',version:1});d.idempotency['unrelated-client-'+n+':fixture']={bookingId:'unrelated-history-'+n};}store.write(d);
  const unrelated=store.organizationRecords('bookings',f.b.org.id),checkpoint=store.db.prepare('SELECT sha256 FROM state_migration_checkpoints').get().sha256;store.readOrganization(f.a.org.id,[client.id]);const prepare=store.db.prepare.bind(store.db);store.db.prepare=query=>{if(/(?:COUNT\(\*\)|MAX\(position\)).*FROM state_rows/i.test(query))throw Error('Forbidden history count scan during organization mutation');return prepare(query);};store.read=()=>{throw Error('Forbidden global read in organization mutation');};
  const candidate=f.candidate(f.a),hold=api.hold(client,candidate);assert.throws(()=>api.hold(client,candidate),e=>e.code==='SLOT_CONFLICT');const input={holdId:hold.id,idempotencyKey:'scoped-confirm',name:'Current fixture name'},booking=api.confirm(client,input);assert.equal(api.confirm(client,input).id,booking.id);api.message(client,{bookingId:booking.id,text:'Own scoped message'});
  assert.equal(store.recordById('bookings',booking.id).priceMinor,2500);assert.equal(store.recordById('clients',client.id).name,'Current fixture name');assert.deepEqual(store.organizationRecords('bookings',f.b.org.id),unrelated);assert.deepEqual(store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(other.id),job);
  api.cancelBooking(client,{id:booking.id,version:1,reason:'Isolated scope test'});assert.equal(store.recordById('bookings',booking.id).status,'canceled');assert.deepEqual(store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(other.id),job);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(booking.id).n,2);assert.equal(store.db.prepare('SELECT sha256 FROM state_migration_checkpoints').get().sha256,checkpoint);
  store.db.prepare=prepare;const raw=JSON.stringify(read());assert.equal(store.rowStats().bytes,Buffer.byteLength(raw));assert.equal(store.rowStats().records,store.db.prepare('SELECT COUNT(*) AS n FROM state_rows').get().n);assert.equal(store.rowStats().legacyMirrored,false);
 }finally{store.close();}
});
test('Provider catalogue, rules and roster patches stay in one indexed organization while account-wide waitlist limits remain global',()=>{
 const f=fixture(),{store,api,owner,client}=f,read=store.read;try{
  const d=read();d.selectionVersions[f.b.org.id]=12;for(let n=0;n<5000;n++)d.bookings.push({id:'retained-provider-history-'+n,organizationId:f.b.org.id,status:'completed',serviceSnapshot:{description:'x'.repeat(500)}});
  for(let n=0;n<20;n++)d.waitlist.push({id:'retained-wait-'+n,organizationId:f.b.org.id,clientId:client.id,state:'waiting',version:1});store.write(d);const foreign=store.organizationRecords('bookings',f.b.org.id);store.read=()=>{throw Error('Provider loaded global private history');};
  const selected=api.selectProcedures(owner,{organizationId:f.a.org.id,procedureIds:['kirpimai-vyru-kirpimas'],version:0,idempotencyKey:'scoped-procedures'}),group=api.saveMenuGroup(owner,{organizationId:f.a.org.id,label:'Scoped hair',rank:1});
  let offer=api.saveOffer(owner,{id:selected[0].id,version:selected[0].version,label:'Scoped cut',menuGroupId:group.id,variants:[{id:'scoped-provider-cut',label:'Cut',priceMinor:3000,durationMin:60,staffOptions:[{practitionerId:f.a.service.practitionerId,resourceId:f.a.service.resourceId}]}]});offer=api.submitOffer(owner,{id:offer.id,version:offer.version});offer=api.moderateOffer({...owner,operator:true},{id:offer.id,version:offer.version,state:'approved'});
  assert.equal(api.profile(f.a.org.id).services.find(s=>s.id==='scoped-provider-cut').menuGroupLabel,'Scoped hair');api.bulkOfferPrices(owner,{organizationId:f.a.org.id,idempotencyKey:'scoped-csv',updates:[{offerId:offer.id,version:offer.version,variantId:'scoped-provider-cut',practitionerId:'*',priceMinor:3100,durationMin:60}]});assert.equal(api.option('scoped-provider-cut').priceMinor,3000);
  api.createStaff(owner,{organizationId:f.a.org.id,name:'Scoped second staff'});api.createResource(owner,{organizationId:f.a.org.id,label:'Scoped second chair'});const org=store.recordById('organizations',f.a.org.id);api.saveBookingRules(owner,{organizationId:org.id,version:org.version,minLeadTimeMin:30,maxAdvanceDays:30,weekdays:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],closedDates:[]});
  const wait={organizationId:f.a.org.id,providerServiceId:f.a.service.id,dateKey:'2026-10-08',from:900,to:1200,addons:[],idempotencyKey:'account-wide-wait-limit'};assert.throws(()=>api.createWaitlist(client,wait),e=>e.code==='LIMIT');api.closeWaitlist(client,{id:'retained-wait-0',version:1});const item=api.createWaitlist(client,wait);assert.equal(item.organizationId,f.a.org.id);assert.equal(api.createWaitlist(client,wait).id,item.id);
  const professional=api.workspace(owner,{role:'professional',organizationId:f.a.org.id}),customer=api.workspace(client,{role:'customer'}),operator=api.workspace({...owner,operator:true},{role:'operator'});assert.equal(professional.bookings.length,0);assert.ok(!JSON.stringify(professional).includes('retained-provider-history-'));assert.equal(customer.bookings.length,0);assert.equal(customer.waitlist.length,21);assert.equal(customer.waitlist.filter(x=>!['closed','expired'].includes(x.state)).length,20);assert.equal(operator.bookings.length,0);
  assert.deepEqual(store.organizationRecords('bookings',f.b.org.id),foreign);assert.equal(store.readCollections(['selectionVersions']).selectionVersions[f.b.org.id],12);assert.equal(store.rowStats().bytes,Buffer.byteLength(JSON.stringify(read())));
 }finally{store.read=read;store.close();}
});
test('Organization patch rejects stale or unloaded foreign records/global metadata and rolls back oversized row with its outbox',()=>{
 const f=fixture(),{store}=f;try{
  const old=store.readOrganization(f.a.org.id,[f.owner.id]),d=store.read();d.organizations.find(o=>o.id===f.b.org.id).bio='Later authoritative edit';store.write(d);old.organizations[0].bio='Stale';assert.throws(()=>store.writeOrganization(old),e=>e.code==='VERSION_CONFLICT');assert.equal(store.recordById('organizations',f.b.org.id).bio,'Later authoritative edit');
  const foreign=store.readOrganization(f.a.org.id,[f.owner.id]);foreign.services.push({...f.b.service,organizationId:f.a.org.id});assert.throws(()=>store.writeOrganization(foreign),/unloaded record/);assert.equal(store.recordById('services',f.b.service.id).organizationId,f.b.org.id);
  const global=store.readOrganization(f.a.org.id,[f.owner.id]);global.taxonomy[0].label='Forbidden global change';assert.throws(()=>store.writeOrganization(global),/global metadata/);
  const foreignSelection=store.readOrganization(f.a.org.id,[f.owner.id]);foreignSelection.selectionVersions[f.b.org.id]=99;assert.throws(()=>store.writeOrganization(foreignSelection),/global metadata/);
  const version=store.rowStats().version;assert.throws(()=>store.transaction(()=>{store.mail({recipient:'fixture@example.com',type:'confirmation',payload:{bookingId:'isolated-oversized'}});const value=store.readOrganization(f.a.org.id,[f.owner.id]);value.organizations[0].bio='x'.repeat(129*1024);store.writeOrganization(value);}),e=>e.code==='CAPACITY');assert.equal(store.rowStats().version,version);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE recipient=?').get('fixture@example.com').n,0);
 }finally{store.close();}
});
