import {createProfileTools,publishedMediaIds,profileDetails,validateGallery} from './profile-tools.mjs';
import {createVisitApi,requireWholeVisit} from './visits.mjs';
import {createCustomerTools} from './customer-tools.mjs';
import {createOperations} from './operations.mjs';
import {createModeration,reporterReport} from './moderation.mjs';
import {REMINDER_LEADS,synchronizeReminders} from './notifications.mjs';
import {validateWaitlist,synchronizeWaitlist,claimWaitlist} from './waitlist.mjs';
import {visitSegments,bookingUses,occupiedRanges} from './occupancy.mjs';
import {createLocationApi,validateCoordinates} from './locations.mjs';
import {groupSearchRows,matchingQuotes} from './search-results.mjs';
import {publicLocation,distanceKm,locationSchedule,staffAtLocation,resourceAtLocation,bookingPlace} from './locations-state.mjs';
import {membershipScope,requireCapability,practitionerWorkspace} from './permissions.mjs';
import {CITY_NAMES} from '../prototype/cities.mjs';
import {matchesTaxonomy,normalizeSearch} from '../prototype/taxonomy.mjs';
import {createOfferApi,offerState,catalogueTaxonomy,serviceEligible} from './offers.mjs';
import {randomId,reject} from './primitives.mjs';
import {availability,option,find,plus,overlaps,dayOffsetForDate} from './availability.mjs';
import {localInstant,makeClock,TAXONOMY} from '../prototype/demo-model.mjs';
import {mediaPublic} from './primitives.mjs';
const copy=x=>structuredClone(x);
const text=(v,max=100)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)reject('INVALID_INPUT','Patikrinkite privalomus teksto laukus.');return v.trim();};
const number=(v,min,max)=>{if(!Number.isInteger(v)||v<min||v>max)reject('INVALID_INPUT','Netinkama skaitinė reikšmė.');return v;};
const cities=CITY_NAMES;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
function requireProfileService(d,organizationId){
  if(d.services.some(s=>s.organizationId===organizationId&&s.active))return;
  const offers=(d.offers||[]).filter(o=>o.organizationId===organizationId);
  if(offers.some(o=>o.state==='pending'))reject('INVALID_INPUT','Paslaugų pasiūlymai laukia peržiūros. Profilį pateikite patvirtinus bent vieną paslaugos variantą.');
  if(offers.some(o=>o.state==='returned'))reject('INVALID_INPUT','Paslaugų pasiūlymai grąžinti taisyti. Paslaugų skiltyje peržiūrėkite pastabas ir pateikite pasiūlymą iš naujo.');
  if(offers.some(o=>o.state==='draft'))reject('INVALID_INPUT','Paslaugų pasiūlymų skiltyje užpildykite kainą, trukmę ir meistrą, tada pateikite pasiūlymą peržiūrai.');
  reject('INVALID_INPUT','Pirmiausia pridėkite paslaugą.');
}
export function createPlatform(store,{deferOrganizationPreferences=()=>false,favoriteOrganization=null}={}){
  const clock=()=>makeClock(new Date(store.clock()).toISOString());
  const scope=(d,user,requested={})=>{
    if(!user)reject('UNAUTHENTICATED','Prisijunkite el. paštu.',401);
    if(requested.role==='operator'){if(!user.operator)reject('FORBIDDEN','Prieiga neleidžiama.',403);return {role:'operator',clientId:user.id,accountId:user.id};}
    if(requested.role==='professional'){
      return membershipScope(d,user,requested.organizationId);
    }
    return {role:'customer',clientId:user.id,accountId:user.id};
  };
  const ownOrg=(d,user,org,capability=null)=>requireCapability(scope(d,user,{role:'professional',organizationId:org}),capability);
  const ownBooking=(d,user,requested,id)=>{const b=find(d,'bookings',id),s=scope(d,user,requested);if(s.role==='operator'||s.role==='customer'&&b.clientId!==user.id||s.role==='professional'&&(b.organizationId!==s.organizationId||s.practitionerId&&!bookingUses(b,'practitionerId',s.practitionerId)))reject('FORBIDDEN','Šio vizito prieiga neleidžiama.',403);return b;};
  let catalogueMutation=null,organizationMutation=null,clientMutation=null,reconcileClientPreferences=false,creatingOrganizationId=null;
  const clientInput=input=>{const email=text(input.email,254).toLowerCase(),name=text(input.name,80);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))reject('INVALID_INPUT','Įrašykite teisingą el. paštą.');return {email,name};};
  const mutate=fn=>store.transaction(()=>{const d=catalogueMutation||organizationMutation||clientMutation||store.read();if(!catalogueMutation){d.media||=[];offerState(d);}const result=fn(d);
    if(catalogueMutation)store.writeCatalogue(d);else if(clientMutation){store.writeClient(d);if(reconcileClientPreferences){const accountId=d.clients[0]?.id,organizationIds=new Set([...store.clientRecords('bookings',accountId).filter(b=>b.status==='confirmed'&&Date.parse(b.endAt)>store.clock()),...store.clientRecords('waitlist',accountId).filter(w=>w.criteria&&!['closed','expired'].includes(w.state))].map(x=>x.organizationId));for(const id of organizationIds){if(deferOrganizationPreferences(id,accountId))continue;store.assertOrganizationWritable?.(id);const view=store.readOrganization(id);synchronizeWaitlist(store,view);synchronizeReminders(store,view);store.writeOrganization(view);}}}
    else{synchronizeWaitlist(store,d);synchronizeReminders(store,d);if(organizationMutation)store.writeOrganization(d);else store.write(d);}return copy(result);});
  const event=(d,type,id)=>d.events.push({id:randomId('event'),type,entityId:id,...(d.organizationContext?{organizationId:d.organizationContext}:{}),at:new Date(store.clock()).toISOString(),siteId:store.siteId});
  const outbox=(d,b,type)=>{const c=find(d,'clients',b.clientId);return store.mail({accountId:c.id,organizationId:b.organizationId,bookingId:b.id,recipient:c.email,type,payload:{bookingId:b.id,startAt:b.startAt,endAt:b.endAt,status:b.status,priceMinor:b.priceMinor}});};
  const slots=(d,input,opts={})=>availability(d,input,store.clock(),opts);
  const choose=(d,candidate,opts={})=>{
    if(!candidate||!Number.isFinite(Date.parse(candidate.snapshotAt))||Date.parse(candidate.snapshotAt)+300000<store.clock())reject('STALE_AVAILABILITY','Pasirinkimas paseno. Atnaujinkite laikus.',409);
    const dateKey=candidate.dateKey||new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(candidate.startAt));
    const result=slots(d,{providerServiceId:candidate.providerServiceId,addons:candidate.addonIds,practitionerId:candidate.practitionerId,dateKey,dayOffset:candidate.dayOffset,from:candidate.from,to:candidate.to},opts);
    const c=result.slots.find(s=>s.id===candidate.id&&s.serviceVersion===candidate.serviceVersion&&s.scheduleVersion===candidate.scheduleVersion&&s.locationVersion===candidate.locationVersion&&s.priceMinor===candidate.priceMinor);
    if(!c)reject('SLOT_CONFLICT','Laikas arba paslauga pasikeitė. Pasirinkite kitą laiką.',409);return c;
  };
  const publicOrg=o=>({id:o.id,name:o.name,kind:o.kind,city:o.city,locationId:o.locationId,bio:o.bio,gallery:o.gallery,avatarImageId:o.avatarImageId||null,approved:o.approved,profileState:o.profileState,calendarState:'current',version:o.version});
  const publicService=(d,s)=>{const o=find(d,'organizations',s.organizationId),p=find(d,'practitioners',s.practitionerId),l=publicLocation(d,s.locationId)||find(d,'locations',s.locationId);const staffOptions=s.staffOptions?.filter(x=>d.practitioners.some(p=>p.id===x.practitionerId&&staffAtLocation(d,p,s.locationId))&&d.resources.some(r=>r.id===x.resourceId&&resourceAtLocation(d,r,s.locationId))).map(x=>({...x,name:find(d,'practitioners',x.practitionerId).name}));return {...s,...(staffOptions?.length?{priceMinor:Math.min(...staffOptions.map(x=>x.priceMinor)),priceToMinor:Math.max(...staffOptions.map(x=>x.priceMinor)),durationMin:Math.min(...staffOptions.map(x=>x.durationMin)),durationToMin:Math.max(...staffOptions.map(x=>x.durationMin)),staffOptions}:{}),organizationName:o.name,practitionerName:p.name,initials:p.initials,city:l.city,kind:o.kind,area:l.area,location:publicLocation(d,s.locationId),calendarState:'current',avatarImageId:o.avatarImageId||null,media:(d.media||[]).filter(a=>a.id===o.avatarImageId).map(mediaPublic)};};
  const publicFields=['services','organizations','locations','practitioners','resources','media','qualifications','taxonomyChanges'];
  const readFields=fields=>store.readCollections?store.readCollections(fields):store.read();
  const publicRead=(extra=[])=>readFields([...publicFields,...extra]);
  const calendarRead=(d,organizationId)=>{const extra={};for(const table of ['schedules','bookings','busyBlocks','holds'])extra[table]=store.organizationRecords?store.organizationRecords(table,organizationId):store.read()[table].filter(x=>x.organizationId===organizationId);return {...d,...extra};};
  const catalogRows=(d,filters={})=>d.services.filter(s=>s.active&&serviceEligible(d,s,store.clock())&&d.organizations.some(o=>o.id===s.organizationId&&o.approved)).map(s=>publicService(d,s)).filter(s=>(!filters.city||s.city===filters.city)&&(!filters.taxonomyServiceId||filters.taxonomyServiceId==='all'||matchesTaxonomy(s.taxonomyServiceId,filters.taxonomyServiceId,catalogueTaxonomy(d)))&&(!filters.kind||s.kind===filters.kind)&&(!filters.name||normalizeSearch(s.label+' '+s.organizationName+' '+s.practitionerName+' '+(s.staffOptions||[]).map(p=>p.name).join(' ')).includes(normalizeSearch(filters.name)))&&(filters.maxPrice==null||s.priceMinor<=filters.maxPrice));
  const api={
    clock,
    session(user){const d=readFields(['memberships','organizations','practitioners']),favoriteIds=user?(store.recordById?store.recordById('clients',user.id):readFields(['clients']).clients.find(c=>c.id===user.id))?.favoriteIds||[]:[];return user?{favoriteIds:[...favoriteIds],user:{id:user.id,email:user.email,name:user.name},clientId:user.id,operator:!!user.operator,organizations:d.memberships.filter(m=>m.accountId===user.id&&m.active!==false).flatMap(m=>{try{return [{...publicOrg(find(d,'organizations',m.organizationId)),membershipRole:m.role,capabilities:membershipScope(d,user,m.organizationId).capabilities}];}catch{return [];}})}:{user:null,clientId:null,operator:false,organizations:[],favoriteIds:[]};},
    catalog(filters={}){return catalogRows(publicRead(),filters);},
    profile(id){const d=publicRead(['reviews']),o=d.organizations.find(o=>o.id===id&&o.approved);if(!o)return null;const services=d.services.filter(s=>s.organizationId===id&&s.active&&serviceEligible(d,s,store.clock())).map(s=>publicService(d,s)),schedules=store.organizationRecords('schedules',id),details=profileDetails(d,o,schedules,services,store.clock());return {...publicOrg(o),...details,media:(d.media||[]).filter(a=>publishedMediaIds(d,o).includes(a.id)&&a.moderationState!=='restricted').map(mediaPublic),location:publicLocation(d,o.locationId)||d.locations.filter(l=>l.organizationId===o.id).map(l=>publicLocation(d,l.id)).find(Boolean)||{city:o.city,publicAddress:''},locations:d.locations.filter(l=>l.organizationId===o.id).map(l=>publicLocation(d,l.id)).filter(Boolean),practitioners:d.practitioners.filter(p=>p.organizationId===id&&p.active).map(({accountId,avatarImageId,...p})=>({...p,avatarImageId:details.staffPortraits.find(x=>x.practitionerId===p.id)?.mediaId||null})),services,reviews:d.reviews.filter(r=>r.organizationId===id&&r.approved).map(({id,bookingId,rating,text,createdAt})=>({id,bookingId,rating,text,createdAt}))};},
    availability(input,user=null){
      const base=publicRead(['memberships']),service=find(base,'services',input.providerServiceId),d=calendarRead(base,service.organizationId),opts={};if(input.scope?.role==='professional'){const access=ownOrg(d,user,input.scope.organizationId);if(access.practitionerId&&input.practitionerId!==access.practitionerId)reject('FORBIDDEN','Pasirink savo meistro grafiką.',403);if(find(d,'services',input.providerServiceId).organizationId!==input.scope.organizationId)reject('FORBIDDEN','Kita organizacija.',403);opts.internal=true;}
      if(input.ignoreBookingId){const b=ownBooking(d,user,input.scope,input.ignoreBookingId);if(b.segments||b.providerServiceId!==input.providerServiceId)reject('FORBIDDEN','Paslaugos variantas nepriklauso šiam vizitui.',403);opts.ignoreBookingId=input.ignoreBookingId;opts.internal=true;}return slots(d,input,opts);
    },
    option(id,addons,practitionerId){const d=publicRead(),s=find(d,'services',id);if(!find(d,'organizations',s.organizationId).approved||!s.active||!serviceEligible(d,s,store.clock()))reject('NOT_FOUND','Paslauga nerasta.',404);const chosen=practitionerId?s.staffOptions?.find(p=>p.practitionerId===practitionerId):s.staffOptions?.[0];if(practitionerId&&!chosen&&practitionerId!==s.practitionerId)reject('INVALID_INPUT','Netinkamas meistras.');const selected=chosen?{...s,...chosen}:s;try{return option(selected,addons);}catch(e){if(e.code!=='ADDON_SELECTION_REQUIRED')throw e;return {...option(selected,addons,{validateGroups:false}),requiresSelection:true,selectionMessage:e.message};}},
    workspace(user,requested){
      const s=scope(readFields(['memberships','organizations','practitioners']),user,requested);let d;
      if(s.role==='professional'&&store.readOrganization)d=store.readOrganization(s.organizationId,[user.id],{includeClientHistory:true});
      else if(s.role==='customer'&&store.clientRecords){d=readFields(['organizations','services']);d.clients=[store.recordById('clients',user.id)].filter(Boolean);for(const table of ['bookings','messages','reviews','preferences','inquiries','waitlist','reports','dataRequests'])d[table]=store.clientRecords(table,user.id);}
      else if(s.role==='operator'&&store.readCollections)d=readFields(['organizations','locations','services','practitioners','resources','schedules','media','revisions','reviews','reports','offers','procedureRequests','qualifications','menuGroups','taxonomy','taxonomyChanges','taxonomyVersion','selectionVersions','isDemo','fixtureRuntime','dataRequests','events','accessChanges']);
      else d=store.read();
      if(s.role==='customer'){
        const requests=table=>d[table].filter(i=>i.clientId===user.id).map(i=>{const {id,organizationId,providerServiceId,note,status,state,createdAt}=i;return {id,organizationId,providerServiceId,note,status,state,createdAt,organizationName:d.organizations.find(o=>o.id===organizationId)?.name||'Paslaugos teikėjas',serviceLabel:d.services.find(v=>v.id===providerServiceId)?.label||'Paslauga',...(i.kind==='consultation'?{requestKind:'consultation'}:{}),...(i.criteria?{criteria:i.criteria,version:i.version,bookingId:i.bookingId||null,offer:i.offer?{id:i.offer.id,candidate:i.offer.candidate,expiresAt:i.offer.expiresAt}:null,deliveryStatus:i.deliveryStatus}: {})};});
        return {client:find(d,'clients',user.id),bookings:d.bookings.filter(b=>b.clientId===user.id),messages:d.messages.filter(m=>m.clientId===user.id),reviews:d.reviews.filter(r=>r.clientId===user.id).map(reporterReport),preferences:d.preferences.filter(p=>p.clientId===user.id),inquiries:requests('inquiries'),waitlist:requests('waitlist'),reports:d.reports.filter(r=>r.accountId===user.id).map(reporterReport),dataRequests:(d.dataRequests||[]).filter(r=>r.clientId===user.id).map(({actions,...r})=>r)};
      }
      const mail=store.db.prepare('SELECT id,organization_id AS organizationId,booking_id AS bookingId,state,type,attempts FROM mail_outbox WHERE site_id=? AND booking_id IS NOT NULL'+(s.role==='professional'?' AND organization_id=?':'')).all(store.siteId,...(s.role==='professional'?[s.organizationId]:[]));
      if(s.role==='operator')return {...d,catalogueNodes:catalogueTaxonomy(d),clients:[],bookings:[],messages:[],holds:[],memberships:[],inquiries:[],waitlist:[],preferences:[],clientLinks:[],clientCards:[],dataRequests:(d.dataRequests||[]).map(({id,state,createdAt,kind,version})=>({id,state,createdAt,kind,version})),outbox:mail};
      const b=d.bookings.filter(b=>b.organizationId===s.organizationId),links=(d.clientLinks||[]).filter(i=>i.organizationId===s.organizationId),clientIds=new Set([...b,...d.inquiries.filter(i=>i.organizationId===s.organizationId),...d.waitlist.filter(i=>i.organizationId===s.organizationId),...links].map(b=>b.clientId));
      return practitionerWorkspace(d,s,{membershipRole:s.membershipRole,practitionerId:s.practitionerId,capabilities:s.capabilities,selectionVersion:d.selectionVersions?.[s.organizationId]||0,catalogueNodes:catalogueTaxonomy(d).map(n=>({...n,enabled:n.scope==='core'})),...Object.fromEntries(Object.entries(d).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,k==='reports'?[]:k==='taxonomy'?v:k==='clients'?v.filter(c=>clientIds.has(c.id)).map(c=>({id:c.id,email:c.email,version:c.version,name:(d.clientCards||[]).find(x=>x.organizationId===s.organizationId&&x.clientId===c.id)?.name||links.find(l=>l.clientId===c.id)?.name||c.name})):v.filter(x=>x.organizationId===s.organizationId||k==='organizations'&&x.id===s.organizationId)])),outbox:mail.filter(m=>m.organizationId===s.organizationId),memberships:d.memberships.filter(m=>m.organizationId===s.organizationId).map(m=>({...m,...store.db.prepare('SELECT email,name FROM accounts WHERE id=? AND site_id=?').get(m.accountId,store.siteId)}))});
    },
    grantMembership(user,input){return mutate(d=>{const access=ownOrg(d,user,input.organizationId,'access');if(!['manager','reception','practitioner'].includes(input.role))reject('INVALID_INPUT','Pasirinkite vadybininko, registratūros arba meistro prieigą.');const account=store.db.prepare('SELECT id FROM accounts WHERE site_id=? AND email=?').get(store.siteId,text(input.email,254).toLowerCase());if(!account)reject('NOT_FOUND','Ši paskyra dar neprisijungė. Pakvieskite žmogų susikurti paskyrą savarankiškai.',404);if(account.id===user.id)reject('FORBIDDEN','Savo prieigos keisti negalima.',403);const old=d.memberships.find(m=>m.accountId===account.id&&m.organizationId===input.organizationId);if(old?.role==='owner')reject('FORBIDDEN','Savininko prieiga šiuo veiksmu nekeičiama.',403);if(input.version!==(old?.version||0))reject('VERSION_CONFLICT','Prieigos versija pasikeitė.',409);const practitionerId=input.role==='practitioner'?input.practitionerId:null;if(practitionerId&&find(d,'practitioners',practitionerId).organizationId!==input.organizationId)reject('FORBIDDEN','Kitos organizacijos meistras.',403);if(input.role==='practitioner'&&(!practitionerId||!find(d,'practitioners',practitionerId).active))reject('INVALID_INPUT','Priskirkite aktyvų šios vietos meistrą.');const previous=old?copy(old):null,m=old||{id:randomId('membership'),accountId:account.id,organizationId:input.organizationId};Object.assign(m,{role:input.role,practitionerId,active:true,version:(old?.version||0)+1});if(!old)d.memberships.push(m);d.accessChanges||=[];d.accessChanges.push({id:randomId('access-change'),organizationId:input.organizationId,membershipId:m.id,actorId:access.accountId,previous,next:copy(m),at:clock().now});event(d,'membership-granted',m.id);return m;});},
    revokeMembership(user,input){return mutate(d=>{const m=find(d,'memberships',input.id),access=ownOrg(d,user,m.organizationId,'access');if(m.role==='owner'||m.accountId===user.id)reject('FORBIDDEN','Savininko arba savo prieigos pašalinti negalima.',403);if(input.version!==(m.version||0))reject('VERSION_CONFLICT','Prieigos versija pasikeitė.',409);const previous=copy(m);m.active=false;m.version=(m.version||0)+1;d.accessChanges||=[];d.accessChanges.push({id:randomId('access-change'),organizationId:m.organizationId,membershipId:m.id,actorId:access.accountId,previous,next:copy(m),at:clock().now});event(d,'membership-revoked',m.id);return m;});},
    createOrganization(user,input){return mutate(d=>{
      if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);if((store.clientRecords?store.clientRecords('memberships',user.id):d.memberships.filter(m=>m.accountId===user.id)).length>=5)reject('LIMIT','Organizacijų limitas pasiektas.');
      if(!cities.includes(input.city)||!['solo','salon'].includes(input.kind))reject('INVALID_INPUT','Pasirinkite miestą ir veiklos tipą.');
      const org={id:creatingOrganizationId||randomId('provider'),name:text(input.name),bio:text(input.bio,600),city:input.city,kind:input.kind,locationId:randomId('location'),approved:false,profileState:'draft',gallery:[],draftGallery:[],draftAvatarImageId:null,avatarImageId:null,version:1,leadTimeMin:30,createdAt:new Date(store.clock()).toISOString()};
      d.organizations.push(org);d.locations.push({id:org.locationId,organizationId:org.id,city:org.city,area:String(input.area||'').slice(0,80),publicAddress:String(input.address||'').slice(0,200),openingHoursLabel:'Pagal darbo grafiką'});
      const practitioner={id:randomId('staff'),organizationId:org.id,locationId:org.locationId,name:text(input.practitionerName||input.name),initials:input.name.trim().slice(0,1).toUpperCase(),active:true,role:'owner',version:1};
      d.practitioners.push(practitioner);d.resources.push({id:randomId('resource'),organizationId:org.id,label:'Darbo vieta',active:true,version:1});
      d.schedules.push({id:practitioner.id+'-schedule',organizationId:org.id,practitionerId:practitioner.id,startMin:540,endMin:1200,breakStartMin:780,breakEndMin:840,closedDay:null,closedDate:null,weekdays:['Mon','Tue','Wed','Thu','Fri'],version:1});
      d.memberships.push({id:randomId('membership'),accountId:user.id,organizationId:org.id,role:'owner',active:true,version:1});event(d,'provider-created',org.id);return org;
    });},
    attachMedia(user,input){return mutate(d=>{ownOrg(d,user,input.organizationId,'profile');const o=find(d,'organizations',input.organizationId);if(d.media.filter(a=>a.organizationId===o.id).length>=24)reject('LIMIT','Profilio vaizdų limitas pasiektas.');d.media.push(copy(input));if(input.usage==='portrait')o.draftAvatarImageId=input.id;else {o.draftGallery=[...(o.draftGallery||o.gallery),input.id];o.draftGalleryEntries=[...(o.draftGalleryEntries||o.galleryEntries||(o.gallery||[]).filter(id=>d.media.some(a=>a.id===id&&a.usage==='gallery')).map(mediaId=>({mediaId,providerServiceId:null,caption:''}))),{mediaId:input.id,providerServiceId:null,caption:''}];}o.version++;return mediaPublic(input);});},
    createStaff(user,input){return mutate(d=>{ownOrg(d,user,input.organizationId,'team');const o=find(d,'organizations',input.organizationId);if(d.practitioners.filter(p=>p.organizationId===o.id).length>=32)reject('LIMIT','Komandos narių limitas pasiektas.');const name=text(input.name),p={id:randomId('staff'),organizationId:o.id,locationId:o.locationId,name,initials:name.split(/\s+/).map(v=>v[0]).slice(0,2).join(''),active:true,role:'staff',version:1};d.practitioners.push(p);d.schedules.push({id:p.id+'-schedule',organizationId:o.id,practitionerId:p.id,startMin:540,endMin:1200,breakStartMin:780,breakEndMin:840,closedDate:null,closedDay:null,weekdays:['Mon','Tue','Wed','Thu','Fri'],version:1});return p;});},
    createResource(user,input){return mutate(d=>{ownOrg(d,user,input.organizationId,'resources');if(d.resources.filter(r=>r.organizationId===input.organizationId).length>=32)reject('LIMIT','Darbo vietų limitas pasiektas.');const l=find(d,'locations',input.locationId||find(d,'organizations',input.organizationId).locationId);if(l.organizationId!==input.organizationId||l.active===false)reject('FORBIDDEN','Kita arba neaktyvi veiklos vieta.',403);const r={id:randomId('resource'),organizationId:input.organizationId,locationId:l.id,label:text(input.label),active:true,version:1};d.resources.push(r);return r;});},
    createClient(user,input){return mutate(d=>{
      ownOrg(d,user,input.organizationId,'clients');const {email,name}=clientInput(input);
      d.clientLinks||=[];if(d.clientLinks.filter(l=>l.organizationId===input.organizationId).length>=1000)reject('LIMIT','Klientų sąrašo limitas pasiektas.');
      let account=store.db.prepare('SELECT id FROM accounts WHERE site_id=? AND email=?').get(store.siteId,email);
      if(!account){account={id:randomId('account')};store.db.prepare('INSERT INTO accounts(id,site_id,email,name,created_at) VALUES(?,?,?,?,?)').run(account.id,store.siteId,email,name,store.clock());}
      if(!d.clients.some(c=>c.id===account.id))d.clients.push({id:account.id,accountId:account.id,email,name,version:1});
      const old=d.clientLinks.find(l=>l.organizationId===input.organizationId&&l.clientId===account.id);
      if(old){old.name=name;old.version++;}else d.clientLinks.push({id:randomId('client-link'),organizationId:input.organizationId,clientId:account.id,name,version:1,createdAt:clock().now});
      event(d,'client-added',account.id);return {id:account.id,name,email};
    });},
    createBusyBlock(user,input){return mutate(d=>{
      ownOrg(d,user,input.organizationId,'bookings');const from=number(input.from,0,1439),to=number(input.to,0,1439),offset=dayOffsetForDate(input,store.clock());
      if(from>=to||(!input.practitionerId&&!input.resourceId))reject('INVALID_INPUT','Pasirinkite meistrą arba darbo vietą ir tinkamą intervalą.');
      for(const [key,table] of [['practitionerId','practitioners'],['resourceId','resources']])if(input[key]&&find(d,table,input[key]).organizationId!==input.organizationId)reject('FORBIDDEN','Kita organizacija.',403);
      const at=min=>{try{return localInstant(clock(),offset,min);}catch{reject('INVALID_LOCAL_TIME','Šis vietinis laikas kartojasi arba neegzistuoja. Pasirinkite kitą intervalą.');}};
      const access=scope(d,user,{role:'professional',organizationId:input.organizationId});if(access.practitionerId&&(input.practitionerId!==access.practitionerId||input.resourceId))reject('FORBIDDEN','Galima tvarkyti tik savo meistro užimtumą.',403);const startAt=at(from),endAt=at(to),related=b=>(input.practitionerId&&bookingUses(b,'practitionerId',input.practitionerId))||(input.resourceId&&bookingUses(b,'resourceId',input.resourceId));
      if(Date.parse(startAt)<store.clock())reject('INVALID_INPUT','Praėjusio laiko blokuoti negalima.');
      if(d.bookings.some(b=>b.status==='confirmed'&&occupiedRanges(b).some(x=>related(x)&&overlaps(startAt,endAt,x.startAt,x.endAt)))||d.holds.some(h=>h.state==='held'&&Date.parse(h.expiresAt)>store.clock()&&occupiedRanges(h).some(x=>related(x)&&overlaps(startAt,endAt,x.startAt,x.endAt))))reject('SCHEDULE_CONFLICT','Intervale jau yra vizitas arba laikomas kliento pasirinkimas.',409);
      if(d.busyBlocks.some(b=>b.active!==false&&related(b)&&overlaps(startAt,endAt,b.startAt,b.endAt)))reject('SCHEDULE_CONFLICT','Šis intervalas jau užblokuotas.',409);
      const block={id:randomId('busy'),organizationId:input.organizationId,practitionerId:input.practitionerId||null,resourceId:input.resourceId||null,label:text(input.label,100),startAt,endAt,active:true,version:1,createdAt:clock().now};d.busyBlocks.push(block);event(d,'time-blocked',block.id);return block;
    });},
    releaseBusyBlock(user,input){return mutate(d=>{
      const b=find(d,'busyBlocks',input.id);const access=ownOrg(d,user,b.organizationId,'bookings');if(access.practitionerId&&b.practitionerId!==access.practitionerId)reject('FORBIDDEN','Kito meistro užimtumas.',403);if(b.version!==input.version)reject('VERSION_CONFLICT','Laiko blokas pasikeitė.',409);
      if(b.active===false)reject('VERSION_CONFLICT','Laikas jau atlaisvintas.',409);b.active=false;b.version=(b.version||0)+1;event(d,'time-released',b.id);return b;
    });},
    createService(user,input){return mutate(d=>{
      ownOrg(d,user,input.organizationId,'offers');const o=find(d,'organizations',input.organizationId),p=find(d,'practitioners',input.practitionerId),r=find(d,'resources',input.resourceId);
      if(p.organizationId!==o.id||r.organizationId!==o.id)reject('FORBIDDEN','Netinkamas meistras arba darbo vieta.',403);
      const tax=TAXONOMY.find(t=>t.id===input.taxonomyServiceId);if(!tax)reject('INVALID_INPUT','Pasirinkite paslaugos kategoriją.');
      const s={id:randomId('service'),organizationId:o.id,locationId:o.locationId,practitionerId:p.id,resourceId:r.id,taxonomyServiceId:tax.id,label:text(input.label),durationMin:number(input.durationMin,15,480),priceMinor:number(input.priceMinor,0,100000),bufferBeforeMin:number(input.bufferBeforeMin??0,0,120),bufferAfterMin:number(input.bufferAfterMin??0,0,120),currency:'EUR',imageId:tax.imageId,addons:[],active:true,version:1};d.services.push(s);return s;
    });},
    hold(user,candidate){return mutate(d=>{if(!user)reject('UNAUTHENTICATED','Prisijunkite prieš pasirinkdami laiką.',401);const c=choose(d,candidate);const h={...c,slotId:c.id,id:randomId('hold'),accountId:user.id,state:'held',expiresAt:plus(clock().now,2)};d.holds.push(h);return h;});},
    releaseHold(user,id){return mutate(d=>{const h=find(d,'holds',id);if(!user||h.accountId!==user.id)reject('FORBIDDEN','Prieiga neleidžiama.',403);if(h.state==='held')h.state='released';return {released:true};});},
    confirm(user,input){return mutate(d=>{
      if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);const key=user.id+':'+text(input.idempotencyKey,160),prior=d.idempotency[key],fingerprint=store.hash(JSON.stringify(canonical(input)));
      if(prior){if(prior.fingerprint!==fingerprint)reject('IDEMPOTENCY_CONFLICT','Pakartojimo raktas jau panaudotas kitam veiksmui.',409);return find(d,'bookings',prior.bookingId);}
      const h=find(d,'holds',input.holdId);if(h.accountId!==user.id)reject('FORBIDDEN','Prieiga neleidžiama.',403);
      if(h.state!=='held'||Date.parse(h.expiresAt)<=store.clock())reject('HOLD_EXPIRED','Laiko pasirinkimo galiojimas baigėsi. Pasirinkite iš naujo.',409);
      const s=find(d,'services',h.providerServiceId),c=choose(d,{...h,id:h.slotId||[h.providerServiceId,h.startAt,h.addonIds.join(',')].join('|'),snapshotAt:clock().now},{ignoreHoldId:h.id});
      const client=find(d,'clients',user.id);client.name=text(input.name||client.name,80);client.version++;store.db.prepare('UPDATE accounts SET name=? WHERE id=? AND site_id=?').run(client.name,user.id,store.siteId);
      const b={id:randomId('booking'),organizationId:c.organizationId,clientId:user.id,providerServiceId:s.id,practitionerId:c.practitionerId,resourceId:c.resourceId,locationId:c.locationId,startAt:c.startAt,endAt:c.endAt,phases:c.phases,occupancies:c.occupancies,durationMin:c.durationMin,priceMinor:c.priceMinor,addonIds:c.addonIds,bufferBeforeMin:s.bufferBeforeMin,bufferAfterMin:s.bufferAfterMin,status:'confirmed',currency:'EUR',timezone:'Europe/Vilnius',version:1,createdAt:clock().now,serviceSnapshot:{label:s.label,practitionerName:find(d,'practitioners',c.practitionerId).name,organizationName:find(d,'organizations',c.organizationId).name,location:publicLocation(d,c.locationId),durationMin:c.durationMin,priceMinor:c.priceMinor,addons:option(s,c.addonIds).addons}};
      h.state='confirmed';d.bookings.push(b);d.idempotency[key]={bookingId:b.id,holdId:h.id,fingerprint};outbox(d,b,'confirmation');event(d,'booking-confirmed',b.id);return b;
    });},
    cancelBooking(user,input){return mutate(d=>{const b=ownBooking(d,user,input.scope,input.id);requireWholeVisit(scope(d,user,input.scope),b);if(b.version!==input.version)reject('VERSION_CONFLICT','Vizitas pasikeitė. Atnaujinkite.',409);if(b.status!=='confirmed'||Date.parse(b.startAt)<=store.clock())reject('INVALID_INPUT','Atšaukti galima būsimą patvirtintą vizitą.');b.status='canceled';b.cancelReason=text(input.reason||'Kliento pasirinkimas',300);b.version++;outbox(d,b,'cancellation');event(d,'booking-canceled',b.id);return b;});},
    changeBooking(user,input){return mutate(d=>{const b=ownBooking(d,user,input.scope,input.id);if(b.segments)reject('INVALID_INPUT','Perkelkite visą kelių paslaugų vizitą.');if(b.version!==input.version)reject('VERSION_CONFLICT','Vizitas pasikeitė. Atnaujinkite.',409);if(b.status!=='confirmed'||Date.parse(b.startAt)<=store.clock())reject('INVALID_INPUT','Keisti galima būsimą patvirtintą vizitą.');if(input.candidate.providerServiceId!==b.providerServiceId)reject('INVALID_INPUT','Paslaugos variantas turi sutapti.');const access=scope(d,user,input.scope),c=choose(d,input.candidate,{ignoreBookingId:b.id,internal:true}),s=find(d,'services',b.providerServiceId);if(access.practitionerId&&c.practitionerId!==access.practitionerId)reject('FORBIDDEN','Galima keisti tik savo meistro vizitą.',403);Object.assign(b,{startAt:c.startAt,endAt:c.endAt,phases:c.phases,occupancies:c.occupancies,practitionerId:c.practitionerId,resourceId:c.resourceId,locationId:c.locationId,priceMinor:c.priceMinor,durationMin:c.durationMin,addonIds:c.addonIds,bufferBeforeMin:s.bufferBeforeMin,bufferAfterMin:s.bufferAfterMin,serviceSnapshot:{label:s.label,practitionerName:find(d,'practitioners',c.practitionerId).name,organizationName:find(d,'organizations',c.organizationId).name,location:publicLocation(d,c.locationId),durationMin:c.durationMin,priceMinor:c.priceMinor,addons:option(s,c.addonIds).addons},version:b.version+1});outbox(d,b,'reschedule');event(d,'booking-changed',b.id);return b;});},
    manualVisit(user,input){return mutate(d=>{
      const access=ownOrg(d,user,input.scope?.organizationId,'bookings');const key=user.id+':manual:'+text(input.idempotencyKey,160),fingerprint=store.hash(JSON.stringify(canonical(input))),prior=d.idempotency[key];
      if(prior){if(prior.fingerprint!==fingerprint)reject('IDEMPOTENCY_CONFLICT','Raktas panaudotas kitam vizitui.',409);return find(d,'bookings',prior.bookingId);}
      const c=choose(d,input.candidate,{internal:true});if(c.organizationId!==input.scope.organizationId||access.practitionerId&&c.practitionerId!==access.practitionerId)reject('FORBIDDEN','Kita organizacija arba meistras.',403);const client=find(d,'clients',input.clientId);
      if(![...d.bookings,...d.inquiries,...d.waitlist,...(d.clientLinks||[])].some(b=>b.clientId===client.id&&b.organizationId===c.organizationId))reject('FORBIDDEN','Klientas nepriklauso šiai organizacijai.',403);
      const s=find(d,'services',c.providerServiceId),b={...c,id:randomId('booking'),clientId:client.id,status:'confirmed',version:1,currency:'EUR',timezone:'Europe/Vilnius',bufferBeforeMin:s.bufferBeforeMin,bufferAfterMin:s.bufferAfterMin,createdAt:clock().now,serviceSnapshot:{label:s.label,practitionerName:find(d,'practitioners',c.practitionerId).name,organizationName:find(d,'organizations',c.organizationId).name,location:publicLocation(d,c.locationId),durationMin:c.durationMin,priceMinor:c.priceMinor,addons:option(s,c.addonIds).addons}};delete b.occupiedStart;delete b.occupiedEnd;d.bookings.push(b);d.idempotency[key]={bookingId:b.id,fingerprint};outbox(d,b,'confirmation');event(d,'booking-manual',b.id);return b;
    });},
    edit(user,input){return mutate(d=>{
      const {table,id,values,version}=input,s=scope(d,user,input.scope),e=find(d,table,id);if(s.role==='professional'){requireCapability(s,{services:'offers',schedules:'schedule',resources:'resources',practitioners:'team',inquiries:'bookings',waitlist:'bookings',clients:'clients'}[table]||'access');if(s.practitionerId&&e.practitionerId!==s.practitionerId)reject('FORBIDDEN','Kito meistro įrašas.',403);}
      if(table==='waitlist'&&e.criteria)reject('INVALID_INPUT','Struktūruotą pageidavimą užbaikite laukiančiųjų sąraše.');
      if(table==='reports')reject('INVALID_INPUT','Pranešimo sprendimą išsaugokite per jo peržiūrą su priežastimi.');
      const fields={services:['label','durationMin','priceMinor','bufferBeforeMin','bufferAfterMin','addons','practitionerId','resourceId','active'],schedules:['startMin','endMin','breakStartMin','breakEndMin','closedDay','closedDate','weekdays'],resources:['label','active'],practitioners:['name','role','active'],inquiries:['status'],waitlist:['state'],clients:['name'],reports:['status'],organizations:['approved','profileState']};
      if(!fields[table]||!values||Object.keys(values).some(k=>!fields[table].includes(k)))reject('INVALID_INPUT','Neleistinas laukas.');
      if(s.role==='customer'&&(table!=='clients'||id!==user.id))reject('FORBIDDEN','Prieiga neleidžiama.',403);
      if(s.role==='professional'&&(e.organizationId!==s.organizationId||['clients','reports','organizations'].includes(table)))reject('FORBIDDEN','Prieiga neleidžiama.',403);
      if(s.role==='operator'&&!['reports','organizations'].includes(table))reject('FORBIDDEN','Prieiga neleidžiama.',403);
      if(version!==undefined&&e.version!==version)reject('VERSION_CONFLICT','Įrašas pasikeitė. Atnaujinkite.',409);
      for(const k of ['name','label'])if(k in values)text(values[k],100);
      for(const k of ['durationMin','priceMinor','bufferBeforeMin','bufferAfterMin','startMin','endMin','breakStartMin','breakEndMin'])if(k in values)number(values[k],k==='durationMin'?15:0,k==='priceMinor'?100000:k==='durationMin'?480:k.startsWith('buffer')?120:1439);
      for(const k of ['active','approved'])if(k in values&&typeof values[k]!=='boolean')reject('INVALID_INPUT','Netinkama būsena.');
      const enums={inquiries:{status:['new','qualified','closed']},waitlist:{state:['waiting','offered','closed']},reports:{status:['new','resolved','hidden']},practitioners:{role:['staff','manager','owner']},organizations:{profileState:['draft','pending','returned','approved']}};
      for(const [key,allowed] of Object.entries(enums[table]||{}))if(key in values&&!allowed.includes(values[key]))reject('INVALID_INPUT','Nežinoma įrašo būsena.');
      if(values.active===false&&['services','resources','practitioners'].includes(table)&&d.bookings.some(b=>b.status==='confirmed'&&Date.parse(b.endAt)>store.clock()&&bookingUses(b,{services:'providerServiceId',resources:'resourceId',practitioners:'practitionerId'}[table],id)))reject('SCHEDULE_CONFLICT','Pirmiau perkelkite arba atšaukite šiam įrašui priskirtus būsimus vizitus.',409);
      if(table==='services'){
        if(e.staffOptions||e.offerId)reject('INVALID_INPUT','Šį variantą redaguokite pasiūlymo juodraštyje.');
        for(const [field,t] of [['practitionerId','practitioners'],['resourceId','resources']])if(field in values&&find(d,t,values[field]).organizationId!==e.organizationId)reject('FORBIDDEN','Kita organizacija.',403);
        if(values.addons&&(!Array.isArray(values.addons)||values.addons.length>12))reject('INVALID_INPUT','Netinkami priedai.');
        for(const a of values.addons||[]){text(a.id,100);text(a.label,100);number(a.durationMin,0,240);number(a.priceMinor,0,100000);}if(values.addons&&new Set(values.addons.map(a=>a.id)).size!==values.addons.length)reject('INVALID_INPUT','Priedai dubliuojasi.');
      }
      if(table==='schedules'){
        const p=find(d,'practitioners',e.practitionerId),place=e.locationId||p.locationId||find(d,'organizations',p.organizationId).locationId,n={...e,...values};if(n.startMin>=n.endMin||n.breakStartMin>=n.breakEndMin||n.breakStartMin<n.startMin||n.breakEndMin>n.endMin)reject('INVALID_INPUT','Patikrinkite pamainos ir pertraukos intervalus.');
        if(n.weekdays&&(!Array.isArray(n.weekdays)||n.weekdays.some(w=>!['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].includes(w))))reject('INVALID_INPUT','Netinkamos savaitės dienos.');
        if('closedDay' in values){if(values.closedDay!==null)number(values.closedDay,0,30);n.closedDate=values.closedDay===null?null:new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(localInstant(clock(),values.closedDay,720)));values.closedDate=n.closedDate;}
        if('closedDate' in values){if(values.closedDate!==null&&(!/^\d{4}-\d{2}-\d{2}$/.test(values.closedDate)||!Number.isFinite(Date.parse(values.closedDate+'T12:00:00Z'))||new Date(values.closedDate+'T12:00:00Z').toISOString().slice(0,10)!==values.closedDate))reject('INVALID_INPUT','Netinkama uždarymo data.');n.closedDate=values.closedDate;values.closedDay=null;}
        for(const other of d.schedules.filter(x=>x.id!==e.id&&x.practitionerId===p.id&&(x.locationId||p.locationId)!==place)){if((n.weekdays||[]).some(day=>(other.weekdays||[]).includes(day))&&n.startMin<other.endMin+(p.transferBufferMin||0)&&other.startMin<n.endMin+(p.transferBufferMin||0))reject('SCHEDULE_CONFLICT','Meistro pamainos skirtingose vietose turi palikti persikėlimo laiką.',409);}
        const future=d.bookings.filter(b=>b.status==='confirmed'&&Date.parse(b.endAt)>store.clock()).flatMap(b=>visitSegments(b)).filter(b=>b.practitionerId===e.practitionerId&&bookingPlace(d,b)===place);
        for(const b of future){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Vilnius',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(b.startAt)).split(':').map(Number),lo=p[0]*60+p[1]-b.bufferBeforeMin,hi=p[0]*60+p[1]+b.durationMin+b.bufferAfterMin,day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(b.startAt)),weekday=new Date(b.startAt).toLocaleDateString('en-US',{timeZone:'Europe/Vilnius',weekday:'short'});if(lo<n.startMin||hi>n.endMin||occupiedRanges(b).filter(x=>x.practitionerId===e.practitionerId).some(x=>{const minute=at=>{const v=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Vilnius',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(at)).split(':').map(Number);return v[0]*60+v[1];};return minute(x.startAt)<n.breakEndMin&&minute(x.endAt)>n.breakStartMin;})||n.closedDate===day||n.weekdays&&!n.weekdays.includes(weekday))reject('SCHEDULE_CONFLICT','Grafiko pakeitimas paslėptų esamą vizitą. Pirmiau perkelkite jį.',409);}
      }
      if(table==='organizations'&&values.approved&&!d.services.some(v=>v.organizationId===e.id&&v.active))reject('INVALID_INPUT','Profilis neturi aktyvių paslaugų.');
      Object.assign(e,copy(values),{version:(e.version||0)+1});if(table==='clients')store.db.prepare('UPDATE accounts SET name=? WHERE id=? AND site_id=?').run(e.name,user.id,store.siteId);event(d,'edit-'+table,id);return e;
    });},
    submitRevision(user,input){return mutate(d=>{const s=scope(d,user,input.scope);if(s.role!=='professional')reject('FORBIDDEN','Prieiga neleidžiama.',403);requireCapability(s,'profile');const o=find(d,'organizations',s.organizationId);if(input.version!==undefined&&input.version!==o.version)reject('VERSION_CONFLICT','Profilio juodraštis pasikeitė. Atnaujinkite.',409);requireProfileService(d,o.id);const kind=input.kind??o.kind,city=input.city??o.city;if(!['solo','salon'].includes(kind)||!cities.includes(city))reject('INVALID_INPUT','Pasirinkite miestą ir veiklos tipą.');if(find(d,'locations',o.locationId).published&&city!==publicLocation(d,o.locationId)?.city)reject('PLACE_EDITOR_REQUIRED','Patvirtintos veiklos vietos miestą keiskite Vietų skiltyje.');const revision={id:randomId('revision'),organizationId:o.id,name:text(input.name),bio:text(input.bio,600),kind,city,state:'pending',gallery:[...(o.draftGallery||o.gallery)],avatarImageId:o.draftAvatarImageId===undefined?o.avatarImageId:o.draftAvatarImageId,galleryEntries:copy(o.draftGalleryEntries||o.galleryEntries||(o.draftGallery||o.gallery||[]).filter(id=>d.media.some(a=>a.id===id&&a.usage==='gallery')).map(mediaId=>({mediaId,providerServiceId:null,caption:''}))),staffPortraits:copy(o.draftStaffPortraits||o.staffPortraits||[]),createdAt:clock().now};d.revisions.push(revision);o.profileState='pending';return revision;});},
    moderate(user,input){return mutate(d=>{scope(d,user,{role:'operator'});const r=find(d,'revisions',input.id);if(r.state!=='pending')reject('VERSION_CONFLICT','Paraiška jau peržiūrėta.',409);if(!['approved','returned'].includes(input.state))reject('INVALID_INPUT','Netinkamas sprendimas.');if(input.state==='returned')text(input.reason,500);r.state=input.state;r.reason=String(input.reason||'').slice(0,500);const o=find(d,'organizations',r.organizationId);if(input.state==='approved'&&(r.galleryEntries?.length||r.staffPortraits?.length))validateGallery(d,o.id,r);if(input.state==='approved'&&[...(r.gallery||[]),r.avatarImageId].filter(Boolean).some(id=>d.media.some(a=>a.id===id&&a.moderationState==='restricted')))reject('MEDIA_RESTRICTED','Versijoje yra apribotas vaizdas. Pašalinkite jį iš pateikiamos galerijos.');if(input.state==='approved'&&r.city!==o.city&&d.bookings.some(b=>bookingPlace(d,b)===o.locationId&&b.status==='confirmed'&&Date.parse(b.endAt)>store.clock()))reject('LOCATION_CONFLICT','Pirmiau perkelkite arba atšaukite šios vietos būsimus vizitus.',409);o.profileState=input.state;if(input.state==='approved'){o.name=r.name;o.bio=r.bio;o.kind=r.kind;if(r.city){o.city=r.city;find(d,'locations',o.locationId).city=r.city;}if(r.gallery)o.gallery=r.gallery;if(r.avatarImageId!==undefined)o.avatarImageId=r.avatarImageId||null;if(r.galleryEntries)o.galleryEntries=copy(r.galleryEntries);if(r.staffPortraits)o.staffPortraits=copy(r.staffPortraits);o.approved=true;o.version++;}return r;});},
    createWaitlist(user,input){return mutate(d=>{
      if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);const idempotencyKey=user.id+':waitlist:'+text(input.idempotencyKey,160),fingerprint=store.hash(JSON.stringify(canonical(input))),prior=d.idempotency[idempotencyKey];
      if(prior){if(prior.fingerprint!==fingerprint)reject('IDEMPOTENCY_CONFLICT','Raktas panaudotas kitam pageidavimui.',409);return find(d,'waitlist',prior.waitlistId);}
      const values=validateWaitlist(d,input,store.clock());if((store.clientRecords?store.clientRecords('waitlist',user.id):d.waitlist).filter(w=>w.clientId===user.id&&!['closed','expired'].includes(w.state)).length>=20)reject('LIMIT','Galite turėti iki 20 aktyvių pageidavimų.');
      const item={id:randomId('waitlist'),organizationId:input.organizationId,providerServiceId:input.providerServiceId,clientId:user.id,note:input.note?text(input.note,500):'',status:'new',state:'waiting',version:1,createdAt:clock().now,deliveryStatus:'stored',...values};d.waitlist.push(item);d.idempotency[idempotencyKey]={waitlistId:item.id,fingerprint};event(d,'waitlist-created',item.id);return item;
    });},
    acceptWaitlist(user,input){return mutate(d=>{const result=claimWaitlist(d,user,input,store.clock());event(d,'waitlist-selected',input.id);return result;});},
    closeWaitlist(user,input){return mutate(d=>{const item=find(d,'waitlist',input.id),access=scope(d,user,input.scope);if(access.role==='customer'?item.clientId!==user.id:access.role!=='professional'||access.organizationId!==item.organizationId)reject('FORBIDDEN','Šio pageidavimo prieiga neleidžiama.',403);if(access.role==='professional')requireCapability(access,'clients');if(item.version!==input.version)reject('VERSION_CONFLICT','Pageidavimas pasikeitė. Atnaujinkite.',409);if(item.holdId){const h=d.holds.find(h=>h.id===item.holdId);if(h?.state==='held')h.state='released';}item.state='closed';item.closeReason='withdrawn';item.version++;event(d,'waitlist-closed',item.id);return item;});},
    createInquiry(user,input){return mutate(d=>{if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);const s=find(d,'services',input.providerServiceId);if(!s.active||!serviceEligible(d,s,store.clock())||!find(d,'organizations',s.organizationId).approved||s.organizationId!==input.organizationId)reject('NOT_FOUND','Paslauga nerasta.',404);const item={id:randomId(input.waitlist?'waitlist':'inquiry'),organizationId:s.organizationId,providerServiceId:s.id,clientId:user.id,note:text(input.note,500),kind:s.bookingMode==='consultation'?'consultation':'inquiry',status:'new',state:'waiting',createdAt:clock().now,deliveryStatus:'stored'};d[input.waitlist?'waitlist':'inquiries'].push(item);return item;});},
    favorite(user,input){return mutate(d=>{if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);const c=find(d,'clients',user.id),o=favoriteOrganization?favoriteOrganization(input.organizationId):find(d,'organizations',input.organizationId);if(!o||o.id!==input.organizationId||input.saved&&!o.approved)reject('NOT_FOUND','Profilis nerastas.',404);if(typeof input.saved!=='boolean')reject('INVALID_INPUT','Netinkamas pasirinkimas.');c.favoriteIds=[...(c.favoriteIds||[]).filter(id=>id!==o.id),...(input.saved?[o.id]:[])];return c.favoriteIds;});},
    completeBooking(user,input){return mutate(d=>{const s=scope(d,user,input.scope);if(s.role!=='professional')reject('FORBIDDEN','Vizitą gali užbaigti jo teikėjas.',403);const b=ownBooking(d,user,input.scope,input.id);requireWholeVisit(s,b);if(b.version!==input.version)reject('VERSION_CONFLICT','Vizitas pasikeitė.',409);if(b.status!=='confirmed'||Date.parse(b.endAt)>store.clock())reject('INVALID_INPUT','Užbaigti galima tik pasibaigusį patvirtintą vizitą.');b.status='completed';b.version++;event(d,'booking-completed',b.id);return b;});},
    retryOutbox(user,input){return store.transaction(()=>{if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);const m=store.db.prepare('SELECT * FROM mail_outbox WHERE id=? AND site_id=? AND booking_id IS NOT NULL').get(input.id,store.siteId);if(!m)reject('NOT_FOUND','Pranešimas nerastas.',404);const d=store.readOrganization?store.readOrganization(m.organization_id,[user.id]):store.read(),s=scope(d,user,input.scope);if(s.role==='customer'||s.role==='professional'&&m.organization_id!==s.organizationId)reject('FORBIDDEN','Prieiga neleidžiama.',403);if(s.role==='professional'&&s.practitionerId)ownBooking(d,user,input.scope,m.booking_id);store.assertOrganizationWritable?.(m.organization_id);if(store.retryMail)return store.retryMail(m);store.db.prepare("UPDATE mail_outbox SET attempts=attempts+1 WHERE id=? AND site_id=?").run(m.id,store.siteId);return {id:m.id,state:m.state,attempts:m.attempts+1};});},
    message(user,input){return mutate(d=>{const b=ownBooking(d,user,input.scope,input.bookingId),s=scope(d,user,input.scope),m={id:randomId('message'),organizationId:b.organizationId,clientId:b.clientId,bookingId:b.id,sender:s.role,text:text(input.text,600),createdAt:clock().now,deliveryStatus:'stored'};d.messages.push(m);return m;});},
    review(user,input){return mutate(d=>{const b=ownBooking(d,user,{role:'customer'},input.bookingId);if(b.status!=='completed')reject('FORBIDDEN','Atsiliepimas galimas tik po atlikto vizito.',403);if(d.reviews.some(r=>r.bookingId===b.id))reject('ALREADY_REVIEWED','Vizitas jau įvertintas.',409);const r={id:randomId('review'),bookingId:b.id,organizationId:b.organizationId,clientId:user.id,rating:number(input.rating,1,5),text:text(input.text,600),createdAt:clock().now,approved:false};d.reviews.push(r);return r;});},
    moderateReview(user,input){return mutate(d=>{
      scope(d,user,{role:'operator'});const r=find(d,'reviews',input.id),current=r.state||(r.approved?'approved':'pending');
      if(input.version!==undefined&&input.version!==(r.version||0))reject('VERSION_CONFLICT','Atsiliepimas pasikeitė.',409);
      if(current!=='pending')reject('VERSION_CONFLICT','Atsiliepimas jau peržiūrėtas.',409);
      if(!['approved','rejected'].includes(input.state))reject('INVALID_INPUT','Pasirinkite peržiūros sprendimą.');
      const reason=input.state==='rejected'?text(input.reason,500):String(input.reason||'').trim().slice(0,500);
      const b=find(d,'bookings',r.bookingId);if(b.status!=='completed'||b.organizationId!==r.organizationId||b.clientId!==r.clientId)reject('INVALID_INPUT','Atsiliepimas nesusietas su jo autoriaus atliktu vizitu.');number(r.rating,1,5);text(r.text,600);
      Object.assign(r,{state:input.state,approved:input.state==='approved',reason,moderatedAt:clock().now,moderatedBy:user.id,version:(r.version||0)+1});r.actions||=[];r.actions.push({previous:current,state:r.state,reason,actorId:user.id,at:clock().now});event(d,'review-'+input.state,r.id);return r;
    });},
    preferences(user,input){return mutate(d=>{if(!user)reject('UNAUTHENTICATED','Prisijunkite.',401);if(typeof input.service!=='boolean'||typeof input.marketing!=='boolean'||input.reminderLeadMin!==undefined&&!REMINDER_LEADS.includes(input.reminderLeadMin))reject('INVALID_INPUT','Netinkami pasirinkimai.');const old=d.preferences.find(p=>p.clientId===user.id),value={id:user.id+'-preferences',clientId:user.id,service:input.service,marketing:input.marketing,reminderLeadMin:input.reminderLeadMin??old?.reminderLeadMin??1440,updatedAt:clock().now};if(old)Object.assign(old,value);else d.preferences.push(value);return value;});},
    metrics(user,{excludeOrganizationIds=[]}={}){scope({},user,{role:'operator'});store.rowStats?.();const ids=[...new Set(excludeOrganizationIds)],where=ids.length?' AND (organization_id IS NULL OR organization_id NOT IN ('+ids.map(()=>'?').join(',')+'))':'',count=(collection,condition='')=>store.db.prepare('SELECT COUNT(*) AS n FROM state_rows WHERE site_id=? AND collection=?'+where+condition).get(store.siteId,collection,...ids).n;return {events:count('events'),realVisits:count('bookings'," AND status='completed'"),realInquiries:count('inquiries'),demand:'TESTING_NOT_MEASURED'};},
  };Object.assign(api,createLocationApi({store,mutate,ownOrg,scope,event,clock}));Object.assign(api,createOfferApi({store,mutate,ownOrg:(d,u,org)=>ownOrg(d,u,org,'offers'),scope,event,clock}));
  Object.assign(api,createVisitApi({store,mutate,publicRead,calendarRead,scope,ownBooking,event,outbox,clock}));
  Object.assign(api,createCustomerTools({store,mutate,ownOrg,ownBooking,scope,event,clock}));
  Object.assign(api,createOperations({store,mutate,ownOrg,event,clock}));
  Object.assign(api,createModeration({store,mutate,scope,event,clock}));
  Object.assign(api,createProfileTools({mutate,ownOrg,event}));
  // Internal alarm/control-plane only; absent from the browser RPC dispatcher.
  api.runAutomation=()=>{
    if(!store.readOrganization)return mutate(()=>({processedAt:clock().now}));
    const organizations=readFields(['organizations']).organizations;
    if(!organizations.length)return mutate(()=>({processedAt:clock().now}));
    for(const o of organizations){if(store.organizationWritable&&!store.organizationWritable(o.id))continue;store.transaction(()=>{const view=store.readOrganization(o.id);if(!view.organizationPatchReady){mutate(()=>null);return;}if(organizationMutation)throw Error('Nested organization automation');organizationMutation=view;try{mutate(()=>null);}finally{organizationMutation=null;}});}
    return {processedAt:clock().now};
  };
  api.search=(filters={})=>{
    const point=filters.near?validateCoordinates(filters.near.latitude,filters.near.longitude):null;
    if(filters.sort==='distance'&&point?.latitude==null)reject('LOCATION_REQUIRED','Atstumui rikiuoti reikia jūsų pasirinktos vietos.');
    const d=publicRead(['reviews']),calendars=new Map(),reviews=new Map();
    for(const r of d.reviews)if(r.approved){const a=reviews.get(r.organizationId)||{count:0,sum:0};a.count++;a.sum+=r.rating;reviews.set(r.organizationId,a);}
    const rows=catalogRows(d,filters).flatMap(s=>{
      const quotes=matchingQuotes(s,filters);if(!quotes.length)return [];
      const selected={...s,priceMinor:Math.min(...quotes.map(q=>q.priceMinor)),priceToMinor:Math.max(...quotes.map(q=>q.priceMinor)),durationMin:Math.min(...quotes.map(q=>q.durationMin)),durationToMin:Math.max(...quotes.map(q=>q.durationMin)),...(s.staffOptions?{staffOptions:quotes}:{}),...(quotes.length===1?{practitionerName:quotes[0].name}:{} )};
      let a;try{
        if(!calendars.has(s.organizationId))calendars.set(s.organizationId,calendarRead(d,s.organizationId));
        a=slots(calendars.get(s.organizationId),{providerServiceId:s.id,addons:filters.addons||[],practitionerId:filters.practitionerId,dayOffset:filters.dayOffset??1,dateKey:filters.dateKey,from:filters.from??540,to:filters.to??1200});
      }catch(e){if(e.code!=='ADDON_SELECTION_REQUIRED')throw e;a={state:'needs-options',slots:[],message:e.message};}
      a={...a,slots:a.slots.filter(c=>quotes.some(q=>q.practitionerId===c.practitionerId))};
      const review=reviews.get(s.organizationId),reviewSummary=review?{count:review.count,rating:Math.round(review.sum/review.count*10)/10}:null;
      return [{...selected,reviewSummary,distanceKm:distanceKm(point,s.location),availability:a,nextAt:a.slots[0]?.startAt||null}];
    }).filter(s=>filters.anyTime||s.bookingMode&&s.bookingMode!=='instant'||s.availability.slots.length||s.availability.state==='needs-options');
    rows.sort(filters.sort==='distance'?(a,b)=>(a.distanceKm??Infinity)-(b.distanceKm??Infinity)||a.id.localeCompare(b.id):filters.sort==='price'?(a,b)=>a.priceMinor-b.priceMinor||a.id.localeCompare(b.id):filters.sort==='name'?(a,b)=>a.organizationName.localeCompare(b.organizationName,'lt')||a.id.localeCompare(b.id):(a,b)=>(a.nextAt||'z').localeCompare(b.nextAt||'z')||a.id.localeCompare(b.id));return rows;
  };
  api.searchResults=(filters={})=>groupSearchRows(api.search(filters),filters);
  if(store.readOrganization&&store.clientRecords){
    const original=api.createOrganization;api.createOrganization=(user,input)=>{
      if(!user)return original(user,input);
      return store.transaction(()=>{if(organizationMutation||creatingOrganizationId)throw Error('Nested organization creation');const id=randomId('provider'),view=store.readOrganization(id,[user.id]);if(!view.organizationPatchReady)return original(user,input);organizationMutation=view;creatingOrganizationId=id;try{return original(user,input);}finally{organizationMutation=null;creatingOrganizationId=null;}});
    };
  }
  if(store.readOrganization&&store.ensureClient){
    const original=api.createClient;api.createClient=(user,input)=>{
      if(!user)return original(user,input);
      return store.transaction(()=>{
        const view=store.readOrganization(input?.organizationId,[user.id]);if(!view.organizationPatchReady||!Array.isArray(view.clientLinks))return original(user,input);
        ownOrg(view,user,input.organizationId,'clients');if(view.clientLinks.length>=1000)reject('LIMIT','Klientų sąrašo limitas pasiektas.');const {email,name}=clientInput(input);
        let account=store.db.prepare('SELECT id FROM accounts WHERE site_id=? AND email=?').get(store.siteId,email);
        if(!account){account={id:randomId('account')};store.db.prepare('INSERT INTO accounts(id,site_id,email,name,created_at) VALUES(?,?,?,?,?)').run(account.id,store.siteId,email,name,store.clock());}
        store.ensureClient(account.id);
        if(organizationMutation||clientMutation)throw Error('Nested client creation');organizationMutation=store.readOrganization(input.organizationId,[user.id,account.id]);
        try{return original(user,input);}finally{organizationMutation=null;}
      });
    };
  }
  if(store.readCatalogue&&store.writeCatalogue){const original=api.changeTaxonomy;api.changeTaxonomy=(user,input)=>store.transaction(()=>{scope({},user,{role:'operator'});if(catalogueMutation||organizationMutation||clientMutation)throw Error('Nested catalogue mutation');catalogueMutation=store.readCatalogue();try{return original(user,input);}finally{catalogueMutation=null;}});}
  if(store.readOrganization&&store.recordById){
    const record=(table,id)=>{const value=store.recordById(table,id);if(!value)reject('NOT_FOUND','Įrašas nerastas.',404);return value;};
    const confirmation=(i,user,multi=false)=>{const h=store.recordById('holds',i?.holdId);if(h)return h;const prior=store.recordById('idempotency',user.id+':'+(multi?'visit:':'')+i?.idempotencyKey);return prior?.bookingId?record('bookings',prior.bookingId):record('holds',i?.holdId);};
    const routes={hold:i=>record('services',i?.providerServiceId),holdVisit:i=>record('services',i?.items?.[0]?.providerServiceId),confirm:(i,u)=>confirmation(i,u),confirmVisit:(i,u)=>confirmation(i,u,true),releaseHold:i=>record('holds',i),cancelBooking:i=>record('bookings',i?.id),changeBooking:i=>record('bookings',i?.id),changeVisit:i=>record('bookings',i?.id),completeBooking:i=>record('bookings',i?.id),message:i=>record('bookings',i?.bookingId),review:i=>record('bookings',i?.bookingId),manualVisit:i=>record('services',i?.candidate?.providerServiceId),acceptWaitlist:i=>record('waitlist',i?.id),closeWaitlist:i=>record('waitlist',i?.id),createInquiry:i=>record('services',i?.providerServiceId)};
    const organization=i=>record('organizations',i?.organizationId||i?.scope?.organizationId);
    Object.assign(routes,{migrateOrganizationCatalogue:organization,grantMembership:organization,revokeMembership:i=>record('memberships',i?.id),moderateProcedure:i=>record('procedureRequests',i?.id),assessQualification:organization,attachMedia:organization,createStaff:organization,createResource:organization,createService:organization,createBusyBlock:organization,releaseBusyBlock:i=>record('busyBlocks',i?.id),selectProcedures:organization,saveOffer:i=>record('offers',i?.id),submitOffer:i=>record('offers',i?.id),moderateOffer:i=>record('offers',i?.id),archiveOffer:i=>record('offers',i?.id),saveMenuGroup:i=>i?.id?record('menuGroups',i.id):organization(i),requestProcedure:organization,saveLocation:i=>i?.id?record('locations',i.id):organization(i),submitLocation:i=>record('locations',i?.id),moderateLocation:i=>record('locations',i?.id),setLocationActive:i=>record('locations',i?.id),assignStaffLocations:i=>record('practitioners',i?.id),saveGallery:organization,saveBookingRules:organization,saveClientCard:organization,submitRevision:organization,moderate:i=>record('revisions',i?.id),moderateReview:i=>record('reviews',i?.id),createWaitlist:i=>record('services',i?.providerServiceId),bulkOfferPrices:i=>{const org=organization(i);for(const row of i?.updates||[]){const offer=store.recordById('offers',row.offerId);if(offer&&offer.organizationId!==org.id)reject('FORBIDDEN','Kita organizacija.',403);}return {...org,organizationId:org.id};},edit:i=>['organizations','locations','practitioners','resources','services','schedules','busyBlocks'].includes(i?.table)?record(i.table,i.id):null});
    for(const [name,resolve] of Object.entries(routes)){const original=api[name];api[name]=(user,input)=>{
      if(!user)return original(user,input);if(['migrateOrganizationCatalogue','moderate','moderateReview','moderateOffer','moderateLocation','moderateProcedure','assessQualification'].includes(name)&&!user.operator)reject('FORBIDDEN','Prieiga neleidžiama.',403);
      return store.transaction(()=>{const target=resolve(input,user);if(!target)return original(user,input);const organizationId=target.organizationId||target.id;store.assertOrganizationWritable?.(organizationId);if(name==='assessQualification'){const location=store.recordById('locations',input?.locationId);if(location&&location.organizationId!==organizationId)reject('FORBIDDEN','Kita vieta.',403);}if(['createBusyBlock','createService','grantMembership'].includes(name)){for(const [field,table] of [['practitionerId','practitioners'],['resourceId','resources']]){const ref=store.recordById(table,input?.[field]);if(ref&&ref.organizationId!==organizationId)reject('FORBIDDEN','Įrašas priklauso kitai organizacijai.',403);}}if(organizationMutation)throw Error('Nested organization mutation');const view=store.readOrganization(organizationId,[user.id,input?.clientId].filter(Boolean));organizationMutation=view.organizationPatchReady&&(name!=='saveClientCard'||Array.isArray(view.clientCards))&&(!['grantMembership','revokeMembership'].includes(name)||Array.isArray(view.accessChanges))?view:null;try{return original(user,input);}finally{organizationMutation=null;}});
    };}
  }
  if(store.readClient&&store.writeClient){
    for(const name of ['preferences','favorite','requestErasure','withdrawErasure','reviewErasure']){const original=api[name];api[name]=(user,input)=>{
      if(!user)return original(user,input);if(name==='reviewErasure'&&!user.operator)reject('FORBIDDEN','Prieiga neleidžiama.',403);
      return store.transaction(()=>{let accountId=user.id;if(['withdrawErasure','reviewErasure'].includes(name)){const request=store.recordById('dataRequests',input?.id);if(!request)reject('NOT_FOUND','Įrašas nerastas.',404);if(name==='withdrawErasure'&&request.clientId!==user.id)reject('FORBIDDEN','Prašymas nepriklauso jums.',403);accountId=request.clientId;}
        if(clientMutation||organizationMutation)throw Error('Nested client mutation');const view=store.readClient(accountId,name==='favorite'?[input?.organizationId]:[]);clientMutation=view.clientPatchReady&&(!['requestErasure','withdrawErasure','reviewErasure'].includes(name)||Array.isArray(view.dataRequests))?view:null;reconcileClientPreferences=name==='preferences'&&!!clientMutation;try{return original(user,input);}finally{clientMutation=null;reconcileClientPreferences=false;}});
    };}
  }
  return api;
}
