import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
const fail=(expected,fn)=>assert.throws(fn,e=>e.code===expected);
function fixture(){
 const store=openStore({filename:':memory:',clock:()=>Date.parse('2026-10-07T06:00:00Z'),secret:'isolated-gallery-'.repeat(3)}),api=createPlatform(store),auth=createAuth(store),login=email=>{const s=auth.session(null),c=auth.start(s,email,'127.0.0.1');return auth.verify(s,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user;},owner=login('gallery-owner@example.com'),other=login('gallery-other@example.com'),operator={...owner,operator:true},org=api.createOrganization(owner,{name:'Gallery fixture',bio:'Isolated service-linked media.',kind:'salon',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),p=w.practitioners[0],service=api.createService(owner,{organizationId:org.id,practitionerId:p.id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Gallery manicure',durationMin:60,priceMinor:2500}),revision=()=>api.submitRevision(owner,{scope,name:org.name,bio:org.bio});api.moderate(operator,{id:revision().id,state:'approved'});
 const asset=(id,usage)=>{api.attachMedia(owner,{id,organizationId:org.id,usage,alt:'Isolated '+id,rights:'Original isolated test fixture',variants:[],source:{original:'private-'+id},rightsConfirmedAt:'2026-10-07T06:00:00.000Z',rightsConfirmedBy:owner.id});return id;};return {store,api,owner,other,operator,org,scope,p,service,revision,asset,version:()=>api.workspace(owner,scope).organizations[0].version,close:()=>store.close()};
}
test('Service-linked gallery order, caption and staff portrait are reviewed snapshots; stale/cross-organization/invalid associations cannot publish',()=>{
 const f=fixture();try{
  const a=f.asset('asset-gallery-first','gallery'),z=f.asset('asset-gallery-second','gallery'),portrait=f.asset('asset-gallery-portrait','portrait'),value={organizationId:f.org.id,version:f.version(),galleryEntries:[{mediaId:z,providerServiceId:f.service.id,caption:'First selected work'},{mediaId:a,providerServiceId:null,caption:'Environment'}],avatarImageId:portrait,staffPortraits:[{practitionerId:f.p.id,mediaId:portrait}]};fail('FORBIDDEN',()=>f.api.saveGallery(f.other,value));fail('INVALID_INPUT',()=>f.api.saveGallery(f.owner,{...value,galleryEntries:[{mediaId:a,providerServiceId:'unrelated-service'}]}));const draft=f.api.saveGallery(f.owner,value);assert.equal(f.api.profile(f.org.id).works.length,0);assert.equal(f.api.profile(f.org.id).practitioners[0].avatarImageId,null);fail('VERSION_CONFLICT',()=>f.api.saveGallery(f.owner,value));fail('VERSION_CONFLICT',()=>f.api.submitRevision(f.owner,{scope:f.scope,version:value.version,name:f.org.name,bio:f.org.bio}));
  const r=f.revision();f.api.saveGallery(f.owner,{...value,version:draft.version,galleryEntries:[{mediaId:a,providerServiceId:null,caption:'Later draft'}],avatarImageId:null,staffPortraits:[]});f.api.moderate(f.operator,{id:r.id,state:'approved'});let publicProfile=f.api.profile(f.org.id);assert.deepEqual(publicProfile.gallery,[z,a]);assert.equal(publicProfile.works[0].serviceLabel,'Gallery manicure');assert.equal(publicProfile.works[0].caption,'First selected work');assert.equal(publicProfile.practitioners[0].avatarImageId,portrait);assert.ok(publicProfile.media.some(x=>x.id===portrait));assert.ok(!JSON.stringify(publicProfile).includes('private-asset')&&!JSON.stringify(publicProfile).includes('rightsConfirmedBy'));
  f.api.grantMembership(f.owner,{organizationId:f.org.id,email:f.other.email,role:'reception',version:0});const reception=f.api.workspace(f.other,f.scope);assert.equal(reception.organizations[0].draftGalleryEntries,undefined);assert.equal(reception.organizations[0].draftStaffPortraits,undefined);assert.ok(!JSON.stringify(reception).includes('Later draft'));assert.ok(reception.media.some(x=>x.id===portrait));assert.ok(!JSON.stringify(reception.media).includes('rightsConfirmedBy'));
  const next=f.revision();f.api.moderate(f.operator,{id:next.id,state:'approved'});publicProfile=f.api.profile(f.org.id);assert.deepEqual(publicProfile.gallery,[a]);assert.equal(publicProfile.avatarImageId,null);assert.equal(publicProfile.practitioners[0].avatarImageId,null);assert.equal(publicProfile.works[0].caption,'Later draft');assert.ok(!publicProfile.media.some(x=>x.id===portrait));
 }finally{f.close();}
});
test('Public weekly hours merge actual active staff windows and breaks, company rules close days; archived service keeps image without a dead booking link',()=>{
 const f=fixture();try{
  const asset=f.asset('asset-gallery-linked','gallery');f.api.saveGallery(f.owner,{organizationId:f.org.id,version:f.version(),galleryEntries:[{mediaId:asset,providerServiceId:f.service.id,caption:'Isolated work'}],staffPortraits:[],avatarImageId:null});f.api.moderate(f.operator,{id:f.revision().id,state:'approved'});let p=f.api.profile(f.org.id);assert.deepEqual(p.weeklyHours[0].days.find(d=>d.day==='Thu').ranges,[[540,780],[840,1200]]);f.api.saveBookingRules(f.owner,{organizationId:f.org.id,version:f.version(),minLeadTimeMin:120,maxAdvanceDays:10,weekdays:['Mon','Tue','Wed','Fri'],closedDates:['2026-10-06','2026-10-09']});p=f.api.profile(f.org.id);assert.deepEqual(p.weeklyHours[0].days.find(d=>d.day==='Thu').ranges,[]);assert.deepEqual(p.bookingPolicy.closedDates,['2026-10-09']);assert.equal(p.bookingPolicy.maxAdvanceDays,10);f.api.edit(f.owner,{scope:f.scope,table:'services',id:f.service.id,version:f.service.version,values:{active:false}});p=f.api.profile(f.org.id);assert.equal(p.works[0].providerServiceId,null);assert.equal(p.works[0].serviceLabel,null);assert.equal(p.works[0].mediaId,asset);
 }finally{f.close();}
});
