import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {openStore} from './store.mjs';
import {createAuth} from './auth.mjs';
import {createPlatform} from './platform.mjs';
import {createOrganizationDirectory,createOrganizationCommand} from './organization-directory.mjs';
import {createOrganizationHandoff,createOrganizationStaging,organizationTransferProof} from './organization-handoff.mjs';
import {createOrganizationCommit,createOrganizationAuthority} from './organization-authority.mjs';
import {createDirectoryCacheIssuer} from './organization-directory-cache.mjs';
import {createRetention} from './retention.mjs';
import {RETENTION_POLICY,monthsBefore} from './retention-policy.mjs';
const secret='isolated-retention-approval-'.repeat(3),version=RETENTION_POLICY.version;
function fixture({target=false}={}){
 let now=Date.parse('2026-10-12T06:00:00Z');const source=openStore({filename:':memory:',secret,clock:()=>now}),auth=createAuth(source),api=createPlatform(source);source.retentionPolicyVersion=version;
 const login=email=>{const s=auth.session(null),c=auth.start(s,email,'fixture');return auth.verify(s,c.challengeId,source.capture(c.challengeId).code,'fixture');};
 const owner=login('retention-owner@example.com').user,clientLogin=login('retention-client@example.com'),client=clientLogin.user,other=login('retention-other@example.com').user,operator={...owner,operator:true};source.db.prepare('UPDATE accounts SET operator=1 WHERE id=?').run(owner.id);
 const org=api.createOrganization(owner,{name:'Retention fixture',bio:'Isolated approved-policy acceptance.',city:'Vilnius',kind:'salon'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),s=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Retention offer',durationMin:30,priceMinor:2200});api.moderate(operator,{id:api.submitRevision(owner,{scope,name:org.name,bio:org.bio}).id,state:'approved'});
 const book=(u,key,offset)=>{const slot=api.availability({providerServiceId:s.id,dayOffset:offset,from:900,to:1200}).slots[0];return api.confirm(u,{holdId:api.hold(u,slot).id,idempotencyKey:key,name:u.id===client.id?'Private client name':'Other preserved client'});};
 const first=book(client,'own',1),foreign=book(other,'foreign',2);api.message(client,{scope:{role:'customer'},bookingId:first.id,text:'PRIVATE erasure message'});api.saveClientCard(owner,{organizationId:org.id,clientId:client.id,version:0,name:'PRIVATE local name',note:'PRIVATE contact note'});
 let targetStore=null,frozen=null,control=null,oldPacket=null,unavailable=false,lostReply=false,seen=[];
 if(target){targetStore=openStore({filename:':memory:',secret,clock:()=>now});targetStore.retentionPolicyVersion=version;const h=createOrganizationHandoff(source);frozen=h.freeze({operatorAccountId:owner.id,organizationId:org.id,epoch:0,requestKey:'retention-transfer'});control={operatorAccountId:owner.id,organizationId:org.id,epoch:frozen.epoch,handoffId:frozen.handoffId};const stage=createOrganizationStaging(targetStore,{targetName:frozen.targetName});let offset=0;for(;;){const p=h.page({...control,offset});oldPacket??=p;stage.accept(p);offset=p.nextOffset;if(p.done)break;}const c=createOrganizationCommit(source),a=createOrganizationAuthority(targetStore,{targetName:frozen.targetName}),r=a.prepare(c.context(control));a.activate(c.seal({...control,targetReceipt:r}));}
 const command=targetStore&&createOrganizationCommand(targetStore,{targetName:frozen.targetName});
 const directory=createOrganizationDirectory(source,{getTarget:targetStore?()=>({executeDirectoryCommand:p=>{if(unavailable)throw Error('Isolated unavailable target');seen.push(p);const r=command.execute(p);if(lostReply&&p.method==='eraseCustomerRecords'){lostReply=false;throw Error('Lost committed erasure reply');}return r;}}):undefined});
 return {source,target:targetStore,auth,api,login,client,other,owner,operator,clientLogin,org,scope,s,first,foreign,directory,seen,control,frozen,oldPacket,at:n=>{now=n;},now:()=>now,outage:n=>{unavailable=n;},lose:()=>{lostReply=true;},close:()=>{source.close();targetStore?.close();}};
}
const counts=(store,table)=>store.db.prepare('SELECT COUNT(*) AS n FROM '+table).get().n;
test('Approved customer erasure requires fresh own email/policy and atomically removes identity, all sessions, notes and unsent mail while keeping another client and anonymous future occupancy',async()=>{
 const f=fixture();try{
  const stale={...f.client,verifiedAt:f.now()-600001};await assert.rejects(f.directory.dispatch('requestErasure',stale,{confirmEmail:f.client.email,policyVersion:version}),e=>e.code==='REAUTH_REQUIRED');
  await assert.rejects(f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.other.email,policyVersion:version}),e=>e.code==='INVALID_INPUT');await assert.rejects(f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.client.email,policyVersion:'draft'}),e=>e.code==='INVALID_INPUT');
  await assert.rejects(f.directory.dispatch('erasurePreview',f.owner,{}),e=>e.code==='PROFESSIONAL_ACCOUNT');const preview=await f.directory.dispatch('erasurePreview',f.client,{});assert.equal(preview.futureBookings[0].id,f.first.id);
  f.source.db.exec('CREATE TABLE IF NOT EXISTS organization_mail_claims(site_id TEXT NOT NULL,mail_id TEXT NOT NULL,lease_token TEXT NOT NULL,message_hash TEXT NOT NULL,PRIMARY KEY(site_id,mail_id))');const ownMail=f.source.db.prepare('SELECT id FROM mail_outbox WHERE account_id=? LIMIT 1').get(f.client.id),otherMail=f.source.db.prepare('SELECT id FROM mail_outbox WHERE account_id=? LIMIT 1').get(f.other.id);for(const m of [ownMail,otherMail])f.source.db.prepare('INSERT INTO organization_mail_claims VALUES(?,?,?,?)').run(f.source.siteId,m.id,'fixture-lease','fixture-hash');
  const otherBefore=f.source.recordById('bookings',f.foreign.id),result=await f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.client.email,policyVersion:version});assert.equal(result.state,'completed');assert.equal(result.signInRevoked,true);assert.equal(f.source.db.prepare('SELECT mail_id FROM organization_mail_claims WHERE mail_id=?').get(ownMail.id),undefined);assert.ok(f.source.db.prepare('SELECT mail_id FROM organization_mail_claims WHERE mail_id=?').get(otherMail.id));assert.equal((await f.directory.dispatch('erasureStatus',null,{receiptToken:preview.receiptToken})).id,result.id);await assert.rejects(f.directory.dispatch('erasureStatus',null,{receiptToken:'A'.repeat(43)}),e=>e.code==='NOT_FOUND');
  assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.client.id),undefined);assert.equal(f.auth.account(f.clientLogin.session),null);assert.equal(f.source.clientRecords('messages',f.client.id).length,0);assert.equal(f.source.clientRecords('clientCards',f.client.id).length,0);assert.equal(f.source.recordById('clients',f.client.id),null);assert.deepEqual(f.source.recordById('bookings',f.foreign.id),otherBefore);
  const retained=f.source.recordById('bookings',f.first.id);assert.equal(retained.status,'confirmed');assert.equal(retained.startAt,f.first.startAt);assert.notEqual(retained.clientId,f.client.id);assert.equal(f.source.recordById('clients',retained.clientId).erased,true);assert.equal(f.source.db.prepare('SELECT id FROM mail_outbox WHERE account_id=?').get(f.client.id),undefined);
  const raw=JSON.stringify(f.source.read());assert.doesNotMatch(raw,/PRIVATE|Private client name|retention-client@example.com/);assert.equal(counts(f.source,'retention_writer_permits'),0);assert.equal(counts(f.source,'retention_mail_permits'),0);
  f.api.runAutomation();assert.equal(f.source.db.prepare('SELECT id FROM notification_jobs WHERE booking_id=?').get(f.first.id),undefined);
  const renamed=f.login(f.client.email).user;assert.notEqual(renamed.id,f.client.id);assert.equal((await f.directory.dispatch('workspace',renamed,{role:'customer'})).bookings.length,0);
  assert.equal((await f.directory.dispatch('workspace',f.owner,f.scope)).bookings.find(b=>b.id===f.first.id).clientId,retained.clientId);
 }finally{f.close();}
});
test('Approved12/24calendar-month sweep preserves exact boundaries and future visits; inactive closure requires an accepted30day notice and a later login resets it',async()=>{
 const f=fixture();try{
  const r=createRetention(f.source),now=f.now(),cut12=monthsBefore(now,12),cut24=monthsBefore(now,24),d=f.source.read();
  // One finished history record has just crossed24 months; a boundary record
  // and unrelated future occupancy remain. Notes attached to the future visit
  // must survive even when their text itself is old.
  d.bookings.push({...f.first,id:'old-history',status:'completed',startAt:new Date(cut24-3600000).toISOString(),endAt:new Date(cut24-1).toISOString()},{...f.first,id:'boundary-history',status:'completed',startAt:new Date(cut24-3600000).toISOString(),endAt:new Date(cut24).toISOString()});
  d.messages.push({id:'old-note-other',clientId:f.other.id,organizationId:f.org.id,bookingId:f.foreign.id,text:'Future note preserved',createdAt:new Date(cut12-1).toISOString()});d.messages.push({id:'expired-text-no-future',clientId:f.client.id,organizationId:'other-org',text:'Delete expired text',createdAt:new Date(cut12-1).toISOString()},{id:'boundary-text-no-future',clientId:f.client.id,organizationId:'other-org',text:'Keep boundary text',createdAt:new Date(cut12).toISOString()});f.source.write(d);r.sweep();assert.equal(f.source.recordById('messages','expired-text-no-future'),null);assert.ok(f.source.recordById('messages','boundary-text-no-future'));assert.equal(f.source.recordById('bookings','old-history'),null);assert.ok(f.source.recordById('bookings','boundary-history'));assert.equal(f.source.recordById('messages','old-note-other').text,'Future note preserved');
  const inactive=f.login('inactive-retention@example.com');f.auth.account(inactive.session);const start=f.now();f.at(Date.parse('2028-09-12T06:00:00Z'));await f.directory.runRetention();const a=f.source.db.prepare('SELECT * FROM retention_activity WHERE account_id=?').get(inactive.user.id);assert.ok(a.notice_at);const mail=f.source.db.prepare('SELECT * FROM mail_outbox WHERE id=?').get(a.notice_mail_id);assert.equal(mail.type,'account-closure-notice');assert.equal(mail.state,'captured');
  f.at(Date.parse('2028-10-12T06:00:00Z'));await f.directory.runRetention();assert.ok(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(inactive.user.id),'Unaccepted notice cannot close account');
  f.source.db.prepare("UPDATE mail_outbox SET state='accepted',delivered_at=?,finalized_at=? WHERE id=?").run(a.notice_at,a.notice_at,mail.id);await f.directory.runRetention();assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(inactive.user.id),undefined);assert.equal(r.get(inactive.user.id).state,'completed');
  const keep=f.login('keep-retention@example.com');f.auth.account(keep.session);f.at(Date.parse('2030-09-12T06:00:00Z'));await f.directory.runRetention();const n=f.source.db.prepare('SELECT * FROM retention_activity WHERE account_id=?').get(keep.user.id);assert.ok(n.notice_at);const newLogin=f.login(keep.user.email);f.auth.account(newLogin.session);assert.equal(f.source.db.prepare('SELECT notice_at FROM retention_activity WHERE account_id=?').get(keep.user.id).notice_at,0);f.at(Date.parse('2030-10-12T06:00:00Z'));await f.directory.runRetention();assert.ok(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(keep.user.id));assert.ok(start<now+1);
 }finally{f.close();}
});
test('Isolated encrypted checkpoint restore requires the latest journal, replays customer erasure before access, preserves the other customer, and imports no old mail or session',async()=>{
 const f=fixture(),empty=openStore({filename:':memory:',secret,clock:f.now});empty.retentionPolicyVersion=version;
 try{
  const r=createRetention(f.source),b=r.backup(),snapshot=r.decodeBackup(b.id);await f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.client.email,policyVersion:version});const journal=r.journal(),digest=createHash('sha256').update(JSON.stringify(journal)).digest('hex'),recovery=createRetention(empty);
  assert.throws(()=>recovery.restoreEmpty(snapshot,[],digest),e=>e.code==='RESTORE_JOURNAL');assert.equal(counts(empty,'accounts'),0);const result=recovery.restoreEmpty(snapshot,journal,digest);assert.equal(result.tombstonesReplayed,1);assert.equal(counts(empty,'mail_outbox'),0);assert.equal(counts(empty,'sessions'),0);assert.equal(empty.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.client.id),undefined);assert.ok(empty.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.other.id));assert.doesNotMatch(JSON.stringify(empty.read()),/PRIVATE|retention-client@example.com|Private client name/);assert.deepEqual(empty.recordById('bookings',f.foreign.id),f.foreign);assert.throws(()=>recovery.restoreEmpty(snapshot,journal,digest),e=>e.code==='RESTORE_NOT_EMPTY');
 }finally{f.close();empty.close();}
});
test('Active target erasure survives a lost committed reply; tombstones reject pre-erasure signed commands, old transfer copies cannot replay, and source business fences stay closed',async()=>{
 const f=fixture({target:true});try{
  // Capture a legitimately signed command issued before erasure and not yet run.
  const body={schemaVersion:1,siteId:f.source.siteId,organizationId:f.org.id,epoch:f.frozen.epoch,targetName:f.frozen.targetName,nonce:'stale-privacy-cache',expiresAt:f.now()+20000,method:'message',actor:{...f.client,operator:false},input:{bookingId:f.first.id,scope:{role:'customer'},text:'PRIVATE resurrection'},cache:createDirectoryCacheIssuer(f.source).issue(f.client.id)};const stale={...body,proof:organizationTransferProof(f.source,'directory-command',body)};
  f.lose();const result=await f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.client.email,policyVersion:version});assert.equal(result.state,'processing');assert.equal(f.directory.retention.pending().length,1);assert.equal(f.source.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.client.id),undefined);
  const targetReceipt=createRetention(f.target).get(f.client.id);assert.equal(targetReceipt.state,'completed');await f.directory.flushErasures();assert.equal(f.directory.retention.get(f.client.id).state,'completed');assert.equal(f.directory.retention.pending().length,0);
  const command=createOrganizationCommand(f.target,{targetName:f.frozen.targetName});assert.equal(command.execute(stale).error.code,'UNAUTHENTICATED');assert.throws(()=>createOrganizationStaging(f.target,{targetName:f.frozen.targetName}).accept(f.oldPacket),e=>e.code==='RETENTION_RETIRED');assert.throws(()=>createOrganizationCommit(f.source).context(f.control),e=>e.code==='RETENTION_RETIRED');
  for(const store of [f.source,f.target]){assert.doesNotMatch(JSON.stringify(store.read()),/PRIVATE|retention-client@example.com|Private client name/);assert.equal(counts(store,'retention_writer_permits'),0);assert.equal(counts(store,'retention_mail_permits'),0);assert.equal(store.db.prepare('SELECT id FROM accounts WHERE id=?').get(f.client.id),undefined);assert.deepEqual(store.recordById('bookings',f.foreign.id),f.foreign);}
  assert.throws(()=>f.source.db.prepare('UPDATE state_rows SET data=data WHERE organization_id=?').run(f.org.id),/ORGANIZATION_MIGRATING/);assert.equal(counts(f.source,'organization_handoff_rows'),0);assert.equal(counts(f.target,'organization_stage_rows'),0);
  assert.equal((await f.directory.dispatch('workspace',f.owner,f.scope)).bookings.find(b=>b.id===f.first.id).erased,true);
 }finally{f.close();}
});
test('Erasure post-write failure rolls back identity, notes, backup and every permit; encrypted checkpoints reject tampering and expire at exactly30days',async()=>{
 const f=fixture();try{
  const before=f.source.read(),prepare=f.source.db.prepare.bind(f.source.db);f.source.db.prepare=q=>{const s=prepare(q);return q.startsWith('DELETE FROM accounts')?{...s,run:()=>{throw Error('Injected final erasure storage failure');}}:s;};await assert.rejects(f.directory.dispatch('requestErasure',f.client,{confirmEmail:f.client.email,policyVersion:version}),/Injected/);f.source.db.prepare=prepare;assert.deepEqual(f.source.read(),before);assert.ok(f.auth.account(f.clientLogin.session));assert.equal(counts(f.source,'retention_writer_permits'),0);assert.equal(counts(f.source,'retention_mail_permits'),0);assert.equal(counts(f.source,'retention_tombstones'),0);assert.equal(counts(f.source,'retention_backups'),0);
  const r=createRetention(f.source),b=r.backup();assert.equal(r.decodeBackup(b.id).accounts.find(a=>a.id===f.client.id).email,f.client.email);const saved=f.source.db.prepare('SELECT payload FROM retention_backups WHERE id=?').get(b.id).payload;assert.doesNotMatch(saved,/PRIVATE|example.com/);const corrupt=JSON.parse(saved);corrupt.tag='AAAAAAAAAAAAAAAAAAAAAA==';f.source.db.prepare('UPDATE retention_backups SET payload=? WHERE id=?').run(JSON.stringify(corrupt),b.id);assert.throws(()=>r.decodeBackup(b.id));f.source.db.prepare('UPDATE retention_backups SET payload=? WHERE id=?').run(saved,b.id);f.at(f.now()+30*86400000);assert.throws(()=>r.decodeBackup(b.id),e=>e.code==='NOT_FOUND');r.backup();assert.equal(f.source.db.prepare('SELECT id FROM retention_backups WHERE id=?').get(b.id),undefined);
  assert.equal(new Date(monthsBefore(Date.parse('2028-02-29T12:00:00Z'),24)).toISOString(),'2026-02-28T12:00:00.000Z');
 }finally{f.close();}
});
