// Manual site-specific audit decisions; this does not turn automated checks into blanket PASS.
import {readFile,writeFile} from 'node:fs/promises';
import {catalogFromMarkdown,scoreAudit} from '../../SKILLS/niche-site-audit/scripts/score-audit.mjs';
const read=async p=>JSON.parse(await readFile(new URL(p,import.meta.url),'utf8'));
const audit=await read('./PHASE-1-AUDIT.json'),summary=await read('./qa/verification-summary.json');
const decisions={};
function set(id,status,evidence,notes){if(decisions[id])throw Error(`Duplicate ${id}`);decisions[id]={status,evidence:Array.isArray(evidence)?evidence:[evidence],notes};}
const pass=(id,e,n)=>set(id,'PASS',e,n),unv=(id,e,n)=>set(id,'UNVERIFIED',e,n),na=(id,e,n)=>set(id,'NA',e,n);
pass('A1',['BUSINESS.md: first-phase prerequest, no order/booking promise','qa/trust-pages.json: /su-operatoriumi, /apie-projekta visible boundaries'],'Local pilot; no measured demand claim.');
pass('A2',['BUSINESS.md: M1 accepted-qualified-lead payer hypothesis; alternatives, contradiction and unconfirmed fulfillment','qa/tool-interaction.json; qa/browser-form-result.json; qa/browser-d1-proof.json: real editable worksheet and synthetic native submission/storage'],'Action tests planned trench work in Kaunas region. No stock, fleet, price, executor, offer or appointment invented; production collection remains closed.');
unv('A3',['BUSINESS.md: six-week proposed decision policy'],'No real qualified requests, accepted paid leads or measured contribution. No expansion decision made.');
pass('B1',['../miniekskavatoriai.md: confirmed MB Pinet / info@pinet.lt','qa/html-final.json; qa/trust-pages.json: same visible contacts and Organization identity','public core config/niche-network.json: default recipient info@pinet.lt, no niche override'],'Recipient configuration inspected; mail receipt itself is not asserted (U2/U3).');
pass('B2',['EDITORIAL-REVIEW.json: all12 local page claim scopes','qa/trust-pages.json: no fleet, phone, business-ID, address, operator experience or testimonials'],'No other niche business details copied.');
unv('B3',['../miniekskavatoriai.md: identity facts and unknowns'],'Legal identifiers/address and actual domain control not established by this local task.');
pass('C1',['history/audit.json; history/REPORT.md: bounded4 readable snapshots,2 URLs, periods and retrieval limits','history/ASSESSMENT.md: current agent assessment'],'Successful snapshots do not establish ownership/continuity or full archive coverage.');
pass('C2',['history/url-decisions.json: root keep for new current intent, utility no restore','qa/publication-isolation.json: legacy utility403, no restored content/redirect'],'Cloudflare reserved utility path returns403, rather than planned404; actual result recorded. No mass home redirects.');
na('C3',['history/url-decisions.json: no legacy redirect implemented'],'No implemented legacy redirect exists to validate. Root new content is not a redirect.');
pass('D1',['RESEARCH.md; DESIGN.md: LT/foreign original pages, URL-specific adopted/deferred/rejected decisions','research/technikos-*.jpg; avesco-*.jpg; avesco-detail-*.jpg; dozr-*.jpg; hh-*.jpg; paslaugos-*-list.jpg; ramirent-*.jpg'],'Actual desktop/mobile. Paslaugos final list unobstructed; Ramirent cookie overlay restricts that evidence; Bobcat retrieval failed and supplies no facts.');
pass('D2',['BUSINESS.md: no competitor rates or historical business facts borrowed','EDITORIAL-REVIEW.json; MEDIA.json: original contribution and illustrative assets','qa/trust-pages.json: no imaginary expertise/fulfillment'],'Original supplier source facts remain qualified, not our commercial capacity.');
pass('D3',['BUSINESS.md: search/intent and unit-economic unknowns','CONTENT-CALENDAR.md; ACQUISITION.md: seasonal/SEO hypotheses'],'No search volume, rank, customer count or profit invented.');
pass('E1',['FINISH-REVIEW.md: fresh review of14 home/index/guide/tool/contact captures and nearest-network samples','qa/home-{desktop,mobile}-final.jpg; qa/gidai-*-final.jpg; qa/*-ar-be-*-final.jpg; qa/pravaziavimo-plotis-*-final.jpg; qa/nuomos-kainos-sudetis-*-final.jpg'],'Coherent field worksheet, actual tools/prism/access and vertical guide rows. Scoped craft8.57/10; guide rhythm/mobile first feedback weaker, not ≥9 target achieved.');
pass('E2',['DESIGN.md; .impeccable/design.json; QUALITY-BAR.md: actual tokens, plan, code-led choice, compromises','qa/PALETTE-VERIFICATION.md; qa/palette-runtime.json; research/concept-seed-original.txt; research/concept-seed-provenance.json'],'Fresh documenter reconciled actual colors/type/layout and image-free tool/purpose pages to the original plan. Captured warm cast distinguished from CSS/DOM and raw Lighthouse. Study/image timing deviation and late quality-card consolidation disclosed. Technical scores separate.');
pass('E3',['MEDIA.json; assets/*.prompt.txt; assets/*.png: private exact origin','qa/browser-layout-final.json: real loaded WebP images','qa/trust-pages.json: /redakcija truthful AI illustration method'],'No public generator badge, borrowed machinery ownership, fake client work or stock claim. SVG is exact geometric formula diagram, not a safety profile.');
pass('F1',['qa/html-final.json:12 pages and40 actual target requests,0 findings','qa/gidai-*-final.jpg; qa/trust-pages.json: all initial routes reachable'],'Three guides through home/index/context; trust routes via footer, inquiry via nav/action.');
pass('F2',['qa/browser-layout-final.json; qa/keyboard-menu.json: desktop/mobile destinations and native menu','qa/browser-form-result.json: real native submission destination'],'No placeholder navigation or dead CTA found.');
pass('F3',['EDITORIAL-REVIEW.json: unique originalContribution per URL','CONTENT-CALENDAR.json: distinct future intents kept private'],'No city/synonym doorway pages; index helps choose the question.');
pass('G1',['qa/home-desktop-final.jpg; qa/home-mobile-final.jpg'],'Trench planning, three dimensions, region/partner limits and actual next action visible. Mobile result below first viewport is a recorded compromise.');
pass('G2',['qa/home-desktop-final.jpg; qa/home-mobile-final.jpg; DESIGN.md'],'Middle distinguishes geometry, scope, access, networks and three guide questions, then explicit prerequest close.');
pass('G3',['qa/tool-interaction.json: empty/invalid/valid values, prepared text not automatically sent','qa/browser-form-result.json; qa/local-form-interest.json: native required fields, honest success and503 failure','qa/trust-pages.json: privacy linked'],'Real behavior, including alternate email path on failure; SMTP remains off.');
pass('H1',['EDITORIAL-REVIEW.json: individual operator/access/price guide review and contributions','qa/html-final.json: three full Article pages rendered; source text individually read'],'Guide usefulness judged from complete text and checklists, not minimum word count.');
pass('H2',['EDITORIAL-REVIEW.json; RESEARCH.md: each guide source/claim review','qa/html-final.json: visible source lists and limits'],'No universal width/depth, safe digging, guaranteed price/time or operator credential claim. ESO original procedural limitations checked.');
pass('H3',['EDITORIAL-REVIEW.json: operator responsibilities, narrowest access checklist, total quote-comparison questions','qa/*-ar-be-*-final.jpg; qa/pravaziavimo-plotis-*-final.jpg; qa/nuomos-kainos-sudetis-*-final.jpg'],'Concrete decisions and next routes; no nominal word-count filler.');
pass('H4',['qa/html-final.json: actual full guide article/lists/sources,577+ visible words on operator route','qa/browser-layout-final.json; qa/narrow-tablet.json: mobile/320/tablet rendering'],'No body quietly dropped by renderer. Long captures downsampled; source and DOM supplement visual review.');
pass('H5',['MEDIA.json:4 original families and20 shared responsive WebP variants','qa/browser-layout-final.json: all home/index/guide images loaded','FINISH-REVIEW.md: each guide image present and suitable'],'Contact/trust/legal and workflow pages use text/native controls instead of decorative photography; information/privacy/action is their task. Three guides, home panorama/access and index thumbnails have meaningful imagery.');
pass('I1',['qa/html-final.json: Article author MB Pinet linked to eligible public /redakcija','qa/trust-pages.json: /redakcija identifies responsibility and corrections contact'],'Organization, not fictional Person.');
pass('I2',['qa/html-final.json: Organization/Article author/schema IDs','qa/trust-pages.json: no qualifications invented'],'Attribution consistent; AI review not a qualified human approval.');
pass('I3',['qa/html-final.json: fixed visible publication/review and Article dates','qa/trust-pages.json: /redakcija explains local planned-publication meaning'],'Dates do not refresh on requests. Package date is not evidence of a public launch.');
unv('I4',['qa/trust-pages.json: local version explicitly not public deployment'],'No production deployment/first public availability occurred.');
pass('J1',['qa/trust-pages.json: full /apie-projekta and /redakcija texts'],'Purpose, responsible operator, AI role, source method, limitations and corrections contact explicit.');
pass('J2',['EDITORIAL-REVIEW.json: AI agent review actor','qa/trust-pages.json: qualified approval not claimed'],'No owner, engineer or construction specialist signoff inferred.');
pass('J3',['fix-reviewed-content.mjs: targeted corrections through studio edit/approval/export','qa/publication-isolation.json: altered approved body rejected; hash/revocation negative tests','qa/html-final.json: final approved text projected'],'Includes tool position sentence and home ESO source correction; no direct post-approval public content edit.');
pass('K1',['qa/html-final.json: all12 routes, one H1,title,description,lt, canonical;0 findings'],'Final production worker, not static mock.');
pass('K2',['qa/html-final.json; qa/browser-layout-final.json: heading/alt/share metadata matches','qa/trust-pages.json: own data-SVG icon and own wordmark; renderer niche head override'],'Own trench mark. Core base icon also exists in head; niche override is present, no borrowed visible wordmark.');
pass('K3',['qa/publication-isolation.json: future/private unknown404','qa/html-final.json; qa/execution-proof.json: negative URLs,no homepage canonical'],'Reserved Cloudflare utility403 is excluded from page URL claim.');
pass('L1',['qa/html-final.json: parsed Organization/WebSite/WebPage/Article appropriate types','qa/execution-proof.json: own SEO smoke'],'Tool/inquiry remain WebPage; three editorial guides Article.');
pass('L2',['qa/html-final.json: BreadcrumbList names/path/URLs and author public target checked'],'ArticleMeta uses shared visible byline/date, not hidden identity.');
pass('L3',['qa/html-final.json; EDITORIAL-REVIEW.json'],'No Product/Offer/Review/AggregateRating/LocalBusiness or rich-result guarantee.');
unv('L4',['qa/html-final.json: local schema evidence only'],'No crawlable production site, Search Console verification or official rich-result inspection.');
pass('M1',['qa/html-final.json:40 target requests, fragment destinations checked','qa/publication-isolation.json: real target-ID projection'],'Context links help operator/access/quote/tool questions.');
pass('M2',['qa/publication-isolation.json: actual future/revoked/hash projection removes guide and incoming links','qa/execution-proof.json: core publication negative tests24/24'],'Incoming links withheld consistently; fixture manipulations not published.');
pass('M3',['CONTENT-CALENDAR.json; fix-reviewed-content.mjs: own pillar/related IDs','qa/html-final.json: actual related and contextual links'],'No all-to-all network link scaffold.');
pass('N1',['RESEARCH.md; EDITORIAL-REVIEW.json: original official/supplier sources, reviewed2026-10-01','research/avesco-detail-*.jpg; hh-*.jpg; technikos-*.jpg; qa/html-final.json: visible source panels'],'Supplier mention supplies comparison evidence, not partnership. Failed Bobcat source excluded.');
na('N2',['qa/html-final.json; own approved content-package.json: no owned editorial cross-domain link'],'No editorial owned-domain link included. Mandatory footer attribution is assessed separately under N4, not a fake target-ID article relation.');
pass('N3',['qa/html-final.json: contextual prose/source/related links render','qa/*-guide screenshots; qa/trust-pages.json'],'No paid/sponsored/UGC arrangement; no invented rel sponsor.');
unv('N4',['qa/home-desktop-final.jpg: required verslomatika attribution; networkLiveDomains remains empty'],'No live launch occurred; external attribution availability and actual launch destination must be checked then.');
pass('O1',['qa/execution-proof.json: own and seven-domain SEO smoke','qa/html-final.json: canonical/sitemap/robots','qa/publication-isolation.json: unavailable404/crosshost404; slash308 and query canonical tested'],'Canonical https real domain retained even in local preview; loopback is not live-domain evidence.');
pass('O2',['qa/html-final.json; qa/execution-proof.json: approved sitemap only,lastmod,robots tested'],'Draft access is not secured by robots alone; draft source excluded from public export.');
unv('O3',['qa/verification-summary.json: isolated local worker only'],'DNS/TLS/domain control/production host isolation not exercised.');
pass('P1',['qa/publication-isolation.json: authoritative projection controls eligible pages/links/assets/LLM','qa/html-final.json; qa/execution-proof.json: sitemap/schema actual'],'No niche SEO copy fork; shared projection reused.');
pass('P2',['qa/publication-isolation.json: actual future/revoked/hash/cross-host negative cases','qa/execution-proof.json: core24/24'],'Private future drafts never imported; unknown-host media blocked.');
pass('P3',['qa/publication-isolation.json: changed approval rejected; six other package counts preserved','qa/execution-proof.json: compile/import and all seven SEO smoke'],'Only own content/renderer and small registry/dispatch/import integration; no schema change.');
pass('Q1',['qa/publication-isolation.json: llmScope approved editorial facts only','qa/execution-proof.json: active niche LLM exports smoke'],'Same contact/URLs, no private drafts, prompts, synthetic leads or hidden business facts. Client form state is not machine-only content.');
pass('Q2',['qa/html-final.json; EDITORIAL-REVIEW.json: visible semantic qualified answers,lists,citations'],'Definitions and prerequisites in HTML; no hidden model-specific assertions.');
pass('Q3',['BUSINESS.md; RESEARCH.md; ../miniekskavatoriai.md'],'LLM index supplementary; no guaranteed rankings/AI traffic/rich-result capability.');
pass('R1',['qa/keyboard-menu.json; qa/skip-link-focus.jpg: native Tab/Return skip and menu','qa/browser-form-result.json; ACCESSIBILITY-VERIFICATION.json: labelled controls,3px focus'],'Actual keyboard behavior, not Lighthouse alone.');
unv('R2',['ACCESSIBILITY-VERIFICATION.json: computed contrast,touch targets,320 reflow','qa/palette-runtime.json: extra Chrome zoom attempt unchanged'],'200% browser enlargement not established; native ctrl+plus had no effect in IAB or Chrome. Narrow layout/score100 cannot substitute.');
pass('R3',['qa/tool-interaction.json: aria-invalid and recovery','qa/browser-form-result.json: required field focused with native error','qa/browser-layout-final.json; own CSS: no entrance motion/animation'],'Images/heading/menu disclosure and requirements usable; default visible content requires no reduced-motion workaround.');
pass('S1',['qa/browser-layout-final.json:1440/390 seven main routes; all loaded,no overflow','qa/trust-pages.json: five additional routes desktop/mobile','qa/narrow-tablet.json:320 main routes and768 home/guide/tool no overflow'],'Real browser viewports.');
unv('S2',['qa/narrow-tablet.json; qa/keyboard-menu.json; ACCESSIBILITY-VERIFICATION.json'],'Narrow content/byline/source/form/footer inspected, but actual enlarged text200% remains unproved.');
pass('S3',['ACCESSIBILITY-VERIFICATION.md; FINISH-REVIEW.md'],'IAB viewport and Lighthouse simulation explicitly distinguished from physical devices/touch certification.');
pass('T1',['qa/performance-summary.json; lighthouse-{home,guide,tool}.report.json/html: final mobile96/91/95, other categories100','qa/verification-summary.json: exact package/renderer hashes'],'Production-built isolated worker, real WebP/Manrope; Lighthouse12.8.2 mobile simulated network/CPU. All chosen pages ≥90.');
pass('T2',['qa/performance-summary.json: LCP2.5/3.1/2.5s,TBT90/60/60ms,CLS.00974/.0274/.002,total428/253/184KiB','MEDIA.json; own CSS: shared srcset/sizes,self-hosted fonts,plain tool'],'Guide labLCP3.1s not portrayed as field-green. Prior material contrast/CTA correction documented; no repeat score fishing after target met.');
unv('T3',['qa/performance-summary.json: local lab only'],'No live traffic/CrUX field CWV.');
pass('U1',['qa/local-form-interest.json:400 invalid/size,403origin,200honeypot without insert,503storage failure','qa/browser-d1-proof.json: actual native synthetic form retained in isolated D1, exact row removed'],'D1 storage independent of optional mail/voice; disabled mail leaves statusnew. Live SMTP failure not freshly triggered in this task (U2/U3).');
unv('U2',['qa/verification-summary.json: LEAD_SMTP_ENABLED=0','../../MAIL_CORE.md:2026-09-30 shared transport evidence is context only'],'Task expressly keeps actual SMTP off. New niche recipient/acceptance test not performed; no client mail sent.');
unv('U3',['qa/verification-summary.json: no new Message-ID/INBOX proof','../../MAIL_CORE.md: earlier other-niche matching test'],'SMTP authentication/old inbox proof cannot be relabelled as this niche receipt. QA records not demand.');
unv('U4',['qa/local-form-interest.json; qa/browser-d1-proof.json: isolated local D1 only'],'Production D1/bindings/delivery/recovery/reconciliation/rate controls unverified.');
pass('V1',['qa/local-form-interest.json: DNT/GPC/bot no increment,valid event increment,origin/private-path/size rejection','qa/verification-summary.json: synthetic counters local only'],'Pageviews/mail clicks separate from durable inquiries; QA counters excluded from demand ledger.');
pass('V2',['qa/trust-pages.json: /privatumas data inventory','qa/local-form-interest.json; qa/tool-interaction.json: query/form state not telemetry; only site/page/day event'],'No analytics cookies/visitor ID or form content payload; server logging terms remain launch gate.');
unv('V3',['BUSINESS.md; ACQUISITION.md: proposed measured decision interval','qa/verification-summary.json: voice off'],'No GSC/real qualified demand data. No expansion or voice activation.');
pass('W1',['qa/trust-pages.json: /privatumas and /naudojimo-salygos individually read','RESEARCH.md: EDPB original and VDAI context reviewed2026-10-01'],'Local synthetic-only notice matches actual pilot/data inventory. Public legal compliance not asserted.');
pass('W2',['qa/trust-pages.json: actual local purpose/contact/rights/deletion of synthetic records,unconfirmed public processor/retention terms explicit','qa/browser-d1-proof.json: marked record removed'],'Unknown business-ID/address/retention/processors not invented. No public personal-data collection authorized before W3 launch checks.');
unv('W3',['qa/trust-pages.json: public launch conditions explicit'],'Production basis,recipients/processors,transfers,retention and recovery/deletion procedure not established.');
pass('W4',['qa/trust-pages.json: inquiry purpose not newsletter/marketing','qa/tool-interaction.json; own native form source: explicit purpose checkbox, no tracking/marketing subscription'],'No nonessential-cookie provider active; inquiry consent does not authorize outreach.');
pass('X1',['qa/publication-isolation.json: package/bundle names exclude env/devvars/private prompt/original nichePNG; cross-host asset404','qa/local-form-interest.json: tenant/body boundaries','prepare-production.mjs: whitelist copy excludes private vars/secrets/runtime'],'No secrets read/exported or synthetic leads in public package/LLM. Private source originals stay out of niche public media.');
pass('X2',['qa/local-form-interest.json: deliberate storage503 with honest fallback; table restored','qa/publication-isolation.json: isolation/negative paths','qa/verification-summary.json: voice/mail off'],'Assessed optional dependencies, honeypot/origin/body limits; actual production rate/backups/recovery still X3/U4 gates.');
unv('X3',['qa/verification-summary.json: local only'],'Production access/rate/abuse/backups/restore/incident operation not proved.');
pass('Y1',['qa/publication-isolation.json: all current packages preserved','own renderer files; shared dispatch/registry tiny integration; no schema mutation','qa/execution-proof.json: core tests'],'Shared technical SEO/media/lead mechanism reused; only niche identity/content new.');
pass('Y2',['qa/execution-proof.json: core24/24, all seven domain SEO smoke after import; final own smoke repeat','qa/verification-summary.json: tsc and own ESLint/build pass'],'Other niches not redesigned or their existing dist rebuilt; own production copy.');
pass('Y3',['../../START_HERE.md; ../../AGENTS.md; ../../CORE_BUILD_CONTRACT.md: current workflow read','../miniekskavatoriai.md: links to this audit/research/design/QA and open gates'],'Own journal completes fresh-session handover without rewriting shared instructions or historical fingerprints.');
pass('Z1',['PHASE-1-AUDIT.md/json; PHASE-1-SCORE.json: all85 explicit site-specific criteria','qa/execution-proof.json; qa/verification-summary.json; FINISH-REVIEW.md: versions,bounds,baseline/corrections/screens'],'Audit initialized with all85UNVERIFIED; no other niche PASS copied. First-run snapshot retained separately before final/parent feedback.');
pass('Z2',['PHASE-1-AUDIT.md/json; PHASE-1-SCORE.json: scorer contract and explicit open gates','FINISH-REVIEW.md:8.57 subjective craft separate from lab and A–Z'],'No10/10, local-ready, domain-ready, ≥9 craft or proven demand claim.');
unv('Z3',['PHASE-1-AUDIT.md/json: launch checks UNVERIFIED'],'No actual launch handover; explicit deployment authorization, factual and operational evidence still required.');

const catalog=catalogFromMarkdown(await readFile(new URL('../../SKILLS/niche-site-audit/references/checklist.md',import.meta.url),'utf8'));
if(catalog.length!==85||Object.keys(decisions).length!==85)throw Error(`Expected85; catalog${catalog.length}; decisions${Object.keys(decisions).length}`);
audit.checks=audit.checks.map(c=>{if(!decisions[c.id])throw Error(`No manual decision ${c.id}`);return {...c,...decisions[c.id]};});
audit.evaluatedAt=new Date().toISOString(); audit.evaluator='AI agent site-specific A–Z evidence audit; separate fresh Impeccable reviewer for visual craft; no human/legal/engineering certification';
audit.environment={preview:summary.productionPreview,isolatedRoot:summary.isolatedRoot,SMTP:0,voice:0,viewports:[1440,390,320,768],actual200PercentZoom:'UNVERIFIED',physicalDevice:false,productionDeployed:false};
audit.version=summary.version;
audit.verdict={local:'FUNCTIONING LOCAL PILOT; NOT LOCAL-READY UNDER ALL AUDIT GATES',launch:'NOT LAUNCHED; NOT DOMAIN-READY',demand:'UNMEASURED: 0 verified real inquiries; synthetic QA excluded',visual:'Distinct coherent field worksheet; scoped craft8.57/10; ≥9 target not achieved; see fresh review and fixes-only verdict'};
audit.analysisInput={path:'domain-sorter/output/top200-research-20261001/selected/analizes/miniekskavatoriai-lt.md',sourceAt:'2026-10-01T10:38:17Z',sha256:'1f1fbfc730a3a0b97f2d42e396e74775e09486f2dc3d1e882ebcc405aeeace8e',assisted:true};
audit.findings=[
 {priority:'P1',state:'UNVERIFIED',ids:['R2','S2'],finding:'Actual200% browser enlargement not established; narrow widths and score100 do not substitute.'},
 {priority:'P1',state:'UNVERIFIED',ids:['U2','U3'],finding:'SMTP intentionallyoff; no new niche SMTP/Message-ID INBOX receipt.'},
 {priority:'P1',state:'UNVERIFIED',ids:['B3','I4','O3','U4','W3','X3','Z3'],finding:'Actual domain/identity/production legal and operational launch not authorized or proved.'},
 {priority:'P2',state:'TARGET NOT MET',ids:['E1','E2'],finding:'Fresh subjective craft12/14=8.57; guide rhythm/mobile feedback compromises remain. No benchmark or whole-surface perfection claim.'},
 {priority:'P2',state:'DOCUMENTED',ids:['E2'],finding:'Topic asset generation preceded final study screenshot comparison. Formal quality bar consolidated at finish. Original seed recovered unchanged, no reroll.'},
 {priority:'P2',state:'DOCUMENTED',ids:['E2'],finding:'CUA screenshots share a warm cast; actual DOM/CSS and raw Lighthouse colors match palette. Exact capture/environment cause unknown; no raster/CSS color compensation.'}
];
audit.baselineAndRepairs=[
 'Initial audit scaffold85/85UNVERIFIED; this manual record is independent of other niche audits.',
 'Initial source lacked some final source/context/cluster wiring; corrected through studio revision approval/export. Twelve final pages tested.',
 'Base/default link contrast and subsequent CTA inherited text were detected in actual render; scoped selectors corrected, final CTAwhite/dark confirmed.',
 'One detector pass:2px pilot side-border corrected to1px; rounded-border flag documented as falsepositive on square controls. No second detector.',
 'Legacy reserved-path assertion expected404; actual403 accepted as recorded no-restore result. Test expectation corrected, no runtime/redirect patch.',
 'Fresh review14 captures valid; original seed evidence recovered and common capture warmcast investigated. Fix verdict recorded by same reviewer, no new implementation batch.'
];
const score=scoreAudit(audit,catalog); audit.scoreSummary=score.stages;
await writeFile(new URL('./PHASE-1-AUDIT.json',import.meta.url),JSON.stringify(audit,null,2)+'\n');
await writeFile(new URL('./PHASE-1-SCORE.json',import.meta.url),JSON.stringify(score,null,2)+'\n');
let md=`# miniekskavatoriai.lt · pirmos fazės A–Z auditas\n\nVertinta ${audit.evaluatedAt}. ${audit.evaluator}.\n\nVeikiantis vietinis pilotas:12 patvirtintų puslapių,3 gidai, realus V=L×W×D įrankis ir taisomas poreikio ruošinys, vietinė D1 forma. Tai nėra local-ready ar domain-ready pagal visus vartus. SMTP/voiceoff; tikras domenas nepaleistas.\n\nAnalizės įvestis ir SHA – [svetainės žurnale](../miniekskavatoriai.md). Analysis-assisted darbas, ne nepaveiktas cold-start.\n\n## Atskiros būsenos ir balai\n\n| Etapas | PASS / taikomi | Balas /10 | gateReady | Neuždaryti vartai |\n| --- | --- | ---: | --- | --- |\n`;
for(const [stage,v] of Object.entries(score.stages))md+=`| ${stage} | ${v.passed}/${v.applicable} | ${v.score} | ${v.gateReady} | ${v.blockers.join(', ')||'—'} |\n`;
md+='\nCraft atskirai: **12/14 = 8,57/10**, šviežio vertintojo subjektyvus įvertis. ≥9 tikslas nepasiektas. Dizaino tapatybė ir naudingi mechanizmai išskirtiniai, bet gidų ritmas bei pirmo mobile ekrano rezultato vieta silpnesni. [FINISH-REVIEW](FINISH-REVIEW.md) ir jo fixes-only verdict nusako tikrą peržiūros apimtį.\n\nGalutinis mobilus Lighthouse: home96, kainos sudėties gidas91, įrankis95; accessibility/best-practices/SEO100 visose trijose ataskaitose. LCP2,5/3,1/2,5s; tai vietinis lab, ne field CWV ar WCAG atitiktis. [Visas matavimas](qa/performance-summary.json).\n\nDemand:0 patvirtintų realių užklausų; testai/skaitymai/mail clicks nėra paklausa. Launch nėra autorizuotas/atliktas.\n\n## Baseline ir taisymai\n\n';
md+=audit.baselineAndRepairs.map(t=>'- '+t).join('\n')+'\n\n## Likusios išvados\n\n';
md+=audit.findings.map(f=>`- **${f.priority} ${f.state} (${f.ids.join(', ')})**: ${f.finding}`).join('\n')+'\n\n## A–Z kriterijai\n\nPASS įrodymai yra konkrečios šios svetainės peržiūros/bandymai. UNVERIFIED ir FAIL prisideda0 prie balo; NA turi produkto apimties priežastį. Negalima vietiniu balu kompensuoti launch vartų.\n\n';
for(const group of Object.keys(score.categories)){
 const v=score.categories[group];md+=`### ${group} · ${v.passed}/${v.applicable}, ${v.score??'NA'}/10\n\n`;
 for(const c of audit.checks.filter(c=>c.id.startsWith(group)))md+=`- [${c.status==='PASS'?'x':' '}] **${c.id} ${c.status}** · ${c.stage} / ${c.gate?'gate':'review'} · ${c.criterion}\n  Įrodymai: ${c.evidence.join('; ')}. ${c.notes}\n`;
 md+='\n';
}
md+='## Versija ir perdavimas\n\nPaketo SHA256: `'+summary.version.packageSha256+'`. Rendererio failų hash, izoliuota aplinka ir komandų įrodymai: [verification-summary](qa/verification-summary.json), [execution-proof](qa/execution-proof.json), [publication-isolation](qa/publication-isolation.json). Visi85 kriterijai įtraukti, skaičiuota bendru `SKILLS/niche-site-audit/scripts/score-audit.mjs`; [JSON](PHASE-1-AUDIT.json), [scorer išvestis](PHASE-1-SCORE.json).\n\nPirma viešo paskelbimo data nežinoma; paketo publishAt jos nepakeičia. Prieš tikrą rinkimą reikia rekvizitų/domain control/DNS/TLS/hostingo, galutinės privatumo/retention eigos, productionD1/delivery/recovery/abuse kontrolės ir atskirai autorizuoto SMTP+konkretaus Message-ID INBOX testo. Partneriai/atlygis/grafikas vis dar nepatvirtinti. [BUSINESS](BUSINESS.md), [ACQUISITION](ACQUISITION.md), [pirmo rezultato snapshot](FIRST-RUN.md).\n';
await writeFile(new URL('./PHASE-1-AUDIT.md',import.meta.url),md);
console.log(JSON.stringify({criteria:audit.checks.length,stages:score.stages,version:summary.version},null,2));
