import {readFile,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {core} from '../release-20261010/pinned-core.mjs';
export const repo=path.resolve(import.meta.dirname,'../../..'),out=path.join(repo,'sites/madbeauty/cloudflare/output/indexing-release-20261010'),origin='https://madbeauty.lt';
export async function candidate(){
 const manifest=JSON.parse(await readFile(path.join(out,'manifest.json'),'utf8')),script=await readFile(path.join(out,'worker.mjs'),'utf8');assert.equal(createHash('sha256').update(script).digest('hex'),manifest.artifactSha256);
 const {Miniflare}=await import(pathToFileURL(path.join(core,'node_modules/miniflare/dist/src/index.js'))),mails=[],storage=await mkdtemp(path.join(os.tmpdir(),'madbeauty-indexing-candidate-'));
 const types={'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2','.json':'application/json'};
 const assetService=async req=>{try{const name=decodeURIComponent(new URL(req.url).pathname),root=path.join(repo,'sites/madbeauty/cloudflare/output/assets-release'),file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep))return new Response('Not found',{status:404});return new Response(await readFile(file),{headers:{'Content-Type':types[path.extname(file)]||'application/octet-stream'}});}catch{return new Response('Not found',{status:404});}};
 const mf=new Miniflare({modules:true,script,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'MadbeautyPlatform',useSQLite:true},ORGANIZATION_STAGING:{className:'MadbeautyOrganizationStaging',useSQLite:true}},durableObjectsPersist:storage,images:{binding:'IMAGES'},bindings:{APP_ORIGIN:origin,RELEASE_MODE:'production',SESSION_SECRET:'local-indexing-acceptance-no-production-access',OPERATOR_EMAIL:'operator@example.com',RETENTION_POLICY_VERSION:'madbeauty-2026-10-10-v1'},serviceBindings:{MAIL_TRANSPORT:async r=>{mails.push(await r.json());return new Response('Accepted');},ASSETS:assetService}});
 const browser=()=>{let cookie='',csrf='';const send=async(endpoint,input)=>{const r=await mf.dispatchFetch(origin+'/api/madbeauty/'+endpoint,{method:input===undefined?'GET':'POST',headers:{...(cookie?{cookie}:{}),...(input===undefined?{}:{origin,'content-type':'application/json','x-csrf-token':csrf})},...(input===undefined?{}:{body:JSON.stringify(input)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const value=await r.json();if(value.csrf)csrf=value.csrf;return {status:r.status,value};};return {send,async rpc(method,input={}){const r=await send('rpc',{method,input,siteId:'madbeauty'});assert.equal(r.status,200,method+': '+JSON.stringify(r.value));return r.value.result;},async login(email){await send('session');const c=await send('auth/start',{email});assert.equal(c.status,200);const code=mails.findLast(m=>m.to===email).text.match(/\b\d{6}\b/)[0];assert.equal((await send('auth/verify',{challengeId:c.value.challengeId,code})).status,200);},async upload(bytes,organizationId){const r=await mf.dispatchFetch(origin+'/api/madbeauty/upload',{method:'POST',headers:{cookie,origin,'content-type':'image/webp','x-csrf-token':csrf,'x-organization-id':organizationId,'x-asset-alt':'Izoliuoto bandymo iliustracija','x-asset-rights':'Savininko originali platformos iliustracija, tik vietinis testas','x-asset-rights-confirmed':'true','x-asset-usage':'gallery'},body:bytes});assert.equal(r.status,200);return(await r.json()).result;}};};
 return {mf,manifest,browser,request:p=>mf.dispatchFetch(origin+p),close:()=>mf.dispose()};
}
export async function seedPublicFixture(f){
 const owner=f.browser(),operator=f.browser();await owner.login('local-directory-owner@example.com');await operator.login('operator@example.com');const org=await owner.rpc('createOrganization',{name:'Izoliuotas katalogo bandymas',bio:'Tik vietinės patikros profilis; į live nekeliamas.',city:'Vilnius',kind:'salon'}),scope={role:'professional',organizationId:org.id},w=await owner.rpc('workspace',scope),service=await owner.rpc('createService',{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Testinis manikiūras',durationMin:60,priceMinor:2500});
 const draft=await owner.rpc('saveLocation',{organizationId:org.id,id:w.locations[0].id,version:w.locations[0].version||0,label:org.name,city:'Vilnius',publicAddress:'Tik vietinis bandymo adresas',openingHoursLabel:'Pagal grafiką',latitude:54.7,longitude:25.3}),pending=await owner.rpc('submitLocation',{id:draft.id,version:draft.version});await operator.rpc('moderateLocation',{id:pending.id,version:pending.version,state:'approved'});
 const asset=await owner.upload(await readFile(path.join(repo,'sites/madbeauty/prototype/public/images/service-illustration-nagai-360.webp')),org.id);
 assert.equal((await f.request('/'+asset.variants[0].file)).status,404,'Unpublished image must stay private');const current=await owner.rpc('workspace',scope);await owner.rpc('saveGallery',{organizationId:org.id,version:current.organizations[0].version,galleryEntries:[{mediaId:asset.id,providerServiceId:service.id,caption:'Vietinio bandymo iliustracija'}],staffPortraits:[],avatarImageId:null});
 const revision=await owner.rpc('submitRevision',{scope,name:org.name,bio:org.bio});await operator.rpc('moderate',{id:revision.id,state:'approved'});return {org,asset,owner};
}
