// Owner's seven screenshots define intended platform breadth, beyond today's 10 functional categories.
export const expandedCategories=[
{id:'nagu-priauginimas',name:'Nagų priauginimas ir papildymas',code:'NP',sources:['S01','S05','S07','S41'],rows:`
gidas|Nagų priauginimo gidas: ilgio kūrimas, konstrukcija ir papildymas|Q,S,E|1|Natūralus nagas ir konstrukcija;Ilgio bei formos užduotis;Naujas darbas ir papildymas|Konstrukcijos ir dangos komponentų schema|Sistemų dokumentai ir nagų specialisto review
gelis-akrilas-poligelis|Gelis, akrilas ir poligelis: medžiaga, konstrukcija bei pasirinkimo ribos|A,S|2|Skirtingos produktų sistemos;Norimas ilgis ir rezultatas;Ką turi įvertinti specialistas|Palyginimo lentelė pagal patikrintus protokolus|Kiekvienos sistemos gamintojo dokumentai; ne saugiausio produkto reitingas
formos-tipsai|Nagų priauginimo formos ir tipsai: ką reiškia paslaugos metodas?|Q,A|2|Ilgio formavimo pagrindas;Medžiaga atskirai;Metodo ir rezultato skirtumas|Originalus formos ir tipso brėžinys|Meistro techninių apibrėžimų review
papildymas|Gelinių nagų papildymas ar pilnas nuėmimas: kaip skiriasi konstrukcijos darbai?|A,C|2|Esama konstrukcija;Papildymo apimtis;Naujas darbas ir kito meistro sistema|Trijų pradinių situacijų apimties lentelė|Konkrečios sistemos ir meistro protokolas
kaina-trukme|Nagų priauginimo kaina ir trukmė: ilgis, konstrukcija, dizainas bei nuėmimas|C|1|Naujo darbo komponentai;Papildymo variantai;Papildomi darbai|Datuotų realių meniu komponentų palyginimas|LT meniu ir konkrečios sistemos patikra
pasiruosimas|Prieš nagų priauginimą: sena sistema, norimas ilgis ir kasdieniai poreikiai|P|3|Pradinė danga;Ilgio bei formos užduotis;Ankstesnio darbo informacija|Užpildoma konsultacijos kortelė|Meistro review; individualaus tinkamumo neįrodo nuotrauka
prieziura|Priaugintų nagų priežiūra: kasdieniai įpročiai ir tolimesnio vizito planas|R|3|Konstrukcijos tausojimas;Priežiūra pagal sistemą;Papildymas ar nuėmimas|Naudotai sistemai skirta priežiūros kortelė|Gamintojo instrukcija; nėra universalaus korekcijos intervalo
pazeidimas|Pažeista nagų konstrukcija: korekcija, nuėmimas ir sveikatos pagalbos riba|H|5|Defektas ir sveikatos požymiai;Informacija meistrui;Ko nedaryti savarankiškai|Pagalbos kelias be klijavimo namuose|Sveikatos specialisto ir nagų meistro review
`},
{id:'plauku-formavimas',name:'Plaukų formavimas ir šukuosenos',code:'SF',sources:['S33','S43','S58'],rows:`
gidas|Plaukų formavimo gidas: džiovinimas, sušukavimas ir proginė šukuosena|Q,S,E|1|Formavimas nėra kirpimas;Paslaugos komponentai;Vizito eiga ir rezultato užduotis|Trijų formavimo tikslų schema|Kirpėjo eigos patikra
dziovinimas-ar-progine|Džiovinimas ir sušukavimas ar proginė šukuosena: skirtinga darbo apimtis|A,C|2|Plovimas ir džiovinimas;Formos kūrimas bei tvirtinimas;Pasiūlymo priedai|Vienodos apimties paketų palyginimas|S33,S58 meniu prieš rašymą
garbanos-bangos|Garbanos, bangos ir tiesus sušukavimas: ką parodyti šukuosenos užduotyje?|A,S|2|Sruogos forma ir dydis;Ilgis ir tekstūra;Renginio bei komforto poreikiai|Originalūs siluetų pavyzdžiai|Kirpėjo review ir originalūs vaizdai
susegta|Susegta ar palaida proginė šukuosena: tvirtinimas, apranga ir aksesuarai|S|2|Plaukų tvirtinimo vieta;Apranga ir aksesuarai;Pradinio ilgio ribos|Renginio užduoties matrica|Meistro realių atlikimo galimybių review
vestuves|Vestuvinė šukuosena ir bandomasis vizitas: ką užbaigti prieš renginį?|P,S|4|Bandomojo vizito tikslas;Dokumentuotas sprendimas;Dienos grafikas|Bandomojo vizito rezultatų kortelė|Tikro teikėjo sąlygos; ne visiems privalomas bandymas
kaina-trukme|Šukuosenos kaina ir trukmė: plovimas, formavimas bei aksesuarai|C|1|Įtrauktas plovimas;Sudėtingumas ir ilgis;Atvykimas į renginio vietą|Normalizuota dviejų tikrų pasiūlymų lentelė|Aktualūs meniu ir tikras išvykimo pasiūlymas
pasiruosimas|Prieš sušukavimą: kada plauti plaukus ir ką atsinešti?|P|3|Meistro pasirinktas metodas;Ankstesnės priemonės;Aksesuarai ir užduoties nuotrauka|Pasiruošimo kortelė pagal sutartą vizitą|Konkretaus teikėjo instrukcija; jokios universalios neplovimo taisyklės
prieziura|Kaip išlaikyti šukuosenos formą renginyje ir saugiai ją išardyti?|R,H|3|Aplinka ir judėjimas;Tvirtinimo elementai;Karščio bei įtempimo ribos|Renginio priežiūros ir išardymo kortelė|S43 ir meistro review; nėra visos dienos garantijos
makiazas-kartu|Makiažas ir šukuosena vienu vizitu: grafikas bei paslaugų sudėtis|C,P|4|Vienas ar keli meistrai;Darbų seka ir atvykimas;Paketo komponentai|Renginio laiko schema su patvirtinimo laukais|S58 ir tikro teikėjo darbo organizavimas
`},
{id:'plauku-prieziura',name:'Plaukų priežiūros procedūros',code:'PP',sources:['S33','S43','S54'],rows:`
gidas|Plaukų priežiūros procedūrų gidas: kosmetinė priežiūra ir lūkesčių ribos|Q,S,E|1|Kosmetinis tikslas;Naudota produktų sistema;Ko procedūra nepakeičia apie plaukų sveikatą|Tikslų, komponentų ir teiginių lentelė|Konkrečių sistemų dokumentai ir kirpėjo review
atstatymas|„Plaukų atstatymas“: ką reiškia pasiūlymas ir kokiam rezultatui reikia įrodymų?|Q,H|2|Rinkodaros terminas;Laikinas kosmetinis efektas;Teiginio patikros apimtis|Teiginių ir reikalingų įrodymų schema|Konkrečių produktų duomenys; ne gydymo ar permanent repair pažadas
tiesinimas|Ilgalaikis plaukų tiesinimas ir įprastas formavimas: skirtinga procedūra|A,S|2|Formavimas karščiu;Produkto procedūra;Rezultato ir saugos ribos|Dviejų paslaugų eigos palyginimas|S54 ir konkrečios sistemos saugos dokumentai
keratinas|Keratininio tiesinimo pasiūlymas: produktas, karštis ir sudėties patikra|Q,H|5|Pavadinimas ir tikra sistema;Sudėtis bei darbo sąlygos;Ko neįrodo žyma|Produkto dokumentų tikrinimo kortelė|S54, aktualūs ES reikalavimai ir sveikatos review; ne JAV normų perkėlimas
kaina-trukme|Plaukų priežiūros procedūros kaina ir trukmė: sistema, ilgis bei priedai|C|1|Naudota sistema;Ilgis ir tankis;Kirpimas ar formavimas papildomai|Datuotų pasiūlymų apimties lentelė|Tikri meniu ir identifikuoti produktai
pasiruosimas|Prieš plaukų priežiūros procedūrą: dažymo istorija ir naudojami produktai|P|3|Ankstesni cheminiai darbai;Norimas kosmetinis rezultatas;Produkto protokolas|Istorijos ir lūkesčių kortelė|Sistema ir kirpėjo individualus įvertinimas
prieziura|Po plaukų priežiūros procedūros: kodėl plovimo instrukcija priklauso nuo sistemos?|R|3|Kas buvo atlikta;Konkrečios sistemos instrukcija;Spalvos bei formavimo planas|Produkto pavadinimu pažymėta priežiūros kortelė|Gamintojo instrukcija; ne universali 72 h taisyklė
reakcija|Reakcija procedūros metu ar po jos: kosmetinės priežiūros ir sveikatos pagalbos riba|H|5|Naudota sistema ir ekspozicija;Kokią informaciją perduoti;Kada reikia sveikatos vertinimo|Pagalbos ir informacijos perdavimo atmintinė|S54 ir sveikatos specialisto review
`},
{id:'depiliacija',name:'Depiliacija vašku ir cukrumi',code:'DP',sources:['S51','S55','S11'],rows:`
gidas|Depiliacijos gidas: vaškas, cukraus pasta, zonos ir vizito eiga|Q,S,E|1|Plaukelio pašalinimo principas;Metodas ir zona;Vizito eiga bei komfortas|Metodo ir zonos pasirinkimų schema|Depiliacijos specialisto eigos review
vaskas-ar-cukrus|Depiliacija vašku ar cukrumi: metodų ir paslaugos skirtumai|A,S|2|Naudojama medžiaga;Darbo metodas;Ko pavadinimas nepasako apie individualų tinkamumą|Metodų lentelė be „neskausmingos“ garantijos|Konkrečių produktų protokolai ir specialisto review
kojos|Kojų depiliacija: blauzdos, šlaunys ar visos kojos|C,S|1|Zonų ribos;Pasiūlymo sudėtis;Metodas ir vizito planas|Originalus zonų žemėlapis|S55 meniu; ne visiems vienodi zonų pavadinimai
rankos-pazastys|Rankų ir pažastų depiliacija: kaip skiriasi zonos bei pasiūlymai?|C,S|2|Rankų zonos;Pažastys kaip atskira paslauga;Paketo sudėtis|Zonų ir komponentų schema|Aktualūs meniu ir teikėjo ribų patvirtinimas
bikini|Bikini depiliacija: klasikinis, gilus ir kiti pasiūlymo pavadinimai|Q,S|2|Zonos ribos;Privatumas bei komunikacija;Ką tiksliai patvirtinti|Neutralus zonų apimties paaiškinimas be eksplicitinių nuotraukų|Tikro teikėjo terminai ir darbo tvarka
veidas|Veido depiliacija: zonos, metodas ir kosmetinės priežiūros ribos|S,H|4|Ūseliai ar visas veidas;Naudojami odos produktai;Individualaus vertinimo poreikis|Pradinės informacijos ir zonų kortelė|S51 ir dermatologinė review; nesustabdyti vaistų savarankiškai
vyrams|Vyrų depiliacija vašku: kūno zonos, apimtis ir pirmasis vizitas|S,P|2|Nugara ir kitos zonos;Apimtis bei privatumas;Pirmo vizito informacija|Konkrečių zonų ir komforto užduotis|Tikro teikėjo vyrų paslaugų meniu dar reikalingas
kaina-trukme|Depiliacijos kaina ir trukmė: zonos, metodas bei paketai|C|1|Kiek zonų apima pasiūlymas;Atskiras ar bendras vizitas;Kas įskaičiuota|Normalizuotas dviejų meniu palyginimas|S55 patikrinti prieš tekstą; jokio vidurkio iš vieno meniu
pasiruosimas|Kaip pasiruošti depiliacijai: plaukelių ilgis, odos produktai ir instrukcija|P|3|Metodas ir teikėjo instrukcija;Pradinė odos informacija;Kas negali būti universali taisyklė|Sistemai pildoma pasiruošimo kortelė|Konkretaus vaško/pastos protokolas; nesugalvoti vienodo mm ar valandų termino
prieziura|Priežiūra po depiliacijos: naudojamas metodas, oda ir tolesnis planas|R|3|Naudoti produktai;Konkreti priežiūros instrukcija;Kada kosmetinių patarimų nepakanka|Datuota priežiūros kortelė|S51 ir produkto instrukcija; jokios universalios šveitimo datos
reakcija|Sudirgusi oda po depiliacijos: kada reikia sveikatos specialisto?|H|5|Procedūros informacija;Kosmetinio diskomforto vertinimo ribos;Pagalbos kelias|Veiksmų atmintinė be ligos diagnozės ar vaistų|Sveikatos specialisto review
ar-lazeris|Depiliacija vašku ar lazerinis plaukų šalinimas: skirtingas metodas ir vizitų planas|A,S|2|Pašalinimas ir mažinimo principas;Vienas vizitas ir individualus planas;Kompetencijos bei įrodymų ribos|Dviejų metodų pasirinkimo matrica|S50,S51 ir kvalifikuota review; ne individualus saugumo testas
`},
{id:'plauku-salinimas-lazeriu',name:'Plaukų šalinimas lazeriu ir IPL',code:'LZ',sources:['S50','S51','S29','S31'],rows:`
gidas|Plaukų šalinimo lazeriu gidas: metodas, konsultacija ir rezultatų ribos|Q,S,E|1|Poveikio principas;Konsultacija ir pradinė informacija;Vizito eiga bei individualus planas|Pasirinkimo ir konsultacijos schema|Konkretaus įrenginio dokumentai ir LT kvalifikuota review
lazeris-ipl|Lazeris ir IPL plaukų šalinimui: kuo skiriasi technologijos pavadinimai?|A,Q|2|Šviesos šaltinis;Įrenginio ir protokolo reikšmė;Ko vien pavadinimas neįrodo|Technologijų terminų schema|Pirminė konkrečių įrenginių dokumentacija dar reikalinga
diapazonas|Odos ir plaukelių savybės prieš lazerinį šalinimą: ką vertina specialistas?|S,H|5|Pradinė oda ir plaukelis;Įrenginio tinkamumo ribos;Kodėl nėra savidiagnostinio testo|Konsultacijos duomenų kortelė|S50/S51 turi kontekstinių išimčių; nederinti į universalų tinkamumo pažadą
zonos|Lazerinio plaukų šalinimo zonos: veidas, pažastys, bikini ir kūnas|C,S|2|Zonų ribos;Atskiras ir bendras pasiūlymas;Įrenginio paskirtis pasirinktai zonai|Neutralus zonų žemėlapis|Tikras teikėjo ir įrenginio zonų protokolas
kursas|Kiek lazerio vizitų reikia: individualus planas ir palaikymo ribos|C,R|4|Pradinės savybės;Rezultato stebėjimas;Palaikymas ir paketo sąlygos|Individualaus plano ruošinys be universalaus vizitų skaičiaus|S50 nėra garantija kiekvienam klientui; specialisto review
kaina-trukme|Plaukų šalinimo lazeriu kaina ir trukmė: zona, įrenginys bei paketas|C|1|Vienos zonos apimtis;Konsultacija;Kurso komercinės sąlygos|Tikro pasiūlymo komponentų lentelė|LT meniu ir konkretus įrenginys dar tikrintini
pasiruosimas|Prieš lazerinį šalinimą: įdegis, ankstesni metodai ir konsultacija|P|3|Ankstesnė ekspozicija ir šalinimas;Naudojami produktai/vaistai;Specialisto instrukcijos|Konsultacijos istorijos kortelė|S50 ir konkretaus protokolo review; vaistų nekeisti pagal straipsnį
prieziura|Priežiūra po plaukų šalinimo lazeriu: pagal procedūrą pateikta instrukcija|R|3|Atlikta procedūra;Aplinkos poveikis;Individuali priežiūra ir pakartotinis vertinimas|Pasirašytos instrukcijos komponentų ruošinys|Specialisto ir įrenginio protokolas; ne naminio lazerio mokymas
reakcija|Reakcija po lazerinės procedūros: kada kreiptis į sveikatos specialistą?|H|5|Procedūros ir įrenginio duomenys;Vertinimo nuotoliu ribos;Pagalbos kelias|Informacijos perdavimo atmintinė|S50 ir kvalifikuota sveikatos review
`},
{id:'makiazas',name:'Makiažas',code:'MK',sources:['S33','S58','S11'],rows:`
gidas|Makiažo paslaugų gidas: dieninis, proginis ir vestuvinis rezultatas|Q,S,E|1|Renginio ir rezultato užduotis;Naudojamų produktų kontekstas;Vizito eiga|Tikslų ir darbų komponentų matrica|Vizažisto peržiūra ir originalūs vaizdai
dieninis-proginis|Dieninis ir proginis makiažas: intensyvumas, apimtis ir pasiūlymo ribos|A,S|2|Intensyvumo užduotis;Darbų apimtis;Ko nepasako vien pavadinimas|Originalios vienodos veido schemos|Vizažisto review; ne realios klientės transformacija
vestuvinis|Vestuvinis makiažas ir bandomasis vizitas: kaip užfiksuoti pasirinkimą?|P,S|4|Bandomojo vizito tikslas;Renginio sąlygos;Dokumentuotas rezultato briefas|Pasirinkimų ir bandomojo vizito kortelė|Konkretaus teikėjo sąlygos; ne universalus privalomas bandymas
nuotrauka|Makiažo nuotrauka vizažistui: tekstūra, atspalvis ir retušo ribos|S,P|2|Kas nuotraukoje patinka;Apšvietimas ir retušas;Rezultato užduotis realiame kontekste|Originalus nuotraukos vertinimo pavyzdys|S23 ir vizažisto review; teisių patikra
kaina-trukme|Makiažo kaina ir trukmė: blakstienos, bandomasis vizitas bei atvykimas|C|1|Įtraukti komponentai;Papildomas vizitas;Išvykimo sąlygos|Datuotų tikrų meniu apimties palyginimas|S33,S58 naujas patikrinimas
pasiruosimas|Kaip pasiruošti makiažui: odos produktai, reakcijų istorija ir renginio planas|P|3|Naudojamos priemonės;Ankstesnės reakcijos;Renginio dienos informacija|Pasiruošimo kortelė be odos diagnozavimo|Vizažisto instrukcija ir sveikatos teiginių review
laikymasis|Makiažo palaikymas renginyje: tekstūra, aplinka ir pataisymo priemonės|R|3|Kosmetinis rezultatas;Renginio aplinka;Sutartas pataisymo rinkinys|Renginio priežiūros atmintinė|Konkretaus produkto instrukcija; nėra 24 h išlaikymo garantijos
nuvalymas|Kaip nuvalyti profesionalų makiažą ir atskirti laikinų blakstienų priežiūrą?|R|3|Naudoti produktai;Vienkartiniai priedai;Priauginimas nėra tas pats|Nuvalymo instrukcijos ruošinys pagal produktus|Gamintojų instrukcijos; ne klijų tirpiklio naudojimas prie akių
higiena|Makiažo higiena: įrankiai, produktai ir odos reakcijų informacija|H,E|5|Įrankių higiena;Produkto naudojimo sąlygos;Reakcijos ir sveikatos vertinimo riba|NVSC terminų paaiškinimas makiažo situacijai|S11 ir aktuali produkto/sveikatos review
`},
{id:'kuno-prieziura',name:'Kūno priežiūra ir estetinės procedūros',code:'KP',sources:['S52','S57','S29','S31'],rows:`
gidas|Kūno priežiūros procedūrų gidas: kosmetinė priežiūra, metodai ir lūkesčiai|Q,S,E|1|Priežiūra ir estetinis tikslas;Rankinis ar aparatinis komponentas;Vizito eiga ir medicininė riba|Tikslų bei komponentų žemėlapis|Konkrečių metodų dokumentai ir kvalifikuota review
sveitimas|Kūno šveitimas: kosmetinės procedūros apimtis ir priežiūra|Q,R|2|Šveitimo komponentas;Zona ir papildomi darbai;Priežiūra pagal produktą|Neprocedūrinė paslaugos eigos schema|Kosmetikos instrukcija ir teikėjo review
ivyniojimas|Kūno įvyniojimai: priemonė, ritualas ir pažadų ribos|Q,A|2|Naudota priemonė;Papildomi ritualo darbai;Ko neįrodo svorio ar detox reklama|Dviejų tikrų paketų komponentų palyginimas|S57 ir produktų duomenys; jokio kilogramų pažado
celiulitas|„Celiulito gydymas“ kainyne: estetinio pokyčio ir gydymo teiginio skirtumas|Q,H|5|Meniu terminas;Konkretaus metodo įrodymai;Kosmetinio rezultato ir gydymo riba|Teiginių ir įrodymų lentelė|S52 ir LT kvalifikuota review; ne garantuotas gydymas
liekninanti|Liekninamoji procedūra ar kūno kontūro keitimas: ko iš tikrųjų tikėtis?|A,S,H|5|Pavadinimas ir realus metodas;Kontūras nėra svorio mažinimo gydymas;Individualus vertinimas|Tikslų atskyrimo schema be garantijų|S52 ir konkretaus įrenginio duomenys
mezoterapija|Beadatinė mezoterapija: koks metodas slepiasi po paslaugos pavadinimu?|Q,E,H|5|Koks konkretus įrenginys naudojamas;Skirtumas nuo injekcijų;Poveikio ir kvalifikacijos įrodymai|Metodą ir įrodymų paskirtį atskirianti kortelė|Įrenginio protokolas bei LT veiklos teisėtumo review dar būtini
aparatai|Kūno procedūrų įrenginiai: RF, ultragarsas ir kitos technologijos|A,S|4|Technologijos pavadinimas;Konkreti paskirtis ir zona;Ko neįrodo vien prekės ženklas|Tik patikrintų technologijų terminų schema|S52 nėra ES leidimo ar konkretaus teikėjo įrodymas
kaina-trukme|Kūno procedūros kaina ir trukmė: zonos, metodas bei kursas|C|1|Vienos zonos apimtis;Komponentai ir konsultacija;Paketo sąlygos|Realios apimties ir kainos pasiūlymo ruošinys|Aktualūs LT meniu; veiksmingumas tikrinamas atskirai
pasiruosimas|Prieš kūno procedūrą: tikslas, ankstesni darbai ir individualus vertinimas|P|3|Kosmetinis tikslas;Naudotos procedūros;Metodo instrukcija bei sveikatos informacija|Konsultacijos duomenų kortelė|Konkretaus metodo ir sveikatos specialisto review
prieziura|Po kūno procedūros: metodo instrukcija ir rezultato stebėjimas|R|3|Kas buvo atlikta;Konkretaus protokolo priežiūra;Rezultato dokumentavimo sąlygos|Priežiūros ir stebėjimo kortelė|Produkto/įrenginio dokumentai; ne detox dieta
reakcija|Nepageidaujama reakcija po kūno procedūros: pagalbos bei kompetencijos ribos|H|5|Procedūros ir įrenginio informacija;Individualaus vertinimo poreikis;Sveikatos pagalbos kelias|Informacijos perdavimo atmintinė|S52 ir kvalifikuota sveikatos review
`},
{id:'auskaru-verimas',name:'Auskarų vėrimas',code:'AV',sources:['S11','S53','S30'],rows:`
gidas|Auskarų vėrimo gidas: vieta, papuošalas, eiga ir priežiūros planas|Q,S,E|1|Vėrimo vieta ir pradinė informacija;Specialisto ir aplinkos patikra;Vizito eiga bei priežiūros ribos|Paslaugos užduoties ir dokumentų kortelė|Specialisto bei LT veiklos reikalavimų review
vietos|Ausies spenelis, kremzlė ir kitos vėrimo vietos: skirtinga užduotis|A,S|2|Pasirinkta vieta;Papuošalo ir darbo apimtis;Individualaus vertinimo ribos|Neutralus anatominių zonų orientacinis brėžinys|Kvalifikuota review; ne vėrimo namuose schema
metodai|Auskarų vėrimo metodas ir įrankiai: ką paaiškina specialistas?|A,E|2|Naudojamas metodas;Vienkartiniai ir daugkartiniai instrumentai;Sterilizavimo informacija|Terminų ir paskirties lentelė|NVSC ir konkretaus metodo dokumentai; ne DIY instrukcija
papuosalas|Pirmas auskaras: papuošalo medžiaga, dydis ir dokumentuota informacija|S|2|Medžiagos deklaracija;Dydis ir pasirinktai vietai tinkamumas;Produkto informacija|Papuošalo dokumentų kortelė be saugios medžiagos garantijos|Aktualūs ES medžiagų reikalavimai ir specialisto review
kaina-trukme|Auskarų vėrimo kaina ir trukmė: papuošalas, vieta ir kontrolinis vizitas|C|1|Darbo ir papuošalo sudėtis;Vėrimo vieta;Kontrolinio vizito sąlygos|Tikro pasiūlymo komponentų lentelė|Datuotas LT teikėjo meniu dar tikrintinas
pasiruosimas|Prieš auskarų vėrimą: ankstesnės reakcijos, amžius ir paslaugos sąlygos|P|3|Ankstesnių reakcijų informacija;Teikėjo sutikimo ir amžiaus sąlygos;Pasiruošimo instrukcija|Vizito informacijos kortelė|Tikros LT nepilnamečių ir veiklos taisyklės; UK amžiaus normų neperkelti
prieziura|Priežiūra po auskarų vėrimo: vietai pritaikyta instrukcija ir kontrolė|R|3|Konkrečios vietos instrukcija;Papuošalo keitimo vertinimas;Kada priežiūros nepakanka|Rašytinės instrukcijos ruošinys|Specialisto protokolas ir sveikatos review; nėra vienodo gijimo termino
reakcija|Skausmas ar įtariama infekcija po vėrimo: kada reikalinga sveikatos pagalba?|H|5|Procedūros istorija;Kodėl nedaroma diagnozė iš nuotraukos;Pagalbos kelias Lietuvoje|Pagalbos ribų atmintinė|S53 ir LT sveikatos specialisto review; UK numerių neperkelti
`},
{id:'barzda-vyrams',name:'Barzda ir vyrų paslaugų pasirinkimas',code:'BR',sources:['S56','S43','S11'],rows:`
gidas|Vyrų grožio paslaugų gidas: kirpimas, barzda, dažymas, oda ir depiliacija|Q,S|1|Paslaugos pagal tikslą;Kirpimas ir barzda atskirai;Kur tęsti konkretaus metodo pasirinkimą|Vyrų paslaugų kelio schema su nuorodomis į bendrus metodų gidus|Nedubliuoti dažymo/veido/depi tekstų vien pagal lytį
kirpimas-modeliavimas|Barzdos kirpimas ir modeliavimas: ilgis, kontūras ir darbo apimtis|Q,S,E|1|Ilgio užduotis;Kontūras ir ūsai;Vizito eiga bei užbaigimas|Originalus barzdos zonų brėžinys|Barberio techninių terminų review
masinele-skutimas|Barzdos formavimas mašinėle ar švarus skutimas: skirtingas rezultatas|A,S|2|Paliekamas ilgis;Kontūro darbas;Naudoti produktai ir papildomi komponentai|Dviejų užduočių palyginimas|S56 ir barberio protokolas
forma|Barzdos forma: kaip sutarti kontūrą ir ilgį be „idealios veido formos“ pažado?|S|2|Norimas kontūras;Augimo kryptis ir tankis;Kasdienis formavimas|Originalūs kontūrų siluetai ir užduoties kortelė|Barberio review; ne plaukų augimo gydymas
paketas|Kirpimas ir barzda vienu vizitu: kaip palyginti paketo apimtį?|C|2|Plaukų kirpimo komponentai;Barzdos darbas;Papildomi ritualai|Vienodų komponentų meniu palyginimas|S56 meniu perpatikrinti
kaina-trukme|Barzdos paslaugų kaina ir trukmė: formavimas, skutimas ir papildomi darbai|C|1|Atskiras barzdos vizitas;Paketo priedai;Vizito laikas|Datuotų realių pasiūlymų lentelė|Aktualūs LT meniu
pasiruosimas|Prieš barberio vizitą: ilgis, norimas pokytis ir odos informacija|P|3|Pradinė barzda;Norimo rezultato nuotrauka;Ankstesni produktai ir reakcijos|Vizito užduoties kortelė|Barberio review; sveikatos teiginiai atskirai
prieziura|Barzdos priežiūra po vizito: formavimas, priemonės ir palaikymo užduotis|R|3|Sutarta forma;Naudotų produktų instrukcija;Tolimesnis vizitas pagal poreikį|Priežiūros ir formos užduoties kortelė|Produkto instrukcija; nėra visiems vienodo vizitų intervalo
oda|Odos sudirgimas po skutimo: kosmetinės priežiūros ir sveikatos vertinimo riba|H|5|Naudota priemonė ir metodas;Ko neįrodo nuotrauka;Kada reikia sveikatos pagalbos|Informacijos perdavimo atmintinė|Dermatologinis šaltinis ir sveikatos review dar būtini
`}
];
export const extraRows={masazas:`
gilieji-audiniai|Giliųjų audinių masažas: metodo paskirtis, stiprumas ir kompetencijos ribos|Q,A,H|5|Metodo principas;Stiprumas nėra rezultato garantija;Individualaus vertinimo poreikis|Terminų ir paskirties schema|S37 ir kvalifikuota masažo/sveikatos review
limfodrenazinis|Limfodrenažinis masažas: grožio pasiūlymas ir sveikatos paslaugos kontekstas|Q,A,H|5|Konkretaus metodo paskirtis;Rankinis ar aparatinis variantas;Kompetencijos ir efekto įrodymai|Tikslą, metodą ir kvalifikaciją atskirianti lentelė|Metodo dokumentai ir LT kvalifikuota review; ne detox pažadas
aromaterapinis|Aromaterapinis masažas: naudojamos priemonės, kvapas ir komfortas|Q,A|2|Rankinio darbo komponentas;Naudota priemonė;Kvapo ir reakcijų informacija|Paslaugos komponentų kortelė|Konkrečios priemonės dokumentai; jokio ligų gydymo aromatais
kaklas-peciai|Nugaros, kaklo ir pečių masažas: kaip apibrėžiama zona bei seanso apimtis?|C,S|2|Kokios zonos įtrauktos;Darbo ir vizito laikas;Komforto derinimas|Originalus zonų brėžinys|Tikro teikėjo apimtis; nedubliuoti viso kūno palyginimo
`};
// Every named item in the supplied screenshots has a reader-job destination, including broad category labels.
export const referenceMenu=[
['Plaukai','Kirpimas moterims','KR-gidas'],['Plaukai','Vyriškas kirpimas','KR-trumpas-vyriskas'],['Plaukai','Plaukų ar sruogelių dažymas moterims','DZ-sruogos'],['Plaukai','Džiovinimas ir sušukavimas','SF-dziovinimas-ar-progine'],['Plaukai','Balayage ir Ombre dažymas','DZ-ombre-sombre'],['Plaukai','Vaikų kirpimas','KR-vaikui'],['Plaukai','Visos plaukų priežiūros paslaugos','PP-gidas'],
['Nagai','Ilgalaikis gelinis manikiūras','GL-gidas'],['Nagai','Ilgalaikis gelinis pedikiūras','PD-gelinis-ar-paprastas'],['Nagai','Manikiūras','MN-gidas'],['Nagai','Nagų lako nuėmimas','GL-nuemimas'],['Nagai','Nagų priauginimas','NP-gidas'],['Nagai','Nagų papildymas geliu','NP-papildymas'],['Nagai','Visos nagų priežiūros paslaugos','MN-gidas'],
['Depiliacija','Moterų kojų depiliacija vašku','DP-kojos'],['Depiliacija','Moterų rankų ir pažastų depiliacija vašku','DP-rankos-pazastys'],['Depiliacija','Moterų depiliacija cukrumi','DP-vaskas-ar-cukrus'],['Depiliacija','Vyrų depiliacija vašku','DP-vyrams'],['Depiliacija','Moterų bikini depiliacija vašku','DP-bikini'],['Depiliacija','Plaukų šalinimas lazeriu','LZ-gidas'],['Depiliacija','Visos depiliacijos paslaugos','DP-gidas'],
['Masažas','Giliųjų audinių masažas','MS-gilieji-audiniai'],['Masažas','Atpalaiduojantis masažas','MS-atpalaiduojantis-gydomasis'],['Masažas','Nugaros kaklo ir pečių masažas','MS-kaklas-peciai'],['Masažas','Limfodrenažinis masažas','MS-limfodrenazinis'],['Masažas','Aromaterapinis masažas','MS-aromaterapinis'],['Masažas','Veido masažas','MS-veido-kobido'],['Masažas','Visos masažo paslaugos','MS-gidas'],
['Veidas','Blakstienų priauginimas','BL-klasikinis-volume'],['Veidas','Antakių korekcija ir dažymas','AN-korekcija-ar-dazymas'],['Veidas','Blakstienų laminavimas','BL-laminavimas'],['Veidas','Veido procedūros','VP-gidas'],['Veidas','Veido valymas','VP-valymo-metodai'],['Veidas','Makiažas','MK-gidas'],['Veidas','Visos veido priežiūros paslaugos','VP-gidas'],
['Kūnas','Kūno šveitimas','KP-sveitimas'],['Kūnas','Celiulito gydymas','KP-celiulitas'],['Kūnas','Auskarų vėrimas','AV-gidas'],['Kūnas','Kūno įvyniojimai','KP-ivyniojimas'],['Kūnas','Liekninamoji procedūra','KP-liekninanti'],['Kūnas','Beadatinė mezoterapija','KP-mezoterapija'],['Kūnas','Visos kūno priežiūros paslaugos','KP-gidas'],
['Vyrams','Vyriškas kirpimas','KR-trumpas-vyriskas'],['Vyrams','Plaukų dažymas vyrams','DZ-gidas'],['Vyrams','Barzdos kirpimas ir modeliavimas','BR-kirpimas-modeliavimas'],['Vyrams','Veido procedūros vyrams','VP-gidas'],['Vyrams','Vyrų kirpykla','BR-gidas'],['Vyrams','Vyrų depiliacija vašku','DP-vyrams'],['Vyrams','Vyrų kirpykla (bendras meniu adresas)','BR-gidas']
].map(([family,label,targetId])=>({family,label,targetId,decision:'COVER_DISTINCT_JOB_OR_CONTEXT_IN_SHARED_METHOD_GUIDE',source:'OWNER_SUPPLIED_SCREENSHOT_2026-10-06',platformState:'INTENDED_SCOPE_NOT_PROOF_OF_LIVE_CATEGORY_OR_PROVIDER'}));
