// Reviewed high-demand discoveries. These are editorial judgments, not vendor observations.
export const overrides=[
 ['nagai','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','MN-gidas','Plati nagų paslaugų kategorija; ne vien manikiūras ir ne vien dizainas.',['nagai']],
 ['odontologija','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','OD-gidas','Plati odontologijos paslaugų kategorija; gidas paaiškina užduočių skirtumus.',['odontologija']],
 ['kineziterapeutas','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','KT-gidas','Specialisto pasirinkimo ketinimas, ne atskiras profesijos sinonimo straipsnis.'],
 ['barzdaskuciai','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','BR-kirpimas-modeliavimas','Bendras specialistų paieškos terminas; barzdos paslaugų apimtis ir tikri pasiūlymai atskiri.'],
 ['spa lietuvoje','REVIEW_MIXED_TRAVEL_OR_SERVICE','SP-gidas','SPA viešbutis, nakvynė ir dienos procedūra skiriasi. Turime tik spa desktop imtį, ne šios tikslios frazės SERP.'],
 ['pi pilates','EXCLUDE_COMPETITOR_OR_BRAND_NAVIGATION',null,'Navigacinis studijos pavadinimas; nesavinti kito verslo prekės ženklo.'],
 ['dot pilates','EXCLUDE_COMPETITOR_OR_BRAND_NAVIGATION',null,'Navigacinis studijos pavadinimas; nesavinti kito verslo prekės ženklo.'],
 ['trumpu plauku kirpimas vyresnems moterims','MERGE_AS_READER_CONSTRAINT','KR-gidas','Amžius savaime nesukuria universalios formos. Tekstūra, tankis ir priežiūros poreikis aptariami pagrindiniame pasirinkimo gide.'],
 ['trumpu plauku kirpimas virs 50','MERGE_AS_READER_CONSTRAINT','KR-gidas','Tas pats pasirinkimas su tikromis tekstūros ir priežiūros išimtimis; atskiro amžiaus klono nereikia.'],
 ['šukuosenos moterims virš 50','MERGE_AS_READER_CONSTRAINT','KR-gidas','Ne ideali forma pagal amžių; pasirinkimą lemia pageidaujamas kontūras, tekstūra ir priežiūra.'],
 ['kirpimai moterims virš 60','MERGE_AS_READER_CONSTRAINT','KR-gidas','Amžiaus variantas aptarnaujamas įvardytame pasirinkimo skyriuje, ne universalių stereotipų straipsnyje.'],
 ['reformer pilates','ANSWER_IN_NAMED_SECTION','FX-joga-pilatesas','Inventorius ir pamokos formatas yra palyginimo gido dalis. Konkrečią reformer pamokos eigą pagrįsti realia instruktoriaus programa; pratimų ar tinkamumo nekurti.'],
 ['plaukai','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','KR-gidas','Bendra plaukų kategorija apima ne vien kirpimą.',['plaukai']],
 ['programos','EXCLUDE_AMBIGUOUS_GENERIC_QUERY',null,'Neįvardyta kokios srities programa; paklausa nepriskiriama treniruotėms vien dėl related seed.'],
 ['masazas skelbiu','EXCLUDE_COMPETITOR_OR_BRAND_NAVIGATION',null,'Skelbimų portalo navigacija, ne mūsų straipsnio užduotis.'],
 ['poilsis lietuvoje','EXCLUDE_OUT_OF_SERVICE_SCOPE',null,'Platus turizmo ir nakvynės pasirinkimas, ne patvirtintos vietinės procedūros.'],
 ['kirpimas','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','KR-gidas','Bendra kirpimo paslaugų paieška; amžiaus ar lyties variantų nepadauginti į gidus.'],
 ['valymas','EXCLUDE_AMBIGUOUS_GENERIC_QUERY',null,'Neįvardyta veidas, oda ar kita valymo paslauga; bendras terminas nėra kosmetologijos apimties įrodymas.'],
 ['naujausi trumpu plaukų kirpimai','MERGE_AS_READER_CONSTRAINT','KR-gidas','Naujumo epitetas nesukuria naujo URL ar mados tyrimo įrodymo; parodyti originalius patikrintus kontūrų pavyzdžius.'],
 ['trumpu plauku kirpimas','ANSWER_IN_NAMED_SECTION','KR-gidas','Trumpų formų pasirinkimas pagal kontūrą ir tekstūrą; mašinėlės perėjimas turi siauresnį KR-trumpas-vyriskas atsakymą.'],
 ['trumpu plauku kirpimas pagal veido forma','ANSWER_IN_NAMED_SECTION','KR-gidas','Tas pats formos, tekstūros ir kasdienio formavimo pasirinkimas; ne atskiras frazės variantas.'],
 ['labai trumpu plauku kirpimas','ANSWER_IN_NAMED_SECTION','KR-gidas','Ilgio ribos aptariamos pasirinkimo gide ir nuorodoje į konkrečią trumpą techniką.'],
 ['parafino vonele','REVIEW_MIXED_PRODUCT_OR_SERVICE',null,'Gali reikšti perkamą įrenginį ar procedūrą. Nepainioti parafino paslaugos su prekės paieška.'],
 ['parafino vonele rankoms','REVIEW_MIXED_PRODUCT_OR_SERVICE',null,'Prekės/įrenginio ir salono procedūros ketinimas neištirtas tiksliu SERP; ne automatinis RP-gidas savininkas.'],
 ['pilates namai','REVIEW_BRAND_OR_HOME_EXERCISE',null,'Galimas studijos pavadinimas arba treniruotė namuose; tikslių rezultatų neturime.'],
 ['gydanti raminanti muzika','EXCLUDE_AUDIO_OR_TREATMENT_QUERY',null,'Garso klausymas ar gydymo teiginys nėra mūsų vietinio užsiėmimo pasiūlymas. Nekurti terapinio pažado.'],
 ['veido masažai','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','MS-veido-kobido','Daugiskaita nekeičia paslaugos užduoties; konkretūs metodai aptariami veido masažo gide.'],
 ['grazus plauku kirpimai','MERGE_AS_READER_CONSTRAINT','KR-gidas','Subjektyvus grožio epitetas; originalių kontūrų ir skirtingų tekstūrų pavyzdžiai tame pačiame pasirinkimo gide.'],
 ['spa dviems','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','SP-poroms','SPA poroms sinonimas; vienas laiko, privatumo ir paketų apimties gidas.'],
 ['tattoo ant rankos','ANSWER_IN_NAMED_SECTION','TT-eskizas','Vieta ir mastelis yra eskizo užduoties kriterijai; ne svetimų piešinių galerija ar atskiras vietos klonas.'],
 ['tatuiruotės ant rankos','ANSWER_IN_NAMED_SECTION','TT-eskizas','Tas pats vietos, mastelio ir autoriaus eskizo sprendimas.'],
 ['tattoo ant rankos moterims','MERGE_AS_READER_CONSTRAINT','TT-eskizas','Lytis savaime nesukuria kitos eskizo funkcijos; individuali idėja ir mastelis paaiškinami bendrame gide.'],
 ['lakavimas','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','GL-gidas','Bendras padengimo pasirinkimas apima paprastą ir gelinę dangą; nukreipti į tikrą bendrą lakavimo grupę.'],
 ['treniruotės','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','FX-gidas','Plati individualių ir grupinių užsiėmimų kategorija.'],
 ['nagu idejos vasarai','ANSWER_IN_NAMED_SECTION','ND-gidas','Originalios dizaino adaptacijos pagal progą pagrindiniame gide; nekopijuoti masinės tendencijų galerijos.'],
 ['gydomasis masazas','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','MS-atpalaiduojantis-gydomasis','Sveikatos paslaugų kompetencijos ir gydomojo masažo konsultacijos skirtumas; ne poilsio pasiūlos pakaitalas.'],
 ['mezoterapija plaukams','ANSWER_IN_NAMED_SECTION','ES-mezoterapija-biorevitalizacija','Zonos ir indikacijos klausimas konsultacijai; jokio plaukų slinkimo gydymo ar individualaus tinkamumo pažado.'],
 ['mezoterapija veidui','ANSWER_IN_NAMED_SECTION','ES-mezoterapija-biorevitalizacija','Konkretaus produkto paskirtis ir zona yra metodų gido dalis, klinikinė peržiūra privaloma.'],
 ['dizainas','EXCLUDE_AMBIGUOUS_GENERIC_QUERY',null,'Bendras žodis nėra nagų dizaino paklausa.'],
 ['antakiai','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','AN-gidas','Bendra antakių paslaugų grupė; forma, dažymas ir laminavimas atskirti.'],
 ['plaukų priauginimas kaina','ANSWER_IN_NAMED_SECTION','PX-gidas','Priauginimo metodas, plaukų kiekis, tvirtinimai ir korekcija; ankstesnis dažymo kainos kandidatas neteisingas.'],
 ['plauku priauginimas kaina','ANSWER_IN_NAMED_SECTION','PX-gidas','Rašybos variantas to paties priauginimo kainos apimties atsakymo; paklausos nesumuoti.'],
 ['burnos higiena kaina','ANSWER_IN_NAMED_SECTION','OD-gidas','Profesionalios higienos komponentai ir patikrinto datuoto pasiūlymo apimtis; ne išgalvotas nacionalinis vidurkis.'],
 ['gelinis lakavimas pavyzdziai','ANSWER_IN_NAMED_SECTION','ND-gidas','Spalvos ir dizaino pavyzdžiai yra nagų dizaino funkcija, ne manikiūro bei dangos terminų palyginimas.'],
 ['spa su nakvyne','EXCLUDE_OUT_OF_SERVICE_SCOPE',null,'Nakvynės / viešbučių pasiūlymai nepriskirti patvirtintam procedūrų katalogui.'],
 ['geriausi spa lietuvoje','REVIEW_MIXED_TRAVEL_OR_SERVICE',null,'Neturime patikrintų viešbučių ar realių bandymų, todėl nekurti geriausių reitingo iš snippet.'],
 ['gyvūnų kirpykla','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','GY-gidas','Gyvūnų paslaugų teikėjo paieška; rūšis ir kailio priežiūra gide atskirti.'],
 ['blakstienos','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','BL-gidas','Bendra paslaugų grupė gali turėti kosmetikos / produkto prasmę; tikri paslaugų variantai atskirti.'],
 ['masažas vyrams','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','MS-gidas','Metodas ir tikslas, o ne lyties klonas. Pasiūlymo tinkamumas ir privatumas tikri.'],
 ['masazas vyrams','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','MS-gidas','Rašybos variantas; nedauginti straipsnių ir nesumuoti apimčių.'],
 ['veido proceduros','NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER','VP-gidas','Bendra veido paslaugų apimtis, ne automatinis masažo palyginimo puslapis.'],
 ['gydomoji meditacija','EXCLUDE_AUDIO_OR_TREATMENT_QUERY',null,'Gydymo pažadas nepagrįstas savijautos užsiėmimo pasiūla; įrodymų ribos tik SV-gidas.'],
 ['ryto meditacija','REVIEW_AUDIO_OR_LOCAL_CLASS',null,'Galimas nemokamos garso praktikos ar konkretaus užsiėmimo ketinimas; neturime tikslaus SERP.'],
 ['dažymas','EXCLUDE_AMBIGUOUS_GENERIC_QUERY',null,'Bendras terminas neįvardija plaukų, antakių ar kito objekto.'],
 ['laminavimas','EXCLUDE_AMBIGUOUS_GENERIC_QUERY',null,'Bendras terminas neįvardija antakių ar blakstienų ir gali reikšti spaudos paslaugą.'],
 ['tatuiruotės kaina','ANSWER_IN_NAMED_SECTION','TT-gidas','Dydis, eskizas, vieta ir sesijų apimtis atsakomi gide su tikrais datuotais pavyzdžiais.'],
 ['japoniškas manikiūras kaina','ANSWER_IN_NAMED_SECTION','MN-japoniskas','Paslaugos komponentai ir konkreti sistema; vieno metodo kainai atskiro klono nereikia.'],
 ['madingi kirpimai moterims','MERGE_AS_READER_CONSTRAINT','KR-gidas','Mados epitetas neįrodo aktualios tendencijos; gido originalios formos paaiškinamos pagal žmogaus poreikį.'],
 ['vyresnio amžiaus plonu plauku kare kirpimas ploniems plaukams','ANSWER_IN_NAMED_SECTION','KR-ploni','Plauko storis ir tankis yra reali pasirinkimo išimtis; amžiaus stereotipo nekuriame.']
];
export const addedSections={
 'KR-gidas':['Trumpų kirpimų formos: kontūras, tekstūra ir priežiūra vietoj amžiaus stereotipo'],
 'FX-joga-pilatesas':['Pilatesas ant kilimėlio ir su reformer: inventorius, pamokos formatas ir individualus parinkimas'],
 'ES-mezoterapija-biorevitalizacija':['Veidas ar galvos oda: priemonės paskirties ir individualios konsultacijos ribos'],
 'PX-gidas':['Plaukų priauginimo kainos sudėtis: metodas, kiekis, tvirtinimai ir korekcija'],
 'OD-gidas':['Burnos higienos kainos apimtis ir datuotas tikro pasiūlymo pavyzdys'],
 'TT-gidas':['Tatuiruotės kainos apimtis: eskizas, mastelis, vieta ir sesijos'],
 'ND-gidas':['Originalaus gelinės dangos dizaino pavyzdys ir adaptacija progai'],
 'MN-japoniskas':['Japoniško manikiūro pasiūlymo komponentai ir kaina pagal konkrečią sistemą']
};
