import {readFileSync,writeFileSync} from 'node:fs';
const p=JSON.parse(readFileSync(new URL('PLAN.json',import.meta.url)));
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=Object.fromEntries([...p.existing,...p.pages].map(x=>[x.id,x]));
const ref=id=>p.pages.some(x=>x.id===id)?`<a class="topic-link" href="#${e(id)}">${e(byId[id].title)}</a>`:e(byId[id]?.title??id);
const source=id=>{const s=p.sources.find(s=>s.id===id);return `<a href="${e(s.url)}" target="_blank" rel="noopener">${e(id)} · ${e(s.title)}</a>`;};
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${e(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const section=(id,title,body)=>`<section id="${id}"><h2>${e(title)}</h2>${body}</section>`;
const families=[...new Set(p.pages.map(x=>x.family??'Bendra'))];
const cards=p.pages.map(x=>`<details class="topic" id="${e(x.id)}" data-family="${e(x.family??'Bendra')}" data-category="${e(x.categoryId)}" data-wave="${e(x.wave)}" data-search="${e([x.title,x.id,...x.outline].join(' '))}"><summary><small>${e(x.publishDate)} · ${e(x.id)} · ${e(x.family)}</small><strong>${e(x.title)}</strong><span>${e(x.cluster)}</span></summary><div class="brief"><p class="notice">${x.id==='B-registracija'?'Yra vienas istorinis privatus tekstas ir vaizdas; naujas approval ir public release neatlikti.':'Tai straipsnio planas. Tekstas, medija ir faktinė specialisto peržiūra dar neatlikti.'}</p><p><b>URL:</b> /${e(x.slug)}<br><b>Publikavimas:</b> ${e(x.publishAt)} · 10:00 Vilniuje po kokybės peržiūros.</p><p><b>Tiesioginis atsakymas:</b> ${e(x.answerRequirements.firstParagraph)}</p>${x.seo?`<h3>Raktažodžiai ir metaduomenys</h3><p><b>Pagrindinė frazė:</b> ${e(x.seo.primaryKeyword)}<br><b>Atrastos susijusios frazės (kandidatai):</b> ${e(x.seo.relatedKeywords.join('; '))}<br><b>Meta title:</b> ${e(x.seo.metaTitle)}<br><b>Meta description:</b> ${e(x.seo.metaDescription)}</p><p><b>Apimtis:</b> ${e(x.seo.monthlySearchVolume??'duomenų nėra')} / mėn. · ${e(x.seo.status)}<small>${e(x.seo.volumeMeaning)}</small></p>`:''}<h3>H2 struktūra</h3><ol>${x.outline.map(h=>`<li>${e(h)}</li>`).join('')}</ol><p><b>Originali nauda:</b> ${e(x.originalContribution)}</p><p><b>Savarankiškas ketinimas:</b> ${e(x.distinctIntent)}</p><p><b>Surinkti prieš rašant:</b> ${e(x.evidenceNeeds.map(n=>n.task).join('; '))}</p><p><b>Peržiūra:</b> ${x.reviewLevel==='QUALIFIED_HEALTH_OR_LEGAL_REVIEW'?'Kvalifikuotas sveikatos / teisės specialistas pagal teiginį ir jurisdikciją':'Redakcija ir paslaugos specialistas techniniams teiginiams'}</p><p><b>Vaizdas:</b> ${e(x.media.role)}. ${e(x.media.subject)}. ${e(x.media.proofBoundary)}</p><p><b>Pradiniai šaltiniai:</b> ${x.sourceIds.map(source).join(' · ')}</p>${x.procedureSections?.length?`<h3>Konkrečios katalogo procedūros</h3>${x.procedureSections.map(s=>`<p><b>${e(s.label)}</b> · ${e(s.taxonomyNodeId)}</p><ul>${s.requirements.map(r=>`<li>${e(r)}</li>`).join('')}</ul>`).join('')}`:''}<h3>Vidinės redakcinės nuorodos</h3><ul>${p.links.filter(l=>l.from===x.id).map(l=>`<li>${ref(l.to)} — ${e(l.section)}. ${e(l.reason)}<small>${e(l.activation)}</small></li>`).join('')}</ul><h3>Procedūros ir miesto katalogo tikslas</h3>${x.catalogueTargets.length?table(['Tikslas','Registro ID','Planuojamas adresas'],x.catalogueTargets.map(t=>[e(t.label),e(t.routeRegistryId),`${e(t.canonicalPath)}<small>Pasirinkus miestą: ${e(t.citySelection.pathPattern)}</small>`])):`<p>${e(x.catalogueTargetReason)}</p>`}<p class="notice">Katalogo href aktyvuojamas tik pagal šviežią resolverį: deployed ir reachable. Šis snapshot yra planas. Indeksavimas vertinamas atskirai.</p><p><b>Atmesti tekstą, jei:</b> ${e(x.answerRequirements.failIf)} ${e(x.claimBoundary)}</p></div></details>`).join('\n');
const sections=[
section('strategy','Pilnas katalogas, aiškūs skaitytojo sprendimai',`<p>21 katalogo sritis išskaidyta į 33 redakcines kryptis: kas tai, skirtumai, pasirinkimas, apimtis, pasiruošimas, eiga, priežiūra ir pagalbos ribos. Artimos procedūros turi konkrečius skyrius viename gide; sinonimai nėra atskiri URL.</p><p>Medicina ir kiti plėtiniai planuojami kaip paslaugos supratimo ir pasirinkimo gidai. Tai nėra visų ligų ar gydymo enciklopedija.</p><p class="notice">Aprėpties planas užbaigtas. Vienas privatus registracijos tekstas ir vaizdas parengti; likę tekstai ir vaizdai dar nesukurti, specialistų peržiūros neatliktos. Realus autoritetas ir Google pozicijos neišmatuoti.</p><p><a href="RESEARCH.md">Tyrimas</a> · <a href="WRITING_PLAYBOOK.md">Rašymo taisyklės</a> · <a href="PLAN.json">Visas planas</a> · <a href="VALIDATION.json">Patikra</a></p>`),
section('coverage','21 sritis × 8 skaitytojo poreikiai',`<p>Q — kas tai; A — alternatyvos; S — pasirinkimas; C — apimtis, kaina, trukmė; P — pasiruošimas; E — eiga; R — priežiūra; H — problemos ir pagalbos ribos. Skaičiai reiškia suplanuotus atsakymus.</p>${table(['Katalogo sritis','Procedūros','Apimtis',...Object.keys(p.dimensions)],p.catalogueCategoryCoverage.map(c=>[e(c.label),String(c.treatmentCount),c.scope==='core'?'Grožio katalogas':'Patvirtintas plėtinys',...Object.keys(p.dimensions).map(d=>String(c.matrix[d].length))]))}<details><summary>33 redakcinių krypčių matrica</summary>${table(['Kryptis','Nauji URL',...Object.keys(p.dimensions)],p.categoryCoverage.map(c=>[e(c.name),String(c.pages.length),...Object.keys(p.dimensions).map(d=>String(c.matrix[d].length))]))}</details>`),
section('calendar','Datos: aprėptį parengti iki lapkričio pabaigos',`<p>${p.completionTarget} — ${p.totals.evergreenNew} evergreen temų parengimo orientyras. Parengtą susietą grupę galima išleisti anksčiau; nepatvirtintas tekstas ar nebaigta peržiūra nukelia konkrečią datą. Savaitinės publikavimo kvotos nėra.</p>${table(['Data','Temų','Parengimo sąlyga'],p.waves.map(w=>[w.date,String(p.pages.filter(x=>x.wave===w.id).length),`${e(w.title)}<small>${e(w.gate)}</small>`]))}<h3>Sezonai</h3>${table(['Data','Tema'],p.pages.filter(x=>x.wave==='SEASONAL').map(x=>[x.publishDate,ref(x.id)]))}<h3>3 esami gidai: adresai ir publikavimo datos išlaikomi</h3>${table(['Straipsnis','Atnaujinimas'],p.retained.map(x=>[`${e(x.title)}<small>/${e(x.slug)}</small>`,`${x.revisionDate}<small>${e(x.revisionNeeds)}</small>`]))}<details><summary>12 rezultatų ir aprėpties peržiūrų</summary>${table(['Data','Darbas'],p.reviews.map(x=>[x.date,e(x.action)]))}</details>`),
section('keywords','Lietuvos raktažodžių tyrimas',p.keywordResearch?`<p>${e(p.keywordResearch.summary)}</p><p>${e(p.keywordResearch.limits)}</p><p><a href="KEYWORD_RESEARCH.md">Prioritetai ir tyrimo ribos</a> · <a href="SEO_MAP.json">Visų straipsnių SEO žemėlapis</a></p>`:'<p>Tikros Lietuvos mėnesinės apimtys per treg dar neįtrauktos. Paieškos formuluočių tyrimas nėra apimčių matavimas.</p>'),
section('topics',`Visi ${p.pages.length} individualūs straipsnių planai`,`<div class="controls"><label>Paieška<input id="search" type="search" placeholder="Tema, procedūra arba ID"></label><label>Šeima<select id="family"><option value="">Visos šeimos</option>${families.map(f=>`<option>${e(f)}</option>`).join('')}</select></label><label>Kryptis<select id="category"><option value="">Visos kryptys</option>${[...p.categoryCoverage,{id:'bendri',name:'Registracija ir meistrai'},{id:'sezonai',name:'Sezonai'}].map(c=>`<option value="${e(c.id)}">${e(c.name)}</option>`).join('')}</select></label><label>Banga<select id="wave"><option value="">Visos datos</option>${p.waves.map(w=>`<option value="${w.id}">${w.date}</option>`).join('')}<option value="SEASONAL">Sezonai</option></select></label></div><p id="count">Rodoma ${p.pages.length} iš ${p.pages.length} temų</p><button id="reset" type="button">Išvalyti filtrus</button> <button id="expand" type="button">Atverti matomas temas</button>${cards}`),
section('procedures','Visos 225 procedūros: kur atsakoma',`<p>Kiekviena procedūra susieta su konkretaus straipsnio vardiniu skyriumi. Šaltinis — platformos foundation c1f1593. Skyrius nėra papildomas URL.</p><details><summary>225 procedūrų lentelė</summary>${table(['Procedūra','Grupė / ID','Straipsnis ir skyrius'],p.procedureCoverage.map(s=>[e(s.label),`${e(s.groupId)}<small>${e(s.taxonomyNodeId)}</small>`,`${ref(s.targetId)}<small>${e(s.section)}</small>`]))}</details><details><summary>49 anksčiau parodytos meniu pozicijos</summary>${table(['Šeima','Pozicija','Atsakymas'],p.referenceMenu.map(s=>[e(s.family),e(s.label),ref(s.targetId)]))}</details><details><summary>76 ankstesnio plano ketinimai</summary>${table(['Tema','Sprendimas','Atsakymas'],p.reconciliation.map(s=>[e(s.oldTitle),e(s.decision),`${ref(s.targetId)}<small>${e(s.section)}</small>`]))}</details>`),
section('links',`${p.links.length} redakcinės nuorodos ir katalogo tikslai`,`<p>Kiekvienas ryšys turi vietą ir paskirtį. „Moterų kirpimas Vilniuje“ priklauso procedūros ir miesto katalogui; „kaip pasiruošti kirpimui“ — gidui. Informacinis tekstas siūlo konkrečią procedūrą, o miestą pasirenka skaitytojas.</p><p>305 nacionalinių adresų ir 103 miestų kontraktas nėra masinio indeksavimo planas. Nacionalinis naršymas, tuščias vietinis rezultatas ir naudingas vietinis katalogas vertinami atskirai.</p><p>14 core sričių foundation paruoštas izoliuotoje platformos šakoje; 7 plėtiniai suplanuoti. Gamybinis diegimas ir indeksavimas šiuo planu nepatvirtinami.</p><p><a href="CONTENT_SEO_HANDOFF.md">Suderinta nuorodų sutartis</a> · <a href="ARTICLE_CATALOGUE_TARGETS.json">Katalogo ID</a> · <a href="PLATFORM_SCOPE.md">Platformos apimtis</a></p><details><summary>Ryšiai tarp skirtingų krypčių</summary>${table(['Iš temos','Į temą','Paskirtis'],p.links.filter(l=>l.kind==='CONTEXTUAL'&&byId[l.from]?.categoryId!==byId[l.to]?.categoryId).map(l=>[ref(l.from),ref(l.to),`${e(l.section)}<small>${e(l.reason)}</small>`]))}</details>`),
section('sources',`${p.sources.length} perskaityti turinio šaltiniai`,`<p>Institucijos, konkrečių sistemų instrukcijos ir LT meniu. Meniu įrodo pasiūlymo apimtį, o ne sveikatos naudą ar mėnesines paieškas.</p><details><summary>Šaltiniai ir jų ribos</summary>${p.sources.map(s=>`<div class="source"><b>${source(s.id)}</b><p>${e(s.finding)}</p><small>${e(s.kind)} · ${e(s.checkedAt)} · ${e(s.status)}</small><p>Riba: ${e(s.limit)}</p></div>`).join('')}</details>`)
];
sections.unshift(section('review','2026-10-07: naujo SEO/GEO core peržiūra',`<p>300 pradinių naujų temų sutikrinta pagal skaitytojo užduotį. 8 sutampantys atsakymai sujungti; liko ${p.pages.length} nauji gidai ir 3 atnaujinimai. Visos 225 procedūros išlaikytos.</p><p>${p.keywordOwnership.unresolved} discovery frazių lieka aiškiai nepatvirtinti kandidatai. Related keywords yra vendor stebėjimai, H2 – redakcinės sąvokos. Komercinių šeimos frazių apimtys neperduotos informaciniams primary.</p><p>Vienas privatus registracijos straipsnis su vaizdu parengtas. Istorinis receipt neperrašytas. 303→295 private studio planų migracija dar netaikyta; masinis rašymas ir naujas release neatlikti.</p><p>Naujas viešas resolveris ir tikrintas procedūros–miesto puslapis grąžino404. Planuotos CTA lieka neaktyvios. Nauja mokama tyrimo kaina0USD.</p><p><a href="SEO_CORE_REVIEW.md">Visa peržiūra ir vykdymo ribos</a> · <a href="SEMANTIC_REVIEW.json">300 pradinio žemėlapio sprendimai</a> · <a href="RESEARCH_IMPORT_MANIFEST.json">Private research import kvitas</a></p>`));
const html=`<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Madbeauty · galutinis viso katalogo turinio planas</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f2ed;color:#252733;font:16px/1.6 system-ui,sans-serif}a{color:#9e4164;overflow-wrap:anywhere}header{background:#252733;color:white;padding:44px max(24px,calc((100vw - 1120px)/2))}header p{max-width:870px;color:#e5dce0}h1{font:600 clamp(32px,4.7vw,58px)/1.12 Georgia,serif}h2{font:600 29px/1.2 Georgia,serif}h3{font-size:18px;margin-top:24px}.eyebrow{font-size:12px;letter-spacing:.1em;text-transform:uppercase}.stats{display:flex;flex-wrap:wrap;gap:12px}.stat{padding:14px 18px;background:#393946;border:1px solid #635761;border-radius:8px}.stat b{display:block;font-size:28px}.stat span{font-size:13px}nav{display:flex;gap:18px;flex-wrap:wrap;padding:16px 24px;background:white}main{max-width:1168px;margin:auto;padding:28px 24px 50px}section{background:white;padding:28px;margin:0 0 32px;border:1px solid #ddd7d2;border-radius:12px;scroll-margin-top:16px}.notice{background:#f7edf0;border-left:3px solid #9e4164;padding:12px 16px;font-size:14px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;border-bottom:1px solid #ddd7d2;vertical-align:top;text-align:left}th{background:#eee7e3}small{display:block;color:#656473;font-size:12px}.controls{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:12px;margin-bottom:18px}.controls label{font-size:13px}input,select,button{font:inherit;padding:10px;border:1px solid #beb6b5;border-radius:6px;width:100%;background:white;color:#252733}button{width:auto;cursor:pointer;background:#252733;color:white}.topic{border:1px solid #ddd7d2;border-radius:8px;margin:10px 0;scroll-margin-top:16px}.topic[open]{border-color:#9e4164}summary{cursor:pointer;padding:16px;display:block}summary:before{content:'＋';float:right;color:#9e4164}details[open]>summary:before{content:'−'}summary strong{display:block;font-size:17px;margin-right:20px}summary span{font-size:12px;color:#9e4164}.brief{padding:0 20px 20px;overflow-wrap:anywhere}.brief li{margin:7px 0}.topic[hidden]{display:none}.source{padding:12px 0;border-bottom:1px solid #ddd7d2}footer{font-size:13px;color:#656473}@media(max-width:720px){header{padding:28px 20px}main{padding:20px 12px}section{padding:20px 16px}.controls{grid-template-columns:1fr 1fr}.controls label:first-child{grid-column:1/-1}.stat{flex:1;min-width:125px}.brief{padding:0 14px 16px}}@media print{.controls,nav,button{display:none}header{background:white;color:black}header p{color:black}details{break-inside:avoid}}
</style></head><body><header><div class="eyebrow">Privatus redakcinis planas · atnaujintas 2026-10-07</div><h1>Visas Madbeauty katalogas.<br>Šešių mėnesių turinio planas.</h1><p>2026-10-06–2027-04-06. Visos 225 procedūros turi konkretų atsakymo adresą ir skyrių. Pagrindinė aprėptis rengiama spalį–lapkritį; vėliau — sezonai ir rezultatų peržiūros.</p><div class="stats">${[[p.pages.length,'nauji straipsnių planai'],[225,'sutikrintos procedūros'],[33,'redakcinės kryptys'],[p.links.length,'suplanuotos nuorodos'],[p.sources.length,'turinio šaltiniai']].map(([n,t])=>`<div class="stat"><b>${n}</b><span>${e(t)}</span></div>`).join('')}</div><p>${p.pages.length} nauji gidai + 3 esamų gidų atnaujinimai. 21 sritis ir 59 grupės. Be savaitinių straipsnių kvotų.</p></header><nav>${[['strategy','Strategija'],['coverage','Aprėptis'],['calendar','Datos'],['keywords','Raktažodžiai'],['topics','Straipsniai'],['procedures','225 procedūros'],['links','Nuorodos'],['sources','Šaltiniai']].map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><main>${sections.join('\n')}<footer>PLAN.json — visas brief. batches/ — V1 planavimo projekcijos; tikri studijos ID ir V2 susiejimas tikrinami prieš tekstų importą.</footer></main><script>
const cards=[...document.querySelectorAll('.topic')],filters=['search','family','category','wave'].map(id=>document.getElementById(id));
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function apply(){const [q,f,c,w]=filters.map(el=>norm(el.value));let n=0;for(const el of cards){el.hidden=Boolean(q&&!norm(el.dataset.search).includes(q)||f&&norm(el.dataset.family)!==f||c&&el.dataset.category!==c||w&&norm(el.dataset.wave)!==w);if(!el.hidden)n++;}document.getElementById('count').textContent='Rodoma '+n+' iš '+cards.length+' temų';}
for(const el of filters)el.addEventListener(el.id==='search'?'input':'change',apply);
document.getElementById('reset').addEventListener('click',()=>{filters.forEach(el=>el.value='');apply();});
document.getElementById('expand').addEventListener('click',()=>cards.filter(el=>!el.hidden).forEach(el=>el.open=true));
for(const a of document.querySelectorAll('.topic-link'))a.addEventListener('click',()=>{filters.forEach(el=>el.value='');apply();const target=document.getElementById(a.hash.slice(1));if(target)target.open=true;});
</script></body></html>`;
writeFileSync(new URL('MADBEAUTY-TOPICAL-AUTHORITY-PLANAS.html',import.meta.url),html);console.log(`Rendered ${p.pages.length} briefs and ${p.procedureCoverage.length} decisions.`);
