// Results-format review of already acquired samples. No live or paid queries.
import {readFileSync,writeFileSync} from 'node:fs';
import {normalize} from './keyword-seeds.mjs';
const dir=new URL('./',import.meta.url),s=JSON.parse(readFileSync(new URL('SERP_REVIEW.json',dir),'utf8'));
const formats={1:'providers, local catalogues, design inspiration',2:'DIY instructions, retail education, salons',3:'retail tools, visual inspiration, nail services',4:'salons and local catalogues',5:'salons, directories and training outlier',6:'DIY retail advice and salons',7:'DIY products, social tutorials, method explanation and providers',8:'providers and method explanations',9:'provider directories, medical and relaxation offers',10:'clinics and local providers',11:'method explanation, products and providers',12:'event hair providers and directories',13:'providers, retail products and price aggregators',14:'DIY articles and providers',15:'clinics and method explanations',16:'cosmetics retail and makeup providers',17:'body treatment providers',18:'piercing providers and price menus',19:'barber providers and bundled offers',20:'hotels, overnight travel and day spa services',21:'pigmentation providers, explanations and social images',22:'tattoo studios, inspiration, definitions and temporary retail products',23:'clinical providers and method explanations',24:'hair extension providers and social/listing pages',25:'paraffin providers and thermal health claims',26:'spray tan providers and retail explanations',27:'definitions, classes and reformer formats',28:'health providers and education/university pages',29:'psychological service providers',30:'definitions, audio/video and wellbeing sessions',31:'dental clinics and before/after care articles',32:'medical specialist providers',33:'grooming providers and home/service comparison',53:'Japanese manicure providers and explanation',54:'method comparison, commercial service pages and forum discussion',55:'hair preparation articles, provider advice and social/video pages',56:'care/duration explanation and provider pages',57:'benefit/boundary articles and clinical/provider blogs',58:'provider prices, listing pages and enquiries',59:'couples packages, day spa and hotel/travel explanations',60:'equipment/commercial advice, clinics and method explanations'};
const reviews=s.queries.map(q=>{const n=Number(q.file.match(/\d+/)[0]);return{query:q.query,file:q.file,callId:q.callId,observedAt:q.observedAt,reviewedAt:'2026-10-07',country:'LT',locationCode:2440,language:'lt',device:'desktop',returnedRows:q.items.length,observedFormats:formats[n]??'local procedure providers, catalogues and social/listing pages',role:n>=34&&n<=52?'LOCAL_CATALOGUE_READER_JOB':n===20||n===59?'MIXED_DAY_SPA_AND_TRAVEL_SCOPE':n>=54&&n<=57?'INFORMATIONAL_GUIDE_WITH_COMMERCIAL_MIX':'NATIONAL_SERVICE_OR_MIXED_DISCOVERY',evidence:q.items.map(x=>({url:x.url,title:x.title,rankGroup:x.rankGroup,rankAbsolute:x.rankAbsolute})),limitation:'Returned titles/URLs and known page formats inspected. Destination body not read in this SERP review; no health facts, service availability or Madbeauty ranking inferred.'};});
const pairs=[['manikiūras','gelinis lakavimas'],['manikiūras','japoniškas manikiūras'],['permanentinis makiažas','permanentinis makiažas pliusai ir minusai'],['spa','spa poroms'],['moterų kirpimas','moterų kirpimas vilniuje'],['gelinis lakavimas','gelinis lakavimas vilniuje'],['antakių laminavimas','antakių laminavimas kiek laikosi'],['plaukų priauginimas','plaukų priauginimas kaina']];
const clean=v=>{const u=new URL(v);for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_'))u.searchParams.delete(k);u.hash='';return u.href;};
const overlaps=pairs.map(([a,b])=>{const qa=s.queries.find(x=>normalize(x.query)===normalize(a)),qb=s.queries.find(x=>normalize(x.query)===normalize(b));if(!qa||!qb)throw Error('Missing observed pair');const aa=new Set(qa.items.map(x=>clean(x.url))),bb=new Set(qb.items.map(x=>clean(x.url))),common=[...aa].filter(x=>bb.has(x)),union=new Set([...aa,...bb]);return{a:qa.query,b:qb.query,aFile:qa.file,bFile:qb.file,aCount:aa.size,bCount:bb.size,intersection:common.length,union:union.size,jaccard:common.length/union.size,commonUrls:common,interpretation:'Bounded same-country/device original samples; explicit city and reader question can change results. No universal merge/split threshold and no proof for unqueried article pairs.'};});
writeFileSync(new URL('SERP_INTENT_REVIEW.json',dir),JSON.stringify({reviewedAt:'2026-10-07',status:'REUSED_RESULT_FORMAT_REVIEW_NOT_NEW_SAMPLE',queries:reviews,overlaps,paidUsd:0},null,2)+'\n');
console.log(JSON.stringify({reviewedSamples:reviews.length,observedPairs:overlaps.length,newPaidUsd:0}));
