// Authored reader jobs, not keyword combinations. Each row defines its own answer and contribution.
// key | title/question | dimensions | wave | three topic-specific sections | original deliverable | remaining evidence
export const categories = [
{id:'manikiuras',name:'Manikiūras',code:'MN',sources:['S01','S02','S08'],rows:`
gidas|Manikiūro gidas: metodai, eiga ir paslaugos pasirinkimas|Q,S,E|1|Nagų ir odelių sutvarkymas;Dangos pasirinkimas atskirai;Vizito eiga nuo įvertinimo iki užbaigimo|Paslaugos komponentų schema: priežiūra, padengimas, nuėmimas|Manikiūro specialisto patikrintas eigos aprašymas
klasikinis-aparatinis-kombinuotas|Klasikinis, aparatinis ir kombinuotas manikiūras: kuo skiriasi?|A,S|2|Kas atlieka odelių tvarkymą;Metodų derinimas;Ko metodo pavadinimas nepasako apie higieną|Trijų metodų palyginimas pagal veiksmus, ne pažadėtą saugumą|Tikslūs metodų apibrėžimai ir meistro peržiūra
be-lakavimo|Manikiūras be lakavimo: kas atliekama ir kokio rezultato tikėtis?|Q,E|1|Nagų forma ir paviršius;Odelių sutvarkymas;Kas nėra spalvinė danga|Originali nagų priežiūros komponentų iliustracija|Tikro meniu apimties patvirtinimas
ar-gelinis|Manikiūras ir gelinis lakavimas: kuo skiriasi paslaugos?|A,S|1|Priežiūra ir padengimas;Vienas ar kombinuotas pasiūlymas;Pasirinkimas esant senai dangai|Sprendimų medis pagal norimą rezultatą|Produktų sistemos termino patikra
express|Express ar pilnas manikiūras: kaip palyginti darbų apimtį?|A,C|2|Sutrumpinto vizito komponentai;Nuėmimas ir dizainas;Ką palyginti vienodomis sąlygomis|Dviejų datuotų pasiūlymų komponentų palyginimas|Du naujai patikrinti LT meniu; jokio LT kainų vidurkio
trukme|Kiek trunka manikiūras ir kas prailgina vizitą?|C|1|Priežiūros laikas;Nuėmimas ir papildomi darbai;Vizito trukmė bei atvykimo rezervas|Laiko sudėties schema be universalaus minučių pažado|Datuoti pasiūlymai ir tikro meistro eigos patikra
pasiruosimas|Kaip pasiruošti manikiūrui: esama danga ir norimas rezultatas|P|3|Dangos istorija;Forma ir kasdienė veikla;Ką perduoti prieš vizitą|Užpildoma pradinės būklės kortelė|Produkto instrukcija jei siūloma konkreti priežiūra
odeles|Odelių priežiūra: kuo skiriasi salono darbas ir kasdienė priežiūra?|R,H|3|Odelių paskirtis;Kosmetinės priežiūros ribos;Kai oda pažeista ar uždegusi|Kasdienės priežiūros ir atidėto vizito situacijų lentelė|AAD ir kvalifikuota sveikatos peržiūra; be DIY kirpimo
ziema|Rankų ir nagų priežiūra žiemą: odos sausumas ir danga|R|3|Drėkinimas ir įpročiai;Dangos tausojimas;Kada nepakanka kosmetinės priežiūros|Rutinos kortelė pagal odą ir dangą|Dermatologinio šaltinio ir teiginių patikra
pakartotinis-vizitas|Pakartotinis manikiūras ar korekcija: priežiūros vizitas ir defekto taisymas|R,C|4|Reguliari kosmetinė priežiūra;Dangos defekto korekcija;Skirtingų vizitų apimtis|Dviejų paslaugų užduočių palyginimas be universalaus vizitų intervalo|Tikro teikėjo sąlygos ir metodo priežiūros protokolas
pazeidimas|Po manikiūro pažeistas nagas ar danga: kokia pagalba reikalinga?|H|5|Kosmetinis defektas ir sveikatos požymiai;Ką užfiksuoti;Meistras ar sveikatos specialistas|Aiškiai apribotas veiksmų kelias be diagnozių|Sveikatos specialisto peržiūra privaloma
higiena|Manikiūro įrankių higiena: dezinfekcija, sterilizacija ir vienkartinės priemonės|H,E|3|Terminų skirtumas;Įrankio paskirtis ir apdorojimas;Ką reiškia UV spintelė|NVSC teiginių paaiškinimas pagal situaciją|S11,S20 aktualumas; ne sterilizavimo instrukcija
`},
{id:'gelinis-lakavimas',name:'Gelinis lakavimas',code:'GL',sources:['S01','S02','S07','S14'],rows:`
gidas|Gelinio lakavimo gidas: kas tai, kaip atliekamas ir kaip prižiūrėti|Q,E,S|1|Danga ir natūralus nagas;Padengimo etapai;Rezultato ir priežiūros ribos|Dangos sluoksnių iliustracija, ne procedūros mokymas|Konkrečios sistemos gamintojo protokolas ir meistro peržiūra
ar-stiprinimas|Gelinis lakavimas, nagų stiprinimas ir priauginimas: trys skirtingi rezultatai|A,S|2|Spalvos danga;Papildoma konstrukcija;Ilgio kūrimas|Paslaugos pasirinkimo matrica pagal rezultatą|Meistro terminų patikra; stiprinimas nėra nago gydymas
baze|Ką reiškia bazė ir nago išlyginimas gelinio lakavimo pasiūlyme?|Q,C|2|Bazės paskirtis sistemoje;Išlyginimas ir konstrukcija;Kas įeina į kainą|Sluoksnių ir kainyno komponentų schema|Konkretaus produkto instrukcija; ne universalus tinkamumas
nuemimas|Gelinio lako nuėmimas: atskira paslauga ar naujo padengimo dalis?|C,E|1|Žinoma ir nežinoma danga;To paties ar kito meistro darbas;Nuėmimo ir padengimo paketas|Trijų pradinių situacijų palyginimas|Nuėmimo protokolas; jokios universalaus tirpiklio ar frezos instrukcijos
pasiruosimas|Prieš gelinį lakavimą: kokią informaciją apie nagus ir seną dangą perduoti?|P|3|Ankstesnė sistema;Praėjusio darbo istorija;Kasdienė veikla ir ilgis|Perdavimo kortelė su „nežinau“ pasirinkimu|Specialisto apžiūros ir ankstesnių reakcijų patikra
kaina-trukme|Gelinio lakavimo kaina ir trukmė: nuėmimas, bazė bei dizainas|C|1|Kainos sudėtis;Skirtinga pradinė danga;Papildomi dizaino darbai|Datuotų pasiūlymų palyginimas su vienoda apimtimi|Nauji meniu prieš tekstą; ne bendras rinkos kainų intervalas
laikymasis|Nuo ko priklauso gelinio lakavimo laikymasis ir kodėl nėra vieno termino?|R,C|3|Pradinė būklė ir sistema;Kasdieniai įpročiai;Korekcijos intervalas nėra garantija|Veiksnių schema atskiriant pažadą nuo orientyro|Sistemos gamintojo duomenys; jokių išgalvotų 3–4 sav. garantijų
papildymas|Gelinių nagų papildymas ar pilnas nuėmimas: konstrukcijos ir paslaugos skirtumas|A,C|4|Esama konstrukcija ar tik spalvinė danga;Papildymo ir naujo darbo apimtis;Kito meistro sistemos informacija|Paslaugos komponentų lentelė atskiriant dangą nuo konstrukcijos|Konkrečios sistemos ir meistro protokolas; ne papildymo instrukcija
prieziura|Kaip prižiūrėti gelinę dangą ir kodėl jos nekrapštyti?|R|3|Tausojantys įpročiai;Nuėmimo planas;Kosmetinės priežiūros ribos|Trumpa priežiūros kortelė su šaltinio ribomis|S07 ir naudojamos sistemos priežiūros instrukcija
atsokimas|Atskilusi ar atšokusi gelinė danga: ką daryti ir ko nedaryti?|H|5|Dangos defektas;Skausmas ar pakitusi oda;Kaip perduoti situaciją ir gauti pagalbą|Meistro ir sveikatos specialisto pagalbos ribų lentelė|Sveikatos peržiūra; be klijavimo ar gydymo namuose
led-uv|UV ir LED nagų lempos: ką reiškia šie pavadinimai?|Q,H|5|Šviesos šaltinis ir spinduliuotė;Ko LED terminas negarantuoja;Atsargumo informacija|Terminų schema be individualios rizikos skaičiavimo|AAD ir konkretaus įrenginio dokumentacija
tpo-hema|TPO ir HEMA nagų produktuose: taisyklės ir HEMA-free žymos ribos|H,Q|5|Skirtingos medžiagos;ES draudimas ir naudojimo apribojimai;Kodėl viena žyma neįrodo hipoalergiškumo|Dviejų medžiagų teiginių lentelė su teisės aktų datomis|S12,S13,S22; aktualus 1223/2009 priedas ir kvalifikuota peržiūra
alergines-reakcijos|Galima reakcija į nagų kosmetiką: kada kreiptis į sveikatos specialistą?|H|5|Reakcijos ne visada tik prie nago;Kodėl patys nenustatome alergeno;Kosmetinio vizito ir pagalbos riba|Pagalbos orientyras be diagnostinio testo|S41 ir sveikatos specialisto peržiūra
`},
{id:'nagu-dizainas',name:'Nagų dizainas',code:'ND',sources:['S01','S18','S23'],rows:`
gidas|Nagų dizaino gidas: forma, spalva, technika ir darbo apimtis|Q,S,E|1|Dizainas nėra dangos tipas;Forma ir akcentai;Technikos bei darbų skaičius;Dizaino užduoties patvirtinimas ir darbo eiga|Originali keturių sprendimų dizaino schema|Originalūs vaizdai ir meistro technikų patikra
forma-ilgis|Nagų forma ir ilgis: ovalas, migdolas, kvadratas ir kasdieniai poreikiai|S|2|Formų kontūrai;Laisvo krašto ilgis;Kasdienės veiklos kompromisai|Vienodo mastelio originalūs kontūrų brėžiniai|Meistro anatominių teiginių patikra; nėra universalios idealios formos
trumpi|Trumpų nagų dizainas: kaip keičiasi proporcijos ir akcento vieta?|S|2|Trumpa plokštelė;Detalės dydis;Ilgo dizaino adaptacija|Trys originalios iliustracinės adaptacijos|Vaizdų pikselių patikra, ne tikri klientų rezultatai
prancuziskas|Prancūziškas manikiūras: linijos plotis, bazė ir variacijos|Q,A|2|Klasikinė linija;Micro French ir spalvinė linija;Skirtumas nuo vientisos dangos|Vienodos formos originalių variantų palyginimas|Meistro technikos ir originalių vaizdų patikra
ombre|Ombré ir baby boomer nagai: kuo skiriasi rezultatas?|A|2|Spalvų perėjimas;Švelnaus balto perėjimo variantas;Forma ir kontrastas|Dviejų iliustracinių perėjimų brėžinys|Terminų ir atlikimo variantų patikra; ne universalus metodas
chrome-cat-eye|Chrome ir cat-eye nagai: du skirtingi šviesos efektai|A|2|Atspindintis paviršius;Magnetinės linijos efektas;Kaip vertinti vaizdą judant|Originalios schemos ir teikėjo leistas trumpas tikro efekto vaizdas|Gamintojo technikos aprašai; tikro video leidimas dar negautas
matinis-blizgus|Matinis ar blizgus paviršius: kaip skiriasi tas pats nagų dizainas?|A,R|3|Paviršiaus atspindys;Spalvos suvokimas;Priežiūra pagal naudojamą viršutinį sluoksnį|To paties iliustracinio dizaino pora|Konkretaus top produkto priežiūra; AI nėra dėvėjimo testas
akcentai-kaina|Nagų dizaino kaina: akcentų skaičius, technika ir nuėmimas|C|1|Kurie nagai dekoruojami;Darbo sudėtingumas;Vienodos pasiūlymo sąlygos|10 nagų žymėjimo kortelė ir apimties palyginimas|Aktualūs teikėjų meniu ir patvirtinta apimtis
nuotrauka|Dizaino nuotrauka meistrui: kaip aprašyti adaptaciją ir neįmanomas detales?|P|3|Kas nuotraukoje patinka;Forma ir ilgis realybėje;Kuriuos elementus keisti|Užpildomas briefas su iliustraciniu adaptacijos pavyzdžiu|Meistro įvertinimas; nuotraukos teisės ir tikra technikos patikra
apsvietimas|Kodėl nagų spalva ekrane, dienos šviesoje ir salone atrodo kitaip?|R,H|3|Apšvietimas ir baltos spalvos balansas;Skaidrumas ir pagrindas;Spalvos pavyzdžio patvirtinimas|Originalus kontroliuotas spalvos demonstravimas su metodika|Tikras demonstravimas dar neatliktas; S23 ne mūsų bandymo rezultatas
`},
{id:'pedikiuras',name:'Pedikiūras',code:'PD',sources:['S32','S08','S11'],rows:`
gidas|Pedikiūro gidas: pėdų priežiūra, nagų sutvarkymas ir lakavimas|Q,S,E|1|Trys darbų komponentai;Be dangos ar su danga;Vizito eiga ir sveikatos ribos|Pėdų ir nagų paslaugos apimties schema|Pedikiūro specialisto eigos patikra
aparatinis-klasikinis|Aparatinis ir klasikinis pedikiūras: metodas ir darbų apimtis|A,S|2|Odai ir nagams skirti darbai;Įrankių naudojimas;Metodas nepakeičia higienos|Komponentų palyginimas vietoj „saugesnio metodo“ pažado|Specialisto apibrėžimai ir NVSC teiginių patikra
rugstinis|Rūgštinis pedikiūras: ką reiškia pavadinimas ir ko klausti apie priemonę?|Q,A|2|Priemonės vaidmuo;Nagų ir odos priežiūra atskirai;Kas priklauso nuo produkto|Priemonės, metodo ir paslaugos sudėties schema|Konkretaus produkto instrukcija; ne DIY rūgšties naudojimas
be-lakavimo|Pedikiūras be lakavimo: ko tikėtis iš priežiūros vizito?|S,E|1|Nagų sutvarkymas;Pėdų odos darbai;Kas nepatenka į pasirinktą variantą|Dviejų meniu variantų palyginimas|Aktualus realių pasiūlymų patikrinimas
gelinis-ar-paprastas|Gelinis ar paprastas kojų nagų lakavimas: skirtumai renkantis paslaugą|A,R|2|Dangos tipas;Nuėmimas;Priežiūra ir vizito planas|Dangos ir nuėmimo pasirinkimų lentelė|Gamintojų protokolai; jokio universalaus laikymosi pažado
kaina-trukme|Pedikiūro kaina ir trukmė: pėdos, nagai, danga bei nuėmimas|C|1|Pėdų priežiūros apimtis;Senos dangos nuėmimas;Komplektas ar priedai|Normalizuota dviejų realių pasiūlymų sudėtis|S32 perpatikrinti prieš rašymą
pasiruosimas|Kaip pasiruošti pedikiūrui: danga, avalynė ir svarbi pradinė informacija|P|3|Sena danga;Po vizito planuojama veikla;Ką pasakyti apie odą ir nagus|Pradinės būklės ir vizito planavimo kortelė|Avalynės taisyklės tik pagal naudojamą dangą
prieziura|Priežiūra po pedikiūro: oda ir nagų danga turi skirtingus poreikius|R|3|Odos priežiūros rutina;Dangos priežiūra;Kada kreiptis dėl pokyčių|Dvi atskiros priežiūros kortelės|Produkto instrukcija ir sveikatos teiginių review
kosmetinis-ar-sveikatos|Kosmetinis pedikiūras ar sveikatos konsultacija: kur paslaugos riba?|H,S|5|Kosmetinės priežiūros paskirtis;Skausmas ir įtartini pokyčiai;Kompetencijos patikrinimas|Pagalbos maršrutas be nuospaudų ar ligų diagnozavimo|LT veiklos kvalifikacijos ir sveikatos specialisto review
pazeista-oda|Pažeista pėdų oda ar pakitęs nagas: kada grožio vizitą atidėti?|H,P|5|Kodėl nuotrauka nėra diagnozė;Paslaugos atidėjimas;Sveikatos konsultacija ir komunikacija|Aiškiai apribota atidėjimo atmintinė|S08 ir kvalifikuota medicininė peržiūra
abi-paslaugos|Manikiūras ir pedikiūras vienu vizitu: laikas, darbuotojai ir paketo apimtis|C,P|4|Vienas ar keli specialistai;Nuoseklus ar lygiagretus darbas;Ką patvirtinti pasiūlyme|Vizito laiko schema be fiktyvaus sutaupymo skaičiaus|Tikro teikėjo darbo organizavimas
`},
{id:'kirpimas',name:'Kirpimas',code:'KR',sources:['S04','S33','S34','S43'],rows:`
gidas|Kirpimo gidas: forma, plaukų tekstūra ir paslaugos eiga|Q,S,E|1|Ko tikėtis iš konsultacijos;Forma ir tekstūra;Kirpimas bei užbaigimas|Kirpimo sprendimo schema, ne veido formų stereotipai|Kirpėjo peržiūra ir eigos patikra
galiukai-ar-forma|Galiukų pakirpimas ar nauja kirpimo forma: skirtingos užduotys|A,S|2|Išlaikoma forma;Ilgio ir svorio pokytis;Paslaugos apimtis|Dviejų iliustracinių priešužduočių schema|Kirpėjo paaiškinimas; ne AI before/after rezultatas
sluoksniai|Sluoksniuotas kirpimas: kas keičiasi plaukų formoje ir priežiūroje?|Q,S|2|Ilgių paskirstymas;Judėjimas ir apimtis;Kasdienis formavimas|Originalus sluoksnių brėžinys|Kirpėjo peržiūra pagal skirtingą tekstūrą
bob-kare|Bob ir carré kirpimai: ką tiksliai parodyti nuotraukoje?|A,S|2|Ilgio orientyrai;Kontūro ir sluoksnių skirtumai;Terminų vartojimo variacijos|Vienodos pozicijos kontūrų iliustracijos|Terminai gali persidengti; meistro review
kirpciukai|Kirpčiukai: ilgis, forma ir kasdienė priežiūra prieš apsisprendžiant|S,R|2|Trumpesnė forma prie veido;Augimo kryptis;Formavimo poreikis|Kirpčiukų užduoties ir priežiūros matrica|Kirpėjo vertinimas; ne garantija pagal veido tipą
garbanoti|Garbanotų plaukų kirpimas: natūrali tekstūra, susitraukimas ir vizito ruošimas|S,P|4|Tekstūra natūraliai;Sauso ar drėgno darbo metodas;Ką meistras turi pamatyti|Tekstūros ir pasiruošimo klausimų kortelė|Konkretaus kirpėjo protokolas; ne visiems vienodas plovimas
ploni|Plonų ar retesnių plaukų kirpimas: vizualios apimties pasirinkimai|S|4|Plauko storis ir tankis nėra tas pats;Kontūras ir sluoksniai;Ko kirpimas nepakeičia|Dvi skirtingų pradinių situacijų iliustracijos|Kirpėjo review; plaukų slinkimo gydymas už apimties
trumpas-vyriskas|Trumpas kirpimas: mašinėlės ilgis, kontūras ir perėjimas|Q,S|2|Ilgio orientyrai;Perėjimo aukštis;Kontūras ir užbaigimas|Originalus zonų žemėlapis bei ilgio užduotis|Kirpėjo techninių terminų patikra
vaikui|Vaiko kirpimas: pasiruošimas, paslaugos apimtis ir komfortas|P,S|4|Vaiko amžiaus ir patirties informacija;Vizito trukmė ir pertraukos;Globėjo dalyvavimas|Pirmo vizito komforto planas|Tikro teikėjo amžiaus/sąlygų patikra; nėra vienodų salonų taisyklių
kaina-trukme|Kirpimo kaina ir trukmė: konsultacija, plovimas bei sušukavimas|C|1|Kas įskaičiuota;Ilgis ir pasirinkta forma;Atskiri papildomi darbai|Datuotų vienodos apimties pasiūlymų palyginimas|S33,S34 aktualūs meniu
pasiruosimas|Kaip pasiruošti kirpimui ir ar prieš vizitą plauti plaukus?|P|3|Įprastas formavimas;Tekstūros vertinimas;Teikėjo pasirinkto metodo instrukcija|Pasiruošimo matrica pagal sutartą darbo metodą|Kirpėjo konkretus protokolas; nėra universalaus „neplauti“
nuotrauka|Kirpimo nuotrauka: kaip sutarti ilgį, kontūrą ir norimą pokytį?|P|3|Kas patinka nuotraukoje;Kiek ilgio palikti;Kas priklauso nuo tekstūros ir formavimo|Užpildoma užduotis su ilgio žymėjimo schema|Originali nuotrauka/brėžinys, teisės dar tikrintinos
prieziura|Kirpimo priežiūra namuose: formavimas pagal plaukų tekstūrą|R|3|Natūralus džiovinimas;Formavimo priemonės ir karštis;Kada tikslinti kirpimo užduotį|Dviejų tekstūrų priežiūros scenarijai|S43 ir kirpėjo review; ne ligų gydymas
nepavyko|Nepatinkantis kirpimas: formos patikslinimas, komunikacija ir paslaugos ginčas|H|4|Pradinis susitarimas;Ką galima aptarti korekcijai;Kada aktualus vartotojo kreipimasis|Korekcijos užklausos pavyzdys su faktų laiko juosta|S19 ir kirpėjo realių korekcijos ribų review
`},
{id:'plauku-dazymas',name:'Plaukų dažymas',code:'DZ',sources:['S04','S33','S34','S09','S10','S42'],rows:`
gidas|Plaukų dažymo gidas: spalva, technika ir ankstesnio dažymo istorija|Q,S,E|1|Spalva ir pašviesinimas;Darbų zonos;Konsultacija ir realios pokyčio ribos|Dažymo sprendimų medis pagal pradinę būklę|Dažymo specialisto ir konkrečių sistemų review
saknys-ar-visi|Šaknų ar visų plaukų dažymas: kada keičiasi darbų apimtis?|A,S|2|Ataugusi zona;Ilgiai ir galai;Spalvos suvienodinimas atskirai|Zonų schema su trimis užduotimis|Spalvos specialisto peržiūra
sruogos|Dažymas sruogomis: dalinis, visas ir prie veido|Q,A|2|Darbų zonos;Šviesinimas ir tonavimas;Kainyno skirtingi paketai|Originalus zonų ir įtrauktų darbų žemėlapis|Gamintojo ir kirpėjo technikų apibrėžimai
balayage-airtouch|Balayage ir Airtouch: kuo skiriasi technika bei rezultato planavimas?|A,S|2|Spalvos paskirstymas;Sruogų atrankos principas;Ko nuotrauka ir pavadinimas nepasako|Dviejų metodų schema be „geresnės technikos“ pažado|Airtouch pirminė techninė dokumentacija ir meistro review dar reikalinga
ombre-sombre|Ombré, sombré ir balayage: rezultato pavadinimas ar darbo technika?|A|2|Perėjimo vieta;Kontrasto lygis;Pavadinimų persidengimas|Kontroliuotų iliustracijų palyginimas|Wella terminų ir kirpėjo peržiūra
tonavimas|Plaukų tonavimas: kam jis naudojamas ir kuo skiriasi nuo šviesinimo?|Q,A|2|Atspalvio koregavimas;Ko toneris savaime nepadaro;Sistemos skirtumai|Spalvos lygio ir atspalvio atskyrimo schema|Konkrečios dažų/tonerio sistemos dokumentai
sviesinimas|Plaukų šviesinimas: kodėl norimas pokytis gali būti kelių vizitų užduotis?|E,S|4|Pradinės spalvos istorija;Sruogos įvertinimas;Etapų ir rezultatų derinimas|Konsultacijos scenarijus su nepatvirtinto rezultato laukais|Kirpėjo review; ne receptas ar garantuotas vizitų skaičius
zili|Žilų plaukų dažymas: maskavimas, suvienodinimas ir natūralios spalvos perėjimas|S,A|4|Žilumo pasiskirstymas;Padengimo ir išsklaidymo tikslas;Ataugimo kontrastas|Trijų estetinių tikslų matrica|Konkrečios sistemos padengimo duomenys
korekcija|Plaukų spalvos korekcija: kuo ji skiriasi nuo įprasto dažymo?|Q,E|4|Ankstesnės spalvos;Netolygumo įvertinimas;Konsultacija ir etapų ribos|Korekcijos užduoties istorijos ruošinys|Meistro review; jokio naminio dažų šalinimo recepto
kaina-trukme|Plaukų dažymo kaina ir trukmė: ilgis, tankis, tonavimas bei kirpimas|C|1|Ilgis ir tankis;Dažymo komponentai;Konsultacijos pasiūlymas ir priedai|Vienodos apimties pasiūlymų lentelė|Naujai patikrinti S33,S34 meniu; ne rinkos vidurkis
istorija|Dažymo istorija prieš naują vizitą: ką perduoti spalvos specialistui?|P|3|Dažai ir ankstesnis šviesinimas;Namų produktai ir nežinoma informacija;Norimas pokytis|Chronologinė dažymo kortelė su „nežinau“ laukais|Konkretaus specialisto duomenų poreikio patikra
testai|Alergijos įspėjimo ir sruogos testai prieš dažymą: skirtinga paskirtis|H,P|5|Reakcijos įspėjimo testas;Sruogos rezultato įvertinimas;Instrukcija ir ankstesnės reakcijos|Testų paskirties lentelė be savarankiško diagnostinio testo|S09,S10 aktuali produkto instrukcija; sveikatos review
pasiruosimas|Kaip pasiruošti plaukų dažymui: nuotraukos, plovimas ir vizito diena|P|3|Nuotraukos vienodu apšvietimu;Produkto ir teikėjo instrukcija;Darbų apimtis vizito dieną|Vizito pasiruošimo kortelė|Jokios universalios 24–48 h neplovimo taisyklės be sistemos
prieziura|Dažytų plaukų priežiūra: plovimas, formavimas ir spalvos palaikymas|R|3|Naudota sistema;Plovimo ir karščio įpročiai;Tolimesnis tonavimo/šaknų vizitas|Palaikymo planas atskiriant namų priežiūrą nuo salono darbo|Naudotos sistemos instrukcija ir S43
spalva-nuotraukoje|Kodėl plaukų dažymo rezultatas nuotraukoje ir realybėje gali skirtis?|S,H|4|Šviesa ir baltos spalvos balansas;Pradinė bazė;Retušas ir rezultato dokumentavimas|Originalus spalvos fiksavimo metodikos pavyzdys|S23 ir tikras demonstravimas, ne AI „rezultatas“
reakcija|Reakcija po plaukų dažymo: kada grožio konsultacijos nepakanka?|H|5|Kosmetinis nepasitenkinimas ir sveikatos požymiai;Ką pasakyti apie produktą;Kur kreiptis pagalbos Lietuvoje|Pagalbos kelias be diagnozės ir JK numerių perkėlimo|S09 ir LT sveikatos specialisto review
`},
{id:'antakiai',name:'Antakių priežiūra',code:'AN',sources:['S03','S24','S35'],rows:`
gidas|Antakių priežiūros gidas: korekcija, dažymas ir laminavimas|Q,S,E|1|Forma ir spalva;Plaukelių kryptis;Paslaugų deriniai ir eiga|Trijų skirtingų estetinių tikslų schema|Antakių specialisto terminų ir eigos review
korekcija-ar-dazymas|Antakių korekcija ar dažymas: kuo skiriasi rezultatas?|A,S|1|Keičiama forma;Paryškinama spalva;Bendras paketas|Rezultato ir komponentų lentelė|Meniu ir specialisto patikra
metodai|Antakių korekcija pincetu, vašku ar siūlu: metodų skirtumai|A,S|2|Plaukelių pašalinimo būdas;Darbų zona;Kas priklauso nuo odos ir naudojamų produktų|Metodų palyginimas be universalaus saugumo reitingo|Pirminiai produkto/metodo dokumentai ir specialisto review
spalva|Antakių dažų spalva: ką reiškia norimas intensyvumas ir atspalvis?|S|2|Atspalvis ir intensyvumas;Plaukelio ir odos efektas;Apšvietimas ir pavyzdys|Originali atspalvio užduoties schema|Konkrečios dažų sistemos savybės, ne laboratorinis testas
dazai-henna|Antakių dažai ir henna: ką lyginti renkantis pasiūlymą?|A,R|2|Produkto sudėtis ir paskirtis;Plaukelio/odos spalva;Priežiūros instrukcijos|Sistemų palyginimas tik pagal patikrintus dokumentus|Konkrečių sistemų gamintojų šaltiniai dar reikalingi
laminavimas|Antakių laminavimas: kaip keičiama plaukelių kryptis ir kas įeina?|Q,E|2|Laminavimo paskirtis;Dažymas ir korekcija atskirai;Rezultato ribos|Procedūros komponentų schema, ne DIY mokymas|Konkrečios laminavimo sistemos protokolas
kaina-trukme|Antakių paslaugų kaina ir trukmė: korekcija, dažymas bei laminavimas|C|1|Atskiros paslaugos;Komponentų paketas;Papildomų darbų patvirtinimas|Vienodos apimties dviejų pasiūlymų palyginimas|S03,S35 meniu perpatikrinti
pasiruosimas|Prieš antakių procedūrą: ankstesni darbai, produktai ir pageidaujama forma|P|3|Esama forma ir ankstesnis dažymas;Naudojami produktai;Lūkesčiai bei reakcijų istorija|Pradinės informacijos kortelė|Sistemos saugos instrukcija; individualus tinkamumas ne iš straipsnio
prieziura|Priežiūra po antakių dažymo ir laminavimo: kodėl instrukcijos skiriasi?|R|3|Atlikta paslauga;Produkto instrukcija;Ko nepriskirti visoms sistemoms|Pagal sistemą pildoma priežiūros kortelė|Dabartinis konkretaus gamintojo protokolas dar reikalingas
permanentinis|Permanentinis antakių makiažas ir nauja korekcija: ką galima ir ko nespręsti iš nuotraukos?|P,S|4|Esamo pigmento istorija;Kosmetinis plaukelių darbas;Atskira pigmento korekcijos paslauga|Du paslaugos tikslus atskirianti užduotis|Specialisto review; pigmento šalinimo mokymas neįtrauktas
reakcija|Odos reakcija po antakių procedūros: kosmetinio vizito ir sveikatos pagalbos riba|H|5|Naudota priemonė ir atlikti darbai;Kodėl nedarome diagnozės;Kada reikalinga sveikatos pagalba|Pagalbos ir informacijos perdavimo atmintinė|Dermatologinis šaltinis ir sveikatos specialisto review
`},
{id:'blakstienos',name:'Blakstienų priežiūra',code:'BL',sources:['S24','S35','S36','S40'],rows:`
gidas|Blakstienų paslaugų gidas: dažymas, laminavimas ir priauginimas|Q,S,E|1|Natūrali blakstiena ir pridedamas plaukelis;Spalva ir kryptis;Skirtingų paslaugų eiga|Trijų tikslų ir darbų komponentų schema|Blakstienų specialisto eigos review
laminavimas-ar-priauginimas|Blakstienų laminavimas ar priauginimas: rezultatų ir priežiūros skirtumai|A,S|1|Natūralių plaukelių kryptis;Papildomi plaukeliai;Priežiūros ir papildymo skirtumai|Pasirinkimo matrica be universalaus tinkamumo išvados|Konkrečių sistemų dokumentai
laminavimas|Kaip atliekamas blakstienų laminavimas ir ko tikėtis iš rezultato?|Q,E|2|Konsultacija ir pasirinkta kryptis;Proceso principas;Dažymas kaip atskiras komponentas|Neprocedūrinė eigos iliustracija|S36 tik vienos sistemos šaltinis; meistro review
dazymas|Blakstienų dažymas: ką jis keičia ir ko nesuteikia?|Q,S|2|Spalvos paryškinimas;Ilgio ir tankio ribos;Kombinuoti paketai|Tikslų lentelė be išgalvoto tankinimo pažado|Dažų gamintojo instrukcija ir specialisto review
klasikinis-volume|Klasikinis ir volume priauginimas: ką reiškia 1D, 2D bei kiti pavadinimai?|A,S|2|Pridedamų plaukelių principas;Paslaugos apimtis;Individualaus parinkimo ribos|Terminų brėžinys, ne saugiausio metodo reitingas|Meistro terminų ir sistemos review
efektai|Natūralus, cat-eye ir doll-eye blakstienų efektas: kuo skiriasi išdėstymas?|S|2|Ilgio paskirstymas;Akcento vieta;Norimo rezultato apibūdinimas|Originalios vienodo mastelio išdėstymo schemos|Specialisto review; ne universali akies formos rekomendacija
papildymas-nuemimas|Blakstienų papildymas ar pilnas nuėmimas: kada keičiasi vizito užduotis?|C,E|2|Priauginimo būklė;Kito meistro darbas;Naujo rinkinio ir papildymo apimtis|Trijų pradinių situacijų lentelė|Konkretaus meistro sąlygos ir saugus profesinis nuėmimas
kaina-trukme|Blakstienų paslaugų kaina ir trukmė: naujas rinkinys, papildymas ir dažymas|C|1|Skirtingi metodai;Įtraukti komponentai;Laiko ir kainos pasiūlymas|Normalizuota realių pasiūlymų lentelė|S24,S35 perpatikrinti; ne LT vidurkis
pasiruosimas|Prieš blakstienų vizitą: ankstesnis darbas, kontaktiniai lęšiai ir kosmetika|P|3|Pradinė blakstienų būklė;Naudojamos priemonės;Instrukcija vizito dienai|Pagal teikėjo protokolą pildoma pasiruošimo kortelė|Kontaktinių lęšių/produkto saugos teiginiams kvalifikuota review
laminavimo-prieziura|Priežiūra po blakstienų laminavimo: ką lemia konkreti sistema?|R|3|Produkto instrukcija;Vanduo ir karštis pagal sistemą;Ko nepriskirti kiekvienam laminavimui|Datuota instrukcijos kortelė su sistemos pavadinimu|S36 tik Nouveau LVL; ne universali 24–48 h taisyklė
priauginimo-prieziura|Priaugintų blakstienų priežiūra: valymas, kosmetika ir papildymo planas|R|3|Sistemos valymo instrukcija;Kasdieniai įpročiai;Kosmetinio vizito ribos|Sistemai pritaikyta priežiūros kortelė|Konkrečių klijų/sistemos protokolas ir sveikatos review
akiu-reakcija|Akių ar vokų reakcija po blakstienų procedūros: kada reikalinga sveikatos pagalba?|H|5|Kosmetinis rezultatas ir sveikatos požymiai;Naudotų produktų informacija;Profesionalios pagalbos kelias|Atskirtos sveikatos pagalbos ir meistro užklausos situacijos|S40 ir sveikatos specialisto review; be naminio tirpiklio naudojimo
komplektas|Antakiai ir blakstienos kartu: kaip palyginti paketo apimtį bei laiką?|C,P|4|Keturi atskiri tikslai;Kas atliekama viename vizite;Priežiūros protokolai atskirai|Paketo komponentų lentelė|S03,S35 ir tikro teikėjo tvarka
`},
{id:'masazas',name:'Masažas',code:'MS',sources:['S25','S26','S28','S29','S37'],rows:`
gidas|Masažo gidas: kūno ir veido paslaugos, eiga bei kompetencijos ribos|Q,S,E|1|Estetinis ir sveikatos tikslas;Kūno zonos ir veidas;Vizito eiga bei komfortas|Masažo tikslų ir paslaugos apimties schema|Masažo specialisto eigos review; sveikatos ribos pagal LT
atpalaiduojantis-gydomasis|Atpalaiduojantis ir gydomasis masažas: skirtinga paskirtis ir kvalifikacija|A,H|5|Savijautos paslauga;Sveikatos paslauga;Specialisto ir įstaigos apimtis|LT kompetencijos tikrinimo kelias|S28,S29,S31 aktualūs reikalavimai ir kvalifikuota review
nugara-ar-kunas|Nugaros ar viso kūno masažas: zonos, apimtis ir seanso trukmė|A,C|1|Įtrauktos zonos;Darbo laikas ir visas vizitas;Komforto derinimas|Zonų ir laiko komponentų brėžinys|Tikro teikėjo meniu ir eigos review
stiprumas|Masažo spaudimo stiprumas: kaip suderinti komfortą ir lūkesčius?|S,E|2|Stiprumas nėra kokybės matas;Bendravimas seanso metu;Skausmo ir sveikatos klausimų riba|Komforto pokalbio scenarijus|S37 ir kvalifikuota review; be toleruoti skausmą rekomendacijos
veido-kobido|Veido masažas ir Kobido: terminai, zonos bei paslaugos sudėtis|Q,A|2|Veido masažo tikslas;Kobido pavadinimo vartojimas;Kaklas ir dekoltė kaip komponentai|Datuotų variantų apimties palyginimas|Kvalifikuoto teikėjo metodo dokumentai; ne liftingo pažadas
veido-ar-procedura|Veido masažas ar veido priežiūros procedūra: ką renkatės iš tikrųjų?|A,S|2|Rankų darbo komponentas;Valymas ir kosmetinės priemonės;Derinio sudėtis|Dvi komponentų schemos|S25,S27 ir kosmetologo/masažo specialisto review
kaina-trukme|Masažo kaina ir trukmė: darbo laikas, zonos bei papildomi komponentai|C|1|Seanso ir vizito laikas;Įtrauktos zonos;Priedai ir ritualai|Vienodos apimties realių pasiūlymų lentelė|S25,S26 meniu tikrinti iš naujo
pasiruosimas|Kaip pasiruošti pirmajam masažo vizitui: apranga, privatumas ir komfortas|P,E|3|Atvykimo ir aprangos informacija;Privatumas ir uždengimas;Komforto bei sveikatos informacijos ribos|Pirmo vizito situacijų atmintinė|Tikro teikėjo praktikos ir individualaus tinkamumo review
prieziura|Po masažo: realistiški savijautos lūkesčiai ir pagalbos ribos|R,H|3|Savijauta nėra gydymo įrodymas;Teikėjo instrukcijos;Neįprastų simptomų sveikatos vertinimas|Savijautos ir pagalbos ribų kortelė|S37 ir sveikatos specialisto review; be detox ar privalomų litrų
kada-konsultacija|Sveikatos klausimai prieš masažą: kada pirmiau reikalinga kvalifikuota konsultacija?|H,P|5|Ką pranešti apie būklę;Straipsnio tinkamumo ribos;Specialisto ir sveikatos pagalbos pasirinkimas|Informacijos perdavimo kortelė be diagnozių|NCCIH ir LT sveikatos specialisto review; ne kontraindikacijų savidiagnostika
kursas|Masažo kursas ar vienas seansas: kaip vertinti pasiūlymą be rezultato garantijų?|S,C|4|Paslaugos tikslas;Paslaugų skaičiaus pagrindimas;Komercinio paketo sąlygos|Paketo pasiūlymo vertinimo lentelė|Teikėjo faktiškai siūlomo paketo informacija; S37 nerodo universalaus kurso
teiginiai|Kobido, limfodrenažas ir „detox“: kaip atskirti paslaugos aprašą nuo sveikatos pažado?|H,Q|5|Metodas ir rinkodaros teiginys;Kokiam rezultatui reikia įrodymų;Sveikatos paslaugų riba|Teiginių ir įrodymų paskirties lentelė|S29,S37 ir kvalifikuota sveikatos review; ne procedūros efektyvumo reklama
`},
{id:'veido-prieziura',name:'Veido priežiūra',code:'VP',sources:['S27','S38','S29','S30','S39'],rows:`
gidas|Veido priežiūros paslaugų gidas: konsultacija, valymas ir procedūros apimtis|Q,S,E|1|Estetinis poreikis ir odos būklės vertinimo ribos;Darbų komponentai;Konsultacija ir vizito eiga|Paslaugos sudėties schema atskiriant gydymą|Kosmetologo ir sveikatos specialisto peržiūros apimtys
valymo-metodai|Mechaninis, ultragarsinis ir kombinuotas veido valymas: ką reiškia meniu?|A,Q|2|Metodo principas;Papildomi komponentai;Ko pavadinimas neįrodo apie individualų tinkamumą|Terminų ir komponentų lentelė|Konkrečios priemonės/įrenginio dokumentai ir kvalifikuota review
drekinimas|Drėkinamoji veido procedūra: valymas, kaukė ir kiti paketo komponentai|Q,E|2|Kosmetinis tikslas;Priemonių ir rankų darbo etapai;Kas nėra odos ligos gydymas|Neprocedūrinė etapų schema|Konkrečių produktų dokumentai; ne klinikinio poveikio pažadas
express|Express ar išsami veido procedūra: kas pasikeičia trumpesniame vizite?|A,C|2|Paslaugos apimtis;Konsultacija ir darbų laikas;Papildomi komponentai|Datuotų realių variantų sudėties palyginimas|S27,S38 tik pasiūlymų apimtis, ne veiksmingumas
masazas-kauke|Veido procedūra su kauke ar masažu: kaip palyginti paketą?|A,C|2|Valymo komponentas;Kaukė ir naudojami produktai;Masažo zonos|Paketo komponentų matrica|Kosmetologo review ir aktualūs meniu
odos-tipas|Odos tipas, jautrumas ir dabartinė būklė: kokią informaciją perduoti kosmetologui?|S,P|4|Vartotojo pastebėjimai;Dabartiniai produktai;Kodėl pats nenustatomas sutrikimas|Stebėjimų kortelė be savidiagnostinio testo|AAD ir kvalifikuota review; jokio universalaus tinkamumo testo
konsultacija|Pirmoji veido priežiūros konsultacija: poreikiai, istorija ir aiškus planas|S,P|1|Tikslas ir ankstesnės procedūros;Produktų bei reakcijų informacija;Tolesnių veiksmų pagrindimas|Konsultacijos rezultatų ruošinys|Tikro kosmetologo darbo eigos patikra
kaina-trukme|Veido priežiūros kaina ir trukmė: konsultacija, metodas bei papildomi darbai|C|1|Darbų apimtis;Konsultacijos ir procedūros laikas;Kas apmokama atskirai|Normalizuotas dviejų patikrintų pasiūlymų palyginimas|S27,S38 atnaujinti; ne LT rinkos vidurkis
pasiruosimas|Kaip pasiruošti veido procedūrai: produktai, ankstesni darbai ir instrukcija|P|3|Naudojamų produktų istorija;Ankstesnės procedūros;Konkretaus protokolo pasiruošimas|Vizitui skirtas duomenų ir instrukcijų ruošinys|Konkretaus produkto/procedūros protokolas; nesustabdyti vaistų savo nuožiūra
prieziura|Priežiūra po veido procedūros: kodėl nėra visiems vienodo plano?|R|3|Kokia procedūra atlikta;Produktai ir aplinkos poveikis;Kada reikalinga papildoma pagalba|Rašytinės priežiūros kortelė su metodo ir sistemos laukais|Konkretaus protokolo ir sveikatos teiginių review
sveikatos-riba|Veido priežiūra ir sveikatos paslauga: invazinių procedūrų bei pažadų riba|H,Q|5|Kosmetinė paskirtis;Invaziniai darbai ir medicininiai tikslai;Specialisto bei įstaigos patikra|LT kompetencijos ir paslaugos paskirties lentelė|S29,S31 ir aktualių veiklos reikalavimų review
pilingas|Kosmetinis šveitimas ir profesionalus cheminis pilingas: kodėl svarbus metodas bei gylis?|A,H|5|Mechaninė/kosmetinė priežiūra;Cheminio metodo skirtinga apimtis;Kvalifikacija ir individualaus vertinimo ribos|Terminų atskyrimo schema be koncentracijų ar DIY receptų|S39 ir LT kvalifikuota review; ne FDA taisyklių perkėlimas
reakcija|Nepageidaujama reakcija po veido procedūros: kada reikalingas sveikatos vertinimas?|H|5|Atlikto metodo informacija;Ko straipsnis negali nustatyti;Teikėjo ir sveikatos specialisto pagalbos kelias|Informacijos perdavimo ir pagalbos ribų atmintinė|Sveikatos specialisto review privaloma
planas|Vienkartinė veido procedūra ar priežiūros kursas: kaip vertinti siūlomą planą?|S,R|4|Konkretaus estetinio tikslo apibrėžimas;Produktų ir procedūrų logika;Kurso sąlygos be rezultato garantijų|Plano vertinimo lentelė be universalaus procedūrų skaičiaus|Tikro teikėjo planas ir kvalifikuota teiginių review
`}
];

export const sharedRows=`
registracija|Grožio vizito registracijos gidas: paslauga, laikas, vieta ir patvirtinimas|P,C|1|Paslaugos ir pradinės būklės duomenys;Atvykimas bei prieinamumas;Ką reiškia patvirtintas vizitas|Užpildomas registracijos ruošinys su patvirtinimo laukais|Tikra Madbeauty rezervavimo eiga prieš jos aprašą
sauga|Grožio paslaugų teikėjo patikra: vieta, higiena ir paslaugos pobūdis|H,S|1|Teikėjas ir vieta;Dokumentų patikros apimtis;Grožio ir sveikatos ribos|NVSC/VASPVT tikrinimo maršrutas be „visi patikrinti“ teiginio|S11,S28,S29,S31 aktualumas
salygos|Avansas, vizito keitimas ir atšaukimas: kaip perskaityti teikėjo sąlygas?|C,H|2|Mokėjimas ir patvirtinimas;Keitimo bei atšaukimo sąlygos;Ką išsaugoti susitarimui|Sąlygų perskaitymo scenarijus|S19 ir tikros platformos/teikėjo sąlygos; nėra visuotinio grąžinimo pažado
ginčas|Nepavykusi grožio paslauga: faktai, kreipimasis ir vartotojo ginčo kelias|H|3|Rezultatas ir susitarimas;Įrodymai bei rašytinis kreipimasis;Institucijos kompetencija|Neutralus kreipimosi šablonas su įvykių seka|S19 aktuali LT ginčų tvarka
vizitu-derinimas|Keli grožio vizitai ir individualūs poreikiai: laiko, vietos bei komforto planas|P|3|Nuoseklūs ar lygiagretūs darbai;Atvykimas ir prieinamumas;Bendravimo poreikiai|Dienos planas su tikrais patvirtinimo laukais|Jokio neįrodyto procedūrų suderinamumo pažado
meistrui-meniu|Meistrui: kaip sudaryti aiškų paslaugų meniu, kainą ir sąlygas?|C|4|Skirtingų variantų komponentai;Kaina ir papildomi darbai;Keitimo sąlygos vienoje vietoje|Nagų ir plaukų meniu ruošiniai|Tikros Madbeauty redagavimo funkcijos ir platformos sąlygos
meistrui-grafikas|Meistrui: paslaugų trukmė, laiko rezervas ir vizitų duomenys|C,E|4|Darbo laikas ir tarpai;Realių vizitų stebėjimas;Trukmių pakeitimo pagrindimas|Anoniminis trukmių žurnalo ruošinys|Nenaudoti privačių klientų įrašų; tikrai veikiantys grafiko laukai
meistrui-galerija|Meistrui: darbų fotografavimas, spalvos tikslumas ir publikavimo teisės|S|4|Vienodas apšvietimas;Originalas ir retušas;Kliento atvaizdo bei darbo teisių susitarimas|Fotografavimo protokolas ir sutikimo klausimų ruošinys|S21,S23 ir teisinė peržiūra; nėra universalios teisinės formos
meistrui-matavimas|Meistrui: profilio peržiūros, užklausos ir patvirtinti vizitai|C|4|Skirtingi veiksmai;Duomenų rinkimo ribos;Kokius rodiklius realiai turime|Piltuvo apibrėžimas su prieinamų/neprieinamų rodiklių laukais|Tikro Madbeauty matavimo galimybės; rodikliai dar neišmatuoti
`;

export const seasonalRows=`
kaledos|Grožio vizitai prieš Kalėdas: nagų dizainas ir kelių paslaugų planas|P,S|2026-11-10|Dizaino užduotis su originaliais akcentais;Kelių vizitų kalendorius;Tikras patvirtinimas ir laiko rezervas|Originali dizaino pora ir planavimo ruošinys|Nėra salonų apkrovos ar laisvų vietų matavimo
naujieji|Nagų dizainas Naujųjų metų renginiui: blizgesys, akcentai ir darbų apimtis|S,C|2026-11-24|Paviršiaus efektas;Akcentų vieta;Paketo sudėtis ir norimas rezultatas|Originalūs vienodos formos dizaino variantai|Vaizdai dar nesukurti; ne tikrų darbų galerija
valentino|Nagų dizainas Valentino dienai: originalūs akcentai ir adaptacijos|S|2027-01-12|Subtilus ir kontrastingas variantas;Trumpų nagų adaptacija;Technikos ir apimties užduotis|Originalių iliustracijų pora su adaptacijos schema|Ne metinis vienodo turinio URL klonas; vaizdų review dar reikalinga
velykos|Velykų savaitgalis 2027: grožio vizito darbo laikas ir patvirtinimas|P|2027-02-23|2027-03-28 datos kontekstas;Konkretaus teikėjo grafikas;Keitimo bei atvykimo informacija|Užpildoma darbo laiko ir vizito patvirtinimo kortelė|S15 ir tikri darbo laikai; nėra tariamos sezoninės paklausos
`;
