import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {localDate,localPublishAt} from '../../../content-studio/src/content-schedule.mjs';
import {TAXONOMY} from '../prototype/demo-model.mjs';
const read=f=>readFileSync(new URL(f,import.meta.url),'utf8');
const p=JSON.parse(read('PLAN.json')),html=read('MADBEAUTY-TOPICAL-AUTHORITY-PLANAS.html');
const all=[...p.existing,...p.pages],byId=Object.fromEntries(all.map(x=>[x.id,x]));
assert.equal(p.pages.length,p.totals.newUrls);assert.equal(p.window.target,p.policy.coverageTarget);assert.equal(p.totals.coverageTarget,p.pages.length+p.retained.length);assert.equal(p.retained.length,3);
const semantic=JSON.parse(read('SEMANTIC_REVIEW.json'));assert.equal(semantic.inputNewArticles,semantic.outputNewArticles+semantic.merges.length);assert.equal(semantic.outputNewArticles,p.pages.length);assert.equal(semantic.articles.length,semantic.inputNewArticles);assert.equal(new Set(semantic.articles.map(x=>x.articleId)).size,semantic.inputNewArticles);
assert.equal(p.categoryCoverage.length,33);assert.equal(p.referenceMenu.length,49);assert.equal(p.platformGaps.length,21);
assert.equal(new Set(p.pages.map(x=>x.slug)).size,p.pages.length);assert.equal(new Set(all.map(x=>x.id)).size,all.length);
assert.deepEqual([...p.liveCategoryIds].sort(),TAXONOMY.map(x=>x.id).sort());
assert.equal(p.policy.cadence,'coverage');assert.equal(p.execution.publicationQuota,null);
for(const c of p.categoryCoverage){assert.ok(byId[c.rootId]);for(const [dim,ids] of Object.entries(c.matrix)){assert.ok(ids.length,c.id+' missing '+dim);for(const id of ids)assert.ok(byId[id].dimensions.includes(dim));}}
for(const x of p.pages){
 assert.match(x.slug,/^gidai\/[a-z0-9-]+$/);assert.ok(!p.existing.some(y=>y.slug===x.slug));
 assert.equal(x.status,'PLAN_ONLY_NOT_WRITTEN');assert.equal(x.media.status,'NOT_CREATED');assert.equal(x.expertReview.status,'NOT_PERFORMED');assert.equal(x.agentReview,'NOT_PERFORMED');
 assert.ok(x.outline.length>=3&&x.outline.every(s=>s.length>=7));assert.ok(x.originalContribution.length>25);assert.ok(x.evidenceNeeds[0].task.length>10);
 assert.ok(x.sourceIds.length&&x.sourceIds.every(id=>p.sources.some(s=>s.id===id&&s.status==='READ')));
 assert.equal(localDate(x.publishAt,p.policy.timezone),x.publishDate);assert.equal(x.publishAt,localPublishAt(x.publishDate,'10:00','Europe/Vilnius'));
 assert.ok(x.publishDate>='2026-10-13'&&x.publishDate<='2027-04-06');if(x.wave!=='SEASONAL')assert.ok(x.publishDate<='2026-11-24');
 if(x.parentId){assert.ok(byId[x.parentId]);assert.ok(byId[x.parentId].publishAt<=x.publishAt);}
 const seen=new Set();let current=x;while(current.parentId){assert.ok(!seen.has(current.id));seen.add(current.id);current=byId[current.parentId];}
 assert.equal(html.split('id="'+x.id+'"').length-1,1);assert.ok(p.links.some(l=>l.from===x.id&&l.kind==='FUNCTIONAL_CTA'));
 if(['plauku-salinimas-lazeriu','kuno-prieziura','auskaru-verimas'].includes(x.categoryId))assert.equal(x.reviewLevel,'QUALIFIED_HEALTH_OR_LEGAL_REVIEW');
}
assert.equal(p.sources.length,84);assert.equal(new Set(p.sources.map(s=>s.id)).size,84);for(const s of p.sources){assert.equal(s.status,'READ');assert.ok(/^https:\/\//.test(s.url));assert.ok(s.limit.length>20);}
for(const r of p.referenceMenu)assert.ok(byId[r.targetId],r.label);
assert.equal(new Set(p.referenceMenu.map(x=>x.family)).size,7);
assert.equal(p.reconciliation.length,76);assert.equal(new Set(p.reconciliation.map(x=>x.oldId)).size,76);for(const r of p.reconciliation)assert.ok(byId[r.targetId]);
assert.equal(new Set(p.links.map(l=>l.from+'|'+l.to)).size,p.links.length);
for(const l of p.links){assert.ok(byId[l.from]&&byId[l.to]);assert.notEqual(l.from,l.to);assert.ok(l.anchor&&l.section&&l.reason&&l.activation);assert.equal(l.status,'PLANNED_NOT_LIVE');if(l.kind==='FUNCTIONAL_CTA')assert.ok(p.existing.some(x=>x.id===l.to));}
for(const x of p.retained)assert.equal(x.publishAt,p.existing.find(y=>y.id===x.id).publishAt);
const schema=JSON.parse(read('../../../content-studio/schemas/plan-result.schema.json'));
function validate(v,s){if(s.type==='object'){assert.ok(v&&typeof v==='object'&&!Array.isArray(v));for(const key of s.required??[])assert.ok(Object.hasOwn(v,key),key);for(const key of Object.keys(v)){if(s.additionalProperties===false)assert.ok(Object.hasOwn(s.properties,key),key);if(s.properties?.[key])validate(v[key],s.properties[key]);}}else if(s.type==='array'){assert.ok(Array.isArray(v));assert.ok(v.length>=(s.minItems??0)&&v.length<=(s.maxItems??Infinity));v.forEach(x=>validate(x,s.items));}else if(s.type==='string'){assert.equal(typeof v,'string');if(s.pattern)assert.match(v,new RegExp(s.pattern));}if(s.enum)assert.ok(s.enum.includes(v));}
const exported=[],files=readdirSync(new URL('batches/',import.meta.url)).filter(x=>x.endsWith('.json')).sort();assert.equal(files.length,Math.ceil(p.pages.length/24));
for(const f of files){const batch=JSON.parse(read('batches/'+f));validate(batch,schema);for(const x of batch.pages){const full=p.pages.find(y=>y.slug===x.slug);assert.ok(full);for(const key of ['type','slug','title','description','intent','cluster','publishDate'])assert.equal(x[key],full[key]);assert.equal(x.pillarSlug,full.parentId?byId[full.parentId].slug:'');assert.ok(x.reason.includes(full.id)&&x.reason.includes(full.originalContribution));assert.deepEqual(x.networkLinks,[]);exported.push(full.id);}}
assert.equal(exported.length,p.pages.length);assert.equal(new Set(exported).size,p.pages.length);for(const x of p.pages)if(x.parentId)assert.ok(exported.indexOf(x.parentId)<exported.indexOf(x.id));
const raw=readFileSync(new URL('../content/initial-release/content-package.json',import.meta.url));assert.equal(createHash('sha256').update(raw).digest('hex'),p.packageSha256);assert.equal(p.packageSha256,'dba452bae4c613cc91b2da0d67addd221e405f30c594992553f3009bfc809579');
assert.ok(!html.includes('undefined')&&!html.includes('[object Object]'));
const catalogue=JSON.parse(read('CATALOGUE_SNAPSHOT.json')),registry=JSON.parse(read('REGISTRY_PLANNED_SNAPSHOT.json')),cities=JSON.parse(read('CITIES_SNAPSHOT.json'));
const treatments=catalogue.nodes.filter(n=>n.kind==='treatment');assert.equal(treatments.length,225);assert.equal(catalogue.nodes.filter(n=>n.kind==='category').length,21);assert.equal(catalogue.nodes.filter(n=>n.kind==='group').length,59);assert.equal(cities.cities.length,103);assert.equal(new Set(cities.cities.map(c=>c.id)).size,103);
assert.equal(p.catalogueAlignment.foundationCommit,'c1f159353620aed66e9c67a95306786646c7137c');assert.equal(p.procedureCoverage.length,225);assert.equal(new Set(p.procedureCoverage.map(d=>d.taxonomyNodeId)).size,225);
for(const n of treatments){const d=p.procedureCoverage.find(d=>d.taxonomyNodeId===n.id);assert.ok(d);assert.equal(d.categoryId,n.categoryId);assert.equal(d.groupId,n.parentId);assert.equal(d.scope,n.scope);assert.ok(byId[d.targetId].outline.includes(d.section));assert.equal(d.status,'PLANNED_SECTION_NOT_WRITTEN');assert.equal(d.requirements.length,3);assert.ok(d.requirements.every(r=>r.length>30));}
for(const c of p.catalogueCategoryCoverage){for(const ids of Object.values(c.matrix)){assert.ok(ids.length);assert.ok(ids.every(id=>byId[id]));}}
for(const x of p.pages){assert.ok(x.catalogueTargets.length||x.catalogueTargetReason);for(const t of x.catalogueTargets){const r=registry.routes.find(r=>r.routeRegistryId===t.routeRegistryId);assert.ok(r);assert.equal(t.canonicalPath,r.canonicalPath);assert.equal(t.status,'planned');assert.equal(t.deployed,false);assert.equal(t.reachable,false);assert.equal(t.indexEligible,false);assert.equal(t.cityId,null);}assert.equal(x.seo.h1,x.title);assert.deepEqual(x.seo.h2,x.outline);assert.equal(x.description,x.seo.metaDescription);assert.ok(x.seo.primaryKeyword&&x.seo.metaTitle&&x.seo.metaDescription);if(x.seo.monthlySearchVolume!==null){assert.ok(x.seo.volumeSource?.callId);assert.ok(x.seo.volumeKeyword);}}
for(const key of ['primaryKeyword','metaTitle','metaDescription'])assert.equal(new Set(p.pages.map(x=>x.seo[key])).size,p.pages.length,'Duplicate SEO '+key);
const keyword=JSON.parse(read('KEYWORD_DATA.json'));
for(const x of p.pages){for(const r of x.seo.relatedEvidence)assert.ok(keyword.related.some(k=>k.keyword===r.keyword&&k.callId===r.callId));if(x.seo.monthlySearchVolume!==null)assert.equal(x.seo.primaryKeyword.normalize('NFD').replace(/[\u0300-\u036f]/g,''),x.seo.volumeKeyword.normalize('NFD').replace(/[\u0300-\u036f]/g,''));}
assert.equal(p.keywordResearch.volumeKeywords,730);assert.equal(p.keywordResearch.discoverySeeds,33);assert.equal(p.keywordResearch.serpQueries,60);assert.ok(p.keywordResearch.chargedUsd<1);for(const r of p.keywordResearch.receipts)assert.equal(r.http_status,200);
const seo=JSON.parse(read('SEO_MAP.json'));assert.equal(seo.articles.length,p.pages.length);for(const d of seo.decisions){if(d.articleId)assert.ok(byId[d.articleId]);for(const id of d.catalogueTargets)assert.ok(registry.routes.some(r=>r.routeRegistryId===id));if(d.cityId)assert.ok(cities.cities.some(c=>c.id===d.cityId));assert.equal(d.publicReady,false);}
for(const [term,expected] of [['mezoterapija','ES-mezoterapija-biorevitalizacija'],['pirtis','SP-gidas']]){const d=seo.decisions.find(x=>x.keyword===term);assert.equal(d.articleId,expected);assert.equal(d.decision,'NATIONAL_CATALOGUE_OR_MIXED_SERVICE_OWNER');}
const mask=seo.decisions.find(x=>x.keyword==='veido kaukė');assert.equal(mask.articleId,null);assert.equal(mask.decision,'REVIEW_MIXED_PRODUCT_OR_SERVICE');
for(const m of semantic.merges){assert.ok(!byId[m.oldId]);assert.ok(byId[m.targetId]);assert.ok(byId[m.targetId].mergedMediaBriefs.some(x=>x.oldId===m.oldId&&x.media.subject));const migration=p.execution.planMigration.retire.find(x=>x.oldId===m.oldId);assert.match(migration.oldPageId,/^[a-f0-9-]{36}$/);assert.match(migration.targetPageId,/^[a-f0-9-]{36}$/);}
assert.match(p.seoCoreReview.fingerprint,/^[a-f0-9]{64}$/);assert.ok(p.seoCoreReview.modules.includes('niche-seo-geo-core'));assert.equal(p.execution.pilot.historicalGenerationReceiptUnchanged,true);
const serp=JSON.parse(read('SERP_REVIEW.json'));assert.equal(serp.queries.length,60);for(const q of serp.queries){assert.equal(q.locationCode,2440);assert.equal(q.languageCode,'lt');assert.ok(q.callId&&q.items.length);assert.ok(q.observedAt);for(const [i,x] of q.items.entries()){assert.equal(x.rankGroup,i+1);assert.equal(x.rank,x.rankAbsolute);}}
const migration=JSON.parse(read('STUDIO_RECONCILIATION.json'));assert.equal(p.execution.planMigration.status,'APPLIED_TO_OWNER_PRIVATE_STUDIO');assert.equal(migration.activePages,p.totals.coverageTarget);assert.equal(migration.archivedPlans,semantic.merges.length);assert.equal(migration.promptInspection.mergedTargets.length,semantic.merges.length);assert.equal(migration.activeJobs,0);
const live=JSON.parse(read('LIVE_TARGET_REVIEW.json'));assert.equal(live.registry.idsMatchPlannedSnapshot,true);assert.equal(live.registry.readyNational,257);assert.equal(live.registry.readyLocal,0);assert.equal(live.registry.indexEligible,0);assert.equal(live.samples.length,2);assert.equal(live.emptyLocal.httpStatus,404);
const artifactHashes=Object.fromEntries(['PLAN.json','SEMANTIC_REVIEW.json','SEO_MAP.json','RESEARCH_IMPORT_MANIFEST.json','STUDIO_RECONCILIATION.json','LIVE_TARGET_REVIEW.json'].map(f=>[f,createHash('sha256').update(read(f)).digest('hex')]));
const report={checkedAt:p.updatedAt,artifactHashes,status:'FULL_CATALOGUE_PLAN_STRUCTURE_AND_RESEARCH_PROVENANCE_PASS',totals:p.totals,semanticMerges:semantic.merges.length,keywordOwnership:p.keywordOwnership,skillFingerprint:p.seoCoreReview.fingerprint,keywordResearch:{volumeKeywords:730,seeds:33,serpQueries:60,historicalChargedUsd:p.keywordResearch.chargedUsd,newPaidUsd:0},checks:['All 225 treatments retain explicit named article-section decisions after semantic merges','21 catalogue areas, 33 editorial branches, explicit shared preparation answer and 103 city IDs','Unpublished overlapping jobs merged with reasons, old private UUID migration explicit and not silently applied','49 menu positions and 76 old intents reconciled; 3 existing URLs/dates preserved',`${p.pages.length} unique slugs/IDs, cycle-free hierarchy and Europe/Vilnius DST`,`${p.totals.evergreenNew} evergreen + 4 seasonal dates and 12 reviews`,`${p.links.length} unique valid planned links; no automatic href activation`,'84 historical READ source records; qualified clinical review still not performed','730 volume rows, 33 related responses, 60 original SERPs; both rank types retained','Related keywords are observed vendor rows, distinct from generated editorial concepts','Broad service heads assigned national/mixed catalogue role; mask query unresolved explicitly',`${Math.ceil(p.pages.length/24)} schema-valid transport batches; every retained plan exactly once, parent first`,'New maintained SEO core included in actual planning instruction fingerprint','Historical pilot execution and original initial content package unchanged','Owner-isolated studio295 active/8 archived; actual merged brief prompt projection verified without generation','Fresh live resolver matches305 planned IDs; two national SSR/noindex samples and emptylocal404 verified; prompt evidence refreshed'],notAccepted:['All new article texts, media or clinical review; only one historical private pilot exists','Keyword candidate/backlog targeting, full keyword universe, mobile/city ranking or AI visibility','Private tenant restoration in another clone, V2 rich-output generation adapter and any new public release','Independent acceptance of all257 public SSR routes, indexable local provider supply and booking delivery','GSC/GA4, qualified leads, confirmed bookings, future traffic or Google rankings']};
writeFileSync(new URL('CATALOGUE_BINDING_VALIDATION.json',import.meta.url),JSON.stringify({checkedAt:report.checkedAt,status:'FULL_PLAN_BINDING_PASS_NOT_RUNTIME_ACCEPTANCE',foundationCommit:p.catalogueAlignment.foundationCommit,articles:p.pages.length,treatments:225,cities:103,actualActivation:false,notAccepted:report.notAccepted},null,2)+'\n');
writeFileSync(new URL('VALIDATION.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
