import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {v2RevisionHash} from 'file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/content-package-v2.mjs';
const here=new URL('.',import.meta.url),sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8'));
process.env.STUDIO_DATA_DIR=sel.privateStudio;process.env.STUDIO_OUTPUT_DIR=sel.privateStudio+'/output';
const {getSite,recordEditorialReview,approveReviewedBatch,releaseContent}=await import('file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/model.mjs');
const qa=JSON.parse(await fs.readFile(new URL('RENDER-CHECK.json',here),'utf8')),sources=JSON.parse(await fs.readFile(new URL('SOURCE-NOTES.json',here),'utf8')),media=JSON.parse(await fs.readFile(new URL('MEDIA-PLAN.json',here),'utf8')),base=JSON.parse(await fs.readFile(new URL('BASELINE.json',here),'utf8'));
const findings={
 'AN-gidas':'Forma, spalva ir plaukelių kryptis atskirtos; S03/S24/S35 meniu variantai nepristatomi kaip universalus protokolas. Nėra dažų mišinių, alergijos nebuvimo ar vienodos priežiūros garantijos.',
 'BL-gidas':'Natūralių blakstienų spalva ir LVL pakėlimas atskirti nuo pridedamo plaukelio. S36 gamintojo LVL skirtumas ir S03/S24 pasiūlymų apimtis patvirtina palyginimą; nėra visuotinio trukmės ar klijų saugumo pažado.',
 'DP-gidas':'S51 AAD vaškas šalina nuo šaknies, skutimas ties paviršiumi, pakartotinis aplikatoriaus merkimas ir šilumos higienos ribos patvirtintos. S55 45 min. / 25 Eur blauzdos ir 60 min. / 40 Eur kojos atitinka meniu. Nėra individualaus vaistų nutraukimo ar procedūros namuose protokolo.',
 'DZ-gidas':'S42 gamintojas skiria highlights, pilną šviesinimą su tonavimu ir balayage; S04/S33 meniu atskiria plotą, tonavimą ir kirpimą. Nėra dažų receptų, oksidantų, laikų, garantuoto vieno vizito rezultato ar savidiagnozės.',
 'GL-gidas':'S07 AAD gelinis lakas kietinamas UV šviesa, jo neplėšti. S01/S02 meniu skiria dangą, stiprinimą, ilginimą ir nuėmimą. Sluoksnių schema aiškiai konceptuali, nėra universalių lempų, chemijos, eiliškumo ar dozavimo instrukcijų.',
 'MN-gidas':'S01 atskiras manikiūras be dangos ir su danga; S02 atskiros stiprinimo/priauginimo užduotys. S08 kosmetinė danga neslepia pakitusio nago vertinimo poreikio. Sprendimų seka atskirta nuo atlikimo protokolo.',
 'NP-gidas':'S01 faktiškai perskaitytas papildomai: yra Nagų priauginimas, natūralių nagų stiprinimas geliu ir atskira gelinio lako nuėmimo žyma. Priauginimo konstrukcija atskirta nuo spalvos dangos. S07 patarimas neplėšti aiškiai tik geliniam lakui, ne visų medžiagų nuėmimo protokolas.',
 'PD-gidas':'S32 realus datuotas meniu: 75 min. / 45 Eur be dangos; 90 min. / 50 Eur paprastas lakas; iki 120 min. / 60 Eur nuėmimas su geliniu. S08 sveikatos ir kosmetinės paslaugos ribos; nėra gydymo instrukcijų ar vietinės pasiūlos pažado.',
 'PP-gidas':'S54 FDA ne visiems glotninimo produktams taikomas formaldehido teiginys; JAV informacija nėra LT teisė. S33 tonavimas, dažymas ir kirpimas atskiri. Nevertinamas nenustatytas produktas ar klinikinis veiksmingumas.',
 'AN-korekcija-ar-dazymas':'S03 meniu tikrai 30 min. / 10 Eur korekcija, 40 min. / 17 Eur su dažymu, 60 min. / 25 Eur laminavimo derinys. Vienas datuotas teikėjas, ne LT vidurkis ar Madbeauty pasiūla.',
 'BR-kirpimas-modeliavimas':'S56 meniu atskiria kirpimą/modeliavimą ir mašinėlės/skustuvo pasiūlymus. Pavadinimų riba sąlyginė; zonų žemėlapis originalus užduoties ruošinys, ne techninis protokolas. Dabartinis prieinamumas ar kaina iš senesnio meniu neteigiami.'
};
if(qa.views.length!==22)throw Error('Actual 22 views required');
const reviews=[];
for(const i of sel.pages){const p=(await getSite('madbeauty')).pages.find(p=>p.id===i.pageId),views=qa.views.filter(v=>v.planId===i.planId),m=media.find(m=>m.pageId===p.id);if(p.factChecks.length||views.length!==2||views.some(v=>v.revisionHash!==v2RevisionHash(p)))throw Error('Unresolved or stale '+i.planId);if(p.editorial.sources.some(s=>!sources.some(n=>n.id===s.id&&n.url===s.url&&n.review==='READ_FOR_BOUNDED_CLAIMS')))throw Error('Missing source evidence');
 const evidence={usefulness:'Visas galutinis tekstas perskaitytas. '+JSON.parse(await fs.readFile(new URL('REVIEW-NOTES.json',here),'utf8')).pages.find(n=>n.planId===i.planId).usefulness+'. Praktinis komponentų palyginimas ir pasirinkimo pavyzdys atitinka pavadinimą.',facts:findings[i.planId]+' Savininko EDITORIAL_POLICY supersedes human-signature dependency; tai atlikta agento patikra, ne žmogaus ekspertizė.',sources:'SOURCE-NOTES.json realūs perskaityti dokumentai ir bytes SHA. Šio puslapio šaltiniai: '+p.editorial.sources.map(s=>s.id+' '+s.url).join('; ')+'. Datuoti meniu nėra būsimos kainos garantija.',media:'Ankstesnės partijos originalai realiai apžiūrėti, jų SHA ir ImageGen kilmė MEDIA-PLAN.json. Originalūs penki WebP variantai išlaikyti. Šiandien papildomai apžiūrėti actual desktop/mobile screenshot kontaktiniai lapai; tinkamas crop, viena featured nuotrauka, alt, jokio fiktyvaus darbo ar eksperto įrodymo.',links:'Native selectReleaseLinks ir finalizeInternalLinks įvykdyti tik šioms11 temų. Tik tikri approved ar šios atominės partijos UUID; likusios neparašytos temos atidėtos. Commerce nacionaliniai IDs iš ankstesnio tikro katalogo, miesto pasiūla neteigiama.',presentation:'RENDER-CHECK.json22 actual Chrome1440/390 peržiūros, būtent šio teksto revision hash. Screenshot kontaktiniai lapai faktiškai apžiūrėti, vienas dekoduotas responsive vaizdas, nėra overflow, kirilicos ar raw Markdown nuorodų. Native privati peržiūra, ne production deployment.'};
 const review=await recordEditorialReview('madbeauty',p.id,{reviewer:'codex-editor:01a11146-e1d2-78b1-ae76-081e812c0ca0',revisionHash:v2RevisionHash(p),evidence});reviews.push({planId:i.planId,pageId:p.id,reviewRevisionHash:review.revisionHash,checkedAt:review.checkedAt,verifiedClaims:findings[i.planId],reviewMode:'autonomous-agent',humanExpertReviewPerformed:false});
}
const approval=await approveReviewedBatch('madbeauty',sel.pages.map(i=>i.pageId),'codex-autonomous-owner-policy');
const final=await getSite('madbeauty');for(const b of base.approvedSnapshots){if(JSON.stringify(final.pages.find(p=>p.id===b.id).publishedRevision)!==JSON.stringify(b.revision))throw Error('Incumbent snapshot changed');}for(const b of base.dates){if(final.pages.find(p=>p.id===b.id).publishAt!==b.publishAt)throw Error('Date changed');}
const release=await releaseContent('madbeauty');await fs.mkdir(new URL('release/',here),{recursive:true});await fs.cp(path.dirname(release.path),new URL('release/',here),{recursive:true});
await fs.writeFile(new URL('CLAIM-REVIEW.json',here),JSON.stringify({checkedAt:new Date().toISOString(),policySha256:createHash('sha256').update(await fs.readFile(new URL('../EDITORIAL_POLICY.json',here))).digest('hex'),pages:reviews},null,2)+'\n');
await fs.writeFile(new URL('DELIVERY.json',here),JSON.stringify({preparedAt:new Date().toISOString(),additionalApproved:approval.approved.length,approvedTotal:69,guideTotal:65,preservedApprovedSnapshots:58,preservedPublicationMoments:299,release,state:'EXPORTED_NOT_DEPLOYED',humanExpertReviewPerformed:false,productionAcceptance:null},null,2)+'\n');
console.log(JSON.stringify({additionalApproved:approval.approved.length,approvedTotal:69,packageSha256:release.packageSha256,state:'EXPORTED_NOT_DEPLOYED'}));
