// Public identity: Registru centras bulletin 2026-124, notice 7520005.
export const purchaseVersion='phonebridger-v1-20261006';
export const purchaseTerms=`<article class="prose reading-page">
<h2>Your seller</h2><p>PhoneBridger purchases are sold by MB Memocasting, company number 306026827, registered in Lithuania at Pupinės g. 10-55, LT-02206 Vilnius. Contact hello@phonebridger.com or company support on +370 691 08251. MB Memocasting is not VAT registered.</p>
<h2>What you are buying</h2><p>App only is USD 29; App + 1 holder is USD 49; App + 2 holders is USD 65; App + 3 holders is USD 79. Each includes the same one-time Windows V1 licence for one PC and up to three Android phones, with the Android companion. No subscription is added. The licence covers personal or business use of V1 and available V1 maintenance updates; a future paid major version is a separate offer. You may reinstall on a replacement PC, but not redistribute or resell the software.</p><p>The current beta remains free to try. Buying does not unlock extra beta features. Your purchase and licence record appear after confirmed payment; the record is not an activation key entered into the current apps. Download the apps from the Downloads page. Review compatibility and required Android permissions before buying. The beta is still in development; future features and release dates are not promised.</p><p>Hardware bundles add the selected count of foldable magnetic holders in Black or Silver. No laptop, phone or physical software box is included. Images are illustrations; the depicted PhoneBridger engraving is a branding mockup. Check magnetic-ring or case fit and a suitable mounting surface before attachment. Do not strain your laptop hinge or screen.</p>
<h2>Payment and confirmation</h2><p>Checkout availability is shown on the shop. Saving a setup or contacting us does not place an order. When Checkout is available, accept these terms, sign in to keep your order connected to your account, then pay on Stripe-hosted Checkout. Review the final payable amount before payment. We do not add VAT under our current non-VAT-registered status. Import duties or destination charges, where applicable, may be collected locally.</p><p>Your order becomes paid only after payment is verified. Status, downloadable order confirmation and licence record appear in your account. The confirmation retains the terms accepted for that order. Card statements may show MB MEMOCASTING. Payment method availability is determined at Checkout. If payment is pending, refresh your order or contact us before paying again.</p>
<h2>Free shipping and supplier fulfilment</h2><p>Shipping is free to destinations offered at Checkout. MB Memocasting arranges hardware orders manually with its supplier, which sends goods directly to the recipient. We remain your seller for delivery and returns. No local warehouse stock is claimed. Tracking appears in your account after dispatch.</p><p>Transit time varies. Unless a different period is agreed before purchase, the statutory delivery deadline is 30 days. We notify you and refund an order we cannot fulfil. Contact us about late or damaged goods; supplier policies do not replace your legal rights.</p>
<h2>Cancellation and returns</h2><p>Cancel app-only purchases within 14 days of purchase; downloading does not waive this right. Withdraw from an entire hardware bundle within 14 days of receiving the goods. Notify us online, by email or by post; no reason is required. For a partial cancellation, tell us which items you are returning.</p><p>Return hardware within 14 days of notification. You pay ordinary change-of-mind return postage; contact us for instructions before sending. Excessive use may reduce the refund. Refunds use the original payment method within 14 days of notification; we may wait for goods or proof of sending. A cancelled licence is revoked. Faulty or incorrect goods retain their statutory remedies.</p>
<h2>Withdraw from your contract</h2><p><a class="button secondary" href="/contact?topic=other&amp;action=withdraw">Withdraw from contract</a></p><p>The online form takes your name, email, order reference and withdrawal statement, and provides a dated confirmation to download after submission. You may instead email hello@phonebridger.com with “I withdraw from my PhoneBridger order”, your order reference, name, address and purchase or receipt date. Sign only if sending on paper. This wording is optional.</p>
<h2>Support and disputes</h2><p>Contact us about downloads, setup, delivery, cancellation or faults. Lithuanian law applies without removing mandatory consumer protections in your country. Unresolved consumer complaints may be referred to Lithuania’s State Consumer Rights Protection Authority, vvtat.lrv.lt. Creator commissions and a creator dashboard are not included.</p><p>Terms version ${purchaseVersion}. Updated 6 October 2026.</p>
</article>`;
