const icon=(name)=>`<svg aria-hidden="true" viewBox="0 0 24 24"><use href="/assets/shared-shell/icons.svg#${name}"/></svg>`;
const brand=`<a class="pb-shell-brand" href="/" aria-label="PhoneBridger home"><img src="/assets/brand-mark.svg" alt="" width="32" height="32"><span>PhoneBridger</span></a>`;
export const header=`<header class="pb-global-header"><div class="pb-shell-wrap pb-shell-bar">${brand}<nav id="pb-global-nav" class="pb-shell-nav" aria-label="Main navigation"><a href="/#workspace" data-shell-route="demo">Live demo<span class="pb-shell-live" aria-hidden="true"></span></a><a href="/shop/" data-shell-route="shop">Shop</a><a href="/guides/" data-shell-route="guides">Guides</a><a href="/help/" data-shell-route="help">Setup &amp; help</a><a href="/contact/" data-shell-route="contact">Contact</a><a class="pb-shell-mobile-account" href="/account/">Your account &amp; orders</a></nav><div class="pb-shell-actions"><a class="pb-shell-account" href="/account/" aria-label="Your account">${icon('user')}</a><a class="pb-shell-cta" href="/shop/"><span class="pb-shell-wide-label">Choose my setup</span><span class="pb-shell-short-label">Shop setups</span>${icon('arrow')}</a><button class="pb-shell-toggle" type="button" aria-expanded="false" aria-controls="pb-global-nav" aria-label="Open navigation">${icon('menu')}</button></div></div></header>`;
export const footer=`<footer class="pb-global-footer"><div class="pb-shell-wrap"><div class="pb-shell-footer-grid"><div class="pb-shell-intro">${brand}<p>Your phone.<br><span>A little more connected.</span></p><a href="mailto:hello@phonebridger.com">hello@phonebridger.com ${icon('arrow')}</a></div><nav aria-label="Footer product links"><h2>Your workspace</h2><a href="/shop/">Choose a setup</a><a href="/#workspace">Try the live demo</a><a href="/#features">Explore the features</a><a href="/downloads/">Downloads</a><a href="/about/">About PhoneBridger</a></nav><nav aria-label="Footer help links"><h2>A little help</h2><a href="/guides/">Guides</a><a href="/help/">Setup &amp; troubleshooting</a><a href="/#faq">Questions &amp; answers</a><a href="/contact/">Contact us</a><a href="/account/">Your account &amp; orders</a></nav><div class="pb-shell-signoff"><span class="pb-shell-eyebrow">MADE FOR YOUR EVERYDAY DESK</span><h2>One mouse.<br> More room to work.</h2><span class="pb-shell-platform">${icon('windows')}${icon('android')} Windows + Android</span><a class="pb-shell-footer-cta" href="/shop/">Find your setup ${icon('arrow')}</a></div></div><div class="pb-shell-trust"><div><strong>Checkout powered by Stripe</strong><p>Available payment methods are shown at checkout.</p></div><div class="pb-shell-cards" aria-label="Card networks: Visa, Mastercard, American Express and Discover"><svg role="img" aria-label="Visa" viewBox="0 0 64 40"><use href="/assets/shared-shell/cards.svg#visa"/></svg><svg role="img" aria-label="Mastercard" viewBox="0 0 64 40"><use href="/assets/shared-shell/cards.svg#mastercard"/></svg><svg role="img" aria-label="American Express" viewBox="0 0 64 40"><use href="/assets/shared-shell/cards.svg#amex"/></svg><svg role="img" aria-label="Discover" viewBox="0 0 64 40"><use href="/assets/shared-shell/cards.svg#discover"/></svg></div></div><div class="pb-shell-footer-bottom"><span>© ${new Date().getUTCFullYear()} PhoneBridger · MB Memocasting</span><nav aria-label="Legal and editorial links"><a href="/privacy/">Privacy</a><a href="/terms/">Terms &amp; store information</a><a href="/editorial/">Editorial</a></nav><a href="#pb-page-top">Back to top ↑</a></div></div></footer>`;
export function sharedShell(input){
 if(!/<header class="(?:site-header|inner-header)\b/.test(input))throw Error('Missing expected page header');
 if(!/<footer class="(?:site-footer|inner-footer)\b/.test(input))throw Error('Missing expected page footer');
 return input.replace(/<header class="(?:site-header|inner-header)\b[^>]*>[\s\S]*?<\/header>/,header).replace(/<footer class="(?:site-footer|inner-footer)\b[^>]*>[\s\S]*?<\/footer>/,footer).replace(/<body\b([^>]*)>/,'<body$1><span id="pb-page-top" aria-hidden="true"></span>').replace('</head>','<link rel="stylesheet" href="/assets/shared-shell/shell.css"><script src="/assets/shared-shell/shell.js" defer></script></head>');
}
