// Production-only transforms: the accepted prototype and demo engine remain immutable.
export function transform(file, input) {
 let text=input;
 if(file.endsWith('.html')) {
  text=text.replace(/<aside id="integration-preview"[\s\S]*?<\/aside>/,'');
  text=text.replace(/href="#integration-preview"([^>]*>)([\s\S]*?)Download for (Windows|Android)/g,(_,attrs,before,platform)=>`href="/downloads/${platform.toLowerCase()}"${attrs}${before}Download for ${platform}`);
  text=text.replaceAll('Local account preview','Your PhoneBridger account').replaceAll('local account preview','PhoneBridger account').replaceAll('Local preview account','PhoneBridger account').replaceAll('Use a test password. This preview does not create a production licence or order.','Accounts are for this website. Paid licences and orders are not open.').replaceAll('website preview','website');
  text=text.replaceAll('<dd>Local preview</dd>','<dd>Website account · email unverified</dd>');
  if(file==='contact/index.html') {
   text=text.replace('<label for="contact-email">Your email <span class="field-note">optional, for the draft</span></label>','<label for="contact-name">Your name</label><input id="contact-name" name="name" autocomplete="name" required minlength="2" maxlength="100"><label for="contact-email">Your email</label>').replace('name="email" type="email"','name="email" required type="email"').replace('minlength="10"','minlength="20"').replace('Prepare email','Send message');
   text=text.replace('<button class="button primary full" type="submit">','<label class="field-help"><input type="checkbox" name="consent" required style="width:18px;height:18px;min-height:18px;display:inline-block;margin-right:8px;vertical-align:middle;padding:0;accent-color:#ff1493"> I agree that my details will be used to answer this enquiry, as explained in the <a href="../privacy/">privacy notice</a>.</label><input name="website" tabindex="-1" autocomplete="off" hidden><button class="button primary full" type="submit">');
   text=text.replace('This prepares an editable email draft. Open it in your email app and send it there; this form does not send or store a message.','Your enquiry is stored securely so we can respond. Please do not include sensitive information.').replace(/<a class="text-link" data-email-draft[\s\S]*?<\/a>/,'');
  }
  if(file==='privacy/index.html')text=text.replace(/<article class="prose reading-page">[\s\S]*?<\/article>/,`<article class="prose reading-page"><h2>Who operates this website</h2><p>PhoneBridger is operated by MB Pinet. For privacy, access or deletion requests, use our contact form. This notice covers this website and its account service.</p><h2>Website demonstration</h2><p>The interactive demo uses fictional sample apps and data. Demo edits stay in page memory and clear on reset or reload. Sample reviews are illustrations, not verified customer testimonials. The demo does not sign in to your Google or other accounts.</p><h2>Saved setup</h2><p>When you choose Save my setup, your chosen package and holder finish are saved only in this browser’s local storage. Clear this site’s browser data to remove that choice.</p><h2>Enquiries</h2><p>We store your name, email, message, enquiry topic, source page and consent time to answer your request. Your enquiry is passed to our Hostinger mailbox so we can answer it. Form records are retained for up to 180 days; correspondence needed for a continuing matter may require a separate record. The form is not a marketing subscription.</p><h2>Accounts</h2><p>We store your email, creation date and salted password hash, never a readable password. A first-party Secure, HttpOnly, SameSite session cookie expires after eight hours; logging out revokes the session. Account records remain until deletion. Email verification and automatic password recovery are not available yet. Accounts do not represent a paid licence or purchase.</p><h2>Hosting and limited measurement</h2><p>Cloudflare hosts this website; application records use a dedicated D1 database with an EU jurisdiction setting. Cloudflare and Hostinger may process network and security data according to their service practices. Our application stores daily totals for page views and contact-link clicks, not browsing profiles. It respects Do Not Track and Global Privacy Control. Totals expire after 395 days. Temporary keyed rate-limit records expire after their rate windows; raw IP addresses are not stored in those records.</p><h2>Your choices and requests</h2><p>Use the contact form for access, correction or deletion of your enquiry or account, or questions about these practices. We may need to confirm ownership before acting. Where applicable, you may object to processing or complain to your data protection authority.</p><h2>Current scope</h2><p>No advertising trackers, live checkout or marketing subscription is included. The downloaded apps have their own permissions and pairing settings; this website notice does not replace their setup information. Updated 6 October 2026.</p><p><a href="../contact/?topic=account">Ask a privacy or account question</a>.</p></article>`);
 }
 if(file==='assets/site-pages-v1/site.js') {
  text=text.replace("location.assign('../account/');","{const p=new URLSearchParams(location.search);location.assign(p.get('next')==='shop'?'/shop':p.get('next')==='checkout'&&/^[a-f0-9]{32}$/.test(p.get('order')||'')?'/checkout?order='+p.get('order'):'../account/');}");
  text=text.replace(/ \$\('\[data-contact\]'\)\.addEventListener\('submit',[\s\S]*?link\.focus\(\);\}\);/,` $('[data-contact]').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const status=$('[data-contact-status]'),button=form.querySelector('[type=submit]');button.disabled=true;status.textContent='Sending your message…';try{const payload=Object.fromEntries(new FormData(form));payload.consent=form.elements.consent.checked;const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw Error(result.error||'Please try again.');status.textContent=result.message;form.reset();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});`);
  text=text.replaceAll('Account service is not connected in this preview. Please use the local account preview or contact support.','Account service is temporarily unavailable. Please try again or contact support.').replaceAll('Creating your local preview account…','Creating your account…').replaceAll('You’re signed in to the local preview.','You’re signed in to PhoneBridger.');
 }
 if(file==='app.js'){
  // Navigation belongs to the shared shell; preserve all demo/detail handlers.
  text=text.replace(/  const menuButton =[\s\S]*?  const privacy =/,"  root.dataset.theme = 'dark';\n  document.querySelector('meta[name=\"theme-color\"]').content = '#101114';\n  const privacy =").replace(/  updateNavigation\(\);\s*\}\)\(\);/, '})();');
  text=text.replace("querySelector('[data-open-privacy]').addEventListener","querySelector('[data-open-privacy]')?.addEventListener").replace("querySelector('[data-close-privacy]').addEventListener","querySelector('[data-close-privacy]')?.addEventListener");
 }
 return text;
}
