import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync,spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
const repo=path.resolve(import.meta.dirname,'../../..'),root=path.join(repo,'sites/madbeauty/cloudflare/output/next60-private'),json=async name=>JSON.parse(await readFile(path.join(root,name))),manifest=await json('manifest.json');
for(const mode of ['native','hosted','live-before']){const proof=await json(mode+'-proof.json');assert.equal(proof.state,'PASS');assert.equal(proof.packageSha256,manifest.packageSha256);assert.equal(proof.runtimeSource,manifest.runtimeSource);assert.equal(proof.coreSource,manifest.coreSource);assert.equal(proof.currentProjection.pages,7);assert.equal(proof.currentProjection.futureBlocked,122);assert.equal(proof.currentProjection.assets,mode==='live-before'?434:734);if(mode!=='live-before')assert.equal(proof.publicationCases.length,244);assert.ok(Date.now()-Date.parse(proof.finishedAt)<30*60*1000,'Acceptance receipt expired: '+mode);}
for(const mode of ['native','hosted'])assert.equal((await json(mode+'-proof.json')).artifactSha256,manifest.qaArtifactSha256);
const browser=await json('browser-hosted-proof.json');assert.equal(browser.state,'PASS');assert.equal(browser.packageSha256,manifest.packageSha256);assert.equal(browser.artifactSha256,manifest.qaArtifactSha256);assert.equal(browser.views.length,120);assert.equal(browser.pixelReview.state,'PASS_ACTUAL_PIXELS');assert.equal(browser.pixelReview.sheets.length,8);
const source=await readFile(path.join(root,'production-worker.mjs'));assert.equal(createHash('sha256').update(source).digest('hex'),manifest.productionArtifactSha256);for(const token of ['CALENDAR_ACCESS_KEY','CALENDAR_ACCEPTANCE_NOW','CalendarSource','madbeauty-calendar-acceptance-20261009'])assert.ok(!source.includes(token),'QA code in production artifact');
const config=await json('production-wrangler.json');assert.deepEqual(config,manifest.productionConfig);assert.equal(config.name,'madbeauty-platform-preview');assert.equal(config.account_id,'d102163f74a45ab6d33bca786ce281ec');assert.deepEqual(config.durable_objects,{bindings:[{name:'PLATFORM',class_name:'MadbeautyPlatform'}]});assert.deepEqual(config.migrations,[{tag:'v1',new_sqlite_classes:['MadbeautyPlatform']}]);assert.equal(config.no_bundle,true);
execFileSync(process.execPath,[path.join(import.meta.dirname,'provider.mjs'),'predeploy'],{cwd:repo,stdio:'inherit'});
const child=spawn(process.execPath,[path.join(repo,'../dovanos-memorycasting/node_modules/wrangler/bin/wrangler.js'),'deploy','--config',path.join(root,'production-wrangler.json'),'--message','Madbeauty content-only autonomous articles; incumbent runtime b7a34b1 core63cfd8c; prior69 unchanged'],{cwd:repo,stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);const code=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});await writeFile(path.join(root,'production-deploy.log'),log);assert.equal(code,0,'Inspect private deployment log before retrying');const version=log.match(/Current Version ID: ([a-f0-9-]{36})/)?.[1];assert.ok(version);console.log(JSON.stringify({state:'PRODUCTION_DEPLOYED',version,packageSha256:manifest.packageSha256,artifactSha256:manifest.productionArtifactSha256}));
