import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {stableV2 as stable} from 'file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/content-package-v2.mjs';
const here=new URL('.',import.meta.url),sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8')),notes=JSON.parse(await fs.readFile(new URL('SOURCE-NOTES.json',here),'utf8')),policy=JSON.parse(await fs.readFile(new URL('../EDITORIAL_POLICY.json',here),'utf8'));
process.env.STUDIO_DATA_DIR=sel.privateStudio;process.env.STUDIO_OUTPUT_DIR=sel.privateStudio+'/output';
const {getSite,listJobs,reconcilePrivatePlan,editPage}=await import('file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/model.mjs');
if((await listJobs()).some(j=>j.siteId==='madbeauty'&&['running','queued'].includes(j.status)))throw Error('Writer active');
let site=await getSite('madbeauty');const chosen=new Map(sel.pages.map(p=>[p.pageId,p]));
const extras=i=>{const ids=[];if(i.planId.startsWith('AV-'))ids.push('S89','S90','S93','S94');if(i.planId.startsWith('OD-'))ids.push('S85','S86');if(i.planId.startsWith('LZ-')||i.planId==='DP-ar-lazeris')ids.push('S91','S92','S50');if(i.planId==='DZ-balayage-airtouch')ids.push('S87');if(i.planId==='ND-chrome-cat-eye')ids.push('S88');if(i.planId.startsWith('ES-'))ids.push('S92');if(i.planId==='TT-eskizas')ids.push('S89');return ids;};
const updates=site.pages.map(p=>{let b=structuredClone(p.planningBrief?.data||{id:p.id,intent:p.intent||p.title});const i=chosen.get(p.id);if(i){if(p.body.length)throw Error('Selected already written '+i.planId);b.ownerPolicy=policy;b.previousExpertReview=structuredClone(b.expertReview);b.expertReview={status:'NOT_REQUIRED_BY_OWNER_POLICY',requiredScope:'Faktinė agento šaltinių, teiginių ir galutinio teksto peržiūra. Jokio žmogaus parašo laukimo ar fiktyvių credentials.'};b.reviewLevel='AUTONOMOUS_AGENT_REVISION_BOUND_REVIEW';b.evidenceNeeds=[{status:'REQUIRED_BEFORE_DRAFT_APPROVAL',task:'Tikri šaltiniai ir visas galutinis tekstas; neišspręstą teiginį agentas ištiria, pataiso arba pašalina. Laukti žmogaus specialisto neprivaloma.'}];for(const section of b.procedureSections||[])section.evidenceNeeds=structuredClone(b.evidenceNeeds);if(b.contentAcceptance)b.contentAcceptance.claimEvidence='Kiekvienas metodo, kainos, trukmės, sveikatos ir teisės teiginys pagrįstas actual perskaitytu šaltiniu ir jo kontekstu; atlikta revision-bound agento peržiūra, be privalomo žmogaus parašo.';b.sourceIds=[...new Set([...(b.sourceIds||[]),...extras(i)])];b.researchedClaims=b.sourceIds.map(id=>{const n=notes.find(n=>n.id===id);if(!n)throw Error('Unread source '+id);return{id,url:n.url,sha256:n.sha256,reviewedAt:n.reviewedAt,note:n.note};});b.writingRequirements='Parašyk tiesioginį, praktiškai naudingą atsakymą, ne vien klausimus teikėjui. Paaiškink skirtumus/mechanizmą konkrečiu palyginimu arba iliustracine situacija; nekurk techninio gydymo/procedūros namuose recepto. Meniu kainos tik datuoti konkrečios apimties pavyzdžiai. Nemini vidaus factChecks, reviewer gates, skill, CLI ar publikavimo būsenų skaitytojui. Savininko politika panaikina žmogaus specialisto parašo laukimą; neįrodytus teiginius taisai arba išmeti ir palieki tik konkrečias realias faktų spragas, jeigu tekstas jų dar reikalauja.';}
 return{pageId:p.id,slug:p.slug,brief:b,pillarPageId:p.pillarPageId||'',linkSuggestions:p.linkSuggestions||[]};});
const plan={createdAt:new Date().toISOString(),siteId:'madbeauty',policy,coverageTarget:site.pages.length,updates,retire:[]};const bytes=Buffer.from(JSON.stringify(plan,null,2)+'\n');await fs.writeFile(new URL('WRITER-PLAN.json',here),bytes);
const fingerprint=site.pages.find(p=>p.planningBrief)?.planningBrief.skillFingerprint;
const receipt=await reconcilePrivatePlan('madbeauty',{canonicalHost:site.canonicalHost,locale:site.locale,expectedSiteHash:createHash('sha256').update(stable(site)).digest('hex'),sourcePlanSha256:createHash('sha256').update(bytes).digest('hex'),skillFingerprint:fingerprint,coverageTarget:site.pages.length,updates,retire:[]});
site=await getSite('madbeauty');const author=site.pages.find(p=>p.editorial.authors.length).editorial.authors;
for(const i of sel.pages){const p=site.pages.find(p=>p.id===i.pageId),ids=p.planningBrief.data.sourceIds;const sources=ids.map(id=>{const n=notes.find(n=>n.id===id);return{id,title:n.title,publisher:new URL(n.url).hostname,url:n.url,accessedAt:n.retrievedAt,public:true};});await editPage('madbeauty',p.id,{editorial:{...p.editorial,authors:author,category:i.brief.cluster,datePublished:i.publishAt,dateModified:null,sources},externalLinks:sources.map(s=>({url:s.url,label:s.title,reason:notes.find(n=>n.id===s.id).note,verified:true}))});}
await fs.writeFile(new URL('PREPARATION.json',here),JSON.stringify({preparedAt:new Date().toISOString(),selected:60,actualReadSources:notes.length,policy,planReconciliation:receipt,preservedApproved:69,sourcePlanSha256:createHash('sha256').update(bytes).digest('hex')},null,2)+'\n');console.log('60 native writer inputs prepared with actual sources and owner policy; 69 approved snapshots preserved.');
