import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
import {stableV2} from 'file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/content-package-v2.mjs';
const here=new URL('.',import.meta.url),sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8'));
if(process.argv.includes('--candidate')){const f=new URL('SOURCE-CANDIDATES.json',here),rows=JSON.parse(await fs.readFile(f,'utf8'));if(!rows.some(s=>s.id==='S112'))rows.push({id:'S112',title:'ARPANSA: vartotojams skirtas lazerio ir IPL palyginimas',url:'https://www.arpansa.gov.au/understanding-radiation/sources-radiation/more-radiation-sources/lasers-and-intense-pulsed-light-0',kind:'Australian government radiation authority'});await fs.writeFile(f,JSON.stringify(rows,null,2)+'\n');process.exit(0);}
const ledgerFile=new URL('SOURCE-NOTES.json',here),ledger=JSON.parse(await fs.readFile(ledgerFile,'utf8')),raw=JSON.parse(await fs.readFile(sel.privateStudio+'/sources-next60/FETCH.json','utf8'));
const notes={S111:'Actually read Summary496–507web/218–228raw: lasers/IPL/LED are distinct light-based groups; IPL stands intense pulsed light. No Australian law transplanted to Lithuania, no treatment/device safety assurance or all-device result.',S112:'Actually read consumer503–515web: laser highly focused narrow spectrum, IPL wider spectrum over comparatively large skin area. This physical source distinction is not comparative clinical effectiveness for each person. Do not use wavelength1064nm, cooling/48hour patch/medication interval advice or Australian licensing as Lithuanian law; no personal settings/protocol.'};
for(const[id,note]of Object.entries(notes)){if(!ledger.some(s=>s.id===id)){const s=raw.find(s=>s.id===id);if(s?.status!==200)throw Error('Read source missing '+id);ledger.push({...s,note,review:'READ_FOR_BOUNDED_CLAIMS',reviewedAt:new Date().toISOString(),reviewScope:'Specific source definition only, no individual medical instructions'});}}
await fs.writeFile(ledgerFile,JSON.stringify(ledger,null,2)+'\n');
process.env.STUDIO_DATA_DIR=sel.privateStudio;process.env.STUDIO_OUTPUT_DIR=sel.privateStudio+'/output';
const {getSite,listJobs,reconcilePrivatePlan,editPage}=await import('file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/model.mjs');
if((await listJobs()).some(j=>j.siteId==='madbeauty'&&['running','queued'].includes(j.status)))throw Error('Writer active');
let site=await getSite('madbeauty');
const updates=site.pages.map(p=>{const b=structuredClone(p.planningBrief?.data||{});if(!p.body.length&&sel.pages.some(i=>i.pageId===p.id)){b.writingRequirements+=' STRICT NATIVE OUTPUT: external inline URL may only be an exact separately verified externalLinks URL; do not invent/add other URLs or UUIDs. Inline page targets require an already approved publishedRevision; all newly drafted future60 or unknown pages must be in internalLinks suggestions with exact provided IDs, never live inline page links.';if(p.id==='afc81d78-3f94-4484-9c4b-819841d96493'){b.sourceIds=[...new Set([...b.sourceIds,'S111','S112'])];b.researchedClaims.push(...ledger.filter(s=>['S111','S112'].includes(s.id)).map(s=>({id:s.id,url:s.url,sha256:s.sha256,note:s.note,reviewedAt:s.reviewedAt})));b.writingRequirements+=' Actual ARPANSA consumer bounded source confirms narrow laser spectrum vs broad IPL spectrum. Explain this plainly without clinical superiority/individual protocol. The failed prior result was rejected for unverified URL and invented page ID; rerun using only exact permitted targets.';}}return{pageId:p.id,slug:p.slug,brief:b,pillarPageId:p.pillarPageId||'',linkSuggestions:p.linkSuggestions||[]};});
const bytes=Buffer.from(JSON.stringify({updates,reason:'Failed native draft link validation correction; no accepted45 bodies changed'},null,2)+'\n');await fs.writeFile(new URL('RETRY-WRITER-PLAN.json',here),bytes);
const receipt=await reconcilePrivatePlan('madbeauty',{canonicalHost:site.canonicalHost,locale:site.locale,expectedSiteHash:createHash('sha256').update(stableV2(site)).digest('hex'),sourcePlanSha256:createHash('sha256').update(bytes).digest('hex'),skillFingerprint:site.pages.find(p=>p.planningBrief).planningBrief.skillFingerprint,coverageTarget:299,updates,retire:[]});
site=await getSite('madbeauty');const p=site.pages.find(p=>p.id==='afc81d78-3f94-4484-9c4b-819841d96493'),additions=ledger.filter(s=>['S111','S112'].includes(s.id));
await editPage('madbeauty',p.id,{editorial:{...p.editorial,sources:[...p.editorial.sources,...additions.filter(s=>!p.editorial.sources.some(x=>x.id===s.id)).map(s=>({id:s.id,title:s.title,publisher:new URL(s.url).hostname,url:s.url,accessedAt:s.retrievedAt,public:true}))]},externalLinks:[...p.externalLinks,...additions.filter(s=>!p.externalLinks.some(x=>x.url===s.url)).map(s=>({url:s.url,label:s.title,reason:s.note,verified:true}))]});
await fs.writeFile(new URL('RETRY-PREPARATION.json',here),JSON.stringify({preparedAt:new Date().toISOString(),receipt,reason:'Actual separately researched ARPANSA sources; fail-closed native URL/UUID rejection preserved',rejectedJobId:'8a5bc2c5-c94b-4481-a307-d7455cf13184',acceptedWrittenPreserved:45},null,2)+'\n');console.log('Retry prepared; existing45 unchanged, all299dates and69snapshots preserved.');
