import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';
import {v2RevisionHash} from 'file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/content-package-v2.mjs';
const here=new URL('.',import.meta.url),sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8'));
process.env.STUDIO_DATA_DIR=sel.privateStudio;process.env.STUDIO_OUTPUT_DIR=sel.privateStudio+'/output';
const {getSite,listJobs,recordEditorialReview,approveReviewedBatch,releaseContent}=await import('file:///C:/Users/Lenovo/Documents/Nisiniai_puslapiai/nisiniai_puslapiai_monetizavimui/content-studio/src/model.mjs');
if((await listJobs()).some(j=>j.siteId==='madbeauty'&&['running','queued'].includes(j.status)))throw Error('Writer active');
const read=async name=>JSON.parse(await fs.readFile(new URL(name,here),'utf8'));
const qa=await read('RENDER-CHECK.json'),sources=await read('SOURCE-NOTES.json'),media=await read('MEDIA-PLAN.json'),base=await read('BASELINE69-SNAPSHOTS.json'),texts=await read('FINAL-TEXT-REVIEW.json'),visual=await read('RENDERED-PIXEL-REVIEW.json'),catalogue=await read('CATALOGUE-TARGETS.json');
if(qa.views.length!==120||visual.state!=='PASS_ACTUAL_RENDERED_PIXELS'||visual.sheets.length!==8)throw Error('Actual120 render checks/eight sheet observations required');
if(Date.parse(catalogue.expiresAt)<Date.now())throw Error('Refresh real commerce evidence, no synthetic TTL extension');
const reviews=[];
for(const i of sel.pages){
 const p=(await getSite('madbeauty')).pages.find(p=>p.id===i.pageId),views=qa.views.filter(v=>v.planId===i.planId),m=media.find(m=>m.pageId===p.id),text=texts.pages.find(n=>n.planId===i.planId);
 if(p.factChecks.length||views.length!==2||views.some(v=>v.revisionHash!==v2RevisionHash(p))||text?.revisionHash!==v2RevisionHash(p)||text.state!=='PASS_FULL_FINAL_TEXT_READ')throw Error('Unresolved/stale review '+i.planId);
 if(!m.imported||m.originalPixelReview?.state!=='PASS_ORIGINAL_PIXELS'||m.originalPixelReview.sha256!==m.originalSha256)throw Error('Original media review missing');
 if(p.editorial.sources.some(s=>!sources.some(n=>n.id===s.id&&n.url===s.url&&n.review==='READ_FOR_BOUNDED_CLAIMS')))throw Error('Unread source '+i.planId);
 const c=catalogue.pages.find(n=>n.planId===i.planId);
 const evidence={usefulness:text.usefulness,facts:text.verifiedClaims+' Atlikta autonominė agento patikra pagal svetainės EDITORIAL_POLICY; žmogaus specialistų peržiūros ar credentials neišgalvoti.',sources:'SOURCE-NOTES.json tikrai perskaitytos šaltinių ištraukos su rawbytesSHA ir apribojimais: '+p.editorial.sources.map(s=>s.id+' '+s.url).join('; ')+'. Datuoti meniu pavyzdžiai nėra ateities kainos garantija.',media:m.originalPixelReview.observation+' Tikras originalo SHA'+m.originalSha256+', faktinis ImageGen prompt ir penki common WebP variantai MEDIA-PLAN.json; actual responsive desktop/mobile crop patikrintas atskirai. Fikcinė teminė iliustracija, ne kliento rezultatas.',links:'Native selectReleaseLinks/finalizeInternalLinks, konkretūs approved69 arba šios atominės60partijos UUID. Nacionaliniai commerceIDs'+(c?.kept.join(', ')||'netaikomi arba planned')+'; planned'+(c?.deferred.map(x=>x.taxonomyNodeId).join(', ')||'nėra')+' atidėti evidence. Fresh real registry SHA'+catalogue.registrySha256+';0city/realprovider supply claims, jokio testinio bandymas namespace.',presentation:'RENDER-CHECK.json120actualChrome1440/390 peržiūrų su exact revisionhash;8 actual screenshot sheet pixels perskaityti, tinkamas crop/alt/author/date, nėra overflow/brokenimages/Cyrillic/rawMarkdown. Private common studio rendering; deployment acceptance atskirai.'};
 evidence.presentation+=' Native semantic body rendered through owned private presentation adapter (PREVIEW-ADAPTER.json); contact sheets show first-fold crops, complete body was read separately. Canonical production renderer was not used for these private checks.';
 const review=await recordEditorialReview('madbeauty',p.id,{reviewer:'codex-editor:01a11146-e1d2-78b1-ae76-081e812c0ca0',revisionHash:v2RevisionHash(p),evidence});reviews.push({planId:i.planId,pageId:p.id,reviewRevisionHash:review.revisionHash,checkedAt:review.checkedAt,verifiedClaims:text.verifiedClaims,reviewMode:'autonomous-agent',humanExpertReviewPerformed:false});
}
const approval=await approveReviewedBatch('madbeauty',sel.pages.map(i=>i.pageId),'codex-autonomous-owner-policy');
const final=await getSite('madbeauty');for(const b of base.approvedSnapshots)if(JSON.stringify(final.pages.find(p=>p.id===b.id).publishedRevision)!==JSON.stringify(b.revision))throw Error('Incumbent69 snapshot changed');for(const b of base.dates)if(final.pages.find(p=>p.id===b.id).publishAt!==b.publishAt)throw Error('Publication date changed');
const approved=final.pages.filter(p=>p.publishedRevision);if(approved.length!==129)throw Error('Expected129 approved');
const release=await releaseContent('madbeauty');await fs.mkdir(new URL('release/',here),{recursive:true});await fs.cp(path.dirname(release.path),new URL('release/',here),{recursive:true});
await fs.writeFile(new URL('CLAIM-REVIEW.json',here),JSON.stringify({checkedAt:new Date().toISOString(),policySha256:createHash('sha256').update(await fs.readFile(new URL('../EDITORIAL_POLICY.json',here))).digest('hex'),pages:reviews},null,2)+'\n');
await fs.writeFile(new URL('DELIVERY.json',here),JSON.stringify({preparedAt:new Date().toISOString(),additionalApproved:approval.approved.length,approvedTotal:approved.length,guideTotal:approved.filter(p=>p.type==='guide').length,preservedApprovedSnapshots:69,preservedPublicationMoments:299,release,state:'EXPORTED_NOT_DEPLOYED',humanExpertReviewPerformed:false,productionAcceptance:null,limitations:['Planned catalogue extensions deferred with exactIDs; no test-provider or local-supply claims','Historical dated price examples do not promise publication-date prices']},null,2)+'\n');
console.log(JSON.stringify({additionalApproved:approval.approved.length,approvedTotal:approved.length,packageSha256:release.packageSha256,state:'EXPORTED_NOT_DEPLOYED'}));
