import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
const here=new URL('.',import.meta.url),origin='https://madbeauty.lt',bytes=await fs.readFile(new URL('release/content-package.json',here)),pkg=JSON.parse(bytes),sha=createHash('sha256').update(bytes).digest('hex');
const delivery=JSON.parse(await fs.readFile(new URL('DELIVERY.json',here),'utf8'));assert.equal(sha,delivery.release.packageSha256);assert.equal(pkg.pages.length,129);
const sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8')),selected=new Set(sel.pages.map(p=>p.pageId)),now=Date.now(),due=pkg.pages.filter(p=>Date.parse(p.publishAt)<=now),future=pkg.pages.filter(p=>Date.parse(p.publishAt)>now),fresh=pkg.pages.filter(p=>selected.has(p.id));assert.equal(fresh.length,60);
const feed=await fetch(origin+'/content.json',{cache:'no-store',signal:AbortSignal.timeout(30000)});assert.equal(feed.status,200);assert.equal(feed.headers.get('x-madbeauty-content-sha256'),sha,'Exact129 package not activated; no deployment claim');const data=await feed.json();assert.deepEqual(data.pages.map(p=>p.slug).sort(),due.map(p=>p.slug).sort());
const publicMedia=new Set(due.flatMap(p=>p.media.map(m=>m.src))),privateMedia=[...new Set(fresh.flatMap(p=>p.media.map(m=>m.src)))].filter(src=>!publicMedia.has(src));
const paths=['/sitemap.xml','/llms.txt','/llms-full.txt',...due.map(p=>'/'+p.slug),...future.map(p=>'/'+p.slug),...privateMedia],results=[];
for(let start=0;start<paths.length;start+=8){const rows=await Promise.allSettled(paths.slice(start,start+8).map(async path=>{const r=await fetch(origin+path,{cache:'no-store',signal:AbortSignal.timeout(30000)});return{path,status:r.status,packageSha256:r.headers.get('x-madbeauty-content-sha256'),text:await r.text()};}));for(const r of rows){if(r.status!=='fulfilled')throw r.reason;results.push(r.value);}}
for(const r of results){if(['/sitemap.xml','/llms.txt','/llms-full.txt'].includes(r.path)){assert.equal(r.status,200);for(const p of future)assert.ok(!r.text.includes(origin+'/'+p.slug),r.path+' future canonical leak');}else if(due.some(p=>'/'+p.slug===r.path)){assert.equal(r.status,200);assert.ok(r.text.includes('Madbeauty'));}else assert.equal(r.status,404,r.path+' private before date');}
const receipt={checkedAt:new Date().toISOString(),state:'PASS_ACTUAL_CANONICAL_DOMAIN',origin,packageSha256:sha,additionalGuides:60,totalApprovedPages:129,totalApprovedGuides:125,duePages:due.length,dueGuides:due.filter(p=>p.type==='guide').length,futurePagesHidden:future.length,newFutureMediaHidden:privateMedia.length,uniqueAdditionalPublicationMoments:60,checks:{exactDueSet:true,allFuturePages404:true,newFutureMedia404:true,noFutureCanonicalInSitemapOrLlmIndexes:true},http:results.map(({text,...r})=>r),limitations:['Actual canonical ordinary HTTPS verification. Future-boundary rendering, byline/schema and runtime/core/Cloudflare version identity are independently required from the owner consumer receipt. No search-indexing guarantee.']};
await fs.writeFile(new URL('DOMAIN-ACCEPTANCE.json',here),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({...receipt,http:undefined}));
