import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
const root=await mkdtemp(path.join(os.tmpdir(),'niche-media-test-'));
process.env.STUDIO_DATA_DIR=path.join(root,'data');process.env.STUDIO_OUTPUT_DIR=path.join(root,'output');process.env.STUDIO_PORT='4326';
const model=await import('../src/model.mjs');const {createServer}=await import('../src/server.mjs');
const {validateContentPackage}=await import('../../../dovanos-memorycasting/scripts/content-package-core.mjs');
await model.initialize();
test('HTTP upload optimizes once, attaching one image includes all variants, and approval/export stay isolated',async()=>{
 const site=await model.createSite({canonicalHost:'media-test.invalid',name:'Privatus media bandymas',offer:'Izoliuotas failų importo testas'});
 await model.editSite(site.id,{facts:'Tikras sintetinis bandymas, ne verslo faktas.',contact:{email:'qa@example.invalid',phone:''}});
 const second=await model.createSite({canonicalHost:'other-media.invalid',name:'Kitas testas'});
 const bytes=await sharp({create:{width:1800,height:900,channels:3,background:'#887755'}}).png().toBuffer();
 const server=await createServer();await new Promise(r=>server.listen(4326,'127.0.0.1',r));
 try{
  const res=await fetch(`http://127.0.0.1:4326/api/sites/${site.id}/assets`,{method:'POST',headers:{'x-studio-request':'1','content-type':'application/json'},body:JSON.stringify({mime:'image/png',base64:bytes.toString('base64'),alt:'Originalus bandomasis vaizdas',rights:'Synthetic test only',width:99999,height:99999,prompt:'Exact test generation description'})});
  assert.equal(res.status,201);const imported=await res.json();assert.deepEqual(imported.variants.map(v=>v.width),[1600,1200,800,640,360]);
  const page=await model.addPage(site.id,{type:'home',slug:'',title:'Privatus bandymas',description:'Bandymo turinys',intent:'Test',body:[{type:'paragraph',text:'Tai tik izoliuotas turinio sistemos testas. Vaizdų importas nepatvirtina turinio, nuosavybės ar viešo publikavimo. Šis tekstas nepatenka į tikrą svetainę.'}]});
  await model.editPage(site.id,page.id,{media:[{id:imported.id}]});
  assert.equal((await model.getSite(site.id)).pages[0].media.length,5);
  const other=await model.addPage(second.id,{type:'home',slug:'',title:'Kitas',description:'Kitas',intent:'Test'});
  await assert.rejects(()=>model.editPage(second.id,other.id,{media:[{id:imported.id}]}),/nepriklauso/);
  assert.equal(model.packageForSite(await model.getSite(site.id)).pages.length,0);
  await model.approvePage(site.id,page.id,'test-asset-review');const before=model.packageForSite(await model.getSite(site.id)).pages[0].revisionHash;
  const extra=[await model.saveResponsiveAsset(site.id,{mime:'image/png',alt:'Kita kompozicija',rights:'Synthetic test only'},bytes)];
  assert.equal(model.packageForSite(await model.getSite(site.id)).pages[0].revisionHash,before);
  for(let i=0;i<3;i++)extra.push(await model.saveResponsiveAsset(site.id,{mime:'image/png',alt:`Limitų kompozicija ${i}`,rights:'Synthetic test only'},bytes));
  const exported=await model.exportPackage(site.id),pkg=JSON.parse(await readFile(exported.path,'utf8'));validateContentPackage(pkg);
  assert.equal(exported.assets,5);assert.equal(pkg.pages[0].media.length,5);assert.equal(JSON.stringify(pkg).includes('groupId'),false);assert.equal(JSON.stringify(pkg).includes('Exact test generation'),false);
  const files=await readdir(path.join(root,'output',site.id,'assets'));assert.ok(files.every(f=>f.endsWith('.webp')));assert.equal(files.length,5);
  assert.ok((await readdir(path.join(root,'data','media-originals',site.id))).some(f=>f.endsWith('.png')));
  const original=await fetch(`http://127.0.0.1:4326/api/media/${site.id}/${imported.groupId}.png`);assert.notEqual(original.status,200);
  const image=await fetch(`http://127.0.0.1:4326/api/media/${site.id}/${imported.id}.webp`);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/webp');
  assert.equal((await sharp(Buffer.from(await image.arrayBuffer())).metadata()).width,1600);
  const rich=await model.addPage(site.id,{type:'guide',slug:'/vaizdai',title:'Penki vaizdai',description:'Responsive šeimų priėmimas',intent:'Test',body:page.body});
  await model.editPage(site.id,rich.id,{media:[{id:imported.id},...extra.map(a=>({id:a.id}))]});
  await model.approvePage(site.id,rich.id,'test-rich-media-review');
  const richExport=await model.exportPackage(site.id),richPackage=JSON.parse(await readFile(richExport.path,'utf8'));
  validateContentPackage(richPackage);assert.equal(richPackage.pages[1].media.length,25);assert.equal(richExport.assets,25);
  const schema=JSON.parse(await readFile(new URL('../schemas/content-package.schema.json',import.meta.url),'utf8'));
  assert.equal(schema.$defs.page.properties.media.maxItems,model.MAX_PAGE_MEDIA);assert.equal(model.MAX_PAGE_MEDIA,60);
  const richHash=richPackage.pages[1].revisionHash;
  for(let i=0;i<8;i++)extra.push(await model.saveResponsiveAsset(site.id,{mime:'image/png',alt:`Ribos kompozicija ${i}`,rights:'Synthetic test only'},bytes));
  await assert.rejects(()=>model.editPage(site.id,rich.id,{media:[{id:imported.id},...extra.map(a=>({id:a.id}))]}),/60/);
  assert.equal((await model.getSite(site.id)).pages[1].media.length,25);
  assert.equal(model.packageForSite(await model.getSite(site.id)).pages[1].revisionHash,richHash);
 }finally{await new Promise(r=>server.close(r));}
});
test.after(async()=>{await rm(root,{recursive:true,force:true});});
