import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
export const trialOrigin='https://bandymas.madbeauty.lt';

export function trialBrowser(fetcher=fetch){
 let cookie='',csrf='';
 return {
  async request(path,body,overrides={}){
   const response=await fetcher(trialOrigin+'/api/madbeauty/'+path,{method:body===undefined?'GET':'POST',headers:{cookie,origin:trialOrigin,...(body===undefined?{}:{'content-type':'application/json','x-csrf-token':csrf}),...overrides},...(body===undefined?{}:{body:JSON.stringify(body)})});
   const set=response.headers.get('set-cookie');if(set)cookie=set.split(';')[0];
   const value=await response.json();if(value.csrf)csrf=value.csrf;
   return {status:response.status,value};
  },
  async login(email){
   assert.ok(email.endsWith('@example.com'));await this.request('session');
   const start=await this.request('auth/start',{email});assert.equal(start.status,200,'Test account login start');assert.match(start.value.testCode,/^\d{6}$/);
   const verified=await this.request('auth/verify',{challengeId:start.value.challengeId,code:start.value.testCode});assert.equal(verified.status,200,'Test account verification');return verified.value;
  },
  async rpc(method,input={}){
   const response=await this.request('rpc',{method,input,siteId:'madbeauty'});
   assert.equal(response.status,200,method+': '+response.value.error?.code);return response.value.result;
  },
  async denied(method,input,code){
   const response=await this.request('rpc',{method,input,siteId:'madbeauty'});assert.ok(response.status>=400,method+' must reject');assert.equal(response.value.error?.code,code,method);
  }
 };
}

// Uses only existing, explicitly authorized fictional identities. Each new offer,
// booking, membership and erasure request is tracked for reversible cleanup.
export async function verifyTrialOperations(browserFactory=()=>trialBrowser()){
 const startedAt=new Date().toISOString(),run='trial-ops-'+randomUUID(),checks=[],cleanup=[],organizationId='demo-org-45',scope={role:'professional',organizationId};
 const owner=browserFactory(),foreign=browserFactory(),client=browserFactory(),member=browserFactory(),operator=browserFactory(),guest=browserFactory();
 let offer,booking,held,grant,request,originalRules,originalPreferences,busyBlock;const extraBookings=[];
 const check=async(name,fn)=>{try{await fn();checks.push({name,state:'PASS'});}catch(error){checks.push({name,state:'FAIL',code:error.code||error.name,message:error.message});throw error;}};
 const cleanupStep=async(name,fn)=>{try{await fn();cleanup.push({name,state:'PASS'});}catch(error){cleanup.push({name,state:'FAIL',code:error.code||error.name,message:error.message});}};
 const workspace=()=>owner.rpc('workspace',scope);
 const publish=async()=>{offer=await owner.rpc('submitOffer',{id:offer.id,version:offer.version});offer=await operator.rpc('moderateOffer',{id:offer.id,version:offer.version,state:'approved'});};
 const slot=async(id,dayOffset=2)=>{const values=await client.rpc('availability',{providerServiceId:id,dayOffset,from:540,to:1200,addons:[]});assert.ok(values.slots.length,'Available whole visit slot');return values.slots[0];};
 let failure;
 try{
  await check('Existing fictional client/owner/operator sessions',async()=>{await owner.login('demo-provider-45@example.com');await foreign.login('demo-provider-44@example.com');await client.login('profile-client-45@example.com');await member.login('profile-client-44@example.com');await operator.login('trial-operator@example.com');await guest.request('session');});
  const before=await workspace(),org=before.organizations.find(o=>o.id===organizationId),practitioner=before.practitioners.find(p=>p.organizationId===organizationId&&p.active),resource=before.resources.find(r=>r.organizationId===organizationId&&r.active);
  assert.ok(org&&practitioner&&resource);
  const taxonomy=await owner.rpc('taxonomy'),procedure=taxonomy.nodes.find(n=>n.kind==='treatment'&&!n.archived&&n.scope==='core'&&!n.reviewRequired&&n.label==='Klasikinis manikiūras');assert.ok(procedure);
  assert.ok(!(before.offers||[]).some(o=>o.taxonomyServiceId===procedure.id&&o.state!=='archived'),'QA procedure must not already have an active offer');
  originalRules={minLeadTimeMin:org.leadTimeMin??30,maxAdvanceDays:org.bookingRules?.maxAdvanceDays??30,weekdays:org.bookingRules?.weekdays||['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],closedDates:org.bookingRules?.closedDates||[]};
  originalPreferences=(await client.rpc('workspace',{role:'customer'})).preferences?.[0];
  const basePublic=(await guest.rpc('catalog')).filter(s=>s.organizationId===organizationId).map(s=>s.id).sort();
  await check('Guest mutations and missing CSRF rejected',async()=>{await guest.denied('selectProcedures',{organizationId,procedureIds:[procedure.id],version:before.selectionVersion||0,idempotencyKey:run},'UNAUTHENTICATED');const response=await owner.request('rpc',{method:'selectProcedures',input:{organizationId},siteId:'madbeauty'},{'x-csrf-token':''});assert.equal(response.status,403);});
  await check('Foreign provider cannot read or mutate another workspace',async()=>{await foreign.denied('workspace',scope,'FORBIDDEN');await foreign.denied('selectProcedures',{organizationId,procedureIds:[procedure.id],version:before.selectionVersion||0,idempotencyKey:run},'FORBIDDEN');});
  await check('Procedure selection replay returns one private draft',async()=>{const input={organizationId,procedureIds:[procedure.id],version:before.selectionVersion||0,idempotencyKey:run};const first=await owner.rpc('selectProcedures',input);offer=first[0];assert.equal(first.length,1);assert.equal((await owner.rpc('selectProcedures',input))[0].id,offer.id);assert.ok(!(await guest.rpc('catalog')).some(s=>s.offerId===offer.id));});
  const variantId=run+'-variant',variant={id:variantId,label:'Laikino bandymo variantas',priceMinor:1700,durationMin:30,staffOptions:[{practitionerId:practitioner.id,resourceId:resource.id}],addons:[{id:run+'-addon',label:'Bandymo priedas',priceMinor:300,durationMin:15}]},secondVariant={...variant,id:run+'-second',label:'Antras bandymo variantas',priceMinor:800,durationMin:15,addons:[]};
  await check('Offer price/duration/staff validation and stale version',async()=>{const old=offer;await owner.denied('saveOffer',{id:offer.id,version:offer.version,label:'Bandymo pasiūlymas',variants:[{...variant,durationMin:0}]},'INVALID_INPUT');offer=await owner.rpc('saveOffer',{id:offer.id,version:offer.version,label:'Laikino bandymo pasiūlymas',variants:[variant,secondVariant]});await owner.denied('saveOffer',{id:offer.id,version:old.version,label:'Stale',variants:[variant]},'VERSION_CONFLICT');assert.ok(!(await guest.rpc('catalog')).some(s=>s.id===variantId));});
  await check('Operator review publishes eligible provider offer',async()=>{await owner.denied('moderateOffer',{id:offer.id,version:offer.version,state:'approved'},'FORBIDDEN');await publish();const service=(await guest.rpc('catalog')).find(s=>s.id===variantId);assert.equal(service.priceMinor,1700);assert.equal(service.durationMin,30);});
  await check('Single slot cannot be held by two customers',async()=>{const chosen=await slot(variantId);held=await client.rpc('hold',chosen);await member.denied('hold',chosen,'SLOT_CONFLICT');});
  await check('Confirmation replay returns one durable booking and snapshot',async()=>{const input={holdId:held.id,name:'Fiktyvus operacijų bandymo klientas',idempotencyKey:run+'-booking'};booking=await client.rpc('confirm',input);const replay=await client.rpc('confirm',input);assert.equal(replay.id,booking.id);assert.equal(booking.priceMinor,1700);assert.equal(booking.durationMin,30);held=null;assert.equal((await client.rpc('workspace',{role:'customer'})).bookings.filter(b=>b.id===booking.id).length,1);assert.equal((await workspace()).bookings.filter(b=>b.id===booking.id).length,1);assert.ok(!(await member.rpc('workspace',{role:'customer'})).bookings.some(b=>b.id===booking.id));});
  await check('Service draft cannot change current quote or saved booking',async()=>{offer=await owner.rpc('saveOffer',{id:offer.id,version:offer.version,label:'Laikino bandymo pasiūlymas',variants:[{...variant,priceMinor:1900,durationMin:45},secondVariant]});assert.equal((await guest.rpc('catalog')).find(s=>s.id===variantId).priceMinor,1700);assert.equal((await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===booking.id).priceMinor,1700);await publish();const repeat=await client.rpc('rebooking',{id:booking.id});assert.equal(repeat.priceMinor,1900);assert.equal(repeat.procedureMin,45);assert.equal(repeat.changes[0].previous.priceMinor,1700);assert.equal((await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===booking.id).priceMinor,1700);});
  await check('Move booking updates both roles and rejects stale cancellation',async()=>{const oldVersion=booking.version,candidate=await slot(variantId,3);booking=await owner.rpc('changeBooking',{scope,id:booking.id,version:booking.version,candidate});assert.equal(booking.priceMinor,1900);assert.equal(booking.durationMin,45);await client.denied('cancelBooking',{id:booking.id,version:oldVersion,reason:'Stale test'},'VERSION_CONFLICT');assert.equal((await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===booking.id).startAt,booking.startAt);});
  await check('Reception access is scoped and revocation affects existing session',async()=>{const existing=(await workspace()).memberships.find(m=>m.accountId==='demo-client-44-new');assert.ok(!existing||existing.active===false,'Reception test membership must be absent or revoked');grant=await owner.rpc('grantMembership',{organizationId,email:'profile-client-44@example.com',role:'reception',version:existing?.version||0});assert.ok((await member.rpc('workspace',scope)).bookings.some(b=>b.id===booking.id));await member.denied('saveOffer',{id:offer.id,version:offer.version,label:'Forbidden',variants:[variant]},'FORBIDDEN');grant=await owner.rpc('revokeMembership',{id:grant.id,version:grant.version});await member.denied('workspace',scope,'FORBIDDEN');});
  await check('Ordered multi-service visit includes addon and one atomic snapshot',async()=>{const second=(await guest.rpc('catalog')).find(s=>s.id===secondVariant.id);assert.ok(second);const items=[{providerServiceId:variantId,practitionerId:practitioner.id,addons:[run+'-addon']},{providerServiceId:second.id,practitionerId:second.practitionerId,addons:[]}],availability=await client.rpc('visitAvailability',{items,dayOffset:4,from:540,to:1200});assert.ok(availability.slots.length);held=await client.rpc('holdVisit',availability.slots[0]);const input={holdId:held.id,name:'Fiktyvus kelių procedūrų klientas',idempotencyKey:run+'-whole-visit'},visit=await client.rpc('confirmVisit',input);extraBookings.push(visit);held=null;assert.equal(visit.items.length,2);assert.deepEqual(visit.items.map(i=>i.providerServiceId),items.map(i=>i.providerServiceId));assert.equal(visit.priceMinor,2200+second.priceMinor);assert.equal(visit.durationMin,60+second.durationMin);assert.equal((await client.rpc('confirmVisit',input)).id,visit.id);assert.equal((await workspace()).bookings.find(b=>b.id===visit.id).items.length,2);extraBookings[0]=await client.rpc('cancelBooking',{id:visit.id,version:visit.version,reason:'Fiktyvaus viso vizito bandymo užbaigimas.'});});
  await check('Owner busy block removes the slot and release restores it',async()=>{const chosen=await slot(variantId,5),local=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Vilnius',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(chosen.startAt)),[hour,minute]=local.split(':').map(Number),from=hour*60+minute;busyBlock=await owner.rpc('createBusyBlock',{organizationId,practitionerId:practitioner.id,dayOffset:5,from,to:from+45,label:'Fiktyvus kalendoriaus bandymas'});await client.denied('hold',chosen,'SLOT_CONFLICT');assert.ok(!(await client.rpc('availability',{providerServiceId:variantId,dayOffset:5,from:540,to:1200,addons:[]})).slots.some(s=>s.startAt===chosen.startAt));await foreign.denied('releaseBusyBlock',{id:busyBlock.id,version:busyBlock.version},'FORBIDDEN');busyBlock=await owner.rpc('releaseBusyBlock',{id:busyBlock.id,version:busyBlock.version});assert.ok((await client.rpc('availability',{providerServiceId:variantId,dayOffset:5,from:540,to:1200,addons:[]})).slots.some(s=>s.startAt===chosen.startAt));});
  await check('Private client card is scoped; stale write cannot replace it',async()=>{const current=((await workspace()).clientCards||[]).find(c=>c.clientId===booking.clientId);const input={organizationId,clientId:booking.clientId,version:current?.version||0,name:'Fiktyvus bandymo klientas',note:'Automatinis funkcinės patikros įrašas.'};await foreign.denied('saveClientCard',input,'FORBIDDEN');const card=await owner.rpc('saveClientCard',input);await owner.denied('saveClientCard',input,'VERSION_CONFLICT');assert.ok(!(await foreign.rpc('workspace',{role:'professional',organizationId:'demo-org-44'})).clientCards?.some(c=>c.id===card.id));});
  await check('Notification preferences stay separate from marketing',async()=>{const value=await client.rpc('preferences',{service:false,marketing:false,reminderLeadMin:0});assert.equal(value.service,false);assert.equal(value.marketing,false);assert.equal(value.reminderLeadMin,0);});
  await check('Own data export excludes another client and internal card actor',async()=>{const value=await client.rpc('exportCustomer');assert.equal(value.client.id,booking.clientId);assert.ok(value.bookings.every(b=>b.clientId===booking.clientId));assert.ok(value.organizationCards.every(c=>c.updatedBy===undefined));assert.ok(value.bookings.some(b=>b.id===booking.id));});
  await check('Repeated erasure request keeps the same safe customer projection',async()=>{const own=(await client.request('session')).value;const input={confirmEmail:own.user.email};request=await client.rpc('requestErasure',input);assert.equal(request.actions,undefined);const replay=await client.rpc('requestErasure',input);assert.equal(replay.id,request.id);assert.equal(replay.actions,undefined);await member.denied('withdrawErasure',{id:request.id,version:request.version},'FORBIDDEN');});
  await check('Erasure case review retains future visit; customer can withdraw',async()=>{await owner.denied('erasureCase',{id:request.id},'FORBIDDEN');const review=await operator.rpc('erasureCase',{id:request.id});assert.equal(review.executionEnabled,false);assert.ok(review.futureBookings.some(b=>b.id===booking.id));request=await operator.rpc('reviewErasure',{id:request.id,version:request.version,state:'retention-review',reason:'Fiktyvi funkcinė patikra.',retentionBasis:'Bandymo aplinka; tikrų duomenų trynimas nevykdomas.'});await client.denied('withdrawErasure',{id:request.id,version:1},'VERSION_CONFLICT');request=await client.rpc('withdrawErasure',{id:request.id,version:request.version});assert.equal(request.state,'withdrawn');});
  await check('Booking closure cannot hide a confirmed visit',async()=>{const current=(await workspace()).organizations.find(o=>o.id===organizationId),dateKey=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(booking.startAt));await owner.denied('saveBookingRules',{organizationId,version:current.version,...originalRules,closedDates:[dateKey]},'SCHEDULE_CONFLICT');assert.equal((await workspace()).bookings.find(b=>b.id===booking.id).status,'confirmed');});
  await check('Owner report excludes client email/contact values',async()=>{const from=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(startedAt)),to=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Vilnius',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.parse(startedAt)+7*86400000));const value=await owner.rpc('organizationReport',{organizationId,from,to});assert.ok(!JSON.stringify(value).includes('@example.com'));await foreign.denied('organizationReport',{organizationId,from,to},'FORBIDDEN');});
  await check('Cancellation and archived offer preserve historical snapshot',async()=>{booking=await client.rpc('cancelBooking',{id:booking.id,version:booking.version,reason:'Fiktyvi operacijų patikra baigta.'});assert.equal(booking.status,'canceled');offer=await owner.rpc('archiveOffer',{id:offer.id,version:offer.version});assert.ok(!(await guest.rpc('catalog')).some(s=>s.id===variantId));const repeat=await client.rpc('rebooking',{id:booking.id});assert.equal(repeat.state,'unavailable');assert.equal((await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===booking.id).serviceSnapshot.priceMinor,1900);assert.deepEqual((await guest.rpc('catalog')).filter(s=>s.organizationId===organizationId).map(s=>s.id).sort(),basePublic);});
 }catch(error){failure=error;}
 finally{
  if(held)await cleanupStep('Release own test hold',()=>client.rpc('releaseHold',{id:held.id}));
  for(const visit of extraBookings)if(visit.status==='confirmed')await cleanupStep('Cancel own multi-service test booking',async()=>{const current=(await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===visit.id);if(current?.status==='confirmed')await client.rpc('cancelBooking',{id:current.id,version:current.version,reason:'Fiktyvios kelių paslaugų patikros užbaigimas.'});});
  if(busyBlock?.active)await cleanupStep('Release own test calendar block',async()=>{const current=(await workspace()).busyBlocks.find(b=>b.id===busyBlock.id);if(current?.active)await owner.rpc('releaseBusyBlock',{id:current.id,version:current.version});});
  if(booking&&booking.status==='confirmed')await cleanupStep('Cancel own test booking',async()=>{const current=(await client.rpc('workspace',{role:'customer'})).bookings.find(b=>b.id===booking.id);if(current.status==='confirmed')booking=await client.rpc('cancelBooking',{id:current.id,version:current.version,reason:'Fiktyvios patikros užbaigimas.'});});
  if(offer&&offer.state!=='archived')await cleanupStep('Archive own test offer',async()=>{const current=(await workspace()).offers.find(o=>o.id===offer.id);if(current.state!=='archived')offer=await owner.rpc('archiveOffer',{id:current.id,version:current.version});});
  if(grant&&grant.active!==false)await cleanupStep('Revoke own test membership',async()=>{const current=(await workspace()).memberships.find(m=>m.id===grant.id);if(current&&current.active!==false)await owner.rpc('revokeMembership',{id:current.id,version:current.version});});
  if(request&&!['withdrawn','completed'].includes(request.state))await cleanupStep('Withdraw own erasure request',async()=>{const current=(await client.rpc('workspace',{role:'customer'})).dataRequests.find(r=>r.id===request.id);if(current&&!['withdrawn','completed'].includes(current.state))await client.rpc('withdrawErasure',{id:current.id,version:current.version});});
  if(originalPreferences)await cleanupStep('Restore prior test preferences',()=>client.rpc('preferences',{service:originalPreferences.service,marketing:originalPreferences.marketing,reminderLeadMin:originalPreferences.reminderLeadMin}));
 }
 return {state:failure||cleanup.some(c=>c.state==='FAIL')?'FAIL':'PASS',startedAt,finishedAt:new Date().toISOString(),origin:trialOrigin,checks,cleanup,bookingId:booking?.id,offerId:offer?.id,bookingState:booking?.status,offerState:offer?.state,smtp:false,erasureExecuted:false,error:failure?{name:failure.name,code:failure.code,message:failure.message}:null};
}
