(()=>{'use strict';
 const $=s=>document.querySelector(s),main=$('#main'),path=location.pathname.replace(/\/$/,'')||'/account',isCreator=path.startsWith('/creator/'),creatorWorkspace=path==='/creator'||isCreator;
 const query=new URLSearchParams(location.search),days=[7,30,90].includes(Number(query.get('days')))?Number(query.get('days')):30;
 let account,creator,applicationTermsVersion,currency=query.get('currency')||'usd',toastTimer;
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
 const money=(value,c=currency)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c.toUpperCase(),currencyDisplay:'narrowSymbol'}).format(value/100);
 const date=v=>new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
 const paths={home:'M3 10 12 3l9 7v10H3z M9 20v-7h6v7',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',chart:'M4 20V12 M10 20V8 M16 20V4 M22 20H2',wallet:'M3 6h17v14H3z M3 6V3h14 M15 11h6v5h-6z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18 M12 7v6l4 2',cart:'M2 3h3l3 12h11l3-9H6 M9 21h.01 M18 21h.01',trend:'M3 18l6-6 4 3 8-10 M15 5h6v6',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',key:'M15 4a5 5 0 1 0 0 10 5 5 0 1 0 0-10 M11 12l-8 8v2h5v-4h4',help:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18 M9 9a3 3 0 1 1 4 3l-1 1v2 M12 18h.01',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',image:'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5 M15 7h.01',play:'M3 5h18v14H3z M10 8l6 4-6 4z',user:'M12 3a4 4 0 1 0 0 8 4 4 0 1 0 0-8 M4 21v-3a8 8 0 0 1 16 0v3',check:'M4 12l5 5L20 6',arrow:'M4 12h16 M14 6l6 6-6 6',copy:'M8 8h13v13H8z M3 16V3h13'};
 const icon=id=>`<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[id]||paths.home}"></path></svg>`;
 const button=(label,href,kind='secondary')=>`<a class="button ${kind}" href="${esc(href)}">${label}${icon('arrow')}</a>`;
 const badge=(text)=>{const s=String(text||'Unknown'),type=/pending|reserved|unfulfilled|open|creating/i.test(s)?'pending':/review|suspended|reversed|revoked|disputed|refunded|failed|rejected/i.test(s)?'danger':/paid|active|available|fulfilled|approved/i.test(s)?'':'neutral';return `<span class="badge ${type}"><span class="status-dot" aria-hidden="true"></span>${esc(s.charAt(0).toUpperCase()+s.slice(1))}</span>`;};
 const empty=(title,text,action='',i='cart')=>`<div class="empty">${icon(i)}<h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;
 const header=(title,subtitle,controls='')=>`<div class="page-heading"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${controls?`<div class="heading-controls">${controls}</div>`:''}</div>`;
 const cardHeader=(title,subtitle='',i='home',action='')=>`<div class="card-header"><div class="card-title">${icon(i)}<div><h2>${esc(title)}</h2>${subtitle?`<p class="hint">${esc(subtitle)}</p>`:''}</div></div>${action}</div>`;
 const fields=(label,name,type='text',value='',extra='')=>`<label class="field">${label}<input type="${type}" name="${name}" value="${esc(value)}" ${extra}></label>`;
 const status='<p class="form-status" role="status" data-form-status></p>';
 async function api(url,body){const r=await fetch(url,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw Object.assign(Error('This service is temporarily unavailable. Please try again.'),{status:r.status});}if(!r.ok)throw Object.assign(Error(d.error||'Please try again.'),{status:r.status});return d;}
 function toast(text){clearTimeout(toastTimer);const t=$('[data-toast]');t.textContent=text;t.hidden=false;toastTimer=setTimeout(()=>t.hidden=true,4000);}
 function navigation(){
  $('[data-avatar]').textContent=(account.profile.name||account.user.email).slice(0,1).toUpperCase();
  $('[data-switch]').innerHTML=`<a class="workspace-choice ${creatorWorkspace?'':'active'}" href="/account">${icon('user')}<span><strong>Customer</strong><small>Your app &amp; orders</small></span></a>${account.creator.approved?`<a class="workspace-choice ${creatorWorkspace?'active':''}" href="/creator">${icon('chart')}<span><strong>Creator</strong><small>Your links &amp; earnings</small></span></a>`:`<a class="workspace-choice" href="/creators/apply">${icon('chart')}<span><strong>Creator program</strong><small>${account.creator.applicationStatus==='pending'?'Application in review':'Share your workspace'}</small></span></a>`}`;
  const items=creatorWorkspace?[['Overview','/creator','home'],['Links','/creator/links','link'],['Performance','/creator/performance','chart'],['Referrals','/creator/referrals','user'],['Earnings','/creator/earnings','wallet'],['Payouts','/creator/payouts','wallet'],['Media kit','/creator/media-kit','image'],['Content','/creator/content','play'],['Settings','/creator/settings','settings']]:[['Overview','/account','home'],['Downloads','/account/downloads','download'],['Licences','/account/licences','key'],['Orders','/account/orders','cart'],['Support','/account/support','help'],['Settings','/account/settings','settings']];
  $('[data-nav]').innerHTML=items.map(([label,href,i])=>{const active=path===href||href==='/account/orders'&&path.startsWith(href+'/');return `<a class="nav-link ${active?'active':''}" href="${href}" ${active?'aria-current="page"':''}>${icon(i)}${label}</a>`;}).join('');
  const current=items.find(v=>v[1]===path)||[path.startsWith('/account/orders/')?'Order details':path==='/creators/apply'?'Creator application':'Workspace'];
  $('[data-breadcrumb]').innerHTML=`${creatorWorkspace?'Creator':'Account'} <span>/</span> <strong>${esc(current[0])}</strong>`;document.title=current[0]+' — PhoneBridger';
 }
 function orderRows(orders){if(!orders.length)return empty('Your first setup starts here','Your orders will appear here after you open checkout.',button('Explore setups','/shop','outline'));
  return `<div class="table-wrap responsive-records"><table class="records"><thead><tr><th>Order</th><th>Setup</th><th>Total</th><th>Payment</th><th>Hardware</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>PB-${esc(o.id.slice(0,6).toUpperCase())}</strong><br><span class="hint">${date(o.created_at)}</span></td><td>${o.holders?`App + ${o.holders} holder${o.holders===1?'':'s'}`:'App only'}</td><td><strong>${money(o.subtotal+o.shipping,o.currency)}</strong> <span class="hint">${esc(o.currency.toUpperCase())}</span></td><td>${badge(o.status)}</td><td>${o.holders?badge(o.fulfilment):'<span class="hint">No hardware</span>'}</td><td><a class="text-link" href="/account/orders/${esc(o.id)}">View order</a></td></tr>`).join('')}</tbody></table></div><div class="record-stack">${orders.map(o=>`<details class="record-detail"><summary><strong>PB-${esc(o.id.slice(0,6).toUpperCase())}</strong><span>${money(o.subtotal+o.shipping,o.currency)}</span></summary><dl class="detail-grid"><div><dt>Date</dt><dd>${date(o.created_at)}</dd></div><div><dt>Payment</dt><dd>${badge(o.status)}</dd></div><div><dt>Setup</dt><dd>${o.holders?`App + ${o.holders} holders`:'App only'}</dd></div><div><dt>Hardware</dt><dd>${o.holders?badge(o.fulfilment):'No hardware'}</dd></div></dl><a class="text-link" href="/account/orders/${esc(o.id)}">View order ${icon('arrow')}</a></details>`).join('')}</div>`;
 }
 const downloadActions=()=>`${account.downloads.windows?button('Download for Windows',account.downloads.windows.url,'primary'):button('Windows downloads','/downloads','primary')}${account.downloads.android?button('Android companion',account.downloads.android.url):button('Android downloads','/downloads')}`;
 function overview(){
  const name=account.profile.name?`, ${account.profile.name}`:'',latest=account.orders[0];
  const steps=[['windows','Download the Windows app','/account/downloads'],['android','Install the Android companion','/account/downloads'],['permissions','Enable Android permissions','/guides/android-permissions'],['pairing','Pair your first phone','/guides/getting-started']];
  return header('Welcome back'+name+'.','A little more room for your day.')+`<div class="grid cols"><div><section class="card download-hero"><div><div class="eyebrow">YOUR WORKSPACE, CONNECTED</div><h2>One mouse. More possibilities.</h2><p>Bring Windows and Android together. Start with the apps, then make your desk your own.</p><div class="actions">${downloadActions()}</div><p class="hint" style="margin:16px 0 0">Free beta · USB + Wi-Fi · Up to three phones</p></div><img class="downloads-art" src="/assets/closing-conversion-v1/software-package-pink-v1-640.webp" alt="PhoneBridger software package" width="220" height="220"></section><section class="card">${cardHeader('Your latest order','Payment and delivery are tracked separately.','cart',`<a class="text-link" href="/account/orders">All orders →</a>`)}${latest?orderRows([latest]):empty('Make yourself at home','No orders on this account yet. You can start with the free beta.',button('Choose your setup','/shop','outline'))}</section></div><div><section class="card">${cardHeader('Make your first connection','Four small steps to a bigger workspace.','check')}<ul class="checklist">${steps.map(([id,label,url])=>`<li><label><input type="checkbox" data-setup="${id}" ${account.profile.setup.includes(id)?'checked':''}><span>${label}<a href="${url}" aria-label="Guide: ${label}">↗</a></span></label></li>`).join('')}</ul><p class="hint">Your personal checklist. Website login does not detect an installed app or a connected phone.</p></section><section class="card">${cardHeader('We’re here to help','A smooth setup starts with a little guidance.','help')}<p class="muted" style="font-size:12px;margin-bottom:20px">Explore the setup guides or send us a support request from your account.</p>${button('Get setup help','/account/support','outline')}</section></div></div>`;
 }
 function downloads(){return header('Your apps. Your workspace.','Download the published beta and follow the setup guide.')+`<div class="grid equal">${['windows','android'].map(platform=>{const d=account.downloads[platform];return `<section class="card"><div class="release-row">${icon(platform==='windows'?'download':'play')}<div><div class="eyebrow">${platform==='windows'?'WINDOWS DESKTOP':'ANDROID COMPANION'}</div><h2>${platform==='windows'?'PhoneBridger for Windows':'Your phone, right beside you'}</h2><p class="muted">${platform==='windows'?'Unzip the package and open the Windows app.':'Install the APK and enable the required permissions.'}</p><div class="divider"></div>${d?`<p class="hint">Published file</p><p class="order-ref">${esc(d.filename)}</p><p class="hint" style="margin:8px 0 20px">${(d.bytes/1048576).toFixed(1)} MB · ${d.version?'Version '+esc(d.version):'Current published beta'}</p>${button('Download '+(platform==='windows'?'Windows app':'Android companion'),d.url,'primary')}<p class="checksum">SHA-256<br>${esc(d.sha256)}</p>`:empty('Download metadata unavailable','Use the public download page for the published files.',button('Open downloads','/downloads','outline'),'download')}</div></div></section>`;}).join('')}</div><section class="card" style="margin-top:20px">${cardHeader('Your next steps','USB is preferred automatically; Wi-Fi provides a fallback.','check')}<div class="actions">${button('Getting started','/guides/getting-started')}${button('Android permissions','/guides/android-permissions')}${button('USB & Wi-Fi guide','/guides/usb-wifi')}</div><p class="hint" style="margin-top:18px">These are the published release files. The account does not infer native activation or device status. Release version details appear on the public downloads page.</p></section>`;}
 function licences(){return header('Your licences','Purchase entitlements associated with this account.')+`<section class="card">${cardHeader('Website purchase records','Native activation and device slots are not connected yet.','key')}${account.licences.length?`<ul class="list">${account.licences.map(l=>`<li><div class="left"><strong>PhoneBridger V1</strong><p>${esc(l.licence_reference)}</p><p>Order PB-${esc(l.order_id.slice(0,6).toUpperCase())} · ${date(l.created_at)}</p></div>${badge(l.status)}${l.status==='active'&&l.payment_status==='paid'?button('Download record','/api/shop/licence?id='+l.order_id,'outline'):button('View order','/account/orders/'+l.order_id)}</li>`).join('')}</ul>`:empty('No purchase entitlement yet','Your website licence record appears after a confirmed payment. The free beta is available to try.',button('Download the beta','/account/downloads','outline'),'key')}</section>`;}
 async function orderDetail(id){const d=await api('/api/shop/order?id='+encodeURIComponent(id)),o=d.order,e=d.entitlement,delivery=d.delivery;return header('Your order','PB-'+o.id.slice(0,6).toUpperCase(),button('Back to orders','/account/orders'))+`<div class="grid cols"><section class="card">${cardHeader(o.holders?`App + ${o.holders} holder${o.holders===1?'':'s'}`:'App only','Created '+date(o.created_at),'cart',badge(o.status))}<dl class="detail-grid"><div><dt>Order reference</dt><dd class="order-ref">${esc(o.id)}</dd></div><div><dt>Purchase terms</dt><dd>${esc(o.policy_version)}</dd></div><div><dt>Merchandise</dt><dd>${money(o.subtotal,o.currency)}</dd></div><div><dt>Shipping</dt><dd>${money(o.shipping,o.currency)}</dd></div><div><dt>Total (${esc(o.currency.toUpperCase())})</dt><dd><strong>${money(o.subtotal+o.shipping,o.currency)}</strong></dd></div><div><dt>Finish</dt><dd>${o.holders?esc(o.finish):'No hardware'}</dd></div></dl><div class="divider"></div><h3>Digital delivery</h3><p class="muted" style="margin:10px 0 18px">${e?`Website entitlement: ${esc(e.status)}. This record is not a native activation key.`:'A licence record is issued after verified payment.'}</p><div class="actions">${e?.status==='active'&&o.status==='paid'?button('Download licence record','/api/shop/licence?id='+o.id,'primary'):''}${o.paid_at?button('Download payment summary','/api/shop/receipt?id='+o.id):''}</div><p class="hint" style="margin-top:15px">A payment summary is not a VAT invoice.</p></section><div><section class="card">${cardHeader('Hardware delivery','Actual fulfilment updates appear here.','cart')}${o.holders?`${badge(o.fulfilment)}${delivery?`<dl class="detail-grid"><div><dt>Carrier</dt><dd>${esc(delivery.carrier)}</dd></div><div><dt>Tracking reference</dt><dd>${esc(delivery.tracking_number)}</dd></div><div><dt>Dispatched</dt><dd>${date(delivery.dispatched_at)}</dd></div><div><dt>Delivered</dt><dd>${delivery.delivered_at?date(delivery.delivered_at):'Not confirmed'}</dd></div></dl>${/^https:\/\//.test(delivery.tracking_url)?`<a class="button outline" href="${esc(delivery.tracking_url)}" target="_blank" rel="noopener noreferrer">Track delivery ↗</a>`:''}`:'<p class="hint" style="margin-top:15px">Tracking is added when your order is dispatched. No arrival date is confirmed yet.</p>'}`:'<p class="muted">This setup includes software only.</p>'}</section><section class="card">${cardHeader('Need help with this order?','A request does not itself issue a refund.','help')}<div class="actions">${button('Ask about this order','/account/support?order='+o.id,'outline')}${button('Request cancellation','/contact?action=withdraw&topic=account')}</div></section></div></div>${d.mode==='test'?'<p class="notice" style="margin-top:20px">Sandbox order. No money, licence or physical goods supplied.</p>':''}`;}
 async function support(){const d=await api('/api/workspace/support'),selected=query.get('order');return header('A little help, when you need it','Send a request or follow up on a saved conversation.')+`<div class="grid equal"><section class="card">${cardHeader('What can we help with?','Please leave passwords and payment details out.','help')}<form data-form="support" class="form-grid">${fields('Subject','subject','text','', 'required minlength="3" maxlength="120"')}<label class="field">Order (optional)<select name="orderId" style="width:100%"><option value="">General setup or account question</option>${account.orders.map(o=>`<option value="${esc(o.id)}" ${o.id===selected?'selected':''}>PB-${esc(o.id.slice(0,6).toUpperCase())} · ${date(o.created_at)}</option>`).join('')}</select></label><label class="field">Your message<textarea name="message" required minlength="10" maxlength="3000" placeholder="Tell us what happened and what you’ve tried."></textarea></label><details class="record-detail"><summary>Optional diagnostics attachment</summary><div class="form-grid" style="margin-top:15px"><p class="hint">Choose a .txt or .json file, up to 8 KB. Review it before attaching. Common tokens, emails and user paths are redacted; do not attach sensitive details.</p><label class="field">Choose diagnostics<input type="file" accept=".txt,.json,text/plain,application/json" data-diagnostics-file></label><label class="field">Review attachment<textarea name="diagnostics" maxlength="8000" data-diagnostics></textarea></label><label class="checkbox-label"><input type="checkbox" name="diagnosticsConsent">I choose to include the reviewed diagnostics in this request.</label></div></details><button class="button primary" type="submit">Save support request ${icon('arrow')}</button>${status}</form></section><section class="card">${cardHeader('Your requests','Saved to this account.','clock')}${d.tickets.length?d.tickets.map(ticket=>`<details class="record-detail"><summary><strong>${esc(ticket.subject)}</strong>${badge(ticket.status)}</summary><p class="hint" style="margin-top:15px">${date(ticket.created_at)} · ${esc(ticket.id)}</p><p class="ticket-body">${esc(ticket.message)}</p>${d.replies.filter(r=>r.ticket_id===ticket.id).map(r=>`<div class="divider"></div><p class="hint">${r.sender==='support'?'PhoneBridger support':'You'} · ${date(r.created_at)}</p><p class="ticket-body">${esc(r.message)}</p>`).join('')}</details>`).join(''):empty('A fresh start','No support requests yet. Our guides can help with common setup questions.',button('Browse guides','/guides','outline'),'help')}<p class="hint" style="margin-top:20px">Requests are stored securely. Email notifications are not enabled yet. Support replies appear here after review. For urgent follow-up, contact hello@phonebridger.com with your request reference.</p></section></div>`;}
 function settings(){return header('Account settings','The essentials, kept simple.')+`<div class="grid equal"><section class="card">${cardHeader('Your profile','One account for customer and creator access.','user')}<form class="form-grid" data-form="profile">${fields('Display name','name','text',account.profile.name,'maxlength="80"')}<label class="field">Email<input value="${esc(account.user.email)}" readonly autocomplete="email"><span class="hint">Email is unverified. Email change and automatic recovery are not enabled.</span></label><button class="button primary" type="submit">Save profile</button>${status}</form><div class="divider"></div><h3>Notifications</h3><p class="hint" style="margin-top:10px">Email notifications are not connected yet. No marketing subscription is created by your account.</p></section><section class="card">${cardHeader('Keep your account secure','Changing your password revokes other sessions.','key')}<form class="form-grid" data-form="password">${fields('Current password','currentPassword','password','','required maxlength="128" autocomplete="current-password"')}${fields('New password','newPassword','password','','required minlength="6" maxlength="128" autocomplete="new-password"')}<button class="button outline" type="submit">Change password</button>${status}</form><div class="divider"></div><h3>Active sessions</h3>${account.sessions.map(s=>`<div class="session-row"><span>${s.current?'This session':'Another session'}</span><small>Expires ${date(s.expiresAt)} at ${new Date(s.expiresAt).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')}<button class="button small" type="button" data-revoke style="margin-top:18px">Sign out other sessions</button></section></div>`;}
 const proposal=()=>`<div class="proposal"><div><strong>${creator?.terms.commissionBps/100||25}%</strong><small>Proposed commission</small></div><div><strong>${creator?.terms.audienceDiscountBps/100||5}%</strong><small>Proposed code discount</small></div><div><strong>30 days</strong><small>Proposed attribution</small></div></div><p class="hint">Eligible merchandise actually paid after discount, excluding taxes and shipping. First qualifying new-customer purchase; no self-referrals. Digital hold: 30 days. Hardware hold: the later of sale +30 days or delivery +14 days. Refunds and chargebacks reverse commissions proportionally. Proposed monthly payout: the 15th, from USD 25. No automatic higher tier.</p>`;
 async function application(){const d=await api('/api/creator/application');applicationTermsVersion=d.terms.version;return header('Share your workspace. Build your impact.','Apply to the PhoneBridger creator program.')+`<div class="grid cols"><section class="card">${cardHeader('Tell us about your content','Creator access is reviewed separately from purchases.','chart')}${d.application?`<p style="margin-bottom:18px">Your application is ${badge(d.application.status)}</p><dl class="detail-grid"><div><dt>Submitted</dt><dd>${date(d.application.created_at)}</dd></div><div><dt>Audience</dt><dd>${esc(d.application.audience)}</dd></div></dl><p class="hint">Channels</p><p style="overflow-wrap:anywhere;margin:8px 0 20px">${esc(d.application.channels)}</p>${d.application.status==='approved'?button('Open creator workspace','/creator','primary'):button('Contact us about your application','/account/support','outline')}`:`<form class="form-grid" data-form="application"><label class="field">Your channels<textarea name="channels" placeholder="https://youtube.com/@yourchannel" required maxlength="1000"></textarea><span class="hint">Up to five public HTTPS channel URLs, separated by a space or new line.</span></label>${fields('Your audience','audience','text','','required minlength="2" maxlength="200" placeholder="Who watches or reads your content?"')}<label class="field">How would you introduce PhoneBridger? (optional)<textarea name="message" maxlength="1000"></textarea></label><label class="checkbox-label"><input type="checkbox" name="consent" required>I agree to submit these channel and audience details for application review. Financial terms are a proposal; applying does not activate commissions or discounts.</label><button class="button primary" type="submit">Submit application ${icon('arrow')}</button>${status}</form>`}</section><section class="card"><div class="eyebrow">PROGRAM PROPOSAL · ${esc(d.terms.version)}</div><h2>A clear starting point</h2>${proposal()}<div class="divider"></div><p class="notice info">Live commissions, discounts and payouts are not enabled. Final financial terms require owner approval.</p><p class="hint">Create useful, accurate content. Disclose your creator relationship. Do not promise features, shipping times or earnings that have not been confirmed.</p></section></div>`;}
 const balance=(bucket)=>creator.balances[currency]?.[bucket]||0;
 const ledgerFor=()=>creator.ledger.filter(r=>r.currency===currency);
 function ledgerTable(records,limit){const filter=query.get('status')||'',data=records.filter(r=>!filter||(r.balances[filter]||0)>0).slice(0,limit||200);if(!data.length)return empty('Your impact starts with a link','Qualified paid orders will appear here with their commission and eligibility status.',button('Create a referral link','/creator/links','outline'),'link');
  const statuses=r=>Object.entries(r.balances).filter(([_,n])=>n>0).map(([s])=>badge(s)).join(' ');
  return `<div class="table-wrap responsive-records"><table class="records"><thead><tr><th>Date</th><th>Order reference</th><th>Setup</th><th>Commission</th><th>Status</th></tr></thead><tbody>${data.map(r=>`<tr><td>${date(r.paidAt)}</td><td><strong>${esc(r.reference)}</strong></td><td>${r.holders?`App + ${r.holders} holder${r.holders===1?'':'s'}`:'App only'}</td><td><strong>${money(r.amount,r.currency)}</strong><br><span class="hint">${r.rateBps/100}% of ${money(r.basis,r.currency)}</span></td><td>${statuses(r)}</td></tr>`).join('')}</tbody></table></div><div class="record-stack">${data.map(r=>`<details class="record-detail"><summary><strong>${esc(r.reference)}</strong><span>${money(r.amount,r.currency)}</span></summary><dl class="detail-grid"><div><dt>Date</dt><dd>${date(r.paidAt)}</dd></div><div><dt>Status</dt><dd>${statuses(r)}</dd></div><div><dt>Eligible paid merchandise</dt><dd>${money(r.basis,r.currency)}</dd></div><div><dt>Rate</dt><dd>${r.rateBps/100}%</dd></div><div><dt>Terms version</dt><dd>${esc(r.termsVersion)}</dd></div><div><dt>Setup</dt><dd>${r.holders?`App + ${r.holders} holders`:'App only'}</dd></div></dl></details>`).join('')}</div>`;
 }
 function controls(){const currencies=[...new Set(['usd',...Object.keys(creator.balances),...creator.ledger.map(r=>r.currency)])];return `<label class="hint"><span class="sr-only">Currency</span><select data-currency aria-label="Currency">${currencies.map(c=>`<option value="${esc(c)}" ${currency===c?'selected':''}>${esc(c.toUpperCase())}</option>`).join('')}</select></label><select data-days aria-label="Reporting period">${[7,30,90].map(n=>`<option value="${n}" ${days===n?'selected':''}>Last ${n} days</option>`).join('')}</select>${creator.financiallyActive?'<span class="tag">Sandbox data</span>':'<span class="tag">Program not active</span>'}`;}
 function referralCard(){const link=creator.links.find(l=>l.active);return `<section class="card referral-card"><div class="referral-intro">${icon('link')}<div><h2>Your referral link</h2><p>A clear path from your content to their workspace.</p></div></div>${link?`<div class="copy-field"><input aria-label="Your referral link" value="${esc(link.url)}" readonly><button class="button primary" type="button" data-copy="${esc(link.url)}">${icon('copy')}Copy link</button></div>`:`<div>${button('Create your first link','/creator/links','primary')}</div>`}<div class="referral-code"><strong>${esc(creator.partner.code)}</strong><button type="button" data-copy="${esc(creator.partner.code)}">Copy code</button><p class="hint">${creator.financiallyActive?'Sandbox code · 5% off':'Discount not active'}</p></div></section>`;}
 function metric(label,value,note,i,target){return `<a class="metric" href="${target}">${icon(i)}<div><span class="metric-label">${label}</span><strong>${value}</strong><small>${note}</small></div></a>`;}
 function chart(){const dailySeries=creator.daily.filter(r=>r.currency===currency),total=dailySeries.reduce((n,r)=>n+r.amount,0);let visual;
  if(!dailySeries.length)visual=`<div class="chart-empty">${icon('trend')}<h3>Room for your first commission</h3><p class="hint">Your qualified earnings will build this chart over time.</p></div>`;
  else{const values=Array(days).fill(0),end=new Date();end.setUTCHours(0,0,0,0);const start=end.getTime()-(days-1)*86400000;dailySeries.forEach(r=>{const i=Math.floor((r.day*86400000-start)/86400000);if(i>=0&&i<days)values[i]+=r.amount;});const max=Math.max(...values,100),points=values.map((v,i)=>`${50+i/(days-1)*680},${200-v/max*150}`),ticks=[0,.5,1].map(v=>`<path d="M50 ${200-v*150}H730" stroke="#2a2d35"/><text x="3" y="${204-v*150}">${esc(money(Math.round(max*v)))}</text>`).join('');visual=`<svg class="chart" viewBox="0 0 760 240" role="img" aria-label="Daily qualified commissions for the last ${days} days, total ${esc(money(total))} ${esc(currency.toUpperCase())}"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ff2d9a" stop-opacity=".22"/><stop offset="1" stop-color="#ff2d9a" stop-opacity=".01"/></linearGradient></defs>${ticks}<path d="M50 200 L${points.join(' L')} L730 200Z" fill="url(#chart-fill)"/><polyline points="${points.join(' ')}" fill="none" stroke="#ff2d9a" stroke-width="3" stroke-linejoin="round"/><text x="50" y="228">${date(start).replace(', '+new Date().getFullYear(),'')}</text><text x="370" y="228">${date(start+Math.floor(days/2)*86400000).replace(', '+new Date().getFullYear(),'')}</text><text x="660" y="228">${date(end).replace(', '+new Date().getFullYear(),'')}</text></svg>`;}
  return `<section class="card">${cardHeader('Commission earnings','Qualified commissions at the frozen purchase rate.','chart',`<div class="chart-total"><span class="hint">${days}-day total · ${esc(currency.toUpperCase())}</span><strong>${money(total)}</strong></div>`)}${visual}<div class="chart-legend">Commission granted in this period, before later reversals.</div></section>`;
 }
 function payoutCard(){return `<section class="card">${cardHeader('Your next payout','Understand what is eligible and what comes next.','wallet')}<div class="payout-summary"><div><span class="hint">Available · ${esc(currency.toUpperCase())}</span><strong>${money(balance('Available'))}</strong></div><div><span class="hint">Payout method</span>${badge('Not connected')}</div></div><button class="button outline full" type="button" disabled aria-describedby="payout-method-note">Add payout method</button><p id="payout-method-note" class="hint" style="margin-top:10px">Provider onboarding is not enabled yet. No transfer can be requested from this workspace.</p><div class="divider"></div><div class="payout-details"><div><span class="hint">Proposed schedule</span><strong>Monthly, on the 15th</strong><span class="hint">Minimum USD 25</span></div><div><span class="hint">Proposed commission</span><strong>${creator.terms.commissionBps/100}%</strong><span class="hint">Subject to final approval</span></div></div></section>`;}
 function resourcesCard(){return `<section class="card">${cardHeader('Made for your next story','A few useful things to get you started.','image')}<div class="media-preview"><div class="media-tile logo"><img src="/assets/brand-mark.svg" alt="PhoneBridger logo"><small>Brand mark · SVG</small></div><div class="media-tile"><img src="/assets/closing-conversion-v1/holder-black-640.webp" alt="Black magnetic holder"><small>Product · WebP</small></div><div class="media-tile"><img src="/assets/closing-conversion-v1/software-package-pink-v1-320.webp" alt="Software package"><small>Software · WebP</small></div></div>${button('Explore the media kit','/creator/media-kit','outline')}</section>`;}
 function creatorOverview(){const m=creator.metrics;return header('Creator overview','Your links. Your impact. Your earnings.',controls())+referralCard()+`<div class="metrics">${metric('Available',money(balance('Available')),'Eligible, unreserved balance','wallet','/creator/earnings?status=Available')}${metric('Pending',money(balance('Pending')),'Commissions still on hold','clock','/creator/earnings?status=Pending')}${metric('Qualified orders',String(m.qualifiedOrders),'For the selected period','cart','/creator/referrals?days='+days)}${metric('Link conversion',m.conversion===null?'—':m.conversion.toFixed(1)+'%','Link orders / unique visitors','trend','/creator/performance?days='+days)}</div><div class="grid cols"><div>${chart()}<section class="card">${cardHeader('Recent commissions','Only your masked referral records.','wallet','<a class="text-link" href="/creator/earnings">View all →</a>')}${ledgerTable(ledgerFor(),5)}</section></div><div>${payoutCard()}${resourcesCard()}</div></div>`;}
 function links(){return header('Every story has a starting point','Create a separate link for each channel or campaign.',controls())+referralCard()+`<div class="grid cols"><section class="card">${cardHeader('Your links','Archive old links when a campaign ends.','link')}${creator.links.length?`<ul class="list">${creator.links.map(l=>`<li><div class="left"><strong>${esc(l.tag)}</strong><p>${esc(l.url)}</p><p>${date(l.created_at)} · ${l.active?'Active':'Archived'}</p></div><div class="actions"><button class="button small" type="button" data-copy="${esc(l.url)}">Copy</button>${l.active?`<button class="button small" type="button" data-archive="${esc(l.id)}">Archive</button>`:''}</div></li>`).join('')}</ul>`:empty('Your first link is one label away','Create a channel link so your visits can be attributed consistently.','','link')}</section><section class="card">${cardHeader('Create a link','Keep labels short and recognizable.','link')}<form data-form="link" class="form-grid">${fields('Channel or campaign label','tag','text','','required minlength="2" maxlength="80" placeholder="YouTube · desk setup"')}<button class="button primary" type="submit">Create link ${icon('arrow')}</button>${status}</form><p class="hint" style="margin-top:20px">Referral visits use a first-party cookie for attribution. Explicit eligible codes take priority over links. A direct return preserves attribution. Live financial terms are not active.</p></section></div>`;}
 function earnings(referrals=false){return header(referrals?'Your referrals':'Your earnings',referrals?'Qualified purchase records, with customer details kept private.':'The basis, rate and status behind every commission.',controls())+`<section class="card">${cardHeader(referrals?'Qualified orders':'Commission ledger',`${currency.toUpperCase()} only. Original commission shown; balances reflect reversals.`,'wallet')}<div class="filters"><select data-ledger-filter aria-label="Commission status"><option value="">All statuses</option>${['Pending','Available','Reserved','Paid','Reversed','Review'].map(s=>`<option ${query.get('status')===s?'selected':''}>${s}</option>`).join('')}</select><a class="text-link" href="/api/creator/export?days=${days}">Export latest 200 records · CSV</a></div>${ledgerTable(ledgerFor())}</section><section class="card">${cardHeader('Where your balance stands','Balances across your complete ledger, separated by currency.','wallet')}<dl class="detail-grid">${['Pending','Available','Reserved','Paid','Reversed','Review'].map(s=>`<div><dt>${s} · ${esc(currency.toUpperCase())}</dt><dd><strong>${money(balance(s))}</strong></dd></div>`).join('')}</dl><p class="hint">Reversed commissions include proportional refunds and chargebacks. Paid is the unreversed paid balance; payout history records the original paid batch. Hardware eligibility waits for confirmed delivery. Reserved funds are awaiting payout reconciliation.</p></section>`;}
 function performance(){return header('A clearer view of your impact','Understand how your links turn attention into qualified orders.',controls())+`<div class="metrics">${metric('Unique visitors',String(creator.metrics.visitors),'Distinct referral-cookie visitors','user','/creator/links')}${metric('Qualified orders',String(creator.metrics.qualifiedOrders),'Link and code qualifying orders','cart','/creator/referrals?days='+days)}${metric('Link orders',String(creator.metrics.linkedOrders),'Eligible link-attributed orders','link','/creator/referrals?days='+days)}${metric('Link conversion',creator.metrics.conversion===null?'—':creator.metrics.conversion.toFixed(1)+'%','Code orders are excluded','trend','/creator/links')}</div>${chart()}<section class="card">${cardHeader('What these numbers mean','Visits are attribution records, not verified people.','chart')}<p class="muted">${esc(creator.metrics.definition)}</p><p class="hint" style="margin-top:15px">A browser blocking cookies or clearing its cookie can affect visitor counts. A new-customer order is qualified by the server after verified payment. No social-platform reach or impressions are inferred from submitted posts.</p></section>`;}
 function payouts(){return header('Your payouts','Eligible balances, reservations and settled batches.',controls())+`<div class="grid equal">${payoutCard()}<section class="card">${cardHeader('Payout history','A saved reservation is not a completed payment.','clock')}${creator.payouts.length?`<ul class="list">${creator.payouts.map(p=>`<li><div class="left"><strong>${money(p.amount,p.currency)} ${esc(p.currency.toUpperCase())}</strong><p>${date(p.created_at)} · ${esc(p.id.slice(0,8).toUpperCase())}</p></div>${badge(p.status)}</li>`).join('')}</ul>`:empty('No payout batches yet','When the program and payout provider are activated, eligible balances can enter a scheduled batch.','','wallet')}</section></div>`;}
 function mediaKit(){const assets=[['Brand mark','/assets/brand-mark.svg','SVG · pink on transparent','logo'],['Black magnetic holder','/assets/closing-conversion-v1/holder-black-640.webp','WebP · product master',''],['PhoneBridger software','/assets/closing-conversion-v1/software-package-pink-v1-960.webp','WebP · software master','']];return header('Make something worth sharing','Reviewed brand and product assets, ready for your content.')+`<div class="asset-grid">${assets.map(([name,url,note,cl])=>`<section class="media-tile ${cl}"><img src="${url}" alt="${name}"><div><h3>${name}</h3><small>${note}</small></div><a class="button outline" href="${url}" download>Download asset ${icon('download')}</a></section>`).join('')}</div><section class="card" style="margin-top:20px">${cardHeader('Keep the story accurate','Helpful talking points and a few boundaries.','check')}<ul class="steps-copy"><li>Use one Windows mouse and keyboard with up to three Android phones.</li><li>USB is preferred automatically, with Wi-Fi as the fallback.</li><li>Explain the Android permissions and show the setup honestly.</li><li>Use these product assets without changing holder geometry or the brand mark.</li><li>Disclose your relationship when sharing referral links. Do not promise unconfirmed delivery dates, earnings or future features.</li></ul><div class="actions">${button('Setup guide','/guides/getting-started')}${button('Current product details','/shop')}</div><p class="hint" style="margin-top:18px">Social templates, B-roll and a downloadable creator guide are not part of this kit yet.</p></section>`;}
 function content(){return header('Your content, in one place','Keep a record of the posts and videos you’ve shared.')+`<div class="grid equal"><section class="card">${cardHeader('Your submitted posts','These are your links, not platform reach metrics.','play')}${creator.content.length?`<ul class="list">${creator.content.map(c=>`<li><div class="left"><strong>${esc(c.label)}</strong><p>${date(c.created_at)}</p></div><a class="text-link" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Open post ↗</a></li>`).join('')}</ul>`:empty('Your next post belongs here','Add a published post URL when it is ready.','','play')}</section><section class="card">${cardHeader('Add a post','A label helps you recognize it later.','link')}<form class="form-grid" data-form="content">${fields('Post label','label','text','','required minlength="2" maxlength="100"')}${fields('Published HTTPS URL','url','url','','required maxlength="1000"')}<button class="button primary" type="submit">Save post</button>${status}</form></section></div>`;}
 function creatorSettings(){return header('Creator settings','Your program status and the terms behind it.')+`<div class="grid equal"><section class="card">${cardHeader('Program terms','Financial proposal; live commissions are not enabled.','wallet')}<div class="eyebrow">${esc(creator.terms.version)}</div>${proposal()}<div class="divider"></div>${creator.partner.acceptedTerms===creator.terms.version?`${badge('Proposal acknowledged')}<p class="hint" style="margin-top:15px">Acknowledgement does not activate live commissions, discounts or payouts.</p>`:`<form class="form-grid" data-form="creator-terms"><label class="checkbox-label"><input type="checkbox" name="consent" required>I acknowledge this proposal version for the sandbox. Live financial terms still require separate approval.</label><button class="button outline" type="submit">Acknowledge proposal</button>${status}</form>`}</section><section class="card">${cardHeader('Your account & channels','One sign-in, two workspaces.','user')}<p class="muted">${esc(account.user.email)}</p><p class="hint" style="margin:15px 0 20px">Channel or audience changes are reviewed by support. Payout details will be collected through the approved provider when onboarding is available.</p><div class="actions">${button('Account settings','/account/settings')}${button('Request a channel update','/account/support','outline')}</div></section></div>`;}
 async function render(){navigation();let html;
  if(creatorWorkspace){if(!account.creator.approved)throw Object.assign(Error('Creator access is available after application approval.'),{status:403});const action=path.split('/')[2]||'overview';if(action==='media-kit')html=mediaKit();else{creator=await api('/api/creator/'+action+'?days='+days);if(!/^[a-z]{3}$/.test(currency))currency='usd';const notice=`<div class="notice info">${creator.financiallyActive?'Sandbox program · Test commissions only. No real money or goods.':'The creator program is being prepared. Live commissions, discounts and payouts are not active.'}</div>`;const builders={overview:creatorOverview,links,performance,referrals:()=>earnings(true),earnings,payouts,content,settings:creatorSettings};if(!builders[action])throw Error('This workspace page is unavailable.');html=notice+builders[action]();}}
  else if(path==='/creators/apply')html=await application();else if(path.startsWith('/account/orders/'))html=await orderDetail(path.split('/').pop());else{const builders={'/account':overview,'/account/downloads':downloads,'/account/licences':licences,'/account/orders':async()=>{const d=await api('/api/shop/orders'+(query.get('before')?'?before='+encodeURIComponent(query.get('before')):''));return header('Your orders','Payment, software and hardware delivery, at a glance.')+`<section class="card">${orderRows(d.orders)}<div class="actions" style="margin-top:20px">${query.get('before')?button('Newest orders','/account/orders'):''}${d.nextCursor?button('Older orders','/account/orders?before='+encodeURIComponent(d.nextCursor),'outline'):''}</div></section>`;},'/account/support':support,'/account/settings':settings,'/account/integrations':()=>header('Your integrations','A future connection, with your consent.')+`<section class="card">${empty('Local app bridge is not available yet','Your website account cannot see or control nearby phones. Connection scopes, activity and revocation will appear here when the local bridge is implemented.','','link')}</section>`};if(!builders[path])throw Error('This workspace page is unavailable.');html=await builders[path]();}
  main.innerHTML=html;main.setAttribute('aria-busy','false');
 }
 function failure(e){const auth=e.status===401,denied=e.status===403;main.setAttribute('aria-busy','false');main.innerHTML=`<section class="card error-card"><div class="eyebrow">${auth?'YOUR ACCOUNT':denied?'CREATOR ACCESS':'A MOMENT TO RECONNECT'}</div><h1>${auth?'Sign in to your workspace':denied?'Your creator journey starts here':'We couldn’t load this page'}</h1><p>${esc(e.message)}</p><div class="actions">${auth?button('Sign in','/login?next=account','primary'):denied?button('View your application','/creators/apply','primary'):'<button class="button primary" type="button" data-retry>Try again</button>'}${button('Back to website','/')}</div></section>`;}
 async function boot(){try{account=await api('/api/workspace/summary');await render();}catch(e){failure(e);}}
 async function saveForm(form){const b=form.querySelector('[type=submit]'),s=form.querySelector('[data-form-status]'),type=form.dataset.form;if(!form.reportValidity())return;b.disabled=true;form.setAttribute('aria-busy','true');s.classList.remove('error');s.textContent='Saving…';const d=Object.fromEntries(new FormData(form));try{let result;
  if(type==='profile')result=await api('/api/workspace/profile',{name:d.name,setup:account.profile.setup});
  if(type==='password')result=await api('/api/workspace/password',{currentPassword:d.currentPassword,newPassword:d.newPassword});
  if(type==='support')result=await api('/api/workspace/support',{...d,orderId:d.orderId||null,requestId:form.dataset.requestId||(form.dataset.requestId=crypto.randomUUID()),diagnosticsConsent:form.elements.diagnosticsConsent.checked});
  if(type==='application')result=await api('/api/creator/application',{...d,consent:form.elements.consent.checked,termsVersion:applicationTermsVersion});
  if(type==='link')result=await api('/api/creator/links',{tag:d.tag});
  if(type==='content')result=await api('/api/creator/content',{label:d.label,url:d.url});
  if(type==='creator-terms')result=await api('/api/creator/accept-terms',{version:creator.terms.version,consent:form.elements.consent.checked});
  if(type==='support'){s.textContent=result.message+' Reference: '+result.id;b.textContent='Request saved';b.dataset.saved='true';toast('Support request saved.');return;}
  if(type==='password'){form.reset();s.textContent='Password changed. Other sessions have been signed out.';toast('Password changed.');account=await api('/api/workspace/summary');return;}
  toast(type==='application'?'Application submitted for review.':type==='link'?'Referral link created.':'Saved.');await boot();
 }catch(e){s.textContent=e.message;s.classList.add('error');s.tabIndex=-1;s.focus();}finally{form.removeAttribute('aria-busy');if(!b.dataset.saved)b.disabled=false;}}
 document.addEventListener('submit',e=>{if(e.target.matches('[data-form]')){e.preventDefault();saveForm(e.target);}});
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-menu')){const open=b.getAttribute('aria-expanded')!=='true';$('#sidebar').classList.toggle('open',open);$('[data-close-menu]').hidden=!open;b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Close navigation':'Open navigation');if(open)$('#sidebar a').focus();}
  if(b.hasAttribute('data-logout')){b.disabled=true;try{await api('/api/account/logout',{});location.assign('/login');}catch(err){toast(err.message);b.disabled=false;}}
  if(b.hasAttribute('data-retry'))boot();
  if(b.hasAttribute('data-copy')){try{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied to clipboard.');}catch{const input=b.closest('.copy-field')?.querySelector('input');input?.select();toast('Clipboard unavailable. Select and copy the link or code.');}}
  if(b.hasAttribute('data-archive')){b.disabled=true;try{await api('/api/creator/links',{archive:b.dataset.archive});toast('Link archived.');await boot();}catch(err){toast(err.message);b.disabled=false;}}
  if(b.hasAttribute('data-revoke')){b.disabled=true;try{await api('/api/workspace/revoke-sessions',{});toast('Other sessions signed out.');await boot();}catch(err){toast(err.message);b.disabled=false;}}
 });
 function closeMenu(){const b=$('[data-menu]');$('#sidebar').classList.remove('open');$('[data-close-menu]').hidden=true;b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation');b.focus();}
 $('[data-close-menu]').addEventListener('click',closeMenu);document.addEventListener('keydown',e=>{if(!$('#sidebar').classList.contains('open'))return;if(e.key==='Escape')closeMenu();if(e.key==='Tab'){const focusable=[...$('#sidebar').querySelectorAll('a,button')].filter(el=>el.getClientRects().length),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 document.addEventListener('change',async e=>{const el=e.target;if(el.matches('[data-days],[data-currency],[data-ledger-filter]')){const q=new URLSearchParams(location.search);q.set(el.hasAttribute('data-days')?'days':el.hasAttribute('data-currency')?'currency':'status',el.value);location.assign(path+'?'+q);}
  if(el.hasAttribute('data-setup')){el.disabled=true;const old=[...account.profile.setup],setup=[...document.querySelectorAll('[data-setup]:checked')].map(i=>i.dataset.setup);try{await api('/api/workspace/profile',{name:account.profile.name,setup});account.profile.setup=setup;toast('Checklist saved.');}catch(err){el.checked=old.includes(el.dataset.setup);toast(err.message);}finally{el.disabled=false;}}
  if(el.hasAttribute('data-diagnostics-file')){const file=el.files[0];if(!file)return;if(file.size>8000||! /\.(txt|json)$/i.test(file.name)){el.value='';toast('Choose a .txt or .json file up to 8 KB.');return;}$('[data-diagnostics]').value=await file.text();toast('Review the file before attaching it.');}
 });
 boot();
})();
