import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../../..'),out=path.resolve(root,'sites/madbeauty/cloudflare/output/full-release-20261010'),phase=process.argv[2];assert.ok(['before','accept'].includes(phase));
const secrets=JSON.parse(await readFile(path.resolve(root,'sites/madbeauty/platform-upgrade-20261007/evidence/hosted-ui264/secrets.private.json'))),origin='https://madbeauty-ui-acceptance-20261009.phonebridger-app.workers.dev',authorization='Bearer '+secrets.ACCEPTANCE_KEY;
const qa=async(p,method='GET')=>{const r=await fetch(origin+'/__qa/'+p,{method,headers:{authorization}});assert.equal(r.status,200,p);return r.json();};
if(phase==='before'){const value={at:new Date().toISOString(),source:await qa('source'),target:await qa('target'),sourceMedia:await qa('source-media'),mailbox:await qa('mailbox')};assert.equal(value.target.authority.state,'active');await writeFile(path.resolve(out,'qa-state-before.private.json'),JSON.stringify(value));console.log(JSON.stringify({state:'CAPTURED',sourceCollections:Object.keys(value.source).length,targetCollections:Object.keys(value.target.snapshot).length,physicalMedia:value.sourceMedia.length+value.target.media.length}));}
else {
 const before=JSON.parse(await readFile(path.resolve(out,'qa-state-before.private.json'))),checks=[],policyVersion='madbeauty-2026-10-10-v1',email='hosted-erasure@example.com',org='provider_6267a38c-81d0-401a-bb7e-ba25212b5180',scope={role:'professional',organizationId:org};
 assert.ok(!before.source.clients.some(c=>c.email===email));assert.ok(!before.target.snapshot.clients.some(c=>c.email===email));
 const browser=()=>{let cookie='',csrf='';return {async request(p,body,overrides={}){const r=await fetch(origin+'/api/madbeauty/'+p,{method:body===undefined?'GET':'POST',headers:{authorization,cookie,origin,...(body===undefined?{}:{'content-type':'application/json','x-csrf-token':csrf}),...overrides},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const value=await r.json();if(value.csrf)csrf=value.csrf;return {status:r.status,value};},async login(e){await this.request('session');const start=await this.request('auth/start',{email:e});assert.equal(start.status,200);const code=(await qa('code?email='+encodeURIComponent(e))).code;assert.match(code,/^\d{6}$/);const v=await this.request('auth/verify',{challengeId:start.value.challengeId,code});assert.equal(v.status,200);return v.value.user;},async rpc(method,input={}){const r=await this.request('rpc',{method,input,siteId:'madbeauty'});assert.equal(r.status,200,method+': '+JSON.stringify(r.value.error));return r.value.result;},async denied(method,input,code){const r=await this.request('rpc',{method,input,siteId:'madbeauty'});assert.ok(r.status>=400);assert.equal(r.value.error?.code,code);}};};
 const owner=browser(),client=browser(),stranger=browser();await owner.login('hosted-owner@example.com');await owner.denied('erasurePreview',{},'PROFESSIONAL_ACCOUNT');checks.push('Existing owner/operator business access cannot use customer erasure');
 const created=await owner.rpc('createClient',{organizationId:org,email,name:'Disposable hosted retention fixture',idempotencyKey:'hosted-c02-20261010-client'});await client.login(email);await stranger.request('session');
 assert.equal((await client.rpc('workspace',{role:'customer'})).retentionPolicy.version,policyVersion);
 const service=(await client.rpc('catalog')).find(s=>s.organizationId===org);assert.ok(service);let slot;for(let dayOffset=1;dayOffset<9&&!slot;dayOffset++)slot=(await client.rpc('availability',{providerServiceId:service.id,dayOffset,from:540,to:1200})).slots[0];assert.ok(slot);
 const hold=await client.rpc('hold',slot),booking=await client.rpc('confirm',{holdId:hold.id,name:'Disposable hosted retention fixture',idempotencyKey:'hosted-c02-20261010-booking'});await client.rpc('message',{bookingId:booking.id,scope:{role:'customer'},text:'Disposable hosted retention text'});
 await owner.rpc('saveClientCard',{organizationId:org,clientId:booking.clientId,version:0,name:'Disposable hosted retention fixture',note:'Disposable hosted retention note'});
 const preview=await client.rpc('erasurePreview');assert.ok(preview.futureBookings.some(b=>b.id===booking.id));checks.push('Live target preview includes actual future visit and active policy');
 await client.denied('requestErasure',{confirmEmail:'foreign@example.com',policyVersion},'INVALID_INPUT');await client.denied('requestErasure',{confirmEmail:email,policyVersion:'draft'},'INVALID_INPUT');assert.equal((await client.request('rpc',{method:'requestErasure',siteId:'madbeauty',input:{confirmEmail:email,policyVersion}},{'x-csrf-token':''})).status,403);checks.push('Wrong email, stale policy and missing CSRF refuse before deletion');
 const receipt=await client.rpc('requestErasure',{confirmEmail:email,policyVersion});assert.equal(receipt.state,'completed');assert.equal(receipt.signInRevoked,true);assert.equal((await client.request('session')).value.user,null);assert.equal((await client.rpc('erasureStatus',{receiptToken:preview.receiptToken})).id,receipt.id);await stranger.denied('erasureStatus',{receiptToken:'A'.repeat(43)},'NOT_FOUND');checks.push('Identity revoked; completed receipt available only by capability');
 const current=await owner.rpc('workspace',scope),anonymous=current.bookings.find(b=>b.id===booking.id);assert.equal(anonymous.erased,true);assert.equal(anonymous.status,'confirmed');assert.equal(anonymous.startAt,booking.startAt);assert.notEqual(anonymous.clientId,booking.clientId);assert.ok(!current.clients.some(c=>c.id===booking.clientId));assert.ok(!current.clientCards.some(c=>c.clientId===booking.clientId));assert.ok(!current.messages.some(m=>m.bookingId===booking.id));checks.push('Active target retains anonymous occupancy and removes own profile, card and messages');
 for(const p of ['restart-source','restart-target']){const r=await fetch(origin+'/__qa/'+p,{method:'POST',headers:{authorization}});assert.ok(r.status>=500);}
 assert.equal((await client.request('session')).value.user,null);assert.equal((await client.rpc('erasureStatus',{receiptToken:preview.receiptToken})).id,receipt.id);assert.equal((await owner.rpc('workspace',scope)).bookings.find(b=>b.id===booking.id).erased,true);checks.push('Both hosted SQLite objects restart without resurrecting identity or visit contact');
 const after={at:new Date().toISOString(),source:await qa('source'),target:await qa('target'),sourceMedia:await qa('source-media'),retention:await qa('retention')};assert.equal(after.target.authority.state,'active');assert.deepEqual(after.sourceMedia,before.sourceMedia);assert.deepEqual(after.target.media,before.target.media);
 for(const key of ['bookings','offers','providerServices','practitioners','resources','memberships','media','reviews','busyBlocks'])for(const [old,now] of [[before.source,after.source],[before.target.snapshot,after.target.snapshot]])for(const row of old[key]||[])assert.deepEqual((now[key]||[]).find(r=>r.id===row.id),row,'Preserve incumbent '+key+' '+row.id);
 checks.push('Existing role, calendar, offer and physical media records preserved exactly');assert.ok(after.retention.tombstones>=1);assert.equal(after.retention.queued,0);assert.ok(after.retention.backups>=1);checks.push('Durable completion journal, acknowledged queue and encrypted customer checkpoint exist');
 await owner.rpc('cancelBooking',{scope,id:anonymous.id,version:anonymous.version,reason:'Disposable C02 hosted acceptance completed'});checks.push('Only own anonymous disposable visit canceled using supported calendar action');
 await writeFile(path.resolve(out,'qa-state-after.private.json'),JSON.stringify(after));await writeFile(path.resolve(out,'qa-retention-acceptance.private.json'),JSON.stringify({state:'PASS',at:new Date().toISOString(),checks,checkCount:checks.length,createdClientId:created.id,receiptId:receipt.id,bookingId:booking.id,smtp:false,existingAccountsErased:0,sourceAndTargetNamespacesPreserved:true},null,2));console.log(JSON.stringify({state:'PASS',checks:checks.length,smtp:false,existingAccountsErased:0}));
}
