import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {core,coreSource,pinCore} from './pinned-core.mjs';
const repo=path.resolve(import.meta.dirname,'../../..'),out=path.resolve(repo,'sites/madbeauty/cloudflare/output/full-release-20261010');
const config=JSON.parse(await readFile(path.resolve(repo,'sites/madbeauty/cloudflare/wrangler.production.json'))),baseline=JSON.parse(await readFile(path.resolve(out,'main-before.private.json'))).records[0],receipt=JSON.parse(await readFile(path.resolve(repo,'sites/madbeauty/cloudflare/output/content-release-receipt.json')));
assert.equal(baseline.deployments.deployments[0].versions[0].version_id,'a492b36a-1f43-4ad3-ab5f-fb5b1c33ed22');assert.equal(baseline.settings.bindings.find(b=>b.name==='PLATFORM').namespace_id,'2faf96eedef1425c8d4fc07444cde2f3');assert.equal(receipt.packageSha256,'e20c3b95b57ae9f813e55ffd0ef46688a937a7d63fe1c70246a92b8a71e71953');assert.equal(receipt.approvedPages.length,129);
assert.equal(config.compatibility_date,baseline.settings.compatibility_date);assert.deepEqual(config.compatibility_flags,baseline.settings.compatibility_flags);
for(const b of baseline.settings.bindings.filter(b=>b.type==='plain_text'))assert.equal(config.vars[b.name],b.text,'Preserve actual '+b.name);
const {build}=await import(pathToFileURL(path.resolve(core,'node_modules/esbuild/lib/main.js'))),bundle=await build({entryPoints:[path.resolve(repo,'sites/madbeauty/cloudflare/worker.mjs')],write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text','.html':'text'},plugins:[pinCore]}),script=bundle.outputFiles[0].text;
for(const marker of ['ACCEPTANCE_KEY','HostedSource','qa_mail_captures','__qa/retention','NATIVE_CONTENT_CLOCK'])assert.ok(!script.includes(marker),'QA must not enter production artifact');
config.main='production-worker.mjs';config.no_bundle=true;config.assets.directory=path.resolve(repo,'sites/madbeauty/cloudflare/output/assets-release');delete config.$schema;
config.keep_vars=true;config.observability=baseline.settings.observability;
await writeFile(path.resolve(out,'production-worker.mjs'),script);await writeFile(path.resolve(out,'production-wrangler.json'),JSON.stringify(config,null,2));
const manifest={builtAt:new Date().toISOString(),sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),coreSource,artifactSha256:createHash('sha256').update(script).digest('hex'),packageSha256:receipt.packageSha256,approvedPages:129,media:630,assets:receipt.assets,previousVersion:baseline.deployments.deployments[0].versions[0].version_id,policyVersion:config.vars.RETENTION_POLICY_VERSION,configuration:config,namespaceBefore:baseline.settings.bindings.find(b=>b.name==='PLATFORM').namespace_id};
assert.equal(manifest.coreSource,'5661d5d6907d6f5d11514ae69c0decc6130d65e2');await writeFile(path.resolve(out,'production-manifest.json'),JSON.stringify(manifest,null,2));console.log(JSON.stringify({state:'CANDIDATE_BUILT',sourceCommit:manifest.sourceCommit,artifactSha256:manifest.artifactSha256,pages:129,assets:receipt.assets}));
