import assert from 'node:assert/strict';
import {readFile,writeFile,access} from 'node:fs/promises';
import path from 'node:path';
const out=path.resolve(import.meta.dirname,'../cloudflare/output/full-release-20261010'),phase=process.argv[2],origin='https://madbeauty.lt',file=path.resolve(out,'main-session.private.json');assert.ok(['start','verify','before','after'].includes(phase));
let session;if(phase==='start'){try{await access(file);throw Error('Existing attempt; inspect outcome before another mail');}catch(error){if(error.code!=='ENOENT')throw error;}session={cookie:'',csrf:'',startedAt:new Date().toISOString()};}else session=JSON.parse(await readFile(file));
async function request(p,body,overrides={}){const r=await fetch(origin+'/api/madbeauty/'+p,{method:body===undefined?'GET':'POST',headers:{cookie:session.cookie,origin,...(body===undefined?{}:{'content-type':'application/json','x-csrf-token':session.csrf}),...overrides},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))session.cookie=r.headers.get('set-cookie').split(';')[0];const value=await r.json();if(value.csrf)session.csrf=value.csrf;await writeFile(file,JSON.stringify(session));return {status:r.status,value};}
async function rpc(method,input={}){const r=await request('rpc',{method,input,siteId:'madbeauty'});assert.equal(r.status,200,method+': '+r.value.error?.code);return r.value.result;}
if(phase==='start'){await request('session');const r=await request('auth/start',{email:'info@pinet.lt'});assert.equal(r.status,200);session.challengeId=r.value.challengeId;await writeFile(file,JSON.stringify(session));console.log(JSON.stringify({state:'AUTH_MAIL_ACCEPTED',recipient:'authorized own mailbox',attempts:1}));}
if(phase==='verify'){const code=(await readFile(path.resolve(out,'main-otp.private.txt'),'utf8')).trim();assert.match(code,/^\d{6}$/);let r=await request('session');if(!r.value.user)r=await request('auth/verify',{challengeId:session.challengeId,code});assert.equal(r.status,200);assert.equal(r.value.user.email,'info@pinet.lt');assert.equal(r.value.operator,true);session.accountId=r.value.user.id;await writeFile(file,JSON.stringify(session));console.log(JSON.stringify({state:'ORDINARY_OPERATOR_LOGIN_ACCEPTED',capturedCode:false}));}
if(['before','after'].includes(phase)){
 const current=await request('session');assert.equal(current.value.user.id,session.accountId);assert.equal(current.value.operator,true);const recovery=await request('recovery-status');assert.equal(recovery.status,200);assert.equal(recovery.value.siteId,'madbeauty');assert.match(recovery.value.bookmark,/^[a-f0-9-]+$/);
 const catalogue=await rpc('catalog'),state={at:new Date().toISOString(),recovery:recovery.value,user:current.value.user,customer:await rpc('workspace',{role:'customer'}),operator:await rpc('workspace',{role:'operator'}),catalog:catalogue,profiles:[...new Set(catalogue.map(s=>s.organizationId))].sort()};
 if(phase==='after'){const before=JSON.parse(await readFile(path.resolve(out,'main-state-before.private.json')));assert.equal(state.user.id,before.user.id);for(const key of ['bookings','messages','favorites','clients','inquiries','waitlist'])if(before.customer[key])assert.deepEqual(state.customer[key],before.customer[key],'Preserve own '+key);assert.deepEqual(state.catalog,before.catalog);assert.deepEqual(state.profiles,before.profiles);assert.equal(state.customer.retentionPolicy.version,'madbeauty-2026-10-10-v1');const denied=await request('rpc',{siteId:'madbeauty',method:'erasurePreview',input:{}});assert.equal(denied.value.error?.code,'PROFESSIONAL_ACCOUNT');const noCsrf=await request('rpc',{siteId:'madbeauty',method:'preferences',input:{service:true,marketing:false}},{'x-csrf-token':''});assert.equal(noCsrf.status,403);}
 await writeFile(path.resolve(out,'main-state-'+phase+'.private.json'),JSON.stringify(state,null,2));console.log(JSON.stringify({state:'PASS',phase,ordinaryExistingAccountPreserved:true,bookmarkPresent:true,realPublicProfiles:state.profiles.length,catalogServices:state.catalog.length,stateRows:state.recovery.stateStorage?.rows,physicalMediaBytes:state.recovery.mediaBytes,policyActive:!!state.customer.retentionPolicy}));
}
