import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {core,pinCore} from './pinned-core.mjs';
const repo=path.resolve(import.meta.dirname,'../../..'),out=path.resolve(repo,'sites/madbeauty/cloudflare/output/full-release-20261010');
const {build}=await import(pathToFileURL(path.resolve(core,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.resolve(core,'node_modules/miniflare/dist/src/index.js')));
const qaManifest=JSON.parse(await readFile(path.resolve(out,'qa-manifest.json'))),qaScript=await readFile(path.resolve(out,'qa-worker.mjs'),'utf8'),secrets=JSON.parse(await readFile(path.resolve(repo,'sites/madbeauty/platform-upgrade-20261007/evidence/hosted-ui264/secrets.private.json'))),qaConfig=JSON.parse(await readFile(path.resolve(out,'qa-wrangler.json'))),checks=[];
let mf=new Miniflare({modules:true,script:qaScript,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'HostedSource',useSQLite:true},ORGANIZATION_STAGING:{className:'HostedOrganization',useSQLite:true}},bindings:{...qaConfig.vars,...secrets},serviceBindings:{ASSETS:()=>new Response('QA asset sentinel')}});
try{
 const headers={Authorization:'Bearer '+secrets.ACCEPTANCE_KEY},send=(p,init={})=>mf.dispatchFetch(qaManifest.origin+p,init);
 for(const p of ['/','/app.mjs','/api/madbeauty/session','/__qa/retention','/__qa/source','/__qa/target'])assert.equal((await send(p)).status,404);checks.push('Protected QA anonymous HTML/assets/API/maintenance refused');
 assert.equal((await mf.dispatchFetch('https://madbeauty.lt/',{headers})).status,404);assert.equal((await send('/__qa/health',{headers})).status,200);checks.push('Protected QA identity and canonical-host refusal');
 assert.equal((await send('/api/madbeauty/auth/start',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({email:'foreign@pinet.lt'})})).status,400);checks.push('Protected QA cannot send to real or non-allowlisted recipient');
 assert.equal((await send('/boot.json',{headers})).status,200);assert.equal((await (await send('/boot.json',{headers})).json()).retentionPolicy.version,'madbeauty-2026-10-10-v1');checks.push('Approved policy in real compiled QA boot');
}finally{await mf.dispose();}
const entry=path.resolve(repo,'sites/madbeauty/cloudflare/worker.mjs').replaceAll('\\','/'),clockBundle=await build({stdin:{contents:`import app,{MadbeautyPlatform,MadbeautyOrganizationStaging} from ${JSON.stringify(entry)};export {MadbeautyPlatform,MadbeautyOrganizationStaging};export default {fetch(request,env){return app.fetch(request,{...env,NATIVE_CONTENT_CLOCK:request.headers.get('X-Native-Content-Clock')||Date.now()});}};`,resolveDir:repo,sourcefile:'private-native-content-clock.mjs'},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text','.html':'text'},plugins:[pinCore,{name:'native-only-clock',setup(b){b.onLoad({filter:/cloudflare[\\/]worker\.mjs$/},async a=>({contents:(await readFile(a.path,'utf8')).replace('contentProjection(Date.now(),registry)','contentProjection(Number(env.NATIVE_CONTENT_CLOCK),registry)'),loader:'js'}));}}]});
mf=new Miniflare({modules:true,script:clockBundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'MadbeautyPlatform',useSQLite:true},ORGANIZATION_STAGING:{className:'MadbeautyOrganizationStaging',useSQLite:true}},bindings:{APP_ORIGIN:'https://madbeauty.lt',RELEASE_MODE:'production',RETENTION_POLICY_VERSION:'madbeauty-2026-10-10-v1',SESSION_SECRET:'native-only-static-acceptance-key-no-provider-access'},serviceBindings:{ASSETS:async req=>{try{return new Response(await readFile(path.resolve(repo,'sites/madbeauty/cloudflare/output/assets-release','.'+new URL(req.url).pathname)));}catch(e){if(e.code!=='ENOENT')throw e;return new Response('Not found',{status:404});}}}});
const pkg=JSON.parse(await readFile(path.resolve(repo,'sites/madbeauty/cloudflare/output/content-package.json'))),escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),future=pkg.pages.filter(p=>p.type==='guide'&&Date.parse(p.publishAt)>Date.now()),publication=[];
try{
 for(const p of future)for(const now of [Date.parse(p.publishAt)-1,Date.parse(p.publishAt)]){
  const request=route=>mf.dispatchFetch('https://madbeauty.lt'+route,{headers:{'X-Native-Content-Clock':String(now)}}),due=pkg.pages.filter(p=>Date.parse(p.publishAt)<=now),r=await request('/'+p.slug),html=await r.text(),visible=now===Date.parse(p.publishAt);assert.equal(r.status,visible?200:404,p.slug);
  const data=await(await request('/content.json')).json();assert.deepEqual(data.pages.map(p=>p.id).sort(),due.map(p=>p.id).sort());
  if(visible){assert.ok(html.includes('<h1>'+escape(p.title)+'</h1>'));assert.ok(html.includes('property="og:title" content="'+escape(p.title)+'"'));assert.ok(html.includes('property="og:image"'));assert.ok(html.includes('name="twitter:card"'));assert.ok(html.includes('application/ld+json'));assert.ok(html.includes(p.publishAt));for(const reason of p.externalLinks?.map(x=>x.reason).filter(x=>x?.length>50)||[])assert.ok(!html.includes(escape(reason)));}
  else assert.ok(!html.includes(escape(p.title)));
  for(const route of ['/sitemap.xml','/llms.txt','/llms-full.txt']){const body=await(await request(route)).text();for(const guide of pkg.pages.filter(p=>p.type==='guide'))assert.equal(body.includes('https://madbeauty.lt/'+guide.slug),Date.parse(guide.publishAt)<=now,route+guide.slug);}
  const media=new Set(due.flatMap(p=>p.media.map(m=>m.src)));for(const m of p.media)assert.equal((await request(m.src)).status,media.has(m.src)?200:404);
  publication.push({id:p.id,visible,at:new Date(now).toISOString()});
 }
 assert.equal(publication.length,244);checks.push('244 exact before/at publication states include new SSR OG/schema and eligible JSON/discovery/media');
 const main=JSON.parse(await readFile(path.resolve(out,'production-manifest.json'))),script=await readFile(path.resolve(out,'production-worker.mjs'));assert.equal(createHash('sha256').update(script).digest('hex'),main.artifactSha256);
 await writeFile(path.resolve(out,'native-proof.json'),JSON.stringify({state:'PASS',at:new Date().toISOString(),checks,publication,publicationCount:publication.length,packageSha256:main.packageSha256,productionArtifactSha256:main.artifactSha256,qaArtifactSha256:qaManifest.artifactSha256,clockArtifactSha256:createHash('sha256').update(clockBundle.outputFiles[0].text).digest('hex'),scope:'Private native-only content clock; not deployed or used in production. QA gate and production compilation checked separately.'},null,2));console.log(JSON.stringify({state:'PASS',checks:checks.length,publicationStates:publication.length}));
}finally{await mf.dispose();}
