import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting');
const {build}=await import(pathToFileURL(path.join(runtime,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(runtime,'node_modules/miniflare/dist/src/index.js')));
test('Actual Workers ordinary HTTP uses the committed organization after two-object restart; new ID lookup, current search, session revocation and central CSRF checks retain source data',async()=>{
 const bundle=await build({stdin:{resolveDir:import.meta.dirname,sourcefile:'isolated-organization-directory-fixture.mjs',contents:`
  import {MadbeautyPlatform} from './platform-object.mjs';
  import {MadbeautyOrganizationStaging} from './organization-object.mjs';
  import {openDurableStore} from './store.mjs';
  import {createPlatform} from '../backend/platform.mjs';
  import {createAuth} from '../backend/auth.mjs';
  import {createOrganizationDirectory} from '../backend/organization-directory.mjs';
  const now=Date.parse('2026-10-08T06:00:00Z'),users={owner:{id:'worker-directory-owner',email:'worker-directory-owner@example.com',name:'Owner'},client:{id:'worker-directory-client',email:'worker-directory-client@example.com',name:'Client'},reception:{id:'worker-directory-reception',email:'worker-directory-reception@example.com',name:'Reception'},foreign:{id:'worker-directory-foreign',email:'worker-directory-foreign@example.com',name:'Foreign'}};
  export class SourceFixture extends MadbeautyPlatform{
   constructor(ctx,env){super(ctx,env);this.store=openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>now});}
   directory(){return createOrganizationDirectory(this.store,{getTarget:name=>{if(this.store.db.prepare("SELECT value FROM release_metadata WHERE key='directory-outage'").get()?.value==='1')throw Error('Isolated directory control outage');const target=this.env.ORGANIZATION_STAGING.getByName(name);return {executeDirectoryCommand:async packet=>{const result=await target.executeDirectoryCommand(packet);if(packet.method==='createClient'&&this.store.db.prepare("SELECT value FROM release_metadata WHERE key='client-reply-outage'").get()?.value==='1')throw Error('Isolated lost client reply');return result;}};}});}
   controlOutage(value){this.store.db.prepare('INSERT INTO release_metadata VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('directory-outage',value?'1':'0');return {outage:value};}
   clientReplyOutage(value){this.store.db.prepare('INSERT INTO release_metadata VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('client-reply-outage',value?'1':'0');return {outage:value};}
   controlStatus(){return {clientAdmissions:this.store.db.prepare('SELECT id,account_id,state FROM directory_client_admissions').all(),pending:this.store.db.prepare('SELECT revision FROM directory_customer_controls').all(),preferences:this.store.readCollections(['preferences']).preferences};}
   recoverControls(){this.store.db.prepare('UPDATE directory_customer_controls SET due_at=0').run();this.store.db.prepare('UPDATE directory_client_admissions SET due_at=0').run();return this.alarm();}
   prepareFixture(){const existing=this.store.db.prepare("SELECT value FROM release_metadata WHERE key='directory-fixture'").get();if(existing)return JSON.parse(existing.value);const api=createPlatform(this.store),auth=createAuth(this.store),sessions={};
    for(const [role,u]of Object.entries(users)){this.store.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(u.id,this.store.siteId,u.email,u.name,role==='owner'?1:0,now);this.store.ensureClient(u.id);const s=auth.session(null);this.store.db.prepare('UPDATE sessions SET account_id=? WHERE token_hash=?').run(u.id,s.token_hash);sessions[role]={token:s.token,csrf:s.csrf};}
    const make=name=>{const org=api.createOrganization(users.owner,{name,bio:'Isolated Worker directory.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(users.owner,scope),service=api.createService(users.owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Original Worker service',durationMin:60,priceMinor:2500});api.moderate({...users.owner,operator:true},{id:api.submitRevision(users.owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,service,scope};};
    const a=make('Worker Directory A'),b=make('Worker Directory B'),membership=api.grantMembership(users.owner,{organizationId:a.org.id,email:users.reception.email,role:'reception',version:0}),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0],first=api.confirm(users.client,{holdId:api.hold(users.client,candidate(a)).id,idempotencyKey:'worker-directory-retained',name:'Client'}),other=api.confirm(users.client,{holdId:api.hold(users.client,candidate(b)).id,idempotencyKey:'worker-directory-other',name:'Client'}),hold=api.hold(users.client,candidate(a)),info={a,b,first,other,hold,membership,sessions};this.store.db.prepare('INSERT INTO release_metadata VALUES(?,?)').run('directory-fixture',JSON.stringify(info));return info;
   }
   retainedSnapshot(){const f=this.prepareFixture();return {booking:this.store.recordById('bookings',f.first.id),service:this.store.recordById('services',f.a.service.id),bookings:this.store.organizationRecords('bookings',f.a.org.id).length};}
   forgetIndex(){this.store.db.prepare('DELETE FROM organization_directory_refs').run();}
   registerFreshIdentity(email='worker-directory-fresh@example.com'){const auth=createAuth(this.store),anonymous=auth.session(null),challenge=auth.start(anonymous,email,'127.0.0.1'),row=this.store.db.prepare("SELECT payload FROM mail_outbox WHERE challenge_id=? AND type='login-code'").get(challenge.challengeId),verified=auth.verify(anonymous,challenge.challengeId,this.store.unseal(row.payload).code,'127.0.0.1');createPlatform(this.store).preferences(verified.user,{service:false,marketing:false,reminderLeadMin:0});return {id:verified.user.id,token:verified.session.token,csrf:verified.session.csrf};}
   freshIdentity(){const account=this.store.db.prepare('SELECT id,name FROM accounts WHERE email=?').get('worker-directory-fresh@example.com');return {account,client:account?this.store.recordById('clients',account.id):null};}
  }
  export class TargetFixture extends MadbeautyOrganizationStaging{constructor(ctx,env){super(ctx,env);this.store=openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>now});}snapshot(){return {clientLinks:this.store.readCollections(['clientLinks']).clientLinks||[],clientReceipts:this.store.db.prepare('SELECT id FROM organization_client_admissions').all(),bookings:this.store.readCollections(['bookings']).bookings,mail:this.store.db.prepare('SELECT booking_id,state FROM mail_outbox WHERE booking_id IS NOT NULL').all(),sessions:this.store.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,accounts:this.store.db.prepare('SELECT id,operator FROM accounts').all(),preferences:this.store.readCollections(['preferences']).preferences,cachePermits:this.store.db.prepare('SELECT COUNT(*) AS n FROM directory_cache_writer_permits').get().n,jobs:this.store.db.prepare('SELECT booking_id,state FROM notification_jobs').all(),controls:this.store.db.prepare('SELECT client_id,revision FROM organization_customer_controls').all(),authority:this.authorityStatus()};}}
  export default {async fetch(request,env){const source=env.SOURCE.getByName('madbeauty-pilot-v1'),route=new URL(request.url).pathname;if(route==='/__fixture/bootstrap')return Response.json(await source.prepareFixture());if(route==='/__fixture/transfer'){const f=await source.prepareFixture(),control={operatorAccountId:users.owner.id,organizationId:f.a.org.id},frozen=await source.freezeOrganization({...control,epoch:0,requestKey:'worker-directory-transfer'}),input={...control,epoch:frozen.epoch,handoffId:frozen.handoffId},target=env.ORGANIZATION_STAGING.getByName(frozen.targetName);let offset=0;do{const page=await source.organizationHandoffPage({...input,offset});await target.stage(page);offset=page.nextOffset;if(page.done)break;}while(true);const receipt=await target.prepareAuthority(await source.organizationHandoffContext(input)),token=await source.sealOrganizationHandoff({...input,targetReceipt:receipt});return Response.json(await target.activateAuthority(token));}if(route==='/__fixture/source')return Response.json(await source.retainedSnapshot());if(route==='/__fixture/target'){const f=await source.prepareFixture();return Response.json(await env.ORGANIZATION_STAGING.getByName('madbeauty:organization:v1:'+f.a.org.id).snapshot());}if(route==='/__fixture/control-outage-on')return Response.json(await source.controlOutage(true));if(route==='/__fixture/control-outage-off')return Response.json(await source.controlOutage(false));if(route==='/__fixture/controls')return Response.json(await source.controlStatus());if(route==='/__fixture/recover-controls'){await source.recoverControls();return Response.json({recovered:true});}if(route==='/__fixture/client-lost-on')return Response.json(await source.clientReplyOutage(true));if(route==='/__fixture/client-lost-off')return Response.json(await source.clientReplyOutage(false));if(route==='/__fixture/register-manual')return Response.json(await source.registerFreshIdentity('worker-new-manual@example.com'));if(route==='/__fixture/register-team')return Response.json(await source.registerFreshIdentity('worker-directory-team@example.com'));if(route==='/__fixture/register-fresh')return Response.json(await source.registerFreshIdentity());if(route==='/__fixture/fresh')return Response.json(await source.freshIdentity());if(route==='/__fixture/forget'){await source.forgetIndex();return Response.json({ok:true});}return source.fetch(request);}};
 `},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text'}});
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-directory-workers-')),origin='https://directory-worker.test',start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{SOURCE:{className:'SourceFixture',useSQLite:true},ORGANIZATION_STAGING:{className:'TargetFixture',useSQLite:true}},durableObjectsPersist:dir,bindings:{SESSION_SECRET:'isolated-directory-worker-secret-'.repeat(3),APP_ORIGIN:origin}});let mf=start();
 try{
  const get=async route=>{const response=await mf.dispatchFetch(origin+route);assert.equal(response.status,200);return response.json();},f=await get('/__fixture/bootstrap');
  const request=async(role,method,input={},headers={},route='/api/madbeauty/rpc')=>{const s=f.sessions[role],response=await mf.dispatchFetch(origin+route,{method:route.endsWith('/session')?'GET':'POST',headers:{origin,'content-type':'application/json',cookie:'__Host-madbeauty_sid='+s.token,'x-csrf-token':s.csrf,...headers},...(route.endsWith('/session')?{}:{body:JSON.stringify({method,input})})});return {status:response.status,...await response.json()};};
  assert.equal((await get('/__fixture/transfer')).writeAuthority,true);const result=await request('client','confirm',{holdId:f.hold.id,idempotencyKey:'worker-directory-new',name:'Client'});assert.equal(result.status,200,JSON.stringify(result));const next=result.result;assert.equal(next.priceMinor,2500);assert.notEqual(next.id,f.first.id);assert.equal((await request('client','confirm',{holdId:f.hold.id,idempotencyKey:'worker-directory-new',name:'Client'})).result.id,next.id);
  assert.equal((await request('owner','workspace',f.a.scope)).result.bookings.find(b=>b.id===next.id).id,next.id);const unmigrated=await request('owner','workspace',f.b.scope);assert.equal(unmigrated.status,200,JSON.stringify(unmigrated));assert.equal(unmigrated.result.bookings[0].id,f.other.id);assert.equal(unmigrated.result.bookings.some(b=>b.id===next.id),false);assert.equal((await request('client','workspace',{role:'customer'})).result.bookings.filter(b=>b.id===next.id).length,1);assert.equal((await request('foreign','workspace',{role:'customer',clientId:'worker-directory-client'})).result.bookings.length,0);assert.equal((await request('foreign','cancelBooking',{id:next.id,version:1,reason:'Forged client',operator:true})).status,403);
  const edited=await request('owner','edit',{scope:f.a.scope,table:'services',id:f.a.service.id,version:1,values:{priceMinor:3300,label:'Current Worker target service'}});assert.equal(edited.status,200,JSON.stringify(edited));assert.equal((await request('client','searchResults',{anyTime:true})).result.treatments.find(s=>s.id===f.a.service.id).priceMinor,3300);
  assert.equal((await request('client','cancelBooking',{id:next.id,version:1},{'x-csrf-token':'bad'})).error.code,'CSRF');assert.equal((await request('client','cancelBooking',{id:next.id,version:1},{origin:'https://foreign.test'})).status,403);
  await mf.dispose();mf=start();await get('/__fixture/forget');assert.equal((await request('client','message',{bookingId:next.id,text:'Recovered ID after Workers restart'})).status,200);assert.equal((await request('client','profile',{id:f.a.org.id})).result.services[0].label,'Current Worker target service');assert.equal((await request('reception',null,{}, {},'/api/madbeauty/session')).organizations.some(o=>o.id===f.a.org.id),true);assert.equal((await request('owner','revokeMembership',{id:f.membership.id,version:1})).status,200);assert.equal((await request('reception',null,{}, {},'/api/madbeauty/session')).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await request('reception','workspace',f.a.scope)).status,403);
  await get('/__fixture/client-lost-on');const manualInput={organizationId:f.a.org.id,email:'worker-new-manual@example.com',name:'Naujas rankinis Worker klientas',idempotencyKey:'worker-manual-one'},manual=await request('owner','createClient',manualInput);assert.equal(manual.status,200,JSON.stringify(manual));assert.equal(manual.result.admission.state,'pending');assert.equal((await get('/__fixture/target')).clientLinks.filter(c=>c.clientId===manual.result.id).length,1);assert.equal((await get('/__fixture/controls')).clientAdmissions[0].state,'pending');
  await mf.dispose();mf=start();assert.equal((await get('/__fixture/controls')).clientAdmissions[0].state,'pending');await get('/__fixture/client-lost-off');await get('/__fixture/recover-controls');assert.equal((await get('/__fixture/controls')).clientAdmissions[0].state,'applied');assert.equal((await request('owner','createClient',manualInput)).result.id,manual.result.id);assert.equal((await get('/__fixture/target')).clientLinks.find(c=>c.clientId===manual.result.id).version,1);assert.equal((await get('/__fixture/target')).clientReceipts.length,1);assert.equal((await get('/__fixture/register-manual')).id,manual.result.id);
  const team=await get('/__fixture/register-team');f.sessions.team=team;
  const added=await request('owner','createClient',{organizationId:f.a.org.id,email:' WORKER-DIRECTORY-TEAM@EXAMPLE.COM ',name:'Vidinis Worker kliento vardas'});assert.equal(added.status,200,JSON.stringify(added));assert.equal(added.result.id,team.id);
  const teamGrant=await request('owner','grantMembership',{organizationId:f.a.org.id,email:'worker-directory-team@example.com',role:'manager',version:0});assert.equal(teamGrant.status,200,JSON.stringify(teamGrant));assert.equal((await request('team',null,{}, {},'/api/madbeauty/session')).organizations.find(o=>o.id===f.a.org.id).membershipRole,'manager');assert.equal((await request('team','grantMembership',{organizationId:f.a.org.id,email:'worker-directory-client@example.com',role:'reception',version:0})).status,403);
  const fresh=await get('/__fixture/register-fresh');f.sessions.fresh=fresh;const slots=await request('fresh','availability',{providerServiceId:f.a.service.id,dayOffset:1,from:900,to:1200,addons:[]}),held=await request('fresh','hold',slots.result.slots[0]);assert.equal(held.status,200,JSON.stringify(held));const freshReply=await request('fresh','confirm',{holdId:held.result.id,idempotencyKey:'worker-fresh-after-handoff',name:'Naujas Worker klientas'});assert.equal(freshReply.status,200,JSON.stringify(freshReply));const freshBooking=freshReply.result;assert.equal((await get('/__fixture/fresh')).client.name,'Naujas Worker klientas');assert.equal((await get('/__fixture/fresh')).account.name,'Naujas Worker klientas');
  await mf.dispose();mf=start();assert.equal((await request('team',null,{}, {},'/api/madbeauty/session')).organizations.find(o=>o.id===f.a.org.id).membershipRole,'manager');assert.equal((await request('owner','workspace',f.a.scope)).result.clients.find(c=>c.id===team.id).name,'Vidinis Worker kliento vardas');assert.equal((await request('owner','revokeMembership',{id:teamGrant.result.id,version:1})).status,200);assert.equal((await request('team','workspace',f.a.scope)).status,403);assert.equal((await request('team',null,{}, {},'/api/madbeauty/session')).organizations.some(o=>o.id===f.a.org.id),false);assert.equal((await request('fresh','confirm',{holdId:held.result.id,idempotencyKey:'worker-fresh-after-handoff',name:'Naujas Worker klientas'})).result.id,freshBooking.id);assert.equal((await get('/__fixture/fresh')).client.version,2);assert.equal((await request('fresh','workspace',{role:'customer'})).result.bookings.filter(b=>b.id===freshBooking.id).length,1);assert.equal((await request('owner','workspace',f.a.scope)).result.clients.find(c=>c.id===fresh.id).name,'Naujas Worker klientas');const on=await request('fresh','preferences',{service:true,marketing:false,reminderLeadMin:1440});assert.equal(on.status,200,JSON.stringify(on));assert.equal(on.result.synchronization,'applied');assert.equal((await get('/__fixture/target')).jobs.find(j=>j.booking_id===freshBooking.id).state,'planned');await get('/__fixture/control-outage-on');const off=await request('fresh','preferences',{service:false,marketing:false,reminderLeadMin:0});assert.equal(off.status,200,JSON.stringify(off));assert.equal(off.result.synchronization,'pending');assert.equal((await get('/__fixture/controls')).pending.length,1);assert.equal((await get('/__fixture/controls')).preferences.find(p=>p.clientId===fresh.id).service,false);await mf.dispose();mf=start();assert.equal((await get('/__fixture/controls')).pending.length,1);await get('/__fixture/control-outage-off');await get('/__fixture/recover-controls');assert.equal((await get('/__fixture/controls')).pending.length,0);const target=await get('/__fixture/target'),source=await get('/__fixture/source');assert.equal(target.jobs.find(j=>j.booking_id===freshBooking.id).state,'suppressed');assert.equal(target.bookings.find(b=>b.id===next.id).priceMinor,2500);assert.equal(target.mail.filter(m=>m.booking_id===next.id).length,1);assert.equal(target.sessions,0);assert.equal(target.cachePermits,0);assert.equal(target.accounts.find(a=>a.id===fresh.id).operator,0);assert.equal(target.preferences.find(p=>p.clientId===fresh.id).service,false);assert.equal(target.mail.filter(m=>m.booking_id===freshBooking.id).length,1);assert.equal(target.authority.mailAuthority,false);assert.deepEqual(source.booking,f.first);assert.equal(source.service.priceMinor,2500);assert.equal(source.bookings,1);assert.equal((await request('client','workspace',{role:'customer'})).result.bookings.filter(b=>b.id===next.id).length,1);

  const favorite=await request('client','favorite',{organizationId:f.a.org.id,saved:true});assert.equal(favorite.status,200,JSON.stringify(favorite));assert.deepEqual(favorite.result,[f.a.org.id]);
  const taxonomy=await request('owner','taxonomy'),changed=await request('owner','changeTaxonomy',{version:taxonomy.result.version,nodeId:'manikiuras',operation:'aliases',aliases:['Aktuali Worker procedūra']});assert.equal(changed.status,200,JSON.stringify(changed));assert.equal((await request('client','changeTaxonomy',{version:changed.result.version,nodeId:'manikiuras',operation:'aliases',aliases:['Denied']})).status,403);assert.equal((await request('owner','changeTaxonomy',{version:taxonomy.result.version,nodeId:'manikiuras',operation:'aliases',aliases:['Stale']})).status,409);
  assert.equal((await request('client','createInquiry',{organizationId:f.a.org.id,providerServiceId:f.a.service.id,note:'Izoliuota dabartinio target užklausa'})).status,200);const metrics=await request('owner','metrics');assert.equal(metrics.status,200,JSON.stringify(metrics));assert.equal(metrics.result.realInquiries,1);assert.equal(metrics.result.demand,'TESTING_NOT_MEASURED');assert.equal((await request('client','metrics')).status,403);
  const migrated=await request('owner','migrateCatalogue');assert.equal(migrated.status,200,JSON.stringify(migrated));assert.equal(migrated.result.added,2);assert.equal(migrated.result.services,2);assert.equal(migrated.result.bookings,4);const eventCount=(await request('owner','metrics')).result.events;
  await mf.dispose();mf=start();assert.deepEqual((await request('client','workspace',{role:'customer'})).result.client.favoriteIds,[f.a.org.id]);assert.equal((await request('owner','taxonomy')).result.version,changed.result.version);assert.equal((await request('owner','migrateCatalogue')).result.added,0);assert.equal((await request('owner','metrics')).result.events,eventCount);assert.equal((await request('owner','metrics')).result.realInquiries,1);assert.equal((await request('client','favorite',{organizationId:f.a.org.id,saved:false})).result.length,0);
 }finally{await mf.dispose();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-directory-workers-'))await rm(absolute,{recursive:true,force:true});}
});
