import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting');
const {build}=await import(pathToFileURL(path.join(runtime,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(runtime,'node_modules/miniflare/dist/src/index.js')));

test('Actual Workers source seal and prepared target persist separately; post-write failures roll back, one target confirms the old hold and stale source/foreign writers cannot resume',async()=>{
 const bundle=await build({stdin:{resolveDir:import.meta.dirname,sourcefile:'isolated-organization-authority-fixture.mjs',contents:`
  import {MadbeautyPlatform} from './platform-object.mjs';
  import {MadbeautyOrganizationStaging} from './organization-object.mjs';
  import {openDurableStore} from './store.mjs';
  import {createPlatform} from '../backend/platform.mjs';
  const now=Date.parse('2026-10-08T06:00:00Z'),owner={id:'authority-worker-owner',email:'authority-owner@example.com',name:'Fixture owner'},client={id:'authority-worker-client',email:'authority-client@example.com',name:'Fixture client'};
  export class SourceFixture extends MadbeautyPlatform{
   constructor(ctx,env){super(ctx,env);this.store=openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>now});}
   prepareFixture(){const saved=this.store.db.prepare("SELECT value FROM release_metadata WHERE key='authority-fixture'").get();if(saved)return JSON.parse(saved.value);const api=createPlatform(this.store);
    for(const u of [owner,client]){this.store.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(u.id,this.store.siteId,u.email,u.name,u.id===owner.id?1:0,now);this.store.ensureClient(u.id);}
    const make=name=>{const org=api.createOrganization(owner,{name,bio:'Actual isolated Worker authority.',kind:'solo',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=api.workspace(owner,scope),service=api.createService(owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Workers retained authority service',durationMin:60,priceMinor:2500});api.moderate({...owner,operator:true},{id:api.submitRevision(owner,{scope,name,bio:org.bio}).id,state:'approved'});return {org,service};};
    const a=make('Worker authority A'),b=make('Worker authority B'),candidate=f=>api.availability({providerServiceId:f.service.id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0],book=f=>api.confirm(client,{holdId:api.hold(client,candidate(f)).id,idempotencyKey:f.org.id,name:'Original worker client'}),first=book(a),other=book(b),hold=api.hold(client,candidate(a)),info={a,b,first,other,hold};this.store.db.prepare('INSERT INTO release_metadata VALUES(?,?)').run('authority-fixture',JSON.stringify(info));return info;
   }
   rememberAbort(token){this.store.db.prepare("INSERT INTO release_metadata VALUES('authority-abort',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify(token));}
   priorAbort(){return JSON.parse(this.store.db.prepare("SELECT value FROM release_metadata WHERE key='authority-abort'").get().value);}
   sourceSnapshot(){const f=this.prepareFixture();return {first:this.store.recordById('bookings',f.first.id),other:this.store.recordById('bookings',f.other.id),mail:this.store.db.prepare('SELECT id,organization_id,booking_id,state,payload FROM mail_outbox ORDER BY id').all(),commits:this.store.db.prepare('SELECT COUNT(*) AS n FROM organization_handoff_commits').get()?.n||0};}
   failSeal(input){const prepare=this.store.db.prepare;this.store.db.prepare=q=>{const s=prepare(q);if(!q.startsWith("UPDATE organization_handoffs SET state='sealed'"))return s;return {...s,run:(...args)=>{s.run(...args);throw Error('Isolated Worker source seal failure');}};};try{return this.sealOrganizationHandoff(input);}finally{this.store.db.prepare=prepare;}}
   async errors(){const f=this.prepareFixture(),api=createPlatform(this.store),errors=[];for(const fn of [()=>api.cancelBooking(client,{id:f.first.id,version:1,reason:'Old source cannot resume'}),()=>this.store.db.prepare('UPDATE platform_state SET version=version+1 WHERE site_id=?').run(this.store.siteId),()=>this.store.db.prepare('DELETE FROM state_rows WHERE site_id=? AND collection=? AND record_key=?').run(this.store.siteId,'bookings','id:'+f.first.id),()=>this.store.db.prepare("UPDATE mail_outbox SET state='sending' WHERE booking_id=?").run(f.first.id),()=>this.store.db.prepare('DELETE FROM notification_jobs WHERE booking_id=?').run(f.first.id)]){try{fn();errors.push('Writer escaped');}catch(e){errors.push(e.code||e.message);}}return errors;}
   foreignChange(){const f=this.prepareFixture();createPlatform(this.store).cancelBooking(client,{id:f.other.id,version:1,reason:'Foreign source remains writable'});return this.store.recordById('bookings',f.other.id);}
  }
  export class TargetFixture extends MadbeautyOrganizationStaging{
   constructor(ctx,env){super(ctx,env);this.store=openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>now});}
   failPrepare(packet){const prepare=this.store.db.prepare;this.store.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO notification_jobs'))return s;return {...s,run:(...args)=>{s.run(...args);throw Error('Isolated Worker target import failure');}};};try{return this.prepareAuthority(packet);}finally{this.store.db.prepare=prepare;}}
   failDiscard(token){const prepare=this.store.db.prepare;this.store.db.prepare=q=>{const s=prepare(q);if(q!=='DELETE FROM accounts WHERE site_id=?')return s;return {...s,run:(...args)=>{s.run(...args);throw Error('Isolated Worker discard failure');}};};try{return this.discardAuthority(token);}finally{this.store.db.prepare=prepare;}}
   confirmFixture(holdId){return createPlatform(this.store).confirm(client,{holdId,idempotencyKey:'worker-target-confirm',name:'Target worker client'});}
   targetSnapshot(firstId){const first=this.store.recordById('bookings',firstId),mail=this.store.db.prepare('SELECT id,booking_id,state,payload FROM mail_outbox ORDER BY id').all();return {first,bookings:this.store.readCollections(['bookings']).bookings,mail,payloads:mail.map(r=>this.store.unseal(r.payload)),accounts:this.store.db.prepare('SELECT id,operator FROM accounts ORDER BY id').all(),sessions:this.store.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n};}
   targetErrors(firstId,foreignId){const first=this.store.recordById('bookings',firstId),api=createPlatform(this.store),errors=[];for(const fn of [()=>this.store.db.prepare('UPDATE platform_state SET version=version+1 WHERE site_id=?').run(this.store.siteId),()=>api.cancelBooking({...client,id:'unrelated-worker-client'},{id:firstId,version:1,reason:'Foreign user denied'}),()=>api.createResource(owner,{organizationId:foreignId,label:'Forbidden cross-organization resource'}),()=>api.preferences(client,{service:false,marketing:false,reminderLeadMin:0})]){try{fn();errors.push('Writer escaped');}catch(e){errors.push(e.code||e.message);}}return errors;}
  }
  export default {async fetch(request,env){const source=env.SOURCE.getByName('madbeauty-pilot-v1'),f=await source.prepareFixture(),control={operatorAccountId:owner.id,organizationId:f.a.org.id},route=new URL(request.url).pathname;try{
   let status=await source.organizationHandoffStatus(control);if(route==='/bootstrap'){status=await source.freezeOrganization({...control,epoch:0,requestKey:'worker-authority'});let offset=0;const target=env.ORGANIZATION_STAGING.getByName(status.targetName);do{const p=await source.organizationHandoffPage({...control,epoch:status.epoch,handoffId:status.handoffId,offset});await target.stage(p);offset=p.nextOffset;if(p.done)break;}while(true);await source.organizationHandoffContext({...control,epoch:status.epoch,handoffId:status.handoffId});return Response.json({status,first:f.first,other:f.other,hold:f.hold});}
   const input={...control,epoch:status.epoch,handoffId:status.handoffId},target=env.ORGANIZATION_STAGING.getByName(status.targetName);let result;
   if(route==='/fail-discard'){const token=await source.abortPreparedOrganizationHandoff(input);await source.rememberAbort(token);result=await target.failDiscard(token);}else if(route==='/replace-prepared'){const token=await source.abortPreparedOrganizationHandoff(input);await source.rememberAbort(token);await target.discardAuthority(token);const next=await source.freezeOrganization({...control,epoch:status.epoch,requestKey:'replacement-worker-authority'}),nextInput={...control,epoch:next.epoch,handoffId:next.handoffId};let offset=0;do{const p=await source.organizationHandoffPage({...nextInput,offset});await target.stage(p);offset=p.nextOffset;if(p.done)break;}while(true);result=await target.prepareAuthority(await source.organizationHandoffContext(nextInput));}else if(route==='/stale-discard')result=await target.discardAuthority(await source.priorAbort());else if(route==='/source')result={status,snapshot:await source.sourceSnapshot()};else if(route==='/target')result={status:await target.authorityStatus(),snapshot:await target.targetSnapshot(f.first.id)};else if(route==='/fail-prepare')result=await target.failPrepare(await source.organizationHandoffContext(input));else if(route==='/prepare')result=await target.prepareAuthority(await source.organizationHandoffContext(input));else if(route==='/wrong-target')result=await env.ORGANIZATION_STAGING.getByName('madbeauty:organization:v1:'+f.b.org.id).prepareAuthority(await source.organizationHandoffContext(input));else if(route==='/commit-fail')result=await source.failSeal({...input,targetReceipt:await target.prepareAuthority(await source.organizationHandoffContext(input))});else if(route==='/seal')result=await source.sealOrganizationHandoff({...input,targetReceipt:await target.prepareAuthority(await source.organizationHandoffContext(input))});else if(route==='/activate'||route==='/activate-forged'){const token=await source.sealOrganizationHandoff({...input,targetReceipt:await target.prepareAuthority(await source.organizationHandoffContext(input))});result=await target.activateAuthority(route==='/activate'?token:{...token,epoch:999});}else if(route==='/confirm')result=await target.confirmFixture(f.hold.id);else if(route==='/abort')result=await source.abortPreparedOrganizationHandoff(input);else if(route==='/source-errors')result=await source.errors();else if(route==='/target-errors')result=await target.targetErrors(f.first.id,f.b.org.id);else if(route==='/foreign-change')result=await source.foreignChange();else return new Response('Not found',{status:404});return Response.json(result);
  }catch(e){return Response.json({error:e.code||e.message});}}};
 `},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text'}});
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-authority-workers-')),start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{SOURCE:{className:'SourceFixture',useSQLite:true},ORGANIZATION_STAGING:{className:'TargetFixture',useSQLite:true}},durableObjectsPersist:dir,bindings:{SESSION_SECRET:'isolated-authority-worker-secret-'.repeat(3)}});let mf=start();
 try{
  const get=async route=>{const response=await mf.dispatchFetch('https://authority-fixture.test'+route);assert.equal(response.status,200);return response.json();};
  const before=await get('/bootstrap');assert.equal(before.status.state,'frozen');assert.ok((await get('/wrong-target')).error.includes('identity mismatch'));assert.equal((await get('/fail-prepare')).error,'Isolated Worker target import failure');let target=await get('/target');assert.equal(target.status.state,'empty');assert.equal(target.snapshot.bookings.length,0);assert.equal(target.snapshot.accounts.length,0);assert.equal(target.snapshot.mail.length,0);
  let receipt=await get('/prepare');assert.equal(receipt.state,'prepared');assert.deepEqual(await get('/prepare'),receipt);target=await get('/target');assert.deepEqual(target.snapshot.first,before.first);assert.equal(target.status.writeAuthority,false);assert.equal(target.snapshot.sessions,0);assert.ok(target.snapshot.accounts.every(a=>a.operator===0));assert.equal((await get('/confirm')).error,'ORGANIZATION_MIGRATING');assert.equal((await get('/commit-fail')).error,'Isolated Worker source seal failure');let source=await get('/source');assert.equal(source.status.state,'frozen');assert.equal(source.snapshot.commits,0);assert.deepEqual(source.snapshot.first,before.first);
  await mf.dispose();mf=start();assert.equal((await get('/target')).status.state,'prepared');assert.equal((await get('/fail-discard')).error,'Isolated Worker discard failure');assert.equal((await get('/source')).status.state,'aborted');assert.equal((await get('/target')).status.state,'prepared');assert.deepEqual((await get('/target')).snapshot.first,before.first);receipt=await get('/replace-prepared');assert.equal(receipt.epoch,2);assert.equal((await get('/stale-discard')).error,'INVALID_STATE');const token=await get('/seal');assert.equal(token.targetReceipt.nonce,receipt.nonce);source=await get('/source');assert.equal(source.status.state,'sealed');assert.equal((await get('/abort')).error,'INVALID_STATE');assert.equal((await get('/activate-forged')).error,'FORBIDDEN');assert.equal((await get('/target')).status.writeAuthority,false);
  await mf.dispose();mf=start();assert.equal((await get('/target')).status.state,'prepared');assert.equal((await get('/activate')).writeAuthority,true);assert.equal((await get('/target')).status.mailAuthority,false);const next=await get('/confirm');assert.ok(next.id,next.error);assert.notEqual(next.id,before.first.id);assert.equal(next.priceMinor,2500);assert.equal((await get('/confirm')).id,next.id);target=await get('/target');assert.deepEqual(target.snapshot.first,before.first);assert.equal(target.snapshot.mail.filter(m=>m.booking_id===next.id).length,1);assert.equal(target.snapshot.payloads.find(p=>p.bookingId===next.id).priceMinor,2500);
  const errors=await get('/source-errors');assert.equal(errors.length,5);assert.ok(errors.every(e=>e.includes('ORGANIZATION_MIGRATING')),JSON.stringify(errors));const denied=await get('/target-errors');assert.equal(denied.length,4);assert.ok(denied.every(e=>e!=='Writer escaped'),JSON.stringify(denied));assert.equal((await get('/foreign-change')).status,'canceled');source=await get('/source');assert.deepEqual(source.snapshot.first,before.first);assert.equal(source.snapshot.mail.some(m=>m.booking_id===next.id),false);
  await mf.dispose();mf=start();target=await get('/target');assert.equal(target.status.state,'active');assert.equal(target.snapshot.bookings.find(b=>b.id===next.id).priceMinor,2500);assert.equal((await get('/abort')).error,'INVALID_STATE');assert.equal((await get('/stale-discard')).error,'INVALID_STATE');assert.deepEqual((await get('/source')).snapshot.first,before.first);
 }finally{await mf.dispose();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-authority-workers-'))await rm(absolute,{recursive:true,force:true});}
});
