import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const runtime=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting'),{build}=await import(pathToFileURL(path.join(runtime,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(runtime,'node_modules/miniflare/dist/src/index.js'))),hash=bytes=>createHash('sha256').update(bytes).digest('hex');
test('Actual Workers ordinary upload stores a real raster in the current target and recovers a lost committed response after both objects restart',async()=>{
 const bundle=await build({stdin:{resolveDir:import.meta.dirname,sourcefile:'isolated-upload-workers.mjs',contents:`
  import {createHash} from 'node:crypto';
  import {MadbeautyPlatform} from './platform-object.mjs';
  import {MadbeautyOrganizationStaging} from './organization-object.mjs';
  import {createPlatform} from '../backend/platform.mjs';
  import {createAuth} from '../backend/auth.mjs';
  import {createOrganizationDirectory} from '../backend/organization-directory.mjs';
  const hash=b=>createHash('sha256').update(b).digest('hex');
  export class UploadSource extends MadbeautyPlatform{
   constructor(ctx,env){super(ctx,env);this.store.db.exec('CREATE TABLE IF NOT EXISTS qa_upload_metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);');}
   async setup(){let row=this.store.db.prepare("SELECT value FROM qa_upload_metadata WHERE key='upload-fixture'").get();if(row)return JSON.parse(row.value);
    const owner={id:'workers-upload-owner',email:'upload-owner@example.com',name:'Isolated owner'},foreign={id:'workers-upload-foreign',email:'upload-foreign@example.com',name:'Isolated foreign'};
    const auth=createAuth(this.store),sessions={};for(const [role,user]of Object.entries({owner,foreign})){this.store.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(user.id,this.store.siteId,user.email,user.name,role==='owner'?1:0,Date.now());this.store.ensureClient(user.id);const session=auth.session(null);this.store.db.prepare('UPDATE sessions SET account_id=? WHERE token_hash=?').run(user.id,session.token_hash);sessions[role]={token:session.token,csrf:session.csrf};}
    const api=createPlatform(this.store),org=api.createOrganization(owner,{name:'Isolated moved upload',kind:'solo',city:'Vilnius',bio:'Real raster in isolated Workers.'}),workspace=api.workspace(owner,{role:'professional',organizationId:org.id});api.createService(owner,{organizationId:org.id,practitionerId:workspace.practitioners[0].id,resourceId:workspace.resources[0].id,taxonomyServiceId:'manikiuras',label:'Isolated original service',durationMin:60,priceMinor:2500});
    const frozen=await this.freezeOrganization({operatorAccountId:owner.id,organizationId:org.id,epoch:0,requestKey:'workers-upload-handoff'}),control={operatorAccountId:owner.id,organizationId:org.id,epoch:frozen.epoch,handoffId:frozen.handoffId},target=this.env.ORGANIZATION_STAGING.get(this.env.ORGANIZATION_STAGING.idFromName(frozen.targetName));let offset=0;for(;;){const page=await this.organizationHandoffPage({...control,offset});await target.stage(page);if(page.done)break;offset=page.nextOffset;}const receipt=await target.prepareAuthority(await this.organizationHandoffContext(control));await target.activateAuthority(await this.sealOrganizationHandoff({...control,targetReceipt:receipt}));
    const info={org,owner,sessions,targetName:frozen.targetName};this.store.db.prepare("INSERT INTO qa_upload_metadata VALUES('upload-fixture',?)").run(JSON.stringify(info));this.store.db.prepare("INSERT INTO qa_upload_metadata VALUES('upload-lose-reply','1')").run();return info;
   }
   directory(){return createOrganizationDirectory(this.store,{getTarget:name=>{const target=this.env.ORGANIZATION_STAGING.get(this.env.ORGANIZATION_STAGING.idFromName(name));return {executeDirectoryCommand:packet=>target.executeDirectoryCommand(packet),readOrganizationMedia:packet=>target.readOrganizationMedia(packet),storeOrganizationMedia:async(packet,objects)=>{const response=await target.storeOrganizationMedia(packet,objects);if(!response.error&&this.store.db.prepare("SELECT value FROM qa_upload_metadata WHERE key='upload-lose-reply'").get()?.value==='1'){this.store.db.prepare("UPDATE qa_upload_metadata SET value='0' WHERE key='upload-lose-reply'").run();throw Error('Lost committed upload reply');}return response;}};}});}
   stats(){return {loseFlag:this.store.db.prepare("SELECT value FROM qa_upload_metadata WHERE key='upload-lose-reply'").get()?.value,handoffs:this.store.db.prepare('SELECT state FROM organization_handoffs').all(),media:this.store.readCollections(['media']).media.length,intents:this.store.db.prepare('SELECT COUNT(*) AS n FROM directory_media_uploads').get().n,pending:this.store.db.prepare('SELECT COUNT(*) AS n FROM directory_media_uploads WHERE result IS NULL').get().n};}
  }
  export class UploadTarget extends MadbeautyOrganizationStaging{
   async stats(){const assets=this.store.readCollections(['media']).media;return {assets:assets.map(a=>({id:a.id,variants:a.variants.map(v=>({file:v.storageFile,width:v.width,height:v.height,sha256:v.sha256})),originalSha256:a.source.sha256,rightsConfirmedBy:a.rightsConfirmedBy})),bucket:this.mediaBucket.stats(),receipts:this.store.db.prepare('SELECT COUNT(*) AS n FROM organization_media_uploads').get().n,sessions:this.store.db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n};}
  }
  export default {async fetch(request,env){const source=env.PLATFORM.get(env.PLATFORM.idFromName('isolated-upload-source')),url=new URL(request.url);if(url.pathname==='/fixture/setup')return Response.json(await source.setup());if(url.pathname==='/fixture/stats'){const info=await source.setup(),target=env.ORGANIZATION_STAGING.get(env.ORGANIZATION_STAGING.idFromName(info.targetName));return Response.json({source:await source.stats(),target:await target.stats()});}return source.fetch(request);}};
 `},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text'}});
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-upload-workers-')),origin='https://upload-workers.test',start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'UploadSource',useSQLite:true},ORGANIZATION_STAGING:{className:'UploadTarget',useSQLite:true}},durableObjectsPersist:dir,images:{binding:'IMAGES'},bindings:{APP_ORIGIN:origin,SESSION_SECRET:'isolated-upload-workers-secret-only'}});let mf=start();
 try{
  const info=await(await mf.dispatchFetch(origin+'/fixture/setup')).json(),require=createRequire(path.resolve(import.meta.dirname,'../../../content-studio/package.json')),{default:sharp}=await import(pathToFileURL(require.resolve('sharp'))),bytes=await sharp({create:{width:16,height:24,channels:3,background:'#9b60ad'}}).png().toBuffer();
  const headers=role=>({'cookie':'__Host-madbeauty_sid='+info.sessions[role].token,origin,'x-csrf-token':info.sessions[role].csrf}),upload=async(role='owner',extra={})=>{const response=await mf.dispatchFetch(origin+'/api/madbeauty/upload',{method:'POST',headers:{...headers(role),'content-type':'image/png','x-organization-id':info.org.id,'x-asset-operation':'workers-same-upload-intent','x-asset-alt':'Real isolated raster','x-asset-rights':'Created only for isolated test','x-asset-rights-confirmed':'true','x-asset-usage':'gallery',...extra},body:bytes});return {status:response.status,value:await response.json()};},rpc=async(method,input)=>{const response=await mf.dispatchFetch(origin+'/api/madbeauty/rpc',{method:'POST',headers:{...headers('owner'),'content-type':'application/json'},body:JSON.stringify({method,input})});const value=await response.json();assert.equal(response.status,200,method+': '+JSON.stringify(value));return value.result;},stats=async()=>await(await mf.dispatchFetch(origin+'/fixture/stats')).json();
  assert.equal((await upload('foreign')).status,403);assert.equal((await stats()).source.intents,0);
  const lost=await upload();assert.equal(lost.status,503,JSON.stringify({response:lost,stats:await stats()}));let state=await stats();assert.equal(state.source.pending,1);assert.equal(state.source.media,0);assert.equal(state.target.assets.length,1);assert.equal(state.target.receipts,1);assert.equal(state.target.assets[0].originalSha256,hash(bytes));assert.equal(state.target.sessions,0);const asset=state.target.assets[0],file=asset.variants[0].file;
  const image=role=>mf.dispatchFetch(origin+'/api/madbeauty/media/'+file,{headers:role?headers(role):{}});assert.equal((await image(null)).status,404);let privateImage=await image('owner');assert.equal(privateImage.status,200);const optimized=Buffer.from(await privateImage.arrayBuffer());assert.equal(hash(optimized),asset.variants[0].sha256);const decoded=await sharp(optimized).metadata();assert.equal(decoded.width,16);assert.equal(decoded.height,24);assert.equal(decoded.format,'webp');
  await mf.dispose();mf=start();const recovered=await upload();assert.equal(recovered.status,200);assert.equal(recovered.value.result.id,asset.id);state=await stats();assert.equal(state.source.pending,0);assert.equal(state.source.intents,1);assert.equal(state.target.assets.length,1);assert.equal(state.target.receipts,1);assert.equal(state.target.bucket.objects,2);assert.equal((await upload('owner',{'x-asset-alt':'Changed intent'})).value.error.code,'IDEMPOTENCY_CONFLICT');
  const revision=await rpc('submitRevision',{scope:{role:'professional',organizationId:info.org.id},name:info.org.name,bio:info.org.bio});await rpc('moderate',{id:revision.id,state:'approved'});assert.equal((await image(null)).status,200);
  await mf.dispose();mf=start();assert.equal((await image(null)).status,200);state=await stats();assert.equal(state.source.media,0);assert.equal(state.target.assets[0].id,asset.id);assert.equal(state.target.sessions,0);
 }finally{await mf.dispose();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-upload-workers-'))await rm(absolute,{recursive:true,force:true});}
});
