import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting');
const {build}=await import(pathToFileURL(path.join(runtime,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(runtime,'node_modules/miniflare/dist/src/index.js')));

test('Actual separate Workers SQLite objects persist a fenced source and read-only target across partial import failure/restart; old writer and forged target cannot book',async()=>{
 const bundle=await build({stdin:{resolveDir:import.meta.dirname,sourcefile:'isolated-calendar-handoff-fixture.mjs',contents:`
  import {MadbeautyPlatform} from './platform-object.mjs';
  import {MadbeautyOrganizationStaging} from './organization-object.mjs';
  import {createPlatform} from '../backend/platform.mjs';
  export class SourceFixture extends MadbeautyPlatform {
   constructor(ctx,env){super(ctx,env);this.store.clock=()=>Date.parse('2026-10-08T06:00:00Z');this.owner={id:'handoff-worker-owner',email:'owner@example.com',operator:true};this.client={id:'handoff-worker-client',email:'client@example.com'};
    if(!this.store.readCollections(['organizations']).organizations.length){const d=this.store.read();d.clients.push({...this.owner,name:'Owner fixture',version:1},{...this.client,name:'Client fixture',version:1});this.store.write(d);for(const u of [this.owner,this.client])this.store.db.prepare('INSERT INTO accounts(id,site_id,email,name,operator,created_at) VALUES(?,?,?,?,?,?)').run(u.id,this.store.siteId,u.email,'Isolated fixture',u.operator?1:0,this.store.clock());const api=createPlatform(this.store);for(const name of ['Worker Handoff A','Worker Handoff B']){const org=api.createOrganization(this.owner,{name,city:'Vilnius',kind:'solo',bio:'Isolated actual Workers handoff.'}),scope={role:'professional',organizationId:org.id},w=api.workspace(this.owner,scope);api.createService(this.owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Workers preserved service',durationMin:60,priceMinor:2500});api.moderate(this.owner,{id:api.submitRevision(this.owner,{scope,name,bio:org.bio}).id,state:'approved'});}}
   }
   info(){const orgs=this.store.readCollections(['organizations']).organizations,a=orgs.find(o=>o.name==='Worker Handoff A'),b=orgs.find(o=>o.name==='Worker Handoff B');return {a,b,control:{operatorAccountId:this.owner.id,organizationId:a.id,epoch:0,requestKey:'worker-handoff'}};}
   async control(action,input){try{return await ({freeze:()=>this.freezeOrganization(input),page:()=>this.organizationHandoffPage(input),abort:()=>this.abortOrganizationHandoff(input),status:()=>this.organizationHandoffStatus(input)})[action]();}catch(e){return {error:e.code||e.message,status:e.status||500};}}
   fixture(action){const {a,b}=this.info(),api=createPlatform(this.store),slot=org=>api.availability({providerServiceId:this.store.organizationRecords('services',org.id)[0].id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0];
    if(action==='prepare'){for(const org of [a,b]){const hold=api.hold(this.client,slot(org));api.confirm(this.client,{holdId:hold.id,idempotencyKey:org.id,name:'Worker client'});api.selectProcedures(this.owner,{organizationId:org.id,procedureIds:['kirpimai-vyru-kirpimas'],version:0,idempotencyKey:'worker-select-'+org.id});}const d=this.store.read();for(let n=0;n<180;n++)d.bookings.push({id:'worker-own-retained-'+n,organizationId:a.id,clientId:this.client.id,status:'completed',serviceSnapshot:{label:'Exact retained private snapshot',priceMinor:2300}});for(let n=0;n<5000;n++)d.bookings.push({id:'worker-foreign-retained-'+n,organizationId:b.id,clientId:'foreign-worker-client-'+n,status:'completed',serviceSnapshot:{privateNote:'x'.repeat(500)}});this.store.write(d);}
    if(action==='sql-fence-check'){const booking=this.store.organizationRecords('bookings',a.id).find(x=>x.status==='confirmed'),d=JSON.parse(this.store.db.prepare('SELECT data FROM platform_state WHERE site_id=?').get(this.store.siteId).data);d.bookings.find(x=>x.id===booking.id).status='canceled';const errors=[];for(const write of [()=>this.store.db.prepare('UPDATE platform_state SET data=?,version=version+1 WHERE site_id=?').run(JSON.stringify(d),this.store.siteId),()=>this.store.db.prepare('UPDATE state_rows SET data=? WHERE site_id=? AND collection=? AND record_key=?').run(JSON.stringify({...booking,status:'canceled'}),this.store.siteId,'bookings','id:'+booking.id),()=>this.store.db.prepare('DELETE FROM state_rows WHERE site_id=? AND collection=? AND record_key=?').run(this.store.siteId,'bookings','id:'+booking.id)]){try{write();errors.push('Unexpected old writer bypass');}catch(e){errors.push(e.message);}}return {errors,permits:this.store.db.prepare('SELECT COUNT(*) AS n FROM state_writer_permits').get().n};}
    if(action==='fence-check'){const booking=this.store.organizationRecords('bookings',a.id).find(x=>x.status==='confirmed'),errors=[];for(const change of [()=>api.cancelBooking(this.client,{id:booking.id,version:1,reason:'Blocked source cancel'}),()=>api.preferences(this.client,{service:false,marketing:true,reminderLeadMin:0}),()=>api.createClient(this.owner,{organizationId:a.id,email:'blocked-worker-manual@example.com',name:'Blocked worker client'}),()=>{const d=this.store.read();d.bookings.find(x=>x.id===booking.id).status='canceled';this.store.write(d);},()=>{const row=this.store.db.prepare('SELECT * FROM mail_outbox WHERE booking_id=?').get(booking.id);this.store.retryMail(row);},()=>this.store.mail({organizationId:a.id,recipient:this.client.email,type:'confirmation',payload:{}})]){try{change();errors.push('Unexpected source write');}catch(e){errors.push(e.code||e.message);}}if(this.store.db.prepare('SELECT id FROM accounts WHERE email=?').get('blocked-worker-manual@example.com'))throw Error('Leaked manual account');return {errors,...this.fixture('status')};}
    if(action==='other-write'){api.createResource(this.owner,{organizationId:b.id,label:'Other organization remains writable'});}
    if(action==='automation'){api.runAutomation();}
    if(action==='resume'){const booking=this.store.organizationRecords('bookings',a.id).find(x=>x.status==='confirmed');api.cancelBooking(this.client,{id:booking.id,version:1,reason:'Resumed original source after partial copy'});}
    const first=this.store.organizationRecords('bookings',a.id).find(x=>x.serviceSnapshot?.label==='Workers preserved service'),other=this.store.organizationRecords('bookings',b.id).find(x=>x.serviceSnapshot?.label==='Workers preserved service');return {first,other,rows:this.store.organizationRecords('bookings',a.id).length,foreignRows:this.store.organizationRecords('bookings',b.id).length,preferences:this.store.clientRecords('preferences',this.client.id),mail:this.store.db.prepare('SELECT organization_id,state,booking_id FROM mail_outbox WHERE booking_id IS NOT NULL ORDER BY created_at').all(),job:this.store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(first?.id),version:this.store.rowStats().version};
   }
   async freezeGuarded(input){const prepare=this.store.db.prepare;this.store.db.prepare=q=>{if(/FROM state_rows\\b/i.test(q)&&!/\\bcollection\\s*=/i.test(q))throw Error('Global Worker migration history scan forbidden');return prepare(q);};try{return await this.control('freeze',input);}finally{this.store.db.prepare=prepare;}}
   async failFreeze(input){const prepare=this.store.db.prepare;let n=0;this.store.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO organization_handoff_rows'))return s;return {...s,run:(...args)=>{s.run(...args);if(++n===3)throw Error('Isolated Worker snapshot failure');}};};try{return await this.control('freeze',input);}finally{this.store.db.prepare=prepare;}}
  }
  export class TargetFixture extends MadbeautyOrganizationStaging {
   failPage(packet){const prepare=this.store.db.prepare;let n=0;this.store.db.prepare=q=>{const s=prepare(q);if(!q.startsWith('INSERT INTO organization_stage_rows'))return s;return {...s,run:(...args)=>{s.run(...args);if(++n===2)throw Error('Isolated Worker target failure');}};};try{this.stage(packet);return {error:'Expected target failure missing'};}catch(e){return {error:e.code||e.message};}finally{this.store.db.prepare=prepare;}}
   stagedFirst(){const records=this.store.db.prepare('SELECT data FROM organization_stage_rows WHERE site_id=? ORDER BY ordinal').all(this.store.siteId).map(r=>JSON.parse(r.data));return {first:records.filter(r=>r.collection==='bookings').map(r=>JSON.parse(r.raw)).find(x=>x.serviceSnapshot?.label==='Workers preserved service'),replayKeys:records.filter(r=>r.collection==='idempotency').map(r=>r.key),liveBookings:this.store.readCollections(['bookings']).bookings.length,foreignPresent:JSON.stringify(records).includes('worker-foreign-retained-')};}
  }
  export default {async fetch(request,env){const source=env.SOURCE.getByName('madbeauty-pilot-v1'),url=new URL(request.url),route=url.pathname,info=await source.info(),control=info.control;let result;
   if(route==='/sql-fence')return Response.json(await source.fixture('sql-fence-check'));
   if(route==='/prepare')result=await source.fixture('prepare');else if(route==='/failed-freeze')result=await source.failFreeze(control);else if(route==='/denied')result=await source.control('freeze',{...control,operatorAccountId:'handoff-worker-client'});else if(route==='/freeze')result=await source.freezeGuarded(control);else if(route==='/status')result=await source.control('status',control);else if(route==='/source')result=await source.fixture('status');else if(route==='/fence-check')result=await source.fixture('fence-check');else if(route==='/other')result=await source.fixture('other-write');else if(route==='/automation')result=await source.fixture('automation');else if(route==='/drain'){await source.drain();result=await source.fixture('status');}else if(route==='/abort'||route==='/resume'){const status=await source.control('status',control);result=await source.control('abort',{...control,epoch:status.epoch,handoffId:status.handoffId});if(route==='/resume')result=await source.fixture('resume');}else{
    const status=await source.control('status',control),target=env.ORGANIZATION_STAGING.getByName(status.targetName);
    if(route==='/target')result=await target.stagingStatus();else if(route==='/target-first')result=await target.stagedFirst();else {const packet=await source.control('page',{...control,epoch:status.epoch,handoffId:status.handoffId,offset:Number(url.searchParams.get('offset')||0)});if(route==='/packet')result=packet;else if(route==='/fail-page')result=await target.failPage(packet);else if(route==='/stage')result=await target.stage(packet);else if(route==='/wrong-target'){try{await env.ORGANIZATION_STAGING.getByName('madbeauty:organization:v1:'+info.b.id).stage(packet);result={error:'Missing object identity guard'};}catch(e){result={error:e.message};}}else if(route==='/tamper'){try{await target.stage({...packet,nextOffset:999});result={error:'Missing signature guard'};}catch(e){result={error:e.message};}}else return new Response('Not found',{status:404});}
   }return Response.json(result);
  }};
 `},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text'}});
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-handoff-workers-')),mails=[],start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{SOURCE:{className:'SourceFixture',useSQLite:true},ORGANIZATION_STAGING:{className:'TargetFixture',useSQLite:true}},durableObjectsPersist:dir,bindings:{SESSION_SECRET:'isolated-worker-handoff-secret-'.repeat(3)},serviceBindings:{MAIL_TRANSPORT:async request=>{mails.push(await request.json());return new Response('Accepted');}}});let mf=start();
 try{
  const get=async route=>{const response=await mf.dispatchFetch('https://handoff-fixture.test'+route),value=await response.json();assert.equal(response.status,200,JSON.stringify(value));return value;};
  const before=await get('/prepare');assert.equal((await get('/denied')).error,'FORBIDDEN');assert.equal((await get('/failed-freeze')).error,'Isolated Worker snapshot failure');assert.equal((await get('/status')).state,'source');assert.deepEqual(await get('/source'),before);
  const frozen=await get('/freeze');assert.equal(frozen.state,'frozen');assert.equal(frozen.manifest.mode,'read-only-staging');assert.deepEqual(await get('/freeze'),frozen);assert.ok((await get('/wrong-target')).error.includes('identity mismatch'));assert.ok((await get('/tamper')).error.includes('nepatvirtintas'));assert.equal((await get('/target')).rows,0);
  const sqlFenced=await get('/sql-fence');assert.equal(sqlFenced.errors.length,3);assert.ok(sqlFenced.errors.every(e=>e.includes('ORGANIZATION_MIGRATING')),JSON.stringify(sqlFenced));assert.equal(sqlFenced.permits,0);
  const checked=await get('/fence-check');assert.deepEqual(checked.errors,Array(6).fill('ORGANIZATION_MIGRATING'));assert.deepEqual(checked.first,before.first);assert.deepEqual(checked.job,before.job);assert.deepEqual(checked.preferences,before.preferences);assert.equal(checked.version,before.version);assert.deepEqual(checked.mail,before.mail);await get('/other');await get('/automation');assert.deepEqual((await get('/source')).first,before.first);
  const drained=await get('/drain');assert.equal(drained.mail.find(m=>m.booking_id===before.first.id).state,'pending');assert.equal(drained.mail.find(m=>m.booking_id===before.other.id).state,'accepted');assert.equal(mails.length,1);
  const packet=await get('/packet'),firstPage=await get('/stage');assert.equal(firstPage.state,'receiving');assert.equal(firstPage.writeAuthority,false);assert.equal((await get('/fail-page?offset='+packet.nextOffset)).error,'Isolated Worker target failure');assert.deepEqual(await get('/target'),firstPage);
  await mf.dispose();mf=start();assert.deepEqual(await get('/status'),frozen);assert.deepEqual(await get('/target'),firstPage);assert.deepEqual((await get('/fence-check')).errors,Array(6).fill('ORGANIZATION_MIGRATING'));let offset=0,summary;do{const page=await get('/packet?offset='+offset);summary=await get('/stage?offset='+offset);assert.deepEqual(await get('/stage?offset='+offset),summary);offset=page.nextOffset;if(page.done)break;}while(true);
  assert.equal(summary.state,'ready-read-only');assert.equal(summary.rows,frozen.manifest.rows);assert.equal(summary.sha256,frozen.manifest.sha256);assert.equal(summary.writeAuthority,false);const imported=await get('/target-first');assert.deepEqual(imported.first,before.first);assert.equal(imported.foreignPresent,false);assert.equal(imported.liveBookings,0);assert.ok(imported.replayKeys.includes('handoff-worker-client:'+before.first.organizationId));assert.ok(!imported.replayKeys.includes('handoff-worker-client:'+before.other.organizationId));
  const restartedSql=await get('/sql-fence');assert.ok(restartedSql.errors.every(e=>e.includes('ORGANIZATION_MIGRATING')));assert.equal(restartedSql.permits,0);
  const resumed=await get('/resume');assert.equal(resumed.first.status,'canceled');assert.equal(resumed.first.id,before.first.id);assert.deepEqual(resumed.other,before.other);assert.equal((await get('/status')).state,'aborted');assert.equal((await get('/target')).writeAuthority,false);await mf.dispose();mf=start();assert.equal((await get('/source')).first.status,'canceled');assert.equal((await get('/target')).state,'ready-read-only');
 }finally{await mf.dispose();const absolute=path.resolve(dir);if(absolute.startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-handoff-workers-'))await rm(absolute,{recursive:true,force:true});}
});
