import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting');
const {build}=await import(pathToFileURL(path.join(runtime,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(runtime,'node_modules/miniflare/dist/src/index.js')));
test('Actual Workers organization patch books against 5000 unrelated rows without global read; other reminder and snapshots survive conflict/restart',async()=>{
 const bundle=await build({stdin:{resolveDir:import.meta.dirname,sourcefile:'isolated-org-row-fixture.mjs',contents:`
  import {DurableObject} from 'cloudflare:workers';
  import {openDurableStore} from './store.mjs';
  import {createPlatform} from '../backend/platform.mjs';
  import {createAuth} from '../backend/auth.mjs';
  export class OrganizationFixture extends DurableObject {
   constructor(ctx,env){super(ctx,env);this.store=openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>Date.parse('2026-10-07T06:00:00Z')});this.read=this.store.read;this.api=createPlatform(this.store);this.owner={id:'isolated-owner',email:'owner@example.com'},this.client={id:'isolated-client',email:'client@example.com'};
    if(!this.store.readCollections(['organizations']).organizations.length){const d=this.read();d.clients.push({...this.owner,name:'Owner fixture',version:1},{...this.client,name:'Client fixture',version:1});d.accessChanges=[];d.dataRequests=[];this.store.write(d);for(const user of [this.owner,this.client])this.store.db.prepare('INSERT INTO accounts(id,site_id,email,name,created_at) VALUES(?,?,?,?,?)').run(user.id,this.store.siteId,user.email,'Isolated fixture',this.store.clock());for(const name of ['Fixture A','Fixture B']){const org=this.api.createOrganization(this.owner,{name,city:'Vilnius',kind:'solo',bio:'Isolated Worker organization authority.'}),scope={role:'professional',organizationId:org.id},w=this.api.workspace(this.owner,scope);this.api.createService(this.owner,{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Worker fixture manicure',durationMin:60,priceMinor:2500});this.api.moderate({...this.owner,operator:true},{id:this.api.submitRevision(this.owner,{scope,name,bio:org.bio}).id,state:'approved'});}}
   }
   async fetch(request){const route=new URL(request.url).pathname,orgs=this.store.readCollections(['organizations']).organizations,a=orgs.find(o=>o.name==='Fixture A'),b=orgs.find(o=>o.name==='Fixture B'),services=this.store.readCollections(['services']).services,slot=org=>this.api.availability({providerServiceId:services.find(s=>s.organizationId===org.id).id,dayOffset:1,from:900,to:1200,addons:[]}).slots[0];try{
    if(route==='/load'){const otherHold=this.api.hold(this.client,slot(b));this.api.confirm(this.client,{holdId:otherHold.id,idempotencyKey:'other-worker',name:'Client fixture'});const d=this.read();d.clientLinks=[];for(let n=0;n<5000;n++)d.bookings.push({id:'isolated-history-'+n,organizationId:b.id,status:'completed',clientId:'isolated-unrelated-'+n,startAt:'2026-01-01T07:00:00Z',endAt:'2026-01-01T08:00:00Z',serviceSnapshot:{label:'Retained isolated history',description:'x'.repeat(500),priceMinor:3000}});this.store.write(d);}
    this.store.read=()=>{throw Error('Global history read forbidden');};
    this.store.write=()=>{throw Error('Global history write forbidden');};
    if(route==='/creation'){
     const prepare=this.store.db.prepare,guarded=query=>{if(/FROM state_rows\\b/i.test(query)&&!/\\bcollection\\s*=/i.test(query))throw Error('Global creation history scan forbidden');return prepare(query);};this.store.db.prepare=guarded;
     try{
      const org=this.api.createOrganization(this.owner,{name:'Indexed Worker organization',city:'Švenčionėliai',kind:'salon',bio:'Isolated Workers onboarding.'});
      try{this.api.createClient(this.client,{organizationId:org.id,email:'worker-denied-manual@example.com',name:'Denied'});throw Error('Missing manual client permission');}catch(e){if(e.code!=='FORBIDDEN')throw e;}
      if(prepare('SELECT id FROM accounts WHERE email=?').get('worker-denied-manual@example.com'))throw Error('Unauthorized manual account');
      const identity=this.store.recordById('clients',this.client.id);this.api.createClient(this.owner,{organizationId:org.id,email:this.client.email,name:'Local Worker client name'});if(JSON.stringify(this.store.recordById('clients',this.client.id))!==JSON.stringify(identity))throw Error('Existing identity changed');
      this.api.createClient(this.owner,{organizationId:org.id,email:'worker-manual-new@example.com',name:'New Worker manual fixture'});
      const version=prepare('SELECT version FROM state_row_metadata WHERE site_id=?').get(this.store.siteId).version;this.store.db.prepare=query=>{const statement=guarded(query);if(!query.startsWith('INSERT INTO state_rows('))return statement;return {...statement,run:(...args)=>{const result=statement.run(...args);if(args[1]==='clientLinks'&&JSON.parse(args.at(-1)).name==='Failed Worker manual fixture')throw Error('Isolated Worker manual creation failure');return result;}};};
      try{this.api.createClient(this.owner,{organizationId:org.id,email:'worker-manual-failed@example.com',name:'Failed Worker manual fixture'});throw Error('Missing manual creation rollback');}catch(e){if(e.message!=='Isolated Worker manual creation failure')throw e;}
      if(prepare('SELECT id FROM accounts WHERE email=?').get('worker-manual-failed@example.com')||prepare('SELECT version FROM state_row_metadata WHERE site_id=?').get(this.store.siteId).version!==version)throw Error('Incomplete manual rollback');
      this.store.db.prepare=guarded;this.api.createClient(this.owner,{organizationId:org.id,email:'worker-manual-failed@example.com',name:'Failed Worker manual fixture'});
      for(let n=0;n<2;n++)this.api.createOrganization(this.owner,{name:'Worker limit '+n,city:'Vilnius',kind:'solo',bio:'Isolated account-wide limit.'});try{this.api.createOrganization(this.owner,{name:'Worker over limit',city:'Vilnius',kind:'solo',bio:'Isolated limit.'});throw Error('Missing organization limit');}catch(e){if(e.code!=='LIMIT')throw e;}
      const outbox=prepare("SELECT * FROM mail_outbox WHERE organization_id=? AND type='confirmation'").get(b.id);try{this.api.retryOutbox(this.owner,{id:outbox.id,scope:{role:'professional',organizationId:a.id}});throw Error('Missing outbox scope');}catch(e){if(e.code!=='FORBIDDEN')throw e;}
      this.api.retryOutbox(this.owner,{id:outbox.id,scope:{role:'professional',organizationId:b.id}});
     }finally{this.store.db.prepare=prepare;}
    }
    if(route==='/creation-status'){
     const org=this.store.readCollections(['organizations']).organizations.find(o=>o.name==='Indexed Worker organization'),identities=['worker-manual-new@example.com','worker-manual-failed@example.com'].map(email=>this.store.db.prepare('SELECT id FROM accounts WHERE site_id=? AND email=?').get(this.store.siteId,email)).filter(Boolean).map(account=>this.store.recordById('clients',account.id));
     return Response.json({org,identities,links:org?this.store.organizationRecords('clientLinks',org.id):[],memberships:this.store.clientRecords('memberships',this.owner.id).length,stats:this.store.rowStats(),actualBytes:Buffer.byteLength(JSON.stringify(this.read()))});
    }
    if(route==='/identity'){
     const auth=createAuth(this.store),prepare=this.store.db.prepare,guarded=query=>{if(/FROM state_rows\\b/i.test(query)&&!/\\bcollection\\s*=/i.test(query))throw Error('Global identity history scan forbidden');return prepare(query);},challenge=email=>{const session=auth.session(null),started=auth.start(session,email,'127.0.0.1'),row=prepare("SELECT payload FROM mail_outbox WHERE challenge_id=? AND type='login-code'").get(started.challengeId);return {session,id:started.challengeId,code:this.store.unseal(row.payload).code};},verify=c=>auth.verify(c.session,c.id,c.code,'127.0.0.1');
     this.store.db.prepare=guarded;try{
      verify(challenge('worker-new-identity@example.com'));prepare('INSERT INTO accounts(id,site_id,email,name,created_at) VALUES(?,?,?,?,?)').run('worker-imported-identity',this.store.siteId,'worker-imported-identity@example.com','Imported Worker fixture',this.store.clock());verify(challenge('worker-imported-identity@example.com'));
      const version=prepare('SELECT version FROM state_row_metadata WHERE site_id=?').get(this.store.siteId).version;verify(challenge('worker-imported-identity@example.com'));if(prepare('SELECT version FROM state_row_metadata WHERE site_id=?').get(this.store.siteId).version!==version)throw Error('Duplicate Worker identity');
      const failed=challenge('worker-failed-identity@example.com');this.store.db.prepare=query=>{const statement=guarded(query);if(!query.startsWith('INSERT INTO state_rows('))return statement;return {...statement,run:(...args)=>{const result=statement.run(...args);if(args[1]==='clients'&&JSON.parse(args.at(-1)).email==='worker-failed-identity@example.com')throw Error('Isolated Worker identity failure');return result;}};};
      try{verify(failed);throw Error('Missing identity rollback');}catch(e){if(e.message!=='Isolated Worker identity failure')throw e;}if(prepare('SELECT id FROM accounts WHERE email=?').get('worker-failed-identity@example.com')||prepare('SELECT consumed FROM email_challenges WHERE id=?').get(failed.id).consumed||auth.session(failed.session.token,{create:false}).account_id||prepare('SELECT version FROM state_row_metadata WHERE site_id=?').get(this.store.siteId).version!==version)throw Error('Incomplete identity rollback');
      this.store.db.prepare=guarded;verify(failed);
     }finally{this.store.db.prepare=prepare;}
    }
    if(route==='/provider'){const selected=this.api.selectProcedures(this.owner,{organizationId:a.id,procedureIds:['kirpimai-vyru-kirpimas'],version:0,idempotencyKey:'worker-own-selection'}),group=this.api.saveMenuGroup(this.owner,{organizationId:a.id,label:'Worker own group',rank:2}),source=services.find(s=>s.organizationId===a.id);let offer=this.api.saveOffer(this.owner,{id:selected[0].id,version:selected[0].version,label:'Worker own cut',menuGroupId:group.id,variants:[{id:'worker-own-cut',label:'Worker cut',priceMinor:3100,durationMin:60,staffOptions:[{practitionerId:source.practitionerId,resourceId:source.resourceId}]}]});offer=this.api.submitOffer(this.owner,{id:offer.id,version:offer.version});this.api.moderateOffer({...this.owner,operator:true},{id:offer.id,version:offer.version,state:'approved'});this.api.createResource(this.owner,{organizationId:a.id,label:'Worker second chair'});}
    if(route==='/access'){this.api.grantMembership(this.owner,{organizationId:a.id,email:this.client.email,role:'practitioner',practitionerId:services.find(s=>s.organizationId===a.id).practitionerId,version:0});const request=this.api.requestProcedure(this.owner,{organizationId:a.id,label:'Worker requested service',description:'Isolated mapped procedure.'});this.api.moderateProcedure({...this.owner,operator:true},{id:request.id,version:request.version,state:'resolved',targetId:'kirpimai-vyru-kirpimas',reason:'Mapped in isolated Workers.'});this.api.assessQualification({...this.owner,operator:true},{organizationId:a.id,locationId:a.locationId,taxonomyNodeId:'kirpimai-vyru-kirpimas',expiresAt:'2026-11-01T00:00:00Z',evidenceReference:'Isolated Worker reference'});}
    if(route==='/alarm'){const other=this.store.organizationRecords('bookings',b.id).find(x=>x.status==='confirmed');this.store.clock=()=>Date.parse(other.startAt)-86400000;this.api.runAutomation();this.api.runAutomation();}
    if(route==='/preferences'){this.api.preferences(this.client,{service:false,marketing:true,reminderLeadMin:0});this.api.favorite(this.client,{organizationId:a.id,saved:true});let request=this.api.requestErasure({...this.client,verifiedAt:this.store.clock()},{confirmEmail:this.client.email});this.api.withdrawErasure(this.client,{id:request.id,version:request.version});request=this.api.requestErasure({...this.client,verifiedAt:this.store.clock()},{confirmEmail:this.client.email});this.api.reviewErasure({...this.owner,operator:true},{id:request.id,version:request.version,state:'retention-review',reason:'Isolated review only',retentionBasis:'No execution policy activated'});}
    if(route==='/book'){const candidate=slot(a),hold=this.api.hold(this.client,candidate),input={holdId:hold.id,idempotencyKey:'worker-scoped',name:'Client fixture'},booking=this.api.confirm(this.client,input);if(this.api.confirm(this.client,input).id!==booking.id)throw Error('Replay mismatch');try{this.api.hold(this.client,candidate);throw Error('Missing conflict');}catch(e){if(e.code!=='SLOT_CONFLICT')throw e;}this.api.cancelBooking(this.client,{id:booking.id,version:1,reason:'Isolated scoped cancellation'});}
    const identities=['worker-new-identity@example.com','worker-imported-identity@example.com','worker-failed-identity@example.com'].map(email=>this.store.db.prepare('SELECT id FROM accounts WHERE site_id=? AND email=?').get(this.store.siteId,email)).filter(Boolean).map(account=>this.store.recordById('clients',account.id));
    const first=this.store.organizationRecords('bookings',a.id),other=this.store.organizationRecords('bookings',b.id).find(x=>x.status==='confirmed'),job=this.store.db.prepare('SELECT * FROM notification_jobs WHERE booking_id=?').get(other?.id),raw=JSON.stringify(this.read());return Response.json({identities,bookings:first,other,job,stats:this.store.rowStats(),actualBytes:Buffer.byteLength(raw),clientPreferences:this.store.clientRecords('preferences',this.client.id),clientFavorites:this.store.recordById('clients',this.client.id).favoriteIds||[],clientErasureCases:this.store.clientRecords('dataRequests',this.client.id).map(r=>({id:r.id,state:r.state,version:r.version})),clientOrganizations:this.api.session(this.client).organizations.map(o=>({id:o.id,role:o.membershipRole})),customerExportCount:this.api.exportCustomer({...this.client,verifiedAt:this.store.clock()}).bookings.length,rebookingReady:first.length?this.api.rebooking(this.client,{id:first[0].id}).state:null,otherReminderCount:this.store.db.prepare("SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=? AND type='reminder'").get(other?.id).n,workspaceCounts:{professional:this.api.workspace(this.owner,{role:'professional',organizationId:a.id}).bookings.length,customer:this.api.workspace(this.client,{role:'customer'}).bookings.length,operator:this.api.workspace({...this.owner,operator:true},{role:'operator'}).bookings.length},ownMenu:this.api.profile(a.id).services.filter(s=>s.id==='worker-own-cut').map(s=>({id:s.id,priceMinor:s.priceMinor,menuGroupLabel:s.menuGroupLabel})),outbox:first.length?this.store.db.prepare('SELECT COUNT(*) AS n FROM mail_outbox WHERE booking_id=?').get(first[0].id).n:0});
   }catch(e){return Response.json({code:e.code||e.message},{status:e.status||500});}}
  }
  export default {fetch(request,env){return env.ORGANIZATION_FIXTURE.get(env.ORGANIZATION_FIXTURE.idFromName('isolated-only')).fetch(request);}};
 `},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text'}});
 const dir=await mkdtemp(path.join(os.tmpdir(),'madbeauty-org-workers-')),start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{ORGANIZATION_FIXTURE:{className:'OrganizationFixture',useSQLite:true}},durableObjectsPersist:dir,bindings:{SESSION_SECRET:'isolated-org-worker-'.repeat(3)}});let mf=start();
 try{
  const get=async route=>{const r=await mf.dispatchFetch('https://org-fixture.test'+route);const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value;},before=await get('/load'),provider=await get('/provider'),access=await get('/access'),after=await get('/book');assert.equal(access.clientOrganizations.length,1);assert.equal(access.clientOrganizations[0].role,'practitioner');assert.equal(after.customerExportCount,2);assert.equal(after.rebookingReady,'ready');assert.deepEqual(provider.ownMenu,[{id:'worker-own-cut',priceMinor:3100,menuGroupLabel:'Worker own group'}]);assert.deepEqual(provider.other,before.other);assert.deepEqual(provider.job,before.job);assert.equal(after.bookings.length,1);assert.equal(after.bookings[0].status,'canceled');assert.deepEqual(after.other,before.other);assert.deepEqual(after.job,before.job);assert.equal(after.outbox,2);assert.deepEqual(after.workspaceCounts,{professional:1,customer:2,operator:0});assert.equal(after.stats.bytes,after.actualBytes);assert.equal(after.stats.legacyMirrored,false);
  const creation=await get('/creation');assert.deepEqual(creation.other,after.other);assert.deepEqual(creation.job,after.job);const created=await get('/creation-status');assert.equal(created.memberships,5);assert.equal(created.links.length,3);assert.equal(created.identities.length,2);assert.equal(created.org.approved,false);assert.equal(created.org.city,'Švenčionėliai');assert.equal(created.stats.bytes,created.actualBytes);
  const identity=await get('/identity');assert.equal(identity.identities.length,3);assert.equal(identity.identities[1].id,'worker-imported-identity');assert.equal(identity.identities[1].name,'Imported Worker fixture');assert.deepEqual(identity.other,after.other);assert.deepEqual(identity.job,after.job);assert.equal(identity.stats.bytes,identity.actualBytes);
  const alarm=await get('/alarm');assert.equal(alarm.otherReminderCount,1);assert.equal(alarm.job.state,'queued');assert.equal(alarm.customerExportCount,2);const preferences=await get('/preferences');assert.equal(preferences.job.state,'suppressed');assert.equal(preferences.clientPreferences[0].service,false);assert.equal(preferences.clientFavorites.length,1);assert.deepEqual(preferences.clientErasureCases.map(r=>r.state),['withdrawn','retention-review']);await mf.dispose();mf=start();const reopened=await get('/');assert.deepEqual(reopened.identities,identity.identities);assert.deepEqual(reopened.bookings,after.bookings);assert.deepEqual(reopened.ownMenu,provider.ownMenu);assert.deepEqual(reopened.job,preferences.job);assert.deepEqual(reopened.clientPreferences,preferences.clientPreferences);assert.deepEqual(reopened.clientErasureCases,preferences.clientErasureCases);assert.deepEqual(reopened.clientFavorites,preferences.clientFavorites);assert.equal(reopened.otherReminderCount,1);assert.deepEqual(reopened.clientOrganizations,access.clientOrganizations);assert.equal(reopened.stats.bytes,reopened.actualBytes);assert.equal(reopened.outbox,2);assert.deepEqual(reopened.workspaceCounts,after.workspaceCounts);
  const restoredCreation=await get('/creation-status');assert.deepEqual(restoredCreation.org,created.org);assert.deepEqual(restoredCreation.identities,created.identities);assert.deepEqual(restoredCreation.links,created.links);assert.equal(restoredCreation.memberships,5);assert.equal(restoredCreation.stats.bytes,restoredCreation.actualBytes);
 }finally{await mf.dispose();if(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'madbeauty-org-workers-'))await rm(dir,{recursive:true,force:true});}
});
