import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import {RETENTION_POLICY} from '../backend/retention-policy.mjs';
const core=path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting');
const {build}=await import(pathToFileURL(path.join(core,'node_modules/esbuild/lib/main.js'))),{Miniflare}=await import(pathToFileURL(path.join(core,'node_modules/miniflare/dist/src/index.js')));
const origin='https://retention-workers.test',version=RETENTION_POLICY.version;
// Only this compiled test fixture contains the controllable clock and private
// probes. Production classes expose none of these diagnostic methods.
const bundle=await build({entryPoints:[path.join(import.meta.dirname,'worker.mjs')],write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*'],loader:{'.sql':'text','.html':'text'},plugins:[{name:'native-retention-acceptance',setup(b){
 b.onLoad({filter:/cloudflare[\\/]platform-object\.mjs$/},async a=>({contents:(await readFile(a.path,'utf8')).replaceAll('Date.now()','this.store.clock()').replace('openDurableStore(ctx,env.SESSION_SECRET,storeOptions)','openDurableStore(ctx,env.SESSION_SECRET,{...storeOptions,clock:()=>Number(env.ISOLATED_CLOCK)})').replace(' async fetch(request){',` async privacyProbe(){return JSON.stringify({state:this.store.read(),accounts:this.store.db.prepare('SELECT id,email FROM accounts').all(),journal:this.directory().retention.journal(),backups:this.store.db.prepare('SELECT id,payload FROM retention_backups').all()});}
 async privacyLargeCheckpoint(){const d=this.store.read();for(let i=0;i<2400;i++)d.messages.push({id:'large-checkpoint-'+i,clientId:'chunk-client',organizationId:'isolated-org',text:'x'.repeat(1100),createdAt:new Date(this.store.clock()).toISOString()});this.store.write(d);const r=this.directory().retention,b=r.backup({force:true});return JSON.stringify({id:b.id,count:r.decodeBackup(b.id).state.messages.length,parts:this.store.db.prepare('SELECT COUNT(*) AS n FROM retention_backup_chunks WHERE id=?').get(b.id).n});}
 async privacyDecode(id){try{return JSON.stringify({snapshot:this.directory().retention.decodeBackup(id)});}catch(error){return JSON.stringify({error:error.message});}}
 async privacyRemoveChunk(id){this.store.db.prepare('DELETE FROM retention_backup_chunks WHERE id=? AND part=1').run(id);}
 async privacyCheckpoint(){const r=this.directory().retention,b=r.backup({force:true});return JSON.stringify(r.decodeBackup(b.id));}
 async privacyRestore(snapshot,journal,hash){return JSON.stringify(this.directory().retention.restoreEmpty(snapshot,journal,hash));}
 async privacyRecoveryRefusal(){try{await this.scheduleRecovery('00000001-00000001-00000001-00000000000000000000000000000000');return 'UNEXPECTED_RESTORE';}catch(error){return error.message;}}
 async privacyRun(){await this.directory().runRetention();return true;}
 async fetch(request){`),loader:'js'}));
 b.onLoad({filter:/cloudflare[\\/]organization-object\.mjs$/},async a=>({contents:(await readFile(a.path,'utf8')).replace('openDurableStore(ctx,env.SESSION_SECRET)','openDurableStore(ctx,env.SESSION_SECRET,{clock:()=>Number(env.ISOLATED_CLOCK)})').replace(' stage(packet){',` privacyProbe(){return JSON.stringify({state:this.store.read(),accounts:this.store.db.prepare('SELECT id,email FROM accounts').all()});}
 stage(packet){`),loader:'js'}));
}}]});
test('Native SQLite approved erasure routes to active target, survives both restarts, rejects old sessions, and isolated encrypted-backup restore replays latest tombstones without mail',async()=>{
 const persist=await mkdtemp(path.join(os.tmpdir(),'madbeauty-retention-native-')),mails=[],bindings={APP_ORIGIN:origin,RELEASE_MODE:'preview',SESSION_SECRET:'isolated-native-retention-key-at-least-thirty-two-characters',OPERATOR_EMAIL:'operator@example.com',RETENTION_POLICY_VERSION:version,ISOLATED_CLOCK:Date.parse('2026-10-12T06:00:00Z')};
 const start=storage=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'MadbeautyPlatform',useSQLite:true},ORGANIZATION_STAGING:{className:'MadbeautyOrganizationStaging',useSQLite:true}},durableObjectsPersist:storage,bindings,serviceBindings:{MAIL_TRANSPORT:async req=>{mails.push(await req.json());return new Response('Captured');},ASSETS:async()=>new Response('Not found',{status:404})}});
 let mf=start(persist),restoreMf;
 const browser=()=>{let cookie='',csrf='';return {async send(endpoint,body){const r=await mf.dispatchFetch(origin+'/api/madbeauty/'+endpoint,{method:body===undefined?'GET':'POST',headers:{cookie,...(body===undefined?{}:{origin,'content-type':'application/json','x-csrf-token':csrf})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const value=await r.json();if(value.csrf)csrf=value.csrf;return {status:r.status,value};},async login(email){await this.send('session');const c=await this.send('auth/start',{email});assert.equal(c.status,200,JSON.stringify(c));const code=mails.findLast(m=>m.to===email).text.match(/\b\d{6}\b/)[0],v=await this.send('auth/verify',{challengeId:c.value.challengeId,code});assert.equal(v.status,200,JSON.stringify(v));return v.value.user;},async rpc(method,input={}){return this.send('rpc',{method,input,siteId:'madbeauty'});}};};
 const rpc=async(b,m,i)=>{const r=await b.rpc(m,i);assert.equal(r.status,200,m+JSON.stringify(r));return r.value.result;};
 const source=async()=>{const ns=await mf.getDurableObjectNamespace('PLATFORM');return ns.get(ns.idFromName('madbeauty-pilot-v1'));};
 try{
  const owner=browser(),client=browser(),other=browser(),operator=browser(),oUser=await owner.login('privacy-native-owner@example.com'),cUser=await client.login('privacy-native-client@example.com');await other.login('privacy-native-other@example.com');const op=await operator.login('operator@example.com');
  const org=await rpc(owner,'createOrganization',{name:'Native privacy fixture',bio:'Isolated actual SQL retention acceptance.',kind:'salon',city:'Vilnius'}),scope={role:'professional',organizationId:org.id},w=await rpc(owner,'workspace',scope),s=await rpc(owner,'createService',{organizationId:org.id,practitionerId:w.practitioners[0].id,resourceId:w.resources[0].id,taxonomyServiceId:'manikiuras',label:'Native privacy service',durationMin:30,priceMinor:2200});await rpc(operator,'moderate',{id:(await rpc(owner,'submitRevision',{scope,name:org.name,bio:org.bio})).id,state:'approved'});
  const book=async(b,offset,key)=>{const c=(await rpc(b,'availability',{providerServiceId:s.id,dayOffset:offset,from:900,to:1200})).slots[0];return rpc(b,'confirm',{holdId:(await rpc(b,'hold',c)).id,name:key,idempotencyKey:key});};const first=await book(client,1,'PRIVATE native client'),foreign=await book(other,2,'Other unchanged customer');await rpc(client,'message',{bookingId:first.id,scope:{role:'customer'},text:'PRIVATE native note'});await rpc(owner,'saveClientCard',{organizationId:org.id,clientId:cUser.id,version:0,name:'PRIVATE local name',note:'PRIVATE card note'});
  const oldSource=await source(),frozen=await oldSource.freezeOrganization({operatorAccountId:op.id,organizationId:org.id,epoch:0,requestKey:'native-privacy-transfer'}),epoch=Number(frozen.epoch),handoffId=String(frozen.handoffId),targetName=String(frozen.targetName),control={operatorAccountId:op.id,organizationId:org.id,epoch,handoffId};
  const ns=await mf.getDurableObjectNamespace('ORGANIZATION_STAGING'),target=ns.get(ns.idFromName(targetName));let offset=0;for(;;){const page=await oldSource.organizationHandoffPage({...control,offset});await target.stage(page);offset=Number(page.nextOffset);if(page.done)break;}
  const prepared=await target.prepareAuthority(await oldSource.organizationHandoffContext(control));await target.activateAuthority(await oldSource.sealOrganizationHandoff({...control,targetReceipt:prepared}));
  assert.match(await oldSource.privacyRecoveryRefusal(),/current erasure journal/);const snapshot=JSON.parse(await oldSource.privacyCheckpoint()),preview=await rpc(client,'erasurePreview');assert.equal(preview.futureBookings[0].id,first.id);assert.equal((await owner.rpc('requestErasure',{confirmEmail:oUser.email,policyVersion:version})).status,409);
  const result=await rpc(client,'requestErasure',{confirmEmail:cUser.email,policyVersion:version});assert.equal(result.state,'completed');assert.equal((await client.rpc('exportCustomer')).value.error.code,'CSRF');const beforeMail=mails.length;
  await mf.dispose();mf=start(persist);const currentSource=await source(),currentNs=await mf.getDurableObjectNamespace('ORGANIZATION_STAGING'),currentTarget=currentNs.get(currentNs.idFromName(targetName));await currentSource.privacyRun();
  const central=JSON.parse(await currentSource.privacyProbe()),local=JSON.parse(await currentTarget.privacyProbe());for(const p of [central,local]){assert.doesNotMatch(JSON.stringify(p.state),/PRIVATE|privacy-native-client@example.com/);assert.equal(p.accounts.some(a=>a.id===cUser.id),false);assert.equal(p.state.bookings.find(b=>b.id===foreign.id).clientId,foreign.clientId);assert.equal(p.state.bookings.find(b=>b.id===first.id).erased,true);}
  assert.equal((await client.send('session')).value.user,null);assert.equal((await rpc(client,'erasureStatus',{receiptToken:preview.receiptToken})).id,result.id);assert.equal((await rpc(owner,'workspace',scope)).bookings.find(b=>b.id===first.id).erased,true);assert.equal(mails.length,beforeMail);
  restoreMf=start(await mkdtemp(path.join(os.tmpdir(),'madbeauty-privacy-restore-')));const recoveryNs=await restoreMf.getDurableObjectNamespace('PLATFORM'),recovery=recoveryNs.get(recoveryNs.idFromName('isolated-empty-recovery')),journal=central.journal,hash=createHash('sha256').update(JSON.stringify(journal)).digest('hex');
  const restored=JSON.parse(await recovery.privacyRestore(snapshot,journal,hash));assert.equal(restored.tombstonesReplayed,1);assert.equal(restored.mailImported,0);assert.doesNotMatch(JSON.stringify(JSON.parse(await recovery.privacyProbe()).state),/PRIVATE|privacy-native-client@example.com/);assert.equal(mails.length,beforeMail);
 }finally{await mf.dispose();await restoreMf?.dispose();}
});

test('Native SQLite encrypted customer checkpoints exceed the2MiB row limit safely, persist all chunks across restart and refuse a missing chunk',async()=>{
 const persist=await mkdtemp(path.join(os.tmpdir(),'madbeauty-retention-chunks-')),start=()=>new Miniflare({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],durableObjects:{PLATFORM:{className:'MadbeautyPlatform',useSQLite:true}},durableObjectsPersist:persist,bindings:{APP_ORIGIN:origin,RELEASE_MODE:'preview',SESSION_SECRET:'isolated-native-retention-key-at-least-thirty-two-characters',RETENTION_POLICY_VERSION:version,ISOLATED_CLOCK:Date.parse('2026-10-12T06:00:00Z')},serviceBindings:{ASSETS:async()=>new Response('Not found',{status:404})}});let mf=start();const get=async()=>{const ns=await mf.getDurableObjectNamespace('PLATFORM');return ns.get(ns.idFromName('isolated-large-checkpoint'));};try{const result=JSON.parse(await (await get()).privacyLargeCheckpoint());assert.equal(result.count,2400);assert.ok(result.parts>4);await mf.dispose();mf=start();const current=await get();assert.equal(JSON.parse(await current.privacyDecode(result.id)).snapshot.state.messages.length,2400);await current.privacyRemoveChunk(result.id);assert.equal(JSON.parse(await current.privacyDecode(result.id)).error,'Backup chunks incomplete');}finally{await mf.dispose();}
});
