import assert from 'node:assert/strict';import fs from 'node:fs/promises';import{createHash}from'node:crypto';
import {trustPages} from '../prototype/public/product-trust.mjs';
import path from 'node:path';
const pkg=JSON.parse(await fs.readFile(new URL('output/content-package.json',import.meta.url),'utf8'));
const receipt=JSON.parse(await fs.readFile(new URL('output/content-release-receipt.json',import.meta.url),'utf8'));
const visible=pkg.pages.filter(p=>p.approval.status==='approved'&&p.approval.revisionHash===p.revisionHash&&Date.parse(p.publishAt)<=Date.now());
const sourceAssets=pkg.schemaVersion===1?new URL('../content/initial-release/assets/',import.meta.url):process.env.MADBEAUTY_REVIEWED_RELEASE_ASSETS;
const origin=process.argv[2]||'https://madbeauty-platform-preview.phonebridger-app.workers.dev',production=origin==='https://madbeauty.lt';
assert.ok(production||origin==='https://madbeauty-platform-preview.phonebridger-app.workers.dev');
const get=async path=>{const r=await fetch(origin+path,{redirect:'manual'});assert.equal(r.headers.get('x-madbeauty-content-sha256'),receipt.packageSha256,path);return {status:r.status,headers:r.headers,bytes:Buffer.from(await r.arrayBuffer())};};
const paths=[...new Set([...visible.map(p=>'/'+p.slug),...Object.keys(trustPages)])],proof={origin,at:new Date().toISOString(),production,packageSha256:receipt.packageSha256,pages:[],assets:[],boundaries:[],discovery:[]};
for(const path of paths){const functional=path==='/paslaugos'||path.startsWith('/paslaugos/'),r=await get(path),html=r.bytes.toString();assert.equal(r.status,200,path);assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,path);assert.ok(html.includes(`rel="canonical" href="https://madbeauty.lt${path}"`));assert.equal(html.includes('application/ld+json'),!functional);if(!production||functional)assert.match(r.headers.get('x-robots-tag'),/noindex/);else assert.ok(!r.headers.get('x-robots-tag'));
 for(const m of html.matchAll(/<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g))JSON.parse(m[1]);proof.pages.push({path,status:200});}
const assets=JSON.parse(await fs.readFile(new URL('output/asset-paths.json',import.meta.url),'utf8'));
for(const assetPath of assets){let r=await get(assetPath);if(r.status===307){const location=r.headers.get('location');assert.equal(new URL(location,origin).origin,origin);assert.equal(decodeURIComponent(new URL(location,origin).pathname),assetPath);r=await get(location);}const media=assetPath.startsWith('/content-assets/'),eligible=!media||visible.some(p=>p.media.some(m=>m.src===assetPath));assert.equal(r.status,eligible?200:404,assetPath);if(media&&eligible){assert.ok(sourceAssets,'MADBEAUTY_REVIEWED_RELEASE_ASSETS required for V2 byte proof');const file=assetPath.split('/').at(-1),source=await fs.readFile(typeof sourceAssets==='string'?path.join(sourceAssets,file):new URL(file,sourceAssets));assert.equal(createHash('sha256').update(r.bytes).digest('hex'),createHash('sha256').update(source).digest('hex'));}proof.assets.push({path:assetPath,status:r.status});}
for(const path of ['/backend/local-admin.mjs','/.dev.vars','/runtime/platform.sqlite','/meistrai/demo-org-0','/originals/asset_abc','/images/profile-0-360.webp','/not-a-page']){const r=await get(path);assert.equal(r.status,404,path);assert.ok(!r.bytes.toString().includes('rel="canonical"'));proof.boundaries.push({path,status:404});}
for(const path of ['/sitemap.xml','/llms.txt','/llms-full.txt']){const r=await get(path);assert.equal(r.status,production?200:404,path);if(production){const text=r.bytes.toString();for(const p of paths.filter(p=>!p.startsWith('/paslaugos')))assert.ok(text.includes('https://madbeauty.lt'+p));if(path==='/sitemap.xml')assert.ok(!text.includes('<loc>https://madbeauty.lt/paslaugos'));if(path==='/llms.txt')assert.ok(!text.split('\n').some(line=>/^- \[.*\]\(https:\/\/madbeauty.lt\/paslaugos/.test(line)));for(const p of pkg.pages.filter(p=>!visible.includes(p)))assert.ok(!text.includes('https://madbeauty.lt/'+p.slug));}proof.discovery.push({path,status:r.status});}
const boot=JSON.parse((await get('/boot.json')).bytes.toString());assert.equal(boot.enabled,false);assert.equal(boot.privatePrototype,false);assert.equal(boot.contact.email,'info@pinet.lt');
const requestBody=JSON.stringify({siteId:'madbeauty',method:'catalog',input:{}}),unsigned=await fetch(origin+'/api/madbeauty/rpc',{method:'POST',headers:{origin,'content-type':'application/json'},body:requestBody});assert.equal(unsigned.status,403);
const session=await fetch(origin+'/api/madbeauty/session'),cookie=session.headers.get('set-cookie').split(';')[0],csrf=(await session.json()).csrf;
const catalog=await fetch(origin+'/api/madbeauty/rpc',{method:'POST',headers:{origin,cookie,'content-type':'application/json','x-csrf-token':csrf},body:requestBody});assert.equal(catalog.status,200);assert.ok(Array.isArray((await catalog.json()).result));proof.csrf=true;proof.catalog=true;
if(production){for(const url of ['http://madbeauty.lt/pagalba?test=1','https://www.madbeauty.lt/pagalba?test=1']){const r=await fetch(url,{redirect:'manual'});assert.ok([301,308].includes(r.status));assert.equal(r.headers.get('location'),'https://madbeauty.lt/pagalba?test=1');}}
await fs.mkdir(new URL('output/',import.meta.url),{recursive:true});await fs.writeFile(new URL(`output/${production?'canonical':'preview'}-verification.json`,import.meta.url),JSON.stringify(proof,null,2));console.log(JSON.stringify({origin,pages:proof.pages.length,assets:proof.assets.length,boundaries:proof.boundaries.length,discovery:proof.discovery,pass:true}));
