"""Local runtime role; migration owner and application role stay distinct."""
import argparse
import asyncio
import os

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from pinet_core.config import settings
from pinet_core.models import Business, new_id


async def main():
    parser = argparse.ArgumentParser(description="Prepare the restricted database role and runtime grants")
    parser.add_argument("--role-only", action="store_true", help="Create the role before the initial migrations")
    args = parser.parse_args()
    cfg = settings()
    engine = create_async_engine(cfg.admin_database_url)
    password = os.environ.get("PINET_DB_RUNTIME_PASSWORD")
    if not password:
        from dotenv import dotenv_values
        password = dotenv_values(".env").get("PINET_DB_RUNTIME_PASSWORD")
    if not password or not all(c in "0123456789abcdef" for c in password):
        raise RuntimeError("local runtime password must be generated by setup_local.py")
    async with engine.begin() as tx:
        exists = await tx.scalar(text("SELECT 1 FROM pg_roles WHERE rolname='pinet_runtime'"))
        if not exists:
            await tx.execute(text(f"CREATE ROLE pinet_runtime LOGIN PASSWORD '{password}' "
                                  "NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE"))
        if args.role_only:
            print("Restricted runtime role prepared; run migrations before applying grants.")
            return
        await tx.execute(text("GRANT USAGE ON SCHEMA public TO pinet_runtime"))
        await tx.execute(text("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pinet_runtime"))
        await tx.execute(text("REVOKE ALL ON alembic_version FROM pinet_runtime"))
        await tx.execute(text("REVOKE INSERT, UPDATE, DELETE ON businesses FROM pinet_runtime"))
        for site, host in [("traktoriupadangos", "traktoriupadangos.lt"),
                           ("greitossvetaines", "greitossvetaines.lt")]:
            if not await tx.scalar(text("SELECT id FROM businesses WHERE site_id=:s"), {"s": site}):
                await tx.execute(Business.__table__.insert().values(id=new_id(), site_id=site, canonical_host=host))
    await engine.dispose()
    print("Runtime role and stable site mappings ready; no customer data seeded.")


asyncio.run(main())
