import {ready} from './qa-ready.mjs';
import {chromium} from 'file:///C:/Users/lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const pkg=JSON.parse(await readFile(new URL('./export-handyman/auksarankiams/content-package.json',import.meta.url),'utf8')),out=path.join(import.meta.dirname,'qa');await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];
for(const width of [1440,390,320])for(const item of pkg.pages){const p=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push({slug:item.slug,width,error:e.message}));const r=await p.goto('http://127.0.0.1:8890/'+item.slug);assert.equal(r.status(),200);await ready(p);const state=await p.evaluate(()=>({title:document.title,h1:[...document.querySelectorAll('h1')].map(h=>h.textContent),overflow:document.documentElement.scrollWidth>innerWidth,viewport:innerWidth,body:document.body.innerText,images:[...document.images].map(i=>({alt:i.alt,currentSrc:i.currentSrc,naturalWidth:i.naturalWidth,renderedWidth:i.getBoundingClientRect().width,loading:i.loading})),font:getComputedStyle(document.querySelector('h1')).fontFamily,cookies:document.cookie}));assert(!state.overflow,item.slug+' '+width+' overflow');assert.equal(state.h1.length,1);for(const b of item.body){if(b.type==='paragraph')assert(state.body.includes(b.text),'Missing paragraph '+item.slug+' '+b.text.slice(0,70));if(b.type==='list')for(const text of b.items)assert(state.body.includes(text),'Missing list '+item.slug);}
if(width!==320)await p.screenshot({path:path.join(out,(item.slug||'home')+'-'+width+'.png'),fullPage:true});if(width===320&&['','kontaktai','darbu-ivertinimas'].includes(item.slug))await p.screenshot({path:path.join(out,(item.slug||'home')+'-320.png'),fullPage:true});checks.push({slug:item.slug,width,status:r.status(),...state,body:undefined});await p.close();}
for(const slug of ['','kontaktai','darbu-ivertinimas']){const p=await browser.newPage({viewport:{width:768,height:1000}});await p.goto('http://127.0.0.1:8890/'+slug);await p.evaluate(()=>document.fonts.ready);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,(slug||'home')+'-768.png'),fullPage:true});await p.close();}
const p=await browser.newPage({viewport:{width:390,height:1000}});await p.goto('http://127.0.0.1:8890/');await p.keyboard.press('Tab');assert.equal(await p.locator(':focus').innerText(),'Pereiti prie turinio');await p.keyboard.press('Enter');assert.match(p.url(),/#turinys$/);const menu=p.locator('header summary');await menu.focus();await p.keyboard.press('Enter');assert.equal(await p.locator('header details').getAttribute('open'),'');await p.screenshot({path:path.join(out,'menu-390.png')});await p.keyboard.press('Enter');assert.equal(await p.locator('header details').getAttribute('open'),null);
await p.goto('http://127.0.0.1:8890/darbu-ivertinimas');const toc=p.locator('aside summary');await toc.focus();await p.keyboard.press('Enter');assert.equal(await p.locator('aside details').getAttribute('open'),null);await p.keyboard.press('Enter');await p.locator('aside a').last().click();assert.match(p.url(),/#skyrius-/);await p.screenshot({path:path.join(out,'guide-end-390.png')});
await p.goto('http://127.0.0.1:8890/kontaktai#forma');await p.locator('button[type=submit]').click();assert.equal(await p.locator('form').evaluate(f=>f.checkValidity()),false);assert.equal(await p.locator(':focus').getAttribute('name'),'name');await p.screenshot({path:path.join(out,'form-empty-390.png')});await p.locator('#name').fill('AUDIT');await p.locator('#email').fill('bad');await p.locator('#message').fill('AUDIT synthetic request only; Vilnius, two shelves, flexible month.');await p.locator('[name=consent]').check();assert(await p.locator('#email').evaluate(i=>i.validity.typeMismatch));await p.close();assert.equal(errors.length,0);
await browser.close();await writeFile(path.join(out,'BROWSER-VERIFICATION.json'),JSON.stringify({at:new Date().toISOString(),realDevice:false,mechanism:'Playwright Chrome viewport; enlargement tested separately',checks,errors,keyboard:{skip:true,nativeMenu:true,nativeContents:true,fragment:true},form:{emptyNative:true,badEmailNative:true,submitTest:'separate HTTP/D1 evidence'},reducedMotion:true},null,2));console.log('39 pages/widths, three tablet pages, images, copy, keyboard, details and native validation passed');
