import {ready} from './qa-ready.mjs';
import {chromium} from 'file:///C:/Users/lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {writeFile,readFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const dir=path.join(import.meta.dirname,'qa'),pkg=await readFile(new URL('./export-handyman/auksarankiams/content-package.json',import.meta.url));
const c=await chromium.launchPersistentContext(path.join(dir,'owned-zoom-profile'),{channel:'chrome',headless:true,viewport:null,args:['--window-size=1440,1000','--lang=en-US']});
const settings=c.pages()[0]||await c.newPage(),p=await c.newPage();let original,restored=false;const checks=[];
const capture=async(page,name,full=true)=>{const d=await c.newCDPSession(page),m=await d.send('Page.getLayoutMetrics'),r=await d.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:full,clip:{x:0,y:0,width:m.layoutViewport.clientWidth,height:full?m.contentSize.height:m.layoutViewport.clientHeight,scale:1}});await writeFile(path.join(dir,name),Buffer.from(r.data,'base64'));await d.detach();};
const metrics=()=>p.evaluate(()=>({width:innerWidth,dpr:devicePixelRatio,outerWidth,scrollWidth:document.documentElement.scrollWidth,h1Font:getComputedStyle(document.querySelector('h1')).fontSize,bodyFont:getComputedStyle(document.body).fontSize}));
try{
 await settings.goto('chrome://settings/appearance');const control=settings.locator('#zoomLevel');await control.waitFor();const interruptedAttemptValue=await control.inputValue();if(interruptedAttemptValue!=='1')await control.selectOption('1');original=await control.inputValue();assert.equal(original,'1');
 await p.goto('http://127.0.0.1:8890/');await p.evaluate(()=>document.fonts.ready);const baseline=await metrics();
 await control.selectOption('2');assert.equal(await control.inputValue(),'2');assert.equal((await control.locator('option:checked').innerText()).trim(),'200%');await capture(settings,'chrome-zoom-200.png',false);
 for(const slug of ['','gidai','baldu-surinkimo-uzklausa','smulkiu-darbu-sarasas','darbu-ivertinimas','kontaktai']){
  await p.goto('http://127.0.0.1:8890/'+slug);await ready(p);const m=await metrics();assert.equal(m.dpr,baseline.dpr*2);assert(Math.abs(m.width-baseline.width/2)<2);assert(m.scrollWidth<=m.width);await capture(p,(slug||'home')+'-zoom200.png');checks.push({slug,...m});
 }
 await p.goto('http://127.0.0.1:8890/');await p.locator('header summary').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('header details').getAttribute('open'),'');await p.keyboard.press('Enter');assert.equal(await p.locator('header details').getAttribute('open'),null);
 await p.goto('http://127.0.0.1:8890/darbu-ivertinimas');await p.locator('aside summary').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('aside details').getAttribute('open'),null);await p.keyboard.press('Enter');await p.locator('aside a').last().click();assert.match(p.url(),/#skyrius-/);await capture(p,'sources-footer-zoom200.png');await p.locator('a[href="/kontaktai#forma"]').first().click();assert.match(p.url(),/kontaktai#forma$/);await p.locator('button[type=submit]').click();assert.equal(await p.locator(':focus').getAttribute('name'),'name');await capture(p,'form-empty-zoom200.png');
 await control.selectOption(original);assert.equal(await control.inputValue(),original);await p.goto('http://127.0.0.1:8890/');await p.evaluate(()=>document.fonts.ready);const final=await metrics();assert.equal(final.dpr,baseline.dpr);assert.equal(final.width,baseline.width);restored=true;await capture(settings,'chrome-zoom-restored100.png',false);
 await writeFile(path.join(dir,'ACCESSIBILITY-VERIFICATION.json'),JSON.stringify({at:new Date().toISOString(),packageSha256:createHash('sha256').update(pkg).digest('hex'),capture:'Chrome CDP Page.captureScreenshot with DIP layoutViewport/contentSize clipping; Playwright CSS clipping at native page zoom was corrected, no page/CSS scaling applied',mechanism:'Actual Chrome native chrome://settings/appearance #zoomLevel select; agent-owned persistent profile; viewport null, no CSS zoom/DPR emulation',browser:await c.browser().version(),headless:true,physicalDevice:false,originalZoom:'100%',testedZoom:'200%',restoredZoom:'100%',restored,baseline,final,checks,actions:{nativeMenu:true,contents:true,fragment:true,inquiryLink:true,emptyNativeForm:true},limitations:'Scoped browser reflow/enlargement evidence; no physical-device or complete WCAG certification.'},null,2));console.log('Actual Chrome 200% zoom, six page types, controls, reflow and 100% restoration passed');
}finally{if(original&&!restored){try{await settings.locator('#zoomLevel').selectOption(original);}catch{}}await c.close();}
