const p=text=>({type:'paragraph',text}),h=text=>({type:'heading',level:2,text}),list=(...items)=>({type:'list',items});
export const reviewedOn='2026-10-06';
export const site={name:'PhoneBridger',canonicalHost:'phonebridger.com',locale:'en',timezone:'Europe/Kiev',offer:'Use your Windows mouse and keyboard in your own Android apps, on the phone beside your PC.',facts:'Owner-selected Windows/Android product and English identity. Native input is frozen. The current beta uses automatic USB preference and Wi-Fi fallback, saved pairing and up to three Android positions. One physical USB phone at a time. File dragging is planned, browser demo data is illustrative, paid orders are closed. Contact hello@phonebridger.com is owner-approved; operator default MB Pinet comes from core network configuration. Domain/deployment/production privacy and actual email receipt remain unverified. This package is editorially reviewed shadow preparation, not live publication.',contact:{email:'hello@phonebridger.com'},brand:{accent:'#ff2d9a'}};
export const guides=[
{slug:'guides/getting-started',type:'guide',image:'getting-started',category:'Start here',title:'Set up PhoneBridger on Windows and Android',description:'Install both beta apps, pair your own PC, approve it on Android and check your first screen-edge transition.',intent:'How do I complete my first PhoneBridger setup without confusing installation, permission and pairing?',lede:'Install the Windows app and Android companion, enable mouse control on the phone, then scan the PC’s pairing code and approve your computer. Use the same reachable Wi-Fi network for this first pairing.',body:[
p('PhoneBridger controls apps on your physical Android screen. It does not turn a browser demo into a connection to your phone. Keep your phone beside the PC so you can see both screens while you set up.'),
h('Before you start'),list('Have your own Windows PC and an Android phone available. The current download is a 64-bit Windows ZIP; the Android companion requires Android 8 or later.','Keep both devices on the same reachable Wi-Fi network for the first pairing. A guest network can prevent devices from reaching each other.','Use the beta files from the Downloads page. The Windows beta is unsigned and Android is distributed as an APK. If you cannot establish the source of a file or understand an installation warning, stop and ask for help.'),
h('1. Install both apps'),p('Extract the entire Windows ZIP into one folder. Keep PhoneBridger.exe next to its _internal folder; running only a copied EXE can leave its dependencies behind. Close an older running PC instance before opening this version.'),p('Install the Android companion on your phone. Updating the existing app with the current compatible package retains the saved pairing. Read the system installation prompts rather than accepting an unrelated app or a file sent by a stranger.'),
h('2. Enable mouse control on Android'),p('Open PhoneBridger on the phone and use its mouse-control setup. Review the explanation before opening Android’s accessibility settings, then enable the PhoneBridger service if you choose to grant that access. Android menu labels can differ by manufacturer.'),p('This permission and pairing are separate steps. An installed app is not automatically allowed to control other apps, and an enabled accessibility service does not automatically trust a PC. Read Android permissions explained if the setting is unavailable.'),
h('3. Scan and approve your PC'),list('Open the pairing screen in the Windows app.','Open the pairing scanner in PhoneBridger on Android and scan the code displayed by your own PC. Use the app’s scanner, not an unrelated QR reader.','Check that this is the computer you intend to trust, then approve it on the phone.','Wait for the connected status before trying to enter the phone. The illustration on this website is not a working pairing code.'),
h('4. Match the phone’s position'),p('Put the phone left, right or above your PC screen. Choose the corresponding position and transition zone in the Windows app. The selected zone is the part of the screen edge you cross to enter the phone; it should agree with the desk arrangement.'),p('Start with one phone. Open a harmless screen on it, move through your chosen PC screen edge and check that you can click and scroll. Use Ctrl + Alt + S to return to Windows. Ctrl + Alt + Q exits the PC app. Do not use this first check to alter private or consequential information.'),
h('If the first connection does not complete'),list('Check that both apps are open, the phone is unlocked and the PC’s pairing code is current.','Check that the devices can reach one another on the network. Being connected to similarly named networks is not proof of reachability.','Confirm the PC approval on the phone and mouse-control permission separately.','If you are upgrading, close the older PC app before starting the new one.','Record the exact visible status and your app/OS versions for support; leave passwords, pairing codes and private app messages out of an email.'),
h('What happens next time?'),p('Saved pairing is reused when the phone is reachable. A normal disconnect preserves that trust; forgetting the phone or computer revokes it. If you change device trust, approve your own PC again rather than trying to bypass the warning.'),p('After the initial pairing, you can keep using Wi-Fi or prepare USB once. The current beta prefers an authorized physical USB phone automatically and falls back to Wi-Fi when the cable is removed. Native file dragging is planned and is not part of this setup.'),
],related:['guides/android-permissions','guides/phone-position','guides/usb-wifi'],sources:[]},
{slug:'guides/usb-wifi',type:'guide',image:'usb-wifi',category:'Connections',title:'USB or Wi-Fi? Set up the connection that fits your desk',description:'Understand automatic USB priority, Wi-Fi fallback, data-cable requirements and the current one-USB-phone limit.',intent:'When should I use USB or Wi-Fi in PhoneBridger, and what must I prepare?',lede:'Pair over the same reachable Wi-Fi network first. After one-time USB debugging authorization, connecting a data cable makes the beta prefer USB automatically; unplugging it restores Wi-Fi when the saved phone is reachable.',body:[
h('Choose for your desk, not a different feature tier'),p('Wi-Fi keeps the desk free of a cable. USB is useful when your phone already sits beside a wired PC. PhoneBridger uses the same mouse, keyboard, supported audio and link features on either transport. Neither choice adds native file dragging to the current beta.'),p('There is no universal latency or reliability promise here. Network conditions, cable quality and the phone matter. Start with the arrangement you can maintain comfortably, then confirm the active connection in both apps.'),
h('Start with Wi-Fi pairing'),p('Follow Set up PhoneBridger on Windows and Android. Keep both devices on the same reachable Wi-Fi network, scan the PC pairing code in the Android companion and approve your own PC. PhoneBridger’s ordinary Wi-Fi connection does not require Android wireless debugging.'),p('A guest or isolated network may let both devices access the internet while preventing them from communicating with each other. If pairing waits, check the network policy or try your own permitted network; do not disable a managed network’s protections.'),
h('Prepare USB once'),list('Use a data-capable cable that fits your phone and PC. A charging-only cable cannot provide this connection.','On your Android phone, enable Developer options using the manufacturer’s applicable instructions, then enable USB debugging. Android’s official instructions explain where these settings live; menu locations vary.','Connect the phone to your own PC and review the debugging authorization prompt on the phone. Authorize only a computer you trust.','Keep PhoneBridger running and look for USB as the active connection. No separate USB launcher or PC app restart is required by the current beta.'),
p('USB debugging grants development access to the authorized computer. It is different from approving the computer inside PhoneBridger. If your device or workplace policy does not permit debugging, use Wi-Fi instead. Turn off debugging or revoke debugging authorizations when you no longer want that access.'),
h('What happens when you unplug?'),p('Control returns to Windows while the transport changes. If the saved phone is reachable over Wi-Fi, PhoneBridger reconnects with the saved pairing. Cross the configured screen edge again to enter the phone; the switch itself does not silently repeat your previous action.'),p('If Wi-Fi is unavailable, the app waits for a reachable saved phone. A disconnection does not erase the pairing. Forgetting a phone or computer is the deliberate trust-revocation action.'),
h('Using more than one phone'),p('The beta supports up to three configured phone positions, but USB discovery supports one physical USB debugging phone at a time. Keep one such phone connected by cable; other paired phones can use Wi-Fi. Multiple USB debugging devices can make selection ambiguous, so do not assume that three cables give three USB sessions.'),
h('If USB does not take over'),list('Check that the cable carries data, not only power.','Unlock the phone and check whether debugging authorization is waiting for your decision.','Keep only the intended physical USB debugging phone attached.','Check the active USB/Wi-Fi status in the apps rather than assuming a plugged-in cable is active.','If Windows does not detect the Android device, official Android documentation notes that an applicable manufacturer USB driver may be needed. Do not install an unknown driver from a search advertisement.'),
h('A simple arrangement to try'),p('For example, connect one desk phone by USB and keep a second paired phone on Wi-Fi. This illustrates a supported arrangement; it is not a claim that a particular phone, dock or cable has been tested. If you ask for help, include the phone model, Windows/Android versions, visible connection status and whether the cable transfers data.'),
],related:['guides/getting-started','guides/android-permissions'],sources:[{url:'https://developer.android.com/studio/run/device',label:'Android Developers: connect a hardware device',reason:'USB debugging, computer authorization context and applicable Windows USB driver requirements; retrieved 2026-10-06.'},{url:'https://developer.android.com/studio/debug/dev-options',label:'Android Developers: Developer options',reason:'Official platform settings context; retrieved 2026-10-06. PhoneBridger Wi-Fi does not use Android wireless debugging.'}]},
{slug:'guides/android-permissions',type:'guide',image:'android-permissions',category:'Permissions',title:'Android permissions explained: mouse control, pairing and audio',description:'Know which permission enables which PhoneBridger feature, what restricted settings mean and when to stop rather than grant access.',intent:'Why does PhoneBridger request Android permissions, and which permissions do I need for my chosen feature?',lede:'Mouse control uses Android accessibility access. Pairing separately approves your PC. Phone audio asks for Android capture consent, and USB needs debugging authorization only if you choose a cable.',body:[
h('One feature, one reason for access'),p('A connection is not a blanket permission. Install the companion, read its explanation and choose access for the feature you intend to use. You can use the setup guide to distinguish a missing app permission from a PC that has not been approved.'),
h('Mouse and keyboard control'),p('PhoneBridger’s mouse-control setup opens Android’s accessibility service settings. Accessibility access can let an app read screen content and interact with other apps on your behalf. Grant it only after you understand that capability and trust the app source.'),p('Open the permission flow in PhoneBridger, review the explanation and choose the PhoneBridger service in Android settings if you wish to enable it. Return to the companion and check its status. A saved switch and a service that is still starting are not always the same state; give the app’s status a chance to update before repeatedly toggling settings.'),
h('When Android shows a restricted setting'),p('Some Android 13-and-later settings can be restricted for installed apps. Google’s guidance describes a route through Settings → Apps → the app → More → Allow restricted settings, with on-screen confirmation. Availability and wording vary by device.'),p('That is a sensitive choice, not a routine error to bypass. Google advises allowing it only when you trust the developer. If the option is absent, managed by your organization or unclear, stop and ask for help. Do not install another tool simply to defeat Android’s protection.'),
h('Camera access for pairing'),p('The in-app pairing scanner uses the camera to read the code on your own PC. Review the camera request in that context. The sample QR illustration on the website cannot pair a device. Approving the PC is a separate confirmation after scanning.'),p('If scanning is unsuccessful, check the current PC code, lighting and scanner framing before changing unrelated permissions. Do not share a pairing code in a public post or send it to an unsolicited helper.'),
h('Listening through your PC'),p('Phone audio requires Android 10 or later and Android’s capture consent. The source app must also permit playback capture; some apps or content do not. Silent audio does not by itself mean mouse control or pairing failed.'),p('Start audio sharing from the app and review the system prompt. Declining audio consent leaves that audio feature unavailable. Check the source app and PC volume before retrying; repeatedly granting unrelated permissions will not make protected audio capturable.'),
h('USB authorization'),p('USB debugging is needed only for the current physical USB transport. It approves development access for a computer, while PhoneBridger’s own approval establishes application trust. Use USB or Wi-Fi? for the cable preparation steps. Ordinary PhoneBridger Wi-Fi does not require wireless debugging.'),
h('How to stop or revoke access'),list('Use the PC app’s pause control or return to Windows with Ctrl + Alt + S when you want to stop controlling the phone.','Disable the PhoneBridger accessibility service in Android settings if you no longer want that service access.','Use the app’s forget action to revoke the saved phone/computer pairing rather than treating an unplugged cable as revocation.','Review or revoke Android debugging authorizations separately when you no longer trust that PC for debugging.'),
h('What to send support'),p('Describe the feature you are enabling, the exact visible prompt, your Android version and the app version. A cropped screenshot of the setting can help if it contains no personal content. Do not include a password, pairing token, private app messages or a full settings export.'),
],related:['guides/getting-started','guides/usb-wifi'],sources:[{url:'https://support.google.com/android/answer/12623953?hl=en',label:'Google Android Help: restricted settings',reason:'Restricted settings, accessibility capability and trusted-developer warning; retrieved 2026-10-06.'},{url:'https://developer.android.com/media/platform/av-capture',label:'Android Developers: playback capture',reason:'Android 10 playback capture, system consent and source-app capture policy; retrieved 2026-10-06.'}]},
{slug:'guides/phone-position',type:'guide',image:'phone-position',category:'Your desk',title:'Put your phone in the right place: positions and transition zones',description:'Match left, right or above in PhoneBridger to the phone on your desk, then check entry, return and a comfortable multi-phone arrangement.',intent:'How should I match the physical phone position and screen-edge transition zone?',lede:'Choose Left, Right or Above to match where the phone actually sits beside your PC. Then set the matching screen-edge transition zone and check entry and return with one phone before adding more.',body:[
h('Start from the physical arrangement'),p('Keep the phone screen visible and within a comfortable viewing position. If it sits on the left of the PC screen, select Left; if it sits on the right, select Right; if it sits above the PC screen, select Above. The setting describes your desk arrangement, not the phone’s USB port or its Wi-Fi address.'),p('A magnetic holder is optional. A suitable existing phone stand can work too. Mount compatibility, attachment and stability depend on your actual phone, case and laptop; do not assume the website illustration guarantees a particular fit.'),
h('Position and transition zone are different choices'),p('Position chooses the side of the PC associated with that phone. The transition zone chooses the area of that screen edge you cross to enter it. Use the Windows app’s zone editor and test the visible area rather than treating the entire edge as an accidental trigger.'),p('Leave a zone that makes sense alongside other windows or monitors you use. This guide does not prescribe new sensitivity, movement timing or cursor tuning; it uses the app’s existing controls.'),
h('Make one simple check'),list('Connect one approved phone and open a harmless app screen on it.','Check the phone’s actual placement and choose the matching Left, Right or Above position in Windows.','Check the selected transition zone.','Move deliberately through that part of the PC screen edge. Verify that the phone is the screen you intended to enter.','Use Ctrl + Alt + S to return to Windows. Make one click and one scroll in a harmless screen before using your normal apps.'),
h('If you enter the wrong place or cannot enter'),list('Check that the phone is connected and approved; a saved position is not evidence of an active connection.','Check which phone you selected in the Windows device view.','Check the chosen position against the actual desk, then check the transition-zone area.','Check mouse-control permission on Android separately.','If the phone was rotated, compare its visible orientation and the app’s current state. Describe an unresolved mismatch to support instead of experimenting with unrelated settings.'),
h('Adding a second or third phone'),p('Add one phone at a time and give each its intended place. For example, a portrait phone on the left and a landscape phone above the PC are two different positions. The illustration is an arrangement example, not a statement that your device orientation or mount has been tested.'),p('Keep the same basic check for every phone: connected status, correct selected device, matching physical position and intended transition zone. The beta can configure up to three Android phones; one may use physical USB while others use Wi-Fi. Three positions do not imply three physical USB connections.'),
h('Returning after a connection switch'),p('USB and Wi-Fi share the same settings. When the connection changes, control returns to Windows; cross the configured edge again when the saved phone reconnects. An unavailable Wi-Fi network after unplugging a cable cannot be solved by changing the phone’s position.'),
h('Make the arrangement comfortable'),p('Choose a stable surface and keep the phone visible without covering the laptop’s vents or controls. Avoid a placement that pulls on the cable or makes the screen difficult to read. The right arrangement is the one you can use consistently; the app-only option lets you start with the stand you already have.'),p('If you need help, include the phone position, orientation, app versions and a simple sketch of the desk. Leave account credentials and private phone screens out of that sketch.'),
],related:['guides/getting-started','guides/usb-wifi','guides/android-permissions'],sources:[]}
];
export const editorial={slug:'editorial',type:'faq',title:'Who prepares the PhoneBridger guides',description:'Our guide scope, organizational attribution, source checks, illustration method and correction contact.',intent:'Who is responsible for this guidance and how are product claims checked?',body:[p('The organizational attribution for these guides is MB Pinet, the operator named in the shared project configuration. PhoneBridger’s guide contact is hello@phonebridger.com. We do not list a fictional individual expert, customer test or independent certification.'),h('How these guides are prepared'),p('AI assists research, drafting and layout. Product instructions are checked against the current release documentation; platform requirements are checked against linked primary Android or Microsoft sources. An agent’s editorial review is not an independent human expert review.'),h('What the illustrations mean'),p('Original contextual illustrations show a plausible desk, cable or permission theme. They do not document a customer installation, stocked product, exact device compatibility or a measured test. Precise controls and diagrams are provided as editable text and vector graphics. Required third-party credits are retained where applicable.'),h('Versions and dates'),p('These guides were prepared and checked on 6 October 2026 for the beta described on Downloads. This private preview is not evidence of public publication. Before launch, the real first publication date and any later meaningful review must be recorded; changing a calendar date alone does not update the guidance.'),h('Scope and corrections'),p('Use the guides to understand setup and feature limits. They do not replace Android’s own permission explanation, your organization’s policy or the manufacturer’s hardware requirements. Send the page URL, the inaccurate sentence and a supporting source to hello@phonebridger.com. Do not send passwords, pairing codes or private messages.'),h('What we do not claim'),p('There is no measured latency guarantee, supported-device certification, independent product review or proof of demand in these guides. Paid orders, production customer accounts and native file dragging are not activated by the website preview.')],related:['guides','about'],sources:[]};
