import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const here=fileURLToPath(new URL('.',import.meta.url));
const runtime=path.resolve(process.argv[2]||'');
if(!process.argv[2])throw Error('Supply homepage source directory.');
const core=path.resolve(here,'../../../../dovanos-memorycasting');
const {projectPublicPages,contextualParts}=await import(pathToFileURL(path.join(core,'lib/niche-links.mjs')).href);
const seo=await import(pathToFileURL(path.join(core,'lib/niche-seo-core.mjs')).href);
const {nicheSchemaGraph,nicheBreadcrumbs,nicheEditorialDates}=await import(pathToFileURL(path.join(core,'lib/niche-schema-core.mjs')).href);
const {imageSrcSet}=await import(pathToFileURL(path.join(core,'lib/niche-media.mjs')).href);
const shared=createRequire(import.meta.url)(path.resolve(runtime,'../../source/site-pages-v1/build.cjs'));
const pkg=JSON.parse(await readFile(path.join(here,'package/content-package.json'),'utf8'));
const settings=JSON.parse(await readFile(path.join(core,'config/niche-network.json'),'utf8'));
const pages=projectPublicPages(pkg,[pkg],settings);
const byId=new Map(pages.map(p=>[p.id,p])),bySlug=new Map(pages.map(p=>[p.slug,p]));
const esc=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const guidePages=pages.filter(p=>p.type==='guide');
const routeHref=(base,p)=>`${base}${p.slug?`${p.slug}/`:''}`;
const anchor=text=>text.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function image(page,base,sizes,lazy=false){const asset=page.media[0];return `<img src="${base}${asset.src.slice(1)}" srcset="${esc(imageSrcSet(page.media,asset).replaceAll('/content-assets/',`${base}content-assets/`))}" sizes="${sizes}" width="${asset.width}" height="${asset.height}" alt="${esc(asset.alt)}" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`;}
function linked(text,page,base){const links=page.links.map(l=>({label:l.label,href:`/${byId.get(l.targetPageId).slug}/`}));return contextualParts(text,links).map(p=>p.href?`<a href="${esc(`${base}${p.href.slice(1)}`)}">${esc(p.text)}</a>`:esc(p.text)).join('');}
function body(page,base){return page.body.map((b,index)=>b.type==='heading'?`<h${b.level} id="${anchor(b.text)}">${esc(b.text)}</h${b.level}>`:b.type==='paragraph'?`<p>${linked(b.text,page,base)}</p>`:b.type==='list'?`<ul>${b.items.map(t=>`<li>${linked(t,page,base)}</li>`).join('')}</ul>`:'').join('');}
function breadcrumb(page,base){return `<nav class="guide-breadcrumb" aria-label="Breadcrumb"><ol>${nicheBreadcrumbs(pkg,page,pages).map((b,i,a)=>`<li>${i===a.length-1?`<span aria-current="page">${esc(b.name)}</span>`:`<a href="${b.path==='/'?base:`${base}${b.path.slice(1)}/`}">${esc(b.name)}</a>`}</li>`).join('')}</ol></nav>`;}
function related(page,base){return `<section class="guide-next" aria-labelledby="next-title"><h2 id="next-title">A useful next step.</h2><div class="guide-related">${page.links.filter(l=>byId.get(l.targetPageId)?.type==='guide').map(l=>`<a href="${routeHref(base,byId.get(l.targetPageId))}">${esc(byId.get(l.targetPageId).title)} ${shared.icon('arrow').replaceAll('../',base)}</a>`).join('')}</div><p><a href="${base}downloads/">Get both beta apps</a> · <a href="${base}contact/?topic=pairing">Ask for setup help</a></p></section>`;}
function head(page,base){const asset=page.media[0]||guidePages[0].media[0];const url=seo.nichePageUrlCore(pkg,page);return `<meta name="description" content="${esc(page.description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="${page.type==='guide'?'article':'website'}"><meta property="og:site_name" content="PhoneBridger"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://${pkg.canonicalHost}${asset.src}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify(nicheSchemaGraph(pkg,page,pages,'MB Pinet')).replaceAll('<','\\u003c')}</script>`;}
await mkdir(path.join(runtime,'assets/guides-v1'),{recursive:true});
await writeFile(path.join(runtime,'assets/guides-v1/guides.css'),await readFile(path.join(here,'guides.css')));
for(const page of pages.filter(p=>p.type==='guide'||['guides','editorial'].includes(p.slug))){
 const base='../'.repeat(page.slug.split('/').length);let content;
 if(page.slug==='guides'){
  content=`<section class="guide-hub-intro"><h1>A clear start.<br><span>A smoother everyday setup.</span></h1><p>Practical answers for pairing, permissions and the place your phone calls home.</p></section><div class="guide-hub-grid">${guidePages.map((g,i)=>`<article class="guide-card ${i===0?'guide-featured':''}"><a class="guide-card-image" href="${routeHref(base,g)}" tabindex="-1" aria-hidden="true">${image(g,base,i===0?'(max-width: 760px) calc(100vw - 40px), 650px':'(max-width: 760px) calc(100vw - 40px), (max-width: 1000px) calc((100vw - 116px) / 2), 260px',i>0)}</a><div class="guide-card-content"><h2><a href="${routeHref(base,g)}">${esc(g.title)} ${shared.icon('arrow').replaceAll('../',base)}</a></h2><p>${esc(g.description)}</p><span class="guide-read">${Math.ceil(g.body.map(b=>b.text||b.items?.join(' ')||'').join(' ').split(/\s+/).length/200)} min read</span></div></article>`).join('')}</div><section class="guide-support"><div><h2>Stuck on one step?</h2><p>Tell us the visible status and your app versions. Keep passwords and pairing codes private.</p></div><a class="button secondary" href="${base}contact/?topic=pairing">Ask for help ${shared.icon('arrow').replaceAll('../',base)}</a></section><div class="guide-method"><p>Prepared for the current beta by <a href="${base}editorial/">MB Pinet</a>. Checked on 6 October 2026.</p><a href="${base}editorial/">How these guides are prepared ${shared.icon('arrow').replaceAll('../',base)}</a></div>`;
 }else if(page.type==='guide'){
  const headings=page.body.filter(b=>b.type==='heading');const dates=nicheEditorialDates(page);
  content=`${breadcrumb(page,base)}<header class="guide-article-header"><h1>${esc(page.title)}</h1><p class="guide-lede">${esc(page.body[0].text)}</p><div class="guide-meta"><a href="${base}editorial/">MB Pinet</a><span>Prepared 6 October 2026</span><span>Reviewed ${new Date(dates.modified).toISOString().slice(0,10)}</span><span>${Math.ceil(page.body.map(b=>b.text||b.items?.join(' ')||'').join(' ').split(/\s+/).length/200)} min read</span></div></header><figure class="guide-hero">${image(page,base,'(max-width: 760px) calc(100vw - 40px), (max-width: 1200px) calc(100vw - 96px), 1120px')}<figcaption>Illustrative ${page.slug.endsWith('usb-wifi')?'cable context':page.slug.endsWith('phone-position')?'desk arrangement':page.slug.endsWith('android-permissions')?'permission theme':'desk setup'}; device appearance and compatibility vary.</figcaption></figure><div class="guide-layout"><aside class="guide-toc"><details open><summary>In this guide</summary><nav aria-label="On this page">${headings.map(b=>`<a href="#${anchor(b.text)}">${esc(b.text)}</a>`).join('')}</nav></details><a class="guide-toc-back" href="${base}guides/">${shared.icon('arrow').replaceAll('../',base)} All guides</a></aside><article class="guide-prose">${body({...page,body:page.body.slice(1)},base)}${page.externalLinks?.length?`<section class="guide-sources"><h2>Sources &amp; scope</h2><ul>${page.externalLinks.map(l=>`<li><a href="${esc(l.url)}">${esc(l.label)} ${shared.icon('arrow').replaceAll('../',base)}</a><p>${esc(l.reason)}</p></li>`).join('')}</ul></section>`:''}<p class="guide-review-note">Product steps checked against the current release documentation on 6 October 2026. This private preview records a prepared editorial edition; it is not a past public publication. <a href="${base}editorial/">Review method &amp; corrections</a>.</p></article></div>${related(page,base)}`;
 }else content=`${breadcrumb(page,base)}<header class="guide-article-header"><h1>${esc(page.title)}</h1><p class="guide-lede">Clear instructions, traceable sources and honest limits.</p></header><article class="guide-prose editorial-prose">${body(page,base)}<p><a href="${base}guides/">Explore the guides ${shared.icon('arrow').replaceAll('../',base)}</a></p></article>`;
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="theme-color" content="#101114"><title>${esc(page.title)} — PhoneBridger</title>${head(page,base)}<link rel="icon" href="${base}assets/brand-mark.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/fonts/manrope-800.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${base}assets/site-pages-v1/site.css"><link rel="stylesheet" href="${base}assets/guides-v1/guides.css"><script src="${base}assets/site-pages-v1/site.js" defer></script></head><body data-page="guides">${shared.header('guides').replaceAll('../',base)}<main id="main" class="shell guide-main">${content}</main>${shared.footer.replaceAll('../',base)}</body></html>`;
 await mkdir(path.join(runtime,page.slug),{recursive:true});await writeFile(path.join(runtime,page.slug,'index.html'),html);
}
// Extend allowed inner pages through the shared formatter. Frozen homepage head stays untouched.
for(const page of pages.filter(p=>p.slug&&!['guides','editorial'].includes(p.slug)&&p.type!=='guide')){
 const file=path.join(runtime,page.slug,'index.html'),base='../';let html=await readFile(file,'utf8');
 html=html.replace(/<meta name="description"[^>]*>/,head(page,base));
 if(page.slug==='help')html=html.replace('</main>',`<section class="guide-support"><div><h2>Prefer a step-by-step answer?</h2><p>Pairing, connections, permissions and phone placement.</p></div><a class="button secondary" href="../guides/">Explore the guides ${shared.icon('arrow').replaceAll('../',base)}</a></section></main>`).replace('</head>','<link rel="stylesheet" href="../assets/guides-v1/guides.css"></head>');
 await writeFile(file,html);
}
await writeFile(path.join(runtime,'robots.txt'),seo.nicheRobotsTextCore(pkg,true,true));
await writeFile(path.join(runtime,'sitemap.xml'),seo.nicheSitemapXmlCore(pkg,pages));
await writeFile(path.join(runtime,'llms.txt'),seo.nicheLlmsIndexCore(pkg,pages));
await writeFile(path.join(runtime,'llms-full.txt'),seo.nicheLlmsFullCore(pkg,pages,'MB Pinet'));
await writeFile(path.join(here,'projection.json'),JSON.stringify({mode:'private prepared preview',eligible:pages.map(p=>({slug:p.slug,id:p.id,revisionHash:p.revisionHash,media:p.media.length})),publicAdmission:false,homepageHeadFrozen:true},null,2)+'\n');
console.log(JSON.stringify({newRoutes:6,sharedSeoPages:pages.length,privateRobots:true,frozenHomepageHead:true}));
