/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Native SSR links and responsive raster families. */
import type {NichePackage,NichePage,NicheBlock,NicheMedia} from '@/lib/niche-sites';
import {nichePagePath} from '@/lib/niche-sites';
import {nicheJsonLd} from '@/lib/niche-seo';
import {nicheBreadcrumbs} from '@/lib/niche-schema-core.mjs';
import {imageSrcSet} from '@/lib/niche-media.mjs';
import {ArticleMeta} from './article-meta';
import {InterestTracking} from './interest-tracking';
import {LinkedText} from './linked-text';
import styles from './laiptucentras-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};
function Arrow(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>}
function Mark(){return <svg width="38" height="38" viewBox="0 0 40 40" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 32h9V22h9V12h10V4M4 36 36 4"/></svg>}
function Text({text,page,livePages}:{text:string;page:NichePage;livePages:NichePage[]}){return <LinkedText text={text} page={page} livePages={livePages}/>}
function Picture({page,asset,sizes,priority=false,className}:{page:NichePage;asset?:NicheMedia;sizes:string;priority?:boolean;className?:string}){return asset?<img className={className} src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>:null;}
function uniqueMedia(page:NichePage){return page.media.filter((a,i,arr)=>arr.findIndex(x=>x.alt===a.alt)===i);}
function Header({page,livePages}:Props){const entries=[['vidaus-laiptu-irengimas','Laiptų poreikis'],['gidai','Gidai'],['apie-projekta','Apie projektą']];const nav=<>{entries.map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`} aria-current={page.slug===slug?'page':undefined}>{label}</a>)}<a className={styles.button} href="/kontaktai#poreikis">Aprašyti poreikį <Arrow/></a></>;
return <header className={styles.header}><div className={styles.headerInner}><a className={styles.brand} href="/" aria-label="Laiptų centras – pradžia"><Mark/><span>laiptų<br/>centras</span></a><nav className={styles.desktopNav} aria-label="Pagrindinė navigacija">{nav}</nav><details className={styles.mobileNav}><summary>Meniu <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18"/></svg></summary><nav aria-label="Mobilioji navigacija">{nav}</nav></details></div></header>;}
function Breadcrumb({pkg,page,livePages}:Props){return <nav className={styles.breadcrumb} aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg,page,livePages).map((item:{name:string;path:string},i:number,arr:{name:string;path:string}[])=> <span key={item.path}>{i>0&&<span aria-hidden="true"> / </span>}{i===arr.length-1?<span aria-current="page">{item.name}</span>:<a href={item.path}>{item.name}</a>}</span>)}</nav>;}
function Blocks({blocks,page,livePages,offset=0}:{blocks:NicheBlock[];page:NichePage;livePages:NichePage[];offset?:number}){return blocks.map((b,i)=>b.type==='paragraph'?<p key={i}><Text text={b.text} page={page} livePages={livePages}/></p>:b.type==='heading'?(b.level===2?<h2 key={i} id={`section-${i+offset}`}>{b.text}</h2>:<h3 key={i} id={`section-${i+offset}`}>{b.text}</h3>):b.type==='list'?<ul key={i}>{b.items.map((t,j)=><li key={j}><Text text={t} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Picture page={page} asset={page.media.find(a=>a.id===b.assetId)} sizes="(max-width: 800px) calc(100vw - 44px), 740px"/></figure>);}
function GuideList({livePages,headingLevel=3}:{livePages:NichePage[];headingLevel?:2|3}){const Heading=headingLevel===2?"h2":"h3";return <div className={styles.guideGrid}>{livePages.filter(p=>p.type==='guide').map(p=><article key={p.id}><a className={styles.guideImage} href={nichePagePath(p)} tabIndex={-1} aria-hidden="true"><Picture page={p} asset={p.media[0]} sizes="(max-width: 700px) calc(100vw - 44px), (max-width: 1000px) 45vw, 400px"/></a><Heading><a href={nichePagePath(p)}>{p.title}</a></Heading><p>{p.description}</p><a className={styles.textLink} href={nichePagePath(p)}>Skaityti gidą <Arrow/></a></article>)}</div>;}
function Contact({pkg,page,livePages,blocks}:{pkg:NichePackage;page:NichePage;livePages:NichePage[];blocks?:NicheBlock[]}){const service=livePages.find(p=>p.slug==='vidaus-laiptu-irengimas');return <section id="poreikis" className={styles.contact} aria-labelledby="form-title"><div className={styles.contactIntro}><h2 id="form-title">{blocks?.[0]?.type==='heading'?blocks[0].text:'Aprašykite planuojamus laiptus'}</h2>{blocks?<Blocks blocks={blocks.slice(1)} page={page} livePages={livePages}/>:<p>Nurodykite darbą, vietovę, dabartinį etapą ir planuojamą laiką.</p>}<p className={styles.formLimit}>Registracija nėra užsakymas. Gamybos partnerystės dar nesudarytos; pasiūlymo ar atvykimo negarantuojame.</p>{service&&<a className={styles.textLink} href={nichePagePath(service)}>Registracijos eiga ir ribos <Arrow/></a>}<p><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p></div><form className={styles.form} action="/uzklausa" method="post" acceptCharset="utf-8"><div className={styles.formPair}><label>Jūsų vardas<input name="name" autoComplete="name" minLength={2} maxLength={100} required/></label><label>El. paštas<input name="email" type="email" autoComplete="email" maxLength={250} required/></label></div><label>Darbas, vietovė ir planuojamas laikas<textarea name="message" rows={6} minLength={20} maxLength={3000} required aria-describedby="message-help" placeholder="Pvz., nauji vidaus laiptai Vilniaus rajone. Namas įrengiamas, anga paruošta. Reikia karkaso, pakopų ir turėklų. Planuoju pavasarį."/></label><p id="message-help" className={styles.formHelp}>Parašykite bent 20 ženklų. Jei matmenų dar neturite, taip ir nurodykite. Tikslus adresas nereikalingas. Nuotraukas galite siųsti el. paštu.</p><label className={styles.consent}><input name="consent" type="checkbox" value="yes" required/><span>Sutinku, kad MB Pinet naudotų šiuos duomenis mano poreikiui įvertinti ir su manimi susisiekti.</span></label><p className={styles.formHelp}>Visi formos laukai privalomi. Tai nėra rinkodaros sutikimas; duomenys automatiškai gamintojams neperduodami. <a href="/privatumas">Privatumo informacija</a>.</p><div className={styles.honeypot} aria-hidden="true"><label>Palikite tuščią<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className={styles.button} type="submit">Registruoti laiptų poreikį <Arrow/></button></form></section>;}
function Footer({pkg,livePages}:Props){const links=[['gidai','Visi gidai'],['kontaktai','Kontaktai'],['apie-projekta','Apie projektą'],['redakcija','Redakcija'],['privatumas','Privatumas'],['naudojimo-salygos','Naudojimo sąlygos']];return <footer className={styles.footer}><div className={styles.footerTop}><a className={styles.brand} href="/"><Mark/><span>laiptų<br/>centras</span></a><p>MB Pinet<br/><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p><nav aria-label="Poraštės navigacija">{links.map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a href={`/${slug}`} key={slug}>{label}</a>)}</nav></div><div className={styles.footerBottom}><p>{pkg.site.offer}</p><p>Mūsų verslas automatizuotas su <a href="https://verslomatika.lt/" rel="noopener noreferrer">verslomatika.lt</a></p></div></footer>;}
function groups(body:NicheBlock[]){const result:{title:string;blocks:NicheBlock[];offset:number}[]=[];for(const [i,b] of body.entries()){if(b.type==='heading'&&b.level===2)result.push({title:b.text,blocks:[b],offset:i});else if(result.length)result[result.length-1].blocks.push(b);}return result;}
function Home(props:Props){const {page,livePages}=props;const images=uniqueMedia(page),sections=groups(page.body),intro=page.body.filter((b,i)=>b.type==='paragraph'&&i<2);return <><section className={styles.hero}><div className={styles.heroIntro}><h1>{page.title}</h1><div><Blocks blocks={intro.slice(0,1)} page={page} livePages={livePages}/><div className={styles.actions}><a className={styles.button} href="/kontaktai#poreikis">Aprašyti laiptų poreikį <Arrow/></a><a className={styles.textLink} href="/gidai">Pradėti nuo gidų</a></div><div className={styles.pilotNotice}><Blocks blocks={intro.slice(1)} page={page} livePages={livePages}/></div></div></div><Picture page={page} asset={images[0]} sizes="(max-width: 1400px) calc(100vw - 44px), 1320px" priority className={styles.heroImage}/><p className={styles.caption}>Vidaus laiptų sprendimo iliustracija</p></section><section className={styles.needs}><Blocks blocks={sections[0]?.blocks??[]} offset={sections[0]?.offset??0} page={page} livePages={livePages}/><a className={styles.textLink} href="/vidaus-laiptu-irengimas">Kokį poreikį galite registruoti <Arrow/></a></section><section className={styles.material}><div><Picture page={page} asset={images[1]} sizes="(max-width: 800px) calc(100vw - 44px), 660px"/><p className={styles.caption}>Konstrukcija ir pakopos apdaila yra skirtingos dalys</p></div><div className={styles.materialCopy}><Blocks blocks={sections[1]?.blocks??[]} offset={sections[1]?.offset??0} page={page} livePages={livePages}/></div></section><section className={styles.prepare}><Blocks blocks={sections[2]?.blocks??[]} offset={sections[2]?.offset??0} page={page} livePages={livePages}/></section><section className={styles.guides}><div className={styles.sectionTitle}><h2>Aiškesnis sprendimas, žingsnis po žingsnio.</h2><a className={styles.textLink} href="/gidai">Visi gidai <Arrow/></a></div><GuideList livePages={livePages}/></section><Contact {...props} blocks={sections[3]?.blocks}/></>;}
function Inner(props:Props){const {pkg,page,livePages}=props;const isGuide=page.type==='guide',isIndex=page.slug==='gidai',toc=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:`section-${i}`}]:[]);const guideImage=page.media[0];return <><section className={styles.pageIntro}><Breadcrumb {...props}/><h1>{page.title}</h1><p className={styles.lead}>{page.description}</p>{isGuide&&<ArticleMeta pkg={pkg} page={page} pages={livePages} className={styles.byline}/>}</section>{isIndex?<section className={styles.index}><div className={styles.indexIntro}><Blocks blocks={page.body} page={page} livePages={livePages}/></div><GuideList livePages={livePages} headingLevel={2}/></section>:<div className={`${styles.readingLayout} ${isGuide?styles.guideLayout:''}`}><article className={styles.article}>{guideImage&&<figure className={styles.articleFigure}><Picture page={page} asset={guideImage} sizes="(max-width: 800px) calc(100vw - 44px), 740px" priority/><figcaption>Iliustracija – ne kliento projektas</figcaption></figure>}<Blocks blocks={page.body} page={page} livePages={livePages}/>{Boolean(page.externalLinks?.length)&&<section className={styles.sources} id="saltiniai"><h2>Šaltiniai ir jų ribos</h2><ul>{page.externalLinks?.map(s=><li key={s.url}><a href={s.url}>{s.label}</a><p>{s.reason}</p></li>)}</ul></section>}</article>{isGuide&&<aside className={styles.contents}><details open><summary>Šio gido turinys</summary><nav aria-label="Gido turinys">{toc.map(t=><a key={t.id} href={`#${t.id}`}>{t.text}</a>)}<a href="#saltiniai">Šaltiniai ir jų ribos</a></nav></details><a className={styles.button} href="/kontaktai#poreikis">Aprašyti poreikį <Arrow/></a></aside>}</div>}{page.links.length>0&&!isIndex&&<section className={styles.related} aria-labelledby="related-title"><h2 id="related-title">Kitas naudingas žingsnis</h2><div>{page.links.map(link=>{const target=livePages.find(p=>p.id===link.targetPageId);return target?<a key={target.id} className={styles.textLink} href={nichePagePath(target)}>{link.label}<Arrow/></a>:null;})}</div></section>}{['kontaktai','vidaus-laiptu-irengimas'].includes(page.slug)&&<Contact {...props}/>}</>;}
export function LaiptucentrasSite(props:Props){return <div className={styles.shell}>{['newsreader-400.woff2','manrope-latin-a30ddcd34970.woff2','manrope-latin-ext-3911b66d9f2e.woff2'].map(font=><link key={font} rel="preload" href={'/fonts/laiptucentras/'+font} as="font" type="font/woff2" crossOrigin="anonymous"/>)}<InterestTracking/><a href="#turinys" className={styles.skip}>Pereiti prie turinio</a><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><Header {...props}/><main id="turinys" tabIndex={-1}>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}</main><Footer {...props}/></div>;}
