import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';
const dir=import.meta.dirname,project=new URL('../../',import.meta.url),core='C:/Users/lenovo/Documents/dovanos-memorycasting/',ws=new URL('WORKSTREAMS.md',project);
const note='2026-10-03 fasadopastoliai mažas shared langas: po BUSINESS/istorijos/actual tyrimo ir official studio11pages20WebP, tik viena savo dispatch šaka ir SVG/favicon šaka, vienas networkDomains papildymas fasadopastoliai.lt bei oficialus import/compile aktualių visų paketų. Savi Archivo/SourceSans3 fontai su OFL; own renderer/tools/CSS. Izoliuota QA kopija/8911, SMTP/voice/FB/off, bendras dist nekinta. Auto8910/FIRST-RUN ir kitų nišų failai/procesai neliečiami.\n\n';await writeFile(ws,note+await readFile(ws,'utf8'));
await mkdir(dir+'/qa',{recursive:true});const changes=[];
for(const [file,apply]of [
['app/niche/[siteId]/[[...slug]]/page.tsx',s=>{const anchor='  const { GenericNicheSite } = await import';if(!s.includes(anchor))throw Error('Dispatch anchor');if(s.includes('siteId === "fasadopastoliai"'))return s;return s.replace(anchor,'  if (siteId === "fasadopastoliai") { const { FasadopastoliaiSite } = await import("@/components/niche/fasadopastoliai-site"); return <FasadopastoliaiSite {...props} />; }\n'+anchor)}],
['app/niche/[siteId]/brand-icon/route.ts',s=>{const anchor='  if (pkg.siteId === "autoelektrikaivilniuje")';if(!s.includes(anchor))throw Error('Icon anchor');if(s.includes('pkg.siteId === "fasadopastoliai"'))return s;return s.replace(anchor,'  if (pkg.siteId === "fasadopastoliai") {\n    const svg = \'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 38 38"><rect width="38" height="38" fill="#d4e84c"/><path d="M6 33V5h26v28M6 14h26M6 24h26M19 5v28M6 5l13 9 13-9M6 24l13 9 13-9" fill="none" stroke="#182d31" stroke-width="2.4"/></svg>\';\n    return new Response(svg, { headers: { "content-type": "image/svg+xml", "cache-control": "public, max-age=3600", "x-content-type-options": "nosniff" } });\n  }\n'+anchor)}],
['config/niche-network.json',s=>{const j=JSON.parse(s);if(!j.networkDomains.includes('fasadopastoliai.lt'))j.networkDomains.push('fasadopastoliai.lt');j.networkDomains.sort();return JSON.stringify(j,null,2)+'\n'}]
]){const before=await readFile(core+file,'utf8'),after=apply(before);await writeFile(core+file,after);changes.push({file,beforeSha256:createHash('sha256').update(before).digest('hex'),afterSha256:createHash('sha256').update(after).digest('hex'),scope:'only own additive branch; existing branches preserved'})}
await writeFile(dir+'/qa/integration.json',JSON.stringify({at:new Date().toISOString(),changes,liveDomainsChanged:false,otherRendererChanged:false,sharedDistChanged:false},null,2)+'\n');
