import {readFile,writeFile,cp,mkdir} from 'node:fs/promises';
const dir=import.meta.dirname,first=new URL('../autoelektrikaivilniuje/',import.meta.url);
await mkdir(dir+'/qa',{recursive:true});
let prepare=await readFile(new URL('prepare-preview.mjs',first),'utf8');prepare=prepare.replaceAll('autoelektrikaivilniuje','fasadopastoliai').replaceAll('8910','8911');await writeFile(dir+'/prepare-preview.mjs',prepare);
for(const file of ['seo-all.mjs','publication.mjs','cleanup-ui.mjs']){let s=await readFile(new URL('qa/'+file,first),'utf8');s=s.replaceAll('autoelektrikaivilniuje','fasadopastoliai').replaceAll('8910','8911').replaceAll('autoelektriko-kontaktai-adresas-vilniuje','technine_informacija');await writeFile(dir+'/qa/'+file,s)}
let form=await readFile(new URL('qa/form-measurement.mjs',first),'utf8');form=form.replaceAll('autoelektrikaivilniuje','fasadopastoliai').replaceAll('8910','8911').replaceAll('diagnostikos-poreikis','nuomos-poreikis').replaceAll('trumpi-vaziavimai-akumuliatorius','nuomos-pratesimas').replaceAll('Sintetinis planinės diagnostikos poreikio testas. Ne klientas.','Sintetinis pastolių nuomos poreikio testas. Ne klientas.');
form=form.replace("'Original cross-host POST → next oversized POST sequence returned a local proxy 503; standalone same-host oversized request returned 400. Order adjusted for per-case checks; not a claim of cross-host transport recovery. See form-measurement-failure.json.'","'First site observed a local cross-host POST sequencing limitation. This site checks rejected unknown host last; no transport recovery or production behavior is inferred from isolated case PASS.'");await writeFile(dir+'/qa/form-measurement.mjs',form);
let capture=await readFile(new URL('qa/capture-final.js',first),'utf8');capture=capture.replaceAll('autoelektrikaivilniuje','fasadopastoliai').replaceAll('8910','8911').replaceAll('akumuliatorius-issikrauna','fasado-matmenys').replaceAll('automobilis-neuzsiveda','nuoma-su-montavimu').replaceAll('diagnostikos-kaina','pastoliu-nuomos-kaina').replaceAll('diagnostikos-poreikis','nuomos-poreikis').replaceAll('Barlow Condensed','Archivo').replaceAll('Barlow','Source Sans 3').replaceAll("document.fonts.check('18px Source Sans 3'","document.fonts.check('18px \"Source Sans 3\"'");await writeFile(dir+'/qa/capture-final.js',capture);await writeFile(dir+'/qa/capture-initial.js',capture.replaceAll('-final.jpg','-initial.jpg'));
await writeFile(dir+'/qa/lint.json',JSON.stringify({at:new Date().toISOString(),files:['fasadopastoliai-site.tsx','fasadopastoliai-site.tools.tsx'],toolSession:97149,exitCode:0,output:'empty successful scoped eslint output'},null,2)+'\n');
await cp(new URL('qa/freeze-result.mjs',first),dir+'/qa/freeze-result-template.mjs');console.log('Own QA scripts; no other PASS copied.');
