import assert from 'node:assert/strict';
import {readFile,writeFile,rename,access} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../../..'),privateDir=path.join(root,'sites/madbeauty/cloudflare/output/mail-acceptance-20261010'),readJSON=async name=>JSON.parse(await readFile(path.join(privateDir,name),'utf8'));
try{await access(new URL('./RECEIPT.json',import.meta.url));throw Error('Immutable historical acceptance already exists; write a separately named supplement.');}catch(e){if(e.code!=='ENOENT')throw e;}
const before=await readJSON('before.json'),deployment=await readJSON('relay-deployment.json'),transport=await readJSON('transport.json'),inbox=await readJSON('inbox.json');
assert.equal(before.result.status,400);assert.ok(deployment.exactReload&&deployment.guardOnly);assert.ok(inbox.booking.primaryInbox&&inbox.reminder.primaryInbox&&inbox.booking.exactBookingMatch&&inbox.reminder.exactBookingMatch);
const http=[];for(const [pathname,status,method] of [['/relay.php',200,'GET'],['/',404,'GET'],['/_private/config.php',403,'GET'],['/_private/protection-probe.txt',403,'GET'],['/relay.php',401,'POST']]){
 const r=await fetch('https://'+deployment.host+pathname,{method,redirect:'manual',signal:AbortSignal.timeout(15000),...(method==='POST'?{headers:{'content-type':'application/json'},body:'{}'}:{})});assert.equal(r.status,status,pathname);if(pathname==='/relay.php'&&method==='GET')assert.equal((await r.json()).ready,true);http.push({pathname,method,status:r.status});
}
const sha=v=>createHash('sha256').update(v).digest('hex'),source={};for(const name of ['infrastructure/mail-relay/relay.php','infrastructure/mail-relay/purpose.test.mjs','sites/madbeauty/mail-acceptance-20261010/run.mjs','sites/madbeauty/cloudflare/platform-object.mjs'])source[name]=sha(await readFile(path.join(root,name)));
const require=createRequire(path.join(root,'content-studio/package.json')),{default:sharp}=await import(pathToFileURL(require.resolve('sharp')));
const screenshots=[];for(const base of ['relay-saved','booking-inbox','reminder-inbox']){let bytes;try{bytes=await readFile(path.join(privateDir,base+'.jpeg'));}catch{bytes=await readFile(path.join(privateDir,base+'.png'));await rename(path.join(privateDir,base+'.png'),path.join(privateDir,base+'.jpeg'));}const meta=await sharp(bytes).metadata();assert.equal(meta.format,'jpeg');screenshots.push({name:base+'.jpeg',sha256:sha(bytes),width:meta.width,height:meta.height,storage:'Private ignored output; unedited native Chrome capture; not committed'});}
const receipt={schemaVersion:1,at:new Date().toISOString(),sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),sourceHashes:source,scope:'Existing protected relay narrow purpose correction; native isolated SQL booking/reminder with real SMTP and authorized own primary INBOX',before,relay:deployment,transport,inbox,http,screenshots,productRegression:{unchangedSource:true,reuse:'trial-20261010/OPERATIONS_RECEIPT.json at runtime7f08f8a,264/264; not claimed as newly rerun'},purposeContract:{command:'node --test infrastructure/mail-relay/purpose.test.mjs',pass:1,new:1,removed:0},canonical:{fullUpgradeActivated:false,applicationDeploymentUnchanged:true,databaseWrites:0,dnsChanges:0},trial:{deploymentUnchanged:true,databaseWrites:0,realMailEnabled:false},retention:{ownerConfirmedNoPolicy:true,proposal:'../platform-upgrade-20261007/RETENTION_BACKUP_PROPOSAL.md',approved:false,erasureExecutionEnabled:false},privateExclusions:['Credentials','OTP','Message bodies','Booking IDs','Mail UI message IDs','Native mailbox screenshots']};
await writeFile(new URL('./RECEIPT.json',import.meta.url),JSON.stringify(receipt,null,2)+'\n');console.log('Sanitized mail acceptance receipt written; primary INBOX2, public safety checks5 PASS.');
