import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {build}=await import(pathToFileURL(path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting/node_modules/esbuild/lib/main.js')));
const bundle=await build({entryPoints:[path.join(import.meta.dirname,'public/booking-ui.mjs')],write:false,bundle:true,format:'esm',platform:'node',plugins:[{name:'public-module-roots',setup(b){b.onResolve({filter:/^\/(cities|taxonomy|seo-contract)\.mjs$/},a=>({path:path.join(import.meta.dirname,a.path.slice(1))}));}}]});
const {bookingView,bookingForm,bookingAction}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
test('Booking variant selection has one checked authoritative service ID; staff choice keeps that ID and applies its own quote',async()=>{
 const rows=[{id:'variant-a',label:'A',organizationId:'org',practitionerId:'p1',practitionerName:'One',organizationName:'Test',city:'Vilnius',durationMin:60,priceMinor:2500,bufferBeforeMin:0,bufferAfterMin:0,addons:[],staffOptions:[{practitionerId:'p1',resourceId:'r1',name:'One',priceMinor:2500,durationMin:60},{practitionerId:'p2',resourceId:'r2',name:'Two',priceMinor:3500,durationMin:90}]},{id:'variant-b',label:'B',organizationId:'org',practitionerId:'p1',durationMin:30,priceMinor:1500,addons:[]}];
 const profile={kind:'salon',services:rows,practitioners:[{id:'p1',name:'One'},{id:'p2',name:'Two'}]},quote=(id,addons,p)=>{const s=rows.find(x=>x.id===id),x=s.staffOptions?.find(x=>x.practitionerId===p)||s;return {priceMinor:x.priceMinor,durationMin:x.durationMin,addons:[]};},ctx={state:{booking:{serviceId:'variant-a',practitionerId:'p1',addons:[],contact:{}},search:{}},adapter:{mode:'real',clock:{now:'2026-10-07T07:00:00Z'},catalog:async()=>rows,profile:async()=>profile,option:async(...args)=>quote(...args)},saveUI(){},navigate:async p=>{ctx.path=p;}};
 const first=await bookingView(ctx,'/registracija/paslauga'),radios=[...first.matchAll(/<input type="radio"[^>]*>/g)].map(x=>x[0]);assert.equal(radios.length,2);assert.equal(radios.filter(x=>/ checked/.test(x)).length,1);assert.ok(radios[0].includes('name="serviceId" value="variant-a"'));assert.ok(!radios.some(x=>x.includes('staffChoice')));
 const fd=new FormData();fd.set('serviceId','variant-a');await bookingForm(ctx,{id:'booking-services'},fd);assert.equal(ctx.path,'/registracija/meistras');const staff=await bookingView(ctx,ctx.path);assert.ok(staff.includes('value="variant-a|p2"'));assert.match(staff,/90 min\. · 35,00/);
 const choice=new FormData();choice.set('staffChoice','variant-a|p2');await bookingForm(ctx,{id:'booking-staff'},choice);assert.equal(ctx.state.booking.serviceId,'variant-a');assert.equal(ctx.state.booking.practitionerId,'p2');assert.equal(ctx.path,'/registracija/laikas');
});

test('Whole visit UI keeps order/staff/addons, prevents one-item submission and uses authoritative saved result after reschedule',async()=>{
 const rows=[{id:'a',label:'A',locationId:'place',organizationId:'org',practitionerId:'p1',practitionerName:'One',durationMin:30,priceMinor:1000,addons:[{id:'addon',label:'Extra',durationMin:15,priceMinor:500}]},{id:'b',label:'B',locationId:'place',organizationId:'org',practitionerId:'p2',practitionerName:'Two',durationMin:45,priceMinor:2000,addons:[]},{id:'elsewhere',label:'Hidden branch',locationId:'other',organizationId:'org',addons:[]}],profile={name:'Fixture',services:rows,practitioners:[{id:'p1',name:'One'},{id:'p2',name:'Two'}]};
 let released=0;const ctx={state:{booking:{serviceId:'a',practitionerId:'p1',addons:['addon'],contact:{},hold:{id:'h'}}},realAdapter:{session:{user:{id:'client'}}},adapter:{mode:'real',catalog:async()=>rows,profile:async()=>profile,releaseHold:async()=>released++,option:async(id,addons)=>({priceMinor:rows.find(x=>x.id===id).priceMinor+(addons.length?500:0),durationMin:rows.find(x=>x.id===id).durationMin+(addons.length?15:0),addons:[]})},saveUI(){},navigate:async p=>{ctx.path=p;},render:async()=>{}};
 await bookingAction(ctx,'sequence-start',{dataset:{}});assert.equal(released,1);assert.equal(ctx.state.booking.sequence,true);assert.deepEqual(ctx.state.booking.items[0].addons,['addon']);const html=await bookingView(ctx,'/registracija/paslauga');assert.ok(!html.includes('Hidden branch'));assert.match(html,/visitStaff:a/);
 const fd=new FormData();fd.append('visitService','a');fd.set('visitStaff:a','p1');await assert.rejects(bookingForm(ctx,{id:'visit-sequence-services'},fd),/bent dvi/);
 fd.append('visitService','b');fd.set('visitStaff:b','p2');fd.append('visitAddon:a','addon');await bookingForm(ctx,{id:'visit-sequence-services'},fd);assert.equal(ctx.path,'/registracija/laikas');await bookingAction(ctx,'sequence-up',{dataset:{id:'b'}});assert.deepEqual(ctx.state.booking.items.map(i=>i.providerServiceId),['b','a']);assert.deepEqual(ctx.state.booking.items[1].addons,['addon']);
 ctx.state.booking.result={id:'saved'};ctx.adapter.catalog=async()=>{throw Error('Archived catalogue must not hide saved booking');};ctx.adapter.workspace=async()=>({bookings:[{id:'saved',status:'confirmed',startAt:'2026-10-08T15:00:00Z',endAt:'2026-10-08T16:30:00Z',priceMinor:3500,segments:[{startAt:'2026-10-08T15:00:00Z',endAt:'2026-10-08T15:45:00Z',priceMinor:2000,serviceSnapshot:{label:'B',practitionerName:'Two'}}],serviceSnapshot:{location:{publicAddress:'Saved address',city:'Vilnius'}}}]});const saved=await bookingView(ctx,'/registracija/rezultatas');assert.match(saved,/18:00–19:30/);assert.match(saved,/Saved address/);assert.equal(ctx.state.booking.result.priceMinor,3500);
});

test('Returning from expired review does not mark an available time as already held; a current hold still marks its selected time',async()=>{
 const service={id:'fixture-variant',organizationId:'fixture-org',label:'Isolated cut',practitionerId:'fixture-staff',durationMin:60,priceMinor:2500,addons:[]},candidate={id:'fixture-slot',startAt:'2026-10-08T15:00:00Z',endAt:'2026-10-08T16:00:00Z'},now='2026-10-07T07:00:00Z';
 const ctx={state:{booking:{serviceId:service.id,addons:[],contact:{},candidate,hold:{id:'fixture-hold',expiresAt:'2026-10-07T06:59:59Z'}},search:{diena:1,nuo:'17:00',iki:'20:00'}},candidates:new Map(),dayKey:()=> '2026-10-08',dayLabel:()=> 'spalio 8 d.',adapter:{mode:'real',clock:{now},catalog:async()=>[service],option:async()=>({priceMinor:2500,durationMin:60,addons:[]}),profile:async()=>({services:[service],practitioners:[]}),availability:async()=>({state:'available',asOf:now,slots:[candidate]})}};
 let html=await bookingView(ctx,'/registracija/laikas');assert.match(html,/data-id="fixture-slot" aria-pressed="false"/);ctx.state.booking.hold.expiresAt='2026-10-07T07:02:00Z';html=await bookingView(ctx,'/registracija/laikas');assert.match(html,/data-id="fixture-slot" aria-pressed="true"/);
});
