import {readFile,writeFile} from 'node:fs/promises';
const url=new URL('./public/workspace-ui.mjs',import.meta.url);let s=await readFile(url,'utf8');
const start=s.indexOf('function calendar(ctx,d){'),end=s.indexOf('async function professionalView',start);
if(start<0||end<0)throw Error('Calendar boundaries missing');
const fn=String.raw`function calendar(ctx,d){
  const start=ctx.state.calendarDay,mode=ctx.state.calendarMode,days=mode==='day'?[start]:Array.from({length:5},(_,i)=>start+i);
  const forDay=i=>d.bookings.filter(b=>date(b.startAt)===ctx.dayLabel(i)).sort((a,b)=>a.startAt.localeCompare(b.startAt));
  const localMinute=at=>{const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Vilnius',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(at)).split(':').map(Number);return p[0]*60+p[1];};
  const lo=480,hi=1260,scale=1,dayMarkup=i=>{
    const rows=forDay(i),ends=[],positioned=rows.map(b=>{const from=localMinute(b.startAt),to=localMinute(b.endAt);let lane=ends.findIndex(end=>end<=from);if(lane<0)lane=ends.length;ends[lane]=to;return {b,from,to,lane};}),lanes=Math.max(1,ends.length);
    return '<section class="time-day"><h3>'+ctx.dayLabel(i)+'</h3><div class="time-day-body" style="height:'+((hi-lo)*scale)+'px">'+Array.from({length:13},(_,n)=>'<span class="hour-rule" style="top:'+(n*60*scale)+'px"></span>').join('')+positioned.map(({b,from,to,lane})=>{const label=d.services.find(s=>s.id===b.providerServiceId)?.label||'Vizitas',client=d.clients.find(c=>c.id===b.clientId)?.name||'Klientas',staff=d.practitioners.find(p=>p.id===b.practitionerId)?.name||'';return btn('visit-drawer','<strong>'+time(b.startAt)+'–'+time(b.endAt)+'</strong><span>'+esc(label)+'</span><span>'+esc(client)+'</span><small>'+esc(staff)+'</small>','data-id="'+b.id+'" aria-label="'+esc(time(b.startAt)+'–'+time(b.endAt)+', '+label+', '+client+', '+status(b.status))+'" style="top:'+Math.max(0,(from-lo)*scale)+'px;height:'+Math.max(40,(to-from)*scale)+'px;left:calc('+(lane*100/lanes)+'% + 4px);width:calc('+(100/lanes)+'% - 8px)"','time-appointment '+b.status);}).join('')+'</div></section>';
  };
  return '<div class="toolbar calendar-toolbar"><div class="row">'+btn('calendar-nav','Ankstesnė','data-id="-1" aria-label="Ankstesnė diena"','button outline small')+btn('calendar-today','Šiandien','','button outline small')+btn('calendar-nav','Kita','data-id="1" aria-label="Kita diena"','button outline small')+'</div><div class="segmented">'+[['day','Diena'],['week','Savaitė']].map(([id,l])=>btn('calendar-mode',l,'data-id="'+id+'" aria-pressed="'+(mode===id)+'"')).join('')+'</div>'+btn('manual-visit',icon('calendar')+' Naujas vizitas','','button accent small')+'</div><div class="calendar-caption"><strong>'+ctx.dayLabel(start)+'</strong><span>'+esc(d.organizations[0].name)+' · Vilniaus laikas</span></div><div class="time-calendar-wrap"><div class="time-calendar" style="grid-template-columns:48px repeat('+days.length+',minmax('+(mode==='day'?'250':'145')+'px,1fr))"><div class="time-axis"><div class="time-axis-head"></div><div style="height:'+((hi-lo)*scale)+'px">'+Array.from({length:13},(_,n)=>'<span style="top:'+(n*60*scale)+'px">'+hhmm(lo+n*60)+'</span>').join('')+'</div></div>'+days.map(dayMarkup).join('')+'</div></div><div class="agenda">'+days.map(i=>'<section><h2>'+ctx.dayLabel(i)+'</h2>'+list(forDay(i),b=>visitLine(ctx,b),'Šią dieną vizitų nėra.')+'</section>').join('')+'</div><p class="hint">Atidaryk vizitą, kad pakeistum jo laiką ar būseną.</p>';
}
`;
s=s.slice(0,start)+fn+s.slice(end);await writeFile(url,s);
