import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {build}=await import(pathToFileURL(path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting/node_modules/esbuild/lib/main.js')));
async function load(name){const b=await build({entryPoints:[path.join(import.meta.dirname,'public',name)],write:false,bundle:true,format:'esm',platform:'node',plugins:[{name:'public-root',setup(b){b.onResolve({filter:/^\/(cities|taxonomy|seo-contract)\.mjs$/},a=>({path:path.join(import.meta.dirname,a.path.slice(1))}));}}]});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));}
const {phaseFields,phaseValues}=await load('phase-fields.mjs'),{calendarView}=await load('calendar-ui.mjs');
test('Phase inputs have distinct accessible IDs, repeated values decode in order and keep independent staff/resource occupancy',()=>{
 const phases=[{label:'Work',durationMin:20,staffBusy:true,resourceBusy:true},{label:'Wait',durationMin:40,staffBusy:false,resourceBusy:true},{label:'Finish',durationMin:30,staffBusy:true,resourceBusy:true}],html=phaseFields(phases,'base-0','data-variant="0"'),ids=[...html.matchAll(/ id="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);assert.equal(ids.length,6);
 const fd=new FormData();for(let i=0;i<phases.length;i++){const p=phases[i];fd.append('phaseLabel-base-0',p.label);fd.append('phaseDuration-base-0',String(p.durationMin));if(p.staffBusy)fd.set('phaseStaff-base-0-'+i,'on');if(p.resourceBusy)fd.set('phaseResource-base-0-'+i,'on');}assert.deepEqual(phaseValues(fd,'base-0'),phases);
});
test('Calendar staff filter omits passive processing, chair filter retains it and excludes a booking on the other chair',()=>{
 const at=min=>new Date(Date.parse('2026-10-08T06:15:00Z')+min*60000).toISOString(),color={id:'whole-color',practitionerId:'p',resourceId:'r',clientId:'c',startAt:at(0),endAt:at(90),priceMinor:5000,status:'confirmed',serviceSnapshot:{label:'Colour'},phases:[{label:'Apply',startAt:at(0),endAt:at(20),staffBusy:true,resourceBusy:true},{label:'Wait',startAt:at(20),endAt:at(60),staffBusy:false,resourceBusy:true},{label:'Finish',startAt:at(60),endAt:at(90),staffBusy:true,resourceBusy:true}]},cut={id:'other-chair-cut',practitionerId:'p',resourceId:'r2',clientId:'c',startAt:at(30),endAt:at(45),priceMinor:1000,status:'confirmed',serviceSnapshot:{label:'Other chair cut'}};
 const d={organizations:[{name:'Fixture',kind:'salon'}],practitioners:[{id:'p',name:'Fixture staff'}],resources:[{id:'r',label:'Chair'},{id:'r2',label:'Other chair'}],clients:[{id:'c',name:'Fixture client'}],services:[],bookings:[color,cut],busyBlocks:[]},ctx={state:{calendarDay:1,calendarMode:'day',calendarStaff:'p'},adapter:{mode:'real'},dayKey:()=> '2026-10-08',dayInstant:()=> '2026-10-08T12:00:00Z',dayLabel:()=> 'spalio 8 d.'};
 let html=calendarView(ctx,d,()=> '');assert.ok(!html.includes('Wait · Colour'));assert.ok(html.includes('Other chair cut'));assert.ok(html.includes('Apply · Colour'));ctx.state.calendarStaff='';ctx.state.calendarResource='r';html=calendarView(ctx,d,()=> '');assert.ok(html.includes('Wait · Colour'));assert.ok(!html.includes('Other chair cut'));assert.match(html,/time-appointment confirmed processing/);assert.equal([...html.matchAll(/data-id="whole-color"/g)].length,3);
});
