import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {openStore} from '../backend/store.mjs';
import {createAuth} from '../backend/auth.mjs';
import {createPlatform} from '../backend/platform.mjs';
const {build}=await import(pathToFileURL(path.resolve(import.meta.dirname,'../../../../dovanos-memorycasting/node_modules/esbuild/lib/main.js')));
const bundle=await build({entryPoints:[path.join(import.meta.dirname,'public/moderation-ui.mjs')],write:false,bundle:true,format:'esm',platform:'node',plugins:[{name:'public-root',setup(b){b.onResolve({filter:/^\/(demo-model|cities|taxonomy|seo-contract)\.mjs$/},a=>({path:path.join(import.meta.dirname,a.path.slice(1))}));}}]});
const {submitReport,reportQueue,moderationAction}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
test('Contact report UI retries one committed request, rotates changed intent, and shows an escaped platform target with record-only decisions',async()=>{
 const previousDocument=globalThis.document,contexts=[],controls=Object.fromEntries(['state','action'].map(name=>[name,{selectedOptions:[{textContent:name==='state'?'Užbaigti sprendimą':'Užfiksuoti sprendimą'}],setAttribute(key,value){this[key]=value;},insertAdjacentElement(_position,context){contexts.push(context);}}]));let change;
 globalThis.document={querySelector:selector=>{assert.equal(selector,'#report-review');return {id:'report-review',elements:{namedItem:name=>controls[name]},addEventListener:(event,listener)=>{assert.equal(event,'change');change=listener;}};},createElement:tag=>{assert.equal(tag,'p');return {setAttribute(key,value){this[key]=value;}};}};
 const store=openStore({filename:':memory:',secret:'isolated-contact-ui-'.repeat(3)}),auth=createAuth(store),api=createPlatform(store),session=auth.session(null),c=auth.start(session,'contact-ui@example.com','127.0.0.1'),user=auth.verify(session,c.challengeId,store.capture(c.challengeId).code,'127.0.0.1').user,inputs=[];let lost=true;const ctx={realAdapter:{session:{user}},adapter:{mode:'real',report:async input=>{inputs.push({...input});const result=api.report(user,input);if(lost){lost=false;throw Error('Lost committed contact reply');}return result;}}};
 try{const input={target:'platform',note:'Isolated contact <script>issue</script>'};await assert.rejects(submitReport(ctx,input),/Lost committed/);const key=inputs[0].idempotencyKey;assert.ok(key);const replay=await submitReport(ctx,input);assert.equal(inputs[1].idempotencyKey,key);assert.equal(store.readCollections(['reports']).reports.length,1);assert.equal(ctx.reportIntent,undefined);await submitReport(ctx,{...input,note:'A separate issue'});assert.notEqual(inputs[2].idempotencyKey,key);assert.equal(store.readCollections(['reports']).reports.length,2);
 let dialogs=[];ctx.workspace={reports:[replay]};ctx.openDialog=(title,html)=>dialogs.push({title,html});const html=reportQueue(ctx,{reports:[replay],organizations:[]});assert.match(html,/Platforma/);assert.match(html,/Madbeauty/);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);await moderationAction(ctx,'report-status',{dataset:{id:replay.id}});assert.match(dialogs[0].html,/Madbeauty/);assert.doesNotMatch(dialogs[0].html,/disable-profile|hide-media|hide-review/);assert.match(dialogs[0].html,/record-only/);assert.match(dialogs[0].html,/Sprendimas ir priežastis bus matomi/);
 assert.deepEqual(contexts.map(c=>c.textContent),['Užbaigti sprendimą','Užfiksuoti sprendimą']);assert.equal(controls.action['aria-describedby'],'report-review-selected-action');assert.equal(contexts[1].role,'status');controls.action.selectedOptions[0].textContent='Pašalinti profilį iš katalogo';change();assert.equal(contexts[1].textContent,'Pašalinti profilį iš katalogo');
 }finally{store.close();if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument;}
});
