// Responsive illustration map generated by services-design-20261010/import-assets.mjs.
export const SERVICES_MEDIA={
  "plaukai": {
    "variants": [
      {
        "file": "images/service-illustration-plaukai-1242.webp",
        "width": 1242,
        "height": 1266
      },
      {
        "file": "images/service-illustration-plaukai-1200.webp",
        "width": 1200,
        "height": 1223
      },
      {
        "file": "images/service-illustration-plaukai-800.webp",
        "width": 800,
        "height": 815
      },
      {
        "file": "images/service-illustration-plaukai-640.webp",
        "width": 640,
        "height": 652
      },
      {
        "file": "images/service-illustration-plaukai-360.webp",
        "width": 360,
        "height": 367
      }
    ]
  },
  "nagai": {
    "variants": [
      {
        "file": "images/service-illustration-nagai-1145.webp",
        "width": 1145,
        "height": 1374
      },
      {
        "file": "images/service-illustration-nagai-800.webp",
        "width": 800,
        "height": 960
      },
      {
        "file": "images/service-illustration-nagai-640.webp",
        "width": 640,
        "height": 768
      },
      {
        "file": "images/service-illustration-nagai-360.webp",
        "width": 360,
        "height": 432
      }
    ]
  },
  "antakiai": {
    "variants": [
      {
        "file": "images/service-illustration-antakiai-1536.webp",
        "width": 1536,
        "height": 1024
      },
      {
        "file": "images/service-illustration-antakiai-1200.webp",
        "width": 1200,
        "height": 800
      },
      {
        "file": "images/service-illustration-antakiai-800.webp",
        "width": 800,
        "height": 533
      },
      {
        "file": "images/service-illustration-antakiai-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "file": "images/service-illustration-antakiai-360.webp",
        "width": 360,
        "height": 240
      }
    ]
  },
  "blakstienos": {
    "variants": [
      {
        "file": "images/service-illustration-blakstienos-1254.webp",
        "width": 1254,
        "height": 1254
      },
      {
        "file": "images/service-illustration-blakstienos-1200.webp",
        "width": 1200,
        "height": 1200
      },
      {
        "file": "images/service-illustration-blakstienos-800.webp",
        "width": 800,
        "height": 800
      },
      {
        "file": "images/service-illustration-blakstienos-640.webp",
        "width": 640,
        "height": 640
      },
      {
        "file": "images/service-illustration-blakstienos-360.webp",
        "width": 360,
        "height": 360
      }
    ]
  },
  "makiazas": {
    "variants": [
      {
        "file": "images/service-illustration-makiazas-1254.webp",
        "width": 1254,
        "height": 1254
      },
      {
        "file": "images/service-illustration-makiazas-1200.webp",
        "width": 1200,
        "height": 1200
      },
      {
        "file": "images/service-illustration-makiazas-800.webp",
        "width": 800,
        "height": 800
      },
      {
        "file": "images/service-illustration-makiazas-640.webp",
        "width": 640,
        "height": 640
      },
      {
        "file": "images/service-illustration-makiazas-360.webp",
        "width": 360,
        "height": 360
      }
    ]
  },
  "depiliacija": {
    "variants": [
      {
        "file": "images/service-illustration-depiliacija-1222.webp",
        "width": 1222,
        "height": 1287
      },
      {
        "file": "images/service-illustration-depiliacija-1200.webp",
        "width": 1200,
        "height": 1264
      },
      {
        "file": "images/service-illustration-depiliacija-800.webp",
        "width": 800,
        "height": 843
      },
      {
        "file": "images/service-illustration-depiliacija-640.webp",
        "width": 640,
        "height": 674
      },
      {
        "file": "images/service-illustration-depiliacija-360.webp",
        "width": 360,
        "height": 379
      }
    ]
  },
  "veido-prieziura": {
    "variants": [
      {
        "file": "images/service-illustration-veido-prieziura-1214.webp",
        "width": 1214,
        "height": 1295
      },
      {
        "file": "images/service-illustration-veido-prieziura-1200.webp",
        "width": 1200,
        "height": 1280
      },
      {
        "file": "images/service-illustration-veido-prieziura-800.webp",
        "width": 800,
        "height": 853
      },
      {
        "file": "images/service-illustration-veido-prieziura-640.webp",
        "width": 640,
        "height": 683
      },
      {
        "file": "images/service-illustration-veido-prieziura-360.webp",
        "width": 360,
        "height": 384
      }
    ]
  },
  "kuno-prieziura": {
    "variants": [
      {
        "file": "images/service-illustration-kuno-prieziura-1145.webp",
        "width": 1145,
        "height": 1374
      },
      {
        "file": "images/service-illustration-kuno-prieziura-800.webp",
        "width": 800,
        "height": 960
      },
      {
        "file": "images/service-illustration-kuno-prieziura-640.webp",
        "width": 640,
        "height": 768
      },
      {
        "file": "images/service-illustration-kuno-prieziura-360.webp",
        "width": 360,
        "height": 432
      }
    ]
  },
  "masazas": {
    "variants": [
      {
        "file": "images/service-illustration-masazas-1412.webp",
        "width": 1412,
        "height": 1114
      },
      {
        "file": "images/service-illustration-masazas-1200.webp",
        "width": 1200,
        "height": 947
      },
      {
        "file": "images/service-illustration-masazas-800.webp",
        "width": 800,
        "height": 631
      },
      {
        "file": "images/service-illustration-masazas-640.webp",
        "width": 640,
        "height": 505
      },
      {
        "file": "images/service-illustration-masazas-360.webp",
        "width": 360,
        "height": 284
      }
    ]
  },
  "spa-ir-poilsis": {
    "variants": [
      {
        "file": "images/service-illustration-spa-ir-poilsis-1402.webp",
        "width": 1402,
        "height": 1122
      },
      {
        "file": "images/service-illustration-spa-ir-poilsis-1200.webp",
        "width": 1200,
        "height": 960
      },
      {
        "file": "images/service-illustration-spa-ir-poilsis-800.webp",
        "width": 800,
        "height": 640
      },
      {
        "file": "images/service-illustration-spa-ir-poilsis-640.webp",
        "width": 640,
        "height": 512
      },
      {
        "file": "images/service-illustration-spa-ir-poilsis-360.webp",
        "width": 360,
        "height": 288
      }
    ]
  },
  "ilgalaikis-makiazas": {
    "variants": [
      {
        "file": "images/service-illustration-ilgalaikis-makiazas-1226.webp",
        "width": 1226,
        "height": 1283
      },
      {
        "file": "images/service-illustration-ilgalaikis-makiazas-1200.webp",
        "width": 1200,
        "height": 1256
      },
      {
        "file": "images/service-illustration-ilgalaikis-makiazas-800.webp",
        "width": 800,
        "height": 837
      },
      {
        "file": "images/service-illustration-ilgalaikis-makiazas-640.webp",
        "width": 640,
        "height": 670
      },
      {
        "file": "images/service-illustration-ilgalaikis-makiazas-360.webp",
        "width": 360,
        "height": 377
      }
    ]
  },
  "tatuiruotes": {
    "variants": [
      {
        "file": "images/service-illustration-tatuiruotes-1214.webp",
        "width": 1214,
        "height": 1295
      },
      {
        "file": "images/service-illustration-tatuiruotes-1200.webp",
        "width": 1200,
        "height": 1280
      },
      {
        "file": "images/service-illustration-tatuiruotes-800.webp",
        "width": 800,
        "height": 853
      },
      {
        "file": "images/service-illustration-tatuiruotes-640.webp",
        "width": 640,
        "height": 683
      },
      {
        "file": "images/service-illustration-tatuiruotes-360.webp",
        "width": 360,
        "height": 384
      }
    ]
  },
  "auskaru-verimas": {
    "variants": [
      {
        "file": "images/service-illustration-auskaru-verimas-1024.webp",
        "width": 1024,
        "height": 1536
      },
      {
        "file": "images/service-illustration-auskaru-verimas-800.webp",
        "width": 800,
        "height": 1200
      },
      {
        "file": "images/service-illustration-auskaru-verimas-640.webp",
        "width": 640,
        "height": 960
      },
      {
        "file": "images/service-illustration-auskaru-verimas-360.webp",
        "width": 360,
        "height": 540
      }
    ]
  },
  "estetines-proceduros": {
    "variants": [
      {
        "file": "images/service-illustration-estetines-proceduros-1175.webp",
        "width": 1175,
        "height": 1338
      },
      {
        "file": "images/service-illustration-estetines-proceduros-800.webp",
        "width": 800,
        "height": 911
      },
      {
        "file": "images/service-illustration-estetines-proceduros-640.webp",
        "width": 640,
        "height": 729
      },
      {
        "file": "images/service-illustration-estetines-proceduros-360.webp",
        "width": 360,
        "height": 410
      }
    ]
  },
  "services-hero": {
    "variants": [
      {
        "file": "images/service-illustration-services-hero-1536.webp",
        "width": 1536,
        "height": 1024
      },
      {
        "file": "images/service-illustration-services-hero-1200.webp",
        "width": 1200,
        "height": 800
      },
      {
        "file": "images/service-illustration-services-hero-800.webp",
        "width": 800,
        "height": 533
      },
      {
        "file": "images/service-illustration-services-hero-640.webp",
        "width": 640,
        "height": 427
      },
      {
        "file": "images/service-illustration-services-hero-360.webp",
        "width": 360,
        "height": 240
      }
    ]
  },
  "services-guide": {
    "variants": [
      {
        "file": "images/service-illustration-services-guide-1600.webp",
        "width": 1600,
        "height": 800
      },
      {
        "file": "images/service-illustration-services-guide-1200.webp",
        "width": 1200,
        "height": 600
      },
      {
        "file": "images/service-illustration-services-guide-800.webp",
        "width": 800,
        "height": 400
      },
      {
        "file": "images/service-illustration-services-guide-640.webp",
        "width": 640,
        "height": 320
      },
      {
        "file": "images/service-illustration-services-guide-360.webp",
        "width": 360,
        "height": 180
      }
    ]
  }
};
