import fs from 'node:fs/promises';
import path from 'node:path';
const here=new URL('.',import.meta.url),sel=JSON.parse(await fs.readFile(new URL('SELECTION.json',here),'utf8'));
const site=JSON.parse(await fs.readFile(sel.privateStudio+'/sites/madbeauty.json','utf8'));
const media=JSON.parse(await fs.readFile(new URL('MEDIA-PLAN.json',here),'utf8'));
const origin='http://127.0.0.1:8868';
const chosen=new Map(sel.pages.map(i=>[i.pageId,i.planId+'.html']));
for(const p of site.pages.filter(p=>p.publishedRevision&&!chosen.has(p.id)))chosen.set(p.id,'reference-'+p.id+'.html');
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const [id,file] of chosen){
 const p=site.pages.find(p=>p.id===id),r=await fetch(origin+'/preview/madbeauty/'+id);if(!r.ok)throw Error('Native preview failed '+id);
 let html=(await r.text()).replaceAll('/api/media/madbeauty/','assets/').replace('href="/"','href="index.html"').replace('href="/favicon.svg"','href="data:,"');
 html=html.replace(/href="\/preview\/madbeauty\/([^"]+)"/g,(_,target)=>`href="${chosen.get(target)||'index.html#planned'}"`);
 const when=new Intl.DateTimeFormat('lt-LT',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Vilnius'}).format(new Date(p.publishAt));
 const notes=p.factChecks.length?'<details><summary>Likusi patikra prieš publikavimą</summary><ul>'+p.factChecks.map(x=>'<li>'+safe(x)+'</li>').join('')+'</ul></details>':'';
 html=html.replace('</h1>',`</h1><p style="font-size:14px">Autorius: Madbeauty redakcija · Numatyta ${safe(when)} (Lietuvos laiku)</p>${notes}`);
 await fs.writeFile(new URL(file,here),html);
 for(const asset of p.media)await fs.copyFile(sel.privateStudio+'/media/madbeauty/'+path.basename(asset.src),new URL('assets/'+path.basename(asset.src),here));
}
const cards=sel.pages.map(i=>{const p=site.pages.find(p=>p.id===i.pageId),m=media.find(m=>m.pageId===p.id),a=m.imported.variants.find(a=>a.width===640)||m.imported.variants[0];return `<article data-search="${safe((p.title+' '+p.cluster).toLocaleLowerCase('lt'))}"><a href="${safe(chosen.get(p.id))}"><img src="assets/${safe(path.basename(a.src))}" width="${a.width}" height="${a.height}" alt="${safe(a.alt)}" loading="lazy"></a><div><p class="date">${safe(i.localDate)} · ${safe(i.localTime)} · Lietuvos laiku</p><h2><a href="${safe(chosen.get(p.id))}">${safe(p.title)}</a></h2><p>${safe(p.description)}</p><p class="state">${p.publishedRevision?'Patvirtintas; diegimas tikrinamas atskirai':p.factChecks.length?'Tekstas ir nuotrauka parengti; likusi patikra':'Redakcinė patikra atlikta; publikavimo patvirtinimas atskirai'}</p></div></article>`;}).join('');
const html=`<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Madbeauty: 30 papildomų straipsnių</title><style>body{margin:0;background:#f8f5f1;color:#29212a;font:17px/1.55 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:36px 24px}h1{font-size:clamp(2rem,5vw,3.5rem);line-height:1.12;max-width:850px}a{color:#9b2950;text-underline-offset:4px}.intro{max-width:850px}.note{padding:18px;background:#fff;border-left:4px solid #9b2950}input{box-sizing:border-box;width:100%;max-width:600px;padding:14px;border:1px solid #c6b8bb;border-radius:8px;font:inherit;margin:24px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}article{background:#fff;border:1px solid #e0d8d4;border-radius:14px;overflow:hidden}article[hidden]{display:none}article img{width:100%;height:auto;display:block}article div{padding:20px}h2{font-size:1.2rem;line-height:1.3}.date,.state{font-size:14px}.date{color:#70555e}.state{border-top:1px solid #e0d8d4;padding-top:12px}footer{margin-top:35px;font-size:14px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){main{padding:24px 16px}.grid{grid-template-columns:1fr}}</style></head><body><main><p>MADBEAUTY · PARUOŠTA 2026-10-09</p><h1>30 papildomų straipsnių ir 30 skirtingų nuotraukų</h1><div class="intro"><p>Antakiai, blakstienos, vyrų paslaugos, plaukai, depiliacija, nagai, pedikiūras ir praktiniai gidai klientams bei meistrams. Atverk kortelę ir perskaityk visą tekstą.</p><p class="note">Tai privati bendros turinio studijos peržiūra. Datos – esamo kalendoriaus publikavimo akimirkos nuo spalio 29 d. iki gruodžio 2 d., 10:00 arba 16:00 Lietuvos laiku. Teksto parengimas, redakcinė patikra, patvirtinimas ir faktinis įkėlimas turi atskiras būsenas.</p><p>Autorius: <strong>Madbeauty redakcija</strong>. Kainų pavyzdžiai datuoti pagal realių meniu patikrą, o ne pateikti kaip Lietuvos vidurkis. Kai kuriems procedūrų gidams lieka plane nurodyta specialisto patikra; ji parodyta straipsnio pradžioje.</p></div><label for="search">Rasti temą</label><br><input id="search" type="search" placeholder="Pvz., blakstienos, kaina, pedikiūras"><p id="count">30 straipsnių</p><section class="grid">${cards}</section><footer id="planned">Nepublikavus likusių plano temų, jų pasiūlymai išlaikomi privačiame nuorodų plane. Nacionaliniai procedūrų katalogo ID patikrinti; miestų rezultatų ar rezervavimo pasiūlos šis paketas nežada.</footer></main><script>const input=document.querySelector('#search');input.addEventListener('input',()=>{const q=input.value.toLocaleLowerCase('lt');let count=0;for(const a of document.querySelectorAll('article')){a.hidden=!a.dataset.search.includes(q);if(!a.hidden)count++;}document.querySelector('#count').textContent=count+' straipsnių';});</script></body></html>`;
await fs.writeFile(new URL('index.html',here),html);
console.log(JSON.stringify({nativeArticlePreviews:chosen.size,newArticles:sel.pages.length,private:true,productionRenderer:false}));
