import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {optimizeRaster} from '../../../content-studio/src/image-pipeline.mjs';
const sharp=createRequire(new URL('../../../content-studio/package.json',import.meta.url))('sharp');
const root=import.meta.dirname,publicRoot=path.resolve(root,'../prototype/public'),originals=path.resolve(root,'../design-previews/services-assets-20261010/originals');
const specs=JSON.parse(await readFile(path.join(root,'ASSET_INPUTS.json'),'utf8'));
const media=JSON.parse(await readFile(path.join(publicRoot,'media.json'),'utf8'));
const manifest={tool:'built-in image_gen',status:'GENERATED_TRANSPARENT_ILLUSTRATIONS',assets:[]};
await mkdir(originals,{recursive:true});
for(const s of specs){
 const bytes=await readFile(s.sourcePath),stats=await sharp(bytes).stats(),meta=await sharp(bytes).metadata();
 assert.equal(meta.hasAlpha,true,s.id);assert.equal(stats.isOpaque,false,s.id);assert.equal(stats.channels[3].min,0,s.id);
 await copyFile(s.sourcePath,path.join(originals,s.id+'.png'));
 const optimized=await optimizeRaster(bytes,'image/png'),variants=[];
 for(const v of optimized.variants){
  const file='images/service-illustration-'+s.id+'-'+v.width+'.webp';
  await writeFile(path.join(publicRoot,file),v.bytes);
  assert.equal((await sharp(v.bytes).metadata()).hasAlpha,true);
  variants.push({file,width:v.width,height:v.height,bytes:v.bytes.length,sha256:createHash('sha256').update(v.bytes).digest('hex')});
 }
 const record={id:'service-illustration-'+s.id,alt:'',variants};
 const at=media.assets.findIndex(a=>a.id===record.id);if(at<0)media.assets.push(record);else media.assets[at]=record;
 manifest.assets.push({id:s.id,original:'../design-previews/services-assets-20261010/originals/'+s.id+'.png',sha256:createHash('sha256').update(bytes).digest('hex'),width:meta.width,height:meta.height,hasAlpha:true,alphaMin:stats.channels[3].min,alphaMax:stats.channels[3].max,variants});
}
await writeFile(path.join(publicRoot,'media.json'),JSON.stringify(media,null,2)+'\n');
await writeFile(path.resolve(publicRoot,'../services-media.mjs'),'// Responsive illustration map generated by services-design-20261010/import-assets.mjs.\nexport const SERVICES_MEDIA='+JSON.stringify(Object.fromEntries(manifest.assets.map(a=>[a.id,{variants:a.variants.map(({file,width,height})=>({file,width,height}))}])),null,2)+';\n');
await writeFile(path.join(root,'ASSET_MANIFEST.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({assets:manifest.assets.length,variants:manifest.assets.reduce((n,a)=>n+a.variants.length,0),allTransparent:true}));
await import('./provenance.mjs');
