import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
const repo=path.resolve(import.meta.dirname,'../../..'),root=path.join(repo,'sites/madbeauty/cloudflare/output/calendar-private'),json=async name=>JSON.parse(await readFile(path.join(root,name))),manifest=await json('manifest.json'),before=await json('provider-before.json'),after=await json('provider-after.json'),proofs=await Promise.all(['native','hosted','live-before','live-after'].map(async mode=>[mode,await json(mode+'-proof.json')])),browser=await json('browser-views.json'),hash=b=>createHash('sha256').update(b).digest('hex');
assert.deepEqual(before.config,after.config);assert.equal(after.currentDeployment.versions[0].version_id,'4dbdf361-25c6-4496-97a5-daaed23df201');assert.equal(after.currentDeployment.versions[0].percentage,100);
assert.equal(hash(await readFile(path.join(root,'production-worker.mjs'))),manifest.productionArtifactSha256);
for(const [mode,p]of proofs){assert.equal(p.state,'PASS');assert.equal(p.packageSha256,manifest.packageSha256);assert.deepEqual(p.currentProjection,{pages:7,futureBlocked:32,assets:284,served:129,blocked:155});if(['native','hosted'].includes(mode))assert.equal(p.publicationCases.length,64);}
assert.equal(browser.length,6);for(const view of browser){assert.equal(new URL(view.url).origin,'https://madbeauty.lt');assert.ok([390,1440].includes(view.viewport.width));assert.ok(view.document.scroll<=view.document.client);assert.ok(view.main.every(x=>x.scroll<=x.client));assert.ok(view.images.every(x=>x.complete&&x.width>0));if(view.name.includes('future'))assert.deepEqual(view.titles,['Puslapis nerastas']);if(view.name.includes('article'))assert.equal(view.dates[0].datetime,'2026-10-06T17:09:24.272Z');}
const evidence=path.join(import.meta.dirname,'acceptance');await mkdir(evidence,{recursive:true});
for(const [mode]of proofs)await copyFile(path.join(root,mode+'-proof.json'),path.join(evidence,mode+'-proof.json'));
await copyFile(path.join(root,'browser-views.json'),path.join(evidence,'browser-views.json'));
const screenshots=[];for(const view of browser){const name=view.name+'.png',bytes=await readFile(path.join(root,name));await copyFile(path.join(root,name),path.join(evidence,name));screenshots.push({name,sha256:hash(bytes)});}
const receipt={recordedAt:new Date().toISOString(),state:'canonical-date-only-release-accepted',domain:'https://madbeauty.lt',releaseSource:execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),runtimeSource:manifest.runtimeSource,coreSource:manifest.coreSource,packageSource:manifest.packageSource,packageSha256:manifest.packageSha256,previousPackageSha256:'75aa78c1109f046a54ec03354dcf677c2a3af619ce549d5e59cf6ce514f806c4',rendererSha256:manifest.rendererSha256,producerReviewedRendererSha256:manifest.producerReviewedRendererSha256,productionArtifactSha256:manifest.productionArtifactSha256,productionVersion:after.currentDeployment.versions[0].version_id,previousProductionVersion:before.currentDeployment.versions[0].version_id,deployedAt:after.currentDeployment.created_on,fullPlatformUpgradeDeployed:false,package:{pages:39,guides:35,dateChangedFutureGuides:25,unchangedApprovedPages:14,unchangedAssets:180,futureGuides:32,unwrittenPlanIsNotPublishedContent:true},acceptance:Object.fromEntries(proofs.map(([mode,p])=>[mode,{state:p.state,publicationStates:p.publicationCases.length,gateChecks:p.gateChecks.length,...p.currentProjection,receiptSha256:hash(JSON.stringify(p,null,2))}])),productionConfiguration:{unchanged:true,namespaceId:after.config.bindings.find(b=>b.name==='PLATFORM').namespaceId,className:'MadbeautyPlatform',migrationTag:after.config.migrationTag,compatibilityDate:after.config.compatibilityDate,compatibilityFlags:after.config.compatibilityFlags,domainAssignments:after.config.domains.map(x=>x.hostname),plainVars:after.config.bindings.filter(b=>b.type==='plain_text').map(b=>({name:b.name,text:b.text})),secretNames:after.config.bindings.filter(b=>b.type==='secret_text').map(b=>b.name),observabilityUnchanged:true},qa:{version:'2b39ad0a-e114-4793-919f-cc38ef20f2b1',namespaceId:after.qa.bindings.find(b=>b.namespaceId).namespaceId,clockHookOnlyInQa:true,noSmtpBindings:true},screenshots,scope:'Private simulated future-clock acceptance is distinct from real canonical current-time HTTP and browser acceptance. No full platform upgrade, provider admission, customer write, retention erasure, mail test, DNS or storage handoff performed.'};
await writeFile(path.join(import.meta.dirname,'RECEIPT.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify({state:receipt.state,version:receipt.productionVersion,packageSha256:receipt.packageSha256,browserViews:browser.length,source:receipt.releaseSource}));
