// Authored editorial input; publication and media use the shared studio model.
const p = text => ({type:'paragraph',text});
const h = text => ({type:'heading',level:2,text});
const l = (...items) => ({type:'list',items});
export const articles = {
  'PS-20': [
    p('Parašo planšetės kainą verta lyginti kartu su programine įranga, priedais ir diegimo darbais. Du vienodai kainuojantys įrenginiai gali reikšti skirtingą viso pasirašymo proceso sąmatą. Šiame puslapyje pateikiame sąmatos ruošinį; konkrečios kainos ir tiekimo sąlygos patvirtinamos atskirame pasiūlyme.'),
    h('Ką įrašyti į palyginamą sąmatą'),
    l('Įranga: tikslus StepOver modelis, kiekis ir komplekte esantis rašiklis bei kabelis.','Programos: pavadinimas, licencijos vienetas, galiojimas ir atnaujinimų sąlygos.','Priedai: tinklo jungtis, tvirtinimas ar atsarginis rašiklis tik tada, kai jų reikia konkrečiam modeliui.','Darbai: dokumento šablono paruošimas, įdiegimas, integracija, bandymas ir darbuotojų mokymas.','Tęstinės išlaidos: prenumeratos, sutarta priežiūra, atsarginė įranga ir dokumentų saugojimas.','Mokesčiai ir pristatymas: aiškiai atskirtos sumos be PVM, PVM ir galutinė mokėtina suma.'),
    h('Darbo vieta nėra tas pats, kas įrenginių skaičius'),
    p('Pavyzdys: dvi aptarnavimo vietos naudojasi ta pačia verslo sistema. Reikia patikrinti ne vien dviejų planšečių kainą, bet ir tai, kas įdiegta kiekviename kompiuteryje, kur vyksta pasirašymas ir kaip licencijuojama pasirinkta programa. Vienas bendras serveris automatiškai nereiškia vienos licencijos.'),
    h('Kaip vertinti atsipirkimą'),
    p('Savo procese užrašykite dokumentų kiekį, spausdinimo ir skenavimo laiką, popieriaus sąnaudas ir dokumento paieškos laiką. Palyginimas prasmingas tik tada, kai įskaičiuoti naujo proceso darbai ir likę rankiniai veiksmai. Sutaupymo procento be jūsų duomenų apskaičiuoti negalima.'),
    h('Klausimai prieš priimant pasiūlymą'),
    l('Ar šiuo komplektu galima gauti, patikrinti ir išsaugoti mano dokumentą?','Kas į kainą neįtraukta ir kiek kainuotų papildoma darbo vieta?','Kokios licencijų pratęsimo, garantijos ir palaikymo sąlygos?','Kaip bus užfiksuotas priėmimas, jei bandomas dokumentas nepraeis visos eigos?'),
    p('Užklausai paruoškite dokumento rūšį, darbo vietų skaičių, programą, operacinę sistemą ir pasirašymo būdą. Galite naudotis StepOver modelių palyginimu ir pasirašymo piloto sąrašu, o komplekto poreikį pateikti per kontaktų puslapį.')
  ],
  'PS-21': [
    p('Pasirašymo sprendimą renkame pagal dokumento kelią ir žmonių darbo aplinką. Įmonės veiklos sektorius vienas pats nepasako, ar reikia parašo planšetės, nuotolinio pasirašymo, ar abiejų būdų. Šis žemėlapis padės pasirinkti, kurį procesą vertinti pirmiausia.'),
    h('Pradėkite nuo vieno dokumento'),
    l('Kas jį parengia ir kur yra galutinė versija?','Kas skaito ir pasirašo: klientas, darbuotojas, partneris ar keli žmonės?','Ar visi dalyviai yra vienoje vietoje?','Kokį parašo lygį ir dokumento formą reikia užtikrinti?','Kam perduodama kopija ir kur saugomas originalus elektroninis failas?'),
    h('Aptarnavimo vietoje'),
    p('Kai klientas atvyksta fiziškai, parašo planšetė gali būti darbo vietos dalis. Prieš pasirinkdami modelį nustatykite, ar klientas turi perskaityti visą dokumentą planšetėje, ar skaito atskirame ekrane. Sutarčių pasirašymo gidas nagrinėja peržiūrą ir patvirtinimą; perdavimo aktų gidas — objektą, būklę ir išimtis.'),
    h('Darbuotojai, formos ir išvykos'),
    p('Personalo dokumentuose svarbi dokumento rūšis, darbuotojo prieiga ir kopijos pateikimas. Sutikimų bei formų procese atskirkite duomenų užpildymą nuo patvirtinimo. Išvykose papildomai įvertinkite elektros, ryšio, gabenimo ir laikino failų saugojimo sąlygas. Šie klausimai aptarti atskiruose procesuose.'),
    h('Nuotolinis ir mišrus kelias'),
    p('Kai žmonės nesusitinka, vien USB planšetė neišsprendžia kvietimo, tapatybės ir dokumento grąžinimo. Mišriame procese dalis žmonių gali pasirašyti vietoje, kiti — nuotoliu. Sprendimo kriterijai aprašyti vietinio ir nuotolinio pasirašymo palyginime.'),
    h('Proceso aprašo ruošinys'),
    l('Dokumentas ir jo savininkas: …','Dalyviai bei jų vieta: …','Peržiūros ir patvirtinimo veiksmas: …','Reikalingas parašo lygis: …','Galutinio failo gavėjas ir saugykla: …','Kas laikoma sėkmingu bandymu: …'),
    p('Tai atrankos metodas, o ne įrodymas, kad kiekvienas procesas jau integruotas. Pateikite proceso aprašą per kontaktų puslapį; jautrių klientų dokumentų pradinei užklausai siųsti nereikia.')
  ],
  'PS-42': [
    p('Ranka parašytas parašas planšetės ekrane savaime nėra kvalifikuotas elektroninis parašas. Reikia vertinti visą parašo kūrimo sistemą ir konkretaus dokumento reikalavimus. Įrenginio modelis ar matomas parašo vaizdas šio vertinimo nepakeičia.'),
    h('Trys skirtingi klausimai'),
    l('Vaizdas: ar dokumente tik įdėta grafinė parašo kopija?','Elektroninis parašas: kaip parašas susietas su dokumentu ir pasirašančiu asmeniu?','Kvalifikuotas parašas: ar naudojamas kvalifikuotas sertifikatas ir kvalifikuotas parašo kūrimo įtaisas?'),
    h('Ką nustato eIDAS'),
    p('eIDAS 25 straipsnis numato, kad elektroniniam parašui negalima atsisakyti teisinės galios ar įrodomosios reikšmės vien todėl, kad jis elektroninis arba nekvalifikuotas. Kvalifikuotam elektroniniam parašui suteikiama ranka rašyto parašo teisinė galia. Tai nereiškia, kad bet koks planšete sukurtas parašas tinka bet kuriam dokumentui.'),
    h('Dokumento reikalavimų klausimynas'),
    l('Kokia dokumento rūšis ir taikoma teisė?','Ar teisės aktas, institucija arba kita sutarties šalis reikalauja konkretaus parašo lygio?','Kaip nustatoma pasirašančiojo tapatybė ir jo teisė atstovauti?','Kaip įrodomas ryšys su galutine dokumento versija?','Kaip parašas bus tikrinamas ir kas spręs ginčą?'),
    h('Ką tikrinti techniniame bandyme'),
    p('Naudokite sintetinį dokumentą. Patikrinkite, kokią informaciją apie parašą parodo PDF tikrinimo įrankis, ar po pakeitimo fiksuojamas dokumento vientisumo pasikeitimas ir ar gavėjas gali atlikti tokią pat patikrą. Vizualiai tvarkingas parašas nėra šio bandymo pakaitalas.'),
    p('Jei dokumentui reikia kvalifikuoto parašo, tą reikalavimą nurodykite prieš įrangos atranką. Šis gidas paaiškina pasirinkimo klausimus; konkretaus dokumento teisinį tinkamumą vertina už jį atsakingas specialistas. Duomenų tvarkymą aptaria parašo duomenų ir privatumo gidas.')
  ],
  'PS-22': [
    p('eSignatureOffice yra StepOver programa PDF pasirašymo darbui Windows kompiuteryje. Ją verta vertinti, kai reikia valdomos dokumento peržiūros, parašo laukų ir galutinio failo perdavimo. Konkrečios versijos, įrenginio ir licencijos derinys turi būti patikrintas prieš pirkimą.'),
    h('Programos vieta dokumento kelyje'),
    p('Gamintojas aprašo PDF peržiūrą, formų pildymą, parašo laukų valdymą ir automatizuotą išsaugojimą. Mūsų siūlomas bandymas pradedamas nuo jūsų dokumento kopijos be asmens duomenų: atidaryti, perskaityti, pasirašyti, išsaugoti ir vėl atidaryti gavėjo aplinkoje.'),
    h('Ką paruošti bandymui'),
    l('Windows versiją ir kompiuterio architektūrą.','Tikslų StepOver įrenginio pavadinimą ir ryšio kelią.','Vieno ir kelių puslapių bandomus PDF.','Privalomus ir pasirenkamus parašo laukus.','Failo pavadinimo, katalogo ir prieigos taisyklę.','Kas tikrina rezultatą ir kaip grįžta patvirtinimas į verslo sistemą.'),
    h('Šablonas padeda, bet turi būti priimtas'),
    p('Pavyzdžiui, įmonė nori failą pavadinti pagal sutarties numerį. Patikrinkite ne tik teisingą numerį, bet ir atvejį, kai numerio nėra, jis pasikartoja arba išsaugojimo katalogas nepasiekiamas. Klaida neturi palikti neaiškumo, ar dokumentas jau galutinai pasirašytas.'),
    h('Serveris ir naršyklė — atskira apimtis'),
    p('Gamintojas terminalinei aplinkai nurodo papildomus TCP ir Citrix modulius. Tai nepakeičia konkrečios sesijų aplinkos patikros. Naršyklės inicijuojamas procesas taip pat turi atskirai nustatytą vietinio komponento, saugos ir teisių kelią.'),
    h('Priėmimo įrašas'),
    l('Dokumento versija ir programos versija.','Atlikti veiksmai ir galutinio PDF vieta.','Tikrinimo rezultatas bei likusios išimtys.','Licencijos apimtis ir atsakingas palaikymo kontaktas.'),
    p('Programos funkcijų aprašas nėra mūsų atliktos integracijos rezultatas. Į užklausą įtraukite aplinką ir dokumento kelią; platesnį pasirinkimą rasite programinės įrangos apžvalgoje.')
  ],
  'PS-23': [
    p('Print2NG yra virtualus spausdintuvo tvarkyklės kelias dokumentui perduoti į StepOver NextGen serijos planšetę. Jis aktualus, kai dokumentas jau kuriamas programoje, galinčioje spausdinti. Paspaudus spausdinimą dar reikia patikrinti pasirašyto PDF grįžimą ir saugojimą.'),
    h('Kokią problemą sprendžia šis kelias'),
    p('Gamintojo aprašyta eiga leidžia iš spausdinančios programos perduoti dokumentą NG įrenginiui ir gauti pasirašytą failą. Tai atskiras kelias nuo savarankiškos API integracijos. Negalima iš pavadinimo spręsti, kad jis tinka kiekvienam senesniam StepOver modeliui.'),
    h('Penki žingsniai priėmimui'),
    l('Šaltinio programa: sugeneruokite vieno ir kelių puslapių dokumentą.','Spausdinimo nustatymai: patikrinkite puslapio dydį, orientaciją ir tai, ar neliko nukirsto teksto.','Planšetė: patikrinkite, ar klientas mato būtent tą dokumentą, kurį parengė operatorius.','Pasirašymas: įtraukite patvirtinimo ir atsisakymo scenarijus.','Grąžinimas: suraskite galutinį PDF, patikrinkite jo turinį ir prieigos teises.'),
    h('Kas turi būti patikslinta pasiūlyme'),
    p('Nurodykite NG modelį, operacinę sistemą, procesoriaus architektūrą ir dokumentą kuriančią programą. Gamintojo reikalavimuose Windows x86/x64 ir ARM aplinkos skiriamos; vien Windows pavadinimo nepakanka. Programos suderinamumą vertinkite pagal aktualią versiją.'),
    h('Dažna spraga: dokumentas pasirašytas, bet nerastas'),
    p('Bandomame procese sąmoningai pakeiskite išsaugojimo vietą ir panaudokite vienodus dokumentų pavadinimus. Nuspręskite, kaip bus užkertamas kelias perrašyti kitą failą ir kaip operatorius supras, kad išsaugojimas nepavyko. Tai siūlomi patikros scenarijai, ne mūsų atliktas bandymas.'),
    p('Jei pasirašymo pradžią ar grąžinimą turi valdyti verslo sistema, palyginkite Print2NG su StepOver API pasirinkimu. Komplektui vertinti pateikite savo šaltinio programą ir galutinio failo gavėją.')
  ],
  'PS-27': [
    p('Parašo planšetė yra konkretaus pasirašymo proceso įrenginys; įprastas planšetinis kompiuteris — bendros paskirties kompiuteris. Abu gali dalyvauti dokumentų pasirašyme, tačiau pasirinkimą lemia programa, dokumento rodymas, duomenų kelias ir valdymas, o ne vien ekranas.'),
    h('Palyginkite pagal užduotį'),
    l('Fizinė aptarnavimo vieta: kas pateikia dokumentą ir ar klientas gali išeiti iš pasirašymo aplinkos?','Dokumento skaitymas: kur matomas visas tekstas ir kaip pereinama tarp puslapių?','Įvestis: ar reikia tik parašo, ar ir laukų užpildymo?','Valdymas: kas diegia atnaujinimus, suteikia prieigą ir atkuria įrenginį?','Failas: kokį rezultatą gauna verslo sistema ir kaip jis patikrinamas?'),
    h('Kada verta atskira parašo darbo vieta'),
    p('Jei tas pats operatorius nuolat pateikia dokumentus atvykstantiems klientams, atskiras įrenginys gali padėti aiškiai atskirti darbuotojo ir kliento veiksmus. Vis dėlto negalima numanyti, kad kiekviena parašo planšetė savarankiškai atidaro PDF ar jungiasi prie tinklo: tikrinkite konkretų modelį.'),
    h('Kada vertinti bendros paskirties įrenginį'),
    p('Kai žmogus dirba išvykose, naudojasi keliomis programomis ar pasirašo nuotoliu, bendros paskirties planšetė gali būti tinkama esamos sistemos dalis. Reikia įvertinti paskyras, bateriją, internetą, duomenų išvalymą ir atsisakymo kelią. Vien įsigyti rašiklį nepakanka.'),
    h('Savo palyginimo ruošinys'),
    l('Turimas dokumentas ir dalyviai: …','Reikalingas parašo lygis: …','Peržiūros ir įvesties vieta: …','Programinis bei ryšio kelias: …','Įrenginio administravimas: …','Galutinio PDF patikra ir saugojimas: …'),
    p('Abu variantus lyginkite tuo pačiu bandomu dokumentu ir tuo pačiu priėmimo sąrašu. StepOver modelių palyginimas padeda įvertinti specializuotą įrangą; vietinio ir nuotolinio pasirašymo gidas — pasirinkti proceso kryptį.')
  ],
  'PS-28': [
    p('Prieš perkant įrangą verta patikrinti vieną visą dokumento kelią: nuo parengimo iki galutinio failo gavimo, patikros ir archyvavimo. Pilotas turi aiškius priėmimo kriterijus. Gražus parašas ekrane vienas pats neįrodo, kad procesas tinka jūsų verslui.'),
    h('Apribokite pirmą bandymą'),
    p('Pasirinkite vieną dokumento rūšį, vieną darbo vietos aplinką ir atsakingą asmenį. Naudokite sintetinį dokumentą, kurio laukai atspindi tikrą šabloną, bet jame nėra klientų duomenų. Bandymo apimtį suderinkite prieš skaičiuodami plėtrą.'),
    h('Bandymo protokolo ruošinys'),
    l('Aplinka: modelis, programa, versija, operacinė sistema ir ryšys.','Dokumentas: ID, šablono versija, puslapių skaičius ir pasirašytojai.','Veiksmas: kas parengia, perskaito, pasirašo ir patvirtina.','Rezultatas: galutinio failo vieta, tikrinimo rezultatas ir kliento kopija.','Išimtis: kas vyksta atsisakius, nutrūkus ryšiui ar nepavykus išsaugoti.','Sprendimas: priimta, reikia taisyti ar šiam procesui netinka.'),
    h('Patikrinkite ne tik sėkmingą atvejį'),
    l('Klientas atsisako prieš parašą ir po jo, bet prieš galutinį patvirtinimą.','Trūksta privalomo lauko arba pridėtas naujas puslapis.','Du dokumentai turi tą patį pavadinimą.','Saugykla nepasiekiama arba naudotojas neturi rašymo teisės.','Sesija nutrūksta ir operatorius vėliau grįžta prie darbo.','Kitas darbuotojas turi surasti ir patikrinti galutinį failą.'),
    h('Kaip nuspręsti dėl plėtros'),
    p('Užrašykite faktines klaidas ir likusius rankinius veiksmus. Priėmimą pasirašo už dokumentų procesą ir IT aplinką atsakingi žmonės. Tik tada vertinkite daugiau darbo vietų, mokymą ir palaikymo apimtį. Šis protokolas siūlomas jūsų bandymui; čia neskelbiame neatlikto kliento piloto rezultatų.'),
    p('Užklausai pateikite proceso aprašą ir priėmimo kriterijus. Jautrių dokumentų nereikia. Kainos gidas padeda atskirti piloto, įrangos ir tolesnės plėtros sąnaudas.')
  ],
  'PS-35': [
    p('Vietinį pasirašymą rinkitės pagal fizinio aptarnavimo poreikį, nuotolinį — pagal dalyvių atstumą ir tapatybės patikrą. Mišrus kelias reikalingas, kai tas pats dokumentas turi kelis skirtingose vietose esančius pasirašytojus. Reikalingas parašo lygis vertinamas kiekvienam keliui.'),
    h('Vietoje: svarbu dokumento pateikimas'),
    p('Operatorius parengia dokumentą, klientas jį perskaito ir pasirašo pasirinktoje aplinkoje. Nustatykite, kur klientas mato visą tekstą, kas gali taisyti duomenis ir kada versija laikoma galutine. Vienas ekrano dydis nėra viso proceso pasirinkimas.'),
    h('Nuotoliu: svarbu dalyvio pasiekimas'),
    p('Reikia nustatyti kvietimo, prisijungimo, tapatybės, dokumento peržiūros, atsisakymo ir rezultatų gavimo kelią. Prieš renkantis paslaugą klauskite, kur tvarkomi duomenys, kaip administruojami dalyviai ir kokios konkrečios sutarties sąlygos. Nuotolinis nereiškia automatiškai kvalifikuotas.'),
    h('Mišriai: svarbu ta pati dokumento versija'),
    p('Pavyzdys: klientas pasirašo aptarnavimo vietoje, vadovas patvirtina vėliau. Abu turi gauti sutartą dokumento versiją. Iš anksto nustatykite eilę ir ką daryti, jei tarp parašų būtina pakeisti turinį. Du atskirai pasirašyti skirtingi PDF nėra tas pats, kas priimtas bendras procesas.'),
    h('Atrankos matrica savo poreikiui'),
    l('Dalyvių vieta ir galimybė naudotis įrenginiu.','Dokumento rūšis ir parašo reikalavimas.','Asmens bei atstovavimo teisės nustatymas.','Peržiūros, taisymo ir atsisakymo veiksmai.','Kelių parašų eilė ir galutinės versijos savininkas.','Kopijos, saugojimo ir techninės pagalbos kelias.'),
    p('Pirma aprašykite procesą, tada lyginkite programą ar įrenginį. StepOver programų apžvalga skiria vietinius ir debesijos kelius; pasirašymo piloto sąrašas padeda vienodai patikrinti pasirinktą variantą. Paslaugos aktyvavimas ir mūsų pasiūlymas derinami atskirai.')
  ],
  'PS-44': [
    p('StepOver API kelią rinkitės pagal tai, ar jūsų sistema turi valdyti parašo duomenų surinkimą, visą PDF pasirašymą, NG įrenginį ar debesijos procesą. Šios užduotys nėra tapačios. Gamintojo sąsajos pavadinimas dar nepatvirtina suderinamumo su jūsų programa.'),
    h('Atskirkite integracijos ribą'),
    p('Gamintojo kataloge Signature API, Device API, NextGen API ir webSignatureOffice API pateikiamos kaip skirtingos sąsajos. Prieš renkantis SDK užrašykite įėjimą ir išėjimą: PDF, parašo duomenys, proceso būsena ir galutinis failas. Tai padės nepasirinkti vien įrenginio valdymo, kai reikia viso dokumento proceso.'),
    h('Klausimynas programuotojui'),
    l('Kur vykdomas kodas: darbuotojo kompiuteryje, serveryje ar naršyklėje?','Kokį modelį ir programos versiją reikia palaikyti?','Kas pateikia PDF ir kas turi teisę jį pakeisti?','Kaip identifikuojamas dokumentas ir kiekvienas pasirašymo bandymas?','Kaip grąžinama sėkmė, atsisakymas, klaida ir galutinis failas?','Kaip tvarkomi raktai, teisės, logai ir duomenų saugojimas?'),
    h('Minimalus integracijos priėmimas'),
    p('Pasirinkite sintetinį kelių puslapių PDF. Patikrinkite normalų pasirašymą, atšaukimą, ryšio nutrūkimą ir pakartotinį tos pačios užklausos siuntimą. Sistema turi aiškiai atskirti nebaigtą bandymą nuo galutinio dokumento. Pakartotas atsakymas neturi būti laikomas nauju kliento parašu.'),
    h('Kas lieka už API ribos'),
    p('API savaime nepasirenka dokumento teisinio reikalavimo, nepatvirtina atstovavimo ir nenustato archyvavimo termino. Šias atsakomybes suderinkite su dokumentų ir IT proceso savininkais. Licencijavimą bei konkrečias palaikomas aplinkas patvirtinkite aktualioje sąsajos dokumentacijoje.'),
    p('Integracijos užklausai pateikite šiuos įėjimo, išėjimo ir aplinkos duomenis. Naršyklės kelias paaiškintas atskirame gide; bendras integracijos puslapis padeda paruošti darbų apimtį.')
  ],
  'PS-29': [
    p('Kelių padalinių pasirašymo procesą verta pradėti nuo vieno priimto dokumento kelio ir tik tada kartoti jį kitose vietose. Įrangos kiekis, aktyvios darbo vietos, bendros sistemos ir licencijos turi būti skaičiuojamos atskirai.'),
    h('Padalinio inventoriaus ruošinys'),
    l('Padalinys ir proceso atsakingas žmogus.','Darbo vietos, vienu metu pasirašantys žmonės ir įrenginių modeliai.','Kompiuterių bei programų versijos.','Dokumentų šablonai ir jų savininkas.','Saugykla, kopijos perdavimas ir prieigos.','Ryšio sutrikimo bei įrenginio pakeitimo veiksmai.'),
    h('Vienodas procesas, skirtingos sąlygos'),
    p('Pavyzdys: pirmame padalinyje dokumentas gaunamas iš vietinės programos, antrame — iš terminalinės sesijos. Vienodas planšetės modelis dar neleidžia laikyti abiejų aplinkų priimtomis. Kiekvieną ryšio ir programos kelią reikia patikrinti, net jei dokumento forma ta pati.'),
    h('Kaip valdyti šablonų versijas'),
    p('Paskirkite vieną vietą patvirtintam šablonui ir užrašykite jo versiją. Prieš platinant pakeitimą atlikite bandymą su nauju puslapių išdėstymu ir parašo laukais. Padaliniai turi žinoti, kada nauja versija įsigalioja ir ką daryti su pradėtais ankstesnės versijos dokumentais.'),
    h('Plėtros priėmimo sąrašas'),
    l('Kiekvienoje skirtingoje aplinkoje atliktas visas PDF kelias.','Darbuotojai gali atpažinti nebaigtą ir galutinį dokumentą.','Naudotojo pakeitimas neatskleidžia kito kliento dokumentų.','Saugykla turi sutartas prieigas ir veikiantį atkūrimo kelią.','Aiški atsarginio įrenginio ir palaikymo atsakomybė.'),
    p('Kainos pasiūlyme prašykite atskirti įrangą, programų licencijas, pirmo padalinio parengimą ir likusių vietų plėtrą. Integracijos ir piloto gidai padės paruošti techninę dalį. Palaikomų padalinių skaičiaus ar diegimo termino be apimties nežadame.')
  ],
  'PS-30': [
    p('Sutartį aptarnavimo vietoje klientas turi galėti perskaityti prieš pasirašydamas, o verslas — išsaugoti ir pateikti galutinę versiją. Parašo planšetė gali pakeisti parašo įvedimo veiksmą, bet ne sutarties turinio, tapatybės ir kopijos perdavimo atsakomybes.'),
    h('Atskirkite parengimą nuo patvirtinimo'),
    p('Operatorius užpildo sutartį, patikrina kliento duomenis ir pateikia dokumentą skaityti. Nuspręskite, kuriame ekrane matomas visas tekstas ir kaip klientas grįžta prie ankstesnio puslapio. Jeigu prašoma pakeitimo, parašui turi būti pateikta jau patikslinta versija.'),
    h('Aptarnavimo darbo vietos sąrašas'),
    l('Aiškus dokumento pavadinimas, numeris ir versija.','Klientui prieinama visa sutartis ir jos priedai.','Sutartas tapatybės bei atstovavimo tikrinimas.','Matomas atsisakymo ar taisymo veiksmas.','Aiškus galutinis patvirtinimas ir failo išsaugojimo rezultatas.','Kliento kopijos gavimo būdas.'),
    h('Pavyzdys: ilgalaikės paslaugos sutartis'),
    p('Tai iliustracinis scenarijus. Klientas perskaito sutartį ir kainų priedą, paprašo pataisyti paslaugos pradžios datą. Operatorius pataiso dokumentą ir pateikia naują versiją. Turi būti aišku, kuri versija pasirašyta ir kaip klientas gauna būtent ją, o ne pradinį juodraštį.'),
    h('Ką bandyti prieš naudojimą'),
    l('Ilgą sutartį su priedu ir skirtinga puslapių orientacija.','Pataisymą prieš parašą ir atsisakymą po dokumento peržiūros.','Galutinio PDF radimą iš kito darbuotojo paskyros.','Kopijos išsiuntimo klaidą ir jos pakartojimą be naujo parašo.'),
    p('Dokumento rūšies ir parašo lygio reikalavimai vertinami atskirai. Pasirašymo proceso apžvalga padeda paruošti apimtį, o dokumento kopijos gidas — užbaigti kliento kelią. Užklausoje nurodykite sutarties tipą ir turimą programą.')
  ],
  'PS-31': [
    p('Perdavimo ir priėmimo akte svarbu užfiksuoti ne tik parašą, bet ir tai, kas perduota, kada, kokios būklės bei su kokiomis išimtimis. Skaitmeninis procesas turi išsaugoti šį turinį kartu su galutiniu dokumentu ir jo priedais.'),
    h('Akto turinio ruošinys'),
    l('Perduodamo objekto arba paslaugos identifikatorius.','Šalių duomenys ir atstovavimo pagrindas, kai jo reikia.','Perdavimo vieta, data ir faktinė būklė.','Kiekis, komplektacija ir pastebėti trūkumai.','Priedai, jų identifikatoriai ir ryšys su aktu.','Priėmimas, atsisakymas ar priėmimas su išlyga.'),
    h('Pastaba nėra vien techninis laukas'),
    p('Pavyzdys: perduodamas nuomos įrenginys su pastebėtu korpuso pažeidimu. Gavėjas turi matyti pastabą ir susietus priedus prieš patvirtindamas. Jei proceso programa leidžia tik parašą ant jau parengto PDF, pastabą reikia įtraukti į dokumentą prieš pradėjus pasirašymą.'),
    h('Atskirkite dokumentą ir pridėtą nuotrauką'),
    p('Nuotrauka be aiškaus ryšio su akto numeriu gali pasimesti. Apibrėžkite, ar priedai įtraukiami į galutinį PDF, ar saugomi atskirai ir kaip juos galima surasti. Nevadinkite atskirai laikomo priedo pasirašyto dokumento dalimi, jei jūsų sistema tokio ryšio neužtikrina.'),
    h('Priėmimo patikra'),
    l('Patikrinkite vieną aktą su išlyga ir vieną atsisakymo atvejį.','Įsitikinkite, kad pataisius būklę iš naujo pateikiama teisinga versija.','Patikrinkite abiejų šalių kopijas ir priedų paiešką.','Užrašykite, kas sprendžia neužbaigto akto ir ryšio klaidos atvejį.'),
    p('Tai proceso parengimo sąrašas, ne universali konkrečios sutarties teisinė forma. Kelių pasirašytojų ir dokumentų saugojimo gidai padeda užbaigti techninę dalį. Pateikite akto tipą, aplinką ir priedų poreikį per kontaktų puslapį.')
  ],
  'PS-36': [
    p('Keliems žmonėms pasirašant vieną PDF svarbiausia sutarta eilė, kiekvienam pateikta dokumento versija ir aiški galutinio failo būsena. Parašų skaičius ekrane neparodo, ar baigtas visas dokumento procesas.'),
    h('Sudarykite pasirašytojų ir laukų sąrašą'),
    l('Kas pasirašo ir kokiu pagrindu atstovauja?','Kuris laukas skirtas kiekvienam dalyviui?','Kurie parašai būtini, o kurie pasirenkami?','Ar dalyviai pasirašo iš eilės, ar proceso programa leidžia kitą tvarką?','Kas užbaigia procesą ir gauna galutinį failą?'),
    h('Pavyzdys: klientas ir įmonės atstovas'),
    p('Tai iliustracinis scenarijus. Klientas pasirašo pirmas, įmonės atstovas — vėliau. Pradžioje pažymėkite, kad dokumentas laukia antro parašo. Kai abu dalyviai baigia, patikrinkite galutinį PDF ir pateikite jo kopiją. Neužbaigto failo nesiųskite kaip galutinės sutarties vien todėl, kad jame jau matomas kliento parašas.'),
    h('Ką daryti prireikus pataisos'),
    p('Po pirmo parašo turinio keitimas nėra paprastas šablono taisymas. Nustatykite, ar leidžiamas pakeitimas, kaip jis atsispindi parašo tikrinime ir ar reikia pradėti naujos versijos pasirašymą. Negalima pažadėti, kad kiekviena PDF programa išlaiko visų ankstesnių parašų galiojimą.'),
    h('Priėmimo scenarijai'),
    l('Antras dalyvis atsisako arba nebaigia darbo.','Tas pats pasirašytojas bando pasirašyti du kartus.','Pasirenkamas parašas praleidžiamas.','Sesija nutrūksta tarp dviejų parašų.','Galutinis PDF atidaromas gavėjo tikrinimo programoje.'),
    p('Užrašykite dalyvių eilę ir dokumento būsenas prieš pasirinkdami programą. PDF šablonų ir parašo patikros gidai padeda patikrinti laukus bei rezultatą. Konkrečias programos galimybes reikia priimti su jūsų dokumentu.')
  ],
  'PS-37': [
    p('Pasirašytą PDF tikrinkite pagal parašo informaciją ir dokumento vientisumo rezultatą, o ne tik pagal matomą grafinį parašą. Perspėjimas gali reikšti skirtingus dalykus: nepatikimą sertifikatą, pakeistą turinį ar tikrinimo aplinkos ribą. Priežastį reikia perskaityti tikrinimo įrankyje.'),
    h('Patikros protokolas'),
    l('Išsaugokite gautą failą nekeisdami jo turinio.','Atverkite PDF programoje, kuri palaiko elektroninių parašų patikrą.','Perskaitykite kiekvieno parašo būseną ir detales.','Atskirkite dokumento pakeitimo informaciją nuo sertifikato pasitikėjimo klausimo.','Užrašykite tikrinimo programą, versiją, laiką ir tikslų perspėjimą.','Jei rezultatas neaiškus, perduokite informaciją atsakingam žmogui, o ne savarankiškai patvirtinkite parašą.'),
    h('Trys dalykai, kurių nereikia suplakti'),
    p('Matomas parašo vaizdas rodo grafinį elementą. Tikrinimo programa gali pateikti informaciją apie elektroninį parašą ir failą. Kvalifikuoto parašo vertinimui reikia jo konkrečių savybių bei patikimų šaltinių. Vien žalias ženklas vienoje programoje nepakeičia dokumento reikalavimo įvertinimo.'),
    h('Kaip perduoti problemą palaikymui'),
    p('Nurodykite failo sukūrimo aplinką, StepOver modelį, pasirašymo programos ir tikrinimo programos versijas. Pridėkite tikslų klaidos tekstą. Jei galima, naudokite sintetinį dokumentą, kuriame klaida atkartojama. Nesiųskite klientų parašų ar jautrių dokumentų į bendrą užklausą.'),
    h('Savo bandymui'),
    p('Patikrinkite tą patį bandomą PDF siuntėjo ir gavėjo aplinkoje. Užrašykite, ar rezultatai sutampa ir kokių pasitikėjimo ar tinklo nustatymų reikia. Tai siūlomas priėmimo metodas; šis puslapis nepatvirtina konkretaus jūsų failo galiojimo.'),
    p('Parašo lygius paaiškina parašo galiojimo gidas. Dokumento saugojimo gidas padeda išlaikyti originalų elektroninį failą, kad vėliau būtų įmanoma jį tikrinti.')
  ],
  'PS-39': [
    p('Klientui perduokite galutinę pasirašyto dokumento versiją, o siuntimo sėkmę tikrinkite atskirai nuo pasirašymo sėkmės. Vien programos pranešimas „išsiųsta“ dar neparodo, kad klientas gavo teisingą failą.'),
    h('Pasirinkite perdavimo būdą'),
    l('El. paštas: tikrinamas gavėjo adresas, priedas ir pristatymo klaidos.','Kliento paskyra: aišku, kas gali prisijungti ir kiek laiko dokumentas prieinamas.','Sutartas atsisiuntimas: ribojama prieiga ir paaiškinama, kaip išsaugoti kopiją.','Spausdinta kopija: nustatoma jos paskirtis; ji neatstoja originalaus elektroninio failo parašo patikros.'),
    h('Gavėjo patikra prieš siuntimą'),
    p('Aptarnavimo metu paprašykite klientą patikrinti adresą. Jei dokumente yra jautrios informacijos, vien įprasto el. pašto gali nepakakti — perdavimo priemones nustato proceso ir duomenų apsaugos atsakingi asmenys. Siuntimo kanalą pasirinkite pagal dokumentą, o ne pagal patogumą operatoriui.'),
    h('Perdavimo įrašo ruošinys'),
    l('Dokumento ID ir galutinė versija.','Gavėjas ir pasirinktas kanalas.','Siuntimo arba suteiktos prieigos laikas.','Rezultatas: pateikta, atmesta, laukia patikros arba reikia pakartoti.','Kas atsakingas už nepavykusį perdavimą.'),
    h('Pakartoti kopiją nėra pasirašyti dar kartą'),
    p('Pavyzdys: PDF jau išsaugotas, bet laiškas grįžta dėl netikslaus adreso. Patikslinkite gavėją ir pakartokite tos pačios galutinės versijos perdavimą. Naujo parašo prašyti vien dėl siuntimo klaidos nereikėtų automatiškai; pirmiausia patikrinkite dokumento būseną.'),
    p('Bandymui naudokite savo kontroliuojamą gavėją ir sintetinį dokumentą. Patikrinkite priedo atidarymą bei jo tapatybę. PDF darbo eigos ir saugojimo gidai padeda užbaigti visą procesą; automatizuotas siuntimas vertinamas konkrečios programos apimtyje.')
  ],
  'PS-43': [
    p('PDF šabloną paruoškite prieš prijungdami planšetę: stabilūs duomenų ir parašo laukai, aiški dokumento versija bei privalomų veiksmų taisyklės padeda išvengti parašo ne toje vietoje. Įrenginys neatlieka šablono kokybės kontrolės už jus.'),
    h('Laukų žemėlapio ruošinys'),
    l('Lauko pavadinimas ir paskirtis.','Kas jį užpildo: sistema, operatorius ar klientas.','Ar laukas privalomas ir kokį formatą priima.','Kurio pasirašytojo parašas numatytas.','Kas nutinka praleidus arba pataisius lauką.','Kada laukas užrakinamas pagal pasirinktos programos galimybes.'),
    h('Nenaudokite vien ekrano koordinatės'),
    p('Jeigu dokumento ilgis kinta, įterptas tekstas gali perkelti parašo vietą. Nuspręskite, ar šablonas naudoja patikimus laukų identifikatorius, ar programoje nustatomą paieškos ir pozicionavimo taisyklę. Konkreti galimybė priklauso nuo pasirinktos programos; ją tikrinkite su trumpu ir ilgu dokumentu.'),
    h('Bandomų dokumentų rinkinys'),
    l('Trumpiausias ir ilgiausias numatomas tekstas.','Lietuviški vardai, ilgi įmonių pavadinimai ir simboliai.','Vienas papildomas priedas arba puslapis.','Neužpildytas privalomas laukas.','Du pasirašytojai ir praleidžiamas pasirenkamas laukas.','Atnaujinta šablono versija su pakeista pastraipa.'),
    h('Priėmimas ir keitimas'),
    p('Po bandymo išsaugokite šablono versiją ir priimtų dokumentų pavyzdžius be asmens duomenų. Pakeitus šabloną, kartokite jam aktualius bandymus. Pirma sėkminga versija nepatvirtina visų būsimų dokumentų išdėstymų.'),
    p('Parašo lauko buvimas nenurodo jo teisinio lygio. Kelių pasirašytojų gidas padeda nustatyti dalyvius ir eilę; eSignatureOffice apžvalga — vertinti programinį laukų valdymą. Pradinei užklausai užtenka laukų ir dokumento kelio aprašo.')
  ],
  'PS-45': [
    p('Parašo planšetė naršyklėje gali veikti skirtingais keliais: per vietinį komponentą prie USB įrenginio arba per konkretaus NG modelio sąsają. Vien naršyklės pavadinimas neįrodo, kad planšetė bus pasiekiama. Reikia nustatyti, kur yra dokumentas, įrenginys ir pasirašymo logika.'),
    h('USB ir vietinis komponentas'),
    p('StepOver aprašo Pad Connector kaip WebSocket paslaugą naršyklei pasiekti vietinį USB įrenginį. Šis kelias turi vietinio komponento diegimo, teisių ir pasiekiamumo priklausomybes. Negalima pažadėti, kad darbuotojui nereikės jokio diegimo.'),
    h('NG kelias'),
    p('NG sąsajos vertinamos pagal konkretų modelį ir jo dokumentaciją. Tinklo naudojimui gali reikėti atskiro Ethernet priedo. USB prijungimas ir tinklo įrenginio pasiekiamumas nėra ta pati konfigūracija; tai pažymėkite integracijos apraše.'),
    h('Klausimai jūsų naršyklės aplinkai'),
    l('Koks StepOver modelis, programinis kelias ir komponentų versijos?','Kur vyksta PDF parengimas ir kur grįžta galutinis failas?','Kaip nustatomas konkretus įrenginys ir naudotojo sesija?','Kokios saugos taisyklės leidžia naršyklei pasiekti vietinę ar tinklo paslaugą?','Kas įdiegia ir atnaujina komponentą darbo vietoje?','Kaip sistema rodo, kad įrenginys nepasiekiamas?'),
    h('Bandymas, kuris atskleidžia daugiau nei demonstracija'),
    p('Patikrinkite pasirašymą iš tikros darbuotojo paskyros su įprastomis teisėmis. Įtraukite naršyklės perkrovimą, neprieinamą vietinį komponentą ir dvi vienu metu veikiančias sesijas. Kitam naudotojui neturi būti pateiktas ankstesnio kliento dokumentas.'),
    p('StepOver API pasirinkimo ir bendras integracijos gidas padeda aprašyti atsakomybes. Užklausoje pateikite naršyklę, operacinę sistemą, modelį ir dokumento kelią; konkrečios aplinkos palaikymą patvirtina bandymas.')
  ],
  'PS-24': [
    p('StepOver Office Plugin surenka parašo vaizdą ir įterpia jį į Word arba Excel dokumentą. Tai nėra tas pats, kas PDF pasirašymo procesas ar kvalifikuotas elektroninis parašas. Prieš pasirinkdami nustatykite, kokio galutinio dokumento ir parašo reikalauja jūsų procesas.'),
    h('Pirmas sprendimas — galutinis formatas'),
    p('Užrašykite, ką gavėjas turi gauti: redaguojamą Word ar Excel failą, ar pasirašytą PDF. Patikrinkite, kokia programa jis atidaromas ir kaip tikrinamas parašas. Jei reikalaujamas PDF, palyginkite Office kelio rezultatą su dokumento perdavimu į PDF pasirašymo programą.'),
    h('Aplinkos sąrašas'),
    l('Office produkto pavadinimas, versija ir architektūra.','Operacinė sistema ir naudotojo teisės.','StepOver modelis ir reikalingi vietiniai komponentai.','Word dokumento arba Excel darbaknygės struktūra.','Galutinio failo formatas, gavėjas ir jo tikrinimo programa.','Aktualios programos licencijos bei tiekimo sąlygos.'),
    h('Word bandymas'),
    p('Panaudokite dokumentą su lentelėmis, lietuviškais simboliais ir papildomu puslapiu. Patikrinkite, ar klientui pateikiamas visas sutartas turinys. Po pasirašymo atverkite galutinį failą atskiroje gavėjo darbo vietoje. Programos įskiepio įdiegimas vienoje vietoje dar nėra viso kelio priėmimas.'),
    h('Excel bandymas'),
    p('Nustatykite, kurie lapai ir kokia spausdinimo sritis sudaro pasirašomą dokumentą. Įtraukite paslėptų lapų, ilgos lentelės ir perskaičiuojamų duomenų klausimus. Dalyviai turi žinoti, kas patvirtinama, o ne vien matyti parašą šalia kelių langelių.'),
    p('Gamintojas skiria įprastą Office Plugin ir NextGen Office Plugin variantus. Konkrečią Office aplinką tikrinkite aktualioje instrukcijoje ir bandyme. PDF ir Print2NG gidai padeda palyginti kitą galutinio dokumento kelią; įskiepio sukurtas vaizdas negali būti laikomas patikrintu kvalifikuotu parašu.')
  ],
  'PS-32': [
    p('Darbuotojų dokumentams pirmiausia nustatykite dokumento rūšį ir taikomą pasirašymo reikalavimą. Darbo sutartis, supažindinimas ir vidinė forma gali turėti skirtingą paskirtį. Todėl viena parašo planšetė savaime nenustato vienos taisyklės visiems personalo dokumentams.'),
    h('Dokumentų inventorius personalo komandai'),
    l('Dokumento rūšis ir jo savininkas.','Ar reikia susitarimo, patvirtinimo, susipažinimo ar kito veiksmo.','Kas pasirašo ir kas atstovauja darbdaviui.','Kur yra darbuotojas ir kaip jam prieinamas tekstas.','Parašo bei dokumento formos reikalavimą vertinantis žmogus.','Kopijos pateikimas, saugojimas ir prieigos.'),
    h('Atskirkite darbuotojų aplinkas'),
    p('Biuro darbuotojas gali naudotis savo paskyra, o gamybos darbuotojas — bendra aptarnavimo vieta. Bendroje vietoje patikrinkite, kaip uždaromas ankstesnis dokumentas ir kaip darbuotojas gauna savo kopiją. Darbuotojo asmeninis el. paštas neturi būti numanomas vien dėl sistemos patogumo.'),
    h('Iliustracinis supažindinimo procesas'),
    p('Personalo komanda pateikia aktualios versijos dokumentą, darbuotojas jį perskaito, patvirtina sutartą veiksmą, o sistema išsaugo ryšį su dokumento versija. Pakeitus turinį, reikia spręsti, kam ir kaip jis pateikiamas iš naujo. Tai proceso pavyzdys, ne individuali darbo teisės išvada.'),
    h('Prieigų ir priėmimo patikra'),
    l('Kitas darbuotojas nemato ankstesnio asmens dokumentų.','Galutinį failą gali surasti tik įgalioti žmonės.','Darbuotojas gali perskaityti ir išsaugoti jam skirtą kopiją.','Atsisakymo, neatvykimo ar klaidos atvejis turi atsakingą žmogų.','Dokumento saugojimo terminas nustatytas pagal jo rūšį.'),
    p('Dėl konkretaus dokumento reikalavimų konsultuokitės su atsakingais teisės ir duomenų apsaugos žmonėmis. Parašo galiojimo, dokumento kopijos ir privatumo gidai padeda paruošti techninius klausimus įrangos užklausai.')
  ],
  'PS-33': [
    p('Sutikimo ar formos pasirašymo procese atskirkite duomenų užpildymą, informacijos perskaitymą ir konkretų žmogaus patvirtinimą. Parašas nepakeičia aiškaus formos turinio ir tinkamo asmens duomenų tvarkymo pagrindo.'),
    h('Formos veiksmų žemėlapis'),
    l('Kokius laukus užpildo žmogus, operatorius arba sistema?','Ką žmogus turi perskaityti prieš patvirtindamas?','Kokiam tikslui prašomas kiekvienas patvirtinimas?','Ar lauką galima praleisti ir kaip rodomas atsisakymas?','Kada forma tampa galutinė ir kur ji saugoma?','Kaip žmogus gauna jam skirtą kopiją?'),
    h('Nesuplakite kelių pasirinkimų'),
    p('Pavyzdys: aptarnavimo forma ir pasirenkamas rinkodaros sutikimas. Nežymėkite abiejų kaip vieno automatinio parašo rezultato. Jei konkretus pasirinkimas savanoriškas, procesas turi leisti pasirinkti jo nesuteikti. Tikslų teisinį pagrindą nustato už duomenų tvarkymą atsakingas asmuo.'),
    h('Ką turi parodyti klientui skirtas ekranas'),
    p('Patikrinkite teksto skaitomumą, pasirinkimų būseną, perėjimą tarp puslapių ir galimybę grįžti prie paaiškinimo. Mažesnis ekranas gali būti tinkamas parašui, bet nebūtinai ilgos formos skaitymui. Tam gali reikėti kito dokumento pateikimo kelio.'),
    h('Bandomi atvejai'),
    l('Neužpildytas privalomas laukas ir netinkamas formatas.','Atsisakytas pasirenkamas patvirtinimas.','Operatorius pataiso informaciją prieš parašą.','Ilgas tekstas ir padidintas jo mastelis.','Kopijos perdavimas bei ribotos prieigos patikra.'),
    p('Tai techninio proceso parengimas, ne universali sutikimo forma. PDF šablonų ir parašo duomenų gidai padeda aptarti laukus bei privatumą. Užklausai nurodykite formos paskirtį ir veiksmus, be klientų duomenų.')
  ],
  'PS-34': [
    p('Pasirašymui išvykoje reikia numatyti dokumento pateikimą, įrenginio gabenimą, energiją, ryšį ir saugų galutinio failo grąžinimą. Įprasto stalinio komplekto nereikėtų laikyti tinkamu išvykoms nepatikrinus jo konkrečiomis sąlygomis.'),
    h('Išvykos pasiruošimo sąrašas'),
    l('Kokį dokumentą ir jo aktualią versiją vežatės?','Koks kompiuteris, įrenginys, programa ir maitinimas reikalingi?','Ar pasirinktai eigai būtinas internetas?','Kur žmogus gali ramiai perskaityti dokumentą?','Kur laikomas failas iki grąžinimo į įmonės saugyklą?','Kas vyksta praradus ryšį arba įrangą?'),
    h('Neprisijungęs procesas turi būti patikrintas'),
    p('Jei reikia dirbti be interneto, reikalavimą nurodykite iš anksto. Atskirkite programos paleidimą, licencijos patikrą, tapatybės nustatymą, pasirašymą ir vėlesnį siuntimą. Vien tai, kad dokumentą galima atidaryti be ryšio, neįrodo, kad visa pasirašymo eiga veiks neprisijungus.'),
    h('Iliustracinis pristatymo scenarijus'),
    p('Darbuotojas atvyksta perduoti įrangos, gavėjas patikrina komplektaciją ir pastabas, perskaito aktą ir atlieka sutartą patvirtinimą. Darbuotojas turi matyti, ar failas galutinis ir ar jau grąžintas į saugyklą. Neišsiųstas failas neturi pasimesti uždarius kompiuterį.'),
    h('Duomenys ir fizinis saugumas'),
    l('Nenaudokite asmeninių paskyrų be sutartos tvarkos.','Apribokite prieigą prie laikinų dokumentų ir užrakinkite kompiuterį.','Suderinkite įrangos dėklą, kabelių ir rašiklio apsaugą.','Numatykite grąžinimo patikrą ir laikinos kopijos pašalinimą pagal įmonės taisykles.'),
    p('Šis gidas nesiūlo universalaus lauko darbams atsparaus modelio. Perdavimo aktų ir vietinio bei nuotolinio pasirašymo gidai padeda pasirinkti procesą. Į užklausą įrašykite išvykos sąlygas ir ryšio ribas.')
  ],
  'PS-38': [
    p('Pasirašyto PDF saugojimas turi užtikrinti failo tapatybę, tinkamas prieigas ir galimybę dokumentą surasti bei atkurti. Atsarginė kopija ir ilgalaikė elektroninio parašo patikra yra skirtingos užduotys. Vieno saugojimo termino visiems dokumentams nėra.'),
    h('Dokumento įrašo ruošinys'),
    l('Dokumento ID, rūšis ir galutinė versija.','Proceso savininkas ir saugyklos vieta.','Kas turi skaitymo, keitimo arba administravimo prieigą.','Taikomas saugojimo terminas ir jo pagrindas.','Susieti priedai ir klientui pateikta kopija.','Parašo tikrinimo bei atkūrimo tvarka.'),
    h('Paieškai neužtenka žmogaus vardo'),
    p('Failus siekite su stabiliais dokumentų identifikatoriais. Vardas ar data gali pasikartoti, o perteklinis asmens duomenų kiekis failo pavadinime gali būti matomas platesniam žmonių ratui nei pats dokumentas. Metaduomenų ir pavadinimo taisyklę suderinkite su prieigų valdymu.'),
    h('Atkūrimo bandymas'),
    l('Pasirinkite sintetinį galutinį dokumentą ir susietą priedą.','Atkurkite kopiją į atskirą bandomą vietą.','Patikrinkite turinį, dokumento ID ir parašo informaciją.','Įsitikinkite, kad atkurtą failą gali gauti tinkamas naudotojas.','Užrašykite atliktą veiksmą, trukmę ir likusias problemas.'),
    h('Ilgesnio laikotarpio klausimai'),
    p('Kai dokumentas bus naudojamas po daugelio metų, vien failo išsaugojimo gali nepakakti norimam parašo patikros procesui. Reikalingas sprendimas priklauso nuo parašo, formato, saugojimo laikotarpio ir institucijos reikalavimų. Nevadinkite įprastos atsarginės kopijos kvalifikuota archyvavimo paslauga.'),
    p('Konkrečius terminus nustato už dokumentų rūšį atsakingas žmogus. PDF parašo patikros ir kopijos klientui gidai padeda atskirti tikrinimą, perdavimą bei saugojimą. Užklausoje aprašykite saugyklą, prieigas ir paieškos poreikį.')
  ],
  'PS-40': [
    p('Nutrūkus pasirašymui pirmiausia nustatykite galutinio dokumento būseną. Nekartokite parašo automatiškai vien todėl, kad operatoriaus lange nematomas sėkmės pranešimas. Failas galėjo būti išsaugotas, bet negrąžintas, arba procesas galėjo likti nebaigtas.'),
    h('Klaidų medis'),
    l('Įrenginys nepasiekiamas: patikrinkite modelį, ryšį ir programos rodomą klaidą.','Dokumentas nerodomas: nustatykite, ar jis parengtas ir perduotas tinkamu keliu.','Parašas atliktas, bet nėra rezultato: patikrinkite proceso būseną ir sutartą išsaugojimo vietą.','Failas yra, bet kopija neišsiųsta: atskirkite perdavimo klaidą nuo pasirašymo.','Neaišku, ar dokumentas galutinis: stabdykite pakartojimą ir kreipkitės į proceso atsakingą žmogų.'),
    h('Saugaus pakartojimo klausimai'),
    p('Ar ankstesnis bandymas uždarytas? Ar turite tą pačią dokumento versiją? Ar programa atpažįsta pakartotinį bandymą? Ar nebus perrašytas jau galutinis failas? Pakartojimo taisyklę priimkite pilote; savarankiškai trinti programos failų ar keisti parašų nerekomenduojame.'),
    h('Ką užrašyti palaikymui'),
    l('Tikslus klaidos tekstas ir laikas.','StepOver modelis, programos ir operacinės sistemos versijos.','Dokumento proceso ID be perteklinių asmens duomenų.','Paskutinis sėkmingas veiksmas ir tai, kas matoma dabar.','Ar rastas galutinis failas ir kur jis saugomas.','Ar problemą galima atkartoti sintetiniu dokumentu.'),
    h('Pavyzdys: išsaugojimo vieta laikinai neprieinama'),
    p('Tai iliustracinė situacija. Operatorius pamato klaidą po parašo. Prieš prašydamas kliento kartoti veiksmą jis patikrina, ar programa turi baigtą rezultatą ir sutartą jo grąžinimo kelią. Jei būsena neaiški, sprendžia atsakingas palaikymo žmogus.'),
    p('Piloto gidas padeda iš anksto aprašyti klaidų atvejus; dokumento saugojimo gidas — patikrinti rezultatą. Šiame puslapyje nepateikiami neatliktų gedimo bandymų rezultatai ar universali remonto procedūra.')
  ],
  'PS-46': [
    p('Parašo planšetės valymą, rašiklio ir kabelio keitimą atlikite pagal konkretaus StepOver modelio gamintojo instrukciją. Panašiai atrodantys priedai nėra automatiškai suderinami. Prieš užsakant priedą reikia tiksliai identifikuoti įrenginį.'),
    h('Priedo užklausos ruošinys'),
    l('Tikslus modelio pavadinimas ir įrenginio identifikacija.','Kokio priedo reikia: rašiklio, kabelio, tvirtinimo ar kito elemento.','Ar priedas pamestas, pažeistas, ar reikia papildomo komplekto.','Kas nurodyta turimo priedo etiketėje.','Naudojama programa ir ryšio kelias.','Kiekis ir atsarginio įrenginio poreikis.'),
    h('Valymas be spėjimo'),
    p('Nenurodome vieno valiklio ar jo koncentracijos visiems modeliams. Patikrinkite gamintojo leidžiamą priemonę, paviršių ir veiksmų tvarką. Jei instrukcijos nėra, prieš veiksmą kreipkitės dėl modelio dokumentacijos. Netinkamos priemonės gali pažeisti ekraną ar korpusą.'),
    h('Rašiklis ir laidas'),
    p('Keitimo būdą nustato konkretaus modelio konstrukcija. Neardykite korpuso vien todėl, kad priedas atrodo lengvai pakeičiamas. Užklausoje galima pateikti priedo identifikaciją be klientų dokumentų ar ekrane matomų parašų.'),
    h('Pakeisto įrenginio priėmimas'),
    l('Patikrinkite modelį ir reikalingus komponentus.','Atlikite vieno sintetinio PDF visą pasirašymo eigą.','Patikrinkite įrenginio priskyrimą darbo vietai arba sesijai.','Įsitikinkite, kad galutinis failas grįžta į teisingą saugyklą.','Užrašykite pakeitimą inventoriuje ir sutvarkykite seno įrenginio duomenis pagal jo instrukciją.'),
    p('Garantijos, remonto, priedų kaina ir tiekimo terminas patvirtinami konkrečiame pasiūlyme. Modelių katalogas padeda atpažinti įrangą; pasirašymo piloto gidas — patikrinti pakeitimo rezultatą.')
  ],
  'PS-25': [
    p('webSignatureOffice ir webSignatureOffice Lite yra skirtingi StepOver debesijos pasiūlymai nuotoliniam pasirašymui. Juos lyginkite pagal proceso valdymą, dalyvius ir integraciją, o ne vien pagal žodį „cloud“. Tai informacinė atranka: paslaugos aktyvavimas, sutartis ir mūsų komercinis pasiūlymas vertinami atskirai.'),
    h('Pilnesnis ar paprastesnis procesas'),
    p('Gamintojas webSignatureOffice aprašo kaip konfigūruojamą debesijos kelią, o Lite — kaip paprastesnį pradžios variantą. Jei reikia programinės integracijos, kelių dalyvių valdymo ar savų procesų taisyklių, juos įrašykite į reikalavimus ir tikrinkite konkretaus produkto dokumentacijoje.'),
    h('Palyginimo ruošinys'),
    l('Dalyviai: kas siunčia, kas pasirašo ir kas administruoja paskyras?','Dokumentas: kaip jis pateikiamas, peržiūrimas ir grąžinamas?','Tapatybė: kokį patvirtinimą bei parašo lygį reikia užtikrinti?','Valdymas: ar reikalingi šablonai, automatizavimas ir API?','Duomenys: kur jie tvarkomi, kas turi prieigą ir kokios sutarties sąlygos?','Išėjimas: kaip dokumentai eksportuojami nutraukus paslaugą?'),
    h('Apps ir PrintToCloud vaidmuo'),
    p('Gamintojo kataloge mobiliosios programos ir PrintToCloud pateikiami kaip susiję proceso įrankiai. Prieš pasirinkimą patikrinkite, ar konkrečiame procese jų reikia ir su kokia paslaugos versija jie veikia. Papildomo įrankio pavadinimas nėra automatinė jūsų sistemos integracija.'),
    h('Nuotolinio bandymo sąrašas'),
    l('Kvietimas pasiekia kontroliuojamą bandomą gavėją.','Gavėjas mato teisingą dokumentą ir gali atsisakyti.','Neužbaigtas procesas atskiriamas nuo galutinio.','Galutinį failą galima gauti ir patikrinti pasirinktoje aplinkoje.','Paskyrų bei dokumentų prieigos atitinka sutartą tvarką.'),
    p('Lietuvos kainų, aktyvios mūsų debesijos paslaugos ar konkretaus parašo lygio čia nežadame. Vietinio ir nuotolinio pasirašymo gidas padeda pasirinkti kryptį; užklausoje pateikite dalyvius, dokumento rūšį ir integracijos poreikį.')
  ],
  'PS-26': [
    p('StepOver nextGen Pad 5 yra atskiras NG šeimos modelis. Jo nereikia painioti su duraSign Pad 5.0: panašus ekrano dydis nereiškia tos pačios technologijos ar programinio kelio. Čia pateikiame gamintojo modelio atrankos klausimus; prieinamumas ir komplektas patvirtinami užklausoje.'),
    h('Modelio tapatybė ir dokumento kelias'),
    p('Gamintojas nextGen Pad 5 aprašo kaip 5 colių NG įrenginį, kuriame vyksta PDF apdorojimas ir pasirašymo procesas. Šią tapatybę tikrinkite pasiūlyme, sąskaitoje ir įrenginio etiketėje. Senesnio duraSign Pad 5.0 aprašymo ar nuotraukos šiam modeliui naudoti negalima.'),
    h('USB ar tinklas'),
    p('Gamintojo aprašyme tinklo keliui nurodytas papildomas Ethernet Connection Kit 2.0. Todėl „network compatible“ nėra pažadas, kad tinklo priedas jau įtrauktas į bazinį komplektą. Užklausoje aiškiai nurodykite, iš kurios darbo vietos ir kokiu ryšiu pateiksite dokumentą.'),
    h('Palyginimas su kitais modeliais'),
    l('Su duraSign Pad 5.0: pirmiausia lyginkite pasirašymo technologiją ir programos kelią.','Su NG 10: vertinkite dokumento skaitomumą, puslapių išdėstymą ir darbo vietos erdvę.','Su turima įranga: tikrinkite šablonus, grąžinamą PDF ir įrenginio administravimą.','Visais atvejais: atskirai patvirtinkite reikalingus priedus, funkcijas ir programų licencijas.'),
    h('Bandymo klausimai'),
    l('Ar klientas patogiai perskaito jūsų kelių puslapių dokumentą?','Ar veikia sutartas USB arba tinklo kelias?','Kaip dokumentas grįžta ir kas patvirtina jo išsaugojimą?','Kaip atšaukiamas bandymas ir uždaromas ankstesnis dokumentas?'),
    p('Gamintojo nurodomas greitas paleidimas nepakeičia jūsų proceso priėmimo. Neskelbiame nepatvirtinto likučio, pristatymo termino ar įrangos atsparumo garantijos. Modelių palyginimas ir programų apžvalga padeda paruošti konkretaus komplekto užklausą.')
  ],
  'PS-47': [
    p('Tikro piloto rezultatų aprašymui reikia faktinės aplinkos, bandymų įrašų, išmatuotų rezultatų ir leidimo skelbti. Šiame juodraštyje kliento ar rezultatų nėra. Jis lieka privatus iki realaus piloto įrodymų; jo negalima pateikti kaip atlikto diegimo istorijos.'),
    h('Duomenys būsimam atvejui'),
    l('Dokumento procesas ir pradinė problema.','Tikras modelis, programos versija ir aplinka.','Bandymo metodas, dokumentų bei bandymų skaičius.','Pavykę ir nepavykę scenarijai su aiškiais vardikliais.','Faktinis laikas, likę rankiniai veiksmai ir ribos.','Kliento bei vaizdų skelbimo teisės, anonimizavimo sprendimas.','Priėmimo, plėtros arba atsisakymo sprendimas.'),
    h('Kas nėra rezultato įrodymas'),
    p('Sintetinis pavyzdys, sugeneruota nuotrauka, API aprašymas ar svetainės techninis testas neįrodo tikro kliento pasirašymo piloto. Pasirašymo piloto planavimo gidas jau yra atskiras naudingas atsakymas; šio patirties puslapio negalima užpildyti jo kopija.')
  ],
  'PS-41': [
    p('Parašo duomenų privatumas vertinamas pagal tai, kokie duomenys faktiškai renkami, kam naudojami ir kas juos pasiekia. Parašo vaizdas, judesio duomenys ir asmens identifikavimo tikslas nėra vienas klausimas. Planšetės įsigijimas nepakeičia duomenų valdytojo atsakomybių.'),
    h('Pradėkite nuo duomenų inventoriaus'),
    l('Dokumente esantys asmens duomenys.','Matomas parašo vaizdas.','Dinaminiai parašo duomenys, jei juos renka pasirinkta sistema.','Tapatybės ar atstovavimo patikros informacija.','Sesijos, įrenginio ir techninio žurnalo įrašai.','Laikinos kopijos, galutinis PDF ir atsarginės kopijos.'),
    h('Biometrinių duomenų klausimas'),
    p('BDAR biometrinių duomenų apibrėžimas siejamas su specialiu techniniu apdorojimu, leidžiančiu unikaliai nustatyti ar patvirtinti žmogaus tapatybę. 9 straipsnis apima biometrinių duomenų tvarkymą unikalaus identifikavimo tikslu. Todėl nei visų parašo duomenų priskyrimas šiai kategorijai, nei jų automatinis atmetimas yra tinkama bendroji taisyklė.'),
    h('Inventoriaus eilutės ruošinys'),
    l('Duomenys ir konkretus tvarkymo tikslas: …','Valdytojas bei tvarkytojas: …','Vertinamas teisinis pagrindas ir, jei reikia, papildoma sąlyga: …','Kas turi prieigą ir kaip ji suteikiama: …','Saugojimo laikas bei jo pagrindas: …','Perdavimas, šifravimas ir laikinos kopijos: …'),
    h('Ką patikrinti prieš įdiegimą'),
    p('Nubraižykite kelią nuo planšetės iki programos, saugyklos ir gavėjo. Patikrinkite, ar žurnalai nekaupia nereikalingo dokumento turinio ir ar darbo vietoje nelieka prieinamų ankstesnio kliento failų. Debesijos kelyje papildomai vertinkite paslaugos sutartį ir duomenų tvarkymo vietą.'),
    p('Teisinio pagrindo ar poveikio vertinimo sprendimą priima už duomenų apsaugą atsakingi žmonės pagal realų procesą. Vien checkbox ar gamintojo bendras atitikties teiginys šio darbo nepakeičia. Parašo galiojimo ir saugojimo gidai padeda paruošti susijusius klausimus.')
  ]
};
