import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {taxonomy,backlog} from './data.mjs';
import {outputs} from './build-plan.mjs';
const ids=new Map();for(const c of taxonomy.categories){assert(['core','extension'].includes(c.scope));for(const [type,rows] of [['category',[c]],['group',c.groups],['treatment',c.groups.flatMap(g=>g.treatments)]])for(const row of rows){assert(!ids.has(row.id),'Duplicate ID '+row.id);ids.set(row.id,type);assert(row.label.trim());if(type==='treatment'){assert.equal(row.priceMinor,null);assert.equal(row.durationMin,null);assert.equal(row.bookingMode,'provider-configured');}}}
assert.equal(taxonomy.categories.filter(c=>c.scope==='core').length,14);assert.equal(taxonomy.categories.filter(c=>c.scope==='extension').length,7);
const legacy=['manikiuras','gelinis-lakavimas','nagu-dizainas','pedikiuras','kirpimas','plauku-dazymas','antakiai','blakstienos','masazas','veido-prieziura'];assert.deepEqual(taxonomy.legacyMappings.map(m=>m.legacyId).sort(),legacy.sort());for(const m of taxonomy.legacyMappings){assert.equal(ids.get(m.targetId),m.targetType);assert(m.preserveServiceId&&m.preserveBookingSnapshot);}
const tasks=new Map(backlog.tasks.map(t=>[t.id,t]));assert.equal(tasks.size,backlog.tasks.length);const visiting=new Set(),done=new Set();function visit(id){assert(tasks.has(id),'Unknown dependency '+id);assert(!visiting.has(id),'Dependency cycle '+id);if(done.has(id))return;visiting.add(id);for(const dep of tasks.get(id).dependsOn){assert(Number(tasks.get(dep).phase)<=Number(tasks.get(id).phase),'Later phase prerequisite '+id);visit(dep);}visiting.delete(id);done.add(id);}for(const t of tasks.values()){assert(t.acceptance.length>=2);assert(['P0','P1','P2'].includes(t.priority));assert.equal(t.status,'planned');assert(t.files.length);visit(t.id);}
for(const [name,contents] of Object.entries(await outputs()))assert.equal(await readFile(new URL(name,import.meta.url),'utf8'),contents,'Stale generated file '+name);
const plan=await readFile(new URL('PLAN.md',import.meta.url),'utf8');for(const name of ['TAXONOMY_PROPOSAL.json','BACKLOG.json','AUDIT.md','index.html'])assert(plan.includes(name));assert(plan.includes('dar neįdiegti'));const html=await readFile(new URL('index.html',import.meta.url),'utf8');assert(!/<script[^>]+src=/.test(html));assert(!/https?:\/\//.test(html.split('<script id="plan-data"')[1]));
console.log(JSON.stringify({status:'PASS',checks:['unique taxonomy IDs','14 core and 7 extension categories','no fabricated price or duration','all 10 legacy IDs mapped','backlog IDs and acceptance','acyclic dependencies and ordered phases','generated files exact','offline original HTML'],nodes:ids.size,tasks:tasks.size}));
